### ISSUE TITLE
Micromasters home page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1]
As a learner, I would like a single view of all Micromasters offerings from MIT

For MVP, there will be only one micromasters offering, SCM. 

- [ ] initial project setup
  - [ ] set up test infra
  - [ ] use cookie cutter
  - [ ] set up CI
- [ ] schema for micromasters

**Comment by justinabrahms** [comment]
This will be done when #11 is done, I believe.

**Comment by pdpinch** [comment]
Closing in favor of #11, and the other set-up stories.
