### ISSUE TITLE
Add program page URLs to Program API

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1003]
Required to support program page links in the enrollment dialog

**Comment by noisecapella** [comment]
#796 shows a link to the program page when you enroll in a new program. In order to support that we need the program page URLs exposed in a REST API

**Comment by pdpinch** [comment]
There are two cases that need to be supported by this:

1. Link to program page from the Wagtail CMS
2. Link to external URL specified in program model

**Comment by noisecapella** [comment]
It looks like this was done already, in #1571. It doesn't handle the external URL case though
