### ISSUE TITLE
Issues with dashboard page

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1009]
From @pdpinch, made in a comment on #993:

I see a couple of issues with this screenshot:

- [x] The text "You need to upgrade..." is supposed to only appear when the user clicks on the question mark. But more importantly, we should check with @roberthouse54 to see if this is needed at all, when the program doesn't offer financial aid.
- [x] If we do want the (?) icon, it's the wrong color, and it should be next to the price, not in the left column. 
- [x] It shouldn't say "(enrolled)" in parentheses after the course title. 
- [x] Where's the start date? Or is that another for another PR?
- [x] The buttons look wrong

@roberthouse54

**Comment by roberthouse54** [comment]
After this is completed, I think we are going to add another Issue to make sure that the Courses Widget is displaying all of the course statuses correctly, and that we are getting all the required data in the API. @pdpinch @gsidebo @noisecapella

**Comment by pdpinch** [comment]
Is #1015 what you have in mind?

**Comment by roberthouse54** [comment]
George said this issue is for discovery work to see which statuses are not currently covered, and what data is not currently being sent in the API.
