### ISSUE TITLE
Error message shown briefly when user enters dashboard for first time

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1020]
I couldn't get a screenshot of this, it's probably more noticeable when the user is not on a fast network though

**Comment by gsidebo** [comment]
do you know what error message it was?

**Comment by noisecapella** [comment]
No it was too brief to read it. I recently added error handling for program enrollments, I feel like it may be the error message for that

**Comment by aliceriot** [comment]
I've noticed this as well

**Comment by pdpinch** [comment]
We think it's the program enrollment error message. It may be addressed by another issue.

**Comment by aliceriot** [comment]
I think this may have been fixed by https://github.com/mitodl/micromasters/pull/1271
