### ISSUE TITLE
Dashboard: Handle verification start and end dates

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1021]
This data would need to be added to the `CourseRun` model and to the relevant part of the dashboard API. Then we need a design and implementation for how to display course runs which are enrolled but not verified and are outside the verification date.

Related issues: #833

**Comment by pdpinch** [comment]
@roberthouse54 we need a design for this case when the user has failed to purchase (verified or financial aid) before the deadline. 

Some possibilities: omit the course_run altogether; treat it as a failed course
