### ISSUE TITLE
Dashboard: Update enrollment status text

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1022]
See mockup in #925 

 - [ ] It should move from the right column to the middle 
 - [ ] Show 'Enrollment open' if user is not enrolled and is allowed to enroll, or if the user is already enrolled but not verified
 - [ ] If the course is verified show 'You are enrolled in this course'
 - [ ] If the course is passed show 'You passed this course!'
 - [ ] If the course is failed show 'You failed this course' inside a red box like in the mockup

**Comment by pdpinch** [comment]
I'm going to close this since we're going with a different design and text now.
