### ISSUE TITLE
Dashboard: enrollment not open (and after enrollment has ended)

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1023]
- [ ] We need to expose the `enrollment_end` date in the dashboard API, and make sure it's also exposed for enrolled but not verified courses, not just offered courses
 - [ ] We need a design for this case
 - [ ] Implement the design in the UI.

### Enrollment Not Open 

![image](https://cloud.githubusercontent.com/assets/430126/18766995/d7372da2-80ea-11e6-9e97-d21b11ac6b82.png)

When enrollment is not open, the button and the “Enroll” link are both hidden.

### Enrollment Not Open - Fuzzy Dates

![image](https://cloud.githubusercontent.com/assets/430126/18767006/df7da306-80ea-11e6-84c3-b157d4c8f0b5.png)

If there are “fuzzy dates” for the Start Date or the Enrollment start date, display them as shown.

### No Future Course Runs are defined

<img width="607" alt="screen shot 2016-09-22 at 5 35 29 pm" src="https://cloud.githubusercontent.com/assets/430126/18767039/00a928de-80eb-11e6-8990-00683b3453ea.png">

If there are no future course runs that have been created, show this status.

**Comment by pdpinch** [comment]
@noisecapella why would we need to display a course whose enrollment_end date has passed? Wouldn't we just omit it from the dashboard?

FYI @roberthouse54

**Comment by noisecapella** [comment]
That's fine with me, we just need the logic to do so

**Comment by gsidebo** [comment]
First two states are already implemented, and I have a PR up which takes care of the last one (#1261)
