### ISSUE TITLE
Dashboard: Update grade

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1024]
Depends on #762 
See design in #925 

- [ ] show grade for passed course in place of check mark, and add 'Final grade'
 - [ ] show current grade for failed and verified courses and the relevant text underneath
 - [ ] show '--' for enrolled but not verified courses

**Comment by gsidebo** [comment]
this should be closed, correct?

**Comment by pdpinch** [comment]
Yep. Although I don't know which commit in particular closes it.
