### ISSUE TITLE
Dashboard: Upgrade button

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1025]
![image](https://cloud.githubusercontent.com/assets/430126/18618182/4f51926c-7daf-11e6-9b64-f77892080deb.png)

- [ ] When a user in enrolled in the audit track, there should be a grey box explaining that the user needs to upgrade. The upgrade button should move within the grey box.

Note that learners in an personalized pricing program (like DEDP) will upgrade on the MM portal, but learners in other programs will upgrade on edx.org.

**Comment by pdpinch** [comment]
added a screenshot to the description.

**Comment by pdpinch** [comment]
I'm going to close this, because we're going with a different design and different wording now.
