### ISSUE TITLE
move setup commands in `travis.yml` into the `install` section

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#1030]
Our travis build output is super long, and a good chunk of it is `apt`, `pip` and `npm` spewing out package install info.

If we move these commands out of `script` and put them into `install` we can automatically collapse all that stuff - it's still there to look at if we want, but it's collapsed by default.

@noisecapella @giocalitri @blarghmatey is there any reason not to do this?

**Comment by aliceriot** [comment]
I made these changes on a branch, you can see what the build looks like here: https://travis-ci.org/mitodl/micromasters/builds/159946659

changes: https://github.com/mitodl/micromasters/compare/ap/test-travis-change

**Comment by noisecapella** [comment]
Nope, sounds like a good idea to me

**Comment by aliceriot** [comment]
kk, I'll open a quick pr then!
