### ISSUE TITLE
Homepage: add a short description field on the ProgramPage and display it in the home page

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1040]
Related to #919

**Comment by Ferdi** [comment]
@noisecapella @pdpinch I think this is done , right ?

**Comment by noisecapella** [comment]
No, the problem is that we are using `Program.description` which is in the Django model, but we should be using something like `ProgramPage.homepage_description` which exists in the CMS so other people can edit it.

**Comment by Ferdi** [comment]
Ok, added this in epic #1111

**Comment by pdpinch** [comment]
I'm closing this. We don't want to let the program teams have direct control over the home page.
