### ISSUE TITLE
Financial Aid: creating new requests

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1041]
# Acceptance criteria:

- [x] API endpoint for new financial aid request (takes income and currency)
  we can focus on USD for now
- [x] Calculation of pending financial aid tier
- [x] Auto acceptance criteria for requests
- [x] Import of per-country thresholds for auto acceptance; these will be global for all programs

**Comment by pdpinch** [comment]
@zags you told me that you have started this already. Can you add some details here about what (additional) assumptions you're making beyond the criteria above?

**Comment by zags** [comment]
There are a couple assumptions we are making (based on the algorithm sent to us by the econ team and how coupons work):
* Financial aid tiers correspond to a fixed-discount style coupon.  Consequently, a tier corresponds to the notion of "$500 off on all courses in the program".  The specific discount number varies between tiers and can be increased later.
* The financial aid tier someone gets a pending match with is based solely on reported income.  Country of residence is only used for autoa-cceptance and not tier placement.
* The income threshold for tier qualification can be different between courses, but the income thresholds by country for auto-approval are global
* Each country has an income threshold above which we auto-approve its residents (this is a mathematical equivalence with the code sent to us by the econ department).  These thresholds are fairly coarse right now: a country only has an auto-approve income threshold of 0, $15k, $50k, or$100k based on the data they have sent us.  This can be refined later in the thresholds data file if needed.

**Comment by pdpinch** [comment]
In the 3rd bullet, the variability of income thresholds would be between programs, not courses. As we only have one program for October 15th (and the rest of the calendar year), I'm not sure this is an important distinction.
