### ISSUE TITLE
Financial Aid: file storage configuration

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1043]
# Acceptance criteria 
- [ ] Django-storages configuration
- [ ] S3 encryption at rest configuration
- [ ] Ensure secure connection to S3
- [ ] Ensure files created by django-storages on S3 are private

**Comment by pdpinch** [comment]
@blarghmatey let me know how much of this configuration stuff is in your bailiwick

**Comment by zags** [comment]
Some of this is  going to be in django settings (we've got most of the needed settings in SGA-LTI).

**Comment by pdpinch** [comment]
Ok then. Let's assign to you and then if you need assistance you can bring in @Tobias.

**Comment by alvinsiu** [comment]
Relevant docs: http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html

**Comment by alvinsiu** [comment]
I unassigned Zags as we're no longer going to do the uploads.
