### ISSUE TITLE
Financial Aid: Auto-Approved requests

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1044]
When a user's financial aid request is auto-approved their dashboard updates with a message and all their prices are updated to reflect their personal price.

![image](https://cloud.githubusercontent.com/assets/430126/18765704/e11faa98-80e4-11e6-8c91-19c69ba49249.png)

## Acceptance criteria:

- [x] API endpoint for getting a user's price for a course
- [ ] Update message
- [ ] Update course statuses to display "Pay Now - $$$" button, with appropriate price

**Comment by alvinsiu** [comment]
These criteria will probably change given the recent update. @pdpinch will you be updating these?

**Comment by pdpinch** [comment]
I've updated this to reflect the decision to not use coupons.

**Comment by alvinsiu** [comment]
@pdpinch  I think the API endpoint for getting a user's price still makes sense to be a part of financial aid, but should

> Modify the API endpoint for enrolling in a course to initiate the ecommerce flow (instead of redirecting to edX.org)

still to be handled by the financial aid flow?  I'm not too familiar with the stories, but I think it makes more sense for that to be handled as part of ecommerce.

**Comment by noisecapella** [comment]
I agree, all the ecommerce needs is the price to charge at that point

**Comment by pdpinch** [comment]
I don't disagree, but we still need the story. Would you like to create a new one, or can we just assign this issue to someone else once you've finished the first checkbox?

**Comment by alvinsiu** [comment]
I'm not sure how your process works for stories.  For the issue, it would probably be simpler to just assign the issue to someone else once we finish with the first checkbox - but this might complicate pull request if we want to do one pull request per issue.  That, or we can mark the first pull request for the first checkbox with "Work in progress"?

**Comment by pdpinch** [comment]
It doesn't have to be one PR per issue. Just check the box when that bit has been merged.

**Comment by alvinsiu** [comment]
Great, thanks!

**Comment by alvinsiu** [comment]
Oops - didn't mean to close it with the PR.  The endpoint for course price is merged, the other two items are still pending but I think falls under @aliceriot's expertise.

**Comment by pdpinch** [comment]
@noisecapella @aliceriot I'm not sure if this is already done. Feel free to close if it is.

**Comment by noisecapella** [comment]
Yes I think every item is done in the list
