### ISSUE TITLE
Financial Aid: Review Page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1045]
Simple list of financial aid submissions, for review. 

![image](https://cloud.githubusercontent.com/assets/430126/18748865/50a040c8-80a2-11e6-9715-0a7ce2a60c0f.png)

# Acceptance Criteria:

- [ ] Remove "reject" button  /cc @roberthouse54 
- [ ] Rename "approve" checkmark with label "Save"  /cc @roberthouse54 
- [ ] Move "adjusted cost" column close to "Save" button
- [ ] Add a dropdown with a couple of predefined values that will allow reviewer to log a justification for adjusting the cost (e.g  "Docs not notarized" , "Insufficient Docs")
- [ ] Button for documents received
- [ ] Date calculated
- [ ] Date docs sent
- [ ] Radio button for displaying income in dollars or local currency (as calculated, not real time)
- [ ] Modified `PUT` requests for `FinancialAidActionView` to `PATCH` requests to better follow REST
- [ ] Changed `FinancialAidMailView` to use a serializer and to take a `FinancialAid` object instead of email recipient for security and auto-message-generation reasons
- [ ] Linked backend functionality for emailing, approving, and marking documents as received to the frontend
- [ ] UI selectively shows/hides sections and functionality depending on the status selected to view
- [ ] Updated labels and copy
- [ ] Search by name functionality
- [x] Make some of the columns sortable 
- [x] API endpoint for requests given a status (searchable, sortable and pageable)
- [x] simple search for user name
- [x] fields for each request include income of an applicant (as submitted in local currency and as dollars as calculated), date of calculation, document status
- [x] Limit API endpoints to staff in the appropriate program
- [x] API endpoint to get dollar values of each tier (for populating drop-down)

**Comment by pdpinch** [comment]
Note that we modified this UI to allow the reviewer to choose the adjusted cost and override the cost proposed by the algorithm. Allowing this reviewer discretion means we can stop debating the outcome of rejected applications.

**Comment by zags** [comment]
I talked with @giocalitri and we decided that the best approach for this page and it's children was to implement them as Django templates using Django forms rather than API endpoints with react.  This is because it will be faster to build them that way, and they are only accessible to select staff

**Comment by alvinsiu** [comment]
@pdpinch For the "API endpoint to get the income of an applicant and list of document names" criteria, the API endpoint for getting a list of document names is also in #1042 and depends on getting S3/django-storages set up before that can be implemented.  Would it make more sense to remove that criteria from this PR and just have a placeholder for now?  We could add that to #1042 instead?

**Comment by pdpinch** [comment]
I removed the mention of document names from the description, since we won't be storing documents anymore (and it was out of scope for this issue anyway).

**Comment by pdpinch** [comment]
Updated screenshot in description. Note that it now includes:

- [ ] search
- [ ] a checkbox for "documents received"
- [ ] radio button for displaying income in dollars or local currency (as calculated, not real time). 
- [ ] date calculated

**Comment by Ferdi** [comment]
I have updated the description , pls have a look /cc @zags @pdpinch

**Comment by alvinsiu** [comment]
Makes sense to me!

**Comment by alvinsiu** [comment]
[PR](https://github.com/mitodl/micromasters/pull/1161) is ready for review for this issue.  The only thing remaining is a list of justifications, and then any other requested tweaks/changes (which should probably be a new issue).

**Comment by pdpinch** [comment]
@alvinsiu can you update the checkboxes in the description based on the current state of the PR?

**Comment by alvinsiu** [comment]
Updated!

**Comment by pdpinch** [comment]
Hm. Something's not working. It looks like fewer boxes are checked since the last time I looked. 

In your opinion, is there anything not checked?

**Comment by alvinsiu** [comment]
Looks right to me - just added a bunch between "Button for" and "Search by".  Some of these were from comments on this issue, some of them updates from our meetings, and some just more flushed out details about existing requirements.
