### ISSUE TITLE
Financial Aid: auditing

### ISSUE THREAD

**Issue by zags** [mitodl/micromasters#1047]
# Acceptance criteria 
- [ ] Track status changes to financial aid requests
- [ ] Track status changes to tier changes
- [ ] Track initial emails to financial aid recipients

**Comment by zags** [comment]
The database plan is to have three separate databases for each type of event we are tracking (so keep the one you have and add two).  This has probably the largest code footprint, and makes adding new types of auditing the hardest, but it makes the audit history the easiest to automatically process later.  Audit events look approximately like:

    <obj StatusChange>
    old_object = {"status": "created", ...}

    <obj ApplicantEmailed>
    body = "I would like more details about ..."

    <obj DocumentView>
    document = "..."

**Comment by zags** [comment]
@pdpinch Do we need to track the text of the email that was sent?

**Comment by pdpinch** [comment]
Yes we should log e-mail body, but more for user convenience (in the future) than for auditing. 

If it's really hard, you can drop it.

**Comment by pdpinch** [comment]
Removed `- [ ] Track when a coupon is allocated to a financial aid request` from description.

**Comment by alvinsiu** [comment]
Removed Track when someone views a financial aid document

**Comment by Ferdi** [comment]
are we working on this ?

**Comment by pdpinch** [comment]
Alvin told me they had started and expected it to be done Tuesday.

**Comment by Ferdi** [comment]
Great , moved it to ready
