### ISSUE TITLE
Financial Aid: Currency Conversion

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1048]
# Acceptance Criteria

- [x] Currency conversion API
- [x] Cache currency conversion results and only refetch if cache is missing or older than a day
- [ ] API endpoint to get default currency for a user (or have the data file used on frontend)

## Questions

- [x] front-end (JavaScript) API or backend?

**Comment by alvinsiu** [comment]
We should probably be doing this on the backend for better auditing and to be able to cache results from the API.

**Comment by alvinsiu** [comment]
Removed - will be doing backend:

> ## Questions
> 
> - [x] front-end (JavaScript) API or backend?

**Comment by alvinsiu** [comment]
@pdpinch Are there any business requirements about what currencies we need to support or not support?  And do we need to display that information on the frontend somewhere?

Right now, the way we've designed it, the API endpoint will return a ValidationError if the currency isn't supported by the library we use, and the celery task will ensure all all exchange rates are up to date (and consequently add new ones and delete no-longer-supported ones).  Is that sufficient?

**Comment by alvinsiu** [comment]
@aliceriot Just wanted to double check that I have things stright - the first two tasks will be closed by #1146, and the second two tasks are your domain, correct?

The "Data file of currencies per country" is currently in `financialaid/data/country_to_currency.csv`.  Let me know if there's anything we can help with other than that!

**Comment by aliceriot** [comment]
Oh! I forgot about that file. Is the backend just expecting an ISO 4217 currency code? I found a JS package that provides a nice api for code -> country correspondance using that standard: https://github.com/freeall/currency-codes

**Comment by alvinsiu** [comment]
Yup!  The [documentation](https://docs.openexchangerates.org/) for the exchange rate API we're using only says "3-letter ISO code), but I think ISO 4217 is the only major one for currencies.

Up to you if you want to use that file or not!

**Comment by aliceriot** [comment]
I already wrote the code using that JS package, so we should probably delete the file at some point.

**Comment by alvinsiu** [comment]
Oh cool!  Should we remove these two then?  Or are those still in queue?

> - [ ] Data file of currencies per country
> - [ ] API endpoint to get default currency for a user (or have the data file used on frontend)

**Comment by aliceriot** [comment]
I think we can take care of both of those in JS

**Comment by alvinsiu** [comment]
Should I remove those two items from this issue (if they're already on another issue) or leave them here for you?

**Comment by aliceriot** [comment]
oh sorry, I guess maybe leave the second one and remote the first.

**Comment by alvinsiu** [comment]
Removed

> - [ ] Data file of currencies per country

**Comment by zags** [comment]
@aliceriot FYI, these are the currencies we support on the backend: https://oxr.readme.io/docs/supported-currencies
We should limit the user to these in their selection.

**Comment by pdpinch** [comment]
@aliceriot what's the status of this?

**Comment by aliceriot** [comment]
We don't have anything yet on the frontend to get the user's default currency, I think that's the only thing that still needs to be done.
