### ISSUE TITLE
Console warnings on home page

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1050]
I got some console warnings related to the localStorage work we did recently. However I haven't actually noticed anything not working due to them

![screenshot from 2016-09-15 13-29-47](https://cloud.githubusercontent.com/assets/863262/18560248/be99ddfa-7b48-11e6-847e-d2f9b106b9e7.png)

**Comment by Ferdi** [comment]
1105 will probably fix this right ?

**Comment by aliceriot** [comment]
@noisecapella I think it's related to there being an additional reducer synced with localStorage on the dashboard which we do not use on the homepage. I think when we undo the dialog selection work that will fix the problem (there won't be a redux store on the homepage any longer).

**Comment by noisecapella** [comment]
@aliceriot makes sense
