### ISSUE TITLE
notify users about course enrollment dates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#106]
As a learner, I would like to be reminded when a course in my micromasters series is open for enrollment, but I haven't enrolled yet. I'd rather not have to return to the micromasters site in order to discover this. 

Ideally, I'd like to have some influence over how I'm notified, but to start with e-mail seems sufficient. 

This will need some more product thinking.

**Comment by roberthouse54** [comment]
The open question is whether we want to add a new setting for notifications, and allow users to opt out. Then we could send a notification when enrollment opens for a course the user has not yet taken (assuming we can do this).

We could also add different notification options, like SMS.

![image](https://cloud.githubusercontent.com/assets/20047260/21359451/5761624a-c6aa-11e6-9b1a-dc17b6b01c31.png)

**Comment by pdpinch** [comment]
Could we replace the email setting with a notifications setting? It has the advantage of being specific about what the user is getting/avoiding.

**Comment by roberthouse54** [comment]
How about this:

![image](https://cloud.githubusercontent.com/assets/20047260/21399013/dbfbcd24-c777-11e6-9a42-3b50717df157.png)

**Comment by roberthouse54** [comment]
So this will require the above change to settings. Then we can create an email to send to notify users when there is new enrollment open for a course in a program they are in, and which they have not yet taken.

Email title:
Enrollment is now open for Supply Chain Fundamentals.

Email body:
Enrollment is now open for Supply Chain Fundamentals, a course in the Supply Chain Management MicroMasters program. <link>Click here to Enroll today!</link>

**Comment by pdpinch** [comment]
Can this be addressed by an automated e-mail, e.g. when a user has a final grade > passing in a course with a final exam?

**Comment by Ferdi** [comment]
@pdpinch I like your idea as a way of implementing but i'm not sure what you mean by "when a user has a final grade > passing in a course with a final exam?"

**Comment by pdpinch** [comment]
I'm not exactly sure what the criteria would be, but I was thinking something like 'enrolled in Microeconomics', with an edX final grade above 50%. (Microeconomics being a course with a final exam and 50% being the passing threshold).

**Comment by pdpinch** [comment]
I just realized that my last 3 comments were meant for an issue about notifying learners about exam status, not new course enrollments.
