### ISSUE TITLE
Updates for micromasters.mit.edu

### ISSUE THREAD

**Issue by MariaODL** [mitodl/micromasters#1065]
Hi Everyone, 

Attached are the updates that need to go live tomorrow at 12:10pm. We are missing one link that we will send to you tomorrow. 
[Web_Updates_Micromasters.docx](https://github.com/mitodl/micromasters/files/480697/Web_Updates_Micromasters.docx)

**Comment by pdpinch** [comment]
Hi Maria. I've moved this over to the repo for the static site. I'll take care of this sometime before tomorrow at 10.

**Comment by pdpinch** [comment]
Issue moved to [mitodl/mga #10](https://github.com/mitodl/mga/issues/10) via [**ZenHub**](https://www.zenhub.com/)
