### ISSUE TITLE
Set default ordering for `Course` to position_in_program

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1066]

**Comment by Ferdi** [comment]
What is going to be the ordering ?   Maybe by start date ??

**Comment by pdpinch** [comment]
Is this for the dashboard or for something else?

**Comment by Ferdi** [comment]
oh, i assumed it was the order of courses in the dashboard.

**Comment by noisecapella** [comment]
Yes, it's for the order of courses in the dashboard and on the program page. The start date isn't going to help because this is for the course, not the course run which has the start date. We already have a field `position_in_program` for this, we just need to use it

**Comment by pdpinch** [comment]
@annagav took care of this on the program page in her PR #1080

**Comment by Ferdi** [comment]
@pdpinch  close this ?

**Comment by pdpinch** [comment]
Courses on the dashboard appear to be in the correct order.
