### ISSUE TITLE
Sign-up page: greeting doesn't dynamically change name correctly

### ISSUE THREAD

**Issue by singingwolfboy** [mitodl/micromasters#1068]
The sign-up page at `/profile/` has a nice feature where the greeting will dynamically change as the user types. However, it doesn't do so _correctly_, which leads to a confusing user experience.

# Actual behavior
When the user first visits the page, the greeting contains the first part of their email address, like so:
<img width="858" alt="initial signup" src="https://cloud.githubusercontent.com/assets/132355/18646705/ba9ee642-7e80-11e6-9f13-24fd9711738d.png">

However, after the user enters their given and family names, only the family name appears:
<img width="851" alt="typing in first and last name" src="https://cloud.githubusercontent.com/assets/132355/18646737/e2be13aa-7e80-11e6-96f7-d44d1b707dce.png">

After the user types in their preferred name, the given name is updated with their preferred name, but the family name still appears:
<img width="851" alt="typing in given, family, and preferred names" src="https://cloud.githubusercontent.com/assets/132355/18646751/fc9a4078-7e80-11e6-8478-e573b0deedcc.png">

# Expected behavior
When the user first visits the page, the greeting should contain the first part of their email address. The application does this correctly.

When the user types in any text into the "given name" and "family name" fields, they should _both_ override the email address fragment. If the user types "First" into the given name file and "Last" into the family name field, the result should be "First Last" in the greeting.

When the user types any text into the "Preferred name" field, that should override all other fields. If the user types "Preferred" into this field, the result should be "Preferred" in the greeting (not "Preferred Last").

**Comment by aliceriot** [comment]
I'm gonna steal this!
