### ISSUE TITLE
Error message on dashboard if no program enrollment is available

### ISSUE THREAD

**Issue by singingwolfboy** [mitodl/micromasters#1069]
After completing the sign-up process on a new MicroMasters installation, the user is redirected to the dashboard, where they see an ugly error message:
![Error message: No program enrollment is available.](https://cloud.githubusercontent.com/assets/132355/18647184/e092682c-7e82-11e6-9bf5-522b77c744a5.png)

Expected: if the user tries to view the dashboard without a program enrollment, they are shown a friendly message explaining that they cannot proceed further without an enrollment, and no enrollments are available. Another option is to automatically redirect the user someplace they can go, with an informative message on that page explaining why they were redirected. (These messages are known as "flash messages" in Rails and Flask, not sure if there's an equivalent in Django.)

**Comment by noisecapella** [comment]
Your right, we don't cover this case. 'Sign up' link on the home page will ask the user to enroll in a program, but I think the 'Login' link is still functional for those users as long as they have an edX account. We should handle this case better

**Comment by pdpinch** [comment]
@roberthouse54 let's discuss the UX around this

**Comment by giocalitri** [comment]
This should be top priority: the probability people will get this bug is extremely high.

**Comment by singingwolfboy** [comment]
However this ticket is resolved, part of the acceptance criteria should be updating the documentation in the README file. If the solution is to allow students to login without enrolling, then the README needs instructions on how to use the UI to enroll in a course. If the solution is to not allow students to login without enrolling, then the README needs instructions on how to use the admin tools to create a program, so that the developer running this application can then enroll with the newly-created program.

**Comment by pdpinch** [comment]
Yup. @roberthouse54 @Ferdi and I discussed this morning. 

We're thinking about a message on the dashboard, since we already have a UI there for choosing a program. The question is what does the drop-down look like if the user hasn't chosen a program.

**Comment by pdpinch** [comment]
I was thinking of something like this:

![image](https://cloud.githubusercontent.com/assets/430126/18759624/4cf39a0a-80cb-11e6-9f5e-26c60329546b.png)

@roberthouse54 please comment.

**Comment by Ferdi** [comment]
Or "chose one"  be a link that brings up the popup where they chose a program.

**Comment by pdpinch** [comment]
Hi @amir-qayyum-khan we're going to fix this a different way. Stay tuned for a different issue.
