### ISSUE TITLE
Financial Aid: Allow learners to bypass financial aid & pay full price

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1076]
Some learners will want to skip the financial aid process. At any stage, we'll allow them to shortcut the process and be approved to pay full price. 

This function will link from 3 locations:

1. Initial Financial Aid description widget: 

  ![image](https://cloud.githubusercontent.com/assets/430126/18723999/d23b7944-8008-11e6-9214-300446ed689a.png)

2. Cost Calculator:

  ![image](https://cloud.githubusercontent.com/assets/430126/18724024/e228be8e-8008-11e6-8e33-2b7b11c61165.png)

3. The Verify Documents widget

![image](https://cloud.githubusercontent.com/assets/430126/18765119/4c3a255e-80e2-11e6-82c4-5dd283b549ef.png)

Since there's a lot of money at stake, choosing this opens a confirmation dialog:

![image](https://cloud.githubusercontent.com/assets/430126/18765102/366dfaa2-80e2-11e6-822b-bdb3618005ed.png)

## Acceptance Criteria

- [x] API and modifications to financial aid status to track that the user has chosen to pay full price
- [x] UI 1) above
- [x] UI 2) above
- [x] UI 3) above

**Comment by pdpinch** [comment]
@zags @alvinsiu I'm pretty sure this is a case that we didn't consider in the API. Can you confirm?

**Comment by alvinsiu** [comment]
@pdpinch We considered that possibility, but we assumed that anyone who wants to bypass financial aid will simply no apply for financial aid (no request to API made).  For the case where they've already applied, we could add a status to the financial aid object along the lines of USER_BYPASSED that can be set if a user checks out at full price with a pending financial aid request?

**Comment by pdpinch** [comment]
That sounds like it would work. 

We'd like to allow learners to move to this status from the calculator form, in case they want to bail out out of the process rather than type in their income. (this will be clearer once I can paste a design)

**Comment by alvinsiu** [comment]
We can certainly modify the API to allow for this to happen - we'll wait for the design before we implement the changes on the API.

**Comment by pdpinch** [comment]
Add 2 of the 3 screens. The 3rd is still being debated, but I the function is the same.

**Comment by pdpinch** [comment]
added a missing screenshot as well as the confirmation dialog.

**Comment by alvinsiu** [comment]
@pdpinch #1175 implements the backend API for this.  Is there another issue for the frontend work so I can close this issue with the PR, or is this the issue for that and I shouldn't close this issue with the PR?

**Comment by pdpinch** [comment]
Thanks Alvin. There isn't a separate issue for the front-end. I added some check boxes instead and checked off the first one for you.
