### ISSUE TITLE
Abstract "MicroMasters" track to include financial aid case

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1077]
A user is enrolled in a MicroMasters track for a course if one of the two following conditions are met:
1) for programs without financial aid, they have an enrolled in a verified track
2) for programs with financial aid, they have enrolled in an audit track and they have paid for the course

Learner dashboard statuses should be updated so that they depend on this abstract track enrollment, instead of depending directly on the verified track enrollment.

**Comment by pdpinch** [comment]
@giocalitri does this still make sense?

**Comment by giocalitri** [comment]
Wasn't this what we discussed to do?


On Sep 22, 2016, at 5:08 PM, Peter Pinch <notifications@github.com<mailto:notifications@github.com>> wrote:


@giocalitri<https://github.com/giocalitri> does this still make sense?

**Comment by pdpinch** [comment]
It's my interpretation of what we discussed, but I wanted to check with you. Sounds like a "yes"
