### ISSUE TITLE
Return final grade in API for financial aid-enabled courses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1078]
MicroMasters programs with financial aid won't use certificates, so we can't rely on the `certificates` API to get the user's final grade or to determine the user's passed status. 

For those programs we can determine the "final" grade and passed/not-passed status by making a call to the course_grade API after the course end_date.

For example, using my user, a call to https://courses.edx.org/api/grades/v0/course_grade/HarvardX/SW12.3x/1T2014/users/?username=pdpinch returns:

```
[
    {
        "username": "pdpinch",
        "letter_grade": "Pass",
        "percent": 0.97,
        "course_key": "HarvardX/SW12.3x/1T2014",
        "passed": true
    }
]
```

**Comment by Ferdi** [comment]
This will be only for DEDP case right.  The rest will still use certs ?

**Comment by pdpinch** [comment]
I was thinking it would be easier if we used the same mechanism for all courses, but if you prefer to use the certificates table that's fine with me. 

The final grade in the certificate table is more stable, and less expensive to query.

**Comment by gsidebo** [comment]
A more appropriate title for this would probably be "Return final grade in API for financial aid-enabled courses". How we get that final grade is an implementation detail. There's no reason for us to ditch certificate grades for non-financial aid courses

**Comment by Ferdi** [comment]
@gsidebo updated title and description

**Comment by pdpinch** [comment]
@ferdi I don't the title change stuck. Can we discuss this briefly in planning on Monday?

**Comment by pdpinch** [comment]
I spoke with Giovanni and confirmed that we won't "ditch certificate grades for non-financial aid courses" as @gsidebo put it.
