### ISSUE TITLE
Financial Aid: Cost Calculator

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1097]
For programs with financial aid, learners will have to fill out a form to calculate their personal price. 

![image](https://cloud.githubusercontent.com/assets/430126/18765532/198c1426-80e4-11e6-8ffb-7ef7b30513b5.png)

##  Acceptance criteria

- [ ] check with @roberthouse54 about whether country of residence appear in form
- [ ] This form will interact with the APIs implemented in #1053 
- [ ] user can bail out of the form using the "skip this and pay full price" link
- [ ] user cannot submit the form without checking the "I testify..." box

**Comment by alvinsiu** [comment]
@aliceriot @pdpinch Just wanted to make sure we're on the same page - we'll be doing currency conversion on the backend, which currently hasn't been implemented yet (so you can't really test anything but "USD").  That will be implemented as part of #1048.

**Comment by aliceriot** [comment]
alright, if that's already part of the design that's fine - personally, I would store everything on the backend in USD and do all currency conversion in JavaScript, which would let the user change currencies and so on without needing to hit the backend and simplify the logic overall (all the calculations and so on would be done based on USD and the only conversion would happen at the UI level).

Are you thinking of having an endpoint just to receive a tuple of `[number, currency, currency_to_convert_to]`?

**Comment by noisecapella** [comment]
@aliceriot I think it needs to be done on the backend so that we have a record of what the exchange rate, basically

**Comment by aliceriot** [comment]
ah that makes sense!

**Comment by alvinsiu** [comment]
The endpoint expects a post request with the following fields "original_currency", "program_id", and "original_income".

**Comment by pdpinch** [comment]
The checkbox is required. We will store the date that the checkbox was checked.
