### ISSUE TITLE
Financial Aid UI: Documents required for verification

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1098]
Some users will need to send documents to verify income. They will receive a message in their dashboard and a short form to record when they sent their documents. 

![image](https://cloud.githubusercontent.com/assets/430126/18765914/b732589c-80e5-11e6-9d10-4d2d1fb4d5eb.png)

## Acceptance criteria

- [x] use API in #1053 to determine whether docs are required
- [x] form for submitting date docs were sent
- [ ] after date is submitted, update message:

![image](https://cloud.githubusercontent.com/assets/430126/18765997/12c1ec72-80e6-11e6-851c-1e473f0c6e0b.png)

**Comment by alvinsiu** [comment]
I don't think we have a specific API endpoint for determining if docs are required yet, but we can build an endpoint for that.

We also don't have a way of explicitly tracking the date documents were mailed (did you mean received?).  We can retrieve it via the auditing trail, or naively by using the "updated_on" timestamp when the status is changed from "pending-docs" to "pending-manual-approval", but neither of those are the most robust.  Should we add a field explicitly for tracking when documents are mailed?

**Comment by pdpinch** [comment]
For docs required, I'm not sure how you wanted to message that to the front-end. It could just be the return from the calculator submission, but then there's the question of repeat visits from the user. Can you discuss with @aliceriot ?

The date is a new feature. I think adding a new field makes sense. You'll see that it appears in the financial aid review view as well.

**Comment by alvinsiu** [comment]
Docs required should probably be a separate endpoint, that way we can still know when to display the message if they log back in another time separate from the calculator submission.  @aliceriot If we return the `FinancialAid` object so that you can see if `object.status == "pending-docs"`, would that work?

**Comment by aliceriot** [comment]
@alvinsiu yea I think that sounds straightforward enough, I've been working on something else and haven't dug into this yet so I can't say for sure though.

**Comment by alvinsiu** [comment]
Great, we'll implement that API for you, and you can let us know if you need any additional information or any changes to what's returned!

**Comment by aliceriot** [comment]
OK reading over this it would make sense to me if the docs endpoint returned something like:

```js
{
  application_status: 'docs-required-pending' || 'docs-required-received', // etc
  docs_mailing_date: 'YYYY-MM-DD',
}
```

@pdpinch I haven't been so up on the financial aid stuff, does this require that we have the financial aid calculator done?

**Comment by aliceriot** [comment]
just wondering about which one to take on first

**Comment by pdpinch** [comment]
I think it makes more sense to start with #1097. I should have put that one into "ready" ahead of this one.

**Comment by aliceriot** [comment]
@pdpinch I just wanted to clarify on this issue, do we need to have a way to display a different list of documents depending on the income that the user used to submit their financial aid request?

**Comment by pdpinch** [comment]
This is still an unknown, so we'd like to go with a generic phrase and a link to a FAQ page (in a new tab? or in a modal?) with more details. Let me discuss with @roberthouse54 

Suggested text: 

> Before you pay, you need to verify your income by mailing or faxing supporting documentation. [(?)](http://example.com)

**Comment by pdpinch** [comment]
@aliceriot @roberthouse54 I think this is functionally complete, but we need to update the text with:

- [ ] correct list of docuements
- [ ] correct mailing address
- [ ] correct fax number

Currently, it looks like this:

<img width="764" alt="screen shot 2016-10-07 at 8 43 45 am" src="https://cloud.githubusercontent.com/assets/430126/19190233/5e34d9dc-8c6a-11e6-83da-201f2eb4a408.png">

**Comment by Ferdi** [comment]
I commented somewhere else , I think it's important - I dont see a "Pay full price" in this screen. Learner might decide to not go through the process and just pay full price at this point

**Comment by roberthouse54** [comment]
Let's just update the copy here and get rid of the bullets.

"Before you can pay, you need to verify your income. Please mail or fax a translated and notarized income tax or income statement document."

**Comment by aliceriot** [comment]
What's the correct mailing address to use?

**Comment by pdpinch** [comment]
Sorry, I thought I had passed along this info Friday, but I guess not. 

> I’m trying to get a specific locked post box for the DEDP MM; so the address will change slightly once I know which number we will be assigned. We can add a line like “DEDP MicroMasters” as the first address line as a placeholder for now.

> The fax number is 617 715 5799.
