### ISSUE TITLE
simple django template for home page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#11]

**Comment by annagav** [comment]
It should look something like this? 
<img width="597" alt="screen shot 2016-03-03 at 11 45 43 am" src="https://cloud.githubusercontent.com/assets/7574259/13501688/a559b28c-e135-11e5-957d-ac100610426c.png">

**Comment by noisecapella** [comment]
I think so, it can look like the wireframe pretty much, the styling would come later after the designer has produced some mockups

**Comment by pdpinch** [comment]
Like George said. 

We do need to the template to pull in the list of micromasters (currently just one). I think @justinabrahms has incidentally started working on the model for that. You should check with him.
