### ISSUE TITLE
Financial Aid: Docs reviewed and approved / rejected 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1100]
After a learner's financial aid docs have been reviewed, we need to update the status message on their dashboard and the price of their courses:

(note: this is very similar to the screen in #1044)

![image](https://cloud.githubusercontent.com/assets/430126/18766088/8cd9813c-80e6-11e6-80f6-544a23c3b163.png)

## Acceptance criteria:

- [ ] Update the message based on the status returned by the API in #1071/#1096
- [ ] Update the prices
- [ ] If we replaced "adjusted" with "personalized" in the message, we can use the same message even if the user is paying full price.

**Comment by pdpinch** [comment]
@noisecapella @aliceriot I'm not sure if this is already done. Feel free to close if it is.

**Comment by aliceriot** [comment]
I'm not sure on this one, @noisecapella might know!

**Comment by noisecapella** [comment]
It doesn't look like the image in the issue here but it does look like the image in the invision mockups which just say 'Your cost is $125 per course`. Other than that everything should be done

**Comment by pdpinch** [comment]
Invision is more up to date. I'll close this and we can open another issue for any problems that come up.
