### ISSUE TITLE
Dashboard: display passed courses 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1101]
The definition of passed is when the grades API returns `"passed": true` and `course.end` < today

![image](https://cloud.githubusercontent.com/assets/430126/18766650/44d9a792-80e9-11e6-8cbe-554054206a9d.png)

**Comment by gsidebo** [comment]
@pdpinch today < course.end? how can a course be considered 'passed' if the course hasn't ended?

**Comment by pdpinch** [comment]
@gsidebo you're right. I changed the description to `course.end` < today
