### ISSUE TITLE
Dashboard: display courses with enrollment open

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1102]
There are three course states the learner can see before they have enrolled in a course:

### Enrollment Open - Basic View

![image](https://cloud.githubusercontent.com/assets/430126/18766797/ff45787c-80e9-11e6-8f9d-e37b3b2b98d8.png)

This is the normal view when Enrollment is open. Users can click the “Pay” button to pay, or click on Enroll and Pay later to audit. 

For Variable pricing courses, like DEDP, this will start the ecommerce flow. 

For verified track courses, this will link to the edX course info page , https://courses.edx.org/course_modes/choose/{course_key}/

For all courses, Enroll and Pay can enroll the user via edX API. 

### Enrollment Open - Before Calculating Cost

![image](https://cloud.githubusercontent.com/assets/430126/18766837/29cc5c82-80ea-11e6-926f-27e5d06c2f0b.png)

This view is for DEDP only. The user has to Calculate their cost before paying. If they click “Enroll and Pay Later” they are immediately enrolled in the audit track. Clicking “Calculate” opens the Calculator dialog.

### Enrollment Open - Pending Income Verification

![image](https://cloud.githubusercontent.com/assets/430126/18766845/32556c54-80ea-11e6-8c24-3064d22bd216.png)

This view is for DEDP only. This is the status after the user has submitted documents but before they have been confirmed. The user can still enroll in the course (as audit) but they cannot pay, the button is disabled.

**Comment by gsidebo** [comment]
going to look into the first and second states here for the time being. representing the 'pending' state will require changes to the API and @giocalitri is working on that code right now

**Comment by pdpinch** [comment]
As discussed in planning, the finaid status will be included in the dashboard API
