### ISSUE TITLE
Sign-up: display program drop-down for users with no program

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1105]
This will address the bug opened in #1069

The program selection moves from sign up popup to the "basic info" tab (see also #1113)

- [ ] If possible (but please ignore if not straightforward) the value on this dropdown should be pre populated when user signs up from the program pages. 

![image](https://s3.amazonaws.com/uploads.hipchat.com/151776/4073658/O2WNgTAq1XeUPT5/upload.png)

**Comment by pdpinch** [comment]
After this is implemented, we may remove the program drop-down from the sign-up modal on the home page and program pages.

**Comment by amir-qayyum-khan** [comment]
sure, thing got it

**Comment by Ferdi** [comment]
@pdpinch is  "remove the program drop-down from the sign-up modal on the home page" part of this issue or separate ?

**Comment by Ferdi** [comment]
Updated description and created a new issue for sign in/up  #1113
