### ISSUE TITLE
(Bug) Course description component has incorrect logic

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#1120]
from static/js/components/dashboard/CourseDescription.js

```javascript
case STATUS_NOT_PASSED:
      if (firstRun.course_end_date) {
        let courseEndDate = moment(firstRun.course_end_date);
        return this.courseDate('Ended', courseEndDate);
      } else if (!_.isNil(firstRun.fuzzy_start_date)) {
        return `Coming ${firstRun.fuzzy_start_date}`;
      }
      break;
```

the `else if` conditional does not make sense here. if a course has the status `NOT_PASSED`, it happened in the past by definition. whether or not this conditional can be reached under normal circumstances, it's clearly misplaced, and it's very possible that it should be shown for a different course run status

**Comment by pdpinch** [comment]
@gsidebo is this still a problem?

**Comment by gsidebo** [comment]
nope i fixed this while going through these course state issues
