### ISSUE TITLE
Squashed image on 404 page

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1123]
![screenshot from 2016-09-26 11-42-13](https://cloud.githubusercontent.com/assets/863262/18840973/4f728190-83de-11e6-8138-b7c0d73e321d.png)

**Comment by amir-qayyum-khan** [comment]
@noisecapella @pdpinch i dont think this issue exist on master branch. It seems already fixed

![screen shot 2016-10-05 at 2 59 25 pm](https://cloud.githubusercontent.com/assets/10431250/19108953/7a39950a-8b0c-11e6-8181-c25de3faad74.png)
<img width="645" alt="screen shot 2016-10-05 at 2 59 47 pm" src="https://cloud.githubusercontent.com/assets/10431250/19108954/7a6ad840-8b0c-11e6-88a4-70af95523d9c.png">

**Comment by pdpinch** [comment]
I think this was fixed incidentally.
