### ISSUE TITLE
Home: copy changes

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1140]
### Hero image text:

MicroMasters: Learn now, apply later (or never)
A new kind of digital credential for online learners

### What is MicroMasters?

The MicroMasters is a new digital credential for online learners.  The MicroMasters credential will be granted to learners who complete an integrated set of graduate-level courses on edX.org and capstone exams.  With the MicroMasters credentials, learners can apply for an accelerated master’s degree program on campus, at MIT or other top universities. 

(optional)
Micromasters is an important project for me. I believe in the model of empowering people.
-- Rafael Reif

#### Online Learning
Take MIT graduate-level courses remotely, from anywhere, and meet other motivated students and professionals  from around the world.

#### Blended Masters
Start a new, faster path to a Master’s degree from MIT or other universities

#### Cost savings
Get a masters degree at a significantly reduced cost

**Comment by pdpinch** [comment]
FYI @roberthouse54 

@Ferdi do you want Anna to try to work in the quote from President Reif?

**Comment by Ferdi** [comment]
up to @roberthouse54

**Comment by pdpinch** [comment]
@annagav I updated the copy a bit around 11am. Also, not that the headers *don't* change - I was a little lazy typing them.
