### ISSUE TITLE
Currency codes don't match up perfectly between JS client and the server

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1170]
Related to #1146

`json_codes` comes from `JSON.stringify(cc.codes())` on the client. `py_codes` comes from `CurrencyExchangeRate.objects.values_list('currency_code' , flat=True)`

    In [32]: py_codes - json_codes
    Out[32]: {'BTC', 'BYN', 'EEK', 'GGP', 'IMP', 'JEP', 'MTL', 'SVC', 'ZMK', 'ZWL'}
    
    In [33]: json_codes - py_codes
    Out[33]: 
    {'BOV',
     'CHE',
     'CHW',
     'COU',
     'MXV',
     'SSP',
     'USN',
     'USS',
     'UYI',
     'XBA',
     'XBB',
     'XBC',
     'XBD',
     'XBT',
     'XFU',
     'XTS',
     'XXX'}

**Comment by aliceriot** [comment]
@noisecapella so just to confirm everything on the list is a currency code we want to exclude on the client? I can easily take care of this as part of #1275

**Comment by noisecapella** [comment]
Yeah I would say we should support only the currencies on both lists for right now, then later on use the server side list. I'm not sure how many of those currencies are rare or unused or otherwise not worth supporting, but since we only use the currencies to convert the users income it's not a big deal to not support a currency IMO
