### ISSUE TITLE
Program pages:  FAQ categories

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#1190]
For some MM programs, FAQs needs to be grouped in categories. 

## Acceptance Criteria

- [ ] Add a field to the FAQ model in the CMS to categorize
  - [ ] If possible, the CMS should display categories as grouped to aid authoring
- [ ] Group Questions / Answers based on category in the template

**Comment by roberthouse54** [comment]
For the FAQ tab UI, please just add an H2 header element, and I can tweak the styles later.

**Comment by singingwolfboy** [comment]
Is this more like a tagging scheme, where each question can be tagged with multiple categories, and each category can be used for multiple questions? Or is it a many-to-one relationship, where each category can contain multiple questions, but each question has only one category? Also, is it mandatory for each question to have at least one category, or should we support uncategorized questions? (Which is basically an "uncategorized" category, I suppose...)

**Comment by singingwolfboy** [comment]
Also, are the categories hierarchical? That is, can you have a categories and sub-categories? Or is there only one level of categorization?

**Comment by pdpinch** [comment]
I believe we were thinking one level, with a many to one relationship -- each category has multiple questions. 

It would be useful to allow an "Uncategorized" option, but I'm not sure what the design would be.

@ferdi? @roberthouse?

**Comment by Ferdi** [comment]
- no hierarchy - flat
- tags is a superset of many-to-one in this context but harder to implement
in cms? Yes?
- a program either use categories (then tagging /categorization becomes
required) or not at all

- Sent from my phone

**Comment by singingwolfboy** [comment]
Wagtail doesn't have built-in support for tagging, but it has a [tagging recipe right in the official documentation](http://docs.wagtail.io/en/v1.6.2/reference/pages/model_recipes.html#tagging), demonstrating how such a feature could be built using other modules in the Django ecosystem. There's no equivalent recipe for many-to-one categories, although I did find [a StackOverflow question with some code that may work](http://stackoverflow.com/questions/33651722/nested-categories-inlinepanels-in-wagtail).

Tags are certainly more flexible than categories, but that flexibility may not be what we want. If a question has more than one tag, how would it be displayed in the template? Would the question be rendered multiple times, one for each tag? Should we say that each question has one "primary" tag -- and if so, how is that different from a many-to-one category? If a question has multiple tags, is the ordering of those tags important, or not?

**Comment by Ferdi** [comment]
@singingwolfboy and I just chatted a bit. 

In #1232 categories are shared across all programs (the way wagtail snippets work , I think) so DB will come up with another PR where FAQ categories will be:
- scoped to each individual program
- Orderable 
- Optional
