### ISSUE TITLE
Filter dashboard by program enrollments

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1195]
Related to #1193. After MVP is released we should refactor our code to use `/api/v0/programs/` for the list of available programs and only show programs the user has enrolled in in `/api/v0/dashboard/`

**Comment by pdpinch** [comment]
Will this improve performance?

**Comment by noisecapella** [comment]
It would reduce the amount of data coming from the dashboard API but we would need to also fetch from `/api/v0/programs/`, which is probably a slight decrease in data overall. I don't think it would necessarily speed the API up though. The slow part of the dashboard API is the request to edX if your cache has expired (this happens every 5 minutes), and this is independent of your program enrollments.

**Comment by noisecapella** [comment]
We will not have courses or course runs in the `/api/v0/programs/` list but we will add the program page URL if it exists

**Comment by noisecapella** [comment]
At standup this morning we agreed to remove the GET portion of `/api/v0/enrolledprograms/`, leaving the POST portion as is
