### ISSUE TITLE
React app setup

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#12]
- [ ] web pack
       dev & production
- [ ] ES6
- [ ] react
- [ ] mocha

Use teachers portal as a guide

**Comment by jamiefolsom** [comment]
@noisecapella -- I think all of the setup is completed, by your PR #21. I could start on the react containers and components. Would that make sense?

**Comment by noisecapella** [comment]
That sounds right, we still need the redux libraries, the store to be configured, etc, like it is in teachersportal

**Comment by jamiefolsom** [comment]
Great, will do. Thx.
