### ISSUE TITLE
Reset learner's financial aid request

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1201]
Learners are not allowed to make multiple financial aid submissions, but accidents do happen. If a learner contacts us, we need a method to reset their state and let them submit again. 

We don't need a course-team UI for this. It can be via django admin, if that is convenient. 

As discussed, we don't want to delete the original submission, but rather change the state and allow a new submission.

**Comment by pdpinch** [comment]
Hey @alvinsiu let me know if this is sufficiently defined in order to work on it.

**Comment by pdpinch** [comment]
@giocalitri fyi

**Comment by alvinsiu** [comment]
I think this is defined enough - we'll need to do a little thinking, but @giocalitri let me know if you have any thoughts (besides what you already mentioned over HipChat) before we do any implementation.

**Comment by Ferdi** [comment]
It does not sound straightforward. If so,  let's do it post MVP.

**Comment by alvinsiu** [comment]
Let's do it post MVP then.  The long term solution is definitely not very straightforward (though the simple solution of deleting the `FinancialAid` object is pretty straightforward to implement, but has many consequences for auditing).

**Comment by giocalitri** [comment]
Deleting is not an option.

**Comment by pdpinch** [comment]
Since we added more constraints to FinancialAidAudit in PR #1488 , it's now impossible for me to delete a FiancialAid object even from the shell. This is a blocker on our testing process, since there's no way to start the financial aid flow over again. 

We need to either revert #1488 or start working on this "reset" state. 

FYI @noisecapella @giocalitri

**Comment by noisecapella** [comment]
I feel like some reset state would be the cleanest solution here, or otherwise we should make the financial aid foreign key nullable on the audit table

**Comment by giocalitri** [comment]
I vote for the reset state

**Comment by pdpinch** [comment]
When the status is updated, there will be some book-keeping to revert all the related fields.
