### ISSUE TITLE
Make the tabs scrollable on the Program Page

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#1203]
Currently on the Program page, the Tabs UI breaks on mobile... the tabs wrap underneath each other. Mobile tabs are supposed to be scrollable in Material design (see: https://material.google.com/components/tabs.html#tabs-types-of-tabs) 

I was going to try to do this as part of the responsive css issue, but I couldn't figure out how to do this in the css, and it may require javascript... not sure. But I thought someone else could do this one.

**Comment by pdpinch** [comment]
I think this is moot with the other changes to the tab interface. Feel free to open if I'm wrong.

**Comment by roberthouse54** [comment]
Sorry, this was actually fixed with my last responsive PR. https://github.com/mitodl/micromasters/pull/1386

**Comment by pdpinch** [comment]
closed via  fb9ef79
