### ISSUE TITLE
'My dashboard' link should go to learners page for staff

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1227]

**Comment by amir-qayyum-khan** [comment]
@pdpinch @noisecapella what about 404 and 500 error pages. There is dashboard link there as well.

<img width="1280" alt="screen shot 2016-10-05 at 4 25 53 pm" src="https://cloud.githubusercontent.com/assets/10431250/19111335/82a1814c-8b18-11e6-8b8a-d14f49787f57.png">
<img width="1280" alt="screen shot 2016-10-05 at 4 26 08 pm" src="https://cloud.githubusercontent.com/assets/10431250/19111336/82a318ae-8b18-11e6-9cc8-5d13aa689a36.png">

**Comment by pdpinch** [comment]
Should behave the same if possible:

Staff => learner search
Learner => dashboard

**Comment by amir-qayyum-khan** [comment]
Fixed
