### ISSUE TITLE
FinancialAidAudit data_before and data_after store JSON as text representation

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1229]

**Comment by pdpinch** [comment]
I'm not sure what this means. More importantly, do we need to do it before 10/15?

**Comment by noisecapella** [comment]
The data is stored in a JSONField but it's stored as the text representation so we're unable to use the Django ORM to filter the JSON. It would be nice to get this done before release because I don't like the idea of doing data migrations after release on audit tables. But if we're not planning on searching the audit table it's not really necessary

**Comment by pdpinch** [comment]
If this is just a data migration, I agree that doing it now would be much better.
