### ISSUE TITLE
'#undefined' anchor added to home page after login

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#1234]
![ss 2016-10-05 at 09 25 58](https://cloud.githubusercontent.com/assets/14932219/19114893/dffd7660-8add-11e6-85f6-a4a1ea5d243d.png)

when i navigate directly to http://192.168.99.100:8079/ (my local MM instance), '#undefined' is added to the url

**Comment by Ferdi** [comment]
Yes, that's a bug.  That's what @pdpinch meant in his comment https://github.com/mitodl/micromasters/issues/1191#issuecomment-251492175

**Comment by pdpinch** [comment]
This should be fixed by @annagav's next iteration on #1204

**Comment by pdpinch** [comment]
@annagav did you fix this with #1204 ?

**Comment by pdpinch** [comment]
Looks fixed to me.
