### ISSUE TITLE
Currency exchange objects are not created until celery tasks are run

### ISSUE THREAD

**Issue by alvinsiu** [mitodl/micromasters#1235]
Need to create a management command or similar to run on deployment to generate the currency exchange objects

**Comment by pdpinch** [comment]
can you explain a bit more? It sounds like we need this for 10/15?

**Comment by alvinsiu** [comment]
Yeah, this is definitely needed for 10/15.  Basically, there is a task registered to update/create currency exchange objects in the database to do currency conversions when calculating cost.  But those database objects won't be there until the first task runs, so we'll need to generate those at run-time.

Currently, clicking calculate cost with any currency other than USD has no effect on the frontend, even though our endpoint is returning an error "Currency not supported".

**Comment by pdpinch** [comment]
Can I assign this to you?

**Comment by zags** [comment]
By the way, the purpose of the management command is simply to allow the system to have currency conversion numbers in the first day after initial deployment.  Any system where celery has been running for a day will be fine without this fix.   This will also facilitate local development.
