### ISSUE TITLE
When user enrolls in a new program they get a 'No program enrollment is available' message

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1238]
To produce this bug I was enrolled in three `ProgramEnrollment`s on micromasters-rc. I deleted the one I was on currently then refreshed the page. I added it back using the 'Enroll in a new program' dialog. After the refresh happened I got the 'No program enrollment is available.'

I think this is due to course prices not being refreshed at the same time as the dashboard API. If I refresh the page manually it works fine afterwards

**Comment by pdpinch** [comment]
Might this have the same cause as #1231 ?

**Comment by noisecapella** [comment]
Yes it's likely
