### ISSUE TITLE
Memory warnings on micromasters-rc logs

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1240]
I haven't encountered any errors as a user but we should figure out what is causing this and see if it's important

**Comment by pdpinch** [comment]
Hoepfully, we can reproduce this with load testing.

**Comment by blarghmatey** [comment]
This appears to be due to the fact that the uWSGI server is configured to run 10 processes at launch. I addressed that in #1395 which has been merged. Closing this for now until we see the problem again.
