### ISSUE TITLE
Possible race condition with order fulfillment

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1242]
Since order fulfillment happens via postback, the user may get redirected back to the dashboard before the order is fulfilled. This means they still see the pay button even though they paid. So far this has been instantaneous so we haven't seen this yet but we may encounter it after release. Ideas to fix:

 - replace the order fulfillment message with 'Order being fulfilled, may take a few minutes...' or something like that
 - Use the order fulfillment GET parameter as a message to disable payment buttons

**Comment by noisecapella** [comment]
I'm going to use the order fulfillment GET parameter and the dashboard state to pick which toast message to display, and whether to show the pay button for that course run

**Comment by noisecapella** [comment]
After talking with @roberthouse54 we will do a 30 second toast message with a spinner. Every five seconds or so we will refresh the dashboard state and check to see if the course purchase went through. If it did we display the same success message as before. If it didn't succeed after 30 seconds the toast message will change to a message asking the user to contact support

**Comment by roberthouse54** [comment]
![image](https://cloud.githubusercontent.com/assets/20047260/19287662/af56dd6a-8fd0-11e6-9060-0d1ca3d7dad7.png)

![image](https://cloud.githubusercontent.com/assets/20047260/19287780/317feda4-8fd1-11e6-8481-5f3f1d0826e4.png)

**Comment by roberthouse54** [comment]
![image](https://cloud.githubusercontent.com/assets/20047260/19287793/4007bfa0-8fd1-11e6-8afd-b3ab77d330ac.png)

**Comment by roberthouse54** [comment]
![image](https://cloud.githubusercontent.com/assets/20047260/19287814/57fe9a66-8fd1-11e6-93e2-f44f696ecd88.png)

**Comment by Ferdi** [comment]
I'm not sure about this.  Asking users to e-mail us it not ideal.  We can, for example send them an e-mail when we know more about the order status

**Comment by Ferdi** [comment]
Also, the messages here are global to the dashboard.   What if we had another status for each course which depends on the status of the order ?

**Comment by roberthouse54** [comment]
OK, so instead of the second message, perhaps we should instead just make the toast message disappear, and show a "Payment pending" status next to the disabled "Pay Now" button.
