### ISSUE TITLE
Student Dashboard API

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#125]
replaces #74 

For a given user id, return a list of courses in the current micromasters with a status for each course 

For example:

title: Intro to SCM
status: 
- course has not been offered (start date doesn't exist or is in the future)
- user not enrolled, but course is offered with enrollment date in the future
- user not enrolled, course is open for enrollment now
- user enrolled but not verified
- user enrolled but not verified and verification date has passed
- verified but not completed
- verified, completed and not passed
- verified, completed and passed
  
some additional fields, depending on what the status is, e.g. user grade

**Comment by pdpinch** [comment]
Update this with json structure, when we determine it

**Comment by pdpinch** [comment]
APIs don't exist yet in edX for some of this data. We will return `null` for this data for now.

**Comment by pwilkins** [comment]
I find a truth table easier to read.  I'd like to think that these are progressive, that is, the last "yes" in a row implies the yeses that precede it, but the verification date may break that assumption. 

 offered | enrollment open | enrolled | verified | past verification | completed | passed |
 --------- | ----------------- | ---------- | ---------- | -------------------- | ----------- | --------
 no | no | no | no | no | no | no
 yes | no | no | no | no | no | no
 yes | yes | no | no | no | no | no
 yes | yes | yes | no | no | no | no
_**yes**_ | _**yes**_ | _**yes**_ | _**no**_ | _**yes**_ | _**no**_ | _**no**_ 
 yes | yes | yes | yes | no | no | no 
 yes | yes | yes | yes | yes | no | no
 yes | yes | yes | yes | yes | yes | no
 yes | yes | yes | yes | yes | yes | yes

**Comment by noisecapella** [comment]
What about
- user not enrolled, course enrollment date has passed

Is there a time limit the user must enroll in?

**Comment by pdpinch** [comment]
I suppose that is another state, but from the user's perspective it's the same as "course has not been offered (start date doesn't exist or is in the future)" or "user not enrolled, but course is offered with enrollment date in the future"

I believe course runs have a field `enrollment_end` after which users can no longer enroll.

**Comment by noisecapella** [comment]
How is this for the data returned?

    {
      courses:
        [{
          title: "SC1x Supply Chain Fundamentals",
          status: "passed",
          grade: "B"
        }, {
          title: "Supply Chain Management 2",
          status: "not-passed",
          grade: "F"
        }, {
          title: "Supply Chain Management 3",
          status: "verified-not-completed",
          completion: 80,
          // If course_start_date is in the future, show 'Course starts: <date>'
          // else show a completion amount (defaults to 0%)
          course_start_date: "2016-03-31"
        }, {
          title: "Supply Chain Management 4",
          status: "enrolled-not-verified",
          // if verification_date is in the future, UI will show a 'Verify' button
          // else user cannot verify anymore so nothing is shown
          verification_date: "2016-03-31"
        }, {
          title: "Supply Chain Management 7",
          status: "offered-not-enrolled",
          // if enrollment_start_date is in the future, show "Enrollment starts: <date>"
          // if enrollment_start_date is in the past or today, show 'Enroll' button
          enrollment_start_date: "2016-03-31"
        }, {
          title: "Supply Chain Management 8",
          status: "not-offered"
        }]
    }

**Comment by pdpinch** [comment]
This is what I had in mind. I'll want to go over it carefully, but this is the right direction. 

For example, I think "completion" might natively be a float, e.g. .8 instead of 80.

**Comment by pdpinch** [comment]
Here's an update version of the return json. I'm not sure we can actually get all the data necessary for the "verified, completed and not passed" state, but I've left it in:

```
{
  courses:
    [{
      title: "SC1x Supply Chain Fundamentals",
      status: "passed",
      grade: "0.98"
    }, {
      title: "Supply Chain Management 2",
      status: "not-passed",
      grade: "0.05"
      // I'm not sure where we're going to get this data from. AFAIK, the 
      // certificates API will only contain passing certificates    
    }, {
      title: "Supply Chain Management 3",
      status: "verified-not-completed",
      grade: "0.80",
      // If course_start_date is in the future, show 'Course starts: <date>'
      // else show the current grade (defaults to 0%)
      course_start_date: "2016-03-31"
    }, {
      title: "Supply Chain Management 4",
      status: "enrolled-not-verified",
      // if verification_date is in the future, UI will show a 'Verify' button
      // else user cannot verify anymore so nothing is shown
      verification_date: "2016-03-31"
    }, {
      title: "Supply Chain Management 7",
      status: "offered-not-enrolled",
      // if enrollment_start_date is in the future, show 'Enrollment starts: <date>'
      // if enrollment_start_date is in the past or today, show 'Enroll' button
      // if there is no enrollment_start_date, display fuzzy_enrollment_start_date
      enrollment_start_date: "2016-03-31"
      fuzzy_enrollment_start_date: "spring 2016"
    }, {
      title: "Supply Chain Management 8",
      status: "not-offered"
    }]
}
```

**Comment by noisecapella** [comment]
I just realized we don't have a course key anywhere. What should we use for identifying each course? Is the course key good or is that not unique?

**Comment by noisecapella** [comment]
For a course that's not completed, are we not showing completion anymore, just the grade? Also, are we converting the grade values to percents or to letter grades in the React UI?

**Comment by giocalitri** [comment]
We need to use the course key, and it will be called `id`, in case we need to change it in the future

**Comment by pdpinch** [comment]
> For a course that's not completed, are we not showing completion anymore, just the grade?
> 
There is no representation of "percent completed" in edX just a grade. 
> Also, are we converting the grade values to percents or to letter grades in the React UI?
> 
Letter grades are defined for each course, and I don't see a good way to extract that data (i.e. it's not available from the certificate API). It's much simpler to stick with percents.

**Comment by noisecapella** [comment]
If we are showing the grade when the course is not completed, is there anything to notify the user that the course is complete or not?

**Comment by noisecapella** [comment]
We should pass the grades as floats instead of strings. Strings are better at guaranteeing float precision of data but I don't think we'll need that here if we're just rounding to the nearest percent

**Comment by noisecapella** [comment]
Here's the javascript side: https://github.com/mitodl/micromasters/pull/130/files#diff-3ba30cee865fa843dc5141d396244367R39

**Comment by giocalitri** [comment]
This a "compressed" view of all the states
![img_5179](https://cloud.githubusercontent.com/assets/1005204/14291576/2026ef78-fb32-11e5-813a-4680fb6e0b70.jpg)

**Comment by giocalitri** [comment]
Implementation logic
![img_5185](https://cloud.githubusercontent.com/assets/1005204/14363933/914fae8a-fcd4-11e5-84b2-8ef37139675d.jpg)
