### ISSUE TITLE
Course price API should output adjusted price

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1251]
Currently it outputs the full price until the financial aid is approved, but this means the user sees the full price instead of the discounted price right after they submitted a financial aid application. In this example the full price is $2345 and there's a $900 discount, but the user sees $2345 instead of $1445:

![screenshot from 2016-10-05 15-43-20](https://cloud.githubusercontent.com/assets/863262/19128734/9a58bb08-8b12-11e6-8a2c-427bc9dcf36d.png)

**Comment by pdpinch** [comment]
@alvinsiu does this need to be fixed in the API?

**Comment by alvinsiu** [comment]
It's probably the most straightforward to do it in the course price API, but I'll defer that to whomever is writing the frontend for it (since it can also be calculated via information that's already existing, I think, from the dashboard API).

**Comment by noisecapella** [comment]
The dashboard only has information about the minimum and maximum cost, not the assigned tier's cost, so we need to change the price in the price API

**Comment by alvinsiu** [comment]
Sounds good.  Currently it returns:

`program_id (int)`
`price (float)`
`financial_aid_adjustment (bool)`
`financial_aid_adjustment (bool)`
`financial_aid_availability (bool)`

Would it suffice to return an additional field `pending_price (float)`?

**Comment by noisecapella** [comment]
I'd prefer if we just output it in place of `price` for the pending states. I can't think of a use case for having both in the API at the same time

**Comment by alvinsiu** [comment]
Are we also using this for determining how much a learner is supposed to pay in ecommerce?  If so, and a learner has a pending application but decides to just pay now anyway, I think it would make more sense to not have to pull the course price separately if their application isn't in an approved state.

**Comment by noisecapella** [comment]
We are using the same function for ecommerce, but the user is not allowed to checkout unless they are in one of the terminal states. I think their status would need to be 'skipped' to skip the financial aid workflow and pay full price

**Comment by alvinsiu** [comment]
Ah, that makes sense.  I'll do it in place of price.

Let me know if any of the other three returned values are no longer necessary:
>`financial_aid_adjustment (bool)`
>`financial_aid_availability (bool)`
>`has_financial_aid_request (bool)`

**Comment by noisecapella** [comment]
We aren't using `financial_aid_adjustment` but we are using the other two. Feel free to remove it or leave it around

**Comment by Ferdi** [comment]
Maybe unrelated to your discussion, but just to make sure, user can decide not to send the supporting docs and enroll full price after going through the fin. aid app, right ?

**Comment by alvinsiu** [comment]
Yes, the API endpoint to support that is in place.
