### ISSUE TITLE
add LinkedIn social auth plugin

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#126]
Create an endpoint that prompts the user to login to LInkedIn via OAuth and returns all the json available. 

We will use this later once we've established the mapping of LinkedIn fields to user profile fields in micromasters.

**Comment by justinabrahms** [comment]
To close the loop from chat:

- LinkedIn does provide sign-in-with-linkedin, but you can't then make reasonable API access without a partnership
- This started ~ 1 year ago. http://thenextweb.com/dd/2015/02/12/linkedin-takes-aim-developers-plans-lock-apis/
- https://developer.linkedin.com/partner-programs/apply is where we apply for the partnership
- I believe we want access to the "Professional Productivity" suite of APIs, but it's difficult to know without actual API docs.

**Comment by justinabrahms** [comment]
https://developer.linkedin.com/legal/api-terms-of-use -- terms of use say that we are limited to a total of 500,000 registered people ever, fyi.

**Comment by justinabrahms** [comment]
The access we get only allows us to get information about the user's current positions, not past positions.

**Comment by Ferdi** [comment]
FYI .. I just applied for their partner program.
