### ISSUE TITLE
Pre-populate ZenDesk web widget with name, email and program

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1262]
We want to pass some data into the ZenDesk web widget to make it easier for users and also to help automate routing in ZenDesk. 
- [x] @pdpinch Set up a custom field in ZenDesk "MicroMasters Program" which can contain the current  user's current program or "None"
- [x] @pdpinch Update the ZenDesk widget code to accept these fields
- [x] Implement the [ZenDesk JavaScript API](https://developer.zendesk.com/embeddables/docs/widget/api) to set user name and email 
- [x] research how to pass the MicroMasters program name
- [ ] hide pre-populated fields so the user can't change them

**Comment by pdpinch** [comment]
I've updated the widget to add the "MicroMasters Program" field, and to use the current background color.

**Comment by amir-qayyum-khan** [comment]
yes, i saw update , i am getting some issue with local MM, just installing new instace

**Comment by singingwolfboy** [comment]
It looks like the ZenDesk API does not use the [asynchronous module definition API](https://github.com/amdjs/amdjs-api/blob/master/AMD.md), which means it can't be imported in our Javascript files. I spent some time trying to figure out if we could shim it, but I don't see a good way to do so.  We'll probably just need to write a separate `<script>` tag on the page and reference the global [`zE.identify()`](https://developer.zendesk.com/embeddables/docs/widget/api#ze.identify) function.

**Comment by pdpinch** [comment]
@singingwolfboy what's left on this?

**Comment by singingwolfboy** [comment]
Currently, the program name will _only_ be pre-populated in the Zendesk widget if the user is on a program page. If the user is on any other page of the application, the program name will not be pre-populated.

It might make sense to pre-populate the program name in the widget on other pages in certain cases -- for example, if the user is only enrolled in one program, it's very likely that they are seeking help about that program. We may want to define exactly what logic should be used for pre-populating the program name on other pages, and then implement that logic.

**Comment by pdpinch** [comment]
Some pages (notably the dashboard) allows the user to select their program context . We should use the value of that select box for the help widget.

**Comment by pdpinch** [comment]
Just spoke to Ferdi and we'd like to keep this simple and not try to get the program from the dashboard. 

However, one change to add -- can we hide the fields that have values in them, so users can't change their name and e-mail (when we have it)?

**Comment by pdpinch** [comment]
@singingwolfboy just wanted to check to see if you're still working on this -- in particular the [last comment](https://github.com/mitodl/micromasters/issues/1262#issuecomment-261615275)

**Comment by singingwolfboy** [comment]
I don't think we can hide fields that have values in them. The ZenDesk Web Widget is also rendered using React, and every time a value is modified, the whole widget is re-rendered. That means that we could hide fields when the widget is shown, but as soon as the user interacts with the form, it would re-render and show the fields again. We could try to hide them again after every re-render, but that would result in some weird flickering and would be a terrible user experience.

All that being said, I haven't actually tried this yet. I'll spend a few minutes on this, and see if it's possible after all.

**Comment by singingwolfboy** [comment]
Turned out that this was more possible than I expected! I've made #1882 to make this change.

**Comment by pdpinch** [comment]
@singingwolfboy can we check off the last box and close this now?

**Comment by singingwolfboy** [comment]
Yes, I believe we can.
