### ISSUE TITLE
FAQ categories should be scoped to individual programs

### ISSUE THREAD

**Issue by singingwolfboy** [mitodl/micromasters#1266]
This issue is related to #1232, and will be handled after that pull request is merged.

FAQ categories are currently global: all programs share the same set of categories. These categories cannot be reordered within a course: they are always displayed alphabetically. We want to change this, so that each program can define its own set of FAQ categories and order those categories however the program owner wants. @singingwolfboy attempted to accomplish this in https://github.com/mitodl/micromasters/commit/222f9358337eaafd2147035a49182d610fa3777f, but wasn't able to do so.

The basic problem here is limiting the Wagtail form to only allow the user to select from FAQ Category objects that are scoped to the current program. The Django ORM is not flexible enough to express this sort of relationship in a general way ([see this gist for an example of the problem](https://gist.github.com/singingwolfboy/ac8a8b6c04729b797f61e97916102a7d)), so we'll have to find a way to build a custom query to return all FAQ Category options based on a given Program object.

Ideally, program owners should also be allowed to customize the ordering of their FAQ categories, which probably means making the `FAQCategory` class inherit from `wagtail.wagtailcore.models.Orderable`.

**Comment by Ferdi** [comment]
@singingwolfboy  If FAQ is a "page type", it means that user can create more than 1 page each with some FAQs. We can treat pages as categories and render them on the same page 

what do you think ?

**Comment by singingwolfboy** [comment]
@Ferdi: I don't think that the question of whether it's a "page type" or not makes any difference, from a data modeling perspective. As I said, the Django ORM doesn't seem to be flexible enough to express this kind of relationship in a general way, so we have to customize the form.

I suppose it's possible that Wagtail will be more amenable to customizing the form for a Page model, rather than an inline form for a snippet... but I don't know. I wish I understood why overriding the `base_form_class` doesn't work.

**Comment by Ferdi** [comment]
@singingwolfboy I agree that figuring out how to override the base_form_class would be great but I'm not sure I follow your comment.

If you had a content type called "Blog" and created 100 blog items, you'd need a page to show blog listing. I'm suggesting the same thing FAQ content type (which we are doing here #1259).  Program owners would generate a couple of FAQ items like
"Fin aid questions"
- question1
- question2
  etc.
"Admission questions"
-question1
-question2
 etc.
etc.

And you'd simply print a listing of them.

**Comment by pdpinch** [comment]
fixed by #1332
