### ISSUE TITLE
Handle bad API calls for syncing currency rates

### ISSUE THREAD

**Issue by mirfark** [mitodl/micromasters#1267]
Syncing currency exchange rates (via openexchangerates.org) does not account for API failures. See DB's comment here: https://github.com/mitodl/micromasters/pull/1257#discussion_r82225605
Comment on tests: https://github.com/mitodl/micromasters/pull/1257#discussion_r82225774

**Comment by alvinsiu** [comment]
@pdpinch If the currency exchange API returns a non-200 status code (say, their API is temporarily down for whatever reason), and we are unable to update existing exchange rates, what are the business requirements for how to handle these cases?

- Should we wait a couple seconds/minutes/hours and try again?
- How long can the exchange rates be out of date before we should stop using those?
- What should we do on the frontend if exchange rates are out of date and shouldn't be used but a learner tries to submit a financial aid request with a non USD currency?

It might be worth implementing a simpler fix now, and then implement a more thought out plan after 10/15?

**Comment by pdpinch** [comment]
Log the error, and try again later. 

We don't have a lot riding on the currency of these exchange rates. If they are a day or two out of date, that's OK. 

I think the only concern would be if we're getting errors over a stretch of days. Maybe @blarghmatey has a suggestion about how to catch that.
