### ISSUE TITLE
return an error if user tries to upload a non-image file for avatar

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1273]
Currently, i can choose, for example, a .txt file in the avatar upload modal. I get no error message, but no image displays and when I click save, my avatar does not update. 

Looking at the console log, it looks like the PATCH API call returns a 400, probably because it's the wrong type of file.

**Comment by pdpinch** [comment]
@roberthouse54 any thoughts on what the right UX is here? It seems like we may not know for sure that it's a bad file until we try to upload it. But @aliceriot may know better.

**Comment by aliceriot** [comment]
Not sure exactly, I imagine there's something we can do on the frontend to check for a non-image file before we upload it.
