### ISSUE TITLE
CMS: Limit options for child pages

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1279]
Currently in the CMS you can add a page of any type as a child of any other type. This doesn't make sense. 

<img width="552" alt="screen shot 2016-10-06 at 2 03 32 pm" src="https://cloud.githubusercontent.com/assets/430126/19189349/8ff4e89a-8c65-11e6-914b-2e7e12587ee4.png">

- [ ] The home page should allow children of type program. 
- [x] Currently, the program page shouldn't allow children of any type. However, #1204 and #597 would presumably add new page types.

**Comment by Ferdi** [comment]
Maybe related ? https://github.com/torchbox/wagtail/issues/194

**Comment by pdpinch** [comment]
Actually, Anna addressed this in her FAQ PR #1259 -- at least for children of the program page.

**Comment by Ferdi** [comment]
Great !

**Comment by pdpinch** [comment]
#1259 limited program pages to have only FAQ children. But the home page can still have children of type home.
