### ISSUE TITLE
Financial Aid: front-end doesn't handle 400 error from API

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1282]
Steps to reproduce:

1. Click Calculate Cost
2. Set income to be $1000, currency to be Albanian lek, click checkbox
3. Click submit. 

Expected behavior:

View response of Financial Aid calculation

Actual behavior

Nothing happens. Looking in the JavaScript console I see a 400 error.

**Comment by pdpinch** [comment]
I didn't get a chance to capture the JS error or the stack trace. I'll try to update this later with that info.

**Comment by alvinsiu** [comment]
My guess on this is it's passing back "Currency not supported" - we had the same issue when we were testing.

#1235 and #1170 are relevant, though don't encapsulate a full solution to this problem.

From the perspective of the learner (let's take your example), I think it would be better to dynamically generate the currencies that are available from the ones we have on our backend to filter which currencies are displayed.  Then perhaps show a message that if the currency isn't displayed, it isn't currently supported and that they should submit using a different currency (should we also display a link to, say, the Google currency converter?).  As another redundant measure, we should probably have a visual error if they hit "currency not supported" anyway.
