### ISSUE TITLE
Submitting cost calculation with error response has no UX change

### ISSUE THREAD

**Issue by alvinsiu** [mitodl/micromasters#1285]
Spawned from #1282 for handling after MVP

The most likely scenario is submitting a not-supported currency.
#1275 handles general syncing of frontend-supported and backend-supported currency codes, but there may be a rare case where a learner may end up submitting a code that isn't supported.

The learner should get some sort of message when errors come up when they click calculate cost, perhaps directing them to the helpdesk or telling them to refresh the page and try again.

**Comment by pdpinch** [comment]
I'd also like to see this error show up in Sentry

**Comment by roberthouse54** [comment]
Will it actually help to refresh the page? So this is just going to be an error page, correct? As opposed to a form error? I just want to understand before designing something. Perhaps we should just come up with a generic design for an error page that can handle this and other error types.

**Comment by pdpinch** [comment]
Updated title because this also happens with a 500 error, caused by a ImproperlyConfigured exception.

**Comment by pdpinch** [comment]
@roberthouse54 this server call doesn't cause a page refresh, so when it fails, the user doesn't see any change to the page. I would be happy with a generic error UX.
