### ISSUE TITLE
Financial Aid: expand country names in review form

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1287]
We store learner's countries as ISO codes currently and those are displayed in the review form. Unfortunately, that's not too helpful for financial aid reviewers. 

Inside of "AL" I'd like to see "Albania"

**Comment by pdpinch** [comment]
I'm not sure what's the best way to do this, given #828

**Comment by alvinsiu** [comment]
@aliceriot Do we have a JS library or similar to handle country/territory code conversions to full names?

If not, I can look into a simple JS or Python library to do these conversions for MVP.

**Comment by aliceriot** [comment]
go take a look at #1275, I implemented a tiny method called `codeToCountryName` that should put you on the right track.

**Comment by alvinsiu** [comment]
Thanks, that was exactly what I needed!
