### ISSUE TITLE
Faculty thumbnail images on the program page are cropping to the wrong size.

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#1292]
The faculty images on the program page are supposed to crop to an aspect ration of 500px wide and 385px tall. Currently they seem to be cropping to a square that is 385px by 385px.

Basically what we are shooting for is that a user uploads a hi-res image that is equal to or larger than 500x385 in both directions, and then they are cropped to the correct aspect ratio.

**Comment by noisecapella** [comment]
here is the relevant code for reference: https://github.com/mitodl/micromasters/blob/master/cms/serializers.py#L21
