### ISSUE TITLE
404 page UI is broken

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#1293]
![screen shot 2016-10-07 at 1 06 55 pm](https://cloud.githubusercontent.com/assets/1005204/19198828/056563c4-8c8f-11e6-840b-7beb40e2447f.png)

## Related Issue

#1299

**Comment by roberthouse54** [comment]
![image](https://cloud.githubusercontent.com/assets/20047260/19363283/e0931078-9157-11e6-815e-4061ce15de68.png)
