### ISSUE TITLE
Handle invalid dates:

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#1294]
![screen shot 2016-10-07 at 1 31 27 pm](https://cloud.githubusercontent.com/assets/1005204/19199515/6ce3117e-8c92-11e6-8302-4ae135f1b38c.png)

**Comment by aliceriot** [comment]
@pdpinch what should be shown instead?

**Comment by roberthouse54** [comment]
What is the context of this? Why would there be invalid dates?

**Comment by aliceriot** [comment]
I'm not sure exactly what would lead to that, perhaps if there are fields which are option on edX?

anyway, it's pretty easy to handle this in the JavaScript, we just need to think of what to show if there is an invalid date.

**Comment by roberthouse54** [comment]
If there is an invalid date, does that mean we do not know the payment due date? If so, it seems that we would not know if the date is passed or not.

**Comment by pdpinch** [comment]
I don't know why the UI is presenting "invalid date" at the moment. If date is `none` then I suggest we omit the whole block starting with "Payment Due" but I will be doing my best to get actual dates for these fields.
