### ISSUE TITLE
Move auto-approval income thresholds into database

### ISSUE THREAD

**Issue by alvinsiu** [mitodl/micromasters#1301]
I think @noisecapella mentioned this last week, but we should move these constants into the database since leaving it in the codebase if it's open sourced could allow people to maliciously use this information.

**Comment by alvinsiu** [comment]
@pdpinch Is this something important for MVP?  If so, we're happy to do this real quick.

**Comment by noisecapella** [comment]
They will still be able to look in the history of this repo

**Comment by alvinsiu** [comment]
That's true, but it's probably better than having it in plaintext for now.

**Comment by noisecapella** [comment]
I agree

**Comment by Ferdi** [comment]
That would be great.

**Comment by alvinsiu** [comment]
I've made a PR for this - will we also need some sort of way to import all of these, or is the django admin way sufficient for now?  (There's a lot of countries)

**Comment by Ferdi** [comment]
Django admin is fine

- Sent from my phone
