### ISSUE TITLE
Change address and phone number for financial aid applications

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1302]
Address:

```
MIT Economics Department
DEDP MicroMasters
100 Main Street
Cambridge, MA  02139
USA
```
Fax Number: `+1 617-715-5799`

From Anna Schrimpf on 10/7:

> I’m trying to get a specific locked post box for the DEDP MM; so the address will change slightly once I know which number we will be assigned. We can add a line like “DEDP MicroMasters” as the first address line as a placeholder for now.

> The fax number is 617 715 5799.

**Comment by aliceriot** [comment]
phone number is already correct. updating the address.
