### ISSUE TITLE
Set up google analytics to track more events

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#132]
We should instrument both the public part of the site and the dashboard. We have the infrastructure set up but we don't send any GA events yet.

Here are the events we should track for MVP:
- [ ] any page view
- [ ] successful OAuth login via edX
- [ ] dashboard view (if not already tracked by page views)
- [ ] user completes profile
- [ ] profile view (if not already tracked by page views)

Post-MVP:
- [ ] learner clicks enroll button
- [ ] learner clicks 'upgraded to verified' button

**Comment by bdero** [comment]
I've just configured micromasters-ci and micromasters release to use their respective tracking IDs. New micromasters review apps will also use the micromasters-ci tracking ID.
Does this issue refer to configuring the environments, or building out functionality to send tracking events?

**Comment by pdpinch** [comment]
Sorry I think I misunderstood the issue to mean specifically what @bdero but reading it again it seems like there is more to be done. 

@noisecapella what needs to be done for the GA events? Do you need me to define them?

**Comment by noisecapella** [comment]
@pdpinch Yes we should define what events are tracked just to clarify the scope of the issue

@bdero this only refers to actually sending out tracking events, we have the infrastructure set up and in place already

**Comment by pdpinch** [comment]
Now I see what happened. @bdero you actually completed #94? Can we close that?

**Comment by pdpinch** [comment]
Events that should be tracked:

- [ ] any page view
- [ ] admin page views (if not too much trouble)
- [ ] OAuth login via edX
- [ ] dashboard view
- [ ] learner clicks enroll button
- [ ] learner clicks 'upgraded to verified' button
- [ ] learner open profile form 
- [ ] learner saves profile form

I think that's all that's reasonable for currently scheduled work. This story isn't even in the current sprint.

**Comment by pdpinch** [comment]
FWIW, I'm seeing pageviews come across for `/dashboard/` but nothing else. I'm guessing this is because we're configured GA as a react component but the home page doesn't use react.

**Comment by pdpinch** [comment]
I'm gong to close this. We've done two passes now on GA events. We can add more when we specifically need them.
