### ISSUE TITLE
Set up Cybersource email account

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1327]
Not sure if this is already set up but we should have a dedicated email account for the Cybersource post-back receipts.

**Comment by pdpinch** [comment]
Do you think this should be a real e-mail address, a mailing list, or something that passes through maligun and goes into a database?

**Comment by noisecapella** [comment]
We just need some account to hold onto the receipt emails, it should just be a backup to the `Receipt` object we are storing in the MM database. Occasionally our server may go down and it would let us know if there are transactions which weren't recorded in the database

**Comment by pdpinch** [comment]
Sent request to accounts at mit.edu 

```
First/Last name:  ODL CyberSource
Kerberos name:  odl-cybersource-receipts
Sponsor:  Peter Pinch
Backup:  Bill Barrasso 
Use case:  Every time ODL initiates a transaction in MIT's CyberSource account, an e-mail receipt is generated. We'd like to capture these and store them as a back-up, in case there are any fulfillment problems.
Alternatives:  we'd like to store these receipts in a safe, shared location. We don't need multiple copies being distributed. 
```

**Comment by pdpinch** [comment]
@noisecapella the address is odlcyber@mit.edu

(name was limited to 8 characters)

**Comment by pdpinch** [comment]
I changed the Merchant POST email on the test business center and the prod business center to use odlcyber at mit.edu 

I think we're all set.

**Comment by noisecapella** [comment]
:+1:
