### ISSUE TITLE
Description extends past faculty tile

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1331]
From https://github.com/mitodl/micromasters/pull/1300#issuecomment-253048214

![ss 2016-10-11 at 17 12 42](https://cloud.githubusercontent.com/assets/14932219/19288836/f8b26b64-8fd5-11e6-9a87-1688e00d68e5.png)

looks like the description isn't being properly contained. that should fall under this PR, right?

**Comment by pdpinch** [comment]
@roberthouse54 is this still an issue?

**Comment by roberthouse54** [comment]
Should be fixed.
