### ISSUE TITLE
Industry should search in the text

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#1340]
If I type the second word, it does not select it.

![screen shot 2016-10-12 at 11 30 28 am](https://cloud.githubusercontent.com/assets/1005204/19316439/6f24471a-906f-11e6-8914-f9f1c059e639.png)

![screen shot 2016-10-12 at 11 32 08 am](https://cloud.githubusercontent.com/assets/1005204/19316467/8ad0b318-906f-11e6-9f97-4adfa5ded79d.png)

![screen shot 2016-10-12 at 11 30 54 am](https://cloud.githubusercontent.com/assets/1005204/19316440/70c0bacc-906f-11e6-8ffd-e071815fdb45.png)

**Comment by aliceriot** [comment]
this is fixed by switching to react-select.
