### ISSUE TITLE
If user is assigned the zero discount tier, we should proceed as if they were auto-approved from a UX point of view

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1341]

**Comment by pdpinch** [comment]
Is this not what happens?

**Comment by noisecapella** [comment]
It might be a configuration problem on my end actually, I'll do some more research

**Comment by noisecapella** [comment]
I think this is a legitimate problem. The income threshold used to determine auto approval can be different from the income threshold for the financial aid tier. I'm not sure if that's ever the case for DEDP but I think we should handle the case anyway, in case the tiers or thresholds change over time.

**Comment by alvinsiu** [comment]
I agree with George - currently, because of the way DEDP set up their python file, if you submit an income of exactly 75k and live in the US (or any other 75k country), you won't be auto-approved, but you will be assigned the 0 discount tier.

We could also solve this in the backend, marking them as auto-approved regardless of auto-approval determination if they are assigned the 0 discount tier.  It would probably easier than making front-end changes.  This does have some business requirement implications, though.

**Comment by pdpinch** [comment]
I'll ask Anna Schrimpf in DEDP about changing this.

**Comment by pdpinch** [comment]
Here's the response. @alvinsiu or @zags can you confirm whether this is a change from the algorithm as delivered?

> I thought we had agreed that the thresholds should be interpreted as “smaller than or equal to”? So then at 75,000 exactly you would be in the third price tier, and you will be quoted 500 and asked for verification. At 75,001 you would be in the highest tier, quoted 1000 and not asked for verification. 

> People in highest price tier would never be asked for verification

**Comment by noisecapella** [comment]
From the source it looks like it's just "smaller than", not "smaller than or equal to"

**Comment by alvinsiu** [comment]
We implemented it the same way as it was in the python file that was sent to us, so this would be a small change from what is currently implemented.

**Comment by pdpinch** [comment]
Can you give me a line number and file name to reference that I can use when I contact the course team about this?

**Comment by zags** [comment]
DEDP_final.xls describes the tiers as "< 25,000; 25,000 to 50,000; 50,000 to 75,000; and > 75,000", which could not be more ambiguous on this point.

https://github.com/mitodl/micromasters/blob/master/financialaid/api.py#L33 is the comparison for tier placement (income <= tier cap)
https://github.com/mitodl/micromasters/blob/master/financialaid/api.py#L65 is the comparison for auto approval (income > country threshold)

Either of these can be changed; we just need to know how

**Comment by pdpinch** [comment]
Re-reading this thread, I think the easiest and most generally-applicable solution is to do what George wrote in the title: If user is assigned the zero discount tier, we should proceed as if they were auto-approved from a UX point of view
