### ISSUE TITLE
Enroll now link doesn't change after user clicks it

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1344]
It enrolls the user in audit mode in edX and refreshes the dashboard, but since there's no change in course status the link remains. I haven't tried the non-financial aid path yet

**Comment by pdpinch** [comment]
Why is there no change in course status?

**Comment by gsidebo** [comment]
i haven't experienced this. might need to try this out with a FA path

**Comment by noisecapella** [comment]
I tried it with a FA course I just created and I can't reproduce the problem. Maybe it was a configuration error on my machine?

**Comment by pdpinch** [comment]
I have not been able to reproduce this either. I'm leaving this open because I want to do some more testing, but I don't consider it a release blocker any more.
