### ISSUE TITLE
Mailing list signup has Email validation issues

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1347]
Steps to Reproduce
Log into micromasters.herokuapp.com
Scroll down to the Program Tiles section
Select the "Sign up for Mailing List" button
A form pops up.
Note the various email validation messages in the screen shots below.

NOTE that the system accepts an email with the following syntax:
x@x.x (screen shot #3)

Screen Shot #1 (validation on the @)
![email validation](https://cloud.githubusercontent.com/assets/13886722/19323382/b0348178-908a-11e6-8296-3d5b55dceae5.PNG)

Screen Shot #2 (validation on the domain)
![email domain validation](https://cloud.githubusercontent.com/assets/13886722/19323401/b92f8f84-908a-11e6-8e27-9a6de9fdfc66.PNG)

Screen Shot #3 (accepts an invalid email)
![email validation radio buttons](https://cloud.githubusercontent.com/assets/13886722/19323439/f07fc0da-908a-11e6-9bc9-a1f490f4a5ba.PNG)

**Comment by pdpinch** [comment]
mailchimp has its own mechanism for validating e-mail addresses
