### ISSUE TITLE
'Passed' doesn't show if user has passed but not purchased course run

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1354]
This may be fine, not sure what we should have in the UI

**Comment by pdpinch** [comment]
I think this the same as #1121 and I don't think this is a bug. We can't give credit to folks who haven't paid.

**Comment by pdpinch** [comment]
What happens if the user has a passing grade, but the course end date hasn't passed?

Similarly, what happens if the learner has a passing grade and the upgrade deadline hasn't passed?

**Comment by noisecapella** [comment]
From reading the source, the user will not have status 'passed' unless the course end date is passed, no matter what edX says. It does not look like the upgrade deadline is checked at all when deciding the 'passed' status

**Comment by noisecapella** [comment]
I think this is a duplicate of #1121
