### ISSUE TITLE
Add link to "Complete Instructions" for users who have to submit Income Verification documents.

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#1358]
Turns out that there is a lot of copy explaining exactly what a user has to submit for Income Verification documents. We will add a link to the dashboard which opens a popup containing these instructions. Ideally these instructions would ALSO be on the FAQ tab of the program page. So ideally we could just pull that content into the popup.  See mocks below:

![image](https://cloud.githubusercontent.com/assets/20047260/19327269/18dc8214-909c-11e6-84d2-e28770dcd7a4.png)

![image](https://cloud.githubusercontent.com/assets/20047260/19327254/0a261546-909c-11e6-8c9f-3a9cba1cc5d8.png)

**Comment by pdpinch** [comment]
@roberthouse54 do we want to add a link to this also from the calculator?

**Comment by roberthouse54** [comment]
No, not from the calculator.

**Comment by aliceriot** [comment]
do we have the copy for this?

**Comment by roberthouse54** [comment]
Yup:

Whose income should I report?
   
Please report your own household income; that is, the combined income of all people that are part of your household or place of residence. If you live with, or are financially supported by your parent(s)/legal guardians, please enter their combined income instead. For example, if you are a full-time student with no income of your own, you should declare the combined income of your parents or legal guardians instead.    


What documents do you require to verify the income information I entered?
   
If we ask you for supporting documentation to verify the income you declared, we require that you submit the a photocopy of the most recent tax return of all income earners in your household as defined above.


What if I am unable to provide you with a tax return?

If you unable able to provide us with your tax return form, we will accept notarized income statements. An income statement is a statement of annual salary, printed on the official letterhead of the relevant employer (including the employer’s address and contact information) and signed by the employer. Notarization means that the income statement you submit to us has to signed by an authorized notary and contain his or her official seal/stamp and contact information. If your household income is based on more than one earner, you have to submit notarized income statements for each of the people whose income you used to calculate total household income.


What if I am unemployed, and not a student?
   
Please submit either one of the following: a tax return (filed for zero income), a photocopy of an official receipt or check of unemployment benefits received, or a notarized letter verifying your unemployment status.


What should I do if my financial documents are written in a language other than English?

Please submit notarized income statement(s) in English, if at all possible. If the employer(s) in question are unable to provide you with income statement(s) written in English, you have to provide a translation of the statement(s) and submit this along with the original, notarized income statement when you mail or fax your documents. If you are submitting a tax return in a language other than English, you also have to provide a translation in addition to the tax return. We do not require the translation to be certified – you can translate the document yourself.

**Comment by aliceriot** [comment]
thanks!
