### ISSUE TITLE
Calculator text changes

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1361]
Based on feedback from DEDP:

- [x] The price range should be $100 - 1000 (ideally this reange should come from the dashboard API
    See [FinancialAidCalculator.js#L144](https://github.com/mitodl/micromasters/blob/9e4c9a3be52b2f1ab5ca5bc71646f70662d2a44d/static/js/containers/FinancialAidCalculator.js#L144)
- [x] Change the line at [FinancialAidCalculator.js#L145](https://github.com/mitodl/micromasters/blob/9e4c9a3be52b2f1ab5ca5bc71646f70662d2a44d/static/js/containers/FinancialAidCalculator.js#L145) to be `based on your ability to pay`
- [x] Change the line at [FinancialAidCalculator.js#L63](https://github.com/mitodl/micromasters/blob/9e4c9a3be52b2f1ab5ca5bc71646f70662d2a44d/static/js/containers/FinancialAidCalculator.js#L63) to be `I am aware that I may be asked to verify the reported income with documentation.`

**Comment by aliceriot** [comment]
should we hard-code the price ranges? right now we're using what comes back from the course price api.

**Comment by Ferdi** [comment]
We should not hard code values.   It looks like DEDP looked at some screenshot where values where not correct.

**Comment by pdpinch** [comment]
AFAICT, the price range is hard coded currently at https://github.com/mitodl/micromasters/blob/9e4c9a3be52b2f1ab5ca5bc71646f70662d2a44d/static/js/containers/FinancialAidCalculator.js#L144 -- this should be changed.

**Comment by noisecapella** [comment]
Yes, we do use the price from the API for `FinancialAidCard` but it looks like we missed this one
