### ISSUE TITLE
Search: hide facets when they have no hits

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1362]
This looks bad (no current grades in search results):

![image](https://cloud.githubusercontent.com/assets/430126/19387627/687aa492-91e9-11e6-900d-d7458b6f01db.png)

**Comment by roberthouse54** [comment]
![image](https://cloud.githubusercontent.com/assets/20047260/19354179/da47903c-9133-11e6-8e89-c9c4726a020b.png)

**Comment by roberthouse54** [comment]
So this state will happen as follows:

1. The "Filter box" in the left column will only be empty if there are no users in a program.
2. The "Results box" in the right column will be empty either if there are no users in a program (as shown above), OR if the user has selected some filters and there are no results.

For point 2, we could show a different message depending on the reason the box is empty, or we could just show the same message for both cases, as I am assuming that is easier to do.

**Comment by pdpinch** [comment]
@roberthouse54 I'm going to open separate issues for your design changes.

**Comment by pdpinch** [comment]
#1390 and #1391
