### ISSUE TITLE
Search: return error messsage on failed permissions

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1366]
The search API appropriately prevents users without the appropriate role from searching. However, the UI is not clear about why the search failed. 

<img width="986" alt="screen shot 2016-10-13 at 12 02 04 pm" src="https://cloud.githubusercontent.com/assets/430126/19356778/eecf6bde-913c-11e6-8a36-1721c937802e.png">

**Comment by pdpinch** [comment]
@roberthouse54 what are your thoughts on this? Should we direct the user to a generic error page (usually a 404 for permissions failures) or return something in the UI?

**Comment by Ferdi** [comment]
This is clearly a 404 or 403

**Comment by amir-qayyum-khan** [comment]
@pdpinch @Ferdi 

- in case of no results on search page there is pr for this https://github.com/mitodl/micromasters/pull/1449
 
- if user is neither staff nor instructor should we take him to 404 in case he hit learners page?

**Comment by pdpinch** [comment]
Yes. See #1366
