### ISSUE TITLE
Sort FAQs Categories in FAQ page

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#1371]
#1332 Implemented FAQs Categories but not an explicit sorting.

**Comment by annagav** [comment]
You can sort pages in wagtail directly, by dragging the pages around.

![screen shot 2016-10-18 at 2 47 41 pm](https://cloud.githubusercontent.com/assets/7574259/19491555/62a333d0-9541-11e6-9f7c-eb662e4b358d.png)

**Comment by Ferdi** [comment]
@annagav great !  should we close this issue ?

**Comment by annagav** [comment]
Yes, unless @giocalitri had something else in mind for sorting.

**Comment by giocalitri** [comment]
I was talking about the categories in the page that includes all the FAQs.
If those are controlled by the sorting you are talking about, then we can close this issue.

**Comment by annagav** [comment]
Yes, I can change the order of categories as well.

**Comment by Ferdi** [comment]
@annagav so, does the sorting order on this page  is respected when print out the /frequently-asked-questions page ?

**Comment by annagav** [comment]
yes
