### ISSUE TITLE
The backend code to fetch the user profile should handle errors

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#1374]
if the request to `/api/mobile/v0.5/my_user_info` fails, the app crashes

this might be dependent on #1375

**Comment by amir-qayyum-khan** [comment]
@giocalitri i was thinking to look into https://github.com/omab/python-social-auth/blob/f13a5cc3c8670a1a3bbc16410bb30ac0423d9934/social/backends/base.py#L228,

we cant catch exception here by overriding this method, 
2nd if response has error we can log it and exit from here

why do you think?

**Comment by giocalitri** [comment]
the problem with this approach is: what happens to the user in Micromaster? this API is called during the login and if it is the very first login, we might leave the user locally in an inconsistent state.

So the approach might be good depending on what happens to MM.

**Comment by amir-qayyum-khan** [comment]
so if that is the scenario then we should display error messages on MM or
may be we can log him out.  (first time login)

else if there is already data cached on MM then we can use that, ( we can
cache user api),  if no cache available then need to go with logout/error
message

**Comment by giocalitri** [comment]
It can work if nothing is created for that user in the MM database.
But it is still unclear to me how you make the Pipeline of the Python Social Auth stop without an exception.

**Comment by pdpinch** [comment]
We decided that there wasn't any user benefit to making this change.
