### ISSUE TITLE
The edxorg backend should use edx-api-client library and not do direct calls

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#1375]
We should implement a client in `edx-api-client` for the user profile infos to handle 
`/api/mobile/v0.5/my_user_info`
and than remove the direct calls in the edxorg backend.

**Comment by pdpinch** [comment]
@noisecapella was this closed by #33?

**Comment by noisecapella** [comment]
We still need to upgrade the version of edx-api-client used here and switch to use the new function
