### ISSUE TITLE
Search: display error message when there are no users in program 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1390]
The "Filter box" in the left column will only be empty if there are no users in a program.

The "Results box" in the right column will be empty either if there are no users in a program (as shown above), OR if the user has selected some filters and there are no results.

![image](https://cloud.githubusercontent.com/assets/20047260/19354203/f2819882-9133-11e6-8d43-22e5585d38c8.png)

**Comment by amir-qayyum-khan** [comment]
depends on https://github.com/mitodl/micromasters/pull/1407

**Comment by pdpinch** [comment]
Why does this depend on #1407?
