### ISSUE TITLE
In Profile Flow, MicroMasters link in header is confusing

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1394]
If a user hasn't completed their profile and the click the MicroMasters link in the header, that triggers validation alerts on the page.
Per Peter, this is the intended behavior.  In this case, we should remove the MicroMasters link.

Steps to Reproduce:
Create an account in edX.
Don't complete the profile info.
Select a program.
Click on Login.
After logging in, click on the MicroMasters link in the header.
**note** it's not the regular link -- only text is displayed, we've lost the MicroMasters Logo.

First Screen shot shows the incomplete profile:
![profile path - initial](https://cloud.githubusercontent.com/assets/13886722/19392291/331a4072-91fe-11e6-80de-6de0837cb4ac.PNG)

Second Screen shot shows the display when a user clicks on the MicroMasters link in the header:
![profile path - post header link](https://cloud.githubusercontent.com/assets/13886722/19392334/609ea538-91fe-11e6-83be-91ef420a73a2.PNG)

**Comment by Ferdi** [comment]
So, leave it as text (remove the link) from profile pages.
