### ISSUE TITLE
Birthdate year validation on the Profile Page is incorrect

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1405]
A user can enter a value for their date of birth year ranging from 1800-2100.
Steps to reproduce:
Log onto MicroMasters.
Create a new edX profile.
On the first profile page, tab down (or mouse) to the Date of Birth Field.
For the Year value if a user enters "1111" the value changes to "1800"
(or you can manually enter 1800).
Similarly, a user can enter a value greater than 2017 all the way up 2100.
(or you can enter "5555" which reverts to "2100")
![1800](https://cloud.githubusercontent.com/assets/13886722/19402360/bc187350-922e-11e6-8afc-756435e75858.PNG)
![210](https://cloud.githubusercontent.com/assets/13886722/19402367/c650d876-922e-11e6-8c65-fb1f47b6cb29.PNG)

**Comment by noisecapella** [comment]
It makes sense for the upper limit to be today, but what would you suggest for a lower limit?

**Comment by j2tausig** [comment]
Current year - x  (x=100?  that may be too high)

**Comment by noisecapella** [comment]
It seems like we should allow any valid birthday, and it's possible someone older than 100 might sign up for this

**Comment by aliceriot** [comment]
how about `moment().subtract(120, 'years')`?
