### ISSUE TITLE
Preferred Language options are confusing

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1411]
Some of the options in the Preferred Language list are confusing:
![language](https://cloud.githubusercontent.com/assets/13886722/19439230/5d3237d0-944b-11e6-910b-9b4df15077c7.PNG)

It appears as though they may be duplicate information.

Steps to reproduce:
Log into MicroMasters.
Created a new profile in edX.
Navigate to Preferred Language Field.
View the Drop Down of Language Choices -- there appear to be approximately 11-12 entries that don't make sense.

**Comment by amir-qayyum-khan** [comment]
So you want single entry here, not ; ?

**Comment by pdpinch** [comment]
The double names appear to come from the [Library of Congress](http://www.loc.gov/standards/iso639-2/php/English_list.php). 

There are a few dozen that have semicolons in them. Some of these seem to be addressing alternate spellings, which I think we should keep. A few seem to be addressing alternate word order. I don't think we need these. 

@amir-qayyum-khan let me know if this is clear enough for you to work on.

**Comment by j2tausig** [comment]
@amir-qayyum-khan Amir -- "Greek, Modern (1453-)" should probably be changed to "Greek"  Thank you.

**Comment by amir-qayyum-khan** [comment]
ok got it
