### ISSUE TITLE
Deleting a staff role should immediately restrict access to the financial aid review form

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1412]
After deleting my staff role, I can still access the financial aid review form.

Steps to reproduce:

1. login with a user who has the staff role on a program that offers financial aid
2. access the financial aid review form
3. through the django admin, delete the staff role for that user on the program being tested
4. reload the financial aid review form

## Expected Behavior

page returns a 403 error

## Actual behavior

Form returns as if user still has the role.

**Comment by pdpinch** [comment]
I'd like to do a little more testing on this, but I didn't want to wait too long before fixing it.

**Comment by alvinsiu** [comment]
The behavior works as expected for me - it's possible your `User` is a superuser, in which case it will still allow access even if the staff role is deleted.
