### ISSUE TITLE
Mobile Sidenav

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#1414]
This is a design for a mobile sidenav, that is in line with Material Design guidelines. This PR is only about the sidenav.

- All the navigation that is currently in the navigation bar will be moved into the sidenav. This includes: 
- Program selector 
-  A link to "View Profile"
- A link to "Edit Photo" (this is added.)
- A link to "Settings"
- A link to logout.

The navbar will not display any links in mobile. There will be a "hamburger" icon at left that opens the sidenav. Swiping left, or hitting the back button should close the sidenav.

Logging out should go back to displaying the normal logged out navbar, which does not have a hamburger menu. (ie. there are no changes to the logged out view of the nav.)

![image](https://cloud.githubusercontent.com/assets/20047260/19442235/a8732adc-9456-11e6-9e8f-845ce5704ff6.png)

**Comment by pdpinch** [comment]
@roberthouse54 can you put this into invision so we can discuss?

**Comment by roberthouse54** [comment]
https://invis.io/K68ZSLC3U#/197917425_Mobile_Sidenav

**Comment by aliceriot** [comment]
@roberthouse54 what do you think would be best for a width for the sidenav, a percentage of the viewport or a fixed pixel width?

**Comment by aliceriot** [comment]
my concern is that percentage might look weird on bigger phones n stuff
