### ISSUE TITLE
Restore accordions (hide/show) on Program FAQ pages

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1415]
Not sure how this was lost, but the FAQs used to default to a state where the answers were hidden, making it easier to browse all the questions (like http://scm.mit.edu/micromasters/faqs).

**Comment by roberthouse54** [comment]
![image](https://cloud.githubusercontent.com/assets/20047260/19451584/c9f6c43c-947b-11e6-817f-515ba923cc46.png)
