### ISSUE TITLE
ecommerce: pass edx_course_key and courserun.title to cybersource

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1422]
To make it easier for backoffice processing of orders, we'd like to pass the edx_course_key and the course title to Cybersource.

**Comment by pdpinch** [comment]
@noisecapella does #1438 also express the edx_course_key and the course.title in the e-mail receipt that's sent to the user?

**Comment by noisecapella** [comment]
No, I think there's a way to do that however. Should I look into it?

**Comment by noisecapella** [comment]
Actually I'm wrong about that, it appears this did make that change. Here's what it looks like:

![screenshot from 2016-10-19 12-25-43](https://cloud.githubusercontent.com/assets/863262/19527777/5862f8d6-95f7-11e6-8b84-8db5e9cfab72.png)
