### ISSUE TITLE
ecommerce: display course title to user on CyberSource checkout page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1423]
So that users can confirm that they are paying for the course they meant to pay for. 

This will require some discovery on the CyberSource APIs.

**Comment by noisecapella** [comment]
This looks promising: https://support.cybersource.com/cybskb/index?page=content&id=C173&actp=RSS

I don't think I have access to edit the 'Virtual Terminal' part of the business center. Do you know who has access for that?

**Comment by noisecapella** [comment]
I can see the virtual terminal in the business center now and it looks like it's just a way for us to enter purchase information manually, as if we were doing this over the phone or in person for example. The extra fields are just for people using the virtual terminal, they aren't used in the secure acceptance app that the customers would see

**Comment by pdpinch** [comment]
Next try Cybersource support

**Comment by pdpinch** [comment]
Opened a ticket with CyberSource, https://support.cybersource.com/cybskb/index?page=caseDetail&eTicketNumber=1-364121591&tabReq=myCases

**Comment by pdpinch** [comment]
Cybersource support responded to say that this isn't possible:

> My product engineer has checked that the option to display order line items is not available unfortunately.

> For your info, we have requested this as an enhancement last year but got rejected by our Dev team for the fact that they would recommend the iframe option, which allows merchants to display order line items. If you require this, you will need to utilize the embedded version of Secure Acceptance and display those order line items on your page. 

At the moment, I don't think it's worth considering their suggestion of using an iframe. But we should keep that option in mind for the future. 

FYI @noisecapella @Ferdi
