### ISSUE TITLE
Move Error Message on the Upload a Profile Photo Pop-up

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1428]
If a user tries to upload a non-image file to their Profile, we are displaying error messaging to the user, but
because the pop-up window is so large, unless they scroll to the bottom of the window the user never sees the error message.

Suggest that we either shrink the size of the window or handle the error messaging differently.

Steps to reproduce:
Log into MicroMasters
Create a profile on edX
Go to the first profile tab and click on the camera icon at the top.
Click on the pop-up, change the file type to "all files" and chose a non-image file to upload.
First screen shot shows the non-scrolled error message:  you will see that the error message is not displayed.
![non image photo](https://cloud.githubusercontent.com/assets/13886722/19452677/ec6da2f2-947f-11e6-8421-7f683f05c925.PNG)

Second screen shot shows the same window, scrolled to the bottom so the error message is visible.
![non image photo scrolled to error](https://cloud.githubusercontent.com/assets/13886722/19452705/096d132e-9480-11e6-8438-7a307f5b6995.PNG)

**Comment by aliceriot** [comment]
ah, I suspect this is just a small screen size issue. I think the scroll bar looks ugly, so we should try to set a height that's reasonable on all devices.

**Comment by pdpinch** [comment]
Yes please!
