### ISSUE TITLE
optimize images

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1430]
The home page image of the dome is 6.5MB. That's way too big. 

We should also take a look at the image sizes in the CMS.

**Comment by roberthouse54** [comment]
This is all set. I fixed the images in the CMS, and optimized the dome image (now ~400k).

**Comment by pdpinch** [comment]
When you say, "in the CMS" do you mean in production?

Is there a PR for the dome image?

Is there anything else that can be optimized?

**Comment by roberthouse54** [comment]
Yes, I re-uploaded the images to production. I am going to do a PR that is mainly refactoring the buttons, and this will include the new dome image, and also all the corrections for the text to "MITx MicroMasters". I think that should be all the image optimization. I guess we could further optimize the images if we want to, to make them smaller...

**Comment by noisecapella** [comment]
We are already sending the user nearly 1 MB of javascript
