### ISSUE TITLE
Mailgun configuration

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1433]
Mailgun configuration:
- [x] What is current IP
- [ ] whitelist IP at MIT

**Comment by pdpinch** [comment]
@blarghmatey can you update the description of this with the current status of our Mailgun configuration?

In particular, did IS&T take care of the white-listing?

**Comment by blarghmatey** [comment]
The current shared IP is not on any blacklists, so our reputation is good enough that mail is mostly being delivered to @mit.edu addresses, though occasionally delayed. The last response from IS&T suggested that they weren't going to whitelist us and that we needed to continue sending mail and improve our reputation. The text of their reply is pasted here for reference:

> Hi Tobias,
> 
> The MIT mail servers use a dynamic scoring system to rank the reputation of a sending mail server's IP address. As more legitimate mail is received, the reputation will improve. If more spam is received the reputation decreases. The MIT mail servers will then defer some connections from mail servers with lower reputations to provide more resources to those with higher reputations (otherwise spammers would monopolize the mail server's resources). If a connection is deferred, it is not a rejection of the mail message, but simply a request to re-connect and try again later. It takes some time to develop that reputation at first.
> 
> Currently the IP address 209.61.151.228 has a good reputation, but at its current reputation score it may still experience some deferrals (looking at the logs, the majority of the messages are being accepted, but some are getting deferred). The next reputation level up from where it is now there should not be any deferrals.
> 
> Let's give it some time for the reputation to improve on its own since it is a relatively new IP sending mail. I'll keep an eye on it. Also feel free to send more legitimate mail through that IP. Every legitimate message will help improve it's score.
> 
> Thanks.

**Comment by pdpinch** [comment]
Given the ambiguous response from IS&T, I'll close this and open another issue for mail monitoring
