### ISSUE TITLE
Need solution for being able to enter text in fields with a dropdown

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1437]
Currently, if a user types in a field with a drop down, unless that text exactly matches an entry in the dropdown, when they tab off the field,  it clears the values in that field.
(This also came up in the usability testing this afternoon)

@pdpinch @roberthouse54 
Please let us know what solution is agreed upon.

**Comment by pdpinch** [comment]
This has been replaced by #1519 and #1510
