### ISSUE TITLE
Enroll and pay later:  Better to not reload the whole dashboard page

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#1445]
Can we make this so only the relevant part of the page gets updated (e.g. course status) without full reload of the page ?

https://share.viewedit.com/z4ReSsmdB9z22LicyaFz7a

**Comment by pdpinch** [comment]
There may be some code that can be used from the order callback process.

**Comment by pdpinch** [comment]
@roberthouse54 what should be the UX here? Do we put up a spinner over the link, or over the whole card, or something else?

**Comment by roberthouse54** [comment]
Here is what I propose we do. When the user clicks Enroll and Pay Later, we show the spinner as we do now, then we put an overlay over the whole card, with a checkmark, and the message, "You are now auditing this course <br>But you still need to pay to get credit." After a few seconds, this fades and we see the Auditing status.

![image](https://cloud.githubusercontent.com/assets/20047260/21231347/f09e52cc-c2b5-11e6-94e5-7aea94a592b0.png)

**Comment by Ferdi** [comment]
@roberthouse54  This looks good.  One question re:

>  we show the spinner as we do now

Do we currently show a spinner ?

**Comment by roberthouse54** [comment]
Yeah, George just recently added spinners for pretty much any time a button is submitted. Not sure if those changes are all merged or not

**Comment by noisecapella** [comment]
They should be all done now

**Comment by Ferdi** [comment]
@noisecapella this looks like a but, only the one you click should spin 

https://share.viewedit.com/unSaaZAt6fkYVA7u9YLZsz

**Comment by Ferdi** [comment]
that was in micromasters-ci

**Comment by noisecapella** [comment]
I noticed it too, I filed an issue a few days ago: https://github.com/mitodl/micromasters/issues/2140

**Comment by Ferdi** [comment]
great thx

**Comment by pdpinch** [comment]
@noisecapella what's the status of this? I think the specific issue of the enroll now & pay later button has been addressed.

**Comment by noisecapella** [comment]
This is not yet done. The enroll button shows a spinner during API activity but afterwards the entire dashboard is still updated at once. The fix should be simple but the work just hasn't been done yet

**Comment by rhysyngsun** [comment]
Putting this back into Ready until #2519 is merged since that's touching code this will need to change too.
