### ISSUE TITLE
Detect missing migrations during build

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1448]
We can see this when we run `./manage.py migrate` and see

```
Your models have changes that are not yet reflected in a migration, and so won't be applied.
Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

We should detect this string, or find some other means of detecting this, then fail the build if we forget to update migrations for a PR

**Comment by pdpinch** [comment]
@noisecapella didn't you address this?

**Comment by noisecapella** [comment]
Yes, I'll close this
