### ISSUE TITLE
Refactor all modal windows front-end code

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#1452]
We should refactor the front-end code for all the modals in the app so that:

- All modals have a consistent header/title element and class. This could be an H3 tag with a class "modal_title" for example.
- All modals have consistent buttons.
- All modals have classes added to the modal. There should be one shared class like "mm-modal", and then a class that is specific to the modal (ex. Sign-up-modal"). In part this is so that we can style the modals... for example, we cannot currently style the width of modals for mobile layouts.

**Comment by pdpinch** [comment]
@roberthouse54 how many modals are we talking about?

**Comment by roberthouse54** [comment]
I don't know exactly. There are: 
- the modals in the sign up process
- the upload photo modal
- the edit profile modal on the user page
- the add employment/ education on the user page
- the calculator
- the skip and pay full price modal
- the New Email modal on the learner search
- the sign up for mailing list modal

There are probably some I am forgetting

**Comment by singingwolfboy** [comment]
Looks like we mostly use the Material UI [Dialog](http://www.material-ui.com/#/components/dialog) component for these modals. I could go through the codebase and update the `className`, `title`, and `titleClassName` of every place we use that component, but it might be a better idea to define a subclass that sets defaults for those values and use that subclass everywhere. Thoughts?
