### ISSUE TITLE
Clicking on Profile on the Dashboard Page leads to confusing Navigation

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1479]
Steps to Reproduce:
Log into  MicroMasters.
Sign into edX.
Complete a Profile.
From the Dashboard Page, click on view profile in the dropdown in the header.
This brings the user to this page:  https://micromasters.herokuapp.com/learner/jtausig

However, there is no obvious navigation back to the Dashboard.
(Browser back button works, as does the "MicroMasters" link in the header, but neither
are obvious -- especially as in other pages, the MicroMasters link doesn't always take you back one page.)
![dashboard profile](https://cloud.githubusercontent.com/assets/13886722/19565970/bda2df80-96b6-11e6-948a-ad0c1b91685e.PNG)

**Comment by pdpinch** [comment]
@roberthouse54 would breadcrumbs address this?

**Comment by roberthouse54** [comment]
Yes, that is the proposed solution.

**Comment by pdpinch** [comment]
Are there screen designs for this yet? (I don't think there's an issue)

**Comment by roberthouse54** [comment]
![image](https://cloud.githubusercontent.com/assets/20047260/20062156/9c14bd52-a4d0-11e6-8831-563527e76497.png)

**Comment by pdpinch** [comment]
This was addressed by the sidebar navigation
