### ISSUE TITLE
MIT Logo in Header on Dashboard does not link to www.mit.edu

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1481]
Steps to Recreate:
Log onto MicroMasters
Complete the Profile Flow.
Navigate to the Dashboard page.
Click on the MIT Logo in header.

Expected Behavior
Logo should link to www.mit.edu
Actual Behavior:
Logo links to the dashboard page.

**Comment by pdpinch** [comment]
@roberthouse54 was this by design?

**Comment by roberthouse54** [comment]
Yeah, this was by design. We are only linking to mit.edu on the marketing pages.
