### ISSUE TITLE
Info popup on Financial Aid Card is missing text.

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1485]
Steps to recreate:
Log into MicroMasters
Create profile in edX.
Fill out Profile.
On Dashboard page, select the Data, Economics  & Development program.
(The Financial Aid Card should display).
Click on the "Question Mark Button"
"filler-text" is displayed in the balloon window.

ALSO:  the copy under "How Much Does It Cost" needs editing:
Courses cost varies between $100 and $1000 (full price), depending on your income and ability to pay.

![pricing card](https://cloud.githubusercontent.com/assets/13886722/19571159/0afaaa2e-96cb-11e6-8cb4-c2b3ee6aa754.PNG)

**Comment by pdpinch** [comment]
closed via  05388ea
