### ISSUE TITLE
User enrollment: personal info card (part of profile creation)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#149]
When I first enroll, I need to view and update my personal profile information, as it was imported from edX. 

Fields are described in https://docs.google.com/spreadsheets/d/1ehN3FNymCOhpJT7h9XZDOITP_lOFDnEcStRa0le4MX8/edit?pref=2&pli=1#gid=0

This will be the first tab of three, presented the first time the user visits the site. The user will not be able to proceed without completing the required fields. 

edX will provide a full name which we should attempt to split into `family_name` and `given_name.` `preferred_name` is optional.  

Countries should be normalized, ideally using the same list as edX. (It's possible that we may need to restrict users from some countries)

![enroll_personal](https://cloud.githubusercontent.com/assets/430126/14503033/399853c0-017c-11e6-8707-a9abc381b998.png)

**Comment by pdpinch** [comment]
"To enroll in MIT Micromasters you must fill in the information below"

**Comment by pdpinch** [comment]
We will POST/PATCH when the user closes the modal -- to avoid losing data in progress

**Comment by pdpinch** [comment]
@noisecapella I updated the fields in the spreadsheet

**Comment by pdpinch** [comment]
I added a wireframe.

**Comment by noisecapella** [comment]
Is preferred language a dropdown? Should we have state in addition to city and country?

**Comment by noisecapella** [comment]
It looks like edX uses ISO 639-1 language codes but they only support English in the devstack by default. edx.org has four languages to choose from

**Comment by noisecapella** [comment]
We should have a message that says that the user will opt in to receive email by submitting their profile

**Comment by pdpinch** [comment]
Actually, I was referring to `language_proficiencies` in the edX profile, not `language`

I believe the user can choose from any of the ISO 639-1 languages for their proficiencies, but language is limited to the 4 supported languages. 

Our micromasters site is only going to support English (as far as I know) but I think MIT is interested in the range of it's users' proficiencies. 
> It looks like edX uses ISO 639-1 language codes but they only support English in the devstack by default. edx.org has four languages to choose from
>

**Comment by pdpinch** [comment]
> We should have a message that says that the user will opt in to receive email by submitting their profile

Thanks for the reminder! I updated the wireframe. 

I assume we still have a field in the database for tracking opt-in status, even though we're not letting people opt-out here.

**Comment by noisecapella** [comment]
Can you upload the wireframe again?

**Comment by noisecapella** [comment]
When we say 'Preferred name' is optional, does that mean we use first + last otherwise? Should we set preferred_name to this internally?

**Comment by pdpinch** [comment]
I'm trying to anticipate stuff like the social network, where it may not be appropriate to default to the user's given name.

I don't think I know now what we will use in those cases, so I'd rather not populate preferred. 



----------------
I am mobile.

**Comment by Ferdi** [comment]
1. It looks like "preferred name" is required on edx, so we must have that for each learner
2. We might want to allow user to use a name other than real name (in discussions / forums etc.)

Given 1 and 2 above what dont we make "preferred name" required ?

**Comment by noisecapella** [comment]
So we should populate "preferred name" with edX's "name" field?
