### ISSUE TITLE
Remove email & icon from the "view profile" page in Dashboard

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1494]
When a user views their own profile (i.e. goes to the "view profile" page in Dashboard), we are displaying an envelope icon & email address in the top card.  Per discussion w/ @pdpinch, please remove both.

Steps to Reproduce:
Log onto MicroMasters
Complete a profile.
On Dashboard page, select "view profile" from the dropdown in the  header.
![profile email](https://cloud.githubusercontent.com/assets/13886722/19602231/78bcbbc4-977a-11e6-9a43-ead8385091e6.PNG)

**Comment by pdpinch** [comment]
@roberthouse54 does this make sense? You can't e-mail yourself...

**Comment by roberthouse54** [comment]
I think it makes sense to disable the link, but we should probably still display it, since it is part of the data in the user profile.

**Comment by pdpinch** [comment]
FYI, the user can't change their e-mail. That comes from upstream at edX. 

I'm not sure if edX allows changing e-mail.

**Comment by j2tausig** [comment]
Since there is no way for a user to change their email, I wonder if it will lead to confusion/frustration to show the email and then suggest they can edit it via the pencil, when in actuality they cannot.

**Comment by roberthouse54** [comment]
OK, makes sense.
