### ISSUE TITLE
Add Degree Modal on Profile has incorrect Title

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1498]
Steps to Reproduce:
Log into MicroMasters.
Complete a Profile.
Navigate to Dashboard.
Select "View Profile" in Header.
Click on "Add degree" link in Education section.
Note: the title of the Add Degree Modal changes to reflect whichever degree type you select

Please change the title of the Modal to "Add Degree"
![add degree modal](https://cloud.githubusercontent.com/assets/13886722/19606966/862e32aa-9794-11e6-94e6-d10ca04afdce.PNG)

**Comment by pdpinch** [comment]
If the user is editing a degree, the title should be "Edit Degree"
