### ISSUE TITLE
User enrollment: employment card (part of profile creation)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#150]
As a user, I need to enter information about my professional experience. This will help me network with others from my company and industry, and it will help me apply for a masters degree. 

Users can enter as many positions as they choose, but they cannot close the modal with zero positions unless they have also answered "No" to the question "Are you currently employed?"

For each employer, the user must enter:

- Position
- Industry
- Company Name (someday we will normalize these, but not for MVP)
- Company City 
- Company Country (normalized)
- Start Date
- End Date (optional)

Positions without an end date are considered "current"

Self-employed users are encouraged to enter 'self-employed' for position. 

![enroll_ professional](https://cloud.githubusercontent.com/assets/430126/14620475/dc84ae14-058a-11e6-8ea8-2db24e18c8e7.png)

**Comment by pdpinch** [comment]
There should be just enough definition here to get started, but I need to take another pass on the fields. I'm also going to update the title.

**Comment by aliceriot** [comment]
cool, I've got stuff to do in the meantime! no rush.

**Comment by pdpinch** [comment]
@aliceriot I update the description and added a wireframe.

**Comment by aliceriot** [comment]
great! going to probably get started on this today.

**Comment by aliceriot** [comment]
today I merged #190, which sets up react-router to navigate between the profile tabs and adds a skeleton employment page.

currently working on fleshing out the employment page more.

**Comment by aliceriot** [comment]
pr open for the expanded form, not quite done: #191
