### ISSUE TITLE
combine javascript files that contain duplicate libraries

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1500]
These are the current sizes of the JS files being served:

```
-rw------- 1 u46725 dyno  255221 Oct 21 15:43 course_list.js
-rw------- 1 u46725 dyno 2370309 Oct 21 15:43 dashboard.js
-rw------- 1 u46725 dyno  174782 Oct 21 15:43 faculty_carousel.js
-rw------- 1 u46725 dyno  431217 Oct 21 15:43 financial_aid.js
-rw------- 1 u46725 dyno   67623 Oct 21 15:43 public.js
-rw------- 1 u46725 dyno   24321 Oct 21 15:43 sentry_client.js
-rw------- 1 u46725 dyno  785638 Oct 21 15:43 signup_dialog.js
-rw------- 1 u46725 dyno  674183 Oct 21 15:43 style.js
-rw------- 1 u46725 dyno  229752 Oct 21 15:43 style_public.js
-rw------- 1 u46725 dyno    1197 Oct 21 15:43 zendesk_widget.js
```

**Comment by pdpinch** [comment]
find out what is contributing to the size of dashboard.js

**Comment by noisecapella** [comment]
I don't think we do have gzip turned on. It looks like this will do it: https://docs.djangoproject.com/en/1.10/ref/middleware/#module-django.middleware.gzip

**Comment by noisecapella** [comment]
I ran [webpack-bundle-size-analyzer](https://github.com/robertknight/webpack-bundle-size-analyzer) on our project and got this output:

    lodash: 709.6 KB (9.42%)
    react: 629.07 KB (8.35%)
    bootstrap: 464.12 KB (6.16%)
    react-mdl: 446.13 KB (5.92%)
    moment: 444.16 KB (5.90%)
    material-ui: 388.06 KB (5.15%)
    sanctuary: 384.36 KB (5.10%)
      ramda: 286.81 KB (74.6%)
      <self>: 97.55 KB (25.4%)
    ramda: 289.32 KB (3.84%)
    searchkit: 272.8 KB (3.62%)
      qs: 13.48 KB (4.94%)
      react-addons-update: 45 B (0.0161%)
      <self>: 259.27 KB (95.0%)
    jquery: 252.33 KB (3.35%)
    iso-3166-2: 236.13 KB (3.13%)
    react-virtualized: 212.39 KB (2.82%)
    core-js: 198.71 KB (2.64%)
    redux-actions: 108.87 KB (1.45%)
      lodash: 98.9 KB (90.8%)
      <self>: 9.97 KB (9.16%)
    cropperjs: 103.62 KB (1.38%)
    react-router: 100.38 KB (1.33%)
    raven-js: 78.21 KB (1.04%)
    react-select: 77.89 KB (1.03%)
    react-datepicker: 55.99 KB (0.743%)
    history: 55.37 KB (0.735%)
      query-string: 1.45 KB (2.61%)
      <self>: 53.92 KB (97.4%)
    react-slick: 50.41 KB (0.669%)
    lodash._baseclone: 44.96 KB (0.597%)
    sanctuary-def: 44.91 KB (0.596%)
    react-tooltip: 43.3 KB (0.575%)
    inline-style-prefixer: 37.73 KB (0.501%)
    rc-slider: 36.81 KB (0.489%)
      warning: 1.76 KB (4.79%)
      <self>: 35.04 KB (95.2%)
    fbjs: 33.59 KB (0.446%)
    lodash.merge: 31.88 KB (0.423%)
    es6-promise: 31.77 KB (0.422%)
    dom-align: 28.73 KB (0.381%)
    axios: 26.04 KB (0.346%)
    rc-trigger: 25.74 KB (0.342%)
    redux: 22.02 KB (0.292%)
    regenerator-runtime: 21.34 KB (0.283%)
    slick-carousel: 20.94 KB (0.278%)
    currency-codes: 20.58 KB (0.273%)
    rrssb: 20.28 KB (0.269%)
    react-redux: 19.37 KB (0.257%)
    react-dropzone: 19.01 KB (0.252%)
    inline-style-prefix-all: 17.99 KB (0.239%)
    rc-animate: 17.37 KB (0.231%)
    bowser: 15.88 KB (0.211%)
    react-bootstrap: 14.93 KB (0.198%)
      core-js: 5.91 KB (39.6%)
      babel-runtime: 856 B (5.60%)
      <self>: 8.18 KB (54.8%)
    react-sticky: 14.9 KB (0.198%)
    react-ga: 13.97 KB (0.186%)
    lodash.keysin: 12.8 KB (0.170%)
    react-cropper: 12.46 KB (0.165%)
    spin.js: 11.33 KB (0.150%)
    whatwg-fetch: 11.28 KB (0.150%)
    es-abstract: 11.03 KB (0.146%)
    lodash.debounce: 10.85 KB (0.144%)
    react-tap-event-plugin: 9.95 KB (0.132%)
      fbjs: 2.56 KB (25.7%)
      <self>: 7.4 KB (74.3%)
    redux-localstorage: 9.79 KB (0.130%)
    add-dom-event-listener: 9.63 KB (0.128%)
    recompose: 9.26 KB (0.123%)
    enquire.js: 9.24 KB (0.123%)
    lodash.rest: 8.59 KB (0.114%)
    redux-logger: 8.29 KB (0.110%)
    redux-asserts: 7.74 KB (0.103%)
    striptags: 7.56 KB (0.100%)
    css-animation: 7.18 KB (0.0953%)
    style-loader: 6.99 KB (0.0927%)
    rc-tooltip: 6.52 KB (0.0865%)
    ajaxchimp: 5.46 KB (0.0725%)
    react-swipeable: 5.26 KB (0.0699%)
    bem-cn: 5.01 KB (0.0666%)
    react-page-click: 4.82 KB (0.0640%)
    react-onclickoutside: 4.77 KB (0.0633%)
    rc-align: 4.64 KB (0.0616%)
    react-input-autosize: 4.54 KB (0.0602%)
    deep-equal: 3.8 KB (0.0505%)
    rc-util: 3.79 KB (0.0504%)
    react-loader: 3.75 KB (0.0498%)
    react-event-listener: 3.66 KB (0.0486%)
    object-keys: 3.58 KB (0.0475%)
    lodash.throttle: 3.5 KB (0.0464%)
    lodash.isplainobject: 3.49 KB (0.0464%)
    component-classes: 3.29 KB (0.0437%)
    es-to-primitive: 3.2 KB (0.0425%)
    process: 2.76 KB (0.0366%)
    keycode: 2.67 KB (0.0355%)
    redux-localstorage-filter: 1.99 KB (0.0264%)
    object-assign: 1.95 KB (0.0259%)
    lodash._root: 1.9 KB (0.0252%)
    raf: 1.84 KB (0.0244%)
    warning: 1.76 KB (0.0234%)
    define-properties: 1.52 KB (0.0202%)
    function-bind: 1.49 KB (0.0198%)
    invariant: 1.48 KB (0.0197%)
    css-loader: 1.47 KB (0.0195%)
    hoist-non-react-statics: 1.35 KB (0.0180%)
    nub: 1.32 KB (0.0176%)
    is-callable: 1.22 KB (0.0162%)
    object.entries: 1.21 KB (0.0160%)
    json2mq: 1.13 KB (0.0151%)
    classnames: 1.08 KB (0.0143%)
    url-join: 1 KB (0.0133%)
    babel-polyfill: 907 B (0.0118%)
    json-stringify-safe: 907 B (0.0118%)
    performance-now: 886 B (0.0115%)
    react-responsive-mixin: 853 B (0.0111%)
    react-prop-types: 840 B (0.0109%)
    is-symbol: 773 B (0.0100%)
    dom-helpers: 698 B (0.00905%)
    foreach: 555 B (0.00720%)
    is-date-object: 551 B (0.00714%)
    is-regex: 534 B (0.00692%)
    symbol-observable: 451 B (0.00585%)
    reduce-reducers: 419 B (0.00543%)
    webpack: 379 B (0.00491%)
    redux-thunk: 370 B (0.00480%)
    first-match: 313 B (0.00406%)
    simple-assign: 281 B (0.00364%)
    isomorphic-fetch: 233 B (0.00302%)
    string-convert: 216 B (0.00280%)
    clamp: 187 B (0.00242%)
    strict-uri-encode: 182 B (0.00236%)
    component-indexof: 175 B (0.00227%)
    can-use-dom: 139 B (0.00180%)
    react-dom: 132 B (0.00171%)
    has: 114 B (0.00148%)
    react-addons-create-fragment: 59 B (0.000765%)
    react-addons-transition-group: 59 B (0.000765%)
    react-addons-shallow-compare: 53 B (0.000687%)
    react-addons-update: 45 B (0.000583%)
    <self>: 1.05 MB (14.2%)

**Comment by rhysyngsun** [comment]
Might be worth splitting vendor libraries into their own file since their unit of change is probably less than our own code: https://webpack.github.io/docs/code-splitting.html#split-app-and-vendor-code

That would mean that if we make a small bugfix you don't have to pull down all the vendor code again.
