### ISSUE TITLE
User Enrollment: education card (profile creation)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#151]
As a user, I need to enter information about my educational history. This will help me network with others, and it will help me apply for a masters degree.

~~The first field, "Education Completed" is populated from edX, but the user can change it.~~

We will present the user with a series of switches, one for each type of degree. If switch is set to "on" the user must add a degree and complete the form before continuing. However, the user can set any and all degrees to "off" if they in fact don't have the degree (none are required). High school and Bachelors will default to being turned on, since these are the degrees that we expect micromasters applicants to have. 

The user can enter as many degrees/certifications as she chooses.

For each degree/certification, the user must enter:

Degree/Certification
School Name or Granting Authority
School City
School State/Territory (if Country == US)
School Country 
Subject
Online (switch component)
Graduation Month and Year (or expected graduation)

For now, we won't worry about normalizing the data. Later, when we have more users we will clean up the data. 

Screen designs:

https://projects.invisionapp.com/share/KR6FYCZTX#/screens/153562861
https://projects.invisionapp.com/share/KR6FYCZTX#/screens/155766490

Wireframes: 

![education_default](https://cloud.githubusercontent.com/assets/430126/14988189/d66d0412-1120-11e6-8033-cc7037a4c250.png)
![education_modal](https://cloud.githubusercontent.com/assets/430126/14988190/d66e7d6a-1120-11e6-9873-cdef077f176e.png)
![education_list](https://cloud.githubusercontent.com/assets/430126/14988191/d66e6956-1120-11e6-91a9-7d8dd1a53604.png)

stretch goal: When we get a value from edX, we can use the "Education Completed" Field to make some assumptions about which switches to display. 

Doctorate => Ph.D, Bachelor's Degree, High School
Master's or Professional => Master's Degree, Bachelor's Degree, High School
Associate Degree => Associate Degree, High School
High School => High School

**Comment by pdpinch** [comment]
@noisecapella @annagav @Ferdi I added a wireframe for the education tab. I'll update the description shortly.

**Comment by Ferdi** [comment]
Some UX work is needed For example:  
What is required ? 
What if I dont have a doctorate degree?

**Comment by pdpinch** [comment]
I added this to the description:

> We'll use the "Education Completed" Field to make some assumptions about which forms to display. When we display a form, all fields are required. We won't ask for about anything below High School, or for users who have set "education completed" to "Other Education" or "No Formal Education"

> Doctorate => Bachelor's Degree, High School
Master's or Professional => Master's Degree, Bachelor's Degree, High School
Associate Degree => Associate Degree, High School
High School => High School

**Comment by pdpinch** [comment]
@annagav I updated the description, added the wireframes from last week and links to the new screen designs. Let us know if you have any questions.

**Comment by annagav** [comment]
![screen shot 2016-05-03 at 3 47 01 pm](https://cloud.githubusercontent.com/assets/7574259/15020794/a43c2f6e-11f1-11e6-944b-aa771c8943fd.png)

**Comment by annagav** [comment]
![screen shot 2016-05-03 at 3 44 52 pm 1](https://cloud.githubusercontent.com/assets/7574259/15020815/bb331430-11f1-11e6-983c-f00a115a97e2.png)

**Comment by Ferdi** [comment]
Feel free to open new issues for any of these.  The dont have to be part of the current open PR

- Match the style of the form input labels to the mockup (light gray instead of purple)
- The month-year doesn't look very material design.  Here is one suggestion
![month-year](https://cloud.githubusercontent.com/assets/125561/15022029/b69ace6c-11f7-11e6-8c90-b331ee26de89.png)
- The select element (e.g. country) doesnt look material design. Can you look around for a select MD select component ?
- Just a comment: What our error messages looks like? I like how it's done in the image above.

@annagav @noisecapella @pdpinch

**Comment by pdpinch** [comment]
I think the error messages look the way you want them to:

<img width="321" alt="screen shot 2016-05-04 at 4 48 17 pm" src="https://cloud.githubusercontent.com/assets/430126/15028687/0e066fd8-1218-11e6-91d0-c05b3b56a410.png">

**Comment by pdpinch** [comment]
I opened 3 new issues, #275, #276 and #277

**Comment by Ferdi** [comment]
@pdpinch that looks pretty good. The form lables should not be red though.
