### ISSUE TITLE
Sign Up: Add "no results" message in select lists when the string doesn't match 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1513]
This is Related to #1518. Be sure to read that as well before starting work on this.

**Comment by roberthouse54** [comment]
Let's use the text "No results".

![image](https://cloud.githubusercontent.com/assets/20047260/19653466/ac1e595e-99e2-11e6-9e92-9dfaa111d195.png)

**Comment by gsidebo** [comment]
correction/addendum: the 'Enter another' functionality is covered in #1519
