### ISSUE TITLE
Add progress indicators at various places to aid users with slow connections

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1515]
I noticed these when I was testing #1460:
- profile next button should have a spinner and be disabled while the next part is loading
- image upload needs a progress indicator

**Comment by pdpinch** [comment]
Is this exclusively a mobile issue?

**Comment by noisecapella** [comment]
No, it's just much more noticeable over a mobile connection. I'll rename this

**Comment by Ferdi** [comment]
@noisecapella is this fixed ?

**Comment by noisecapella** [comment]
Yes I think so
