### ISSUE TITLE
Sign up profile form doesn't load existing program enrollments

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1517]
This is an edge case, because it requires an enrolled user returning to the initial sign up profile forms. 
## Steps to Reproduce:
1. Sign up. Fill in the profile. View the dashboard
2. Return to /profile/ 
## Expected behavior

The program I enrolled in at first is displayed in the first 
## Actual behavior

No  program is set and I have to select one for the form to validate.

**Comment by pdpinch** [comment]
@amir-qayyum-khan I'm wondering if @noisecapella's work on #1586 affects this?

**Comment by amir-qayyum-khan** [comment]
@pdpinch no, i dont think so.
