### ISSUE TITLE
Sign up: add support for "other" in industry and field of study select fields

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1519]
This will need some UX design first. 
- [ ] Add "other" to the list of values. 
- [ ] When user has chosen "other," display an additional field below the select field where the user can add a free text value
- [ ] In search, these users will appear with a facet value of "other"
- [ ] later, we can analyze the values that are entered and determine if we need to add a new value to our list
- [ ] If the user types something that matches nothing in the list, then, instead of displaying "Other", display "No results. Enter another Industry/Field of Study[link]" Clicking the link is the same as clicking "Other" from the list of options.

See also #1513

**Comment by roberthouse54** [comment]
![other1](https://cloud.githubusercontent.com/assets/20047260/19658957/0444d10c-99f8-11e6-9bf3-f0943f54cdf4.jpg)

![other2](https://cloud.githubusercontent.com/assets/20047260/19658963/07541eac-99f8-11e6-9fca-41bb455fc20a.jpg)

![other3](https://cloud.githubusercontent.com/assets/20047260/19658967/0ac35076-99f8-11e6-8153-450e9fa4e621.jpg)

**Comment by pdpinch** [comment]
Let's start with looking at the default behavior of react select. Hopefully that will be sufficient. 

@aliceriot @roberthouse54

**Comment by aliceriot** [comment]
@pdpinch what do you think we need to do for this now?

**Comment by pdpinch** [comment]
For these two fields we need a way to allow users to enter their own values. 

My suggestion would be to have the form behave the same way as the "Custom Tag creation" example at http://jedwatson.github.io/react-select/ <http://jedwatson.github.io/react-select/> but replace the text "Create Option" with "Other:"

When the API receives an "other" value it should just store it in the db. We won't try to add things back into the controlled vocabulary for now. 

Make sense?

**Comment by aliceriot** [comment]
sure!
