### ISSUE TITLE
release v.0.3.0

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#152]
We can do a release immediately.

@pwilkins will bring @annagav up to speed on how to do the release.

**Comment by pdpinch** [comment]
@annagav @pwilkins is this done?

**Comment by annagav** [comment]
Yes, It's done

**Comment by pwilkins** [comment]
There are two steps left to do.
1. merge ``release`` with ``master``, and push ``master``  (no PR)
2. tag the version with ``v0.3.0``

**Comment by pdpinch** [comment]
Ok. When those two things are done, we can close this issue.

**Comment by pdpinch** [comment]
Looks done to me!
