### ISSUE TITLE
Mailgun monitoring

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1523]
We need to be alerted if Mailgun gets too many failed messages.

**Comment by pdpinch** [comment]
@blarghmatey this is done, right? Can you capture the details here?

**Comment by blarghmatey** [comment]
Yes this is complete. The sequence of events that lead to us being alerted are as follows:
- Message delivery fails
- Mailgun sends webhook to our log aggregators
- Message is logged into our Elasticsearch cluster
- Elastalert queries every minute for a message from Mailgun
- Elastalert sends message to Hipchat if there was a delivery failure
