### ISSUE TITLE
Allow PR creators to populate PR apps with a superuser

### ISSUE THREAD

**Issue by bdero** [mitodl/micromasters#153]
There are a few options here:

- Automatically create one with a stock username/password in a heroku hook (bin directory script). This approach is risky, because if the check doesn't work correctly, a superuser could be created on any environment (such as production).
- Add a chatops command (with permissions) to allow certain chat to add superusers to PR apps. For this, we need to reconsider doof as a serious - tested for security - chat bot, since he'd need to have permission to do some nasty things.

Other options include automatically inviting the PR creator's email as an owner of the review app on Heroku, so that they may manage it through the dashboard and use the heroku CLI.

**Comment by blarghmatey** [comment]
I believe this would be solved by adding developers as collaborators on pre-production applications from which the PR apps are forked.

@pdpinch @bdero comments welcome.

**Comment by bdero** [comment]
@blarghmatey That would allow developers to create new superusers for each app individually by using the Heroku CLI to run the createsuperuser management command, and I think this is something we should do to make testing things more convenient anyways. So yes, given the title I chose, that would solve this issue. :)

**Comment by pdpinch** [comment]
AFAIK, this is working now.
