### ISSUE TITLE
Abbreviated title is confusing

### ISSUE THREAD

**Issue by singingwolfboy** [mitodl/micromasters#1537]
In the file `static/js/components/LearnerSearch.js`, there is a `<RangeFilter>` component on the field `program.grade_average`. The `title` attribute of this component is set to "Program Avg. Grade", which is a bit confusing -- the user may not know what "Avg." stands for. It's also a bit tricky to parse the sentence: is this the grade of the program average, or the average grade of the program?

For clarity, this title should be reworded -- I suggest "Average Grade in Program".

**Comment by roberthouse54** [comment]
Sounds good

**Comment by pdpinch** [comment]
"Fix for #1537" is not magic enough to trigger GitHub's auto closing.
