### ISSUE TITLE
Allow PR creators to reset the database of PR apps

### ISSUE THREAD

**Issue by bdero** [mitodl/micromasters#154]
This comes up sometimes, and currently must be done manually by someone with permission to use the heroku dashboard.

**Comment by blarghmatey** [comment]
I think the answer to this is that the dev team should have Heroku access to any non-production apps.

@pdpinch @bdero differing opinions are welcome.

**Comment by pdpinch** [comment]
That works for me, as long as there's a way to manage it effectively, i.e. adding devs when onboarding, removing offboarding devs, and adding the team to new apps.

**Comment by pdpinch** [comment]
We took care of this some time ago.
