### ISSUE TITLE
Only one Course run without course key is currently allowed

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#1541]
If you try to add multiple course run without a course key you get:

![screen shot 2016-10-25 at 11 44 40 am](https://cloud.githubusercontent.com/assets/1005204/19693125/6fd5c2fe-9aa8-11e6-9ca3-eeff00e409c5.png)

**Comment by pdpinch** [comment]
@gsidebo ?

**Comment by gsidebo** [comment]
*facepalm* 

i wonder if django admin is trying to insert the course run with an edx_course_key of "" instead of null. i'll take a look
