### ISSUE TITLE
Make matching in field of study select behave more like country and industry

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1551]
For both the Country & Industry drop downs, if a user types a letter, all the results are displayed with a match on the entire string, starting with the first character.

This is correct.

However, for the Field of Study drop down, we are constraining the display of the result set to the first 10 only, (and they do not appear to be the correct first 10:  NOTE:  "Farm/Farm and Ranch Management" as the 5th result is you type in "A").

Would it be possible to display all the results with a match on the whole string?
Peter did ask as a "nice to have" if it would be possible to use a search on any word boundary in the phrase.

**Comment by aliceriot** [comment]
@pdpinch can we close this? not sure if it's still an issue.

**Comment by pdpinch** [comment]
Thanks @aliceriot. I'll close this.

**Comment by pdpinch** [comment]
closed via #1645
