### ISSUE TITLE
URL for "View on edx" is malformed

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#1555]
note that in the screenshot it is "http://192.168.33.10:8000//courses/course-v1:odl+MX+2015"

![screen shot 2016-10-25 at 4 23 55 pm](https://cloud.githubusercontent.com/assets/1005204/19702883/905078f4-9acf-11e6-9ab5-aed2a9429392.png)

**Comment by amir-qayyum-khan** [comment]
@giocalitri what base url you have in .env file

http://172.xx.xx.xx:8000
OR
http://172.xx.xx.xx:8000/

**Comment by giocalitri** [comment]
It does not matter: the URL concatenation should take care of this anyway.

On Oct 28, 2016, at 9:00 AM, Amir Qayyum Khan <notifications@github.com<mailto:notifications@github.com>> wrote:


@giocalitri<https://github.com/giocalitri> what base url you have in .env file

http://172.xx.xx.xx:8000
OR
http://172.xx.xx.xx:8000/

**Comment by noisecapella** [comment]
The `url-join` library will be useful for this. We already have it in `package.json`
