### ISSUE TITLE
Cannot input income into cost calculator

### ISSUE THREAD

**Issue by singingwolfboy** [mitodl/micromasters#1558]
When I type an number into the "Income (yearly)" field on the cost calculator, the Javascript console pops up an error:
```
FinancialAidCalculator.js:49 Uncaught TypeError: (0 , _profile.sanitizeNumberString) is not a function
```

When the field loses focus, the number I've typed in disappears. This makes the cost calculator unusable.

**Comment by aliceriot** [comment]
good catch! I think this is just an import statement change.

**Comment by pdpinch** [comment]
Is this a regression?

**Comment by aliceriot** [comment]
yea, small one. already fixed
