### ISSUE TITLE
Programs are laid out oddly on the homepage

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1559]
On micromasters-rc
![screenshot from 2016-10-25 16-51-15](https://cloud.githubusercontent.com/assets/863262/19703831/4eac6684-9ad3-11e6-8b15-b24a798a46e2.png)

**Comment by pdpinch** [comment]
We won't be encountering 3 programs anytime soon, but we might as well prepare. 

@roberthouse54 where does the 3rd program go?

**Comment by roberthouse54** [comment]
![image](https://cloud.githubusercontent.com/assets/20047260/19861203/12735df6-9f62-11e6-988e-fcd83eb563d4.png)

**Comment by noisecapella** [comment]
Sorry if it wasn't clear, I'm referring to the gap in the second row in my screenshot

**Comment by roberthouse54** [comment]
I understood. The programs should be laid out in a 3x grid, left-aligned. So if there are only 4 programs, it would look like this:

![image](https://cloud.githubusercontent.com/assets/20047260/19897923/66ae314c-a030-11e6-9201-d5f0bf54cc71.png)

**Comment by Ferdi** [comment]
Is this still an issue ?

**Comment by roberthouse54** [comment]
DB basically fixed this (mostly) with a recent PR, but once we get more programs, I'd like to move the "Sign Up for Mailing List" stuff below the grid of programs, as shown in the mock above.

**Comment by noisecapella** [comment]
The issue is still present on micromasters-rc, not sure if DB's PR is included there

![screenshot from 2016-11-18 12-14-48](https://cloud.githubusercontent.com/assets/863262/20439237/abcd64ae-ad88-11e6-8424-f48b349aeca2.png)
