### ISSUE TITLE
Faculty tiles fail to render due to console error

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1560]
![screenshot from 2016-10-25 16-53-56](https://cloud.githubusercontent.com/assets/863262/19703911/a92c197e-9ad3-11e6-8f1d-e86a81ed8979.png)

**Comment by pdpinch** [comment]
A contributing issue may be that there are no images for these faculty in the CMS on micromasters-rc. I'm still populating that data.

**Comment by pdpinch** [comment]
Is this related? https://sentry.io/mit-office-of-digital-learning/micromasters/issues/174976921/

**Comment by pdpinch** [comment]
Another possibly related error: https://sentry.io/mit-office-of-digital-learning/micromasters/issues/174605345/
