### ISSUE TITLE
Odd scrollbar on program page

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1561]
From micromasters-rc, it's a horizontal scrollbar right below the hero image

![screenshot from 2016-10-25 16-55-24](https://cloud.githubusercontent.com/assets/863262/19703961/ddf2e9e4-9ad3-11e6-9dfc-8b0a10597813.png)

**Comment by pdpinch** [comment]
@annagav we saw this before. Do you remember what the fix was?

**Comment by pdpinch** [comment]
https://micromasters-rc.herokuapp.com/scm/

**Comment by pdpinch** [comment]
@annagav when you take an issue, please assign it to yourself and change the pipeline to "in progress"
