### ISSUE TITLE
When dashboard refreshes only the footer is visible for a period of time

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1563]
![screenshot from 2016-10-25 17-37-01](https://cloud.githubusercontent.com/assets/863262/19705290/aeb3c21a-9ad9-11e6-8d02-c0681cbce38b.png)

**Comment by gsidebo** [comment]
1 vote to make this a release blocker

**Comment by noisecapella** [comment]
It seems like the large size of the javascript bundle is a partial cause here. The footer is the only thing showing up for a period of time because the code to start the React components hasn't gotten a chance to execute yet.

**Comment by pdpinch** [comment]
Was there a CSS change that's causing the body of the dashboard to collapse?

**Comment by noisecapella** [comment]
@pdpinch Probably. If we just set `min-height: 300px` or something like that on `#dashboard` then we will something that looks better. Not sure how that intersects with responsiveness

**Comment by noisecapella** [comment]
Actually I think if we move the JS before the body, we may delay the whole page such that we don't see this anymore. Still more investigation to do

**Comment by noisecapella** [comment]
I think this is actually caused by the footer code being moved into the Django template from the React app. Since the entire site was being rendered in React, it wasn't noticable that it was taking a while to start running the JS

**Comment by pdpinch** [comment]
I'm a little late to this conversation, but I liked the spinner while I'm waiting for the dashboard (and having min height for the dashboard). Is there a way to have that back?
