### ISSUE TITLE
Notify user when enrollment status doesn't match paid status

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1568]
I think a simple solution here is as follows:
1. For any situation where a user is paid, but not enrolled, we show a status that  says "Something went wrong. You paid for this course but are not enrolled. Contact us for help."
2. In the case where the user pays, and there is an error and they are not enrolled, we show a failure toast message at the top of the page, in addition to the status message next to the button. 

See the proposed design below:
![image](https://cloud.githubusercontent.com/assets/20047260/20841498/06eef20e-b882-11e6-8974-d0435e3f3984.png)

**Comment by roberthouse54** [comment]
I need to learn more about this situation.

**Comment by pdpinch** [comment]
There are two conditions (George, correct me if I'm wrong):

1. User has paid us for a course, but for some reason, the edX automatic enrollment has failed (this happened once when edX made a breaking change to their enrollment API. That shouldn't happen again, but you don't know). 

2. The user has paid us for a course but then decided to unenroll themselves (There is an interface in edX to do this). 

In both cases, this is a degenerate state and we'd like the user to "try again" or contact us (possibly for a refund of some kind).

**Comment by roberthouse54** [comment]
This raises a few questions. First, in case #2... Are we going to give refunds to users who want to un-enroll from a course? How does that work? Second, in case #1, if a user has paid but is still unenrolled, what should we encourage them to do, if anything? The UI, as it is, allows a user to enroll by paying for the course. If the user has already paid, they should be enrolled. It seems that we should avoid having this happen, and if it does happen, I don't know that the user needs to do anything. Instead, could we do something in the background to fix the problem? For example, just show them a simple error message (eg. "Something went wrong, and you are not enrolled in the course on edX. We are working on fixing it.") We should monitor for when (if) this ever happens, and have some mechanism for fixing it.

**Comment by pdpinch** [comment]
1. I think a "Something went wrong" message is appropriate. Easiest for us is for the user to try again or try enrolling on the edX web site. A more generic solution though would be for them to contact us (help button or e-mail micromasters-support@mit.edu). We could cover other edge cases in that case. 

2. We will offer refunds, at least in some cases. The process I've been modeling is the user contacts micromasters-support@mit.edu and asks for a refund. If the request is accepted, then we have a set of back-office tasks to do which include setting their order in the portal to the "refund" state and unenrolling the user. 

Criteria for accepting a refund request have not been established yet.

**Comment by roberthouse54** [comment]
But how can a user "try again" if they have already paid? We can't have them go through the payment process again. And they cannot enroll on ex without paying. And it seems that if we put some separate link to "Try again" which just attempts to enroll them in the verified track, they will probably fail again(?)

We are dealing with 2 different states here. One is an error. The other is the user intentionally unenrolling. I think these should be handled differently.

**Comment by noisecapella** [comment]
There's a PR to send us an email when an enrollment failure happens, so we could just enroll them manually on their behalf, or we could create a queue and a task of users where the enrollment attempt failed the first time. I think that's all we can do to tell whether we failed to enroll the user or whether they unenrolled themself.

We should also make another dashboard API state where we keep track of paid but not enrolled users, and display some appropriate message. That way the user has some idea that their unenrolling themself is going to cause odd behavior in the app

**Comment by Ferdi** [comment]
I think we need
- A status like "paid by not enrolled"
- Some short explanation and a relevant link to the course on edx where they can (re) enroll themselves.

**Comment by roberthouse54** [comment]
I think a simple solution here is as follows:

1. For any situation where a user is paid, but not enrolled, we show a status that  says "You are not enrolled. Click here to enroll."

2. In the case where the user pays, and there is an error and they are not enrolled, we show a failure toast message at the top of the page, in addition to the status message next to the button. 

See the proposed design below:

![image](https://cloud.githubusercontent.com/assets/20047260/20114717/563cf49a-a5c3-11e6-8a77-d0bbd7004193.png)

**Comment by pdpinch** [comment]
I updated the description to better match [Rob's design solution](https://github.com/mitodl/micromasters/issues/1568#issuecomment-259241651). Here is the original description:

> In order to avoid failing the order if the enrollment attempt fails we will change the behavior to mark the `Order` as fulfilled in that case (#1552). We will still need to enroll users afterwards to have proper behavior in the application. Possible tasks:
- We could have a task which looks for all users that are not already enrolled, then enrolls the users if they have paid.
- We also need to set up an alert to tell us if an enrollment attempt failed

> cc @giocalitri
