### ISSUE TITLE
Add tests to cover cases in financial aid frontend code

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1575]
Specifically:
- skip dialog link when user is auto-approved for a price
- docs visibility link
- cancel button on `FinancialAidCard`

The 'Enroll and pay later' link in the dashboard also should be covered

**Comment by aliceriot** [comment]
- [ ] skip dialog link when user is auto-approved for a price
- [ ] docs visibility link
- [ ] cancel button on FinancialAidCard
- [ ] The 'Enroll and pay later' link in the dashboard also should be covered

**Comment by aliceriot** [comment]
@noisecapella I'm not sure how to go about testing the 'enroll and pay later' link, what do you think about merging what I have and then handing that off to you?

**Comment by noisecapella** [comment]
Fine with me
