### ISSUE TITLE
Info Pop on Dashboard for "How much does it cost" needs copy

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1585]
Currently, the copy for the info pop-up on the Dashboard in the "Pricing Based on Income" Card is "filler-text".  The copy needs to be added.

Steps to Reproduce:
Log into MicroMasters
Create Profile and navigate to Dashboard page
Click on the Question Mark info button in the "Pricing Based on Income" card.
Screenshot below:
![cost info pop](https://cloud.githubusercontent.com/assets/13886722/19780807/93b3a756-9c54-11e6-876f-7369951097b6.PNG)

**Comment by pdpinch** [comment]
There was an issue for this already, #1439. We can close this once the fix gets into production (hopefully later today)
