### ISSUE TITLE
Staff user of program should only see that program's learners in the learners display

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1588]
Currently it looks like they can see learners in other programs too

**Comment by pdpinch** [comment]
I'm pretty sure this was working. Is it a regression? @giocalitri can you take a look?

**Comment by giocalitri** [comment]
sure

**Comment by pdpinch** [comment]
Is this actually the same issue as https://github.com/mitodl/micromasters/issues/1366 ?

**Comment by noisecapella** [comment]
There's probably some overlap, but I'm referring to DEDP staff being able to only see DEDP students and not also SCM students. We need to add an Elasticsearch filter similar to what we did in https://github.com/mitodl/micromasters/pull/1502

**Comment by pdpinch** [comment]
I really thought we had done that already.

**Comment by giocalitri** [comment]
I remember doing this long time ago

**Comment by noisecapella** [comment]
I'm looking at the code and I think this is not a bug, it's due to me being superuser and having all permissions despite having only one role. I'll close this

**Comment by giocalitri** [comment]
@noisecapella before closing the issue, did you test it with an user who is not superuser?

**Comment by noisecapella** [comment]
No, I'll do the test now

**Comment by noisecapella** [comment]
Yes it's still an issue, I shouldn't be so hasty to close these issues. Essentially are using a `should` in the backend but we need to use a `must` instead

**Comment by giocalitri** [comment]
I tested this stuff and it was working in the right way: I wonder if this problem has introduced by the `must` clause in Amir's PR

**Comment by noisecapella** [comment]
On further investigation it looks like when we added the code to filter on `is_learner`

    return Q(
        'bool',
        should=[
            Q('term', **{'program.id': program.id}) for program in users_allowed_programs
        ],
        must=[
            Q('term', **{'program.is_learner': True})
        ]
    )

The `must` overrode the `should.. From [this page](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html):

> If this query is used in a filter context and it has should clauses then at least one should clause is required to match.

**Comment by giocalitri** [comment]
yeah, want I thought

**Comment by giocalitri** [comment]
I can open a PR to move everything under the `must`

**Comment by pdpinch** [comment]
Are we missing a test somewhere?

Or did we change the test when we added the is_learner filter?

**Comment by noisecapella** [comment]
I think our automated test didn't find it because it didn't include any learners, just staff users

**Comment by noisecapella** [comment]
Actually I'm not sure on that... in any case the test needs improvement

**Comment by giocalitri** [comment]
this is a good question actually: I remember writing tests for that

**Comment by noisecapella** [comment]
If I change the number of students to `10` I get an error in the test. I wonder if it's because the search API is paginated and we didn't check beyond the pagination limit

**Comment by giocalitri** [comment]
that is probably it, actually

**Comment by noisecapella** [comment]
I bet the `should` moved the programs we cared about to the front of the list. There are `30` students in that test and we divide them into three programs evenly. Since there are `10` student per program and `10` per page, we didn't see any of the others in the test

**Comment by giocalitri** [comment]
ok, so we should move the number of result to the total number of students in the tests
