### ISSUE TITLE
Fix enrollment exception handling

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1589]
An exception during order fulfillment no longer fails the order, but we still aren't catching and logging it properly. We should widen the scope of exceptions to anything `Exception`

**Comment by pdpinch** [comment]
this should be fixed with a currently open PR

**Comment by pdpinch** [comment]
@noisecapella did this get fixed? I didn't right down the PR number in planning.

**Comment by noisecapella** [comment]
Yes, I fixed it in #1679
