### ISSUE TITLE
script to create fake certificates data

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#159]
in order to demo the learner dashboard, we need to have a demo user who has gotten a certificate in at least one course 

a gist would be sufficient. no need to merge upstream

**Comment by pdpinch** [comment]
Any luck finding the management command for creating certificates?

**Comment by bdero** [comment]
```
[certificates]
    cert_whitelist
    create_fake_cert
    fix_ungraded_certs
    gen_cert_report
    regenerate_user
    resubmit_error_certificates
    ungenerated_certs

```

**Comment by pdpinch** [comment]
@bdero can you make me a fake cert on micromasters.d.mitx.mit.edu ?

```
./manage.py lms create_fake_cert pdpinch-micromasters course-v1:MITx+CTL.SC1x_2+1T2016 --mode verified --grade 0.95
```

Or, if I should be able to run this myself, could you remind me how?

**Comment by amir-qayyum-khan** [comment]
@bdero is there way to check if course has certification or not?
``X = (total number of courses in the program minus the courses with certificates)``

https://github.com/mitodl/micromasters/issues/226

@pdpinch @giocalitri

**Comment by giocalitri** [comment]
I was going to write something about this right now

**Comment by giocalitri** [comment]
the problem with the management command is that it assumes that the course mode `verified` already exists.
I am going to paste some code to create it

**Comment by giocalitri** [comment]
To be able to see a course as passed, in Micromasters, the course needs to be "past", meaning the end date should be past.
In EDX, you need to create a verified enrollment and certificate for the micromaster course for a user.
To manually create a certificate for a user `bob` for a course `course-v1:odl+GIO101+CR-FALL15`:
```
from certificates.models import CertificateStatuses
from certificates.tests.factories import GeneratedCertificateFactory
from django.contrib.auth.models import User
from opaque_keys.edx.keys import CourseKey
bob = User.objects.get(username='bob')
course_key = CourseKey.from_string('course-v1:odl+GIO101+CR-FALL15')
GeneratedCertificateFactory.create(user= bob, course_id=course_key, status=CertificateStatuses.downloadable, mode='verified', download_url='www.google.com', grade="0.88",)
```
Make sure the user `bob` is already enrolled in the course, then change the enrollment mode to `verified` in the following way:
```
from course_modes.models import CourseMode
from enrollment.api import update_enrollment
CourseMode.objects.create(course_id=course_key, mode_slug='verified', mode_display_name='Gio verified', min_price=50, )
update_enrollment('bob', 'course-v1:odl+GIO101+CR-FALL15', mode='verified')

```

**Comment by bdero** [comment]
@pdpinch I've generated the certificate for you on `micromasters.d`:
```
$ ./manage.py lms --settings=aws create_fake_cert pdpinch-micromasters course-v1:MITx+CTL.SC1x_2+1T2016 --mode verified --grade 0.95
2016-05-06 13:23:36,914 INFO 28516 [dd.dogapi] dog_stats_api.py:66 - Initializing dog api to use statsd: localhost, 8125
System check identified some issues:

WARNINGS:
wiki.ArticleRevision.ip_address: (fields.W900) IPAddressField has been deprecated. Support for it (except in historical migrations) will be removed in Django 1.9.
	HINT: Use GenericIPAddressField instead.
2016-05-06 13:23:37,512 INFO 28516 [certificates.management.commands.create_fake_cert] create_fake_cert.py:100 - Created certificate for user 15 in course course-v1:MITx+CTL.SC1x_2+1T2016 with mode verified, status downloadable, and grade 0.95
```
