### ISSUE TITLE
Increase order fulfillment timeout on frontend

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1590]
I think I saw this take longer than 30 seconds for it to succeed, can't reproduce it unfortunately. I feel like we should set it higher, maybe 2 minutes

**Comment by pdpinch** [comment]
Is this configured in our code, or somewhere else?

**Comment by noisecapella** [comment]
It's configured in our JS code, specifically https://github.com/mitodl/micromasters/blob/master/static/js/containers/DashboardPage.js#L114
