### ISSUE TITLE
CI build is really slow

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#1593]
CI builds are pretty slow, ranging from 13 minutes to 16 minutes or so on average. Since the whole test suite (for python and JS, with linters and all that) only takes about 5 minutes to finish I think we should really try to work on getting the build time down to something closer to the test execution time.

When watching builds in progress it seems to be that the majority of the time is spent assembling the docker images. One piece of low-hanging fruit we might be able to grab is to pre-build docker images (from `master`, say) and upload them to Docker hub. That way the majority of builds would not need to rebuild the python docker container at least. We could explore how to deal with `npm` as well, although I think there are reasons we don't add `npm` dependencies in the build for the `watch` container.

travis has some info about how to accomplish this [here](https://docs.travis-ci.com/user/docker/) and [here](https://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci/).

thoughts? I think given the number of tests and the size of our codebase a 16 minute PR build is waayyyy too long.

**Comment by noisecapella** [comment]
Having `npm install` use the shared `node_modules` directory is mostly a matter of convenience, we should feel free to change it if we want

**Comment by aliceriot** [comment]
I opened a branch with some changes to try to deal with this stuff here: https://github.com/mitodl/micromasters/compare/ap/faster-builds

By using pre-built docker images (pushed to docker-hub) I was able to pretty easily get the build time from around 6.5 minutes down to just over 2 minutes.

The next thing to reach for is probably setting up parallel builds, so we can execute one job for the python tests and then one for the JavaScript tests.
