### ISSUE TITLE
Add environment variable to affect Elasticsearch pagination size

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1596]
The environment variable should default to `10` which is Elasticsearch's default for `size`, and we should always set a `size` when we construct the query on the server

**Comment by amir-qayyum-khan** [comment]
@noisecapella are you taking abt this size?

![screen shot 2016-11-09 at 5 49 56 pm](https://cloud.githubusercontent.com/assets/10431250/20138908/fe5f8d72-a6a4-11e6-8ace-9feea87d684d.png)

**Comment by pdpinch** [comment]
That looks right to me -- we want to make the number of results per page configurable so it's easier to test the page navigation.

**Comment by amir-qayyum-khan** [comment]
cool, it means from now on word this size will be maintain on server side instead on client side?

**Comment by pdpinch** [comment]
That's right.
