### ISSUE TITLE
(Bug) Course with multiple past runs has incorrect border placement

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#1599]
Style rules need to be changed to get rid of the border between the past runs and the currently displayed run 

![ss 2016-10-28 at 11 58 28](https://cloud.githubusercontent.com/assets/14932219/19818205/c08e61d0-9d1c-11e6-9147-7ab2b396509f.png)

**Comment by annagav** [comment]
blocked by #1697

**Comment by pdpinch** [comment]
this is no longer blocked
