### ISSUE TITLE
add django server status

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#16]

**Comment by bdero** [comment]
Please review this PR and use this version of the code: https://github.com/mitodl/django-server-status/pull/18

I've already added the STATUS_TOKEN var to the environments of the apps; I'll also need to verify that the status check works on all apps after this work is finished and released.

**Comment by pdpinch** [comment]
@jamiefolsom, were you going to pick this up from @annagav since she's out sick today?
