### ISSUE TITLE
UserInfoCard shows email even when this information is not available from profile API

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1604]

**Comment by pdpinch** [comment]
When would e-mail not be available?

**Comment by noisecapella** [comment]
We currently don't expose email in the profile API when viewed by other users. This is currently what we let users see:

        fields = (
            'username',
            'account_privacy',
            'first_name',
            'last_name',
            'preferred_name',
            'country',
            'state_or_territory',
            'city',
            'birth_country',
            'has_profile_image',
            'profile_url_full',
            'profile_url_large',
            'profile_url_medium',
            'profile_url_small',
            'preferred_language',
            'gender',
            'work_history',
            'edx_level_of_education',
            'education'
        )
