### ISSUE TITLE
On learner page, employment or education cards should disappear if there is no information to display

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1605]
When a user views another learner's profile and that learner doesn't have an employment or education, the empty cards shouldn't be displayed.

**Comment by pdpinch** [comment]
If the cards are hidden, how will the learner enter additional employment or education?

@roberthouse54

**Comment by pdpinch** [comment]
@noisecapella I updated the description -- is that what you have in mind?

**Comment by noisecapella** [comment]
Yes that's correct

**Comment by amir-qayyum-khan** [comment]
then how to display add work history or education link? should we display only cards with ``Add`` links?

currently ui is like 

<img width="984" alt="screen shot 2016-11-07 at 6 29 01 pm" src="https://cloud.githubusercontent.com/assets/10431250/20059441/1bfe118e-a518-11e6-8fee-784efd5c89ed.png">

**Comment by pdpinch** [comment]
@amir-qayyum-khan take a look at the updated description. This only applies for users looking at another learner's profile, not their own. A user isn't allowed to edit other users' profiles.

**Comment by amir-qayyum-khan** [comment]
got it thanks
