### ISSUE TITLE
Student Dashboard: add background

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#161]
We need the image

**Comment by aliceriot** [comment]
@pdpinch to confirm, is this to add the background for the profile bar? as seen here: https://projects.invisionapp.com/share/KR6FYCZTX#/screens/142338434

**Comment by pdpinch** [comment]
That's correct. 

I thought I had a PNG for the image, but I can't locate it right now.

**Comment by aliceriot** [comment]
there's one linked over in #97 , can I just use that?

**Comment by pdpinch** [comment]
Yes!

I knew when I put it there I wasn't going to be able to find it again...

**Comment by aliceriot** [comment]
haha, yeah it's easy to lose things.

cool, I have a pr ready then.
