### ISSUE TITLE
Course Status Start Date mismatch

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1612]
Program:  Supply Chain Management
Course: Supply Chain Analytics
Micromasters-RC
Site is displaying a Start Date of 11/1/2016
(see snapshot)

But the following is showing a Start Date in the database of 11/2/2016
Peter noticed that the start time in the Data is 00:00 -- so wondering if the issue might involve timezones?

 python manage.py alter_data --action=course_info --email='jtausig@mit.edu' --program-title='Chain' --course-title='Analytics'
{
  "course_runs": [
    {
      "upgrade_deadline": "12/07/2016",
      "start_date": "11/02/2016",
      "enrollment_end": "12/07/2016",
      "end_date": "12/28/2016",
      "edx_course_key": "course-v1:MITx+CTL.SC0x+3T2016",
      "enrollment_start": "05/01/2016",
      "id": 59
    }
  ],
  "course_title": "Supply Chain Analytics"

![start date](https://cloud.githubusercontent.com/assets/13886722/19871561/c8f61a04-9f8b-11e6-9596-abe47e076e63.PNG)

**Comment by pdpinch** [comment]
@gsidebo are we converting dates and times to the user's local time in the front end?

**Comment by noisecapella** [comment]
@pdpinch yes I think timezones are the problem here. The course start and end dates are stored as times, probably at midnight UTC but they are rendered in Eastern time

**Comment by gsidebo** [comment]
yup, just confirmed these dates are midnight UTC. moment (our JS date/time library) parses these dates and shows an earlier time. @noisecapella that's correct behavior then, right? that start is returned in the API as "2016-11-02T00:00:00Z", which seems to be parsed by moment as 11/01/2016 in EST. i can open up a quick PR to coerce these datetimes to EST before formatting them. #1613 is the same issue and should be closed

**Comment by noisecapella** [comment]
I think the `alter_data` management command should be adjusted to set times relevant to EST, otherwise I think everything looks fine

**Comment by pdpinch** [comment]
I like George's suggestion of changing the management command to record the dates as expected. I think moment is doing the right thing.
