### ISSUE TITLE
Course Status Enrollment Date doesn't match data

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1613]
Not sure if this is the same issue as #1612  -- (that was Start date and this involves Enrollment begins date).

Ran the following query:
python manage.py alter_data --action=course_info --email='jtausig@mit.edu' --program-title='Chain' --course-title='Fundamental'

Which returned:
"course_runs": [
    {
      "edx_course_key": "course-v1:MITx+CTL.SC1x_3+1T2017",
      "start_date": null,
      "id": 62,
      "enrollment_start": "01/01/2030",
      "end_date": null
    },
    {
      "enrollment_end": "05/10/2016",
      "edx_course_key": "course-v1:MITx+CTL.SC1x_2+1T2016",
      "start_date": "02/10/2016",
      "id": 61,
      "enrollment_start": "02/10/2016",
      "end_date": "05/10/2016"
    },
    {
      "enrollment_end": "08/28/2015",
      "edx_course_key": "course-v1:MITx+CTL.SC1x_1+2T2015",
      "start_date": "05/20/2015",
      "id": 14,
      "enrollment_start": "05/20/2015",
      "end_date": "08/28/2015"
    },
    {
      "enrollment_end": "12/24/2014",
      "edx_course_key": "course-v1:MITx+ESD.SCM1x+3T2014",
      "start_date": "09/24/2014",
      "id": 60,
      "enrollment_start": "09/24/2014",
      "end_date": "12/24/2014"
    },
    {
      "edx_course_key": "MITx/ESD.SCM1x/3T2014",
      "start_date": "09/24/2014",
      "id": 17,
      "enrollment_start": "09/24/2014",
      "end_date": "12/24/2014"
    }
  ],
  "course_title": "Supply Chain Fundamentals"
}

That suggests an enrollment begins date of 1/1/2030, but on rc, we are displaying an enrollment begins date of 12/31/2029.
(screenshot below)

Additionally, there is no start date, yet we are showing a fuzzy date of January 2017 -- where is that coming from?

![enroll future fuzzy start](https://cloud.githubusercontent.com/assets/13886722/19891888/870a0d84-a018-11e6-8851-c84d13796db4.PNG)

**Comment by noisecapella** [comment]
I think this is because the dates are set to midnight UTC but they are being displayed in Eastern time

**Comment by j2tausig** [comment]
if that were the case, wouldn't we expect to see all the displayed dates off by one?  And that is not what I'm seeing.  Some dates match, and others do not....
