### ISSUE TITLE
If user switches to their profile before the profile API is loaded, they go to /learner/undefined

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1614]
We should disable the user menu while the APIs are loading

**Comment by pdpinch** [comment]
Which page is this? The dashboard?

Why is the profile necessary to render the user settings?

**Comment by noisecapella** [comment]
It looks like we use `profile.username` to get the username for this link, so before the profile is actually loaded this doesn't have any information. We can switch to `SETTINGS.user.username` which should be always available
