### ISSUE TITLE
Make enrollment and upgrade links active

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#162]
Provide the same endpoints as edX does for enrollment and upgrade to verified. 

All we need is a course key and a logged in user.

**Comment by pdpinch** [comment]
For "enroll" we can use the enrollments API: http://edx.readthedocs.org/projects/edx-platform-api/en/latest/enrollment/enrollment.html#view-and-add-to-a-users-course-enrollments This supports a POST, so it looks like its easiest and best to enroll the user without leaving micromasters. 

For "upgrade to verified" we have no choice but to drop the user into the edX shopping cart flow. The URLs look like this: https://courses.stage.edx.org/course_modes/choose/course-v1:ASUx+CreditDemo+Demo_Course/ (See ### for discussion).

**Comment by pdpinch** [comment]
In the interests of getting this done, we can implement the enroll button as a link instead of a POST for now also.

**Comment by amir-qayyum-khan** [comment]
@pdpinch can i get ui image where to add these links?

**Comment by pdpinch** [comment]
See https://invis.io/UY77QX9N4#/142338434_Student_-_Dashboard
