### ISSUE TITLE
Delay dashboard load until dashboard page is fetched

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1652]
After #1569 is merged components outside the dashboard won't need the information from the dashboard API because they have access to the programs API instead. Since the dashboard API is the slowest API this should speed up page loads for non-dashboard pages

**Comment by pdpinch** [comment]
Is there a reason why we're accessing the dashboard API for non-dashboard pages?

**Comment by pdpinch** [comment]
@noisecapella I think you addressed this in the profile with #1750. What other places does this need to be done?

**Comment by noisecapella** [comment]
It should be done everywhere at this point. It only loads the dashboard API if the `DashboardPage` component is loaded, or if something happens where the user makes a change which requires a dashboard API refresh, for example if they enrolled in a new program.
