### ISSUE TITLE
Uploading a profile image erases education and employment information

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1658]

**Comment by aliceriot** [comment]
Well that's unexpected! Any ideas on what's going on?

**Comment by noisecapella** [comment]
I haven't done any research, but I have a suspicion that our update method does this all the time, we've just not noticed because all of our other PATCHes are with the entire dict. We should check if the `education` or `work_history` items are present in the data being sent, and if not we should ignore it
