### ISSUE TITLE
Search: blank pane is displayed instead of "no results" error message

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#1660]
This is effectively re-opening #1449 due to an error that was discovered on release candidate 0.21.0

The logic to display "no results" messages to users on the search results page seems to be faulty. Here's a code snippet on the release-candidate branch:

```javascript
renderFacets: Function = (currentProgramEnrollment: ProgramEnrollment): React$Element<*> => {
    if (_.isNull(this.getResults())) {
      return (
        <Card className="fullwidth" shadow={1}>
          <div className="no-hits left-nav">
            {`There are no users in the ${currentProgramEnrollment.title} program.`}
          </div>
        </Card>
      );
    }
```

Here's a screenshot of some `console.log` lines I put into `renderFacets` to debug this:

![ss 2016-11-04 at 11 28 40](https://cloud.githubusercontent.com/assets/14932219/20011413/f70f92aa-a281-11e6-9e3b-4a1c663e8868.png)

`this.getResults()` is not returning `null`. It's returning an object with no hits.

**Comment by gsidebo** [comment]
@amir-qayyum-khan @pdpinch FYI

**Comment by pdpinch** [comment]
@gsidebo what's the user impact of this?

**Comment by gsidebo** [comment]
@pdpinch from what i remember, an instructor/staff will never see the "No results" message in the search results page when their search turns up no results. they'll just see a blank pane or something like that. not a complete dealbreaker, but not insignificant, IMO. i can confirm this if you think it's important enough

**Comment by pdpinch** [comment]
This may be the same issue as #2182 Search: confusing error message when there are no results

**Comment by gsidebo** [comment]
yup, same issue. i'll close this one in favor of that
