### ISSUE TITLE
Performance: host static assets on a CDN

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1661]
Part of #1530 

In doing some testing with yslow it identified some static assets that could be hosted on a CDN. 

some of these probably already are on a CDN, but yslow doesn't know it:

- [x] fonts.googleapis.com: 2 components
- [x] js-agent.newrelic.com: 1 component
- [ ] bam.nr-data.net: 1 component

some of these would need to be changed in our build/deploy pipeline:

- [ ] micromasters.herokuapp.com: 16 components

some of these come from the CMS, which may only require a configuration change in our S3 bucket?

- [ ] odl-micromasters-production.s3.amazonaws.com: 2 components

**Comment by noisecapella** [comment]
The google fonts are difficult because they ship you different ones depending on the user agent string. There's not really a clean way to serve them locally

**Comment by pdpinch** [comment]
I used the CDN finder at www.cdnplanet.com/tools/cdnfinder/ to test whether some of these are already on a CDN. fonts.googleapis.com and js-agent.newrelic.com appear to be on a CDN and I've checked them off.

**Comment by pdpinch** [comment]
See https://docs.djangoproject.com/en/1.10/howto/static-files/deployment/#serving-static-files-from-a-cloud-service-or-cdn for documentation on how to move static files to S3. 

See http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/MigrateS3ToCloudFront.html for documentation on how to enable cloudfront for S3 buckets. We should probably put some thought into choosing appropriate CNAMEs.
