### ISSUE TITLE
Model with last call to refresh data per user per edX cache type

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#1665]
We should store when the last call to refresh the cache for an user has been done.

Possible solutions for this model are:
``` 
user
cache_type [enrollments|certificates|current_grades]
timestamp
```

or

```
user
timestamp_for_enrollments
timestamp_for_certificates
timestamp_for_current_grades
```

The first solution is more simple, the second creates less entries in the DB

**Comment by Ferdi** [comment]
Can you describe the context ? What kind of cache do you have in mind  ?

**Comment by giocalitri** [comment]
@Ferdi this is part of the refactoring of the edX cached information in Micromasters
