### ISSUE TITLE
Remove linkedin support

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#167]

**Comment by Ferdi** [comment]
@pdpinch @noisecapella what is the status of this ?

**Comment by pdpinch** [comment]
It's non-functional, but we still have some LinkedIn API code:

https://github.com/mitodl/micromasters/blob/master/backends/pipeline_api.py#L100-L128
https://github.com/mitodl/micromasters/blame/master/backends/pipeline_api_test.py#L8
https://github.com/mitodl/micromasters/blame/master/backends/pipeline_api_test.py#L252-L264
https://github.com/mitodl/micromasters/blame/master/profiles/models.py#L178
https://github.com/mitodl/micromasters/blame/master/micromasters/settings.py#L177
https://github.com/mitodl/micromasters/blame/master/micromasters/settings.py#L184-L199
https://github.com/mitodl/micromasters/blob/master/backends/fixtures/linked_in_response.json
https://github.com/mitodl/micromasters/blob/master/.env.example#L5-L6

**Comment by pdpinch** [comment]
Looks like this is in progress, @singingwolfboy ?
