### ISSUE TITLE
Course Status State: Enrolled with Future Start displaying incorrect # of days to start

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1676]
Tested on RC.
Set a Course state to enrolled with a future start date.
python manage.py alter_data --action=set_course_to_enrolled --username=staff --program-title=’Analog’ --course-title='100' --in-future

The underlying data is a start date of 11/24/2016 (which is 20 days from today), but
the messaging is "Course starts in 19 days".

![future start date](https://cloud.githubusercontent.com/assets/13886722/20021401/fbc8b43c-a2ab-11e6-83f3-67767465a4c0.PNG)

Course_info data:
{                                                                                           
  "course_runs": [                                                                          
    {                                                                                       
      "edx_course_key": "course-v1:MITx+Analog+Learning+100+Nov_2016",                      
      "enrollment_start": "10/30/2016",                                                     
      "enrollment_end": "11/09/2016",                                                       
      "upgrade_deadline": "11/29/2016",                                                     
      "start_date": "11/24/2016",                                                           
      "end_date": "12/24/2016",                                                             
      "edx_data": {                                                                         
        "CachedEnrollment": {                                                               
          "data": {                                                                         
            "course_details": {                                                             
              "enrollment_start": "2016-10-30T20:19:52.226506",                             
              "enrollment_end": "2016-11-09T20:19:52.226506",                               
              "course_id": "course-v1:MITx+Analog+Learning+100+Nov_2016"                    
            },                                                                              
            "user": "Jared",                                                                
            "mode": "verified"                                                              
          },                                                                                
          "last_request": "12/04/2016"                                                      
        }                                                                                   
      },                                                                                    
      "id": 98                                                                              
    },                                                                                      
    {                                                                                       
      "edx_course_key": "course-v1:MITx+Analog+Learning+100+Aug_2015",                      
      "enrollment_start": "08/14/2015",                                                     
      "enrollment_end": "08/28/2015",                                                       
      "upgrade_deadline": "08/21/2015",                                                     
      "start_date": "08/14/2015",                                                           
      "end_date": "12/14/2015",                                                             
      "id": 97                                                                              
    },                                                                                      
    {                                                                                       
      "edx_course_key": "course-v1:MITx+Analog+Learning+100+Jan_2015",                      
      "enrollment_start": "01/14/2015",                                                     
      "enrollment_end": "01/28/2015",                                                       
      "upgrade_deadline": "01/21/2015",                                                     
      "start_date": "01/14/2015",                                                           
      "end_date": "05/14/2015",                                                             
      "id": 96                                                                              
    }                                                                                       
  ],                                                                                        
  "course_title": "Analog Learning 100"                                                     
}

**Comment by pdpinch** [comment]
@gsidebo suggests we change the rounding, or we can remove the times altogether in the calculation.
