### ISSUE TITLE
Accessibilty: add headings to profile page html

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1685]
- [ ] Wrap the Micromasters title in a `<h1>` tag. 
- [ ] Wrap the profile image labeled as "profile image for FIRSTNAME" in an `<h2>` tag
- [ ] Wrap main content in a [`<main>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main) element

**Comment by pdpinch** [comment]
@singingwolfboy does this set of changes make sense to you?

**Comment by singingwolfboy** [comment]
Putting the "Micromasters" title in an `<h1>` tag and using a `<main>` tag make sense. However, I'm not sure about the profile image in an `<h2>` tag. Headings are normally text, not images, as far as I'm aware. A profile image also doesn't really seem like a heading to me. Can you clarify exactly what should happen for taht?

**Comment by pdpinch** [comment]
Can you follow up with Mary Z on https://github.mit.edu/ODLaccessibility/MicroMasters-Portal/issues/6
