### ISSUE TITLE
Dashboard API ignores past course runs (regression)

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#1697]
A regression was introduced in our performance optimization efforts. The dashboard API no longer returns information about past course runs. Any course runs that a user has passed/failed, for example, are no longer retrieved.

**Comment by gsidebo** [comment]
*NOTE:* I still need to confirm with certainty that our suspicions are correct with this bug. I'm doing some testing now

**Comment by gsidebo** [comment]
@j2tausig FYI this should cover the behavior you noticed with passed/failed courses on -rc

**Comment by j2tausig** [comment]
@gsidebo cool.  Thanks! (fingers crossed)
