### ISSUE TITLE
Search: Semester facet

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1710]
![image](https://cloud.githubusercontent.com/assets/20047260/20190091/068666ac-a74e-11e6-8293-62dd5dcf8ee8.png)

## Acceptance Criteria:

- [ ] 2nd facet, after course
- [ ] user can only choose one value at a time ("and" facet)
- [ ] add course run to index, if it isn't already. 
- [ ] mapping of runs to labels: 
  1T2016 = "Spring 2016"
  2T2016 = "Summer 2016"
  3T2016 = "Fall 2016"
  etc. 
- [ ] if the run is ambiguous, fail over to using dates. @pdpinch will spec them. 
- [ ] Selecting a semester without selecting a course, will return all students who are enrolled in any course during the selected semester.
- [ ] unlike other facets, we would like to order these facets in reverse chronological order, instead of ordering by hits. e.g. 
  2016 - Fall
  2016 -  Summer
   2016 - Spring
  2015 -Fall
  etc. 
  This list is limited to the first 5. Clicking "see more" would reveal the whole list.

**Comment by pdpinch** [comment]
Although runs are free-from in edX, afaict all course runs in MicroMasters conform to this scheme.

**Comment by roberthouse54** [comment]
![image](https://cloud.githubusercontent.com/assets/20047260/20190043/d1153070-a74d-11e6-9a83-6c33e06cf108.png)

We will display the first 5 semesters, in reverse chronological order. Clicking "See More" will expand to display all the semesters.

**Comment by pdpinch** [comment]
Are you sure we want to change the standard behavior of this facet, regarding which facets are displayed and their order? Normally we'd order by hits descending, and we wouldn't show a facet with no hits.

**Comment by Ferdi** [comment]
@pdpinch that's a good point.

**Comment by roberthouse54** [comment]
OK, that is a good point. I assumed it would be easier to scan if the selections were by date, but it may be better to just go for consistency.

**Comment by pdpinch** [comment]
After discussing further, we decided to go with reverse chronological order, based on semester, if not too much trouble.

**Comment by pdpinch** [comment]
We will need an entry for each run, in case the user has enrolled multiple times.

**Comment by noisecapella** [comment]
We can use the https://github.com/edx/opaque-keys/ library to handle both old and new style course keys

**Comment by giocalitri** [comment]
I started to work on this issue, but moved to another one.
What I have done is partial and in the branch `semester_1710`

**Comment by gsidebo** [comment]
fyi: i changed the branch name to `1710_course_semester_facet` b/c i have a bunch of local scripts that look for an issue # at the beginning of the branch name :)
