### ISSUE TITLE
Search: Final Grade facet

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1711]
![image](https://cloud.githubusercontent.com/assets/20047260/20535819/6e8d2da2-b0b4-11e6-9ccd-787411fbd181.png)

## Acceptance Criteria

- [ ] This facet is only active when a course has been chosen in the course facet (#933). When the user selects a course, an area expands under the course name, and we display the additional facet, "Final Grade".
- [ ] Histogram is populated with the final grades of the users/courses in the current result set. 
- [ ] If a user has more than one grade in the currently-selected course we would (ideally) use the highest grade
- [ ] When this filter is applied, any users without a final grade will be removed from the result set. 

## Related issues

#933 Course facet
#1730 payment status facet

**Comment by roberthouse54** [comment]
<img width="700" alt="upload" src="https://cloud.githubusercontent.com/assets/20047260/20192860/992a96a8-a759-11e6-92e3-3aec883c7474.png">

This filters by grade in the selected course. In the case of a user who has taken more than one run of the same course, we will have a bit of a problem, but we should just display any user who has fit the criteria in ANY run they have completed.

**Comment by pdpinch** [comment]
I updated the description with Rob's mock-up and comments. 

I'll delete these comments.

**Comment by roberthouse54** [comment]
For this design, the "Grade" means "Final Grade" only. It does not include "Current Grade" for course runs that are in progress. That means that if filters by grade at all, the results set will not include any users that only have a "Current grade" in an "In Progress" course run.

**Comment by gsidebo** [comment]
Just want to chime in and say that this might be a pretty significant effort. I did some poking around in searchkit to see what was involved. I didn't look to go into exhaustive detail, so here are some stray thoughts about the technical work involved.

- I'm not exactly sure about how we would set up the index in such a way that we could index multiple course grades per user and build a histogram only on the values that match the selected course. The current logic for program/course-specific indexing for users is at search/indexing_api.py:248. The per-course grades would probably be indexed as a sibling to `enrollments` and `semester_enrollments`. We won't be able to implement the feature at all before we figure this out.
- The current Course facet uses `HierarchicalRefinementFilter`. We will almost definitely need to create a new component that subclasses `HierarchicalRefinementFilter` and conditionally shows the histogram when a course is selected. We should be sure to review the [searchkit docs on extending components](http://docs.searchkit.co/stable/docs/setup/extending-components.html). It might not give us what we need but it's worth a look.
- If/when we figure out the indexing structure for the histogram, the new component will itself call `RangeFilter` with `showHistogram={true}` to get the actual histogram to show up.

**Comment by gsidebo** [comment]
Just chatted with @giocalitri and he brought up the possibility of rendering these grade histograms separately. We haven't tried using the searchkit histogram on nested properties yet, but we should see how they render. If they render in a way that passes the @roberthouse54 test, we _might_ be able to get this for 'free' rather than hacking searchkit components. I can get a quick example running locally (or at least determine that it isn't possible) in a relatively short amount of time. @annagav do you have any idea when you'll be starting work on this?

**Comment by annagav** [comment]
I have a little bit of work left for the other PR. Feel free take it!

**Comment by gsidebo** [comment]
I'm not ready to take it quite yet either. Let's just keep each other posted
