### ISSUE TITLE
Search: results should be displaying First Name and Last Name.

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#1712]
The default search sorting is by `Last Name` but then we only show the preferred name (my guess).

![screen shot 2016-11-08 at 1 35 18 pm](https://cloud.githubusercontent.com/assets/1005204/20111989/7063dcf4-a5b8-11e6-86fb-e8223d0afe30.png)

**Comment by pdpinch** [comment]
@roberthouse54

**Comment by roberthouse54** [comment]
The search results should be displaying First Name and Last Name.

**Comment by pdpinch** [comment]
@roberthouse54 <First Name> <Last Name> or <Last Name>, <First Name> ?

**Comment by Ferdi** [comment]
Sorting should not have any effect on what's shown in the search result

**Comment by giocalitri** [comment]
Sorting works.
It is only the display that is confusing.

**Comment by roberthouse54** [comment]
First Name Last Name, as in the mock.

**Comment by pdpinch** [comment]
@amir-qayyum-khan this doesn't need a "Work in progress" label does it?

**Comment by aliceriot** [comment]
I said this in standup this morning, but I think the preferred name should be included in the search result too. Something like `First Last (Preferred)`. I think we should ensure that people who are e.g. sending an email to a user would know what name to use when addressing them.

**Comment by roberthouse54** [comment]
OK, I think First Last (Preferred) is an acceptable solution for the time being, but I think at some point I'd like to add column headers here as the table will be getting a bit more complex. If we did that the column headers could be First Name/Last Name and Preferred Name
