### ISSUE TITLE
Search: Payment Status facet

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#1730]
Depends on #933 

![image](https://cloud.githubusercontent.com/assets/20047260/20535919/f0e924cc-b0b4-11e6-90ac-6877d6148ec6.png)

## Acceptance Criteria

- [ ] User first must select a course. Then an area expands under the course name, and we display an additional facet with two values, "paid" and "auditing"
- [ ] User can choose to further filter by either "Paid" or "Auditing".

**Comment by roberthouse54** [comment]
<img width="700" alt="upload" src="https://cloud.githubusercontent.com/assets/20047260/20193142/b3113760-a75a-11e6-9166-a6431336f173.png">

The Payment status shows up below the grade filter. It filters student by whether they have paid or are auditing the course selected. 

If a student had previously been auditing a course, then paid, consider them paid.
If a student had previously paid but was currently retaking a course as audit, consider them auditing.
If a student had previously completed multiple runs that are a combination of paid and audit, consider them paid.

I think this logic makes sense, but this may need some discussion.

**Comment by pdpinch** [comment]
@roberthouse54 I think your 2nd and 3rd statements contradict each other. 

I think we have two (simple) options:

- If the learner has ever paid for the course, consider them paid
- Or, if the learner paid for their most recent enrollment, consider them paid

I think the former makes more sense, but I think either of these is possible.

**Comment by aliceriot** [comment]
@pdpinch which of those two things should I use when determining if a user is paid or not?

I also do not think it is going to be straightforward to do a grade filter inside of a particular course, I don't think searchkit supports this.

**Comment by aliceriot** [comment]
Hum, we may not even be able to do the hierarchical menu with the fields in question. Searchkit does not support using nested fields on a hierarchical menu (like what we're using for the country). We have a nested array for enrollments because there are multiple enrollments per user.

I can fairly easily implement two separate facets, on for course enrollments and another for verification status - this would allow the user to target the same groups of users.

what do we think?

**Comment by aliceriot** [comment]
@roberthouse54 @pdpinch

**Comment by pdpinch** [comment]
Alice, Gavin and I just spoke and I clarified that her suggestion of implementing two facets was, in fact, what we intended. The "hierarchical" nature of the course facets is just UI.

**Comment by gsidebo** [comment]
@pdpinch here are a couple screenshots

**1) No filter applied**
![ss 2016-12-13 at 10 58 40](https://cloud.githubusercontent.com/assets/14932219/21147508/474a4c14-c123-11e6-8422-c8695c020109.png)

**2) Course filter applied**
![ss 2016-12-13 at 10 57 50](https://cloud.githubusercontent.com/assets/14932219/21147515/4bb2904a-c123-11e6-97e6-f3bd7b5048dc.png)
