### ISSUE TITLE
URL for learners does not work with usernames containing dots

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#1731]
![screen shot 2016-11-09 at 3 52 04 pm](https://cloud.githubusercontent.com/assets/1005204/20154258/8fbca950-a694-11e6-965e-595549b6a1c3.png)

**Comment by amir-qayyum-khan** [comment]
@giocalitri edX dont allow it as well

<img width="586" alt="screen shot 2016-11-14 at 5 42 54 pm" src="https://cloud.githubusercontent.com/assets/10431250/20265261/db086768-aa91-11e6-84b7-224b3ea59491.png">

**Comment by giocalitri** [comment]
I still think we should fix it on our side: edx will need to fix this eventually.
