### ISSUE TITLE
seed_db needs to be updated for financial aid programs

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#1736]
seed_db command now creates enrollments and certificates for an user, but for create a proper environment, also current grades, orders and order lines should be created for at least program with financial aid.

I worked on adding this functionality in another PR but it turned to be too much work, so I am attaching to this issue what I have been done as a patch file.

to restore this patch file unzip the attached file and run
`patch -p0 < seed_db.patch`

what I have done:
- created current grades for each user in `seed_data/management/users.json` 
- modified `seed_data/management/commands/seed_db.py` to load the current grades

what needs to be done:
- for each current grade (currently all passed), we should create an order and an order line

[seed_db.patch.zip](https://github.com/mitodl/micromasters/files/584383/seed_db.patch.zip)

**Comment by gsidebo** [comment]
at this point i would strongly suggest that we just update the generation script

**Comment by pdpinch** [comment]
@giocalitri @gsidebo Is this still an issue? I feel like the last time I ran seed_db I got orders to go with my fake users.

**Comment by gsidebo** [comment]
yeah this is implemented now
