### ISSUE TITLE
Purchase Confirmation Email has no MIT/ODL or MicroMasters branding

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1738]
Steps to reproduce:
Purchase a course.

The only MicroMasters branding on the purchase confirmation email is the "from field"  Can we perhaps add a logo or a link or something?

@pdpinch 
![confirm email](https://cloud.githubusercontent.com/assets/13886722/20194673/5c53a258-a761-11e6-83f0-459250eff22f.PNG)

**Comment by noisecapella** [comment]
It looks like there's a way to set a logo:

![screenshot from 2016-11-10 16-25-23](https://cloud.githubusercontent.com/assets/863262/20194914/512bb2c0-a762-11e6-941b-fc0b513709d7.png)

**Comment by roberthouse54** [comment]
Can we test this feature somehow @noisecapella ? Here is a logo. I am not sure about the size requirements.

![micromasters_logo_email](https://cloud.githubusercontent.com/assets/20047260/21358975/98d7ee1c-c6a8-11e6-885b-80baabd118ea.png)

**Comment by roberthouse54** [comment]
It could look like this for example, but I don't know where they put the logo:

![image](https://cloud.githubusercontent.com/assets/20047260/21359266/af190b1a-c6a9-11e6-9996-94b3e18fc04a.png)

**Comment by pdpinch** [comment]
The logo size is limited to 840x60 so I sized it down to 479x60. Here's what it looks like coming from the test business center. 

<img width="1063" alt="screenshot 2017-01-06 09 41 39" src="https://cloud.githubusercontent.com/assets/430126/21721058/79b31cec-d3f4-11e6-8b08-0a8f725dc01d.png">

@roberthouse54 let me know if this looks okay, and I can put it into production. Or we can test another logo.

**Comment by roberthouse54** [comment]
I think we could make it half that size.

**Comment by pdpinch** [comment]
How's this? (240x30 pixels, resized in photoshop)

<img width="1063" alt="screenshot 2017-01-08 13 32 58" src="https://cloud.githubusercontent.com/assets/430126/21752498/522e45c0-d5a7-11e6-84c8-8e41a85495b8.png">

**Comment by roberthouse54** [comment]
That looks good.

**Comment by pdpinch** [comment]
I made the change. Just need to make a purchase to confirm.

**Comment by pdpinch** [comment]
Confirmed.
