### ISSUE TITLE
Django debug toolbar creating huge amount of log noise

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#1741]
(copied from Hipchat)

[1:54 PM] Gavin Sidebottom: is there some extra setup we need to perform for the Django debug toolbar? right now im running the app locally on the master branch, and the web server log output for just a reload of the dashboard page is 1951 lines/426kb. almost all of it seems to be errors generated from the debug_toolbar
[1:55 PM] Gavin Sidebottom: (running in debug mode, if that wasnt obvious)
[1:55 PM] Gavin Sidebottom: example snippet:

> [2016-11-09 18:45:44] DEBUG 14 [django.template] base.py:929 - [17a006a9cbb4] - Exception while resolving variable 'in_trans' in template 'debug_toolbar/panels/sql.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'SQLPanel' object is not subscriptable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
KeyError: 'in_trans'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'in_trans'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'in_trans'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [in_trans] in '{\'is_select\': True, \'stop_time\': 1478717144.5704074, \'params\': \'["192.168.99.100", 8079, 0, "192.168.99.100", true, 1, true, 2, 3, "192.168.99.100", true]\', \'trace_color\': \'#800000\', \'width_ratio_relative\': 65.8965344048217, \'is_slow\': False, \'form\': <SQLSelectForm bound=False, valid=Unknown, fields=(sql;raw_sql;params;alias;duration;hash)>, \'stacktrace\': \'<span class="djdt-path">/usr/local/lib/python3.5/site-packages/raven/</span><span class="djdt-file">middleware.py</span> in <span class="djdt-func">__call__</span>(<span class="djdt-lineno">35</span>)\\n  <span class="djdt-code">iterable = self.application(environ, start_response)</span>\\n<span class="djdt-path">/usr/local/lib/python3.5/site-packages/wagtail/wagtailcore/</span><span class="djdt-file">middleware.py</span> in <span class="djdt-func">process_request</span>(<span class="djdt-lineno">22</span>)\\n  <span class="djdt-code">request.site = Site.find_for_request(request)</span>\\n<span class="djdt-path">/usr/local/lib/python3.5/site-packages/wagtail/wagtailcore/</span><span class="djdt-file">models.py</span> in <span class="djdt-func">find_for_request</span>(<span class="djdt-lineno">154</span>)\\n  <span class="djdt-code">&#39;root_page&#39;</span>\\n<span class="djdt-path">/usr/local/lib/python3.5/site-packages/nplusone/ext/django/</span><span class="djdt-file">patch.py</span> in <span class="djdt-func">fetch_all</span>(<span class="djdt-lineno">275</span>)\\n  <span class="djdt-code">original_fetch_all(self)</span>\', \'width_ratio\': 65.8965344048217, \'start_offset\': 0, \'end_offset\': 65.8965344048217, \'duration\': 2.81524658203125, \'vendor\': \'unknown\', \'rgb_color\': [256.0, 0, 0], \'raw_sql\': \'SELECT "wagtailcore_site"."id", "wagtailcore_site"."hostname", "wagtailcore_site"."port", "wagtailcore_site"."site_name", "wagtailcore_site"."root_page_id", "wagtailcore_site"."is_default_site", CASE WHEN ("wagtailcore_site"."hostname" = %s AND "wagtailcore_site"."port" = %s) THEN %s WHEN ("wagtailcore_site"."hostname" = %s AND "wagtailcore_site"."is_default_site" = %s) THEN %s WHEN "wagtailcore_site"."is_default_site" = %s THEN %s ELSE %s END AS "match", "wagtailcore_page"."id", "wagtailcore_page"."path", "wagtailcore_page"."depth", "wagtailcore_page"."numchild", "wagtailcore_page"."title", "wagtailcore_page"."slug", "wagtailcore_page"."content_type_id", "wagtailcore_page"."live", "wagtailcore_page"."has_unpublished_changes", "wagtailcore_page"."url_path", "wagtailcore_page"."owner_id", "wagtailcore_page"."seo_title", "wagtailcore_page"."show_in_menus", "wagtailcore_page"."search_description", "wagtailcore_page"."go_live_at", "wagtailcore_page"."expire_at", "wagtailcore_page"."expired", "wagtailcore_page"."locked", "wagtailcore_page"."first_published_at", "wagtailcore_page"."latest_revision_created_at" FROM "wagtailcore_site" INNER JOIN "wagtailcore_page" ON ("wagtailcore_site"."root_page_id" = "wagtailcore_page"."id") WHERE ("wagtailcore_site"."hostname" = %s OR "wagtailcore_site"."is_default_site" = %s) ORDER BY "match" ASC\', \'start_time\': 1478717144.5675921, \'alias\': \'default\', \'template_info\': None, \'sql\': \'<strong>SELECT</strong> <a class="djDebugUncollapsed djDebugToggle" href="#">&#8226;&#8226;&#8226;</a> <a class="djDebugCollapsed djDebugToggle" href="#">&quot;wagtailcore_site&quot;.&quot;id&quot;, &quot;wagtailcore_site&quot;.&quot;hostname&quot;, &quot;wagtailcore_site&quot;.&quot;port&quot;, &quot;wagtailcore_site&quot;.&quot;site_name&quot;, &quot;wagtailcore_site&quot;.&quot;root_page_id&quot;, &quot;wagtailcore_site&quot;.&quot;is_default_site&quot;, <strong>CASE</strong> <strong>WHEN</strong> (&quot;wagtailcore_site&quot;.&quot;hostname&quot; = &#39;192.168.99.100&#39; <strong>AND</strong> &quot;wagtailcore_site&quot;.&quot;port&quot; = 8079) <strong>THEN</strong> 0 <strong>WHEN</strong> (&quot;wagtailcore_site&quot;.&quot;hostname&quot; = &#39;192.168.99.100&#39; <strong>AND</strong> &quot;wagtailcore_site&quot;.&quot;is_default_site&quot; = <strong>true</strong>) <strong>THEN</strong> 1 <strong>WHEN</strong> &quot;wagtailcore_site&quot;.&quot;is_default_site&quot; = <strong>true</strong> <strong>THEN</strong> 2 <strong>ELSE</strong> 3 <strong>END</strong> <strong>AS</strong> &quot;match&quot;, &quot;wagtailcore_page&quot;.&quot;id&quot;, &quot;wagtailcore_page&quot;.&quot;path&quot;, &quot;wagtailcore_page&quot;.&quot;depth&quot;, &quot;wagtailcore_page&quot;.&quot;numchild&quot;, &quot;wagtailcore_page&quot;.&quot;title&quot;, &quot;wagtailcore_page&quot;.&quot;slug&quot;, &quot;wagtailcore_page&quot;.&quot;content_type_id&quot;, &quot;wagtailcore_page&quot;.&quot;live&quot;, &quot;wagtailcore_page&quot;.&quot;has_unpublished_changes&quot;, &quot;wagtailcore_page&quot;.&quot;url_path&quot;, &quot;wagtailcore_page&quot;.&quot;owner_id&quot;, &quot;wagtailcore_page&quot;.&quot;seo_title&quot;, &quot;wagtailcore_page&quot;.&quot;show_in_menus&quot;, &quot;wagtailcore_page&quot;.&quot;search_description&quot;, &quot;wagtailcore_page&quot;.&quot;go_live_at&quot;, &quot;wagtailcore_page&quot;.&quot;expire_at&quot;, &quot;wagtailcore_page&quot;.&quot;expired&quot;, &quot;wagtailcore_page&quot;.&quot;locked&quot;, &quot;wagtailcore_page&quot;.&quot;first_published_at&quot;, &quot;wagtailcore_page&quot;.&quot;latest_revision_created_at&quot;</a> <strong>FROM</strong> &quot;wagtailcore_site&quot; <strong>INNER JOIN</strong> &quot;wagtailcore_page&quot; <strong>ON</strong> (&quot;wagtailcore_site&quot;.&quot;root_page_id&quot; = &quot;wagtailcore_page&quot;.&quot;id&quot;) <strong>WHERE</strong> (&quot;wagtailcore_site&quot;.&quot;hostname&quot; = &#39;192.168.99.100&#39; <strong>OR</strong> &quot;wagtailcore_site&quot;.&quot;is_default_site&quot; = <strong>true</strong>) <strong>ORDER</strong> <strong>BY</strong> &quot;match&quot; <strong>ASC</strong>\'}'
[2016-11-09 18:45:44] DEBUG 14 [django.template] base.py:929 - [17a006a9cbb4] - Exception while resolving variable 'duplicate_count' in template 'debug_toolbar/panels/sql.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'SQLPanel' object is not subscriptable

**Comment by pdpinch** [comment]
@gsidebo is this still an issue?

**Comment by noisecapella** [comment]
We ended up changing the default log level to `INFO` which doesn't include this noise
