### ISSUE TITLE
Disable buttons during API activity

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1752]
We should disable buttons to prevent double clicking and to provide an indication to the user of activity being done.

Off the top of my head:
 - [x] signup next and previous buttons
 - [x] edit employment
 - [x] edit education
 - [ ] delete employment
  - [ ] delete work history
 - [ ] new financial aid button
 - [ ] skip financial aid button (also disable both financial aid buttons during either API request)
 - [ ] document sent button
 - [x] pay button
 - [x] enroll link
 - [x] user page dialog buttons
 - [x] photo upload dialog
 - [x] settings page button
 - [ ] enroll in program button
 - [ ] email buttons in search results

**Comment by Ferdi** [comment]
Do you suggest we do them one by one or all at once ?

**Comment by noisecapella** [comment]
One by one is probably best, each button does a different thing so it has a different callback

**Comment by pdpinch** [comment]
This looks like it's in progress to me. I'm moving it.
