### ISSUE TITLE
EComm - FinAid calculation placed a user to "Pending Docs" status incorrectly

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1760]
Steps to Recreate:
RC
Digital Learning Program
Digital Learning 100 & 200 are both open for enrollment
Income: Mexican Peso 1,550,000
System calculated Income USD: 74843.2516737124
Original Currency: MXN

Issue:
On submit, I was expecting to receive zero discount and that no documents were required.  Instead, my status was set to "pending-docs".

**Comment by pdpinch** [comment]
@j2tausig can you confirm this with the updated tier settings?

**Comment by j2tausig** [comment]
@pdpinch I'm not able to recreate this with the updated tier settings.

**Comment by pdpinch** [comment]
I think this was a data problem, which we fixed by updating the test environment (micromasters-rc) with production data.
