### ISSUE TITLE
Exchange rate service

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1761]
I ran a FinAid Calculation using an exchange-rate from Google:
![peso to dollar](https://cloud.githubusercontent.com/assets/13886722/20310863/8e6fd744-ab1b-11e6-8fac-ea7b1f3aee8f.PNG)

@pdpinch wanted us to check the timing/frequency of the exchange rate service we are using.

(From testing I did this morning, it looks like the Date Exchange Rate is from yesterday afternoon).

**Comment by pdpinch** [comment]
we have confirmed that exchange rates are getting updated daily.
