### ISSUE TITLE
E-Comm: After submitting Fin Aid, "Skip this and Pay full Price" does not work

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1777]
Steps to recreate:
RC
Enroll in DEDP Program
Fin Aid Calculator
1,000 Indonesian Rupiah
Submit
Status changes to pending-docs w/ with Tier 1 discount applied.
Click on "Skip this & Pay Full Price"
Click on "Pay Full Price" on the "are you sure pop-up".
Expecting to see the status change from Pending-docs and the full price displayed.
Instead, nothing happens.

Status remains as "pending docs"

**Comment by pdpinch** [comment]
Here's the error in Sentry:

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/181733340/

It appears that when https://micromasters-rc.herokuapp.com/api/v0/financial_aid_skip/2/ was called it resulted in a get() that returned multiple objects. 

`MultipleObjectsReturned: get() returned more than one FinancialAid -- it returned 2!`

I think this is the query:

```
SELECT "financialaid_financialaid"."id", "financialaid_financialaid"."created_on", "financialaid_financialaid"."updated_on", "financialaid_financialaid"."user_id", "financialaid_financialaid"."tier_program_id", "financialaid_financialaid"."status", "financialaid_financialaid"."income_usd", "financialaid_financialaid"."original_income", "financialaid_financialaid"."original_currency", "financialaid_financialaid"."country_of_income", "financialaid_financialaid"."date_exchange_rate", "financialaid_financialaid"."date_documents_sent", "financialaid_financialaid"."justification", "financialaid_financialaid"."country_of_residence" FROM "financialaid_financialaid" INNER JOIN "financialaid_tierprogram" ON ("financialaid_financialaid"."tier_program_id" = "financialaid_tierprogram"."id") WHERE ("financialaid_tierprogram"."program_id" = 2 AND "financialaid_financialaid"."user_id" = 76)
```

**Comment by giocalitri** [comment]
This is possibly a regression introduced by the RESET PR: I never tested this particular case.

**Comment by pdpinch** [comment]
Sorry, I didn't either =(
