### ISSUE TITLE
Profile: User Bio

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1792]
To assist with social features, users should have a short bio included in their profile. 

Currently, we're thinking that this would be a card only on the profile page.

## Acceptance Criteria

- [x] Add card to user profile
- [x] Users can only edit their own bio
- [x] Users can view learner's bios if they can view learner's profile (same as learner profile page)
- [x] plain text only, except preserve line breaks

**Comment by pdpinch** [comment]
@Ferdi edX includes a bio in their profile. We discard this when we create user accounts. Should we keep it, just in case there's something in it?

**Comment by pdpinch** [comment]
@roberthouse54 can you update this with a mock-up?

**Comment by roberthouse54** [comment]
![about_me 2x](https://cloud.githubusercontent.com/assets/20047260/20366587/cfc0ace2-ac19-11e6-9317-6fba84b2b5f4.png)
