### ISSUE TITLE
Exams: Validate the user profiles were accepted by Pearson

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1797]
Part of #1796 

Pearson will ingest user profiles from a Candidate Data Document delivered over sftp (see #1795). The results of the ingestion will be reported back in the same sftp site, in a VCDD file (VUE Candidate Data Confirmation). We will want to update our database with the current status of user profiles and also notify us of any errors. 

- [ ] Download VCDC files from the SFTP server
- [ ] Process the VCDC files for success/failures
    - Send email to `MICROMASTERS_ADMIN_EMAIL` for failures
- [ ] Remove processed files from SFTP server

**Comment by rhysyngsun** [comment]
@pdpinch I've detailed out this ticket, it's still in `In Design`, is there any reason it can't be `Ready` at this point?

**Comment by pdpinch** [comment]
LGTM
