### ISSUE TITLE
create model & API for mm user profile

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#18]
may need to talk to Erdin to understand scope & types of fields

foreign key to the user

for example:

GET /profiles/user_id
POST /profiles/
PATCH /profiles/user_id

**Comment by justinabrahms** [comment]
```js
{
    "account_privacy": "private",
    "bio": null,
    "country": null,
    "date_joined": "2015-12-22T02:47:17Z",
    "email": "staff@example.com",
    "gender": null,
    "goals": null,
    "is_active": true,
    "language_proficiencies": [],
    "level_of_education": null,
    "mailing_address": null,
    "name": "staff",
    "profile_image": {
        "has_image": false,
        "image_url_full": "http://localhost:8000/static/images/profiles/default_500.png",
        "image_url_large": "http://localhost:8000/static/images/profiles/default_120.png",
        "image_url_medium": "http://localhost:8000/static/images/profiles/default_50.png",
        "image_url_small": "http://localhost:8000/static/images/profiles/default_30.png"
    },
    "requires_parental_consent": true,
    "username": "staff",
    "year_of_birth": null
}
```

**Comment by noisecapella** [comment]
Who is creating the user profile? We may not need the POST API if we never need to create the user profile from the dashboard. PATCH would be the only one necessary

**Comment by pdpinch** [comment]
Actually, I think we do need to create the profile form the dashboard. It needs to be created after the user has logged in the first time with their edX account.

**Comment by pdpinch** [comment]
We don't have a list of additional profile fields yet from Erdin, but here are some fields I think we need to add:

- [ ] account_privacy: private | public_to_mm | public (profiles are always visible to MIT staff)
- [ ] email-optin: Required to be true? 
- [ ] current employer (would be nice to have a pre-populated list of fortune 500 companies with some type-ahead, but that's out of scope for this story)
- [ ] Current job title 
- [ ] For US students, we'd like to know what state they are from
- [ ] social profiles, similar to the UI below from Coursera 
- [X] we already know the URL for their edX profile, if it's a public account: https://edx.org/u/{username}


![screenshot-www coursera org 2016-03-13 14-22-06](https://cloud.githubusercontent.com/assets/430126/13730484/1134868c-e927-11e5-8efe-11bf15147dc0.png)

**Comment by justinabrahms** [comment]
We should be able to create the profile after the user logs in via edx on the server side. This seems like a lower complexity avenue.

eg: 

login with edx -> edx confirmation page -> handle response { create user, create profile, backfill profile data } -> profile edit screen

**Comment by justinabrahms** [comment]
Probably not a good UX for this view in particular (cc @jamiefolsom), but we could support login with oauth for social profiles pretty easily. python social auth (a dependency we already have) makes that fairly easy.

**Comment by noisecapella** [comment]
@pdpinch What is email_optin for?

**Comment by noisecapella** [comment]
@justinabrahms will the email field for User be populated by the oauth login process?

**Comment by justinabrahms** [comment]
@noisecapella Yes. You get all of these: https://github.com/mitodl/micromasters/blob/master/backends/edxorg.py#L65

**Comment by pdpinch** [comment]
Use the edX profile data as default values and let the user override them for micromasters.

**Comment by noisecapella** [comment]
Regarding authorization, here are my thoughts at the moment:
 - no anonymous access
 - user can patch only their own profile, they cannot patch others
 - user can see their own entire profile
 - other users can see these fields of a user's profile:
   - name
   - bio
   - country
   - state
   - profile image information

Does that sound good?

**Comment by pdpinch** [comment]
Anti-spam regulations require a positive opt-in to receiving email. Since we will want to email Micromasters students we need them to agree. 

----------------
I am mobile.

**Comment by noisecapella** [comment]
If the email_optin field must always be true, is it necessary to keep track of it in this model? We can use User.is_active to say whether a user is active or not

**Comment by pdpinch** [comment]
It must be true when registering, but we will have to accommodate people who want to be removed from mailings -- probably handled by our mailing service, but I thought it best to be explicit in the model. 

----------------
I am mobile.

**Comment by noisecapella** [comment]
Right, I didn't think of that

**Comment by noisecapella** [comment]
For the limited profile I have this:

        fields = (
            'name',
            'bio',
            'account_privacy',
            'employer',
            'job_title',
            'state_or_territory',
            'country',
            'has_profile_image',
            'profile_url_full',
            'profile_url_large',
            'profile_url_medium',
            'profile_url_small',
        )

Is that good or is any of this sensitive? I'm also adding a private view which only contains account_privacy and the profile information.

If account_privacy is public, that means that users who are not logged in will be able to see this information. Is there a use case for this?

**Comment by pdpinch** [comment]
More profile fields, from Erdin:

https://docs.google.com/spreadsheets/d/1ehN3FNymCOhpJT7h9XZDOITP_lOFDnEcStRa0le4MX8/edit#gid=0

If now is a good time to include them, let's do it. I'm also fine with doing this as a follow-up story. There's still some discussion going on about what is required and what may be acquired through other services, like LinkedIn.

**Comment by pdpinch** [comment]
I'd like to think & talk some more about authorizations but I'm putting out fires. Is that blocking you?

**Comment by pdpinch** [comment]
George and I spoke about an instructor/department role that would be able to read all student profile data. We'll address this in a separate story.

**Comment by noisecapella** [comment]
I added a story for the new user profile fields: #88
