### ISSUE TITLE
Exams: add additional profile data to profile model

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1800]
part of #1796 

Pearson VUE requires the following fields which don't exist in our current profile model:

- Address1
- PostalCode (required for US and Canada; optional for other countries)
- Phone
- Phone CountryCode

Other fields we don't have that aren't required:

- MiddleName
- Suffix
- Salutation
- Address2
- Address3

All these fields can only contain characters that can be encoded in CP-1252. However, they will be transferred (and stored) as UTF8. 

For more details, see https://drive.google.com/a/pearson.com/file/d/0B5lnP24agPPYN2M5bV9sWHc2VXM

**Comment by pdpinch** [comment]
If we don't force users to use CP-1252, we may also want "shadow" fields for first name, last name and city.

**Comment by rhysyngsun** [comment]
@pdpinch @roberthouse54 to Rob's question in planning, each address field is limited to 40 characters on the Pearson side, it might be best to support all bust only require the first one. I think at this point I'm very much in favor of storing the Pearson profile data separately, but populating it initially from our existing profile.

**Comment by rhysyngsun** [comment]
I'll be adding factories and associated tests as part of this work.
