### ISSUE TITLE
Search: "Clear all filters" link appears after 1st page of unfiltered search

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1803]
Steps to recreate:
User w/ Admin rights -- navigate to the Search widget.
Pick a program with more than 10 learners.
Sort by any value.
Note that on the 2nd (or higher) page of results, the 
"clear all filters" link appears.

1st page:
![first page](https://cloud.githubusercontent.com/assets/13886722/20405356/aaf4b332-acd6-11e6-9ead-c9f948bbd8b8.PNG)

2nd page:
![second page](https://cloud.githubusercontent.com/assets/13886722/20405364/b375133a-acd6-11e6-9c68-6a4b92ac2801.PNG)

**Comment by amir-qayyum-khan** [comment]
@pdpinch i do not think so this is bug, when user press next page it change url to ``/learners/?p=2`` and clear filter appears. on press it, it reset url and take user to first page.

what are your thoughts?

**Comment by pdpinch** [comment]
I don't think being on page 2 is the same as having applied a filter. 

But I defer to @roberthouse54 -- what do you think?

**Comment by roberthouse54** [comment]
This is a bug. Pagination is different from filtering.

**Comment by Ferdi** [comment]
@pdpinch @roberthouse54  Not sure if this is causing any trouble for the user.  At least it helps to get back to the first page.
