### ISSUE TITLE
Copydown of data from Prod to RC has removed the faculty images from the carousel in SCM

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1811]
The copydown of data from Prod to RC has removed all the faculty images from the carousel in SCM and removed some of the faculty images from DEDP.

**Comment by noisecapella** [comment]
I feel like this shouldn't have been an issue since the URLs from prod should have kept working on RC. It's probably not a big deal but worth investigating just in case.

When we copied data from production to rc, did we completely wipe the old data?

**Comment by pdpinch** [comment]
I'm not sure what happened, but I just added the missing images again.
