### ISSUE TITLE
Course description pop-up on Program pages for a course listed as "not available" has no link to Edx

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1812]
Navigate to:
https://micromasters-rc.herokuapp.com/dedp/
Click on any course (one of first 4 listed).
The course description pop-up has no "view on edX" link.
![course popup](https://cloud.githubusercontent.com/assets/13886722/20439039/d0852382-ad87-11e6-88b6-178c7fff673d.PNG)

Whereas the last course on the DEDP list has this link
(or any of the course in SCM)
![course with link](https://cloud.githubusercontent.com/assets/13886722/20439058/f1255922-ad87-11e6-9391-ec32a33f53ed.PNG)

**Comment by pdpinch** [comment]
I updated the database with all the known future runs of these courses (spring and summer 2017). However, they don't have about pages on edX yet, so there's nothing to link to. We will update when ready.
