### ISSUE TITLE
FAQ's: SCM Program What are the five online courses required for the MITx MicroMasters Credential in SCM? 

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1816]
RC
Expand this FAQ:
What are the five online courses required for the MITx MicroMasters Credential in SCM? 
Note that the 5th Course is not showing the full title of the course (see screencapture).
![course name](https://cloud.githubusercontent.com/assets/13886722/20441808/06565f1a-ad94-11e6-8630-48fa58d03f9a.PNG)

**Comment by pdpinch** [comment]
Fixed in the CMS on production and rc
