### ISSUE TITLE
Better error handling of enrollment errors

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1817]
When an enrollment fails (for example, if a course key is incorrect, of if the enrollment end date has passed), edX is returning a 400 error, which leads our enrollment API to raise a 500.

The error is logged:

`Error creating audit enrollment for course key course-v1:MITx+CTL.SC0x+3T2016 for user Jared`

-- but it doesn't get raised to sentry. Since these errors are caused by configuration problems, I'd like to have them show up in Sentry. 

See also #1815 Notify users on enrollment errors.

**Comment by giocalitri** [comment]
The code intercept any response from edX that is not in the `2xx` and translates it to a `500` error.
The code also writes a `log.error` in case this happens.

In this specific case, the error edX returns is a `400`, but given that there is not a specific reason for the error, I do not think we should raise an `ImproperlyConfigured` exception.

I do not think this is an actual issue unless we want to raise specific exceptions or run additional checks.

If we really want the data to be sent to Sentry, we can add another custom exception (something like `PossibleMissconfiguration`) and intercept it in the custom exception handler like we do for `ImproperlyConfigured`, but again, we would get this exception even if there was a legit `400` error, so I am not sure what is the behavior we want.

@pdpinch ?

**Comment by pdpinch** [comment]
Fair enough. I just want to make sure the error goes to Sentry. I don't know why the error wasn't showing up in Sentry, but logs alone won't be enough for me to notice.
