### ISSUE TITLE
FAQ's: SCM Program - Link in When will the next course be run? it is hardcoded to CI

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1818]
RC
SCM Program
FAQ: When will the next course be run? 
Please expand this FAQ.  The copy has a typo, but more importantly, the link is hardcoded to CI.  If it's not possible to use a variable, please point to a production URL.
![typo hardcoded link](https://cloud.githubusercontent.com/assets/13886722/20441919/71ec5a04-ad94-11e6-952d-52930f080b85.PNG)

**Comment by pdpinch** [comment]
I was able to replace the link with a relative URL (on prod and rc)
