### ISSUE TITLE
Profile: some values in Field of Study not sorted correctly

### ISSUE THREAD

**Issue by j2tausig** [mitodl/micromasters#1824]
RC
Navigate to Profile and add any degree higher than High School.
Under field of Study -- scroll to the bottom of the list -- the last
few entries are not in correct alpha sort.  Not sure why.

**Comment by pdpinch** [comment]
@aliceriot did I see that you fixed this?

**Comment by aliceriot** [comment]
Yeah I don't think this is an issue any longer.
