### ISSUE TITLE
CMS: Preview of FAQ section causes a 500 error 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1828]
### Steps to reproduce:

Go to, for example, https://micromasters-rc.herokuapp.com/cms/pages/10/edit/
Click on Preview Button

### Expected behavior

Preview of FAQ page opens in a new window

### Actual behavior

500 error

Stack trace in Sentry: https://sentry.io/share/issue/3130343439372e313731303932363937/

**Comment by pdpinch** [comment]
I think this because the individual FAQ sections don't have a template per se. They are intended to be rolled up into one FAQ page. Ideally, the preview button would direct the user to the full FAQ.

**Comment by annagav** [comment]
Should I create a template for viewing each FAQ individually? Giving a preview of one FAQ might not be very helpful. Maybe we should try to disable this functionality.

**Comment by pdpinch** [comment]
Preview is necessary for a CMS. 

Ideally, the template for previewing individual FAQs would be the same as the template for previewing them all together. Is it possible to just point the `FaqsPage` to use the `CategorizedFaqsPage` template?

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/173436279/
