### ISSUE TITLE
React warning

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1834]
I'm seeing this warning and a bunch of similar ones after #1787 was merged, under LearnerSearchPage:

Warning: You are manually calling a React.PropTypes validation function for the `children` prop on `Slider`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by noisecapella** [comment]
I'm guessing this comes from searchkit. I'll add code to #1827 to prevent the build from failing on this warning. Hopefully they'll fix it upstream before we go to React 16

**Comment by aliceriot** [comment]
Yep, I think I noted this one in the PR. It's a problem with the `Slider` library that searchkit uses. I filed an issue on their repo for it (no comments yet).

**Comment by aliceriot** [comment]
here: https://github.com/searchkit/searchkit/issues/354
