### ISSUE TITLE
Error when viewing profile as anonymous user

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1837]
![screenshot from 2016-11-21 13-04-56](https://cloud.githubusercontent.com/assets/863262/20494481/24618f80-afeb-11e6-9452-094df9587e56.png)

**Comment by pdpinch** [comment]
Does this error impact the user experience, or does it just show up in the console? 

Is there a reason why an anonymous user needs to access the programs API?

**Comment by noisecapella** [comment]
There is currently no need for anonymous users to access the programs API AFAIK. I don't think it impacts the user experience now (there's nothing for the user to do on that page anyway) but we should fix it in case it interferes with functionality in the future
