### ISSUE TITLE
Re-label "Current Grade" on the dashboard and link to EDx Progress tab

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#1841]
The current implementation of "Current Grade" being displayed on the Dashboard for an ongoing course is confusing because the number being displayed is more like "Progress" than "Current Grade" as commonly understood. 

For example:

If a course has 10 equally weighted assessments (10% each) that add up to a Final Grade, and a student has completed the first 2 assessments with a perfect score, the "Current Grade" is 20%. I think students would expect that their current grade is 100% even though they have only completed 20% of the course requirements.

EDx does not have a very clear UI for current grade. They have a "Progress" tab, which displays the assessments in a bar graph, with a "Total %" displayed in the right. This "Total %" is what we are currently calling "Current Grade" which is not clear.

The proposed solution is simple: 

For an ongoing course, change the label to read "Course Progress" instead of "Current grade", and make the number a link to the EDx Progress tab for that course. See below:

![image](https://cloud.githubusercontent.com/assets/20047260/20500370/257673fa-b003-11e6-9511-d0516724787c.png)

**Comment by giocalitri** [comment]
the course progress page should be 
```
/courses/<course_id>/progress
```
but needs to be verified on production

**Comment by roberthouse54** [comment]
@pdpinch We should do this before the Dec 5 release.
