### ISSUE TITLE
Red border around income textbox in Firefox

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1850]
![screenshot from 2016-11-22 16-14-43](https://cloud.githubusercontent.com/assets/863262/20542258/da404358-b0ce-11e6-89b1-e4edaac1e6c9.png)

**Comment by pdpinch** [comment]
Is this on -ci, -rc or somewhere else?

**Comment by pdpinch** [comment]
Not in -rc, so must be a recent regression

**Comment by noisecapella** [comment]
I'm not seeing it now... that's odd. Closing this for now

**Comment by pdpinch** [comment]
I'm able to reproduce this, but only on Firefox. I don't see it in Safari or Chrome.
