### ISSUE TITLE
Tweet is too long 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1863]
It looks to me like we're using the meta tag description for the sample tweet text, and it's way too long for that. 

Maybe ask Maria for a sample tweet. 

![screenshot 2016-11-26 09 46 34](https://cloud.githubusercontent.com/assets/430126/20641051/3e053ede-b3bd-11e6-90c0-9ebd97e329d4.png)

**Comment by roberthouse54** [comment]
I will ask Maria for text.

**Comment by roberthouse54** [comment]
Here is the copy: 

MITx MicroMasters Programs: a new academic credential and a new path to a master’s degree from MIT. Learn more https://micromasters.mit.edu
