### ISSUE TITLE
Updating profile photo (avatar) in Safari results in 400 error from Profile API

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1866]
I'm not sure when this regression was introduced. It seems to be broken in production, -rc and -ci.

Steps to reproduce (tested in Safari):

1. Log in
2. Go to https://micromasters-rc.herokuapp.com/learner 
3. Click Camera icon to upload an image
4. Choose image (drag and drop or file dialog)
5. Click Save

### Expected Behavior

Profile photo updates with uploaded image

### Actual behavior

Same photo still there. Profile API returns a 400 error

 We should test to make sure that it works as expected in PR #1858

**Comment by pdpinch** [comment]
Updated: this issue seems to be specific to Safari. I can't reproduce it (with the same learner account) in Firefox or Chrome.

**Comment by amir-qayyum-khan** [comment]
yes, confirmed it is safari specific.

**Comment by amir-qayyum-khan** [comment]
https://github.com/reactjs/redux/issues/615#issuecomment-242743434

**Comment by pdpinch** [comment]
I know Safari is more sensitive to security mismatches than other browsers, but I don't understand how this could be the cause on micromasters-rc -- the API call should be to the same server, over https, right?

**Comment by aliceriot** [comment]
Sounds like it's not particular to the image then (based on that issue).

Does updating the other profile fields also fail?

**Comment by aliceriot** [comment]
I wonder if the problem is that we don't set 'Content-Type' and 'Accept' in the request headers.

@noisecapella any thoughts?

**Comment by aliceriot** [comment]
(we do for all the other API functions, which use the `fetchJSONWithCSRF` function, whereas the `updateProfileImage` function uses `fetchWithCSRF` and has a `FormData` object as it's payload, instead of JSON)

**Comment by noisecapella** [comment]
@aliceriot seems like a good place to start. What's in the 400 error body?

**Comment by amir-qayyum-khan** [comment]
@noisecapella 

```js
{
    "image": [
        "The submitted data was not a file. Check the encoding type on the form."
    ]
}
```

**Comment by amir-qayyum-khan** [comment]
found issue is here http://stackoverflow.com/questions/21705003/how-stable-is-canvas-toblob-method-in-different-browsers

both canvas.toBlob and canvas.msToBlob are undefined for safari
https://github.com/mitodl/micromasters/blob/master/static/js/components/CropperWrapper.js#L14

**Comment by amir-qayyum-khan** [comment]
fixed issues with this lib https://github.com/blueimp/JavaScript-Canvas-to-Blob
i creates blob from canvas. it supported by many browser
