### ISSUE TITLE
No price on `Pay now` Button

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#1871]
![screen shot 2016-11-28 at 12 57 45 pm](https://cloud.githubusercontent.com/assets/1005204/20679784/58ac07be-b56a-11e6-9b8d-12f6cf82afb2.png)

**Comment by pdpinch** [comment]
Do you know what were the prices and discounts that lead to this? I haven't seen it myself, but I've been testing only with the prices and discounts offered by DEDP.

**Comment by giocalitri** [comment]
I skipped the Financial Aid, so I am not sure it is relevant

**Comment by giocalitri** [comment]
I can also see this on CI with my additional course I just added for my tests:

![screen shot 2016-11-28 at 4 30 27 pm](https://cloud.githubusercontent.com/assets/1005204/20686785/0685405e-b588-11e6-95f1-46d980b555a4.png)

**Comment by pdpinch** [comment]
Ok. I see this now too. It looks like a CSS issue, because the price is in the HTML.

**Comment by pdpinch** [comment]
FWIW, this issue seems to be limited to -ci at the moment, so it's a recent regression.

**Comment by roberthouse54** [comment]
This seems to be an issue with the width or padding of the button.

**Comment by noisecapella** [comment]
This is still a bug on IE:

![screenshot from 2016-11-30 15-46-39](https://cloud.githubusercontent.com/assets/863262/20770577/329a4724-b714-11e6-9f9b-48332e2c16e7.png)

**Comment by noisecapella** [comment]
@roberthouse54 should I increase the column to 4 units from 3, and decrease the middle column to 2 units?
