### ISSUE TITLE
switch to yarnpkg instead of using straight npm

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#1884]
I know, I know, JavaScript hipster status and all, but yarn is actually a much nicer package manager than npm.

It:

- has 100% deterministic reproducible installs
- is really, really fast
- its dependency resolution algorithm is more aggressive, and results in a flatter dependency graph and a smaller `node_modules` dir
- has a nice lockfile format which has less churn (more readable and check-able) than `npm-shrinkwrap.json`.

I think we see a lot of pain with npm, and upgrading a single package sometimes takes a bit of time to get the shrinkwrap sorted correctly. Then the huge shrinkwrap diff (which does an ok job of getting us repeatable installs) isn't really reviewable by hand (because it's so big).

Anyway, thoughts? @noisecapella @gsidebo @singingwolfboy

**Comment by noisecapella** [comment]
Are the packages still downloaded from the npm repository?

**Comment by aliceriot** [comment]
Yes, although indirectly. Facebook runs a cache/proxy which yarn pulls from (registry.yarnpkg.com). there are some details on that here: http://blog.npmjs.org/post/151660845210/hello-yarn

**Comment by aliceriot** [comment]
But yeah, the full npm package catalog is available there. I believe the reason for the proxy is so that optimizations can be made on the backend to speed yarn up (over what would be possible using the normal npm registry).

**Comment by aliceriot** [comment]
I'm using yarn for JS packages on a couple of personal projects, and anecdotally speaking it is much, much nicer to use. It's many times faster, especially with a warm cache (for instance if all dependencies are up to date it is almost instantaneous, whereas npm can take a while to check that things are up to date).

**Comment by noisecapella** [comment]
Does it use `package.json`? What about the `npm run ...` commands? In any case I'm open to trying it out

**Comment by aliceriot** [comment]
yeah it uses `package.json` and a lockfile called `yarn.lock`.

we would still have `npm` installed, so we could keep using `npm run ...` for our various commands. alternatively, `yarn run` aliases things to the scripts defined in `package.json`.

**Comment by aliceriot** [comment]
I'll put together a branch so we can try it out.
