### ISSUE TITLE
enrollment page in React (profile creation)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#19]
for the initial enrollment and profile creation, we need to step the user through a large number of required fields. Tabs seem best suited for this:

![enroll_personal](https://cloud.githubusercontent.com/assets/430126/14467852/2dfbd70c-00ab-11e6-8202-10db421ba332.png)

**Comment by pdpinch** [comment]
I update the description and the wireframe. 

I don't know if we will use the same endpoint and container for the enrollment / profile creation, or if we will need different ones. Perhaps @noisecapella has an opinion.

**Comment by noisecapella** [comment]
I think we should have a different endpoint, `/profile/` would work.

**Comment by noisecapella** [comment]
I'm reassigning this to myself since I already did most of this in my personal page work
