### ISSUE TITLE
Handle edX timeouts better 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1901]
Sometimes edX goes down. 

And some edX users (e.g. edX employees) are enrolled in over one hundred courses. It appears that the response time from edX grows with the number of enrollments. 

The end result is a 503 Gateway error returned to us. 

![screenshot 2016-11-30 12 07 15](https://cloud.githubusercontent.com/assets/430126/20763264/430bc19a-b6f7-11e6-975e-07f160c0d831.png)

**Comment by pdpinch** [comment]
@giocalitri @blarghmatey would it help to increase the timeout? Or will we run up against Heroku's timeouts?

**Comment by giocalitri** [comment]
I think this is a duplicate of #2181

**Comment by pdpinch** [comment]
I got a 503 in this issue but it looks like George got a 500 in #2181. Otherwise, I'd say you're right and maybe #2181 is the more general case?

Which one do you want to keep?

**Comment by giocalitri** [comment]
probably #2181 (just because I explained there what we need to solve the problem)

**Comment by pdpinch** [comment]
Closed in favor of #2181

**Comment by pdpinch** [comment]
closed for reals
