### ISSUE TITLE
zendesk button is sort of invisible when in front of the footer

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#1902]
Looks like this:

![zendesk_button_hidden](https://cloud.githubusercontent.com/assets/6207644/20765654/4474ab96-b701-11e6-9858-ead6bb7d233f.png)

is this what we want?

@roberthouse54

**Comment by roberthouse54** [comment]
No that is not ideal. I wonder if changing this to a dark gray with opacity will make it show up against black background.

**Comment by roberthouse54** [comment]
Let's make this simple and just go back to the solid color we had before: 

![image](https://cloud.githubusercontent.com/assets/20047260/20772355/27e3621e-b71b-11e6-8d0e-60f2037c1adb.png)

**Comment by pdpinch** [comment]
@roberthouse54 is this still an issue?

**Comment by roberthouse54** [comment]
I think we should close it.
