### ISSUE TITLE
Use <section> element for grouping parts of page in Home and Program templates

### ISSUE THREAD

**Issue by singingwolfboy** [mitodl/micromasters#1917]
The HTML5 [`<section>`](http://mdn.beonex.com/en/HTML/Element/section.html) element is designed to semantically represent a generic section of a page. When combined with header elements (`<h1>` through `<h6>`), the `<section>` element makes it easier for a screen reader user to understand the general flow of a page and jump to the particular part of the page they are interested in.

For accessibility purposes, we should try to use semantically meaningful elements where possible, including replacing `<div>` with `<section>` in the templates where it makes sense to do so.

**Comment by pdpinch** [comment]
Do you have any particular templates in mind? 

Otherwise I don't know how we'll know when this issue can be closed.

**Comment by singingwolfboy** [comment]
The home page template and the program page template are excellent candidates to start with. @roberthouse54 requested that I make this issue while I was reviewing #1900.

**Comment by pdpinch** [comment]
We've been using the UX label to indicate that Rob needs to take some action on the issue. Do we actually need his input on this?

**Comment by Ferdi** [comment]
sounds good, I'm surprised we dont use sections already
