### ISSUE TITLE
Zendesk widget missing from program pages

### ISSUE THREAD

**Issue by singingwolfboy** [mitodl/micromasters#1923]
The Zendesk widget should show up on the program pages, but it is not currently present on https://micromasters-rc.herokuapp.com/scm/. This seems like a bug with the release: #1888.

**Comment by pdpinch** [comment]
Is this specific to SCM? 

Have there been any changes to the template?

**Comment by singingwolfboy** [comment]
No, I just used that URL as an example. It's missing from DEDP, as well. This isn't a template issue -- the Zendesk widget is loaded via Javascript, and it appears that the relevant Javascript file isn't being loaded.

**Comment by noisecapella** [comment]
I'm in the process of fixing it. Does the zendesk widget on the program page have a program selector anymore? I don't see it locally

**Comment by singingwolfboy** [comment]
@noisecapella: no, that was removed in #1882. The program selector should be hidden on any program page, and the name and email fields should be hidden if you are logged in.
