### ISSUE TITLE
Social sharing links aren't configured properly on financial aid review page

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1928]
This was a problem in 0.24.0 and I'm not going to attempt to fix it for #1925

**Comment by noisecapella** [comment]
@pdpinch Should we just get rid of them? I'm not sure why we have the social icons on that page

**Comment by pdpinch** [comment]
They're not supposed to be on that page. It's not supercritical to fix.

**Comment by pdpinch** [comment]
Can we just use the same footer on the financial aid review form as the one we use on the dashboard? The dashboard footer doesn't have any social sharing links.
