### ISSUE TITLE
Unexpected (and ugly) link encoding in Mailgun e-mail

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1938]
This happened in an e-mail from micromasters-rc. It needs to be tested on the production server. 

> You can pay for MicroMasters courses through the MITx MicroMasters portal (http://email.micromasters.mit.edu/c/eJxtjUsOhCAQBU8DS0I3H2XBQhdzD6TbQDJ-Inj_Ma4neatKpR7FlCnTIGtEDR5QozbaWqe8G7yC0cOocArGzcYLq7ear2NLrfPV1Fa7YrplibAAL4w6WQQgXleLhCNzsOGJBye_sfR-NmEmgZ9n_zoPptTKcqSL5BVPOuuei8C59Zt478P7_6o_B9441A). All coursework will be conducted on edx.org.

The URL does resolve to the expected address, https://micromasters.mit.edu/dashboard, which isn't functional yet.

**Comment by pdpinch** [comment]
I've confirmed this is happening in production too. Again, it works, but it's ugly:

> Dear MITx,
> 
> After reviewing your income documentation, the Data, Economics, and Development Policy MicroMasters team has determined that your personalized course price is $500.00.
>
> You can pay for MicroMasters courses through the MITx MicroMasters portal (http://email.micromasters.odl.mit.edu/c/eJxVjcsKwyAUBb8m7ir3FaMLF930P4zXkkBCilro5zeEbgpnNQdmNMoMKmaNBOiQCHGSAMHiNAW2DIEsMDhgR4PAvuZ67Kn1Ups9dLP72m3Rt1min8Wz8ykLlRJcZvCcEz7HEYskDWaLS--vNvB9oMe5P9fPc2JNbZmPVNXUeNLPrfQrfP1fzx41CQ). All coursework will be conducted on edx.org.
>
> Thank you,
> The Data, Economics, and Development Policy MicroMasters team

**Comment by pdpinch** [comment]
Maybe we should make an HTML mail template? @roberthouse54

**Comment by roberthouse54** [comment]
Yes, let's create a separate issue for designing a generic email template that we can use for this and other emails.

**Comment by Ferdi** [comment]
OK, bu why dont we fix the problem first , making the url be  https://micromasters.mit.edu/dashboard

**Comment by roberthouse54** [comment]
I agree about shortening the link. And Peter and I decided that an html email is a lower priority.

**Comment by pdpinch** [comment]
This should be addressed by the WYSIWYG editor implemented to address #2948

**Comment by aliceriot** [comment]
This is still happening with links in the HTML. mailgun automatically rewrites raw URLs in finds in plain-text emails and also the `href` attribute of any anchor tags in an HTML email - they do this to enable click tracking and so on. Reading through their documentation it looks like this is a setting that we can turn off, I just messaged Tobias about getting an invite for mailgun, once I do I'll turn the setting off and we can close this issue.

**Comment by aliceriot** [comment]
ok I turned the options off, so we should be good. I'm going to close this, if we have any further trouble we can reopen.

**Comment by pdpinch** [comment]
This is account-wide on Mailgun? So any future e-mail we send won't use re-written URLs?

**Comment by aliceriot** [comment]
yep! at least, assuming that I flipped the correct switch! haha.

**Comment by aliceriot** [comment]
If we wanted to use their click tracking feature in the future we could (I think) switch it on just for HTML emails in the API calls we make.
