### ISSUE TITLE
If selected enrolled program is deleted we should choose another to show instead of an error page

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1942]
To reproduce, enroll in a program and choose it in the program selector in your browser. Delete the program on the server (or mark it live=False) and refresh the page. It shows an error page, but it should instead change the selection to another program that the user is enrolled in

**Comment by noisecapella** [comment]
I'm having trouble reproducing this locally but I see it every so often on micromasters-rc

**Comment by pdpinch** [comment]
I think this just happened to @giocalitri

**Comment by giocalitri** [comment]
I can confirm I just saw it.

**Comment by noisecapella** [comment]
Are you able to reproduce it?

**Comment by giocalitri** [comment]
I am able to reproduce it on RC but not on my local environment
