### ISSUE TITLE
Token refresh for user ends up in uncaught exception

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#1945]
We should investigate and possible fix this.

The error is clear when the user is a made up user from seed_db.

see:
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/188568358/

**Comment by pdpinch** [comment]
fwiw, the user cdolivera is a real user. The account was created on prod with an edx.org account. When we copy that user down to -rc and -ci there is no corresponding user on their edX backends.

**Comment by pdpinch** [comment]
@giocalitri any thoughts on what might be an appropriate fix?

**Comment by giocalitri** [comment]
Maybe a generic exception handling.
I actually would like to understand why it is not working now.

On Dec 4, 2016, at 2:14 PM, Peter Pinch <notifications@github.com<mailto:notifications@github.com>> wrote:


@giocalitri<https://github.com/giocalitri> any thoughts on what might be an appropriate fix?

**Comment by pdpinch** [comment]
I assume it's happening because we have accounts in MicroMasters-ci that don't exist on microdmasters.d

**Comment by giocalitri** [comment]
That's true, but the code should not fail in that way, at least not in the celery task.

On Dec 4, 2016, at 3:17 PM, Peter Pinch <notifications@github.com<mailto:notifications@github.com>> wrote:

I assume it's happening because we have accounts in MicroMasters-ci that don't exist on microdmasters.d

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/189430044/

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/188568358/

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/182642956/

**Comment by giocalitri** [comment]
> https://sentry.io/mit-office-of-digital-learning/micromasters/issues/182642956/

This is different from the ones above: this might be caused by the user creating a brand new user and not verifying the user on edX.
Need to double check.

**Comment by giocalitri** [comment]
All the ones before might have different root causes as well: I am in the process to put out a PR to have more granular errors.

**Comment by pdpinch** [comment]
This particular error was resolved by #2047. There are some related errors, which have their own issues now.
