### ISSUE TITLE
Sign Up: note to clarify that legal name is required

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1955]
We expect users to use their real, legal name on the site. This is necessary for in-person proctored exams, and also for applying for the masters program. 

Add a brief message to the profile/personal form clarifying that given name and family name should be legal names, e.g. `Use your legal name, as it appears on your ID`

**Comment by pdpinch** [comment]
@roberthouse54 can you do a quick pass on a design for this?

**Comment by roberthouse54** [comment]
So just to clarify... we did decide that we are going to require the use of roman characters in the sign up? I assume that this is about the regular sign up pages.

**Comment by roberthouse54** [comment]
![image](https://cloud.githubusercontent.com/assets/20047260/20897797/d31e4f8e-baf1-11e6-966d-b7d2845d8901.png)

"Please fill out this form using your legal name and truthful information."

Create a new css variable for "text_highlight" which is background-color #fbf9db.
