### ISSUE TITLE
Database models have fields that aren't timezone-specific

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#1960]
We're still getting a load of django timezone warnings, particularly if we run something that heavily involves the database, eg: the `seed_db` command. A lot of these warnings are likely due to a misunderstanding of python `datetime`. `TimestampedModel` is inherited by a lot of our models, and it uses the following as its queryset:

```python
class TimestampedModelQuerySet(QuerySet):
    """
    Subclassed QuerySet for TimestampedModelManager
    """
    def update(self, **kwargs):
        """
        Automatically update updated_on timestamp when .update(). This is because .update()
        does not go through .save(), thus will not auto_now, because it happens on the
        database level without loading objects into memory.
        """
        if "updated_on" not in kwargs:
            kwargs["updated_on"] = datetime.datetime.utcnow()
        return super().update(**kwargs)
```

`datetime.datetime.utcnow()` does NOT yield a timezone-sensitive datetime. This should be changed to `datetime.datetime.now(pytz.utc)`, and all other examples in the codebase should be changed accordingly. This can be considered done when we can run `seed_db` with no timezone warnings

**Comment by noisecapella** [comment]
Good catch... this seems dangerous
