### ISSUE TITLE
Zendesk error when retrieving elements

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#1962]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/190233171/
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/190244172/

We should add code to do nothing if the expected DOM nodes don't exist

**Comment by noisecapella** [comment]
This still seems to be an issue:
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/190295329/

If the error were that the DOM node didn't exist, I think we would see a different error

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/190233171/

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/190295329/

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/190244172/

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/190401131/

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/190387884/
