### ISSUE TITLE
UnreadablePostError

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1971]
We think it may be due to overly large profile images. Some of them seem to be over 18MB. 

See https://sentry.io/share/issue/3130343439372e313930333037313735/ 

Also see NewRelic.

If we aren't checking the size of the image, we should. It should be kept to a reasonable limit.

**Comment by noisecapella** [comment]
It looks like we can pass a mime type to encode this as JPEG instead of PNG, which may save some space: http://stackoverflow.com/questions/27826213/canvas-toblob-saving-as-png-even-though-i-specified-jpg

**Comment by pdpinch** [comment]
I think #1972 will help and we should proceed with it, but we need some more robust in place that prevents uploads over the max size (which means we need to determine what the max size is). 

@noisecapella can you look into best practices here?

**Comment by aliceriot** [comment]
I'm working on limiting the uploaded filesize already. We can, as far as I can tell, limit the pixel dimensions of the images the user uploads. I am inclined to think a user will not need an image of more than 500x500 (we show only a tiny profile image after all).

**Comment by noisecapella** [comment]
I think 500x500 is too small. For example the Android launcher image can be 512x512 

I just tried uploading a photo taken on my phone and it freezes up for a minute, even before uploading the image. I wonder if there's somewhere we can downsize before we put it in the cropper

**Comment by aliceriot** [comment]
I think we can do that. what would you suggest as a good image size?

**Comment by Ferdi** [comment]
@aliceriot that could work but it's not ideal. User has to use a different app to resize the image. 

Can we resize the image ourselves ?

**Comment by aliceriot** [comment]
@Ferdi that's what I'm implementing

**Comment by noisecapella** [comment]
Maybe 1024x1024?

**Comment by aliceriot** [comment]
sounds good

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/190055463/

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/190307175/

**Comment by pdpinch** [comment]
After spending more time with this, it's more properly a timeout which can be caused by large files, but also can be caused by a slow network. 

The recommendation from Heroku is to upload directly to S3: ####

**Comment by blarghmatey** [comment]
The default socket timeout if it is not explicitly configured is 0 seconds. When digging through the source for uWSGI if the timeout is exceeded it just closes the socket and exits. If I set the timeout to 0 or 1 seconds I get the read timeout. If it's set higher (e.g. 30 seconds) it completes successfully under the same conditions.

The error we are seeing is coming from the `read` call in `wsgi.input`. `wsgi.input` is an instance of `LimitedStream` which is a class for wrapping an input stream. The input stream in question is the socket from the uWSGI application container.

**Comment by giocalitri** [comment]
we read the source code of the UWSGI project and
1- the setting is here https://github.com/unbit/uwsgi/blob/f262899bc5eb890007ba157d8b1da1e836049b74/core/uwsgi.c#L297
and by default is 0

2- one of the many places where it is used is
https://github.com/unbit/uwsgi/blob/c0d1e7655d913d720d4c5d0276f305eebdc4db15/core/fork_server.c#L81

3- and `uwsgi_read_nb` is defined here
https://github.com/unbit/uwsgi/blob/c0d1e7655d913d720d4c5d0276f305eebdc4db15/core/io.c#L969-L986

4- the definition of `uwsgi_waitfd` is 
https://github.com/unbit/uwsgi/blob/f262899bc5eb890007ba157d8b1da1e836049b74/uwsgi.h#L3316
and it is an partial application with a default event parameter for `uwsgi_waitfd_event`

5- `uwsgi_waitfd_event` is 
https://github.com/unbit/uwsgi/blob/c0d1e7655d913d720d4c5d0276f305eebdc4db15/core/io.c#L12-L40

The important part is:
https://github.com/unbit/uwsgi/blob/c0d1e7655d913d720d4c5d0276f305eebdc4db15/core/io.c#L24-L27

The default event parameter for the `wait_fd` function partial is `POLLIN` which is then passed to the `read` system call. The `POLLIN` event parameter tells the `read` call to block and wait for data to be available in the file descriptor. If the timeout is exceeded before the data becomes available then it will return with a failure condition at which point uWSGI will call an error function https://github.com/unbit/uwsgi/blob/c0d1e7655d913d720d4c5d0276f305eebdc4db15/core/io.c#L29-L31

**Comment by blarghmatey** [comment]
The way that we are able to simulate to replicate this error without the `socket-timeout` parameter being set in uWSGI is to simulate a slow network connection with high latency (use the GPRS network profile in the Chrome developer tools) and upload an image. The reason that we don't see this manifest for other requests is because for a majority of cases the Heroku router will buffer up to 1 MB but when there is chunked content (in this case the multi-part form upload) then the data is immediately streamed to the dyno. (https://devcenter.heroku.com/articles/http-routing#request-buffering)

Because the data is streamed to the dyno immediately, we then become subject to the 0 second socket timeout if the network being used is unable to maintain a constant stream of data to the socket.
