### ISSUE TITLE
Layout issue on the User Page, with avatar and name (Safari)

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#1982]
![image](https://cloud.githubusercontent.com/assets/20047260/20903101/134ada94-bb08-11e6-984f-067d093b1f38.png)

There is a layout bug here, where the avatar is on top of the name. Also, the "Edit Photo" icon is supposed to be on the right, and it is on the left. I think this is a problem with how flexbox is layed out.

**Comment by Ferdi** [comment]
Can you give some more details . Your previous screenshots looked good https://github.com/mitodl/micromasters/pull/1981

**Comment by roberthouse54** [comment]
#1981 fixed a layout issue with the "About Me" copy, and this issue is a different layout problem, that I am only seeing in Safari, but might be happening in other browsers. This one is about the user image overlapping the user name.

**Comment by singingwolfboy** [comment]
I can't reproduce this issue on production. Tested with Safari 10, on macOS Sierra.
![cant-reproduce-layout-issue](https://cloud.githubusercontent.com/assets/132355/21596572/80390fa8-d102-11e6-8dc1-5a6a7bed3262.png)

**Comment by roberthouse54** [comment]
Hmm. Ok, I am still seeing this, but I am on Safari 9.1.2

![image](https://cloud.githubusercontent.com/assets/20047260/21618226/e0511132-d1b7-11e6-922a-0477503f9862.png)

**Comment by pdpinch** [comment]
FWIW, 14% of MicroMasters users are using Safari. Of those, 23% user a version before version 10. So this CSS bug is affecting about 3% of users.

**Comment by roberthouse54** [comment]
Actually the layout seems to work both on the Profile page, and the dashboard... but it is not working on the "Learner" page. It seems that all three pages have slightly different layout (see screen shots below). I think if we use the same layout for all three, it should fix this.

Profile page:
![image](https://cloud.githubusercontent.com/assets/20047260/22216195/16622e14-e16c-11e6-80d3-ca78369e6d8f.png)

Dashboard:
![image](https://cloud.githubusercontent.com/assets/20047260/22216233/3fb325d4-e16c-11e6-84dc-b16857937a8e.png)

Learner page:
![image](https://cloud.githubusercontent.com/assets/20047260/22216209/24de49d2-e16c-11e6-8774-12089cf87e64.png)
