### ISSUE TITLE
Course grade histogram overlaps site footer with short window

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#1987]
<img width="779" alt="ss 2016-12-05 at 20 22 48" src="https://cloud.githubusercontent.com/assets/14932219/20909580/9590fcb4-bb2a-11e6-93a2-67181f8a0602.png">

**Comment by pdpinch** [comment]
duplicate of #1948

**Comment by singingwolfboy** [comment]
#2046 fixes this issue.
