### ISSUE TITLE
Part of the course facet sidebar can't be seen with short window

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#1988]
<img width="542" alt="ss 2016-12-05 at 20 38 46" src="https://cloud.githubusercontent.com/assets/14932219/20909633/df057a3c-bb2a-11e6-871b-90554cbc66ff.png">

The top of the sidebar is anchored to the top of the page. If the window is too short, it's impossible to see the whole sidebar

**Comment by singingwolfboy** [comment]
#2046 resolves this issue.

**Comment by pdpinch** [comment]
Looking good to me in  production now.
