### ISSUE TITLE
Refactor dashboard API

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#201]

**Comment by pdpinch** [comment]
What did you have in mind for this?

**Comment by noisecapella** [comment]
I think at this point we just need to have a way to group courses into programs in the rest API, and update the UI accordingly

**Comment by pdpinch** [comment]
@giocalitri @noisecapella I believe this was address with https://github.com/mitodl/micromasters/pull/245 

If I'm wrong, feel free to re-open but we need more details in the description.
