### ISSUE TITLE
Profile upload spinner

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2019]
We should add a spinner somewhere while the profile image uploads

**Comment by roberthouse54** [comment]
OK, here is a proposed solution:

1. Display a spinner in the modal while the image is loading in the browser.
2. Display another spinner and the text "Loading..." on a transparent overlay over the image after the user has clicked Save, and the image is being sent to the server.

See mocks below:

![spinner](https://cloud.githubusercontent.com/assets/20047260/20981294/104029fa-bc82-11e6-9725-50bcd0f1632a.png)

**Comment by Ferdi** [comment]
A percentage based progress would be more useful if it's possible.

**Comment by roberthouse54** [comment]
![spinner](https://cloud.githubusercontent.com/assets/20047260/20981748/d535379a-bc83-11e6-9b82-dde666975ca4.png)

**Comment by noisecapella** [comment]
We will need to replace the `fetch()` with `XMLHttpRequest` to give us access to the completion percent. That's not a huge amount of work, just an extra complication

**Comment by roberthouse54** [comment]
I updated the mock in the comment above. If the percentage is too much of a hassle, I think we can live without it.

**Comment by aliceriot** [comment]
Oops, meant to close this in #2039
