### ISSUE TITLE
Error message shown occasionally during page load for /dashboard and /learners

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2027]
I think I filed an issue for this before and fixed it, maybe #1717? Anyway I'm still seeing this behavior. I'm not able to reproduce it consistently

**Comment by pdpinch** [comment]
I see it as well. Most often when loading learners, and I think it's when I'm starting from a stale session.

**Comment by noisecapella** [comment]
I can reproduce this consistently on the learner page when there is no currently selected program in `localStorage`. I also managed to get a screenshot:

![screenshot from 2017-03-01 13-45-55](https://cloud.githubusercontent.com/assets/863262/23475630/2f6e70a2-fe86-11e6-97a8-ff384b014827.png)
