### ISSUE TITLE
Search: decrease the default number of facet hits for "Country of Birth"

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2038]
The learner search is getting crazy for DEDP. We need to default to seeing fewer facets and give the user an option to "view more" (ask @roberthouse54 how many is a good number)

Not like this:

<img width="177" alt="screenshot 2016-12-08 11 00 42" src="https://cloud.githubusercontent.com/assets/430126/21016978/b6da7b04-bd35-11e6-8da0-65eff59acd61.png">

More like this (see 
http://demo.searchkit.co/imdb):

<img width="265" alt="screenshot 2016-12-08 10 58 23" src="https://cloud.githubusercontent.com/assets/430126/21016910/6f33ccf6-bd35-11e6-9ba0-6a515f676469.png">

**Comment by roberthouse54** [comment]
Let's try 15

**Comment by aliceriot** [comment]
@pdpinch is the 'Country of Birth' field the only one we need to adjust?

**Comment by pdpinch** [comment]
With the current set of facets, both 'Country of Birth' and 'Current Residence' have this problem. 

Since they are different types of facets, I don't know if the same solution will work for both. 

@roberthouse54

**Comment by aliceriot** [comment]
It's very simple to limit the number of entries shown for 'Country of Birth' but unfortunately it doesn't look like 'Current Residence' has a built in mechanism for doing that (supplied by searchkit, I mean).

**Comment by aliceriot** [comment]
An easy option might be using something like this instead: https://github.com/GregoryPotdevin/searchkit-multiselect

**Comment by aliceriot** [comment]
For the `Country of Birth` facet (which is a `<RefinementListFilter />`) it is really trivial to limit the number of options shown - we can just pass a `size` prop which automatically takes care of showing and hiding the excess entries.

The difficulty is the `<HierarchicalMenuFilter />` component, which we use to implement the `Current Residence` filter. This does not have a built-in mechanism for limiting the number of entries initially shown. I have tried a few hacks but haven't gotten anything to work yet.

I've also asked the searchkit developers if they have any insight, but haven't heard anything yet.

**Comment by pdpinch** [comment]
That's frustrating. 

Let's fix the easy case for now, while we decide what to do about the harder case.

**Comment by aliceriot** [comment]
Sure

**Comment by pdpinch** [comment]
Closing this issue and opening a new one for just "Current Residence" facet.
