### ISSUE TITLE
Student ID for external usage

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#2043]
This issue is to facilitate some discussion and implementation around the IDs we generate for the sake of identifying students to Pearson for #1796. We need an ID value we are comfortable sharing to Pearson as well as exposing to the browser for the sake of SSO. I've expressed concerns previously about sequential values being easily guessed. Note that our transactions to Pearson are over either SFTP or HTTPS (in the case of SSO).

It seems we have two options: a) reuse our current `Profile.student_id` somehow or b) implement a different field, probably a random UUID.

To explore option a) a bit we could it pass through as-is or try to obfuscate it.

To obfuscate, we could use this: http://hashids.org/ These will be decodable by us on any return trips. My thought here is to only obfuscate the value and not try to shoehorn more security into the authentication mechanism provided by the third party.

For b) it would require adding another column plus an index (for reverse lookup).

**Comment by gsidebo** [comment]
are there any drawbacks to adding an auto-gen UUID field to `Profile`? seems straightforward enough if our major concern is sequential ids that people can easily guess. if we think it's a little heavyweight to add a new column just for the benefit of Pearson, i would recommend that we do the obfuscation in the back end

**Comment by rhysyngsun** [comment]
@gsidebo Ferdi and Peter were inclined towards reusing the student id if we can. The downside to adding the UUID is it would also necessitate adding an index on it, I just updated my original description to note that.

**Comment by gsidebo** [comment]
fyi: https://github.com/davidaurelio/hashids-python

**Comment by giocalitri** [comment]
I think I need a bit of context: why having the student ID in clear is a problem? Will the students be allowed to do anything just providing the ID number without any other form of authentication?

**Comment by rhysyngsun** [comment]
@giocalitri My original concern was that the SSO mechanism to Pearson uses a sha256 of 6 values. 5 of those values and the hash itself will be sent to the browser. The 6th value is a shared secret between us and Pearson which they require us to periodically rotate. My concern was that if the secret is determined ( brute forced) it would be easy to forge SSO requests for other users if the values are sequential and easily guessed.

After sleeping on it I'm not convinced that hashids are worth it because if someone has put in the effort to brute force the secret, breaking the hashid encoding is far more trivial (it's only obfuscation).

So it comes down to either we're concerned about the brute forcing to determine the secret and should use an identifier that's not easily guessed to reduce impact or we feel the authentication is acceptable and just stick with the plaintext student id.

**Comment by giocalitri** [comment]
wait: what could be the technique to brute force the secret? How long is the secret? How often do we plan to rotate it? where are we going to store it? (still trying to understand the context)

**Comment by rhysyngsun** [comment]
Peter just stopped by and mentioned he may have overemphasized how much we wanted to reuse the student id, he said a random UUID is fine by him.

**Comment by giocalitri** [comment]
I do not think it matters if we use the UUID or the student_id from the security point of view.
I think that from debugging purposes, maybe the student_id is better (but not strong opinions on this).

The crucial part is the `passPhrase`: I think we need a better way to store these kind of things and I disagree with the statement in the documentation: it must not be kept in the database (at least not in the MicroMasters app database).

**Comment by rhysyngsun** [comment]
@giocalitri agree with you on the `passPhrase` storage. I think the language here is a little dated - I believe their main point is not to hardcode the value into your application rather than a specific dictation to store in the DB. It can be stored in the same place as our other credential values that get pulled into settings.

I'm also fine at this point with student_id. I finally found a site that ballparks the computation time to brute force it and assuming a secret at least 10 chars long (I hope for longer) with mixed case, numbers, and symbols it'd take thousands of years of cpu-time to compute. That's fine by me.
