### ISSUE TITLE
Search: add a search box to find a specific user

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2050]
It would be helpful for me debugging support issues if I can search on profiles in the admin

**Comment by pdpinch** [comment]
@roberthouse54 is there a design for this?

**Comment by roberthouse54** [comment]
I have updated the learner search mock here: https://invis.io/CGA3MU4AX

![image](https://cloud.githubusercontent.com/assets/20047260/22110327/5252c4d8-de29-11e6-9c4d-0895e157b6f9.png)

**Comment by pdpinch** [comment]
If you're OK with the acceptance criteria I think we can move this into Ready (at the bottom).

**Comment by roberthouse54** [comment]
What are the acceptance criteria?

**Comment by roberthouse54** [comment]
Updated this agin: https://invis.io/KSA4IEBWF

**Comment by pdpinch** [comment]
What happens when the user clicks on a name in the drop-down? Does the browser load that user's profile, or does the result set update to only display that one user? Or something else?

**Comment by roberthouse54** [comment]
It should only display that one user in the search result.

**Comment by roberthouse54** [comment]
OK, I am updating this again, so please ignore the mock posted above. We are going to go with the out of the box searchkit implementation of this. As the user types, the results are filtered in real time. We will highlight the typed letters in the search results. I do not think we need an "x" icon to clear the search term. I think we will want to consider whether we want to display matches to strings that are inside a word, but not necessarily at the beginning of the word. Like for example "zabet" would match "Elizabeth". My gut feeling is that we should not do this, and we should just match the beginning of the name, either first or last name. See mock below:

![image](https://cloud.githubusercontent.com/assets/20047260/22223783/1cd5ee02-e18a-11e6-81d4-b054c132cde8.png)

**Comment by roberthouse54** [comment]
Note that this design will also require that we replace the "Sort by" dropdown with the sorting by clicking on column headers, as shown.
