### ISSUE TITLE
Financial Aid: warn users not to e-mail income statements

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2052]
We have some users e-mailing their income statements despite the instructions to use fax or post. The support team would appreciate an warning to users NOT to do this, probably on the income verification dialog.

**Comment by pdpinch** [comment]
I think this is the card that needs the warning:

<img width="584" alt="screenshot 2016-12-09 16 45 50" src="https://cloud.githubusercontent.com/assets/430126/21065576/0a411cc2-be2f-11e6-9fdf-1eea1506d825.png">

**Comment by roberthouse54** [comment]
After the sentence "Please mail or fax..." etc Add another sentence. "DO NOT SEND BY EMAIL." (all caps)
