### ISSUE TITLE
Fix indentation for search facets

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#2054]
@roberthouse54 noticed that the left indent for some of our facet options is too much.

![ss 2016-12-09 at 10 46 54](https://cloud.githubusercontent.com/assets/14932219/21054751/dfbf2aca-bdfc-11e6-8556-ce00dc0055d3.png)

**Comment by roberthouse54** [comment]
Lets align all the facets on the left with the facet headers, including the checkboxes. Also, while we are at it, can we move up the arrows a few pixels to they are better aligned with the facet headers. (See below) 

![image](https://cloud.githubusercontent.com/assets/20047260/21055060/f7249406-bdfd-11e6-9f31-2706cfd190ae.png)

**Comment by gsidebo** [comment]
OK, i think i can knock this out pretty quickly. i'll take it on now
