### ISSUE TITLE
Course facet disappears (but leaves expand arrow) when no enrollments exist in search results

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#2062]
Under any condition that leaves no course enrollments in the search results, the facet title and body disappear, and the visibility toggle still remains

![ss 2016-12-09 at 15 30 19](https://cloud.githubusercontent.com/assets/14932219/21063645/b684617a-be24-11e6-973f-67ea592151fd.png)

**Comment by pdpinch** [comment]
I don't think this requires input from Rob. I'm removing the UX label.
