### ISSUE TITLE
Search: don't index users who aren't active

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2070]
We've had a few users ask to have their accounts deleted (#2018). We can easily make their accounts inactive, but they still appear in search. 

I think we can achieve this by only indexing profiles for users who are active.

**Comment by amir-qayyum-khan** [comment]
is ok to add signal that removes index when profile update? or filter out user in query?

**Comment by gsidebo** [comment]
I would definitely go with filtering out those users in the query. We can add a default filter in the back end. There will be a very small minority of users that ask to have their accounts deleted, so the extra data hanging around will definitely not be an issue.

**Comment by gsidebo** [comment]
We just chatted on Slack and I reviewed the doc for user account deactivation. It looks like we are already planning to delete `ProgramEnrollment`s for users that have their accounts deactivated. There's already a signal that removes `ProgramEnrollment`s from the index when they're deleted from the database, so we shouldn't need any extra logic to remove users from the ES index

**Comment by pdpinch** [comment]
Sorry @amir-qayyum-khan it looks like we don't actually need to do this. Our process for removing users includes deleting their program enrollments, which has the desired effect of removing them from elasticsearch.
