### ISSUE TITLE
Don't update edx cache for users who aren't active

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2071]
We've had a few users ask to have their accounts deleted (#2018). We can easily make their accounts inactive, but that won't stop their edx enrollments and grades from getting updated. 

I think we can achieve this by only updating the cache for users who are active.

**Comment by giocalitri** [comment]
Also this one is part of a more general issue about having the possibility to flag an user to not update her cache.

**Comment by pdpinch** [comment]
Closed by #3191
