### ISSUE TITLE
TypeError: Cannot read property 'getCroppedCanvas' of undefined

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2096]
Alice, can you take a quick look at this to triage it? Is it serious enough to fix? Is it obvious enough that we think we'll be successful?

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/192140142/

```
TypeError: Cannot read property 'getCroppedCanvas' of undefined
  at apply (./static/js/components/CropperWrapper.js:19:33)
...
(1 additional frame(s) were not displayed)
```

**Comment by aliceriot** [comment]
I'm able to repro it locally. it does not block uploading an image, it's just noisy. Not exactly sure why it's happening.

**Comment by pdpinch** [comment]
Thanks for checking. We can ignore it for now.
