### ISSUE TITLE
TypeError: r.refs.cropper is undefined

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2097]
Alice, can you take a quick look at this to triage it?

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/193037892/

```
TypeError: r.refs.cropper is undefined
  at originalHandler (./static/js/components/CropperWrapper.js:17:15)
...
(1 additional frame(s) were not displayed)
```

**Comment by aliceriot** [comment]
pretty sure this is a dupe of #2096

**Comment by aliceriot** [comment]
yeah, one is one FF, this one is Edge. browsers often will spit out different error messages for the same problem. closing.
