### ISSUE TITLE
Don't attempt to update edX cache for users who are inactive

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2099]
We get the following error every time we run a batch update:

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/193071074/

```
DoesNotExist: UserSocialAuth matching query does not exist.
  File "dashboard/tasks.py", line 111, in batch_update_user_data_subtasks
    UserSocialAuth.objects.get(user=user)
  File "django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 385, in get
    self.model._meta.object_name
```

The user in question does not have active set to `true` so I think we can just skip any updates when `user.active = false`

**Comment by amir-qayyum-khan** [comment]
@pdpinch  So should we add a django command which make user active=False if user does not have python social auth object?

**Comment by pdpinch** [comment]
Honestly, I'm not sure what the solution is here. We don't have a safe, recommended way to remove users. See #2018, #2070 and #2071.

**Comment by amir-qayyum-khan** [comment]
i think i should integrate is_active in this part of solution. Only active users can access app.

**Comment by pdpinch** [comment]
This is now happening for a few users in production but, recognizing the names, I think they are users who created their accounts before our official launch and are unlikely to return.
