### ISSUE TITLE
Financial Aid: Allow course team to reset students in financial aid review form

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2117]
To reset learners' financial aid status currently, we use the django admin. We'd like to expose this functionality via the financial aid review form (i.e. /financial_aid/review)

### Acceptance criteria:

- [x] For each state in the financial aid review form, add a "reset" button 
- [x] when clicked, display a confirmation dialog for the staff user, because this is not undoable
- [x] after confirmation, update the state of the learner's financial aid submission and reload the review form (the user who has been reset should disappear from the current list)

### questions:

- [x] Do we need to capture a justification for the reset? I don't think so. The audit table already captures who made the reset. 
- [x] Should we send an e-mail at the same time? That would save the staff from going into ZenDesk, although they'll have to close the ticket anyway

**Comment by pdpinch** [comment]
Confirm that the justification is unnecessary. If we ever want to know why users requested resets, that's available in ZenDesk.

**Comment by pdpinch** [comment]
The ideal solution for contacting the user would be to give the staff a way to execute a ZenDesk macro that replies to the user and closes the ticket at the same time they reset the user. Since that's out of scope, we'll stick with the manual process of replying to the user for now.

**Comment by amir-qayyum-khan** [comment]
@rhysyngsun 

- here i have to display list of users with fa state, reset button.
