### ISSUE TITLE
Expand 'alter data' commands to work with non-FA programs

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#2121]
Our 'alter data' commands (seed_data/management/commands/alter_data.py) give us the ability to make fine-grained changes in a user's enrollments/grades. This helps us manually test the app, especially in non-local environments. To ease the development effort, these commands were designed to work only with non-FA programs. At some point we should change this to support FA programs. 

This might also be a good opportunity to centralize the logic for creating enrollment/grade data for FA and non-FA programs. That logic is currently repeated several times over in our tests.

**Comment by pdpinch** [comment]
@gsidebo is this still an issue?

**Comment by gsidebo** [comment]
@pdpinch it is if we want it to be. if you/others want to be able to use `alter_data` with non-FA programs, then this issue is still needed

**Comment by pdpinch** [comment]
we met with SCM today to talk about how the dashboard should handle their comprehensive exam (so-called CFx). We'll need this I think in order to develop and test any work we do for them.

**Comment by pdpinch** [comment]
This also needs to be updated to work with final grades
