### ISSUE TITLE
Add Program Name to the top of the dashboard page

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2123]
Currently, there is no indication which program you are looking at on the dashboard page. We should add the program name to the top of the page to make this clear.

![image](https://cloud.githubusercontent.com/assets/20047260/21195470/e960f6d6-c201-11e6-9122-863f124a1683.png)

**Comment by pdpinch** [comment]
@roberthouse54 is this a duplicate?

**Comment by roberthouse54** [comment]
Yes. I will close.
