### ISSUE TITLE
Search: Fix spacing between facet options on search page

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2124]
Some of the Course names are longer than we suspected, and they look confusing given that there is little difference between the line height of options, and the margin between options.

Please add a line height 1.3 to options in the course facet, and a margin-bottom of 8px under each option.

**Comment by singingwolfboy** [comment]
How do I get the course facet to show up on the search page?

**Comment by roberthouse54** [comment]
You probably need admin access(?) @pdpinch @gsidebo
