### ISSUE TITLE
fake and/or test users on ci and rc generate OAuth errors

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2131]
This appears to be limited to ci and rc servers and is not a critical issue, other than polluting our logs. 

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/193148559/

```
AttributeError: Due to a lack of support for Client Credentials Grant in edX, you must specify the access token.
  File "dashboard/tasks.py", line 130, in batch_update_user_data_subtasks
    edx_client = EdxApi(user_social.extra_data, settings.EDXORG_BASE_URL)
  File "edx_api/client.py", line 20, in __init__
    "Due to a lack of support for Client Credentials Grant in edX,"

Unable to create an edX client object for student fake.peyton.butler
```

**Comment by pdpinch** [comment]
I believe this is the same issue:

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/193437349/

**Comment by giocalitri** [comment]
We should probably work on stopping the celery refresh of the cache for users who fail X consecutive times in the celery tasks.

**Comment by pdpinch** [comment]
@giocalitri this hasn't happened (on rc) for the past couple of days. Did you change something?

**Comment by giocalitri** [comment]
No, I did not change anything

**Comment by pdpinch** [comment]
Is this in progress? If so, please move it on ZenDesk.

**Comment by annagav** [comment]
I talked to @giocalitri and we decided that adding a field to `Profile` to indicate that a user is fake, is good solution for this problem.
