### ISSUE TITLE
Profile: replace country/state/city fields with address field

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2135]
Part of #1796 and #1821 

Currently we collect Country of Residence, State, and City. We will replace this with one field labelled “Current Address”. This field will have hint text “Ex. 100 Main Street, Anytown, 01234, United States of America”. This field will use the Google Places API, which basically allows the user to type their address, then select it from an autocomplete. It will accept the text entry and display results in UTF-8 character set, but on the back end will submit the Street Address, City, Region/State, Postal Code and Country in CP-1252 (provided by the Google Places API.

![image](https://cloud.githubusercontent.com/assets/430126/21227532/7c671d6a-c2a8-11e6-8ee4-8d9ef510cf02.png)

### Acceptance criteria

- [ ] Must work in both initial profile creation (/profile/personal) and in profile editing (/learner)
- [ ] Populates the following fields on `Profile`: `address1`, `city`, `state_or_territory`, `postal_code`, `country`.
  - Optionally, since each address line is limited to 40 characters, `address2` and `address3` are available for overflow.

**Comment by rhysyngsun** [comment]
A few tips based on my research:

- Specify to the Google API that we want output in English.
- Specify that the API returns a precise address (https://developers.google.com/places/web-service/autocomplete#place_types)

**Comment by noisecapella** [comment]
We should have some language telling the user what we're using the address for, and we also need to tell them which parts of their address we're sharing in their public profile

**Comment by pdpinch** [comment]
@singingwolfboy this is In Progress now, right? I'll move it.

**Comment by pdpinch** [comment]
Pricing details are at https://developers.google.com/maps/pricing-and-plans/

Since registration is free for the portal, I believe we fall under the Standard plan. If we start restricting access based on payment (as opposed to enrollment) then that could change. 

For production, we'll getan API key tied to a credit card so we can go over the rate limits if/when necessary.
