### ISSUE TITLE
Some programs require courses to be taken in order

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#214]
As a micromasters student, I need to understand when courses must be taken in the proscribed order. 

In practice, there are plenty of users who have taken the courses out of order. And some programs will allow this (although not SCM). However, when a student hasn't taken the per-requisite courses, we should direct her to enrolling in the first eligible course.

**Comment by pdpinch** [comment]
@Ferdi I don't think this is an MVP requirement, especially given that edX doesn't enforce prerequisites. Let me know if I'm wrong.

**Comment by Ferdi** [comment]
I think the idea is to force it in the MM portal since edx doesn't do it.

**Comment by pdpinch** [comment]
There are no plans to require this for any future MicroMasters. We can reopen if/when that changes.
