### ISSUE TITLE
Spinners appearing in two places on some buttons

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2140]
Specifically:
 - if one pay now button is clicked, all pay now buttons have the spinner while it is loading
 - if an education or employment entry is deleted, the spinner appears on the save button of the profile as well

**Comment by aliceriot** [comment]
An idea for implementing a solution:

- every button generates a UUID at runtime
- when a button is clicked it dispatches an action to the store (`setSpinnerButtonID`) with that UUID
- every button receives a prop with the currently 'active' UUIDs
- if a button's own UUID is present in the store it will show the spinner, else it will remain a normal button
- when the request finishes up a the button will dispatch an action to remove it's UUID from the active pool

This could also be extended to have a notion of classes of buttons - for instance, we may want to disable a set of buttons when one is clicked, even if only one is actually in-flight (and therefore showing a spinner) at a time. That sort of thing might apply on the dashboard, for instance.
