### ISSUE TITLE
Better handling of the session expiration

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#2141]
Currently if the front-end has an expired session cookie, the single page cannot make requests to the MM backend any more and gets 403 responses: the solution is to refresh the page.

We should investigate 

1. increase the expiration timeout
2. force a page refresh in case the session cookie has expired

**Comment by Ferdi** [comment]
@giocalitri is this still a problem ?

**Comment by giocalitri** [comment]
I found it 4 days ago, so I think so. 
It's an edge case and unlikely to happen in production, so maybe low priority.

**Comment by Ferdi** [comment]
great, thx

**Comment by pdpinch** [comment]
I don't think anyone has seen this since Giovanni left.
