### ISSUE TITLE
Add a public/private option to the user profile

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#215]
As a micromasters student, I want to be able to control who can see my profile information. In particular, I may want to share my professional experience with MIT, but I may not want my employer to know that I'm seeking further education. 

Add a field to the profile form. We might as well follow the same format as edX, i.e. 

"Micromasters learners can see my: " ("public to the world", "public to other micromasters students" "private")

We will share private profiles with MIT faculty. We will share "public to other micromasters students" only to logged in users. "public to the world" will be shared with all. 

Default to private. 

Until we have views that show other learners, this won't have any impact, but we need to collect the data at registration. 

Because this is relevant to whole profile, it needs to be a final step, i.e. "Profile Privacy"

**Comment by noisecapella** [comment]
Currently we use the edX account_privacy option as a default, we should make sure to remove this piece of code in `pipeline_api.py`

**Comment by annagav** [comment]
@pdpinch Is this going to be another tab in the profile page (the forth one)?

**Comment by pdpinch** [comment]
Yes. It's in the mockups now. I'll shoot you a url when I get a chance.
