### ISSUE TITLE
Typo in no hits copy

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2151]
![screenshot from 2016-12-16 15-21-07](https://cloud.githubusercontent.com/assets/863262/21277239/50df4eaa-c3a3-11e6-93db-f2f039e8e6e7.png)

This typo is located in searchkit so we'll have to replace that component with our own

**Comment by singingwolfboy** [comment]
Just made a pull request upstream: https://github.com/searchkit/searchkit/pull/362

Also, Searchkit uses a translations system, so we don't need to write our own component, we can simply provide our own (correctly spelled) English translation.

**Comment by pdpinch** [comment]
This has been fixed upstream. Are we running the change in production yet?

@singingwolfboy @noisecapella

**Comment by noisecapella** [comment]
No, it's present in the 1.0.0-7 beta release. Should we upgrade now? cc @aliceriot

**Comment by aliceriot** [comment]
yeah let's go for it. I tried out I think the 1.0.0-4 beta release and all of our tests were working fine, so I don't think it will be terribly complicated.
