### ISSUE TITLE
ecommerce: add MITx MicroMasters logo and styling to Cybersource pages

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2156]
Cybersource supports a logo and a limited amount of styling for the checkout pages. It would make users more confident in the checkout process, and less likely to abandon their cart, if they saw MIT branding on these pages. 

The logo is a 840x60 (or smaller) pixel image, in jpg or png format. 

Here's a screenshot from the Cybersource business center where you can see the style settings that can be changed. 

![screenshot-ebctest cybersource com-2016-12-18-14-51-42](https://cloud.githubusercontent.com/assets/430126/21299708/387d7f6a-c56c-11e6-859f-43de1ff48c42.png)

**Comment by roberthouse54** [comment]
Can I do this myself, if I have access to the cybersource admin? @noisecapella @pdpinch

**Comment by pdpinch** [comment]
Sure, but how much do you want to tweak this?

**Comment by roberthouse54** [comment]
Header Color: #b1233b
Main body background: #f2f2f2
text color: #444444
Progress bar bgcolor: #b1233b

**Comment by pdpinch** [comment]
How's this look (from https://testsecureacceptance.cybersource.com/billing)

![screenshot-testsecureacceptance cybersource com-2016-12-19-22-03-19](https://cloud.githubusercontent.com/assets/430126/21336948/1053609c-c637-11e6-8739-4f83a323278a.png)

**Comment by pdpinch** [comment]
Now with smaller logo and blue background for "Total Amount"

![screenshot-testsecureacceptance cybersource com-2016-12-21-11-48-41](https://cloud.githubusercontent.com/assets/430126/21397958/afbf561c-c773-11e6-8c23-fc6dcbe76600.png)

**Comment by roberthouse54** [comment]
That looks better to me.

**Comment by pdpinch** [comment]
Ok. I'll roll it out to the production CyberSource business center and close the ticket when it's done. 

FYI @noisecapella

**Comment by pdpinch** [comment]
Ok. The update is done. Here's are some screenshots of what production looks like. 

1. Choose Credit/Debit or PayPal: 
![screenshot-secureacceptance cybersource com-2016-12-21-12-23-47](https://cloud.githubusercontent.com/assets/430126/21399419/84c8895a-c779-11e6-963f-5c94ce9e1fc2.png)

2a. Credit Card form: 
![screenshot-secureacceptance cybersource com-2016-12-21-12-24-24](https://cloud.githubusercontent.com/assets/430126/21399424/8e358452-c779-11e6-9a0a-c498ba8db8c6.png)


2b. PayPal form: 
![screenshot-www paypal com-2016-12-21-12-25-00](https://cloud.githubusercontent.com/assets/430126/21399427/912bd026-c779-11e6-8a8c-f3786a3cb0d4.png)
