### ISSUE TITLE
Search: move average grade facet above country of birth

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2157]
Since country of residence is such a large facet, we should move it to the bottom of the list.

**Comment by aliceriot** [comment]
to clarify, do you want the order to be:

- Course
- Country of Birth
- Average Grade
- Country of Residence

The issue title has 'country of birth' but the description just mentions country of residence.

**Comment by gsidebo** [comment]
if i were using the app, i don't think i would want the country facets to be separated, and my impression is that the 'Country of Residence' facet will be used much more often than the avg. grade facet. i could be wrong about both of those, though...

**Comment by roberthouse54** [comment]
I agree that it makes sense to group similar facets next to each other. We should collapse these Country facets by default.

**Comment by aliceriot** [comment]
for technical reasons it's infeasible to collapse the country of residence facet. see: https://github.com/mitodl/micromasters/issues/2038

given that we can't easily collapse it what order should the facets be in?

**Comment by roberthouse54** [comment]
I didn't mean collapse as in showing a "View More", I mean it should not be open by default.

**Comment by aliceriot** [comment]
Ah gotcha, that would be pretty easy to do. Should I change the order as well, or leave it as-is?

**Comment by Ferdi** [comment]
@aliceriot  can you do the following order ?

Course
nr of courses
Average Grade
Country of Birth
Country of Residence

**Comment by aliceriot** [comment]
sure!

**Comment by pdpinch** [comment]
@aliceriot what's the status of this?

**Comment by aliceriot** [comment]
OK so I've been looking into this again, and I'm seeing a really strange bug where putting the filter components (in `LearnerSearch.js`) into different orders throws an error. It seems like some orders are ok (including, obviously, the one on master) sooo idk what's going on.

@gsidebo have you ever seen something like that happen? I'm wondering if it has something to do with my environment but not sure what it would be! haha.

**Comment by aliceriot** [comment]
(asking because the issue seems to be in the `getChildFacetDocCount` on `FilterVisibilityToggle`, which git blame tells me you implemented)
