### ISSUE TITLE
Allow user to view & edit profile

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#216]
As a micromasters student, I'd like to be able to view my profile in one page, with the ability to edit it. 

The user can view at /users/{username}, and editing will return to the profile form at /profile/{username} with the proper tab open. 

Modeled after aboutme.google.com. 

Current draft of the design at https://invis.io/4E791TKU3#/157446163_Public_Profile

**Comment by pdpinch** [comment]
double check the url structure

**Comment by noisecapella** [comment]
Is this necessary for the MVP?

**Comment by pdpinch** [comment]
@noisecapella yes. 

The expectation is that this is the same API as the first profile. And the hope is that we can reuse the react components for education and employment.

**Comment by noisecapella** [comment]
I'm going to submit a PR to put this in place (currently non-functional), then we can figure out what we want in more detail

![screenshot from 2016-05-19 14-31-39](https://cloud.githubusercontent.com/assets/863262/15405110/90713a36-1dce-11e6-9d10-44b2a52db9c9.png)

**Comment by Ferdi** [comment]
@noisecapella that looks pretty good !

**Comment by pdpinch** [comment]
I'm changing this to its own epic.
