### ISSUE TITLE
Move ZenDesk javascript to load at bottom of page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2162]

**Comment by aliceriot** [comment]
I've tried this out and I don't see a noticeable decrease in page load time.

@noisecapella @giocalitri thoughts?

**Comment by noisecapella** [comment]
I'm not sure it would make much of a difference. The `zendesk_widget.js` code just seems to create the iframe and create some handlers. There's not much there that's blocking anything so it wouldn't matter if it was in the header or the footer

Also are you looking at one of the program pages? The home page doesn't have this code

**Comment by aliceriot** [comment]
I was using the dashboard for testing.

**Comment by giocalitri** [comment]
we should try the program marketing page.

In general the assumption was that the download of the zendesk JS was blocking on the `ready` of the page

**Comment by pdpinch** [comment]
@aliceriot this in progress, right? I'll move it.

**Comment by aliceriot** [comment]
@giocalitri looking through some profiles in Chrome I don't think that's the case anymore.

**Comment by aliceriot** [comment]
We can still move it to the bottom though!
