### ISSUE TITLE
Add celery setting to silence warning

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2171]
celery_1   | [2016-12-20 16:50:44,434: WARNING/MainProcess] /usr/local/lib/python3.5/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
    celery_1   | Starting from version 3.2 Celery will refuse to accept pickle by default.
    celery_1   | 
    celery_1   | The pickle serializer is a security concern as it may give attackers
    celery_1   | the ability to execute any command.  It's important to secure
    celery_1   | your broker from unauthorized access when using pickle, so we think
    celery_1   | that enabling pickle should require a deliberate action and not be
    celery_1   | the default choice.
    celery_1   | 
    celery_1   | If you depend on pickle then you should set a setting to disable this
    celery_1   | warning and to be sure that everything will continue working
    celery_1   | when you upgrade to Celery 3.2::
    celery_1   | 
    celery_1   |     CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']
    celery_1   | 
    celery_1   | You must only enable the serializers that you will actually use.
    celery_1   | 
    celery_1   | 
    celery_1   |   warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

**Comment by giocalitri** [comment]
Looking at [this](http://stackoverflow.com/questions/22889269/celery-will-refuse-to-accept-pickle-by-default-should-i-disable-it) we probably cannot use `'json'`, but we can still set it to `'pickle'`

**Comment by noisecapella** [comment]
Where does it say we can't use json? Do we pass objects which aren't simple data structures?

**Comment by giocalitri** [comment]
It says:
>In case you don't use Python objects as arguments in your tasks you should consider using safe e.g. json serialization format.

I think we need to check this, but I prefer not to limit ourselves and simply serialize using pickle.

**Comment by noisecapella** [comment]
Right, but pickle is a (minor) security concern since if the user has the ability to mess with the pickled objects in redis, they can execute arbitrary code. I think json also performs better than pickle since its scope is more restricted. But the user doesn't have access to redis or the ability to craft input to the tasks, so I think it's a minor issue and I'm happy to go either way
