### ISSUE TITLE
Exams: SSO Callback URLs

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#2173]
We need to provide (and implement) the following urls for Pearson:

- [ ] Return url (non-failure)
- [ ] Error url
- [ ] Timeout url
- [ ] Logout url

If we could figure out what these urls are soon (they doesn't have to be implemented immediately) that would be ideal so that we can provide them to Pearson.

For now, we can set up these as redirects, and then add API(s) as needed. For none of these callbacks do we have to take any action, but it would be nice to alert the user to some of the states, and possibly make a log entry. 

Proposed URLs and redirect locations (for now):

/pearson/return => /dashboard?exam=success
/pearson/error => /dashboard?exam=error
/pearson/timeout => /dashboard?exam=timeout
/pearson/logout => /dashboard?exam=logout

**Comment by pdpinch** [comment]
Sorry I've neglected this. 

Would it make sense to set these up as a collection of redirects that we can modify as necessary without updating the Pearson folks? for example:

/pearson/return => /dashboard?exam=success
/pearson/error => /dashboard?exam=error
/pearson/timeout => /dashboard?exam=timeout
/pearson/logout => /logout

I'm imagining that we would set up toast messages that display for the various values of exam that are passed.

**Comment by rhysyngsun** [comment]
That sounds fine to me generally, although I'm not certain a logout on the Pearson side should trigger a  logout on our end. We can change any of those to be whatever we want at any point anyway.

**Comment by pdpinch** [comment]
Ok. I agree about logout. I updated the description, and my plan is to assign this to @mitodl/devops 

@noisecapella you did the coding for the cybersource callbacks. Can you take a look at this when you have a few minutes and let us know if we're adequately planning for the future?

**Comment by rhysyngsun** [comment]
@pdpinch circling back on this, we chatted about whether this should be implemented in nginx or the frontend. Because we want to display errors from the querystring in the UI (probably via toast) I believe we last left this as warranting an implementation in the frontend, correct?
