### ISSUE TITLE
Mobile Safari SecurityError when storing program during sign up flow

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2180]
@aliceriot can you take a quick look at this? I don't think it's blocking user's signing up or logging, but it would be good to confirm. 

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/190414657/

```
SecurityError: The operation is insecure.
  at storage (./static/js/store/configureStore.js:32:40)
  at signupDialogStore (./static/js/store/configureStore.js:47:4)
  at module (./static/js/entry/public.js:54:14)
...
(3 additional frame(s) were not displayed)
```

**Comment by pdpinch** [comment]
I'm not sure if this is related -- similar browser, similar error, but later in the profile flow. 

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/190987041/

**Comment by aliceriot** [comment]
Yeah, I've taken a look at this error before and not found anything conclusive. My guess is that it relates to using `localStorage` (which we do for redux).

**Comment by aliceriot** [comment]
second one looks different, but the underlying theme of 'why safari why' holds :D

**Comment by pdpinch** [comment]
Do you think it's blocking users?

**Comment by aliceriot** [comment]
I doubt it, I imagine that all that's happening is a very slightly degraded experience because `localStorage` is being blocked - although without reproing it ourselves it's hard to say for sure. I think the redux middleware for `localStorage` should be smart enough to keep on trucking even if `localStorage` is blocked for some reason.

**Comment by aliceriot** [comment]
Is there a way we can figure out if that IP has a user associated with it?

**Comment by aliceriot** [comment]
I think this is the same issue as #2256, so if we're going to close that we should close this too.
