### ISSUE TITLE
Degrade gracefully when edX is down

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2181]
Currently if edX is down and the user needs to refresh some data from the cache, we show an error on the whole screen. Instead, we should log the error and show the old data from the cache, if there is any. I'm not sure what to do about the case where a user first logs in and has no cached data, and edX is also down all of a sudden after being available for login.

**Comment by noisecapella** [comment]
![screenshot from 2016-12-21 10-37-03](https://cloud.githubusercontent.com/assets/863262/21395159/739a5858-c769-11e6-924e-64319ddd4591.png)

**Comment by pdpinch** [comment]
Would this address https://sentry.io/mit-office-of-digital-learning/micromasters/issues/193330670/

**Comment by noisecapella** [comment]
Yes, at least from the user experience perspective. We should still log these events in case they're useful, so we know if we are causing too much API activity with edX

**Comment by giocalitri** [comment]
I think this is a super set of some other issues already filed.

In general I think that this is easily accomplishable from a technical point of view (we already have the cached data) but we need a bit of design from @roberthouse54 to solve the problem of how to tell the user that what she is seeing might not be up to date.

**Comment by roberthouse54** [comment]
How about this:

"Sorry, the edX server seems to be down, so some of your information may not be up to date. Please refresh the browser, or check back later. If the error persists, contact support@example.com for help."

![image](https://cloud.githubusercontent.com/assets/20047260/21647847/e1253d60-d269-11e6-8e4a-073c723dd7a0.png)

**Comment by Ferdi** [comment]
Maybe "edx.org is not responding as expected"  or something like that. Because user might see this error and edx.org load fines for them

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/193925129/

**Comment by roberthouse54** [comment]
OK, let's change the error text to say: "Sorry, edx.org is not responding as expected, so some of the information on this page may not be up to date. Please refresh the browser, or check back later. If the error persists, contact support@example.com for help."
