### ISSUE TITLE
Search: confusing error message when there are no results

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2182]
You can reproduce this on micromasters-rc, where no one has passed more then 4 courses, e.g. https://micromasters-rc.herokuapp.com/learners/?num-courses-passed[min]=4&num-courses-passed[max]=5

<img width="1392" alt="screenshot 2016-12-21 11 15 34" src="https://cloud.githubusercontent.com/assets/430126/21396723/21f9aa84-c76f-11e6-8dba-c7bb4b7e8f82.png">

**Comment by pdpinch** [comment]
@roberthouse54 do you think we should have a generic "no results" message or give more feedback about the query that go zero hits.

**Comment by roberthouse54** [comment]
I think we should have a generic message whenever a query results in no hits. "There were no results found for this search. Please remove some filters or <link>start over</link>."
