### ISSUE TITLE
Add "not passed" courses to student dashboard API

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#219]
As a micromasters student I want to see courses that I enrolled in but didn't pass on my student dashboard. 

After discussing the issue at the Product Council, it is clear that we do need to display failed courses, so students know what has happened.

**Comment by pdpinch** [comment]
This is complicated for several reasons:

- The certificate table at edX only contains users who passed the course. 
- Also, the necessary data isn't passed in the dashboard API currently. Moreover, we will need to change the structure to be nested, so we have the relationship of the failed run to the next run.

**Comment by giocalitri** [comment]
dependent on #224

**Comment by pdpinch** [comment]
@Ferdi do you think this is required for MVP?

**Comment by giocalitri** [comment]
The code #224 has been merged, if we want to proceed with this one

**Comment by Ferdi** [comment]
If I understand it correctly, this is one of the core features in the dashboard - knowing that I took the course, didnt pass so I should take it again soon.

**Comment by giocalitri** [comment]
ok: so I will work on this next
