### ISSUE TITLE
Determine what to do with existing micromasters web site

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#22]
This is a little premature, but I assume that the micromasters portal, when it goes live, will be released to https://micromasters.mit.edu/

What should happen to the existing content at http://micromasters.mit.edu/ -- should it be incorporated into the app as static content?

**Comment by Ferdi** [comment]
Yes, the new app will replace the existing one. What you see there currently would move to http://micromasters.mit.edu/scm

**Comment by justinabrahms** [comment]
`/scm` will be a landing page for soliciting email addresses? Or it will be the supply chain management section of the CMS?

**Comment by Ferdi** [comment]
SCM section of the CMS - is what I had in mind.  Which  could contain a signup form too.

**Comment by Ferdi** [comment]
There is not much info in the current page (http://micromasters.mit.edu/). Initially, we can simply link the "micromaster" card in the front page to go to the department SCM page (http://scm.mit.edu/micromasters). We can switch when we have the CMS ready. The only thing to do is have the signup form as part of the new front page.
