### ISSUE TITLE
Knowledge Bases - Explore Taiga's KB-specific features

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#2200]
https://taiga.io/
[KB discussion notes](https://docs.google.com/document/d/1r3S7RsJapA3H5v8crAzcfS9M_hYRCvLsLQHvE3EeNdE/edit)

We can host Taiga ourselves, which is a big perk, but as a tool its top selling point seems to be its project management capabilities. We should take it for a spin to see what its knowledge base-specific features might give us.

**Comment by blarghmatey** [comment]
After testing the wiki authoring in a virtualbox instance of Taiga it definitely doesn't seem like something that we should use for its documentation capabilities. The wiki is very rudimentary and doesn't have any good auto-discovery capabilities. We can create bookmarks into the content, but the workflow for creating a new page is to use markdown/wiki syntax to generate the link which will then create the blank page.

**Comment by gsidebo** [comment]
Issue moved to [mitodl/handbook #25](https://github.com/mitodl/handbook/issues/25) via [**ZenHub**](https://www.zenhub.com/)
