### ISSUE TITLE
Define on_delete on all ForeignKey

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2203]
In Django 2.0 this will be a required attribute:
https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.ForeignKey

**Comment by pdpinch** [comment]
Does this essentially mean that we'll have to remove the foreign keys from the audit tables?

**Comment by noisecapella** [comment]
No, we just need to define `on_delete` explicitly on all our foreign keys. If it's not there already we would need to add a migration

**Comment by rhysyngsun** [comment]
Closing since this is already done.
