### ISSUE TITLE
MicroMasters Adwords Remarketing Tag Insertion

### ISSUE THREAD

**Issue by ChrisLanfranco** [mitodl/micromasters#2211]
Request: Insert Google Adwords Remarketing Tag right before the </body> for the following pages: 

https://micromasters.mit.edu/
https://micromasters.mit.edu/dedp/
https://micromasters.mit.edu/scm/

Maria Cruz wants to start tracking website visitors for adword remarketing purposes for the MicroMasters program. Inserting this tag will allow us to start tracking these visitors. Attached is the tag. Let me know if you have questions.

Thank you!
Chris L
[Google Adword Remarketing Tag.docx](https://github.com/mitodl/micromasters/files/674481/Google.Adword.Remarketing.Tag.docx)

**Comment by pdpinch** [comment]
@ChrisLanfranco can you explain what the user value of remarketing is? And also how we will know if this is working?

**Comment by ChrisLanfranco** [comment]
@pdpinch 

Google Adwords remarketing is conducted through Google Display Network. The value in it allows us to show ads to users who have already visited our site while browsing the web. 

So in theory, we can improve our conversation rate by spending ad dollars that would have gone to marketing to brand new visitors, towards remarketing to people that have searched for and are familiar with our program already.

How it works:

Add the Adwords tracking url to pages we want to track users on

I create a remarketing list on Adwords with certain rules:

- URL contains category
- Search terms used by visitors 
- Referral urls
- ETC

I can setup rules to target particular visitors to remarket to.

Example: I’m targeting visitors to remarket to by what keywords they searched for to find our site. 

If the user fits the criteria, they’re cookied and added within a list in the Adwords account. Allowing us to remarket/show ads to them within Google Display Network sites. 

Adwords has a verification test to make sure the tag is working properly as well.

**Comment by pdpinch** [comment]
Thanks for the explanation. Definitely seems valuable. Can you point us to the docs on the verification test?

**Comment by ChrisLanfranco** [comment]
https://support.google.com/adwords/answer/3103509?hl=en

I know how to verify on my end if you want to stick the tag within the pages. If you want to verify it, I'll be more than happy to give you admin if you don't already to the adwords account. I'm pretty sure you'll need that. Thx again Peter!

**Comment by amir-qayyum-khan** [comment]
@ChrisLanfranco i need to add below code as it on header of these pages ?
please explain what do you mean by ``right before the for the following pages:``?
should this cover (https://micromasters.mit.edu/) all site, i mean header of all site?

```js
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 935224753;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/935224753/?guid=ON&amp;script=0"/>
</div>
</noscript>
```

**Comment by ChrisLanfranco** [comment]
@amir-qayyum-khan Just throw the tag in the header, the Google directions seemed a little bit outdated by adding it in the <body> within each individual page. Thx Amir.

**Comment by pdpinch** [comment]
@amir-qayyum-khan it's most valuable on the public pages, so if it's easier to omit it from the dashboard or the search, that's OK. 

But if it's easier to just include everywhere, that's fine too.

**Comment by amir-qayyum-khan** [comment]
@ChrisLanfranco it is giving errors on console, is this an issue?

<img width="1264" alt="screen shot 2017-01-06 at 9 02 46 pm" src="https://cloud.githubusercontent.com/assets/10431250/21723790/9427a958-d453-11e6-804c-c609052f6557.png">

**Comment by pdpinch** [comment]
@amir-qayyum-khan do you have ad-blocking turned on?

**Comment by amir-qayyum-khan** [comment]
yes @pdpinch

**Comment by amir-qayyum-khan** [comment]
issue fixed after disabling ad blocker. thanks @pdpinch

**Comment by ChrisLanfranco** [comment]
@amir-qayyum-khan 

Hmm it seems like it was working for a hot second on January 6th, is the tag in the header or in the body? 

![screen shot 2017-01-10 at 8 57 35 am](https://cloud.githubusercontent.com/assets/22057324/21808826/fc1c0a7e-d712-11e6-9673-24333add3c33.png)

**Comment by pdpinch** [comment]
This hasn't been merged or deployed yet. What you saw there was the test (I guess we're using the same account for testing and for production?).

Amir, what more work needs to be done on this? I know it's possibly blocked by #2280

**Comment by ChrisLanfranco** [comment]
Ohhhhhh ok, that explains that then! Thx!

**Comment by amir-qayyum-khan** [comment]
@pdpinch I can merge it first and then @singingwolfboy needs to update his PR or vise versa. FYI code is complete.

**Comment by pdpinch** [comment]
Good point. 

If your PR has been approved, you can merge it. DB can update his PR.

**Comment by amir-qayyum-khan** [comment]
no it not approved.

**Comment by ChrisLanfranco** [comment]
I've been monitoring the adwords remarketing tag activity and I'm not seeing any traffic come in from the micromasters portal, not sure why. I installed the adwords tag on another site and it's working properly, so we know the tag code does work. Could we investigate this further? Let me know if you need anything and I'll be happy to lend support.

**Comment by pdpinch** [comment]
Amir, did this get released yet?

Do we need a setting for adwords in production? If so, you need to ask DevOps to do that when this gets released.

**Comment by amir-qayyum-khan** [comment]
- @pdpinch this solution is merged but not release on production yet.
- yup there is a .env variable that need to set ```ADWORDS_CONVERSION_ID=935224753```
- cc @blarghmatey @mitodl/devops 


https://github.com/mitodl/micromasters/pull/2263

**Comment by pdpinch** [comment]
@ChrisLanfranco can you confirm if this is working now? If so, we'll close it.

**Comment by ChrisLanfranco** [comment]
@pdpinch Confirmed! Case closed.

**Comment by pdpinch** [comment]
Thanks for confirming Chris!
