### ISSUE TITLE
when grade is empty, don't display percent completed

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#222]
Since we aren't getting current grades yet, we don't want to mislead students by displaying 0% of the course completed. Instead we will should display the same state as if the student is enrolled with the string "enrolled"

**Comment by aliceriot** [comment]
currently if you set a course run to have the `verified-not-completed` status, and it has no grade, this is what it looks like:

![no-grade](https://cloud.githubusercontent.com/assets/6207644/15119808/a9552486-15e0-11e6-88ac-b9a24cbc4b05.png)

do we need to change this behavior further?

**Comment by pdpinch** [comment]
That's perfect. Thanks for checking.
