### ISSUE TITLE
Final Grades: add celerybeat hook to run the freeze automatically via cron

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#2223]
#2126 added the tasks to freeze the final grades.
this issue is to add a hook in celerybeat to https://github.com/mitodl/micromasters/blob/master/grades/tasks.py#L23 to run the freeze every X hours

**IMPORTANT**: this should not be done until we are confident that everything works fine.

**Comment by pdpinch** [comment]
@giocalitri can we do this now?

**Comment by giocalitri** [comment]
not until we solve the problem of how to deal with the 401 errors when we freeze the final grades.
Maybe a solution might be to collect all the users that have been successful frozen and all the users who got a 401. If the sum of the 2 is the total number of user we set the freeze process as complete, otherwise we need to run it again.
I think this is doable...
