### ISSUE TITLE
Missing enrollments for MITx/14.73x/2013_Spring

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2230]
a user contacted support claiming to have audited the first offering of 14.73x (`MITx/14.73x/2013_Spring`), which is no longer available on edX. The course does not appear in her cached enrollments. In fact, i can't find any use who has enrolled in this course. 

Once #1856 is complete, we'll have a way to address this, but it would be useful to determine whether this data is missing from edX, or we are using the wrong course key, or we have a bug.

**Comment by giocalitri** [comment]
we should probably rule out the key mismatch and other problems on edX before looking for bugs on our side.

**Comment by pdpinch** [comment]
We learned from Nimisha at edX this is because this course doesn't exist in the course overview table, and the enrollments and certificates APIs check course overview first. 

We've dealt with this by freezing the grades for this course and then manually importing data from IRx.
