### ISSUE TITLE
Coupon: change percent discount to full discount

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2236]
Part of #2158

Since we are only handling 100% discount and a fixed price discount we should change the model to handle only those two states. The `percent-discount` state should be removed because this adds complications we don't want to handle right now

**Comment by pdpinch** [comment]
@noisecapella it would be nice to have the option in the future to handle other percent discounts. Is there a reason for removing that support?

**Comment by noisecapella** [comment]
The reason is to cut the scope of the issue, but after thinking about it some more I don't think it simplifies things much to do so
