### ISSUE TITLE
Welcome e-mail for new users

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2241]
Some programs would like to send out an automatic welcome e-mail to new users, when they enroll. The e-mail would contain information about the program, and a link to a (qualtrics) survey. 

It would be useful to have a mechanism to send out this e-mail to existing users enrolled in the program who haven't been sent one yet. 

### acceptance criteria (MVP)
- [ ] course team gives us a mail template which we can add (via django admin or shell)
   - the template will include a link to a qualtrics survey. The link should include some user-identifiable information, like their edx username 
- [ ] support one query: when learner enrolls in program 

### related issues (out of scope)
- [ ] The course team will need an interface to be able to edit and customize the e-mail. 
- [ ] The course team should have options about what triggers the e-mail. Options include:
   - When the learner pays for (any) course in the program
   - When the learner pays for a specific course

**Comment by pdpinch** [comment]
This is a special case of #2510 and should be implemented in a similar way, using the Percolate feature of ElasticSearch.

**Comment by pdpinch** [comment]
This needs to be re-scoped.

**Comment by pdpinch** [comment]
I emailed Arthur from SCM asking for:

1) Search criteria for welcome mail
2) text for welcome mail

**Comment by noisecapella** [comment]
Do we have either of those yet?

**Comment by pdpinch** [comment]
**Search Criteria:** Anyone who joins the portal as a paid, verified learner in at least one course.

**email template:** 

```
Greetings  {first name},
 
Thank you for verifying for your course in the MITx MicroMasters of Supply Chain Management. Welcome! 
 
We will use micromasters.mit.edu as our primary communication channel with you, though all of your course work will take place at edX.org. This dashboard will help you navigate between courses. It is linked directly to edX and will update automatically with your course progress. It will help us to contact you with vital information about courses and allow you to reach us directly with non-assignment questions or concerns. It will enable us to connect you with other learners in your geographic area or reach you with special opportunities. 
 
Please take about three minutes to complete the survey here.
http://mit.co1.qualtrics.com/jfe/form/SV_9zqju8s4t4VniQd
 
As your course work progresses we hope to learn more about you. Knowing the answers to these questions will help us provide you with the best learning experience possible. On behalf of the entire MicroMasters team we welcome you.
 
Best wishes,
 
Dr. Chris Caplice, Director, SCM MicroMasters Program, Silver Family Research Fellow
Dr. Eva Ponce, Executive Director, SCM MicroMasters Program 
```

**Comment by pdpinch** [comment]
I've e-mailed with IRx (Institutional Research) about how to pass data through the survey link. [Qualtrics uses a simple key=value query attributes appended to the URL](https://www.qualtrics.com/support/survey-platform/survey-module/survey-flow/standard-elements/embedded-data/#SettingValuesFromTheSurveyURL). However, IRx recommends against clear text data. Instead we should use some kind of opaque identifier and then pass any additional fields out of band (either via [API](https://api.qualtrics.com/) or manual upload). That raises a question for us of what identifier to use.

**Comment by noisecapella** [comment]
@pdpinch I'm going to add a field to the user profile to add a UUID for that user for use in these emails. That should prevent users guessing other user's user id's and filling out the survey on their behalf, and it should make it easy to link the survey results back to the user.

**Comment by noisecapella** [comment]
I think we should be able to do this now without any additional code changes. We should try it on some testing subset of users to make sure the templating works, then modify the query or create a new `AutomaticEmail` object which has the filter we want

**Comment by noisecapella** [comment]
Just realized that I didn't explicitly put this anywhere, but here are the tokens which are replaced:
 - `%recipient.mail_id%` is the UUID
 - `%recipient.email%` is the user's email
 - `%recipient.preferred_name%` is the user's preferred name

**Comment by pdpinch** [comment]
I was able to make this work on micromasters-rc using a simple query of all paid users. When I faked a payment for one of my users, it triggered an e-mail to be sent. I also tested the tokens in the previous comment. 

I did get an error when I initially created the automatic e-mail, which I think was due to a fake user account. I'll look into that further before I close this out.

**Comment by pdpinch** [comment]
Now that #3126 is released, I think we can close this.
