### ISSUE TITLE
Dashboard: allow user to pay after the end of the course, until the "upgrade" deadline"

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2253]
Some courses (typically financial aid courses) can be paid for even after the course has ended. 

We should rely on the course's upgrade deadline for the logic for displaying the payment button, and not the course end date.

**Comment by giocalitri** [comment]
Algorithm for the implementation.
![img_6099](https://cloud.githubusercontent.com/assets/1005204/21683873/3e629c88-d329-11e6-80de-9d4d993f10a3.jpg)

**Comment by giocalitri** [comment]
Upgraded logic according to current code.
![img_6105](https://cloud.githubusercontent.com/assets/1005204/21695627/a5814886-d358-11e6-9b36-8a8a08e5ba1c.jpg)

**Comment by pdpinch** [comment]
Is this in progress?

**Comment by giocalitri** [comment]
yes: working on tests

**Comment by pdpinch** [comment]
Can you move it to "in progress"
