### ISSUE TITLE
Fix MockedESTestCase

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2254]
Since we don't use Elasticsearch in most of our Python tests we should mock Elasticsearch somehow to prevent communication with it. We need to do it in a way that doesn't interfere with the functionality of the app, and a test speed increase would be nice too

**Comment by pdpinch** [comment]
How much of a speed increase are you expecting?

**Comment by noisecapella** [comment]
I don't know. Currently we run `recreate_index` after each `setUp` for each test so it feels like there's a lot of unnecessary communication there, but I don't know for sure

**Comment by pdpinch** [comment]
How much does this overlap with #812 (opened by @gsidebo) ?

**Comment by noisecapella** [comment]
I don't think there's much overlap. He's talking about refactoring search tests to make them faster, but this would cover all tests that aren't search-related
