### ISSUE TITLE
SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2256]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/190938653/

This error has been picking up recently. It seems to be mostly from Android, but there are  few Linux and Windows users too. 

@aliceriot, do you have any idea what might be happening -- just so we can triage this?

```
SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
  at storage (./static/js/store/configureStore.js:32:40)
  at configureStore (./static/js/store/configureStore.js:47:4)
  at signupDialogStore (./static/js/store/configureStore.js:84:11)
  at call (./static/js/entry/public.js:54:14)
...
(4 additional frame(s) were not displayed)
```

**Comment by aliceriot** [comment]
https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document looks like the primary reason this would happen is because of a user setting. I'm looking into trying to reproduce it exactly,

**Comment by aliceriot** [comment]
I'm seeing the error for our redux-localstorage code as well as for smartlook

**Comment by pdpinch** [comment]
Smarlook isn't turned on in production, so the production errors must be coming from redux-localstorage?

What's the failure behavior like?

**Comment by aliceriot** [comment]
It's a bit hard to tell - the only way I'm able to reproduce it is by blocking the site from setting any data. This also blocks cookies, which means I can't login...

**Comment by aliceriot** [comment]
In chrome you can disable `localStorage` with the `--disable-local-storage` command line flag. It seems like everything works alright - although there is a console error on every redux action (not an exception, just a `console.error` call).

**Comment by aliceriot** [comment]
So users out there who, for some reason, have just their localStorage disabled, they should not have a problem using the site. Of course, if they don't allow their browser to set any data they can't use the site in any case.

**Comment by pdpinch** [comment]
Can we quiet the error, and is it hard?

**Comment by aliceriot** [comment]
based on https://bugs.chromium.org/p/chromium/issues/detail?id=357625 and a couple of other things I found I don't think it's possible for a user to have cookies unblocked and `localStorage` blocked in this way

**Comment by pdpinch** [comment]
Hmm, so our real problem might be people who have cookies blocked? Do you think they're blocking all cookies, or just 3rd party?

**Comment by aliceriot** [comment]
I can't reproduce the error by just blocking third-party cookies, so I think the error is probably cropping up for users who have 'Block sites from setting any data' (in Chrome, similar options exist in other browsers) set.

**Comment by aliceriot** [comment]
From what I understand, most browsers block `localStorage` along with cookies (`localStorage` is kind of just a super-cookie anyway).

**Comment by aliceriot** [comment]
should we go ahead and close this? (and maybe mute the error in sentry)

**Comment by aliceriot** [comment]
@pdpinch what do you think about closing this?

**Comment by aliceriot** [comment]
@pdpinch bump ^^

**Comment by pdpinch** [comment]
I'd like a way to message these users and fail quietly, but I don't we're going to get to it anytime soon. I'll close this for now and see how much more traffic we get from Sentry
