### ISSUE TITLE
Add button and note for applying to masters program to student dashboard

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#226]
For MVP, this should just be an inactive button -- so users know that it's coming later. It should look like https://projects.invisionapp.com/share/AF6XG4X62#/screens/142338434

For the future:

There should be a message, "You need to complete X more courses before you can apply for a masters" 

X = (total number of courses in the program minus the user's course with status PASSED)

button is inactive until user has passed all courses.

**Comment by pdpinch** [comment]
I don't think this is necessary for MVP, @Ferdi ?

**Comment by Ferdi** [comment]
A static , inactive button that does nothing would be nice. To give the impression to users that we are working on it

**Comment by pdpinch** [comment]
I update the description to make the expectation for MVP more clear.

**Comment by amir-qayyum-khan** [comment]
Done with changes in #282 

<img width="1067" alt="screen shot 2016-05-06 at 8 42 16 pm" src="https://cloud.githubusercontent.com/assets/10431250/15078203/79c1685e-13cb-11e6-82e5-4ac25bff0d7b.png">
