### ISSUE TITLE
Profile: staff view of learner’s enrollments and grades

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2266]
As a staff member, when I am advising a student, I’d like an easy way to look up their enrollments and grades. 

We will add a card (per program) to the learner profile, only visible to staff. It will contain:
- [ ] basic information about course enrollments (current and past) 
- [ ] paid/not paid
- [ ] progress and final grades (if any)

**Comment by pdpinch** [comment]
@roberthouse54 this was a specific request from SCM and seems like it would be generally useful (I know it would help me with support issues)

**Comment by roberthouse54** [comment]
Yeah, this makes sense. I will do a design for it.

**Comment by roberthouse54** [comment]
There is a design of this on Invision: 

https://invis.io/PVA10ONNJ#/214364752_Enhanced_Profile_Faculty_View

![enhanced_profile_faculty_view 2x](https://cloud.githubusercontent.com/assets/20047260/22166105/65a37dfc-df2d-11e6-8808-1e10d081de61.jpg)
