### ISSUE TITLE
user has 2 python social auth objects

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2276]
Not sure how this happened, but now it seems to generate an error with every batch update.

```
MultipleObjectsReturned: get() returned more than one UserSocialAuth -- it returned 2!
```

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/201751696/

```
MultipleObjectsReturned: get() returned more than one UserSocialAuth -- it returned 2!
  File "dashboard/tasks.py", line 96, in batch_update_user_data_subtasks
    UserSocialAuth.objects.get(user=user)
  File "django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 389, in get
    (self.model._meta.object_name, num)

user "fgrodriguez74" does not have python social auth object
```

**Comment by pdpinch** [comment]
@giocalitri can we just modify the code to use the first social auth?

**Comment by giocalitri** [comment]
in production we have only one case like this:
```
micromasters=> select user_id, count(user_id) from social_auth_usersocialauth group by user_id having count(user_id) > 1;
 user_id | count
---------+-------
    6497 |     2
(1 row)
```

the problem I can see is that the 2 entries are actually associated with 2 different user ids on edX
```
In [1]: from django.contrib.auth.models import User
In [2]: user = User.objects.get(username='fgrodriguez74')
In [3]: aa = list(user.social_auth.all())
In [4]: aa[0].uid
Out[4]: 'fgrodriguez74'
In [5]: aa[1].uid
Out[5]: 'fgrodriguez'
```

Now considering that the user id created locally is `fgrodriguez74`, I assume that the right social auth is the one with the same user id and I have no idea how the association of a different user id has been possible.

Now given that the profile is not filled out and there are no financial aid applications, I suggest to either delete the user completely or we could email the user asking which one is the username on edx and delete the other one.

The solution to use just the first social auth could not work if that one is the wrong one.

**Comment by giocalitri** [comment]
Follow up question: can an user change username on edX?

**Comment by pdpinch** [comment]
Here's another case: https://micromasters.mit.edu/admin/social_auth/usersocialauth/?q=pogorsky and https://sentry.io/mit-office-of-digital-learning/micromasters/issues/201751696/events/4986340904/

I have to agree, it does look like they changed their username, but the edX account settings page says you can't do that: 

<img width="1033" alt="screenshot 2017-02-27 21 33 43" src="https://cloud.githubusercontent.com/assets/430126/23389252/f7da4b9a-fd34-11e6-9f55-29e668dd81c1.png">

I've contact both users to see what they have to say.

**Comment by giocalitri** [comment]
but this just happened after I checked this afternoon!
I have no idea what's going on.

**Comment by pdpinch** [comment]
We followed up with edX and, although it is against policy to allow username changes, they do do it occassionaly as a support issue.

**Comment by pdpinch** [comment]
The user has not gotten back to me. Now that we know how this happened, shall we delete the 2nd social auth?

**Comment by giocalitri** [comment]
In the meantime I deleted the wrong user social: working on a soution

**Comment by giocalitri** [comment]
we do not have other cases at the moment so closing this issue.

```
micromasters=> select user_id from social_auth_usersocialauth group by user_id having count(user_id) > 1;
 user_id
---------
(0 rows)
```
