### ISSUE TITLE
Coupons: support Pearson exams pilot

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2279]
Generate and apply 100% off coupons for learners / exams in pilot

To support the Pearson pilot, we would like to generate 100% off coupons for anyone who has passed one of the DEDP courses in the pilot. We will apply the coupons for them, and automate the orders, so their dashboard will display as "paid" and they can schedule the exam when it is ready. 

Eligible learners will be notified of this opportunity by the course team (ideally, using the learner search)

### acceptance criteria:

- [ ] generate list of eligible learners
- [ ] generate coupons for eligible leaners for the appropriate course
- [ ] apply the coupon to the user
- [ ] apply the coupon to the course

**Comment by noisecapella** [comment]
Can a user apply two or more coupons to the same course run?

**Comment by noisecapella** [comment]
Is there anything I need to do for this or is this all administrative work?

**Comment by pdpinch** [comment]
How might we handle people who haven't signed up the portal yet, but might do so in order to participate in the pilot?
