### ISSUE TITLE
Dashboard: contact course team link

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2284]
Depends on #2375 

One feature we'd like to offer MicroMasters students is the ability to quickly and easily contact the course team. 

To start with, we'll offer a link to send mail to the course team from the dashboard. Each course potentially has a unique e-mail. 

- [ ] Buttons appear for all users, one associated with each course
- [ ] If user hasn't paid for the specific course, on click they get an upsell message
- [ ] If user has paid for the course, on click they get compose mail pop-up, similar to learner search
- [ ] model for associating courses with e-mail address(es)
- [ ] modify dashboard course buttons to group "Contact course team" with "View on edX" (could be a ︙menu, or could be a horizontal list of links before the course description)
- [ ] from address should be learner's e-mail address

**Comment by pdpinch** [comment]
Can we use the micromasters_verified in the profile to indicate who is eligible for this?

**Comment by gsidebo** [comment]
@pdpinch I'm pretty positive that the `verified_micromaster_user` property in the Profile doesn't tell us anything about whether or not a student has paid for any courses. I don't really know what it tells us, to be honest. 

Just to confirm, if a user is currently enrolled in Course A and B in some program, and they've paid for A, but not B, they would only be shown the 'contact' link for Course A?

**Comment by gsidebo** [comment]
Seems like some courses will have a course-team-specific email and others won't. Is this a possible scenario? If that's the case, I think it might be a good idea to have a program-wide email address and require that it be set for each program. Courses with no course team email would fall back to that. What do you think?

**Comment by pdpinch** [comment]
I made some changes to the description to try to answer your questions above in https://github.com/mitodl/micromasters/issues/2284#issuecomment-271984487. I agree that `verified_micromaster_user` won't be helpful. 

Both of our current course teams have course-specific e-mail addresses, so I don't think it's worth the engineering effort to have a fall back like you suggest in https://github.com/mitodl/micromasters/issues/2284#issuecomment-271986283

**Comment by gsidebo** [comment]
Sounds good. The email address should be a required field then. I'll try to send some simple test emails via mailgun to make sure it behaves the way we expect with specific 'from' addresses

**Comment by pdpinch** [comment]
I'm ok with making the e-mail address required, but it also seems like you could just omit the feature (per course) if there is no e-mail set. 

Amir already did some work to customize the from address for maligun in #2206

**Comment by gsidebo** [comment]
@pdpinch Just tested via mailgun. Everything looks good. Here are screenshots of an email I send from my MIT address to my Gmail address (and replied to from Gmail).

<img width="765" alt="ss 2017-01-11 at 17 04 28" src="https://cloud.githubusercontent.com/assets/14932219/21868438/bee53e3c-d820-11e6-95f3-656fd944c1c1.png">

![ss 2017-01-11 at 17 04 35](https://cloud.githubusercontent.com/assets/14932219/21868440/c223aaf2-d820-11e6-9fb7-1bbacdc35cd3.png)

**Comment by roberthouse54** [comment]
Updated mocks are on Invision:

![image](https://cloud.githubusercontent.com/assets/20047260/22166011/d6d9fac4-df2c-11e6-8c5c-f3dbc0d36c5a.png)

![image](https://cloud.githubusercontent.com/assets/20047260/22166019/de5a4a42-df2c-11e6-8973-fbd54e1540de.png)

![image](https://cloud.githubusercontent.com/assets/20047260/22166024/e5294fee-df2c-11e6-9b5c-690e6dc87932.png)

After clicking Send Message, we should close the modal, and display a standard toast message with the copy "Your message has been sent to the course team." and a checkmark icon at left.

**Comment by roberthouse54** [comment]
I updated the modals to remove the user images:

![image](https://cloud.githubusercontent.com/assets/20047260/22257616/914bdb00-e22c-11e6-9467-5ad528080dec.png)

![image](https://cloud.githubusercontent.com/assets/20047260/22257637/9cc9ee72-e22c-11e6-83c6-262d9ac8f5ea.png)
