### ISSUE TITLE
Profile: capture full address

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2285]
Revised requirements:

- [x] Revert google places
- [ ] Address as a single 100 character field
- [ ] Split address on word boundaries into the 3 fields on backend when we export to Pearson
- [ ] Require / Show zip code for US and Canada only (note to user in UI)

**Comment by rhysyngsun** [comment]
https://developers.google.com/places/web-service/autocomplete - use `"address"` address type.

**Comment by rhysyngsun** [comment]
@singingwolfboy example using their js API directly for discrete addresses: https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform

**Comment by singingwolfboy** [comment]
That example still allows users to select places that do not have fully-qualified street addresses.

**Comment by rhysyngsun** [comment]
A few issues noted in user testing of google's autocomplete:

- Apartment/floor numbers, etc don't work with the autocomplete.
- Some addresses will have `administrative_area_level_1`, which we map to `state_or_territory` as data that probably shouldn't be in our address data (e.g. in the UK this value will be "England"). I don't know if there's a way to disambiguate when the value of that location type is valid for us to use.

**Comment by singingwolfboy** [comment]
Reverting the Google Places UI in #2305

**Comment by pdpinch** [comment]
I'm moving this to the In Progress pipeline
