### ISSUE TITLE
Exams: restrict learners to 2 exam attempts

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2286]
A learner would not be allowed to schedule a 3rd exam (create another `ExamAuthorization` record) if they already had two authorizations with `exam_taken` set to true. That is it to say, the learner is allowed two authorization for each course payment.

**Comment by rhysyngsun** [comment]
Clarification needed: is this a maximum of 2 retakes or a maximum of 2 attempts (i.e. 1 initial attempt + 1 retake).

**Comment by rhysyngsun** [comment]
This would require handling the exam registration results so that we can tell when an authorization is redeemed for a scheduled exam.

**Comment by pdpinch** [comment]
Does it require processing the registration results? Couldn't we just key it off of grades? (assuming that we deal with #3084 appropriately).

**Comment by rhysyngsun** [comment]
@pdpinch we could key it off of grade processing, there's already an `exam_taken` flag on the auth record we could use.

**Comment by pdpinch** [comment]
I updated the total count in the description based on an e-mail from DEDP. 

I also noted that for each course payment, two attempts are allowed.

**Comment by rhysyngsun** [comment]
@pdpinch it's sufficient to only support FA courses for the number of paid courses, correct?

**Comment by pdpinch** [comment]
> @pdpinch <https://github.com/pdpinch> it's sufficient to only support FA courses for the number of paid courses, correct?
> 

Yes, that's fine.
