### ISSUE TITLE
Exams: Accommodations

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#2288]
Accommodations are test modifications that are granted to test-takers with disabilities. Pearson would like us to pass accommodation requests along with exam authorizations. 

### acceptance criteria
- [ ] add a model for accommodations; need to find out if it is associated with users or with user and exam
- [ ] establish a process for granting accommodations. Could be in the django admin or, preferably, a web interface exposed to course staff (similar to financial aid review)
- [ ] determine the set of potential accommodations approved by MIT
- [ ] find out the encoding scheme from Pearson
- [ ] add the accommodations to the authorization export

**Comment by pdpinch** [comment]
I did a first pass on the description, including acceptance criteria. We'll know more when we hear back from Mary Ziegler.

I also added this to the epic.

**Comment by pdpinch** [comment]
We won't be doing this for the pilot, so I'll close the issue. After the pilot we'll know better what we need and re can re-open this, or create a new issue.
