### ISSUE TITLE
Website should respect "Do Not Track" preference

### ISSUE THREAD

**Issue by singingwolfboy** [mitodl/micromasters#2299]
"Do Not Track" is a proposal to allow users of the web to express their preferences regarding tracking and analytics in a universal way. If users do not wish to be tracked, they configure their web browser to send a `DNT: 1` header when requesting web pages. It is up to each individual website to respect or ignore this `DNT` header, but respecting the user's stated preference is the right thing to do. See http://donottrack.us for more info.

Our website doesn't currently respect the user's "Do Not Track" preference: we load Google Analytics on every page, regardless of whether the user wants it or not. (Google Analytics does _not_ respect "Do Not Track", and if it is loaded on the page, it will track users regardless of whether the user has sent the `DNT` header.) We should detect this header, and not load any tracking or analytics code on the page if the user has opted out.

There is an implementation of this feature in #2280. This feature is also relevant to #2211, and any other features involving tracking and analytics.

**Comment by aliceriot** [comment]
We'll need to handle both the GA code we insert into our django templates and the `react-ga` package we use for sending events from the react app.

**Comment by aliceriot** [comment]
( I think we can just put a conditional in the `sendGAEvent` function in `lib/google_analytics.js` )

**Comment by singingwolfboy** [comment]
It looks like this is one of the [well-known URIs](http://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml). This list of URIs is managed by [IANA](https://www.iana.org/), the Internet Assigned Numbers Authority -- this is the group responsible for the global DNS system [(see wikipedia)](https://en.wikipedia.org/wiki/Internet_Assigned_Numbers_Authority). The [EFF](https://www.eff.org/) (Electronic Freedom Foundation) registered this URI in August 2015, and it appears to be a place where website operators can indicate their compliance with the "Do Not Track" policy. Check out https://www.eff.org/dnt-policy for more info.

Presumably, the EFF are running a spider that crawls sites to see which ones indicate that they are compliant with "Do Not Track", and it requests this URI to make that determination.

**Comment by pdpinch** [comment]
closed by #2280
