### ISSUE TITLE
Look at skeleton commit and update cookiecutter-django accordingly

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#23]
I'd like to include the webpack stuff, and there are a bunch of other minor tweaks that are important too

**Comment by pdpinch** [comment]
@noisecapella looks like this is in progress already?

**Comment by noisecapella** [comment]
Yes: https://github.com/mitodl/cookiecutter-djangoapp/pull/26

**Comment by pdpinch** [comment]
Since mitodl/cookiecutter-djangoapp#26 has merged, can I close this?

**Comment by noisecapella** [comment]
Sure, I'll close it
