### ISSUE TITLE
Learner Search: guard against null profile properties

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#2303]
It is possible that profile properties of indexed profiles are null for various reasons (bugs that allow those profiles through, old profiles not having newer required fields filled out). The search rendering should be defensive against this so that profiles with some fields blank don't cause the whole page render to fail.

**Comment by aliceriot** [comment]
I think Amir's pr will fix one small part of this: https://github.com/mitodl/micromasters/pull/2287

**Comment by noisecapella** [comment]
Mentioned this to @rhysyngsun already but we should make use of the  Elasticsearch mock in `LearnerSearchPage_test.js` to assert that an empty profile will not cause problems during rendering
