### ISSUE TITLE
Coupons: adjust prices

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2320]
Part of #2158

The course price API should factor in coupons in calculating the price for the user, and this price should be used in the checkout API.

Coupon cost calculation logic is still TBA

**Comment by pdpinch** [comment]
Should this issue include the changes to the dashboard, or is it limited to the API?

**Comment by noisecapella** [comment]
This is limited to the API, I'll look into making another issue for the frontend

**Comment by noisecapella** [comment]
Closing in favor of #2325
