### ISSUE TITLE
Coupons: Order summary page

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2328]
Part of #2158 
https://projects.invisionapp.com/share/NB7VM1GSG#/screens/213871767

The Pay now/Enroll now button will now direct you to an order summary page:

 - The button on the order summary page will direct the user to the Cybersource page or edX as before depending on the type of program.
 - If a coupon is being applied it should show up here to inform the user of the discount

The URL after the part that says "Clicking below will link outside of the MIT MicroMasters app"... should not be included

**Comment by pdpinch** [comment]
@noisecapella is this a duplicate of #2260 or an enhancement to it?

**Comment by noisecapella** [comment]
Yes, it looks like it's a duplicate

**Comment by noisecapella** [comment]
Closing, duplicate of #2260

**Comment by pdpinch** [comment]
Should this be closed if #2454 hasn't been merged yet?

@annagav @noisecapella
