### ISSUE TITLE
Exams: Create ExamProfile records for learners who are in an eligible course or have taken one in the past

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#2332]
This builds on the work from #1795 which syncs profiles for users who have an `ExamProfile` record. We need to create those records in the following situations:

 - [ ] Leaner enrolls in a course that has a value in `Course.exam_module`
 - [ ] Command to backpopulate Learners that have met the above condition in the past

Open Question:

- [ ] How do we want to handle users that don't have a valid profile from a Pearson sync perspective? _I would suggest just creating the `ExamProfile` record and validating/marking it invalid on our end before the sync. That way we can backpopulate once and then flag which profiles need to get fixed and take actions accordingly._

**Comment by pdpinch** [comment]
How is this different from #2077 ? Is it possible that PR #2331 is actually addressing this instead of #2077 ?

**Comment by rhysyngsun** [comment]
Not needed, closing.
