### ISSUE TITLE
Coupons: hide financial aid options if user has a 100% off coupon for whole program

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2334]
Part of #2158 

For 100% off coupons for a program we need to:
- [ ] change the user-coupon attachment code to additionally skip financial aid
- [ ] Change the UI to omit whatever messaging we have that the user skipped financial aid
- [ ] need a way to skip the financial aid step on the user's behalf

**Comment by pdpinch** [comment]
@ferdi I think this is a nice to have, but in the meantime DEDP can explain to JPAL and Pearson pilot users what to do.
