### ISSUE TITLE
Coupons: Pay now should become Enroll now, when the price is $0

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2335]
When the price is $0 (i.e. 100% off), pay now should become enroll now

Button should also now include the price. See:
https://projects.invisionapp.com/share/NB7VM1GSG#/screens/213871691

**Comment by pdpinch** [comment]
This is still under discussion. I'm going to move this to "in design"

**Comment by roberthouse54** [comment]
My thinking was that we should change all the buttons from saying "Pay Now - [cost]" to "Enroll Now" regardless of the price. This is part of what I suggested we do as a part of https://github.com/mitodl/micromasters/issues/2072

**Comment by pdpinch** [comment]
Let's discuss on [Invision](https://invis.io/2CA5TKEMA#/215596626_Personalized_Pricing)

**Comment by roberthouse54** [comment]
Closing this in favor of https://github.com/mitodl/micromasters/issues/2467
