### ISSUE TITLE
Exams: validate profile before syncing to Pearson

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#2339]
To cover profiles that already exist in production, we should validate the data before we send to Pearson and if they're invalid mark them as such. We probably want to at least display a message on the dashboard and possibly email them.

Particularly, all the following fields need to be filled out and fall within the CP-1252 character set:

- `first_name`
- `last_name`
- `email`
- `address`
- `city`
- `state`
- `country`
- `postal_code`
- `phone_number`

As a special case, `first_name` and/or `last_name` can be outside the CP-1252 character set, however, `romanized_first_name` and `romanized_last_name` need to have values and within the CP-1252 range.

If a profile is invalid when we go to export it, set its `ExamProfile.status` value to `ExamProfile.PROFILE_INVALID`.

**Comment by rhysyngsun** [comment]
I'm only slightly hesitant for the email due to users who already passed and we credit with a coupon suddenly getting an email about a bad profile. That might be a bit weird.

**Comment by pdpinch** [comment]
I removed the email requirement. We can address that in a separate issue.

**Comment by pdpinch** [comment]
@annagav if you've started this, please move it to "In Progress"
