### ISSUE TITLE
Investigate cause of searchkit pagination bug

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#2340]
Bug issue: #2336 
PR to fix: #2337 

We'll want to be sure about why/when this issue appeared before we potentially open a PR on searchkit's end or have a post-mortem

**Comment by noisecapella** [comment]
One unresolved question is why this didn't appear before we switched to yarn install. Was there a change of behavior in some lodash dependency actually being used? It would be nice to get an answer to that, just to get a better understanding of how these dependencies actually work

**Comment by pdpinch** [comment]
Can we get a brief description of the problem? I've read through the slack warroom, but I don't totally understand. Also, those Slack messages may not last as long as it takes to get searchkit fixed.

**Comment by pdpinch** [comment]
I'm going to close this, since I don't think there's enough info here to act on. If either of you disagree, please write out some more details and re-open this.
