### ISSUE TITLE
Coupons: coupon messaging

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2355]
Part of #2158 
https://projects.invisionapp.com/share/NB7VM1GSG#/screens/214035463

### acceptance criteria:
- [ ] If a coupon applies to a course or a run, we should display a message regarding the coupon below the row in the dashboard, like in the mockup.
- [ ] If a coupon applies to a program, we should display the message in place of the financial aid card, which should disappear due to #2334

**Comment by pdpinch** [comment]
This is in progress.
