### ISSUE TITLE
Infinite loop on order receipt page after purchasing a course

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2359]
When working on a coupon issue I ran into this bug where the browser hung due to infinite stack. From the stack trace it looks like `CourseDescription` is involved and `react-router` too, but I haven't done much more investigating yet. 

Note:
 - this shouldn't affect order fulfillment, just the order receipt page showing correctly
 - I haven't been able to reproduce this on micromasters-rc, so it might not be an issue in production

![screenshot from 2017-01-13 17-37-27](https://cloud.githubusercontent.com/assets/863262/21948110/f823ec4c-d9b6-11e6-8a49-afa716827cf1.png)

**Comment by pdpinch** [comment]
We've had two users message us in ZenDesk after they (successfully) completed an order, but their dashboard didn't update.

**Comment by noisecapella** [comment]
Ok, I'll investigate a fix
