### ISSUE TITLE
Change Micromasters to MicroMaster’s

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#236]
Officially, MicroMaster's should be mixed case, ending with an apostrophe s. When possible we will use a curly quote, ’

From Erdin:
> Got the guidance from MIT News Office: the right way to spell is MicroMaster's.  With an apostrophe.

A few questions to resolve:

- [ ] Should the logo be updated?
- [x] Straight apostrophe, or "smart" apostrophe? ' or ’

**Comment by pdpinch** [comment]
We are waiting for a final determination on spelling from Erdin.

**Comment by pdpinch** [comment]
Erdin says that it's definitely "MicroMaster's" (mixed case, with apostrophe). 

I'm double-checking on the logo, and we can decide ourselves about straight vs. curly-quote.
