### ISSUE TITLE
Change the run for an order

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2360]
A learner had enrolled in a past run of a course and paid for it accidentally when they intended to pay for the next offering of the course. 

@noisecapella is there a way to modify an order to change which run it's associated with?

Re: [ZenDesk #5017](https://odl.zendesk.com/agent/tickets/5017)

**Comment by noisecapella** [comment]
You just need to change the course key in the connected `Line` object. We have this disabled in the Django admin but we can still do this in the Django shell. We should use `order.save_and_log(...)` to ensure that this change is saved in the audit table

**Comment by pdpinch** [comment]
Thanks George. I made the change as you recommended.
