### ISSUE TITLE
Limit the number of times celery will attempt to connect with a bad token

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2383]
Sometimes the OAuth token we store for users will stop working and edX will return a 401 error when we periodically update a user's enrollmentCache, certificateCache and gradeCache. When the user actually logs in to the portal, this issue is fixed when they reauthenticate. But until that happens, we generate thousands of 401 errors in our logs whenever celery runs the cache updates. See issues like #2101, #2099, #2132). 

To mitigate this, we can keep track of failed attempts, and skip the celery update after the failures have gone over a threshold of 3 attempts. 

We should continue to raise exceptions for the initial failures. And we should log whenever a cache update is skipped because the failure count is over the threshold. We may want to periodically look at this numbers to help understand the root causes of this problem. 

### acceptance criteria
- model for tracking the errors
- increment error count when celery tasks encounter a 401
- reset the error count when celery successfully authenticates
- reset the error count when the user successfully authenticates
- log anytime a task a skipped because the error count is too high
- continue to raise an exception on initial failures (so we are alerted to any new, systemic problems)

**Comment by pdpinch** [comment]
@giocalitri does this make sense as a partial solution to #2132 ?

**Comment by giocalitri** [comment]
I think that the only thing missing is that when the user re-authenticates, we need to reset the count. We should do the same if a celery attempt prior the 3rd failure is successful.

**Comment by pdpinch** [comment]
I added acceptance criteria, including resetting the count.

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/190336611/

**Comment by pdpinch** [comment]
I spoke to @ferdi about this, and he is concerned that our data for searches will be incorrect as long as this is true. He made the case for working more on determining the root cause instead of quieting the notifications.

**Comment by pdpinch** [comment]
We implemented a limited case of this for freezing grades in #3488

**Comment by giocalitri** [comment]
A possible implementation of sound be something resembling what we have done for the grade freezing.

The idea is that in the celery tasks that refresh the cache, whenever the call to refresh the user's access token fails with a 401, we increase a counter associated to the user inside redis.

Still in the celery tasks, when we select the users for which we want to refresh the cache, after the selection we need to exclude all the users that have a number of previous failures greater than 3 (or whatever is acceptable).

The last part is to add some code in the login pipeline of the python social auth to reset the counter to zero (or remove completely the entry for the user from redis) whenever the user logins again and consequently regenerates the refresh token.

The only possible complication to this is to implement an efficient data structure in redis easy to update with the number of failures and, at the same time, easy to use when we need to select the users that reached the limit of failures.
One easy solution is to use one entry per user that has a key like `user_401_failure_<user_id>` and value the number of failures.
This is really efficient for updating the number of failures, but it will require to scan all the entries the a key like `user_401_failure_*` to select the user ids to exclude.

**Comment by noisecapella** [comment]
He's not around anymore but I'm wondering, why store this in redis instead of the database? If it's a field in the database we can use a filter to eliminate the user from the ones we are considering

**Comment by pdpinch** [comment]
I don't recall. @annagav or @blarghmatey do you know?
