### ISSUE TITLE
Replace city/state/country fields with geosuggest field for education & employment

### ISSUE THREAD

**Issue by singingwolfboy** [mitodl/micromasters#2384]
Follow-up from #2135. We implemented a geosuggest component with Google Places API integration in #2167, but removed the UI in #2305. It would be nice to use this component in places where we really only care about city, state, and country, such as the education form and employment form. This change was reverted for the personal form because, in order to register users for a Pearson exam, we need to know their address all the way down to street address and apartment number. However, we don't need this precision for education and employment.

Here's a mockup of what this might look like:
<img width="748" alt="school typeahead" src="https://cloud.githubusercontent.com/assets/132355/22112459/ffa54f96-de30-11e6-860a-d59800f3ff7d.png">

**Comment by singingwolfboy** [comment]
Even though this feature is an enhancement, I added the "tech debt" label because it _also_ resolves the debt of having unused code in our codebase.

**Comment by pdpinch** [comment]
We tried to make this work with our existing data model, but Google's API and our database of states/territories weren't compatible.
