### ISSUE TITLE
The requests to edX that contain the username should use the proper one

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#239]
Currently we assume that the local username on micromaster is the same we have on edX.

This might not be the case in some edge situations. The solution is to pull the edX username from the `User social Auth` model. The right field is `uid`.

**Comment by noisecapella** [comment]
:+1: I keep running into this locally and it will be painful to deal with in production

**Comment by giocalitri** [comment]
in production is unlikely until we will support multiple edx instances (I know we heard we will not, but you know how these things go :-P )
