### ISSUE TITLE
Google Conversion iframe has added a space at the top of the page

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2390]
The iframe containing the Google Leads conversion frame has added a space at the top of the page (above the micromasters navbar). See screenshot below:

![image](https://cloud.githubusercontent.com/assets/20047260/22118503/12d989dc-de46-11e6-8155-23af5c918465.png)

**Comment by pdpinch** [comment]
@amir-qayyum-khan can you take a look at this?

1. Why does adwords remarketing require an iframe?
2. Can we put it someplace else?

FYI @ChrisLanfranco

**Comment by pdpinch** [comment]
@roberthouse54 do you know if this is on every page? One solution would be to remove the remarketing tag from this particular template. It's an admin view and there's no point in spending ad dollars selling MM to MIT faculty.

**Comment by roberthouse54** [comment]
It seems to be on all pages, including the marketing site. I don't know about the solution.

**Comment by amir-qayyum-khan** [comment]
@pdpinch @roberthouse54  this seem solution 
- http://stackoverflow.com/questions/11939653/google-adwords-remove-iframe-added-by-tracking-conversion-code
- http://stackoverflow.com/questions/18467529/google-remarketing-tag-iframe-height-issue
