### ISSUE TITLE
Coupons: add support for fixed price coupon

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2399]
Part of #2158

**Comment by noisecapella** [comment]
@roberthouse54 Do you know what text we should have for this? We will need to have text for the coupon notification dialog and for the coupon messaging on the dashboard

**Comment by roberthouse54** [comment]
![image](https://cloud.githubusercontent.com/assets/20047260/22442538/c2f20b0c-e709-11e6-811d-839e40f01976.png)

Coupon applied: course price set to $100

This coupon sets the price of each course in the Data, Economics, and Development Policy MicroMasters program at the fixed price of $100. 

The discount will be automatically applied when you enroll.

**Comment by roberthouse54** [comment]
I have updated this slightly:

![image](https://cloud.githubusercontent.com/assets/20047260/22472075/8762448c-e7a2-11e6-91de-be071dd6805e.png)

Coupon applied: course price set to $100

This coupon sets the price of each course in the Data, Economics, and Development Policy MicroMasters program at the fixed price of $100.

Your course prices have been adjusted accordingly.

**Comment by noisecapella** [comment]
What about for a single course?

**Comment by noisecapella** [comment]
Also what copy should we have for the dashboard messages?

**Comment by roberthouse54** [comment]
Coupon applied: course price set to $100

This coupon sets the price of the course [courseName] at the fixed price of $100. The course price have been adjusted accordingly.

**Comment by roberthouse54** [comment]
Dashboard copy

All courses are set to the discounted price of $100.
or
[CourseName] has been set to the discounted price of $100.

**Comment by noisecapella** [comment]
Do you mind if I use `This course` instead of `[CourseName]` here?
