### ISSUE TITLE
Dashboard: SCM students courses are "In Progress" after course end date

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2411]

**Comment by amir-qayyum-khan** [comment]
@pdpinch 

- On the exact end date, should we show ``In Progress`` and remove it after end date?
- It seems user is not passed or fail yet so what should we write instead of ``In Progress``? right now i just left it blank

**Comment by pdpinch** [comment]
Sorry Amir, this is a duplicate of #2412 and should not have been opened.
