### ISSUE TITLE
Set up selenium test

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2414]
We should set up a selenium test which does some minimal set of tasks, for example log in, purchase a $0 course run. This would also give us an opportunity to catch console warnings and see basic integration errors

**Comment by pdpinch** [comment]
Are you suggesting a coupon-specific test?

**Comment by noisecapella** [comment]
No, just a general test of a purchase. The $0 case is easier to test than the non $0 case since we don't have to interact with Cybersource

**Comment by noisecapella** [comment]
cc @pdpinch. I think a single test testing a $0 purchase would be a good use case. We could mock the edX part to keep it simple
