### ISSUE TITLE
Show progress spinner when enrollment is updating after cybersource payment

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2419]
After the user completes the cybersource payment page, he/she is redirected back to the dashboard. Currently, at this point, we show a progress spinner on the "Pay Now" button, while we are waiting to get the confirmation that the enrollment was successful. I feel that the current implementation, showing the spinner on the button may be confusing. We should only ever show a spinner on a button immediately after a button has been pressed.

We should change this so that the progress spinner is shown in the right column, but not on the button. We should also show text that says "updating enrollment..."

See below:

![image](https://cloud.githubusercontent.com/assets/20047260/22223059/6e58b12c-e187-11e6-8e82-1404858bb250.png)

**Comment by pdpinch** [comment]
moot, now that ecommerce is removed from this application
