### ISSUE TITLE
Exams: Production settings for Exams

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#2427]
Need to give @mitodl/devops production values for exams settings.

The following settings need production values different from the defaults, actual values to be shared through secure means:

- [x] `EXAMS_SFTP_HOST`
- [x] `EXAMS_SFTP_USERNAME`
- [x] `EXAMS_SFTP_PASSWORD`
- [x] `EXAMS_SSO_CLIENT_CODE`
- [x] `EXAMS_SSO_PASSPHRASE`
- [x] `EXAMS_SSO_URL`
- [x] `FEATURES_PEARSON_EXAMS_SYNC`

**Comment by pdpinch** [comment]
Don't we also need to set the exam name on the program and the exam modules on the courses?

**Comment by pdpinch** [comment]
@rhysyngsun I think some of this is done, if not all of it?

**Comment by rhysyngsun** [comment]
@pdpinch all but one, updated to reflect that
