### ISSUE TITLE
Coupons: handle messaging for course run coupons

### ISSUE THREAD

**Issue by singingwolfboy** [mitodl/micromasters#2440]
#2392 only addresses messaging for program-level coupons and course-level coupons. When a user attaches a coupon at the course run level, the app should show a confirmation message explaining what the coupon applies to. This will require writing some copy and figuring out the best way to explain to the user what a "course run" is.

**Comment by pdpinch** [comment]
I don't think we have a use case for course-run coupons yet. We can keep this in the backlog until we do.

**Comment by noisecapella** [comment]
Closing for #3157
