### ISSUE TITLE
Not all static assets are served from Cloudfront

### ISSUE THREAD

**Issue by shaidar** [mitodl/micromasters#2462]
Static assets called from [here](https://github.com/mitodl/micromasters/blob/73926efeb12dd7033d8f8e07f43cb7275885872f/static/scss/homepage.scss) are still being served through micromasters as opposed to Cloudfront. This can be verified and tested in Chrome Developer Tools under Sources. 
![screen shot 2017-01-31 at 10 33 18 am](https://cloud.githubusercontent.com/assets/1447295/22471571/bd868af2-e7a0-11e6-9a52-a39fccf90b7d.png)

**Comment by pdpinch** [comment]
It looks like that includes the hero image: 

https://github.com/mitodl/micromasters/blob/73926efeb12dd7033d8f8e07f43cb7275885872f/static/scss/homepage.scss#L162

**Comment by noisecapella** [comment]
Some related issues: #1922 and #1941
