### ISSUE TITLE
Format price to account for cents

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2464]
We need to adjust the `formatPrice` function to round to the nearest cent, or leave off the cents entirely when it's a whole number

**Comment by pdpinch** [comment]
Would this affect form inputs, or just display? See #2470

**Comment by singingwolfboy** [comment]
I recommend using [`decimal.js-light`](http://mikemcl.github.io/decimal.js-light/) where it makes sense to do so. We're already using this library in our codebase.
