### ISSUE TITLE
Refactor email-related front-end code

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#2468]
Our first pass at providing email functionality to users was the search result email dialog, which was not designed for reuse. Implementing the course team contact email (#2284) was a time-sensitive issue, and a large amount of code had to be duplicated in order to make things work quickly. Any new use cases we will have for sending emails will need a similarly large-scale duplication. We should look into implementing email functionality  via composition ([example](https://facebook.github.io/react/docs/higher-order-components.html#convention-maximizing-composability))

**Comment by gsidebo** [comment]
Here are some extra technical details: My general plan is to create a higher-order component like the [example link](https://facebook.github.io/react/docs/higher-order-components.html#convention-maximizing-composability) above. It would be called something like `withEmailDialog`. It would take a component that needs a dialog (such as `DashboardPage`), and would return that same component with email dialog functionality. `withEmailDialog` would take care of the behavior and state changes for normal email dialog behavior (closing, validating subject/body inputs, sending, etc). The original component (`DashboardPage` in my example) would still handle dispatching the actions to open the dialog.

Here's a very rough psuedo-code outline:
```
// DashboardPage.js

class DashboardPage extends React.Component {
  openCourseContactDialog(course: Course, canContactCourseTeam: boolean) {
    if canContactCourseTeam
      startEmailEdit({type: COURSE_TEAM_EMAIL, ...})
      setDialogVisible(COURSE_TEAM_EMAIL)
    else
      setDialogVisible(COURSE_CONTACT_PAYMENT_PROMO)
  }
      
  render() {
    return (
      //...
      <CourseRow openCourseContactDialog={this.openCourseContactDialog} ... />
      //...
    )
  }
}

export default compose(
  connect(mapStateToProps),
  withEmailDialog({
    type: COURSE_TEAM_EMAIL,
    title: "Contact the Course Team",
    sendFuncton: api.sendCourseTeamEmail
    ...?
  })
)(DashboardPage);
```

@noisecapella @aliceriot let me know if you see anything that should be tweaked here

**Comment by aliceriot** [comment]
That generally looks like what we want to do! One thing to keep in mind is that HOCs primarily add functionality by wrapping existing components, and passing down props, not by modifying the components they wrap. So you would need to refactor `DashboardPage` and the other components which have email functionality now (`LearnerSearch`, right?) to expect the relevant functions as props, not as instance methods (`this.foo()`). If that makes sense?

One other minor suggestion is that we create a new directory to put these in. I'm hoping to do a similar refactor to get rid of `ProfileFormContainer` and `ProfileFormFields` too - it would be good to have a single place to keep them all! Maybe `static/js/HOCs`, or `static/js/containers/HOCs`, hmm, I don't really like `HOCs` as a directory name but `hocs` looks weird, and they're not really mixins...

Maybe just `static/js/higher_order_components` ?

**Comment by aliceriot** [comment]
@gsidebo are you working on this?

**Comment by gsidebo** [comment]
i am. i'll move to ready. agreed on not modifying the original component, and i'll look into functionality that should be passed from the HOC to the containers as props. there is some dialog-only functionality like updating/validating input fields and canceling out of the dialog that the container components don't need to worry about. i'll also look into possibly creating a separate directory

**Comment by aliceriot** [comment]
👍
