### ISSUE TITLE
Show teaser dialog when user has not paid and attempts to contact course team

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#2469]
In an effort to move things along and keep the PR more manageable, #2284 was done without the modal that we want to show users who haven't paid for a course and want to contact the course team ([link to the dialog design](https://github.com/mitodl/micromasters/issues/2284#issuecomment-274866731)). The work for this issue will be to implement that dialog.

**Comment by gsidebo** [comment]
fyi @pdpinch. i moved this straight to Ready

**Comment by pdpinch** [comment]
@gsidebo please let me or Ferdi do that. I would have moved it to ready, but I'd but it below some other things.

**Comment by pdpinch** [comment]
@gsidebo have you started this?

**Comment by gsidebo** [comment]
@pdpinch sorry, i totally missed these messages. the PR is up now
