### ISSUE TITLE
Personal Pricing: validate income so it can only be an integer

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2470]
Currently the income field in the personal pricing calculator doesn't allow users to enter decimals. Some users haven't noticed this and ended up entering an income that is 100x what they meant to enter. For example, they type "12345.76" but the input field rejects the period and they end up submitting "123476"

The input field also rejects commas, which could lead to a similar outcome if the user is from a region where commas are used as a decimal separator. I haven't heard from any users who have made this error. I think we should continue to reject commas in the input field.

**Comment by amir-qayyum-khan** [comment]
so what should we do here?
- alert user on pressing decimal?
- allow user  to add  decimal then convert it to integer on focus out or submitting to api

@pdpinch

**Comment by pdpinch** [comment]
Sorry, we had discussed this at planning but I didn't update the issue. 

Anything other than an number should cause a validation error, "Please only use whole numbers."
