### ISSUE TITLE
Jumbled financial aid dialog on mobile device

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2474]
![screenshot_20170201-120421](https://cloud.githubusercontent.com/assets/863262/22517812/6613cc5c-e878-11e6-9520-95f1c90f49d7.png)

**Comment by roberthouse54** [comment]
A few points on this layout for mobile:

- Decrease the passing in the modal
- Decrease the font size and line height of the Checkbox text. Also, remove the left/right padding of the checkbox element.
- The income field, and the currency input field should both be full width, one on top of the other
- Skip this and pay full price should be on a separate line ABOVE the buttons.
- If the content of the modal is too much to fit vertically, the modal should scroll.

**Comment by pdpinch** [comment]
Similar things can happen in the viewport is very short on a desktop browser.

**Comment by noisecapella** [comment]
If I enter text in the income text field and then clear it, the dialog moves such that I'm able to proceed:

![screenshot_20170317-144608](https://cloud.githubusercontent.com/assets/863262/24058424/6c68f5f2-0b21-11e7-89ec-def091c5bf9e.png)
![screenshot_20170317-144616](https://cloud.githubusercontent.com/assets/863262/24058425/6c69051a-0b21-11e7-9fc2-98ae7dc8afa3.png)
![screenshot_20170317-144622](https://cloud.githubusercontent.com/assets/863262/24058426/6c693904-0b21-11e7-9137-3522e40ec2ff.png)

**Comment by roberthouse54** [comment]
I think this still makes sense to proceed as I said above. The main issue is that we need to make sure that content in the modal can scroll and not cover the buttons. But the other issues I mentioned should also be fixed.
