### ISSUE TITLE
Pay button oddly located on mobile device

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2475]
![screenshot_20170201-120352](https://cloud.githubusercontent.com/assets/863262/22517844/8230974e-e878-11e6-826c-c60f0939893a.png)

**Comment by pdpinch** [comment]
We're going to make some changes to this button in #2481 -- maybe we can just review this when we're working on that?

@roberthouse54

**Comment by roberthouse54** [comment]
That makes sense. The button layout in this case, should be centered. We should also add more top/bottom padding to the course-container element for the mobile view. (See below)

![image](https://cloud.githubusercontent.com/assets/20047260/22562251/bc80ab88-e949-11e6-908b-c403c157bd50.png)

**Comment by roberthouse54** [comment]
Closed by #2897
