### ISSUE TITLE
Add a search box to the learner search page to find a specific user

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2479]
The design implements the standard searchkit implementation of this: as the user types, the results are filtered in real time. We will highlight the typed letters in the search results. We do not need an "x" icon to clear the search term. 

Typed searches should just match the beginning of a name, either first or last name, but should not match a string inside of a name. (For example, typing "zabet" would not match "Elizabeth".) But we can also choose to test this and see which implementation "feels" correct, given it is not too much work. 

As part of this issue, we will also replace the "Sort by" dropdown with sorting by clicking on column headers, as shown.

One small note about the implementation: on the searchkit demo of this that I have seen, the entire matching name is highlighted, as opposed to the typed string, which may be a portion of the name. I would prefer to highlight only the matching string, but if this is difficult to do, we can highlight the entire word.

See mock below:

This closes #2050

![image](https://cloud.githubusercontent.com/assets/20047260/22524845/e3e77510-e892-11e6-8e99-62bf8b4a66af.png)

**Comment by pdpinch** [comment]
The sorting requirements has been broken out into another issues, #2632
