### ISSUE TITLE
Add invoice tracking to coupons

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2489]
We will sell batches of coupons to corporate and foundation partners. We need to keep track of who paid for each coupon and under which invoice. 

We can add a customer and invoice number at creation time (or afterwards, via django admin, if necessary). 

We will also need a way for finance staff to view how many coupons have been used per invoice, for billing purposes. This will be addressed in a separate issue.

**Comment by noisecapella** [comment]
How about a `CouponBatch` model with text fields and a one to many relationship to `Coupon`? `CouponBatch` can have an invoice number field and a text description field with more information

**Comment by pdpinch** [comment]
That sounds reasonable. I was wondering if we might need to normalize the customers, but with a `CouponBatch` model we can add that later if/when we need it.
