### ISSUE TITLE
Validation for price + financial aid

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2497]
We should have a management command to assert that all prices are present and equal to each other for a financial aid program, and that no financial aid discount causes the price to go lower than $0. We should also assert that no price or financial aid discount is negative

**Comment by pdpinch** [comment]
I do want to avoid this situation. When would we run the management command?

**Comment by noisecapella** [comment]
After a release, or before making a program live? It would also be useful for PR builds and testing seed_db
