### ISSUE TITLE
add redirect for /favicon.ico

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2502]
Another one of our most common 404s reporting in cloudfront is requests for /favicon.ico. We should redirect requests for it to /static/images/favicon.ico

**Comment by pdpinch** [comment]
I would suggest doing this in nginx config, but there may be other ways to implement it.

**Comment by rhysyngsun** [comment]
If the url that's failing is going to cloudfront, wouldn't the redirect need to be there? cc @mitodl/devops

**Comment by blarghmatey** [comment]
No, because Cloudfront will first try to retrieve the asset from the origin server, so if it encounters a redirect then it should follow that to retrieve the requested asset.
