### ISSUE TITLE
Fix bare exceptions on grades/api.py

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2503]
For the cases where we reraise the exception we should connect the original exception with the new one using the syntax `raise FreezeGradeFailedException(...) from ex`

**Comment by pdpinch** [comment]
Is this going to affect our ability to be aware of correct exceptions in production?

**Comment by noisecapella** [comment]
If we add the `from ex` syntax it would give us a more detailed stack trace than we have currently
