### ISSUE TITLE
Learners Search for Learners

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2512]
As a learner, I would like to find out more about other learners in my program and contact them individually.

The learner can browse or search for other learners. The UI is the same as the instructor search except that it doesn't include all of the facets, nor the ability to send bulk e-mail. This results shown needs to respect the learner's setting for whether their profile is shared with other learners. If they are set to not be shown, they will not appear in the list. Learner search will be available to all users. The results will list only users who have paid or enrolled in at least one course.

Users should be able to view other users' profiles. This page should look the same as the profile when viewed by faculty, except we will not display the user's email address, and we will display the user's current location. At the top of the profile will be a link to "Send a Message". (see #2196)

### Acceptance Criteria:

- [ ] no ability to send bulk e-mail
- [ ] results are limited to users who have opted to share their profile with other learners in their program, or with the world
- [ ] results are limited to users who have pair or enrolled in at least one course in their program(s)
- [ ] the search interface is available to all users
- [ ] all facets listed below

### Related Issues:

- #2196 : Learners should be able to e-mail other learners. The ability to send emails will be behind a paywall.
- As a follow up to this issue, we will add a card to the dashboard called "Learners in this Program". This card will link to the Learners Search page. This is a issue #2516
- We need a way for users to navigate to this page. See: #2564 

We will display the following search facets (we will not include facets for grade or payment status):
Course
Semester
Current Residence
Country of Birth
Company
~~Number of courses passed~~

![learner_search_for_learners 2x](https://cloud.githubusercontent.com/assets/20047260/22667009/dba93ace-ec88-11e6-9e73-067a562715f1.png)

![image](https://cloud.githubusercontent.com/assets/20047260/22707246/2e034ba4-ed40-11e6-94c6-6b4d5ad4be7b.png)

**Comment by pdpinch** [comment]
I added some acceptance criteria, which are just a list version of Rob's description.

**Comment by rhysyngsun** [comment]
Moved this back to ready because I'm taking care of #2690 as a prerequisite.

**Comment by rhysyngsun** [comment]
@pdpinch @roberthouse54 where were we expecting this to live url-wise? /learners is where the current staff search lives.

**Comment by pdpinch** [comment]
How much trouble do we get into if this is at the same URL?

**Comment by rhysyngsun** [comment]
@pdpinch @roberthouse54 I'm nearing finalization of my PR for this and just noticed that the mockup and the list of facets we want to show differ. Which is the correct list?

If it's the list in the description, do we really want to display # of courses passed? That seems like private information.

**Comment by pdpinch** [comment]
I spoke to Rob and confirmed this is the same "number of courses passed" facet as in the staff view. Let's drop it for now until we decide on access control.
