### ISSUE TITLE
Learners in this Program card on Dashboard

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2516]
This is a simple card on the dashboard that shows a grid of user photos, with a View All link that goes to the Learner Search page.

This design is dependent on the Learners Search for Learners issue #2512.

### acceptance criteria

- [ ] This should be behind a feature flag for now

![learners_in_program_card 2x](https://cloud.githubusercontent.com/assets/20047260/22704151/a6803da0-ed34-11e6-9129-311f2869dbaa.jpg)

**Comment by pdpinch** [comment]
How do we choose which learners to display? Can it always be the same same set (perhaps, the first 8 in the program query) or do you want some randomness? Or something else?

**Comment by roberthouse54** [comment]
I would prefer a) users with photos b) randomized

**Comment by pdpinch** [comment]
This can be worked on as soon as #935 and #2196 are done.

**Comment by annagav** [comment]
@roberthouse54, are the images also links to view profile?

**Comment by roberthouse54** [comment]
Yes, let's do that if it's not a problem.
