### ISSUE TITLE
When a role like staff is assigned to the user, a reindex is not triggered

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#2521]
We add a signal to the Role Model so that every time we assign a staff role to a given user, the user gets reindexed and it disappears from the search result.

This is a very minor bug given the amount of users with staff role.

**Comment by pdpinch** [comment]
What does it do currently? Just remove the staff the next time there is a reindex?

**Comment by giocalitri** [comment]
Yes, it does not reindex until the user changes the profile or anything that currently triggers a reindex.
