### ISSUE TITLE
Come up with better solution for the searchkit/search result email bug

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#2527]
Our fix for the critical search result email bug (#2518) is functional, but there are a couple issues with the fix: (1) it puts a complex object into the Redux store, [which is strongly advised against](http://redux.js.org/docs/faq/OrganizingState.html#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state), and (2) we still don't have complete confidence that our new method of getting the 'active' query from searchkit is correct in all cases. To be more specific regarding (2), the new method we're using does not work as expected when it is run upon the opening of the dialog. It _does_ work when the send button is clicked. 

Essentially we are still open to future bugs until we understand more about the `searchkit` object and make use of the Redux store in a more idiomatic way

**Comment by noisecapella** [comment]
@gsidebo I'll take this on, it's intersecting with my test problem
