### ISSUE TITLE
Coupons: reset financial aid if user has a 100% off coupon for whole program

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2532]
in #2334 we hid the financial aid options for users who apply a 100% off coupon, but we (apparently) didn't address the case where the user had started the financial aid process and was in one of the states that blocks them from paying (e.g. "pending-docs"). 

This results in the user seeing the "Pay $0" button but it's greyed out. 

![problem](https://cloud.githubusercontent.com/assets/430126/22788035/57d21c22-eeac-11e6-8fea-eabe0f550476.PNG)

A possible solution would be to set the financialaid status of these users to `reset`

**Comment by pdpinch** [comment]
@noisecapella can you take a look a this?

**Comment by noisecapella** [comment]
We currently check `has_user_applied` to see if we should automatically skip financial aid for the user. Instead we should be more specific and check all statuses which aren't already approved or skipped
