### ISSUE TITLE
Exams: HTML edits to exam card on dashboard

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2553]
1. Change the card title to "Final Proctored Exam"
2. Change the text `any Pearson test center` to `any authorized Pearson test center`
2. Change the link for the text `authorized Pearson test center` to be http://www.pearsonvue.com/mitx/locate/
 

See https://github.com/mitodl/micromasters/blob/master/static/js/components/dashboard/FinalExamCard.js#L34-L40

**Comment by pdpinch** [comment]
Please check with @robhouse before working on this.

**Comment by roberthouse54** [comment]
Can we also change the card title to "Final Proctored Exam" per Anna Shrimpf's request?

**Comment by pdpinch** [comment]
I updated the description and I'll move this to ready.
