### ISSUE TITLE
Financial Aid: skip and pay full price button does nothing

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2554]
Two users have written in about problems with "Skip and Pay Later." I've been able to reproduce the issue in production, but not on micromasters-rc. 

Steps to Reproduce:

1. Enter your financial aid information so that you are in the state "pending-docs"
2. Click "Skip and Pay Full Price"
3. Click "Pay Full Price" on the confirmation dialog

Expected behavior:

XHR request is sent to PATCH /api/v0/financial_aid_skip/2/
Spinner appears
After the API responds, dashboard update with full-price course prices

Actual behavior:

Nothing happens. No request is sent. No JavaScript errors appear in the console, or in Sentry.

**Comment by pdpinch** [comment]
This appears to be working in production again. Something changed between 0.46.1 and 0.46.2 but I have no idea what it could be. 0.46.2 was a relatively small release, and there was nothing obvious that affect the front end.

**Comment by pdpinch** [comment]
@noisecapella @aliceriot could I get your opinions on this before I close it?

**Comment by noisecapella** [comment]
No idea, if it's not in Sentry I'm not sure what it could be

**Comment by noisecapella** [comment]
One thought, did 0.46.1 actually get deployed to production correctly?

**Comment by pdpinch** [comment]
What do you mean by correctly?

**Comment by noisecapella** [comment]
Did the travis build pass and did heroku deploy without errors?

**Comment by pdpinch** [comment]
As far as I can tell it did. Heroku believes the build succeeded and it won't build unless Travis passes. 

Here's the build log:

https://gist.github.com/pdpinch/99ad4bb6baf3f958fdf82218c4f97c7e

We did have that weird thing where it built twice.

**Comment by noisecapella** [comment]
I think I understand now. When @aliceriot wrote the original skip if 100% off coupon functionality, she put the code to skip in a function which checks if the user has applied or not. #2533 is part of 0.46.2 and it fixes that by checking the terminal states explicitly. Before the work was done it probably didn't check the financial aid status at all before telling the API to skip

**Comment by noisecapella** [comment]
In summary I think we can close this

**Comment by aliceriot** [comment]
yea looks like it.

**Comment by pdpinch** [comment]
Serendipity! =)
