### ISSUE TITLE
Coupons: Look for CachedEnrollment instead of CachedCertificate when checking if a user paid on edX

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2561]
This affects the `discounted-previous-course` coupons

**Comment by amir-qayyum-khan** [comment]
can you point out code where we need to change this, it seems MMtrack need to change

**Comment by rhysyngsun** [comment]
@pdpinch question for you: should a `discounted-previous-course` coupon be valid for a verified enrollment in an active `CourseRun`? I ran into this testing, but it was an artificial situation since I took a shortcut by marking my enrollment in the active `CourseRun` as verified.

**Comment by rhysyngsun** [comment]
Answer: not a situation we'll see in production
