### ISSUE TITLE
Add Navigation - Sidebar

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2564]
The goal of this issue is to add a navigation drawer (sidenav) that will be available on all pages in the app, on both desktop and mobile. The sidenav will have links to all pages, including the links that are currently in the user dropdown into the side nav. The "context switcher" will remain in the topnav, but move to the right side where the user dropdown is now. For mobile devices, the context switcher will be in the sidenav (as it is now).

The sidenav, when open, will cover the content on the page. The menu icon will open and close the sidenav. A chevron arrow will close the sidenav, or swiping left will also close the sidenav.

Staff users, faculty and other admin users who have links to admin pages, we see links to those pages above the "My Profile" link.

_In the future we may change this so the sidenav will be open by default if the device is wide enough to have it be open without covering the content of the page._

![navigation_new 2x](https://cloud.githubusercontent.com/assets/20047260/22991304/d082f5ce-f389-11e6-87c5-b9c0ae255037.jpg)

**Comment by aliceriot** [comment]
@roberthouse54 do you have a mockup of what this should look like on a desktop?

**Comment by roberthouse54** [comment]
Here is the admin version of the sidenav. Links to open in new tabs. On desktop it should look as shown (for now):

![image](https://cloud.githubusercontent.com/assets/20047260/23565316/13e49794-001b-11e7-8ca7-c7d42f80c10b.png)

**Comment by aliceriot** [comment]
@roberthouse54 do you know if the icon you have for 'CMS' is a material-ui icon? I tried to find it but couldn't ;_;

**Comment by roberthouse54** [comment]
It is not. I will have to make it as a custom icon.

**Comment by roberthouse54** [comment]
No. Actually, let's switch this and use the material icon called "Description". I have updated the mock above ^^

**Comment by aliceriot** [comment]
there also isn't a material icon for that graduation hat - currently we're using the one called 'dashboard':

![dasbasdfasdf](https://cloud.githubusercontent.com/assets/6207644/23757255/4168a780-04b4-11e7-9abd-17e0ef7be689.png)

**Comment by aliceriot** [comment]
would it be ok to stick with the one we're using now?

**Comment by roberthouse54** [comment]
Yup. I think I just forgot to update my PSD. That dashboard one is fine.
