### ISSUE TITLE
Sort the learner search results by column header

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2632]
The purpose of this is to allow the user to sort columns by clicking on column headers, which is a very common pattern. This was supposed to be done as part of #2479, but we decided to move it out as a separate issue.

The default sort will be by last name. Clicking a column header will sort by that column. Clicking on a column name a second time will reverse the sort order of that column. We will remove the current sorting select method.

![e3e77510-e892-11e6-8e99-62bf8b4a66af](https://cloud.githubusercontent.com/assets/20047260/22996886/562cfb98-f39e-11e6-80d0-744a605a4af7.png)

**Comment by noisecapella** [comment]
@amir-qayyum-khan Sorry that I haven't assigned this to myself earlier, it slipped my mind

**Comment by amir-qayyum-khan** [comment]
its ok
