### ISSUE TITLE
JS code coverage doesn't match up perfectly

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2638]
We should investigate to see what the root cause is, so we can have more confidence in our JS code coverage numbers

**Comment by singingwolfboy** [comment]
I suspect this is due to [Istanbul](https://istanbul.js.org/) measuring coverage of the ES5 code coming out of Babel, rather than the ES6 code in the codebase. Switching to [`babel-plugin-istanbul`](https://github.com/istanbuljs/babel-plugin-istanbul) will probably fix this.

**Comment by noisecapella** [comment]
Ah, good catch
