### ISSUE TITLE
Final Grades: deal with users who do not get a frozen grade because of 401 errors

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#2657]
Users who do not have valid credential for refreshing current grades and certificates cannot get a Frozen Final Grade.
This results in the `CourseRunGradingStatus` never setting the status for the course run to `complete`.
We should decide if skip these users or automatically do something else.

**Comment by pdpinch** [comment]
If we skip these users, can their final grade still be updated if they view their own dashboard?

**Comment by giocalitri** [comment]
yes: as soon as they visit the dashboard, they will create a final grade sync

**Comment by pdpinch** [comment]
I think we should skip these users then, so that `CourseRunGradingStatus` can get set to `complete`

**Comment by giocalitri** [comment]
The problem is that we do not have a state that can tell us if a user is not done because there was a 401 or because the celery task died at some point, so there is no actual way currently to only skip.
I think we need to somehow flag these users so that when we reconcile the results we can take in account that we skipped these users because of a 401.
My idea would be to insert their id in a list in redis: this is doable but it will require a bit of work.

**Comment by pdpinch** [comment]
In general, I like the idea of flagging these 401 failures. Can we come up with a general-purpose approach, not just for freeze grade exceptions?

And why redis?

**Comment by giocalitri** [comment]
Yesterday I talked to Anna about a similar approach for refreshing the edx cache, but I realized that that one is probably the general approach: when we freeze the final grade we probably want something simpler because, after all, if we skip an user because we are not conservative, the user will get her final grade as soon as she visits the dashboard.

I was thinking about redis because in this case it would just be a temporary cache of user ids that we can dispose as soon as we are done with the course grade freezing.
Anyway I have no strong opinions and we can use postgres
