### ISSUE TITLE
Profile: user must fill out all steps sequentially

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#266]
- [x] All but the last tab will have 'Save and continue' buttons. The last tab will have a 'Save' button.
- [x] The continue buttons will validate only the current tab
- [x] The last save button will validate the entire profile. If there is a validation error it will redirect to the earliest tab which has the validation error.
- [x] All tabs except the last tab should patch `filled_out: false` so that we force the user to complete the profile before moving on
- [x] The last tab will patch `filled_out: true` to indicate a complete profile
- [x] #369 remove the "tab" links and replace them with progress indicator
- [x] #375 add a "previous step" button.

**Comment by noisecapella** [comment]
We decided on this UX:

 - All but the last tab will have 'Save and continue' buttons. The last tab will have a 'Save' button.
 - The continue buttons will validate only the current tab
 - The last save button will validate the entire profile. If there is a validation error it will redirect to the earliest tab which has the validation error.
 - All tabs except the last tab should patch `filled_out: false` so that we force the user to complete the profile before moving on
 - The last tab will patch `filled_out: true` to indicate a complete profile

cc @aliceriot @pdpinch

**Comment by noisecapella** [comment]
We should also PATCH `email_optin: true` in the last tab since that's where the email consent message is

**Comment by Ferdi** [comment]
Can you keep the remaining tabs disabled and only enable when the the previous tabs passes the validation ?

**Comment by noisecapella** [comment]
The main problem is that the profile is always updated as a whole but only pieces of it are validated at a time. If the user was on the second tab, they could remove some information from the first tab, go back to the second tab, click save, and the entire profile is sent while only the second tab is validated. Disabling the third tab wouldn't prevent this scenario.

Another way to solve this is to PATCH the tabs separately, but this makes the internal logic more complicated than the UX in my comment above would require

**Comment by Ferdi** [comment]
We should try hard not to compromise on usability. 

Can you emulate the traditional web apps here - keep only the current tab active and disable the rest ?  The previous tabs get enabled by an additional "previous step" button 

Side note :  what is "consent message" ?

**Comment by pdpinch** [comment]
@ferdi and I spoke. They're not tabs, they're steps in a multi-page form. Everything on George's [bullet list](https://github.com/mitodl/micromasters/issues/266#issuecomment-216885753) is correct, but in addition we'll 

- remove the "tab" links  
- and add a "previous step" button. 

The user cannot advance through the steps without clicking "save and continue" which validates, avoiding the scenario George describes in https://github.com/mitodl/micromasters/issues/266#issuecomment-216898166

**Comment by aliceriot** [comment]
by 'remove the "tab" links' do you mean get rid of the tab ui elements or remove the ability to click on them and navigate between tabs that way?

I'm personally in favor of keeping them (or something similar, e.g. 'page 1 of 3') as a visual hint to the user of approximately how much form there is left to deal with.

do we plan to keep having urls for each form section? currently there's `/profile/personal` and `/profile/professional`.

**Comment by Ferdi** [comment]
@aliceriot as you say, we should keep the "tabs" as a replacement for  "step 1/3".
