### ISSUE TITLE
Layout issues on learner search page

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2682]
This was fixed in the past, and something changed to make it come back. There is too much space above the buttons at the top of the learner search. I will wait until the new sorting by column headers is merged, then fix this along with other small style tweaks on this page.

Some other small layout/style tweaks I will address in this:

- vertically center the Company facet selector
- lighten font weight for name
- fix spacing around column headers
- make avatars smaller
- tighten row spacing
- remove the "Program Avg grade" copy in table cells.

![image](https://cloud.githubusercontent.com/assets/20047260/23264629/040fb784-f9b0-11e6-8bcd-da246cd67429.png)

**Comment by pdpinch** [comment]
@roberthouse54 was this fixed by #2688?

**Comment by roberthouse54** [comment]
Yes, sorry I forgot to close it.
