### ISSUE TITLE
Program filter is ignored for certain programs, unless there is text in the textbox

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2685]
For micromasters-rc you can see this on Digital Learning. This is also happening in production for SCM

**Comment by pdpinch** [comment]
I don't understand? I thought each program used its own index?

**Comment by noisecapella** [comment]
I don't know what is causing this yet. The index is shared by the whole site. To get a list of programs we add a filter on that program id

**Comment by noisecapella** [comment]
Might be an error specific to my user. Doing further investigating
