### ISSUE TITLE
Reset of user from financial_aid/review doesn't create a financialaidaudit object

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2687]
In testing #2656 I noticed that taking an action in the financial aid review form doesn't generate the expected financialaidaudit object. These objects are created on learner actions (e.g. creating a financial aid request) and on django admin action (e.g. changing status to "reset"), but they don't seem to be created when the financial aid review form is used. 

I believe we want this behavior to be consistent, with a financialaidaudit object generated in all cases.

**Comment by noisecapella** [comment]
I think it comes down to this line: https://github.com/mitodl/micromasters/pull/2656/files#diff-551baae83c6a12664edc88ffa0362ae7R156

It should be using `save_and_log`. Do we create financialaidaudit objects for any other changes to financial aid state here?

**Comment by pdpinch** [comment]
In my testing, it doesn't seem like any changes to the financial aid status through this ui creates financialaidaudit objects. 

@amir-qayyum-khan can you take a look at this?

**Comment by amir-qayyum-khan** [comment]
@pdpinch there is not audit functionality of these `financial_aid/review/` actions.
I added audit operation and updated the tests
