### ISSUE TITLE
Upgrade to Celery 4

### ISSUE THREAD

**Issue by singingwolfboy** [mitodl/micromasters#2696]
[Celery](http://www.celeryproject.org/) is our distributed task queue. We are currently using version 3.1, but the latest version is 4.0. According to the changelog, Celery 4 is backwards-compatible with previous versions. However, it is "a massive release with over two years of changes. Not only does it come with many new features, but it also fixes a massive list of bugs."

Upgrading to Celery 4 would probably make our task queue more durable, and squash bugs that we may not even be aware of.

http://docs.celeryproject.org/en/latest/whatsnew-4.0.html

**Comment by rhysyngsun** [comment]
Consider doing #2718 first.
