### ISSUE TITLE
Profile: On clicking "I'm Done" CPU goes to 100% and user has to kill the browser

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2714]
[ZenDesk #6274](https://odl.zendesk.com/agent/tickets/6274)

> When I press the "I'm done" Button CPU goes to 100% and I have to kill the explorer.

The learner says they are using Firefox and Windows 10. No errors in Sentry, as far as I can tell.

**Comment by pdpinch** [comment]
Looking through the logs, it appears that he is using Firefox 51. 

He's unable to log in due to this issue.

**Comment by rhysyngsun** [comment]
@pdpinch I tried to reproduce this yesterday, but couldn't, do we have details on what exactly the user did during the signup process?

**Comment by pdpinch** [comment]
What kind of information would be helpful? 

I can ask him for steps to reproduce. I could also dump his profile. I did look for any empty company_name or school but they were all filled out.

**Comment by rhysyngsun** [comment]
@pdpinch I believe based on when I've observed this in the past that it's dependent on the data that was entered which causes a tight loop between our validation logic and navigation code. We don't see Sentry errors for these because there's no actual error.

**Comment by pdpinch** [comment]
I've updated the ZenDesk ticket with his profile data. Let me know if you need access to it.

**Comment by rhysyngsun** [comment]
@pdpinch I'm getting a 404 page with that ticket link

**Comment by rhysyngsun** [comment]
I was unable to reproduce w/ Firefox under Linux using the provided profile data. This probably needs to be tested/reproduced under Win 10 Firefox.

**Comment by pdpinch** [comment]
FWIW, user confirmed that he can log in with Chrome, but FireFox is still out of control. 

I'm going to move this out of Ready, because it's no longer blocking a user.

**Comment by amir-qayyum-khan** [comment]
so should i continue on this or look for other task. my all PRs are merge, looking for new tasks

**Comment by pdpinch** [comment]
apparently hasn't happened again, so I'm closing this.
