### ISSUE TITLE
JS warning during build

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2717]
(node:6) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
    parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

**Comment by aliceriot** [comment]
when I do `ag parseQuery` I don't see any results, so I'm guessing this is a dependency that needs to get it's act together.

**Comment by rhysyngsun** [comment]
It looks like this is being causes by `babel-loader`, which is fixed in 7.x, but that's still in beta: https://github.com/babel/babel-loader/commit/cc8b341c525d0559abf4d058d4d9f9b21c695bcd#diff-1fdf421c05c1140f6d71444ea2b27638L79

**Comment by noisecapella** [comment]
`babel-loader` 7.0 is now released. We should look into upgrading at some point soon
