### ISSUE TITLE
Profile: Enter " " (space) as school name results in 400 page

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#2721]
If you enter a a space as your school name and hit save the application errors (noticed this on the signup process). Should probably check work experience for a similar bug too.

**Comment by aliceriot** [comment]
You can do the same thing on a field on the first page (like 'Personal') as well.

**Comment by aliceriot** [comment]
We should disallow strings with just spaces in the validation.

**Comment by aliceriot** [comment]
got a fix! I'll open a PR real quick.
