### ISSUE TITLE
Change osx_run.sh to not prefix python3 to shell commands

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#274]

**Comment by noisecapella** [comment]
We should also fix this so tox runs correctly

**Comment by aliceriot** [comment]
seems like there's a of code shared between the `osx_run` and `osx_start` scripts, why not move it into one file that defines shell functions?

could look something like this:

```bash
function env_setup() {
  # export various environment variables
}

function code_dependency_setup() {
  # install commands
}

function check_system_dependencies(){
  # check for postgres, etc
}

function start_app(){
  # start django, webpack, export the PIDS, etc
}

function run_cmd() {
  env_setup
  if [[ check_system_dependencies ]]; then
    $@
  else
    echo "setup things first!"
  fi
}
```

then you could just source this file in your shell config (or do something like `alias dev_python_osx='source ~/Code/micromasters/osx_dev.sh'` to source it when you need it) and then call the functions, like `start_app` would start the app, `run_cmd` to run a command, `run_cmd_py` to source `.venv/bin/python` first, etc.

**Comment by noisecapella** [comment]
Replaced by #307
