### ISSUE TITLE
Displaying different prices in the Courses card and Enroll Now UX

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2743]
On my dashboard, I am seeing that my "Personal Course Price is $150 USD per course". When I click Enroll Now, in the modal the Pay Now button shows the price as $1000. Also, clicking Pay Now goes to the Order Summary page with a price of $1000.

![image](https://cloud.githubusercontent.com/assets/20047260/23482701/050eb19c-fe9e-11e6-8877-c611c9ea89e4.png)

**Comment by pdpinch** [comment]
What server are you seeing this on?

**Comment by pdpinch** [comment]
Turns out this is a bug in the financial aid card in the dashboard, and not the pop-up. We're reverting #2519 to fix this immediately. We'll probably open a new improved PR after that.

**Comment by noisecapella** [comment]
From the chat:
I think this is the source of the bug: https://github.com/mitodl/micromasters/pull/2519/files#diff-9da0ee2be64521e2642084f5f8c15533R54
It should pick the price where program id == props.program.id, but it just picks the first price in the list
