### ISSUE TITLE
Fix dashboard UI to correctly display upgradable past course runs

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#2755]
It is possible for a user to be in a state where there is a currently enrolled/enrollable course run for a particular course _and_ a past course run that (a) has a final grade, (b) is past its `end_date`, and (c) has a future `upgrade_deadline`. In this case, the dashboard UI looks like this: 

![ss 2017-03-02 at 13 48 41](https://cloud.githubusercontent.com/assets/14932219/23522000/69c9f716-ff4f-11e6-95b5-ac22f5f49593.png)

We need to display some more meaningful information for these past-but-graded-and-upgradable course runs. The key file that needs to be changed is `static/js/components/dashboard/CourseSubRow.js`.

**Comment by pdpinch** [comment]
What I want to see in this state is:

- [ ] My grade
- [ ] A Pay button
- [ ] ideally, something indicating that I passed

For Monday, March 6, I'll settle for the first two. 

FYI @roberthouse54

**Comment by roberthouse54** [comment]
Can we do something like this:
![image](https://cloud.githubusercontent.com/assets/20047260/23523600/9a2a5242-ff55-11e6-9819-8b4fb970d09c.png)

**Comment by giocalitri** [comment]
Just a quick note to be explicit: if the course is failed there should not be a "pay for this course run", but I think that is just the mockup.

**Comment by giocalitri** [comment]
I Also think that user the "45%" we should show "Final Grade"

**Comment by gsidebo** [comment]
@roberthouse54 what do you think? this reuses the exact button we use for currently-running upgradable courses

![ss 2017-03-02 at 16 26 22](https://cloud.githubusercontent.com/assets/14932219/23527706/02ef4558-ff65-11e6-94ea-3a13ea9edfa7.png)
