### ISSUE TITLE
Profile: make select component more material

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#277]
from https://github.com/mitodl/micromasters/issues/151#issuecomment-216932574

> The select element (e.g. country) doesn't look material design. Can you look around for a select MD select component ?

**Comment by pdpinch** [comment]
How about this? It's a "menu"

<img width="321" alt="screen shot 2016-05-04 at 4 48 17 pm" src="http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3VGxlSGNVWmNJX3c/components_menus_behavior2.png">

from http://www.google.com/design/spec/components/menus.html#menus-behavior

**Comment by aliceriot** [comment]
http://www.material-ui.com/#/components/auto-complete

**Comment by noisecapella** [comment]
The autocomplete component looks like what we want. Not sure how easily it handles many items, but for countries and territories it may not get big enough to matter

**Comment by aliceriot** [comment]
awesome, glad we found something that works!
