### ISSUE TITLE
Certificates: add edx-certificates app to MicroMasters

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2778]
> After an initial review of the codebase of edx/edx-certificates it appears as though we can use that project as a library for Celery tasks in Micromasters without having to manage our own XQueue or a separate server for the certificate process.

part of #2552 

_(Added by Gavin, 8/3/17)_

We've made a few implementation decisions:

1. Certificates don't need to be downloadable or delivered as PDFs.
1. Certificates don't need to be verifiable in any specific way (GPG or otherwise). 

Given that, we've decided to simply render HTML certificates dynamically in the app (edX LMS does this is well).

**Comment by pdpinch** [comment]
@gsidebo the edX repo is at https://github.com/edx/edx-certificates

The Stanford fork is at https://github.com/Stanford-Online/openedx-certificates

**Comment by gsidebo** [comment]
Starter question: Do we have any idea about what we want this certificate to look like? What info should be presented/general layout/fonts/etc.

**Comment by pdpinch** [comment]
We have a version in invision. It looks remarkably similar to edX's because we want it to be the same. I'll follow up with a link once I find it.

**Comment by pdpinch** [comment]
https://invis.io/7UAGCTVYR#/219015184_Micromasters_Certificate

**Comment by gsidebo** [comment]
My next big question mark is around certificate verification. The generated certs have a verification URL at the bottom, and it's not clear to me what app/server should be handling those verification requests. We can chat about this in person, but in the meantime if you have any documentation links that would be helpful

**Comment by pdpinch** [comment]
Gavin and I spoke about this last week. We are going to go with the same behavior edX has currently, which is the verification URL points back to the web page hosting the certificate (in our case, no micromasters.mit.edu)

**Comment by pdpinch** [comment]
@gsidebo I want to confirm our conversation from last week: you aren't planning to use edx/edx-certificates. Instead you're just going to add a view to the MicroMasters app. Is that right?

**Comment by gsidebo** [comment]
Yes that's right. I don't know what that codebase is used for. edX renders at least some certificates dynamically as HTML in LMS. We'll be doing the same in MM
