### ISSUE TITLE
Create separate ES accounts from micromasters-ci and micromasters-rc

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2780]
Currently the ci and rc servers share the came elasticsearch credentials. Since they use separate indexes, they should have separate credentials.

**Comment by pdpinch** [comment]
@blarghmatey @noisecapella I started to write this down last week when we were talking about elasticsearch. Do we still need to do this?

**Comment by blarghmatey** [comment]
This is done a long time ago...
