### ISSUE TITLE
Dashboard: state for passed course but not passed exam

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2781]
DEDP learners need a clear reminder in the dashboard that they need to pass the final exam in order to get MicroMasters credit for a course. This message should also include a reminder about the payment deadline.

**Comment by pdpinch** [comment]
This should be addressed as part of #3046

**Comment by pdpinch** [comment]
@roberthouse54 can we close this?

**Comment by roberthouse54** [comment]
Yes.
