### ISSUE TITLE
Exams: Final exam card status doesn't handle 'failed'

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#2783]
`failed` is a possible `ExamProfile` status, but it results in this line getting hit and an error logged:

https://github.com/mitodl/micromasters/blob/master/dashboard/utils.py#L412

It should be considered invalid and return here instead:

https://github.com/mitodl/micromasters/blob/master/dashboard/utils.py#L395

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/229432438/

**Comment by pdpinch** [comment]
@rhysyngsun we're still seeing this in production with release 0.51.0

**Comment by rhysyngsun** [comment]
@pdpinch it wasn't in 0.51.0
