### ISSUE TITLE
Rewrite a python test module to use pytest style

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#2794]
After our lunch & learn in late February, we determined that a good way to begin using pytest-style testing in our Python suite would be to pick a test module that would (a) see a significant benefit from the rewrite, and (b) wouldn't be overwhelmingly difficult. One suggestion was the test modules in the `grades` app, where there is very heavy and repetitive patching. 

**Once a module is chosen, this issue should be updated**

**Comment by rhysyngsun** [comment]
`ESTestCase` is going to be a major blocker on refactoring our tests to pytest, so we should implement that behavior for pytest via fixtures and find a small module to refactor and use to verify.

Looks like `search/permissions_test.py` is a good target:

```
grep -rwl **/*.py /dev/null -e 'ESTestCase' | xargs wc -l
  341 search/api_test.py
   75 search/base.py
  631 search/indexing_api_test.py
   47 search/permissions_test.py
  268 search/views_test.py
 1362 total
```
