### ISSUE TITLE
style terms of service

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#280]
See https://invis.io/4E791TKU3#/157446164_Terms_Of_Service

- [x] Make it look like profile (with header, user profile image)
- [x] Shift the existing form to the center, like the other profile forms. 
- [x] Use a scrolling text box for the actual legal language, when we get it. 

![terms of service](https://cloud.githubusercontent.com/assets/430126/15399706/b9394f20-1db6-11e6-8f04-a9a1a3866f66.png)
See https://invis.io/4E791TKU3#/157446164_Terms_Of_Service

**Comment by pdpinch** [comment]
@amir-qayyum-khan when you start work on an issue, please assign it to yourself and move it to the "in progress" pipeline.

**Comment by pdpinch** [comment]
added a screenshot to the description, from the invision mock-up

**Comment by amir-qayyum-khan** [comment]
@pdpinch i havent change the color of success button.

<img width="1276" alt="screen shot 2016-05-20 at 1 17 29 am" src="https://cloud.githubusercontent.com/assets/10431250/15408257/b3794e60-1e28-11e6-9f0d-2071ab1f9539.png">

**Comment by amir-qayyum-khan** [comment]
Resolved by #346
