### ISSUE TITLE
Get users to agree to T&S when they go to Pearson VUE website

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2806]
When users leave the portal to go to the Pearson VUE website we need to get them to agree to the Pearson legal terms. The first time a user leaves the portal to complete test registration at Pearson's website, we will show a modal that has two functions:

- Inform the user that they are leaving the portal to complete registration on another website
- Get users to agree to Pearson's legal terms, at https://home.pearsonvue.com/Legal/Privacy-and-cookies-policy.aspx

![image](https://cloud.githubusercontent.com/assets/20047260/23669112/255edc82-0331-11e7-8923-569b1c813ecd.png)

**Comment by amir-qayyum-khan** [comment]
@roberthouse54 should i show exact same text on dialog
- where is P images,
-  what is the url privacy and cookie

**Comment by roberthouse54** [comment]
Yes, please use the same text as is shown in the mock:

Test Registration is completed on the Pearson VUE website 

I acknowledge that by clicking Continue I will be leaving the MicroMasters website and going to the Pearson VUE website, and that I accept the Pearson VUE Group’s Terms of Service. 

I will send the image. The link should open the above URL in a new tab.
