### ISSUE TITLE
Add a new tab for Pearson test information and dates (DEDP)

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2811]
We want to add a new tab in the DEDP Program marketing page that contains information about the Pearson Proctored Exams, and which also contains any dates relevant to the exam. (Payment deadline, exam window dates, exam registration start and end dates.)

We need to determine if this page will be editable in the CMS, and whether we load the dates programmatically or just as text entered in the CMS.

(Design is TBD.)

**Comment by pdpinch** [comment]
We're waiting on text from DEDP
