### ISSUE TITLE
Cloudfront errors: /original_images/econ_hero.jpg

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2829]
I can't find where the requests for this file are coming from, but it generates a significant number of CloudFront errors -- for most of the past week it was our only source of cloud front errors.

**Comment by pdpinch** [comment]
Kibana isn't very enlightening: https://logs.odl.mit.edu/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:%272017-03-11T14:05:47.447Z%27,mode:absolute,to:%272017-03-11T14:15:30.549Z%27))&_a=(columns:!(_source),filters:!(),index:%27logstash-*%27,interval:auto,query:(query_string:(analyze_wildcard:!t,query:%27message:%20%2Foriginal_images%2Fecon_hero.jpg%27)),sort:!(%27@timestamp%27,desc),vis:(aggs:!((params:(field:environment,orderBy:%272%27,size:20),schema:segment,type:terms),(id:%272%27,schema:metric,type:count)),type:histogram))&indexPattern=logstash-*&type=histogram

**Comment by pdpinch** [comment]
talking to Tobias, it looks like we're just missing a behavior setting in Cloudfront that would wrote requests for `/original_images/` to the S3 bucket instead of the app. Indeed, this image does exist in the S3 bucket, http://odl-micromasters-production.s3.amazonaws.com/original_images/econ_hero.jpg

Still, I have no idea where in the app this image is requested.

**Comment by blarghmatey** [comment]
The Cloudfront behavior has been added to the production distribution.
