### ISSUE TITLE
Make Micromasters Production Ready

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#283]
### Oct 15
- [x] Move to production dyno 
- [x] Move db to production db
- [X] #707 Move elasticsearch from bonsai to AWS
- [x] #469 Performance Monitoring
- [x] #980 Production error monitoring
- [x] #1219 Mail Monitoring
- [x] #1218 Load Testing

### Required features:

- [x] Does it support configuration via environment variables?
- [x] Does it support configuration via flatfile (e.g. YAML)?
- [x] Does it have a sane default configuration (e.g. as close to a realistic production configuration as possible)?
- [x] Does it run on parallel HTTP workers? (e.g. uWSGI, Gunicorn)?
- [x] Does it log to standard out/error?
- [x] Does it log to syslog?
- [x] Can it send stack trace emails to a configurable email list?
- [x] Does it have configurable log levels (e.g. DEBUG, ERROR, WARNING, INFO)?
- [x] Does it have a test suite which measures code coverage?
- [x] Does it have a status route (which requires a secret token) that can be used for health checking by a monitoring service?
- [x] Does the health check validate that each service the app depends on is reachable (e.g. databases, caching, external APIs when necessary)?
- [x] Does the health check return a response body with the availability information above in a machine-readable format in all cases?
- [x] Does the health check return a 500 status code when any component in the health check is detected to be failing?

### Required documentation/service infrastructure:

- [x] Does it have continuous integration builds which run the full test suite?
- [x] Does it have an automated continuous delivery to a development environment?
- [x] Does it have a documented release process?
- [x] Does it's release process include staging and production builds, where staging builds are promoted to production?
- [x] Does it's release process require that code changes be "signed off" as working on staging before being promoted to production?
- [x] Does it have application/resource monitoring in production (e.g. New Relic agent, Zenoss SNMP)?
- [x] Does it have service availability monitoring in production (e.g. periodic health checks with Zenoss or New Relic)?
- [x] Does it have automated, periodically generated, fully restorable backups for each non-ephemeral data store in production?

(From https://github.com/mitodl/handbook/blob/master/production-ready.md)

**Comment by pdpinch** [comment]
@blarghmatey @bdero can you guys take a look at this list and let me know how far off we are, before planning on Monday?

**Comment by bdero** [comment]
@pdpinch I've checked off all of the items in the list that are done.

For the others:

-  **Can it send stack trace emails to a configurable email list?:** It *should* be able to, but I haven't received any stack traces in a while, so we should double-check this.
-  **Does the health check return a 500 status code when any component in the health check is detected to be failing?:** This actually [returns a 503](https://github.com/mitodl/django-server-status/blob/master/server_status/views.py#L25) if any service checks fail, which is good.
-  **Does it have service availability monitoring in production (e.g. periodic health checks with Zenoss or New Relic)?: **NewRelic is installed on all micromasters apps, but we should doublecheck that the configuration on New Relic is sane and working for the health checks.
-  **Does it have automated, periodically generated, fully restorable backups for each non-ephemeral data store in production?: **Database backups are NOT turned on in production yet. We are still running everything off of completely free Heroku infrastructure - automated periodic backups will come with wither switching to a non-free Heroku PostgreSQL plan or RDS.

**Comment by bdero** [comment]
FYI @blarghmatey , this checklist is copied from a list if guidelines I wrote and pushed here: https://github.com/mitodl/handbook/blob/master/production-ready.md

Feel free to open a PR against it if you have any additional recommendations/suggested modifications.

**Comment by blarghmatey** [comment]
I am unable to get a stacktrace email despite forcing a 500 error via raising an explicit exception.

**Comment by blarghmatey** [comment]
@bdero @pdpinch This will be done once we move the DB to a paid plan and set the backup schedule.

**Comment by blarghmatey** [comment]
I'm going to leave it as in progress as a reminder to do the DB setup

**Comment by blarghmatey** [comment]
Apparently the free tier allows for up to 2 backups maintained. I added a schedule to run the backups at midnight UTC on a nightly basis.

**Comment by pdpinch** [comment]
🏆
