### ISSUE TITLE
Layout bug with grade slider histogram

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2833]
There is now a gap between the histogram and the slider control in the grade facet. This was introduced recently, but I do not know what caused the change. It seems that a margin-top of -5px on .sk-range-slider will fix this. But I would like to know what caused this change, to make sure we will not break something elsewhere.

![image](https://cloud.githubusercontent.com/assets/20047260/23757487/fb4d141a-04b4-11e7-8f60-6153427a5f46.png)

**Comment by noisecapella** [comment]
I'm not sure I see this change. What was it looking like before?
