### ISSUE TITLE
Test release version with edX.org

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#284]
So far, we've been testing micromasters with sandboxes and stage.edx.org, which may not be configured the same as edx.org. We need to test the release version with the live edX. 

- [x] connect micromasters-rc to stage.courses.edx.org
- [x] create test courses on stage.courses.edx.org
- [x] popualate micromasters-rc with a program that works with stage.courses.edx.org
- [x] ask edX to create fake certificates, so we can test certificates API

- [x] Test with the old library & the existing micromasters OAuth application on edx.org
- [x] Populate the production micromasters app with a program that works with edX course runs
- [x] Ask edX to create a fake certificate, so we test certificate API

**Comment by pdpinch** [comment]
@bdero can you take a quick pass over the checkmarks here? I think you did a lot of this already?

**Comment by bdero** [comment]
@pdpinch I checked off the stuff that's done. Note - I only asked around for the fake certificate, we haven't actually got one yet. Maybe I should ask on slack.

**Comment by pdpinch** [comment]
I think I'll open a ticket. Let's check in tomorrow.

**Comment by bdero** [comment]
For `Test with the old library & the existing micromasters OAuth application on edx.org`, does this mean test with both Django OAuth Toolkit as well as the older one currently in use?

**Comment by pdpinch** [comment]
That's what I had in mind. When I wrote the ticket, I wasn't sure which OAuth library we would go with. If everything is in place and working, I think we can just use the new one, but until we know for sure I'd like to have the option of using the old one.

**Comment by pdpinch** [comment]
@bdero are you done with your testing of this in production?

I think the only thing remaining is `Populate the production micromasters app with a program that works with edX course runs` which I can take care of.

**Comment by bdero** [comment]
Yup, what you mentioned is the only thing left to do. OAuth login works.

**Comment by pdpinch** [comment]
Ok. I created an SCM Program in https://micromasters.herokuapp.com and it's functioning, except for the bug recorded in #648 which is in master.
