### ISSUE TITLE
alert user to which fields are unfilled using red text

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#285]
When checking for profile completeness we need to alert the user about which fields are currently unfilled.

A couple possibilities:

- move `errors` into the redux store, then the `validateProfileComplete` method could dispatch the errors into the store (so that validation messages would show up on individual fields in the same way they currently do on save)
- put information about missing fields into the dialog, something like:

![message](https://cloud.githubusercontent.com/assets/6207644/15076500/f586dfa4-1377-11e6-9f09-023552e2f442.png)

- probably others?

**Comment by pdpinch** [comment]
To be clear, this is an alert in addition to moving the user to the first step with invalid fields?

I'd like to highlight the fields the same way we do when the user is still within a step. Is that the first option you listed?
> move errors into the redux store, then the validateProfileComplete method could dispatch the errors into the store (so that validation messages would show up on individual fields in the same way they currently do on save)

**Comment by aliceriot** [comment]
yes, that would be the first step.

to accomplish that I think we'd need to refactor how we do validation slightly, currently the validation errors are stored in the redux store but under `userProfile.edit.errors`. The `edit` key on `userProfile` doesn't exist unless we've started editing the profile, so we'd need to change that around a little bit.

**Comment by aliceriot** [comment]
although if we're redirecting people there we'd expect them to be editing things soon anyway, so maybe it would work as-is, with a few changes to the `validateProfileComplete` method.

**Comment by Ferdi** [comment]
I think the modal is a bit too much here. There is only one place they'd end up - where they left off . Why dont we simply redirect there displaying the inline validation errors ?   In addition we can show a simple message at the top of the form  "Please complete your profile to continue".

**Comment by amir-qayyum-khan** [comment]
@aliceriot can you guide me where to start?

**Comment by aliceriot** [comment]
@amir-qayyum-khan sure - I think all you should need to do is that when we check for profile completeness (see the `validateProfileComplete` method in `util/util.js` and the `requireCompleteProfile` method on `App.js`) if the profile isn't complete we dispatch the `START_PROFILE_EDIT` and `UPDATE_PROFILE_VALIDATION` actions. The `errors` object that holds the validation results is passed down into each profile tab from its parent component, so the errors should then just show up.

**Comment by aliceriot** [comment]
does that make sense? lmk if you have more questions

**Comment by amir-qayyum-khan** [comment]
yeah, thnaks
