### ISSUE TITLE
Display average program grade in staff view of learner's profile page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2853]
Part of #2480 

When a staff member views the learner profile of a learner in their program, they should be able to view the learner's average grade in the program -- this should be the same value as the one they can view in the learner search. 

![enhanced_profile_faculty_view4 2x](https://cloud.githubusercontent.com/assets/20047260/23867755/51f1f2cc-07f3-11e7-824d-b9163bfb394a.jpg)

**Comment by pdpinch** [comment]
@roberthouse54 can you paste in a design for this? Is [Invision](https://invis.io/PVA10ONNJ#/214364752_Enhanced_Profile_Faculty_View) accurate?

**Comment by roberthouse54** [comment]
The most recent version was slightly different in color, so I updated it on Invision.

![enhanced_profile_faculty_view4 2x](https://cloud.githubusercontent.com/assets/20047260/23867755/51f1f2cc-07f3-11e7-824d-b9163bfb394a.jpg)
