### ISSUE TITLE
Update home page to match current mock-ups

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#287]
See https://invis.io/2R78JXBUG#/142338433_Public_Home

- [x] larger program cards
- [x] add placeholder card for right column
- [x] remove star ratings from card (since we don't have ratings functionality yet)
- [x] refactor cards to strip out extraneous CSS; use bootstrap
- [ ] replace text in placeholder card with the following:

> MIT has plans to bring more MicroMaster’s programs to motivated learners like you. 

> Please sign up for our [mailing list](http://javascript-pop-up-form.here) to hear about new MicroMaster’s programs. Also, don't hesitate to let us know about what MicroMaster’s you’d like to see. 

- [ ] add a pop-up form with the fields and functionality of https://github.com/mitodl/mga/blob/gh-pages/index.html#L125-L198

For designs, see https://projects.invisionapp.com/share/4E791TKU3#/screens/159574507_Public_Home_-sign_Up- and https://projects.invisionapp.com/share/4E791TKU3#/screens/159574508

![public home sign up](https://cloud.githubusercontent.com/assets/430126/15456257/cd09570a-2038-11e6-80d4-0a9752a9435e.png)
![sign up interested modal](https://cloud.githubusercontent.com/assets/430126/15456269/fce8537c-2038-11e6-99b2-165eb7f9a34d.png)

**Comment by amir-qayyum-khan** [comment]
@pdpinch is there template for ``placeholder cards`` or we need to implement it?

**Comment by pdpinch** [comment]
The only template we have is https://github.com/mitodl/micromasters-templates/blob/master/index.html but it looks like that's the smaller, 3-per-row cards.

**Comment by pdpinch** [comment]
@amir-qayyum-khan the image for the placeholder card is at https://github.com/mitodl/micromasters-templates/blob/master/assets/images/academia.png

**Comment by amir-qayyum-khan** [comment]
Work done so far in PR #306.
@pdpinch 

![Uploading Screen Shot 2016-05-11 at 7.16.35 PM.png…]()

**Comment by pdpinch** [comment]
@amir-qayyum-khan I'm not sure how far along you are with this, but this isn't right yet. 

Card size looks good, but we currently have only one Program, plus one placeholder card. Like https://projects.invisionapp.com/share/2R78JXBUG#/screens/142338433_Public_Home

**Comment by amir-qayyum-khan** [comment]
@pdpinch that UI was generic (show card in loop) and i have multiple programs live for testing purpose.

- Just removed 2 out of 3 programs by making live button unchecked.
- Added added card for coming soon

Can you send me text for coming soon card?

<img width="1274" alt="screen shot 2016-05-12 at 5 11 22 pm" src="https://cloud.githubusercontent.com/assets/10431250/15214163/ee938fd4-1864-11e6-840d-238f257e0673.png">

**Comment by pdpinch** [comment]
Looks good @amir-qayyum-khan, but I saw that you need some text for the placeholder box. 

@Ferdi how about this:
> Anyone who successfully masters the material and receives a high passing grade can earn a Micromasters credential from MITx.

I'll also send another e-mail to Erdin to see if he has some input.

**Comment by Ferdi** [comment]
@pdpinch that look more like a message that goes in the main banner and not much related with the "more programs coming soon".  

A sentence the expand the the title "More programs coming soon" and and invite to subscribe for updates would be great,  I think.

**Comment by pdpinch** [comment]
How about 


"Sign in with edX.org <http://edx.org/> now and MITx will send you updates about new Micromasters programs when they are announced"

Ideally with "Sign in with edX.org <http://edx.org/>" being a link that functions like the sign in button.

**Comment by Ferdi** [comment]
Not sure about "sign in with edx".   How about a mailing list sign-up.  Since we are replacing the current micromasters.mit.edu and there is a signup feature already there.

**Comment by pdpinch** [comment]
so, re-use the mailchimp form from https://github.com/mitodl/mga/blob/gh-pages/index.html#L92-L190 <https://github.com/mitodl/mga/blob/gh-pages/index.html#L92-L190> ?

**Comment by Ferdi** [comment]
I think the form wouldn't look great in the page. Maybe a button that brings up the form?  It looks like we need some designer help .

**Comment by pdpinch** [comment]
I spoke with Ferdi and we'd like to replace the placeholder graphic with the form, but it's going to need some design. 

@amir-qayyum-khan can you add the form to your PR and take a screenshot, so we have something to work from?

**Comment by amir-qayyum-khan** [comment]
let me

**Comment by amir-qayyum-khan** [comment]
@pdpinch adding form to card looks like. this form is bigger the normal card.

![screen shot 2016-05-12 at 7 25 45 pm 2](https://cloud.githubusercontent.com/assets/10431250/15218000/61fd60a0-1877-11e6-9caf-33fd0e8c58d6.png)

**Comment by pdpinch** [comment]
@amir-qayyum-khan we finally got the new design:

https://invis.io/4E791TKU3#/159574507_Public_Home_-sign_Up-

There's a button on the home page that launches a modal. There a couple of things that are wrong in the mock-up:

"Micromasters" should be "MicroMaster's" (see #236)
The form in the modal should be dynamic, same as the one currently at http://micromasters.mit.edu/

**Comment by pdpinch** [comment]
I updated the description with new action items based on the new design.

**Comment by amir-qayyum-khan** [comment]
@pdpinch where can i get background image of placeholder card?

**Comment by pdpinch** [comment]
@amir-qayyum-khan the background graphic for the placeholder card is now at https://github.com/mitodl/micromasters-templates/blob/master/assets/images/part-globe.png
