### ISSUE TITLE
Migrate to Docker for OS X

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2876]
We run the webpack server on the user's local machine. We should investigate if we can move to Docker for OS X which would let us have the same commands and workflow for Linux and OS X

**Comment by aliceriot** [comment]
iirc the thing preventing this before was file change notifications

**Comment by noisecapella** [comment]
Yeah, it's possible that Docker for OS X has solved that problem but we've never tested it before

**Comment by rhysyngsun** [comment]
This might be the applicable issue (still open): https://github.com/docker/docker/issues/18246

**Comment by noisecapella** [comment]
@singingwolfboy tested this and it looks like file notifications are still an unresolved issue
