### ISSUE TITLE
Preferred name - a few changes

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2879]
In the current version of the app, it is not clear what is meant by "preferred name/nickname". Most users simply enter their first name in this field. Others enter a nickname in this field. In the app, we display the preferred name on the user profile, which is less than ideal, especially for faculty members who may want to know a user's full legal name. Also, in the learner search results we display both a user's legal name, AND their preferred name, which is also not ideal for users who do not wish for others to know their legal name, for whatever reason.

The goal of this issue is to change both the way we collect Preferred name, and the messaging around this. And also to change the way we show it in the app.

On the sign up page, we will pre-populate the preferred name field with Given Name and Family Name (currently it pre-populates only with Given Name). We will also add explanation text that says "Do you prefer to use a name different than your legal name entered above? If so enter it below."

![image](https://cloud.githubusercontent.com/assets/20047260/23964442/ec5c0ec2-098a-11e7-9263-340e03bde684.png)

**Display of the preferred name:**

Currently we display user names in various places in the portal. Mainly:
- On the learner search results
- In the user chip
- On the user profile
- In the sidenav.

In all the places we display user names, we will instead display the user's preferred name. 

The one exception to this is the user profile viewed by staff or faculty. In this case we will display BOTH the user's legal name, and their preferred name.

![image](https://cloud.githubusercontent.com/assets/20047260/23964937/a77bd3ee-098c-11e7-9753-909703284315.png)

TBD: What do we do with the users who have already entered a preferred name, because it has been required?

**Comment by aliceriot** [comment]
Ok just to be clear, if a learner enters a preferred name we will show only that to other learners, correct? In my view that's the correct behavior - if I have to enter my legal name on a service I don't want it to be visible to anyone except administrators and so on (who may need it for legal reasons).

We should also clarify whether the preferred name is a preferred first and last name, or just a preferred first name, etc. If the idea is to have the preferred name replace the legal first and legal last name we should make that clear to the user, especially given different name setups internationally. 'Preferred name' colloquially in the US usually refers to a preferred first name, for instance.

**Comment by roberthouse54** [comment]
Yes, that is how I am thinking this should work. As far as whether it is a first or a first and last name... it seems to me preferable to have it replace first and last name. So maybe we should make that more explicit. The way I solved this particular part of the UX was to have the hint say "ex: John Smith"... ie. to suggest that the user enter both a first and last name, although if they just entered one name (like "Madonna") we would accept that as well.

Another way to go about this would be to not show the fields by default, but have a link that says, Do you go by a name other than your preferred name? Click here. Then we would show both a first and last name field.

But I am open to other suggestions.

**Comment by aliceriot** [comment]
Oh I missed the hint - I think just putting the hint in makes sense!

**Comment by rhysyngsun** [comment]
@roberthouse54 @pdpinch this was on the sprint themes doc but I see there's still a TBD in the issue description and issue is still in In Design.

**Comment by pdpinch** [comment]
I updated the description to reflect the decision to keep preferred name required, but instead pre-populate it with given name and family name. The screenshots are a little off now, but I don't think that will prevent us working on this issue.
