### ISSUE TITLE
style employment step to look like current mock-ups 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#289]
See https://invis.io/4E791TKU3#/153562860_Step_Three_-_Professional_Info

- [ ] Implement switch instead of "are you employed" question

**Comment by pdpinch** [comment]
I updated the link in the description.

**Comment by aliceriot** [comment]
stuff I'm working on:

- [ ] add actions and reducer to hold employment tab dialog state (dialog visible, index, etc)
- [ ] add dialog element to hold edit form
- [ ] refactor edit form function to size things correctly
- [ ] add callbacks defined in `ProfilePage` to page in to `EmploymentTab` (via `this.props`) for updating dialog state
- [ ] write functions to produce short description rows
- [ ] sort out how / when to validate and save the objects
- [ ] delete `editProfileObjectArray` from `profile_edit.js`
- [ ] fix `react-datepicker` z-index issue
- [ ] finished refactoring UI to match the mockup exactly
- [ ] write tests for new actions + reducers
- [ ] write UI tests to confirm actions are firing correctly (dialog is opening, etc)

**Comment by aliceriot** [comment]
hey @pdpinch, I'm wondering about font selections for the little 'job history summary' rows we show. did nicholae have any specific guidelines for that?

**Comment by aliceriot** [comment]
we have Open Sans included in the `<head>` for all pages, so I can use that (I think it's a nice looking font) I just thought it would be good to check.

**Comment by aliceriot** [comment]
another questions: on the mockup there's only one line shown: 

![employment](https://cloud.githubusercontent.com/assets/6207644/15221584/0755b5e0-183a-11e6-9f1a-e4744610a70a.png)

does the 'plus' button appear on every line? is that what adds a new entry? if it's not on every line, how should things be spaced out?

**Comment by pdpinch** [comment]
Sorry I didn't back to you sooner. You should feel free to add comments to the invision site -- I've added your questions. 

I also added @nicolaeherrera the designer to this repo as well, but I think it will be easier to ask questions about the design in the context of the mock-ups.

**Comment by pdpinch** [comment]
Alice, regarding [your question about the "plus" button](https://github.com/mitodl/micromasters/issues/289#issuecomment-218805573) there's an example of how multiple rows should look in the education mock-up. See https://invis.io/4E791TKU3#/153562861_Step_Two_-_Educational_Info (and yes, it's for adding new entries)

**Comment by aliceriot** [comment]
cool, over in the PR  (#312) I have a screenshot of what I have right now. I have a few small things to iron out and some last-minute styling to change.

One thing I have set up differently than the mockup right now is the placement of the 'add an entry' button, I moved it down to sit on the bottom border of the card. I was reading about what Google thinks you should do with floating action buttons here: https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-behavior and it made me think we might want it there.

If we want it inline in the first row (as we have it in the education mockup) I can easily change it.

**Comment by pdpinch** [comment]
Can you add the screenshots here? We'd like to keep the requirements conversation on the issue.

**Comment by aliceriot** [comment]
![employment-ui](https://cloud.githubusercontent.com/assets/6207644/15249707/fb1c9482-18ee-11e6-9e0e-41f6d259e4bc.png)

**Comment by Ferdi** [comment]
@aliceriot, I agree, your "add new entry" button is more "material design"-like than what we have in mockups. Why is half out of the box ? Just curious.

**Comment by aliceriot** [comment]
I just thought it looked nice like that! haha.

It's one of the placements the design guidelines for material suggest for floating action buttons. I think on a mobile UI you might want it floating, but on a desktop I think it feels better to have it anchored to something.
