### ISSUE TITLE
Weird font-size bug with flexbox on mobile phone

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2891]
I only discovered this bug when testing the app on my actual phone (Moto X- Android 5.1). Basically, in a bunch of divs where the font size is defined as being the same (14px), it is actually being computed to a different size (18.2px). So fonts in different parts of the page are displaying different sizes although they are defined as the same size. As far as I can tell, this has something to do with display: flex, and possibly also display: -webkit-box, because when I uncheck those attributes in inspector, the font size changes.

The goal is to have consistent font-size display in MOST places in the app (apart from where it is explicitly supposed to be a different font size.) Currently, the font-sizes are displaying weirdly because of this bug. I am not sure how widespread this is... I have only seen it on my own phone.

**Comment by pdpinch** [comment]
Is this still an issue?

**Comment by roberthouse54** [comment]
I am not sure. I will look into it.

**Comment by roberthouse54** [comment]
I am not seeing this anymore. Closing this issue.
