### ISSUE TITLE
learners page keeps trying getting dashboard rest api even in case of 500 errors

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#2907]
this is the root cause of the number of [this exception](https://sentry.io/mit-office-of-digital-learning/micromasters/issues/236670197/) and t[his other exception](https://sentry.io/mit-office-of-digital-learning/micromasters/issues/235789042/).

the learner page, if receives a 500 error from the dashboard rest api, retries to request the same resource in a loop instead of just failing.

**Comment by noisecapella** [comment]
Beat you to it: #2905 and a PR to fix #2906

**Comment by giocalitri** [comment]
too slow: ☹️
