### ISSUE TITLE
Dashboard: Remove settings and profile items from drop-down menu 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#291]
because they aren't functional yet. They can be added back when they are functional.

**Comment by giocalitri** [comment]
Planning to work on this: the profile is technically working even if it is not the profile page: do we want to remove the link anyway?

**Comment by pdpinch** [comment]
Yes. Remove the profile link. We'll put it back in when we do https://github.com/mitodl/micromasters/issues/216
