### ISSUE TITLE
exams: modify dashboard rest API to expose exam grades

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2915]
Final grades in DEDP courses are a combination of exam grade and online course grade: 60% exam and 40% course. We need to use this grade when determining if the user has passed a DEDP course. 

### acceptance criteria
- [ ] all DEDP courses will use a 60% exam / 40% online course grading policy
- [ ] need a plan (although not necessarily implemented) for having program-specific grading policies.

### related issues
- [ ] #2792 combined grade displays in learner dashboard
- [ ] combined passed status reflected in course card and program progress card

**Comment by giocalitri** [comment]
Questions:

1. I suppose MMTrack should provide also the Pearson Grade by itself ano only combined in the micromaster final grade. Is that right?
2. when you say "need a plan (although not necessarily implemented) for having program-specific grading policies" do you mean just for the combined micromaster final grade?

**Comment by pdpinch** [comment]
1. That's right. We'll need to display the exam grade and the final grade separately. 

2. Yes. The policy for DEDP will be final grade = 40% edx final grade + 60% exam grade.

**Comment by giocalitri** [comment]
Sorry I added a point 3. to the list above

**Comment by giocalitri** [comment]
Another question is: the integration inside the Dashboard REST API should be done in another issue?

**Comment by pdpinch** [comment]
Sorry, I don't have an opinion about question 3. I guess an exception makes sense...

And I don't now the boundaries between MMTrack and the Dashboard REST API to answer that question. I think it's fine to split it up, if that makes sense to you.

**Comment by giocalitri** [comment]
So is this story is about the REST API?
