### ISSUE TITLE
Staff view of learner profile: Change “you are auditing this course” language 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2917]
Instead of the text "you are auditing" learner's audit status should be displayed as a label, as shown in the mock-up:

@roberthouse54 is there a similar label for `Paid`?

![c08a099c-0d4b-11e7-96db-849d4339983d](https://cloud.githubusercontent.com/assets/20047260/24204042/a8374d98-0eed-11e7-9251-4ac522470822.png)

**Comment by pdpinch** [comment]
@roberthouse54 I think we need to identify `Paid` courses as well as `Auditing`. What do you think?

**Comment by singingwolfboy** [comment]
Should this change occur in both the learner's view of their own profile, _and_ the staff view of another learner's profile?

**Comment by pdpinch** [comment]
This is just about the staff view. The phrase "you are auditing" doesn't make any sense when the staff is viewing someone else's status.

**Comment by roberthouse54** [comment]
Let's just use the words: "Paid" and "Auditing"

**Comment by roberthouse54** [comment]
I have updated the mock above. Let's just leave it as simple copy for now, in the same location as where it is currently. And use "Auditing" or "Paid". Let's show the same copy both for Learners and Staff.

I want to go with the simplest treatment of this for now, as this whole UI is in flux.
