### ISSUE TITLE
copy error on OrderSummary

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#2922]
![uhhh](https://cloud.githubusercontent.com/assets/6207644/24117264/e8c97634-0d7f-11e7-99f0-df3713f3fadf.png)

I don't think "Clicking below with link outside of the MIT MicroMasters app to an external website" is what we want here.

**Comment by aliceriot** [comment]
@roberthouse54 what is this supposed to be?

**Comment by roberthouse54** [comment]
"Clicking Continue will link to a website outside of the MicroMasters app, where you will be able to complete the transaction, by paying with a credit card."

Is this what you were asking?

**Comment by aliceriot** [comment]
yes!
