### ISSUE TITLE
refactor course price frontend code to support username-based namespacing

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#2923]
similar to what I needed to do for https://github.com/mitodl/micromasters/issues/2672

this just covers the frontend code, some changes will also need to be made on the backend, as a follow-up

part of #2862

**Comment by pdpinch** [comment]
Is this something we should just do differently "next time" -- i.e., make the user an explicit parameter for our APIs?

**Comment by aliceriot** [comment]
yes, definitely. george is working on some stuff for the bootcamp app that should hopefully make these kinds of changes require far less code.

**Comment by aliceriot** [comment]
It's generally better REST design anyway to have to request the information about a specific object (i.e. by username or id)
