### ISSUE TITLE
Search: course final grades facet filters is not restricted to just selected course

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2939]
We need to change the indexing to filter the final grades per program

Similar to #2942

**Comment by noisecapella** [comment]
cc @roberthouse54

**Comment by roberthouse54** [comment]
cc @annagav

**Comment by pdpinch** [comment]
@annagav now that #2945 is merged, what's the status of this issue?

**Comment by pdpinch** [comment]
@gsidebo what's the status of this?

**Comment by gsidebo** [comment]
@pdpinch i should have a PR up for this today. implementation was hairier than expected, so i may put up a PR with a bunch of code repetition and and open up a PR to clean that up later. i'll keep you posted
