### ISSUE TITLE
Add dialog polyfill

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#294]
This will be necessary to support Firefox and IE

**Comment by aliceriot** [comment]
I added a dialog polyfill in https://github.com/mitodl/micromasters/commit/0e8cc743c2354a1c79d631456176e6bcd25b70ea, do we need to do anything else?

**Comment by noisecapella** [comment]
I missed that, but we also need it for #241. I'd like to do it as a separate PR to avoid blocking that merge

**Comment by aliceriot** [comment]
ah, gotcha. do you mean a separate PR to handle actually doing the polyfill dealio for `<dialog>` elements declared in #241?

I wrote a little helper function called `doDialogPolyfill` in `util/util.js` that should make it easy to take care of.

**Comment by aliceriot** [comment]
can we close?
