### ISSUE TITLE
Search: Number of results from ElasticSearch is inconsistent. 

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#2944]
We are sharing data offline with course teams and they are noticing that the results are not consistent with the search results. A couple of example:

```
-- Toal enrollment on DEDP

SELECT count(Profile.user_id)
FROM profiles_profile AS Profile
JOIN dashboard_programenrollment AS Program_Profiles ON Profile.user_id= Program_Profiles.user_id
WHERE Program_Profiles.program_id = 2
  AND Profile.filled_out = 'true'
```

DB
![db3](https://cloud.githubusercontent.com/assets/125561/24266469/32d18122-0fdd-11e7-8133-625c222cd9ff.png)

ES
![es3](https://cloud.githubusercontent.com/assets/125561/24266479/3aecb174-0fdd-11e7-9d4f-31b16e2902f4.png)

```
-- Nr of enrollments by course in DEDP

SELECT min(courses_course.title) as course_title, count(DISTINCT dashboard_cachedenrollment.user_id) as nr_enrollments
FROM dashboard_cachedenrollment
JOIN courses_courserun ON courses_courserun.id = dashboard_cachedenrollment.course_run_id
JOIN profiles_profile ON profiles_profile.user_id = dashboard_cachedenrollment.user_id
JOIN courses_course ON courses_course.id = courses_courserun.course_id
WHERE profiles_profile.filled_out = 'true'
  AND courses_courserun.course_id IN (7, 8,9,10,11)
GROUP BY courses_courserun.course_id
ORDER BY (2) DESC
``` 

DB
![db1](https://cloud.githubusercontent.com/assets/125561/24266208/67c8a096-0fdc-11e7-8cc4-160585ed7c03.png)

ES
![es](https://cloud.githubusercontent.com/assets/125561/24266221/74f63cce-0fdc-11e7-9d17-dddcab1a97df.png)

```
-- Nr of enrollments in DEDP by country of birth

SELECT min(profiles_profile.birth_country), count(profiles_profile.user_id) as nr_learners
FROM profiles_profile
JOIN  dashboard_programenrollment ON dashboard_programenrollment.user_id = profiles_profile.user_id
WHERE profiles_profile.filled_out='true' AND  program_id = '2'
GROUP BY profiles_profile.birth_country
ORDER BY nr_learners DESC
```
DB
![db2](https://cloud.githubusercontent.com/assets/125561/24266343/d0388560-0fdc-11e7-871b-d3e1f7a54fc5.png)

ES
![es2](https://cloud.githubusercontent.com/assets/125561/24266360/d8e543ba-0fdc-11e7-9bcd-54027eae8294.png)

**Comment by annagav** [comment]
Query #1
```
Total enrollment on DEDP

SELECT count(DISTINCT Profile.user_id)
FROM profiles_profile AS Profile
JOIN dashboard_programenrollment AS Program_Profiles ON Profile.user_id= Program_Profiles.user_id
WHERE Program_Profiles.program_id = 2
  AND Profile.filled_out = TRUE
  AND NOT EXISTS
    (SELECT *
     FROM roles_role
     WHERE Profile.user_id = roles_role.user_id )
```

**Comment by annagav** [comment]
Query 2: 
For the number of enrollments by course in DEDP the query:
1. was showing extra results for users who have taken a course in the past and have an enrollment, but do not have DEDP program enrollment, so they were not showing up in the Learners search. 
2. not showing users that have a final grade for the course, but are missing `cachedenrollment`.

**Comment by annagav** [comment]
Query 3 shows extra results just for the users that have 'staff' role(s) on MM, whereas in Learners search they are filtered out.

**Comment by pdpinch** [comment]
@Ferdi is there more to do here?

**Comment by pdpinch** [comment]
@Ferdi can I close this?

**Comment by pdpinch** [comment]
I confirmed that a staff person on one program who is enrolled as a learner in a second program will be indexed in the second program, and appear in search results. That's what we expected.
