### ISSUE TITLE
Mail: allow simple HTML

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2948]
Staff would like to include hyperlinks in the mail sent through the portal (in particular, through the search interface).

See [ZenDesk #6790](https://odl.zendesk.com/agent/tickets/6790)

> Is there a way to add a hyperlink to text so that I could write "MITx MicroMasters Portal" and link the homepage? If not, not a problem just wanted to check!

Related issue #1938

**Comment by Ferdi** [comment]
I think it's time to introduce some minimal WYSIWYG editor.  I have seen some good reviews about https://draftjs.org/   and just saw this https://github.com/jpuri/react-draft-wysiwyg
Maybe it can be used to implement #2949 ?

**Comment by pdpinch** [comment]
We should provide a text fall back for HTML mail.

We should start with the bare minimum of HTML features, suggesting anchor, bold and italic. We can add more later.
