### ISSUE TITLE
Mail: radio buttons for choosing one-time / email campaign 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2952]
Part of #2812

Replace the checkbox in the mail composition dialog with a radio button with two, more explicit options. Display instructional text when "email campaign" is chosen. 

![scheduled_email 2x](https://cloud.githubusercontent.com/assets/20047260/24111439/c41c0d50-0d6c-11e7-8bfd-da02ccc346a9.jpg)

**Comment by amir-qayyum-khan** [comment]
@pdpinch @rhysyngsun what are these widgets
- Start sending 
- Stop sending

are the drop down, date picker or timer picker or text fields?

**Comment by roberthouse54** [comment]
The "Start" and "Stop" fields are intended to be date pickers. But this is not intended to be included as part of this issue. ( @pdpinch correct me if I am wrong).

**Comment by pdpinch** [comment]
That's right. The start/stop sending dates will be a separate issue, which I haven't written yet.
