### ISSUE TITLE
Race condition when mailing automatic emails for new users

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#2959]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/235964047/activity/

**Comment by noisecapella** [comment]
Looks like this is still happening: https://sentry.io/mit-office-of-digital-learning/micromasters/issues/235964047/

**Comment by noisecapella** [comment]
It looks like the refresh command doesn't guarantee that all indexing is done by the time of the next command. However percolate can take a document instead of a document id which would work fine for this situation

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/235964047/
