### ISSUE TITLE
Contact Course Team: Change upsell text

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2975]
To better align the upsell message with edX vocabulary, we'd like to display a slightly different message for non-FA programs like SCM. 

Currently, the message is `This is a premium feature for learners who have paid for the course.` This works for financial aid courses. 

For non-financial aid courses, we should display `This is a premium feature for verified learners.`

**Comment by pdpinch** [comment]
@roberthouse54 this OK with you?

**Comment by Ferdi** [comment]
Do DEDP learners "verify" ?

**Comment by roberthouse54** [comment]
This language is OK with me. But did you change it? I think originally you had: "This is a premium feature. You must pay and be verified for the course."

Just to clarify, this change is only for non-FA programs like SCM. The DEDP language would stay the same as it is currently...

**Comment by pdpinch** [comment]
Sorry for any confusion. I did update the description to try to make it clear that we'll have one message (the original one) for FA programs and a new message for non-FA programs.
