### ISSUE TITLE
Dashboard: When user misses payment deadline display "audit" instead of "failed"

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2976]
Although missing the payment deadline means that a course won't be counted for MicroMasters credit, we're confusing too many repeat students by telling them that they failed when they never intended to pursue credit for a course run. 

![image001](https://cloud.githubusercontent.com/assets/430126/24506084/483e18d4-152a-11e7-993a-7308163f2a31.png)

**Comment by pdpinch** [comment]
@Ferdi is this what you had in mind?

@roberthouse54 what do you think?

**Comment by roberthouse54** [comment]
I think in the case where a user has never paid, we should show "Audited". If they have paid, but did not pass, we should display "Not Passed" (instead of "Failed").

**Comment by pdpinch** [comment]
This should be addressed by #3046

**Comment by pdpinch** [comment]
@roberthouse54 I think this was taken care of in the dashboard redesign
