### ISSUE TITLE
Create test_settings so we are explicit about the settings environment for tests

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#2983]
Currently our tests run off of the default settings in `micromasters/settings.py`. Some of these pull from environment variables and I've had tests fail in non-obvious ways because of some local overrides. We should create a `test_settings` file and configure pytest to use it. instead of the default module.

**Comment by noisecapella** [comment]
We should be able to remove `passenv = *` from tox.ini and put our other environment variables there. I think I had a reason for having `passenv = *` but I don't remember what it is

**Comment by rhysyngsun** [comment]
That seems like a better solution.
