### ISSUE TITLE
CMS: increase file upload size

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2988]
From [ZenDesk 6735](https://odl.zendesk.com/agent/tickets/6735)

> Would also like to upload the five key concept documents. One from each course. These are long pdfs with large file sizes up to 25MB. Is it possible to raise the file size limit?

This error message appears in the CMS:

![screen shot 2017-04-03 at 8 42 58 am](https://cloud.githubusercontent.com/assets/430126/24705679/062a2c16-19db-11e7-9eae-9a6011323420.png)

**Comment by amir-qayyum-khan** [comment]
@giocalitri can you give me a hint where to start on this?

**Comment by Ferdi** [comment]
@amir-qayyum-khan maybe this ? https://goo.gl/hzQnkF

**Comment by amir-qayyum-khan** [comment]
i will look into this
