### ISSUE TITLE
add table to database for country code look-ups

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2990]
re-dash (bi) users would like to have a look up table of country codes to country names, to make look ups easier. 

This would be the same data as what we use in JavaScript currently.

**Comment by amir-qayyum-khan** [comment]
@pdpinch i am going to create a able in profile app and will run this data migration to populate this
https://raw.githubusercontent.com/olahol/iso-3166-2.js/master/data.csv

**Comment by pdpinch** [comment]
Ah good. I think it makes sense to  include the regions as well as the countries. Does it make sense to normalize that data though?

**Comment by pdpinch** [comment]
Also, is it possible to base the migration off the data file included in the npm package, just to keep things consistent on the front-end and the back-end?

**Comment by amir-qayyum-khan** [comment]
thiss is what i am going to do @pdpinch

**Comment by Ferdi** [comment]
We need geo coordinates  as well. I used https://developers.
google.com/public-data/docs/canonical/countries_csv

In redash queries

**Comment by pdpinch** [comment]
If we include a table for https://developers.google.com/public-data/docs/canonical/countries_csv then we don't need to normalize the data from https://raw.githubusercontent.com/olahol/iso-3166-2.js/master/data.csv

I suppose it would be nice to have geo coordinates for the regions as well, but I don't want to slow this down to much. That could be a follow up, once we've identified a data source.

**Comment by amir-qayyum-khan** [comment]
i can use both sources

- Can make to tables `Country` and `CountrySubDivision`
- Will load https://developers.google.com/public-data/docs/canonical/countries_csv into `Country`
- Will load  https://raw.githubusercontent.com/olahol/iso-3166-2.js/master/data.csv into `CountrySubDivision`

@pdpinch @Ferdi

**Comment by Ferdi** [comment]
How about we start with countries only first and then decide if we need countrysubdivision ?
Also, here is the list in a sql like format, if that's helpful https://goo.gl/7t9fi2

**Comment by amir-qayyum-khan** [comment]
oops, i am done with both, just testing
