### ISSUE TITLE
Add valid authorization to rest API for courses/programs

### ISSUE THREAD

**Issue by justinabrahms** [mitodl/micromasters#30]
Who should be able to read? All users? Logged in, paying users?

Who should be able to write?

**Comment by pdpinch** [comment]
Given our division between static pages and react pages, I think we're safe limiting read on the API to logged in users. 

I don't know enough about the CMS (Wagtail?) to know about write on the API. For now, I don't think we need write on the API (as long as you make admin views) -- as @noisecapella requested. 

- Peter

**Comment by justinabrahms** [comment]
Going to wait on #2 before I start on this (so, consider this ticket blocked until then). The two API endpoints are marked as read-only for now, so that should be a fine subset until that gets in.

CMS will be read only, unless you use the admin site.

**Comment by pdpinch** [comment]
Two questions @justinabrahms 

1. Does this still need to be done?
2. Is there enough definition?

**Comment by justinabrahms** [comment]
There is no current write API. You can use the django admin. I'm fine with things as they exist now, but there may be some requirements that I've not tracked (doubt it) which require this.

I think it's safe to close. We can always create another if it becomes an issue.

**Comment by noisecapella** [comment]
We don't require authentication for getting information from these APIs FYI, not sure if that's a problem here but it would be good to add it so that it's consistent with the rest of the dashboard

**Comment by Ferdi** [comment]
I closed because of Justin's last comment. Feel free to reopen.

**Comment by noisecapella** [comment]
That's fine, I'll create a more specific issue for it
