### ISSUE TITLE
Search: Preserve search URL after refresh

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#3003]
After a successful refresh the query parameters are removed from the URL. We should change this behavior to preserve them so the user can do multiple refreshes

**Comment by gsidebo** [comment]
_(Copied over from duplicate issue I created...)_

Steps to reproduce:

1. Load the learner's search page (`/learners`)
1. Apply 1+ filters
1. Reload the page
1. Reload the page a second time

Expected: The filters and the querystring remain unchanged.

Actual: On the first refresh, the querystring parameters disappear, but the filters remain. On the second refresh, the filters disappear as well.
