### ISSUE TITLE
Search filters are being removed on page reload

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#3007]
Steps to reproduce:

1. Load the learner's search page (`/learners`)
1. Apply 1+ filters
1. Reload the page
1. Reload the page a second time

Expected: The filters and the querystring remain unchanged.

Actual: On the first refresh, the querystring parameters disappear, but the filters remain. On the second refresh, the filters disappear as well.

**Comment by pdpinch** [comment]
I think this is a dupe of #3003?

**Comment by gsidebo** [comment]
so it is!
