### ISSUE TITLE
Exams: update all Pearson profiles

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3025]
Since Pearson staff have been tweaking some profiles, we can't be confident in the state of all our profiles in their system. To ensure everything is synchronized, we should force an update of all profiles.

**Comment by rhysyngsun** [comment]
All we need to do to trigger this is set `ExamProfile.status = ExamProfile.PROFILE_PENDING` on all profiles and save via `save()` so that `updated_on` gets updated too.

**Comment by rhysyngsun** [comment]
Propose we run this code:

```python
from exams.models import ExamProfile

for exam_profile in ExamProfile.objects.iterator():
    exam_profile.status = ExamProfile.PROFILE_PENDING
    exam_profile.save()
```

**Comment by rhysyngsun** [comment]
Apparently I was incorrect, we *are* using `updated_on` from `Profile`, so we need to address that first.
