### ISSUE TITLE
Hidden search facets create 10px of blank space

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#3026]
![ss 2017-04-07 at 16 30 37](https://cloud.githubusercontent.com/assets/14932219/24818785/d75770e8-1baf-11e7-9e46-320c449c8328.png)

When a search facet is hidden because it has no results, it still applies a bottom margin of 10px and creates empty vertical space

**Comment by rhysyngsun** [comment]
I actually fixed this in my learner search PR because it is more evident since we hide many facets to learners: https://github.com/mitodl/micromasters/pull/2908/files#diff-778179610a38b3dd0905c5fea2d42b0d

**Comment by pdpinch** [comment]
So does that mean this can be closed now?

**Comment by pdpinch** [comment]
I'm assuming this is fixed by now.
