### ISSUE TITLE
Exams: delete all exam authorizations from pilot

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3027]
Now that the pilot period is over, we should delete all outstanding exam authorizations. Existing authorizations use the old exam module scheme, which won't work beginning with the May exam offerings. 

### questions:
- [ ] Is it safe to delete all authorizations, or do we have to be careful to only delete authorizations that did not result in exam attempts?

**Comment by rhysyngsun** [comment]
One issue we need to reconcile is that currently if we delete authorizations, the next time a user updates their profile or enrollment we will see that recreated. That's less than ideal. We had talked in the past of actually tracking exam runs in the DB and only creating authorizations when an upcoming one was present.

**Comment by rhysyngsun** [comment]
Addressed differently in #3085
