### ISSUE TITLE
Move blankWorkHistoryEntry into a function in util/util.js so we can test it

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#303]

**Comment by aliceriot** [comment]
what sorts of tests do we need to write for it?

**Comment by aliceriot** [comment]
are you thinking tests to catch possible regressions?

**Comment by noisecapella** [comment]
Yes, and just for code cleanliness it seems more logical to locate state stuff in utils or a reducer than in a React component

**Comment by aliceriot** [comment]
gotcha, sounds good to me.
