### ISSUE TITLE
use ES search templates to avoid breaking percolate when search index is updated

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#3039]
Our approach to sending automatic emails to users that match some search query is not compatible with any changes to the structure of our index. Right now we store these queries in their entirety, and attempting to run those queries on a new index structure would fail. We need some way to store the search filters that our staff users want to trigger an automatic email, and a straighforward way to adapt those filters when the structure of the index changes.

Our proposed solution involves ES [search templates](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-template.html). We're hoping that we can create and maintain a search template in such a way that basic search filter info (ie: filter name & value) can be sent as inputs to the template, and the full desired query would be generated.

Here's a rough outline of the changes we would be making:
* Store an abstract representation of query when users want an auto-email on some query 
* Create the first version of an ES search template that covers all possible search filters from searchkit
* On reindex, generate percolate queries from search template

**Comment by noisecapella** [comment]
I'm not sure we need a search template for this. Why not do the query rendering in Python instead? We will need to do the query parsing in Python so it seems like it would be cleaner to keep both together in the same language, where they can also be easily tested

**Comment by noisecapella** [comment]
Closing because we decided that this wasn't a good solution to the problem of out of date percolate queries
