### ISSUE TITLE
Fix ordering for courses in the 'Course' facet

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#3040]
![ss 2017-04-10 at 16 09 55](https://cloud.githubusercontent.com/assets/14932219/24880375/2a9e852a-1e08-11e7-9581-f8f3004d76ee.png)

The ordering for courses in the 'Course' facet used to be the order of the courses in the program, but is now ordering alphabetically. This was done in error and should be switched back

**Comment by amir-qayyum-khan** [comment]
on local instance and latest master it is sorting course on the base of position.

<img width="370" alt="screen shot 2017-04-11 at 12 03 01 pm" src="https://cloud.githubusercontent.com/assets/10431250/24896569/ed3596a4-1eae-11e7-8a00-eb92ff67814d.png">

**Comment by amir-qayyum-khan** [comment]
somehow my https://micromasters-rc.herokuapp.com/ access is revoked

**Comment by gsidebo** [comment]
@amir-qayyum-khan i introduced this regression by accident and there's a 1-line fix. i'll take this one

**Comment by amir-qayyum-khan** [comment]
sure go a head please
