### ISSUE TITLE
Small copy change to "Future Semester Dates" in wagtail

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#3045]
There is a new section in Wagtail for "Future Semester Dates". When future semester dates are added, they show up on the program marketing page. (See https://micromasters.mit.edu/dedp/) The current copy is:

"[Semester name]: Courses start [date]"
ex. "Fall 2017: Courses start Sept. 26, 2017"

Change this to 

"[Semester name]: starts [date]"
ex. "Fall 2017: starts Sept. 26, 2017"

**Comment by amir-qayyum-khan** [comment]
<img width="450" alt="screen shot 2017-04-13 at 4 38 58 pm" src="https://cloud.githubusercontent.com/assets/10431250/25003211/bd21660e-2067-11e7-8120-f1d532e0a04d.png">
