### ISSUE TITLE
Update documentation and add scripts for OS X so that webpack-dev-server runs locally but everything else runs via Docker

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#307]
This will remove the need for docker-osx-dev. We will need to update our handling of the host string since right now it assumes the dev server host is the same as the Django host. We will need to figure out how to reference the host IP address from within docker-machine, and we should add a script to let OS X users start the dev server more easily (this would be used by docker-compose.yml too)

**Comment by giocalitri** [comment]
#356 fixed this: closing
