### ISSUE TITLE
Exams: Update Pearson TOS language

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3086]
When we display an SSO link to the Pearson site, we need to include a disclaimer, at the request of MIT OGC. @roberthouse54 will work on a design that accommodates the following text:

> ATTENTION: You are being redirected to Pearson VUE’s website.
 
> You acknowledge that by clicking Continue, you will be leaving the MITx MicroMasters website and going to a third-party website over which MIT’s MITx does not have control, and that you accept the Pearson VUE Business Group’s Terms of Service. MIT is not responsible for the content of third-party sites hyper-linked from the Pearson VUE website, nor does MIT guarantee or endorse the information, recommendations, products or services offered on third-party sites.
 
> By clicking Continue, you further acknowledge, understand, and agree that:
 
> **MIT makes no representations or warranties of any kind regarding the facilities or services provided by Pearson VUE, including, but not limited to, at any Pearson VUE authorized testing center. MIT hereby disclaims all representations and warranties, express or implied, including, without limitation, accuracy and fitness for a particular purpose. To the extent permissible by law, you assume the risk of injury or loss or damage to property while visiting any Pearson VUE testing center for in-person testing for any MITx MicroMasters course (the “Purpose”). You hereby release MIT and all of its officers, directors, members, employees, volunteers, agents, administrators, assigns, and contractors (collectively “Releasees”), from any and all claims, demands, suits, judgments, damages, actions and liabilities of every kind and nature whatsoever, that you may suffer at any time as a result of the Purpose.**

**Comment by roberthouse54** [comment]
Can we do something like this?

![image](https://cloud.githubusercontent.com/assets/20047260/25196751/986b2c62-250f-11e7-92b2-1ad68cad1e00.png)
