### ISSUE TITLE
UI for multiple programs in dashboard

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#310]
Now it looks like this:

![screen shot 2016-05-12 at 2 55 43 pm](https://cloud.githubusercontent.com/assets/1005204/15226657/a32c666e-1851-11e6-91a8-d56cf014600f.png)

**Comment by roberthouse54** [comment]
We have decided to have a UI where the user can switch which program they are looking at, and this will switch the entire context of the application. An analogy would be how you can switch accounts in Google, if you have multiple profiles.

![multiple_programs_ui](https://cloud.githubusercontent.com/assets/20047260/17332747/c5deca44-589d-11e6-9132-39f733efb4cd.png)

**Comment by pdpinch** [comment]
LGTM. Please close this issue once invision is updated. 

I'll open a new issue for implementing this change.

**Comment by roberthouse54** [comment]
Added to Invision: https://invis.io/BA85FXDTX
