### ISSUE TITLE
For non-FA courses, do not display Order Summary after clicking Pay Now button

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#3105]
This issue addresses a problem that we have in SCM, where the final exam (which is configured as an edX course) has a different price than other courses. The proposed solution is to limit the places where we display the cost of courses in the UI, so that the final source-of-truth for course pricing is edX. 

Solution:

1) For non-FA programs, we will skip the order summary page that is shown after the user clicks "Pay Now", and instead link directly to the edX site where users can complete the enrollment.

2) For all programs, remove the course price displayed on the Pay Now button in the modal. (see below)

![image](https://cloud.githubusercontent.com/assets/20047260/25391940/620346ec-29a5-11e7-8736-21fd07cb8706.png)

This should (mostly) solve the issue of displaying the course cost, since the modal and the order summary page are the 2 main places where we display the course price that may be leading to user confusion.

**Comment by amir-qayyum-khan** [comment]
@roberthouse54 @pdpinch on edX where should we link user

> For non-fa instead link directly to the edX site where users can complete the enrollment.

**Comment by pdpinch** [comment]
There should be existing code for this, because there is a link from the order summary view. I'm pretty sure it's the `enrollment_url` on the course run, possibly with a failover to a constructed URL based on the course key. 

If you can't find the existing code, let me know.

**Comment by pdpinch** [comment]
Ugh. `enrollment_url` was the wrong answer. 

I think the existing code called a checkout function. We should have stuck with that. 

See https://github.com/mitodl/micromasters/blob/e5f6866b3879f04e3e5711605dac4d2ff08671fa/static/js/components/OrderSummary.js#L100
