### ISSUE TITLE
Program Page: Use Course Descriptions from the CMS

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3107]
We have a section in the CMS for course teams to enter course descriptions, but they're not actually used anywhere. 

In the course card on the program page, we display course descriptions pulled from the courses model. This doesn't make any sense because course teams don't have access to change those fields. 

So, we should update the Program Page template to pull course descriptions from the CMS instead of from the course model. 

### acceptance criteria:

- [ ] migrate existing course descriptions from course model to CMS
- [ ] update Program Page template to pull from CMS
- [ ] update admin for course model to indicate that the description is deprecated

### future issues:

- [ ] remove description from course model

**Comment by pdpinch** [comment]
@annagav let me know if we should change the description based on our conversation today.

**Comment by annagav** [comment]
@pdpinch I think the description is accurate, so I am going to leave it as it is.

**Comment by annagav** [comment]
@pdpinch, Do we want to do the same for title of the course?
