### ISSUE TITLE
search: Align hit counts in search facets

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3114]
Adding a scrollbar in #3076 threw off the horizontal alignment of the hit counts in the search facets:

<img width="275" alt="screen shot demonstrating offset numbers" src="https://cloud.githubusercontent.com/assets/132355/25440277/fa9b4a18-2a6c-11e7-9038-350c1dd2716a.png">

**Comment by rhysyngsun** [comment]
@roberthouse54 any thoughts on how this should get addressed design-wise? the reason why this is occurs is more obvious on non-OSX browsers (thanks to OSX hiding the scrollbar):
![selection_063](https://cloud.githubusercontent.com/assets/28598/25716247/6aac920c-30cc-11e7-9d18-bc1d312d62fb.png)

I'm thinking best option is to right-pad the other numbers so they line up with the Current Residence numbers.

**Comment by rhysyngsun** [comment]
So, there's an additional difficulty here which is that scrollbars have no standard width across browsers so there's no single padding value that will work for all them:

Chrome:
![selection_064](https://cloud.githubusercontent.com/assets/28598/25717297/03a41090-30d0-11e7-8029-3d734c6e840a.png)

Firefox:
![selection_065](https://cloud.githubusercontent.com/assets/28598/25717301/09759f98-30d0-11e7-8bc3-99227ccc5462.png)

I would imagine Safari and others are also slightly off. Thoughts?

**Comment by pdpinch** [comment]
@roberthouse54 any advice on this?

**Comment by roberthouse54** [comment]
I think we should just accept that there will be a slight discrepancy here... or we can pad for the widest scrollbar. But I do not think a misalignment of a few pixels is much of an issue to worry about.

**Comment by rhysyngsun** [comment]
@pdpinch any preference?

**Comment by roberthouse54** [comment]
I wonder if it is best to just not do anything about this at all, and live with the misalignment. It is mostly an issue with OSX hiding the scrollbars. For visible scrollbars, I do not think it looks too weird, and we cannot probably get them to align anyway without substantial indentation.

**Comment by rhysyngsun** [comment]
That sounds fine to me, @pdpinch since you originally opened this, could you close if you agree?
