### ISSUE TITLE
Fix Modal Titles on Profile

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#3118]
The modal titles for Education and Employment are quite clunky, the way they are currently implemented.

- All of the modals currently have two effective titles. (See below) For example, "Education" and then under that "Edit Education". There should only be a single title for each modal. 
![image](https://cloud.githubusercontent.com/assets/20047260/25495236/72b9ae76-2b4a-11e7-8fbb-920d4c6468ab.png)
- The Add/Edit Education modals also should describe which type of degree is being edited or added. For example, after you have clicked Add degree in the High School card, there is no indication in the modal that you are adding a High School degree. If the user forgets what link they clicked, they might enter the wrong information.

Solution:
- Each modal will have a single title.
- The title will include the type of degree being added/edited.

Ex.
Add a High School Degree
Edit bachelor's degree

On the user profile, if they click "Add degree" and no degree type is specified, the title will be "Add a degree".

For employment, the title will always be either "Add Employment" or "Edit Employment"

**Comment by pdpinch** [comment]
@roberthouse54 does this still need to be fixed?

**Comment by roberthouse54** [comment]
Yes it does.
