### ISSUE TITLE
Selected filters should be bold in learner search page

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#3130]

**Comment by pdpinch** [comment]
Is this a UX suggestion for @roberthouse54 or is this a bug?

**Comment by roberthouse54** [comment]
I looked at this briefly, and didn't see any CSS selector for a "selected" state, so I think we did not have this before.

**Comment by pdpinch** [comment]
So... @roberthouse54 should we do this? Can you do it?

**Comment by pdpinch** [comment]
This has been done for nearly a year...
