### ISSUE TITLE
Textbox disappears in learner page when there are no matches

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#3131]
To reproduce:
 - select an education level on the learner search page
 - type in text in the search box. If there is at least one result there should be the list of results and a textbox. If there are no results all filters and text boxes are removed from the UI: 
![screenshot from 2017-05-03 10-40-04](https://cloud.githubusercontent.com/assets/863262/25665893/efbcad46-2fec-11e7-83d7-06189c0fe949.png)

**Comment by amir-qayyum-khan** [comment]
Already fixed.
<img width="1253" alt="screen shot 2017-06-06 at 1 32 13 pm" src="https://cloud.githubusercontent.com/assets/10431250/26820532/983c839e-4abc-11e7-98e0-3421a879b9e5.png">
