### ISSUE TITLE
Make "industry" a select / dropdown element

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#315]
Can we make this a select element ?

![industry](https://cloud.githubusercontent.com/assets/125561/15259235/01df488a-191e-11e6-98f7-64c17b564b14.png)

It looks like this is the list linkedin uses https://developer.linkedin.com/docs/reference/industry-codes

**Comment by noisecapella** [comment]
Are those industry codes copyrighted? Is that something that you can do to a list of codes?

**Comment by pdpinch** [comment]
LinkedIn is offering the list as part of their API. Unless the pending Google/Oracle suit ends horribly, APIs aren't copyrighted. 

Also, I'm not sure we actually need the codes. We're mostly just interested in the user-facing labels.
