### ISSUE TITLE
Mail tokens are not replaced if they are interrupted with markup

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#3164]
Probably a minor issue but wanted to report it anyway. If you add `[PreferredName]`, highlight part of it and bold it, the HTML becomes something like `[<b>Preferred</b>Name]` and it won't get transformed into `%recipient.preferred_name%` anymore

**Comment by aliceriot** [comment]
do you think we could easily use BeautifulSoup on the backend to find the macro tokens (like `[PreferredName]`) and remove tags in them? We're using it to generate the plain-text fallback already, I set that up but don't have much experience with the library.

**Comment by noisecapella** [comment]
I don't have much experience with BeautifulSoup either but I imagine it would be difficult to separate the tags from the text. Maybe there's a way to prevent the markup from being inserted into that text in the first place. I'm not sure if the editor component has a concept of immutable text

**Comment by noisecapella** [comment]
I looked into this briefly last week and I think the only reasonable solution is to validate the text before it's submitted. We can do something like `get_tags(stripped_html(body)) == get_tags(body)`
