### ISSUE TITLE
UserFactory does not create social auth

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#3166]
This means some data (e.g. ProfileSerializer) generates with `None` values.

**Comment by noisecapella** [comment]
It looks like it's a `SerializerMethodField` which uses `get_username` to return `get_social_username(obj.user)`, which should exist for most users

**Comment by noisecapella** [comment]
This issue is about updating our tests and `UserFactory` to create a social auth with a username.

**Comment by rhysyngsun** [comment]
This is trickier than expected because there are some places in our tests where we expect this not to happen.
