### ISSUE TITLE
Course status: clarify "Passed" label for FA courses 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3176]
Until #3046 lands, we can now display "Passed" for FA courses where the user has failed the proctored exam. 

For FA courses, instead of displaying "Passed" we should display "Final Grade coming soon" -- an interim solution until the more complete #3046 is done. 

![screenshot-micromasters-rc herokuapp com-2017-05-11-20-55-36](https://cloud.githubusercontent.com/assets/430126/25977821/3c96a1b2-368c-11e7-9150-36254864285d.png)

**Comment by aliceriot** [comment]
functionality looks good!
