### ISSUE TITLE
Mail: loading body of mail campaign fails

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3181]
### Steps to reproduce (on rc):

1. Go to learner search as a staff member, `/learners/`
2. Perform a query (can be a search for one user)
3. Click "E-mail these Learners" and choose "Create an email campaign"
4. Go to the automated e-mails interface, `/automaticemails/`
5. Click on the edit link for the email you created

### Expected Behavior

The saved email should display.

### Actual Behavior

The dialog box is empty.

**Comment by aliceriot** [comment]
I think this is related to the change to add the template variables for mailchimp. I've discovered, also, that it will work correctly when the page first loads (i.e. the first time the 'edit' dialog is opened) but it will fail thereafter. This is related to the changes to how we clear the `EditorState` object that the email composition dialog uses, I think.

@annagav do you have any ideas about this?

**Comment by aliceriot** [comment]
yeah, before `this.editorState` was set to `null` when the `clearEditorState` method gets called, but now it is instead being set to `EditorState.createEmpty()`. So now in the `componentWillReceiveProps` function we check `R.isNil(this.state.editorState)` to see if we need to call `editorStateFromProps` again, but `this.state.editorState` will never be nil. So instead we need to devise some way to check whether `this.state.editorState` is empty - perhaps by inspecting the `ContentState` object that lives on there? I'm not sure, I took a quick look through the draft.js docs but didn't see anything super obvious.

**Comment by aliceriot** [comment]
this looks like what we want! https://stackoverflow.com/questions/38064703/draft-js-editor-is-empty
