### ISSUE TITLE
Bug: can't validate country on the the education profile

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#319]
Steps to reproduce:

1. login
2. navigate to https://micromasters-ci.herokuapp.com/profile/education
3. Click to add a degree, for example high school
4. Fill out all the fields. 

Expected behavior:

Form is validated and the pop-up closes. 

Actual behavior:

A red validation message displays "Country is Required." The pop-up does not close.

**Comment by pdpinch** [comment]
@annagav let me know if you have any thoughts about possible causes of this.

**Comment by noisecapella** [comment]
This is due to a bug in #302, not anything specific to the education tab.
