### ISSUE TITLE
Show selected recipients when editing an email campaign

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#3202]
When users create a new email message or campaign, they see the recipients as filters. However, when users are editing an email campaign, the recipients are not shown. 

- We should show the recipients when editing email campaigns. The recipients are not editable... this is view only.
- We should also change the name of that modal to "Edit Email Campaign" (currently it is "Edit Message"

![image](https://cloud.githubusercontent.com/assets/20047260/26160955/8f3b977a-3af0-11e7-96f9-1f74d6fb9a90.png)

**Comment by amir-qayyum-khan** [comment]
@pdpinch @noisecapella @giocalitri @aliceriot 

Currently there is no way to save recipients on servers side what approach should i use

1) should i save comma separated recipients on model?
or any thing else is in ur mind?

**Comment by aliceriot** [comment]
I'm not sure the exact approach, but the query that is used to generate the automatic email is saved as a percolate query, right? perhaps we can use that saved percolate query to generate the labels and so on that we would want to display?
