### ISSUE TITLE
Fix re-enroll link for passed edx course but failed exam

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#3266]
This is present in the dashboard refactor PR but at the moment I don't think the backend will ever let the user know there is another edx course available if the previous one was passed. We should change that to also check exam status.

More info: https://github.com/mitodl/micromasters/pull/3172#issuecomment-305547704

**Comment by pdpinch** [comment]
@amir-qayyum-khan can you check if this is still an issue?

**Comment by amir-qayyum-khan** [comment]
#### 
 dashboard_state_094_create_exams_edx_✔_exam_✖_with_new_offering_can_schedule_more_exams_failed_one_exam
![dashboard_state_094_create_exams_edx_ _exam_ _with_new_offering_can_schedule_more_exams_failed_one_exam](https://user-images.githubusercontent.com/10431250/42453823-5439010c-83a7-11e8-95e9-bd5e57e4f98a.png)

#### dashboard_state_095_create_exams_edx_✔_exam_✖_with_new_offering_can_schedule_more_exams
![dashboard_state_095_create_exams_edx_ _exam_ _with_new_offering_can_schedule_more_exams](https://user-images.githubusercontent.com/10431250/42453856-6a7e1e70-83a7-11e8-88f7-438b9a9f5afe.png)

#### dashboard_state_096_create_exams_edx_ _exam_ _with_new_offering_can_schedule_failed_one_exam
![dashboard_state_096_create_exams_edx_ _exam_ _with_new_offering_can_schedule_failed_one_exam](https://user-images.githubusercontent.com/10431250/42453919-961cc20c-83a7-11e8-86b0-12bbb3d6e556.png)

#### dashboard_state_097_create_exams_edx_ _exam_ _with_new_offering_can_schedule
![dashboard_state_097_create_exams_edx_ _exam_ _with_new_offering_can_schedule](https://user-images.githubusercontent.com/10431250/42453943-ab2296b8-83a7-11e8-99a4-1c15c5ba2512.png)

#### dashboard_state_098_create_exams_edx_ _exam_ _with_new_offering_more_exams_failed_one_exam
![dashboard_state_098_create_exams_edx_ _exam_ _with_new_offering_more_exams_failed_one_exam](https://user-images.githubusercontent.com/10431250/42453955-b7e8b1d4-83a7-11e8-8258-c6e1d0de3606.png)

#### dashboard_state_099_create_exams_edx_✔_exam_✖_with_new_offering_more_exams
![dashboard_state_099_create_exams_edx_ _exam_ _with_new_offering_more_exams](https://user-images.githubusercontent.com/10431250/42453980-c669515a-83a7-11e8-812b-5d2306607fbd.png)

#### dashboard_state_100_create_exams_edx_✔_exam_✖_with_new_offering_failed_one_exam
![dashboard_state_100_create_exams_edx_ _exam_ _with_new_offering_failed_one_exam](https://user-images.githubusercontent.com/10431250/42454029-e41775ba-83a7-11e8-87c5-6f6ffeda26f0.png)

#### dashboard_state_101_create_exams_edx_ _exam_ _with_new_offering
![dashboard_state_101_create_exams_edx_ _exam_ _with_new_offering](https://user-images.githubusercontent.com/10431250/42454035-e8a7d994-83a7-11e8-9096-8f71502ee033.png)
