### ISSUE TITLE
CMS: Deleting ProgramCourse from CMS leads to validation error

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3275]
### Steps to reproduce:

1. Go to a Program Page in the CMS
2. If there isn't already a Course (aka ProgramCourse), add one and save the page. 
3. Delete the Course. Save the page. 
4. Add the course back in again. 

### Expected Result

Should be able to add back a course (ProgramCourse) on the program page that has been deleted. 

### Actual Behavior

Wagtail returns a validation error `Program course with this Course already exists.`

Note: I'm not sure that we even need to validate this. Is there a problem if a course is associated with multiple program pages?

**Comment by annagav** [comment]
About the last note. I spoke to @giocalitri about this when I worked on PR #3165, he said that a course can belong to only one program.

**Comment by pdpinch** [comment]
I'm not really trying to create a new relationship. Just re-use the existing one between the course and the program page.

**Comment by annagav** [comment]
I think it is again one of those things that Wagtail does when you delete an object. I think making the relationship between Course and ProgramCourse one-to-many will solve this problem.

**Comment by annagav** [comment]
@pdpinch, It looks like I don't need to change anything. When the admin user deletes the `ProgramCourse` he has to 'publish' the change first. Just saving as a draft is not enough, since wagtail will keep the `ProgramCourse` in the published version. After you finalized the deletion of the `ProgramCourse` by 'pulishing' you can then add a new ProgramCourse for that course. That should not cause the error.

**Comment by pdpinch** [comment]
Ok. I'll try that.

**Comment by pdpinch** [comment]
That worked and I was able to get the page publishing again. 

This feels like a less than idea workflow to me though. I'm not sure what to tell the course team so they can avoid this happening again. 

Is there any reason why we need this uniqueness constraint?

**Comment by annagav** [comment]
If we allow few `ProgramCourses` to be created for the same course, the description of which `ProgramCourse` would you expect to be displayed on the program page?

**Comment by pdpinch** [comment]
I think we should just display them all. The CMS user will be able to preview and if there's too many on the page, they'll delete them.

**Comment by annagav** [comment]
On the ProgramPage we display the `Course`s not `ProgramCourse`s.  We only use `ProgramCourse` for the description that the admin user might have entered. So when the serialization of courses is happening for each course it checks if an associated `ProgramCourse` has a description and uses that. We did this in PR #3165

**Comment by pdpinch** [comment]
I can't think of a way to solve this other than to be sure to publish CMS changes after deleting a course from a program page.
