### ISSUE TITLE
Add real text to Terms of Service

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#328]
We may want to do this at the same time as #280 

The text is in a google doc at https://goo.gl/EgJRvD

If there is a preferred format (markdown? HTML?), let me know.

**Comment by noisecapella** [comment]
HTML should be fine

**Comment by amir-qayyum-khan** [comment]
@pdpinch  i dont have access on this document.

**Comment by pdpinch** [comment]
asked and answered =)

**Comment by Ferdi** [comment]
What is the scope of this issue ?   Are you aiming for the final version : 

![tos](https://cloud.githubusercontent.com/assets/125561/15395872/7f8e9168-1da7-11e6-8238-0ac0bc229406.png)

**Comment by pdpinch** [comment]
This issue is just the text from https://goo.gl/EgJRvD. #280 is the design

@amir-qayyum-khan , I thought you were working on #280 as well?
