### ISSUE TITLE
repackage redux-rest as a standalone module

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#3293]
We should publish the redux-rest library as a separate module, so that we can use it in all our projects without needing to copy+paste code or anything like that. Perhaps other people will find it helpful too!

The first problem, though, is that we would need to come up with a new name, since [redux-rest](https://github.com/Kvoti/redux-rest) is already taken.

maybe restful-redux? redux-hammock? naptime? chamomile? I could go on with these!

@noisecapella any thoughts on this?

**Comment by noisecapella** [comment]
I like redux-hammock, it's at least a little obvious what it's for. We could even go with `redux-🛏` if we wanted to make it difficult to type

**Comment by aliceriot** [comment]
ahaha I like it!

```js
import 🛏 from '🛏';
```
