### ISSUE TITLE
2 users missing social auth objects

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3299]
MultipleObjectsReturned: get() returned more than one UserSocialAuth -- it returned 2!

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/288659721/

```
MultipleObjectsReturned: get() returned more than one UserSocialAuth -- it returned 2!
  File "dashboard/tasks.py", line 101, in batch_update_user_data_subtasks
    UserSocialAuth.objects.get(user=user)
  File "django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 389, in get
    (self.model._meta.object_name, num)

user "Juja08" does not have python social auth object
```

**Comment by pdpinch** [comment]
I feel like this has happened before. We weren't able to identify the root cause, so we just repaired the users accounts.

**Comment by pdpinch** [comment]
The last occurrence was in #2276

**Comment by pdpinch** [comment]
@amir-qayyum-khan are you doing anything with this issue? If not, you should return it to ready so someone else can work on it.

**Comment by amir-qayyum-khan** [comment]
```unique_together = ('provider', 'uid')```

https://github.com/python-social-auth/social-app-django/blob/master/social_django/models.py#L75

can i check records for `Juja08`

@pdpinch

**Comment by pdpinch** [comment]
That user has two social auths: same username and provider, but different uid.

IIRC, @giocalitri speculated that that could happen if the user's email address changed at edX. In the past, we just deleted one of the social auths. 

I'm wondering if we could just use the most recent one? Or maybe change the unique_together to be provider and username (I'm a little scared of that).

**Comment by pdpinch** [comment]
@amir-qayyum-khan points out that the 2nd social auth has a different username. I think this suggests that the user 

1. Logged in to MM through edX and created a MM account with 1st social auth
2. Logged out of edx.org, but not MM.
3. While still logged in to MM, somehow logged into edX again, with a different edX account. This creates second social auth

**Comment by amir-qayyum-khan** [comment]
there is issue with https://micromasters.d.mitx.mit.edu/account/settings
@mitodl/devops @blarghmatey  can you check?

**Comment by pdpinch** [comment]
Here are some more detailed steps to reproduce:

1. Log in to the MicroMasters portal with your 1st edX account
2. Logout of edX
3. Log out of the MicroMasters portal 
4. Navigate to /login/edxorg -- this should redirect you to the edX login page
5. Login with a different edX account (you can create a new one)
6. You should now have two social auth instances on the MicroMasters portal. You can confirm this by looking at https://micromasters-ci.herokuapp.com/admin/social_django/usersocialauth/
