### ISSUE TITLE
adjust exam results

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3309]
We need to make adjustments to the results of the first round of exams. 

It's possible that we may need to do this every time an exam is offered.

**Comment by pdpinch** [comment]
This is blocked until we get access to the necessary data.

**Comment by gsidebo** [comment]
Data has been sent over, but has some questionable numbers. I can move this along while we wait for some answers

**Comment by gsidebo** [comment]
Setting to blocked again. We need to find out what's going on with the 100+ scores in the csv, and what exactly the id columns are referring to

**Comment by rhysyngsun** [comment]
@pdpinch could you clarify which column in the CSV matches the `ProctoredExamGrade.id` column? We suspect it's `proctoredexam_id` but obviously want to be sure.

Additionally, we noted there were some corrected scores higher than 100% in the data. It sounds like it's desired to keep those and that raises questions/concerns beyond the scope of the original issue here I think.

**Comment by pdpinch** [comment]
We received new data that limits the score to range of 0 - 100.
