### ISSUE TITLE
Suppress "in progress" grades for some courses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3313]
Some courses, like the SCM Comprehensive Final Exam (CFx) shouldn't display in-progress grades before the grades are finalized. The course team doesn't want to mislead learners while the results of the course are still being interpreted. 

This needs to be addressed before the next CFx is offered, in February 2018.

**Comment by aliceriot** [comment]
How about if we just added a boolean (`should_display_progress` or something along those lines) to the course which controls whether we return the `current_grade` before the grades are finalized?

**Comment by aliceriot** [comment]
Seems like the most straightforward thing to me, but I'm not super familiar with all of the code around this stuff

**Comment by pdpinch** [comment]
Ah, so this would be all in the dashboard API?

**Comment by aliceriot** [comment]
yeah

**Comment by pdpinch** [comment]
@aliceriot do I set this on the course or the course run?

**Comment by aliceriot** [comment]
On the course, there should just be a little check-box in the admin UI.
