### ISSUE TITLE
Dashboard: Let learner re-enroll after failing a course

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3322]
Currently if a (DEDP) learner has failed a course, but also missed the payment deadline, we show them a "Pay Now" message. There's no point in them paying for a course they didn't pass though. We won't let them take the proctored exam. 

Instead of "Pay Now" we should display the "The course has ended. You didn't pass but you can re-enroll." message.

**Comment by pdpinch** [comment]
Here's an example of this happening in production. 

Dashboard API returns (excerpt):
```
                {
                    "id": 10,
                    "title": "Foundations of Development Policy: Advanced Development Economics",
                    "position_in_program": 4,
                    "description": "This\r\ncourse provides a\r\ndeeper dive into how to design and evaluate effective policies to\r\nimprove the lives of the poor. In this class, students will delve\r\ninto cutting-edge\r\nresearch and learn more about how to design\r\neffective experiments.",
                    "prerequisites": "",
                    "has_contact_email": true,
                    "can_schedule_exam": false,
                    "runs": [
                        {
                            "id": 32,
                            "course_id": "course-v1:MITx+14.74x+3T2015",
                            "title": "Foundations of Development Policy: Advanced Development Economics",
                            "status": "can-upgrade",
                            "has_paid": false,
                            "position": 1,
                            "course_start_date": "2015-09-21T04:00:00Z",
                            "course_end_date": "2015-12-10T04:00:00Z",
                            "fuzzy_start_date": "",
                            "enrollment_url": "https://www.edx.org/course/foundations-development-policy-advanced-mitx-14-740x-0",
                            "course_upgrade_deadline": "2017-09-09T04:00:00Z",
                            "final_grade": 0.0
                        }
                    ],
                    "proctorate_exams_grades": [],
                    "has_exam": true
                },

```

<img width="640" alt="screenshot 2017-06-21 11 13 45" src="https://user-images.githubusercontent.com/430126/27391742-c0d03faa-5672-11e7-832d-6ddc504151ba.png">

**Comment by aliceriot** [comment]
how can we tell they've failed? I thought that a 'failed' course run was indicated by `status == 'not-passed'`, they still have `status == 'can-upgrade'`

**Comment by pdpinch** [comment]
I have to look at this some more, but I think what we want to do is set `status = 'not-passed'` when the student has a final grade with `passed = False`.

**Comment by pdpinch** [comment]
@amir-qayyum-khan I want to run this by @roberthouse54 before we do any coding on it. I'm going to take it out of ready for the time being, and unassign you.

**Comment by roberthouse54** [comment]
I think your proposed solution is correct in the description. I might tweak the copy slightly:

"The course has ended. You didn't pass but you can re-enroll."

**Comment by pdpinch** [comment]
There is a selenium dashboard test that demonstrates this issue.

**Comment by amir-qayyum-khan** [comment]
@pdpinch there is not in current MM app

**Comment by pdpinch** [comment]
this is the test I had in mind: https://github.com/mitodl/micromasters/blob/master/selenium_tests/management/commands/snapshot_dashboard_states.py#L184-L191

Anna ran it yesterday and this was the output: 

<img width="1104" alt="screen shot 2018-06-06 at 8 57 36 am" src="https://user-images.githubusercontent.com/430126/41108380-602716c6-6a42-11e8-9931-527074069903.png">


the output should be the same as states 78-85, i.e. 

<img width="1094" alt="screen shot 2018-06-06 at 8 52 19 am" src="https://user-images.githubusercontent.com/430126/41108432-7d67cd84-6a42-11e8-8819-6077bfe7d409.png">

**Comment by amir-qayyum-khan** [comment]
but he is not fail just like the user in https://github.com/mitodl/micromasters/issues/3322#issuecomment-310111097

**Comment by pdpinch** [comment]
Ok, maybe we need a new test state then. Same as the one I mentioned above, plus the user failed?

**Comment by amir-qayyum-khan** [comment]
agree

**Comment by amir-qayyum-khan** [comment]
@pdpinch 

Now after apply new logic it is
```json
{
                    "id": 1,
                    "title": "Digital Learning 100",
                    "position_in_program": 1,
                    "description": "An introductory course to Digital Learning",
                    "prerequisites": "",
                    "has_contact_email": true,
                    "can_schedule_exam": false,
                    "exams_schedulable_in_future": [],
                    "has_to_pay": true,
                    "runs": [
                        {
                            "id": 1,
                            "course_id": "course-v1:MITx+Digital+Learning+100+Aug_2016",
                            "title": "Digital Learning 100 - August 2016",
                            "status": "not-passed",
                            "has_paid": false,
                            "position": 1,
                            "course_start_date": "2016-08-15T00:00:00Z",
                            "course_end_date": "2016-12-15T00:00:00Z",
                            "fuzzy_start_date": null,
                            "enrollment_url": null,
                            "final_grade": 0.0
                        }
                    ],
                    "proctorate_exams_grades": [],
                    "has_exam": true,
                    "certificate_url": "",
                    "overall_grade": ""
                },
```

<img width="834" alt="screen shot 2018-06-07 at 9 00 59 pm" src="https://user-images.githubusercontent.com/10431250/41111649-fca21b92-6a95-11e8-8637-eeaca81759e4.png">

- Course is end. Should we apply for reenroll, there is no future runs available. the json you provided me

**Comment by pdpinch** [comment]
If there's another run, we should show the Re-Enroll button -- similar to the conditions that allow for this dashboard state:

<img width="1094" alt="screen shot 2018-06-06 at 8 52 19 am" src="https://user-images.githubusercontent.com/430126/41108432-7d67cd84-6a42-11e8-8819-6077bfe7d409.png">

**Comment by amir-qayyum-khan** [comment]
@pdpinch i think it is omitting previous run https://github.com/mitodl/micromasters/issues/3327

**Comment by pdpinch** [comment]
Sorry, I misread the API results here. The user actually did pass, so they can pay. 

It still should all them to re-enroll, but that'a separate issue.
