### ISSUE TITLE
Display Exam grades in Staff view of learner’s profile page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3330]
As a staff member, I would like to be able to see a learner's exam grades when I view their profile (same as edx course grades)

**Comment by aliceriot** [comment]
oh, these should be included, are they not showing up?

**Comment by pdpinch** [comment]
Oh, I don't know how I missed this.

We are going to need to work on the layout, but I'll make a new issue for that once I talk to Rob.
