### ISSUE TITLE
Style profile privacy page like mock-ups 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#335]
/profile/privacy should look like https://invis.io/4E791TKU3#/156281163_Step_Four_-_Profile_Privacy

Notably, by changing to radio buttons, users will be able to see the options more easily.

**Comment by noisecapella** [comment]
We also need to move the email optin text from the work history tab to the privacy tab

**Comment by amir-qayyum-khan** [comment]
Made changes in UI.

<img width="1209" alt="screen shot 2016-05-23 at 9 21 24 pm" src="https://cloud.githubusercontent.com/assets/10431250/15477113/6e5a56ba-212c-11e6-8270-5aac1fcae6ba.png">
