### ISSUE TITLE
Emails with link to email address do not work

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#3360]
If in the learners page I create an email with a link to an email like`mailto:giovanni@example.com` I get an error.

This has been found by Kayli Maffei in production while trying to send an email. 

![screen shot 2017-06-28 at 3 05 50 pm](https://user-images.githubusercontent.com/1005204/27655456-732be708-5c13-11e7-8d98-ea3049ba7f5b.png)

**Comment by aliceriot** [comment]
I just checked and draft.js does leave `mailto` links alone, as far as I can tell, so I think we can just fix our validation to allow links with href matching `http|https|mailto:`,
