### ISSUE TITLE
Profile: typing location string that matches the suggestion leads to error

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3369]
See https://odl.zendesk.com/agent/tickets/9055

### Steps to Reproduce

1. Go to the education section of the profile, and add a new school. 
2. Paste in what seems like an acceptable location, like "Belo Horizonte, Minas Gerais, Brazil"
3. Instead of clicking on the suggestion, click on the save button

### Expected behavior

It should update the location and save the education entry

### Actual behavior

Save fails and the user gets the message `Location must contain city, state, country` which it looks like it does.

**Comment by pdpinch** [comment]
@mbertrand can you take a look at this?

**Comment by mbertrand** [comment]
Related issue: https://github.com/ubilabs/react-geosuggest/issues/284

I can fix this by directly modifying the above source code, but that isn't ideal (requires forking or submitting a PR).  Currently trying to override the component's default behavior from our own code but no luck so far.

**Comment by pdpinch** [comment]
Might be worth some consultation with @aliceriot or @noisecapella

**Comment by mbertrand** [comment]
Changing [these lines](https://github.com/ubilabs/react-geosuggest/blob/master/src/input.jsx#L40-L42)  in react-geosuggest's input.jsx file to:

```
  onBlur = () => {
    this.props.onSelect();
    this.props.onBlur();
  };
```
seems to fix the issue.  @aliceriot or @noisecapella any idea how to use react-fu to override this method from micromaster's profile_edit.js?
