### ISSUE TITLE
Profile: Omit "state" drop-down for countries that don't require it

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3371]
See https://odl.zendesk.com/agent/tickets/8896

Pearson requires that we provide state and province for US and CA, but no other countries. We can create a configurable list of countries for which we don't display the "state" drop-down. 

I don't think we'll change the list very frequently, so configuration can be in code or by environment variable.

**Comment by rhysyngsun** [comment]
We currently define it in code here: https://github.com/mitodl/micromasters/blob/master/exams/pearson/constants.py#L49-L52
