### ISSUE TITLE
If a user has submitted financial aid they should still be able to enroll in a course

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#3411]
If a user has not yet submitted financial aid they see this for a course they can enroll in:

![screenshot from 2017-07-17 13-58-10](https://user-images.githubusercontent.com/863262/28282316-028a82f4-6af8-11e7-98ba-5347f8c56490.png)

When they click 'Enroll' they see this:

![screenshot from 2017-07-17 13-58-18](https://user-images.githubusercontent.com/863262/28282334-10c3c3c6-6af8-11e7-936c-c7a77ae21db3.png)

The audit button is there but the 'Pay' button is disabled.

If the user submits a financial aid application which is not auto-approved they see this:

![screenshot from 2017-07-17 14-01-14](https://user-images.githubusercontent.com/863262/28282458-7fdf638c-6af8-11e7-8338-a5bfb4886376.png)

The 'Enroll' button is disabled, but the 'Enroll' button should have the same behavior as if they haven't yet submitted a financial aid application: A dialog should show with 'Pay' disabled but the 'Audit' button enabled

**Comment by annagav** [comment]
@roberthouse54, I think we need to update the text for the case when FA is pending and we show the course enrollment dialog. Something like: "You can audit the course for FREE and upgrade later. (Payment is required to get credit for the MicroMasters certificate.)"

**Comment by annagav** [comment]
This is text for when the user hasn't applied: 'You need to get a Personalized Course Price before
        you can pay for this course. Or you can audit the course for FREE
        and upgrade later. (Payment is required to get credit for the
        MicroMasters certificate.)'

**Comment by roberthouse54** [comment]
Let's use this:
"Your Personalized Course Price is still pending approval, but you can sign up now to audit the course for FREE, and then pay later. (Payment is required to get credit for the MicroMasters certificate.)"
