### ISSUE TITLE
Add a status for "Failed Proctored Exam"

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#3441]
We need to show a status for when a user has failed the proctored exam. There are several variations on this. a) if the user is authorized to retake the exam. b) Whether we have any data on upcoming exams c) Whether the exam scheduling window is open.

Currently, users who have paid for DEDP courses can take the exams up to two times.

**1. If the user has failed the exam, but is authorized to retake the exam:** 

- Exam scheduling is open: "You did not pass the exam, but you can try again. Click above to reschedule an exam with Pearson."
- No info on upcoming exams: "You did not pass the exam, but you can try again. There are currently no exams available for scheduling. Please check back later."
- Data on future exams, but scheduling isn't open yet: "You did not pass the exam, but you can try again. You can sign up to re-take the exam starting on [date]."

**2. If the user has failed the exam twice, they have to pay again in order to re-take the exam. So in this state we should display:**

- Exam scheduling is open: "You did not pass the exam. If you want to re-take the exam, you need to pay again." In this status we should show the Pay Now button.
- No info on upcoming exams: "You did not pass the exam. There are currently no exams available for scheduling. Please check back later." In this status we should show a disabled Pay Now button.
- Data on future exams, but scheduling isn't open yet: "You did not pass the exam. If you want to re-take the exam, you need to pay again. You can sign up to re-take the exam starting on [date]." In this status we should show the Pay Now button.

**Comment by rhysyngsun** [comment]
@roberthouse54 how should this language differ when there aren't exams available for scheduling?

**Comment by roberthouse54** [comment]
What do you suggest? What can we say and do here? Something like "You did not pass the exam. You are authorized to re-take the exam, but there are currently no exams available for scheduling. Please check back later."

I don't really know what to tell the user to do in that state.

**Comment by roberthouse54** [comment]
If users cannot currently schedule exams, but we do know the date the user can start scheduling exams, then we will display:

"You did not pass the exam, but you can try again. You can sign up to re-take the exam starting on [date]."

**Comment by rhysyngsun** [comment]
To summarize our discussion, there are basically 3 states of future exam availability:

- No data on future exams
- Data on future exams, but scheduling isn't open yet
- Scheduling is open

So we'd need language for those each 3 states for each of the two variations (payment required and 2nd sitting available)

**Comment by roberthouse54** [comment]
I will update the description with all these variations.

**Comment by rhysyngsun** [comment]
@roberthouse54 those all look good to me
