### ISSUE TITLE
Enable MicroMasters certificate generation

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#3460]
_Part of #2552_

Dynamic HTML certificates were implemented in #3459. We need some method for generating certificates for users that have passed a course run in an FA program (preferably automatic). We have a few options here:

1. Signals - Any time a `FinalGrade` is created, and the course run is in an FA program, create a `MicromastersCourseCertificate` as well
1. Task - Create an async task that checks for `FinalGrade` records with an FA program course run and no associated `MicromastersCourseCertificate`

If it matters to us, we can also create a management command to generate these certificates on demand.

In order to receive a certificate, the learner must:
1. Pass the online course
2. Pass the proctored exam
3. Getting a passing (greater than 50%) final grade, which is a weighted average of 40% of the course grade and 60% of the proctored exam grade.

**Comment by pdpinch** [comment]
Calculating the final course grade is currently only implemented in the front-end. See https://github.com/mitodl/micromasters/blob/49904c54acd415043ed2cf498fa83d22f7250309/static/js/lib/grades.js#L41-L53

**Comment by gsidebo** [comment]
@pdpinch If a user can pass a course with a 50% or higher weighted grade, then a user can receive 50% for the course final grade and 50% for the exam grade, which are both respectively failing grades, but the overall grade would register as passed. Is that right?
