### ISSUE TITLE
Create Channel react component

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3473]
_part of #3467_

As a staff member of a program, I want to create a channel based off a profile search query. When the staff person clicks the "create channel" button on the search results page, they should get the following modal:

![3b 2x](https://user-images.githubusercontent.com/20047260/30397547-43172b76-989b-11e7-999b-33be62b75cad.png)
(from https://invis.io/NB7VM1GSG#/242271568_Create_Channel_-_Filters_Selected)

The currently selected filters are displayed in the modal, similar to the e-mail modal on the search page. They are not interactive. 

When the submit the form, they should get this toast as a confirmation:

![](https://user-images.githubusercontent.com/20047260/30397946-86bfccba-989c-11e7-88f4-95239e5a61f8.png)

Implementation details:
- [ ] Endpoint integration and tests
- [ ] `ChannelCreateDialog` implementation and tests
- [ ] Confirmation toast notification

**Comment by pdpinch** [comment]
Blocked by #3475, at least until a PR is opened that includes the API signature.

**Comment by noisecapella** [comment]
For the API signature:

    POST /api/v0/channels/

    {
        "query": {"elasticsearch query": ["goes", "here"]},
        "title": "title",
        "name": "name",
        "public_description": "public_description",
        "channel_type": "private"
    }

All parameters are required. It returns JSON for the channel similar to the input but the `query` will also include the program enrollment query

**Comment by roberthouse54** [comment]
Here is an updated and simpler UI for this:
![create_channel_ui](https://user-images.githubusercontent.com/20047260/30344939-3e7cba10-97d1-11e7-9a11-db318f67bb03.png)

**Comment by rhysyngsun** [comment]
@roberthouse54 @pdpinch I'm a tad confused, is this supposed to be a modal or not? Descriptions say modal, but mockups aren't.

**Comment by roberthouse54** [comment]
no, it is not a modal.

**Comment by rhysyngsun** [comment]
Follow-up question then, where should the user end up after they complete the form?

**Comment by pdpinch** [comment]
I think we want to direct them to their new channel.

**Comment by rhysyngsun** [comment]
So, same tab then? Only asking because we usually open external links in a new window.

**Comment by roberthouse54** [comment]
OK, sorry for my previous comment. The design will be a modal to be consistent with the Create New Email form. I will follow up with a design showing a link to the new channel.

![image](https://user-images.githubusercontent.com/20047260/30397165-efb0157a-9899-11e7-9df3-98029273f6d0.png)

**Comment by roberthouse54** [comment]
After the modal is submitted we will show what is called a "Snackbar" in Material design (see: https://material.io/guidelines/components/snackbars-toasts.html#). This is a transient message which will contain a link to the channel page.

It will be good if we can control the amount of time the message is displayed before it goes away.

![image](https://user-images.githubusercontent.com/20047260/30397946-86bfccba-989c-11e7-88f4-95239e5a61f8.png)
