### ISSUE TITLE
"Recent Posts" react component 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3476]
See https://invis.io/NB7VM1GSG#/242718039_Dashboard_with_Discussions_card

In the interests of MVP, we can omit some fields/content that appear in the mock-up.

**Comment by pdpinch** [comment]
@aliceriot please let me know if this issue will depend on #3477 and #3478

**Comment by aliceriot** [comment]
It depends how the authentication stuff is set-up so far. I think @rhysyngsun is probably in a better place to answer these questions - I'm not sure, for instance, that we are in a position to directly make an API call from the frontend to open-discussions, or whether it needs to go through MM first, to add profile information and so on.

**Comment by rhysyngsun** [comment]
@pdpinch @aliceriot I'm not sure what #3477 is supposed to be. I thought we had discussed that we didn't need #3478 and would instead go directory to `open-discussions` API from the browser, right?

**Comment by aliceriot** [comment]
Yeah that was my recollection as well

**Comment by pdpinch** [comment]
I updated the description of this with a link to the invision mock-up. 

If you find that any part of the design is slowing you down, let's talk. We don't necessarily need all the elements.
