### ISSUE TITLE
Remove Mail token buttons from "Send a Message" form

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3489]
Although the "Send a Message" interface has the same mail token buttons as "Email These Learners" they don't work. Tokens are inserted into the mail, but they aren't replaced when sending, 

Although there's not much utility in using tokens in a one-off message, at least one user (ZenDesk [#10133](https://odl.zendesk.com/agent/tickets/10133)) was using "Send A Message" to test the Mail token function without sending a mass e-mail, and he was expecting them to behave the same way.

**Comment by pdpinch** [comment]
@roberthouse54 what are your thoughts on this?

Should we make "Email These learners" and "Send a Message" both support Mail Tokens, or should we remove the Mail Token buttons from the "Send a Message" UI?

**Comment by roberthouse54** [comment]
I think we should remove the mail token buttons from the Send Message UI.

**Comment by pdpinch** [comment]
Somehow this is already done.
