### ISSUE TITLE
Add overall final grade data to the dashboard API

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#3492]
The concept of an 'overall' final grade (a grade that combines a user's course final grade [`FinalGrade`] and exam grade [`ProctoredExamGrade`] with appropriate weight) is only represented in front end code right now. This was done to speed up implementation. All of our other grading logic is in the back end, and all other grading data can be retrieved via the dashboard API. This split of front end/back end logic is inconvenient, difficult to reason about and potentially dangerous. The logic for calculating overall final grades should be moved to the back end, and overall final grade data should be returned in the dashboard API response.

**Comment by pdpinch** [comment]
Should this issue include creating a model for overall final grade?

**Comment by gsidebo** [comment]
If we wanted to add another model, we would need to freeze the overall final grade in addition to the course final grade. That might entail some tricky logic. Very much worth considering, though. My initial instinct was to calculate overall final grade info on the fly, but I don't think I would rule out the additional model + 'freezing' task

**Comment by gsidebo** [comment]
Here's some preliminary work I did a few weeks ago in an effort to get the overall final grade data into the dashboard API: https://gist.github.com/gsidebo/1b772d2cfe786b5c5601d7ac283d83a8. This doesn't need to be followed exactly, but could be helpful. The basic idea was to create a class that could consistently represent a user's overall final grade in a course run whether that course had an exam or not

**Comment by gsidebo** [comment]
@pdpinch We might want to think about a separate issue for cleaning up the front-end logic for calculating overall final grade. That could be a pretty hefty change
