### ISSUE TITLE
Add template for program certificates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3519]
As a learner, I'd like to be able to view an HTML certificate when I complete a FA program (non-FA program certificates will be available from edx.org). I'd like also to be able to print the certificate from my browser. 

screen mock-up at https://invis.io/NB7VM1GSG#/239889459_Program_Complete2

### questions
- [ ]  Same URL as course certificates?

**Comment by gsidebo** [comment]
> Same URL as course certificates?

Probably not. If we used the same url, we would need the hashes to all be unique between course and program certificates, and if all the hashes were required to be unique, we would need to combine both certificate types into a single table (which would introduce some complication that I don't think is worth it) or have some kind of pre-insertion check between tables (which would be even uglier). Different URLs is definitely the most straightforward way to go about this

**Comment by pdpinch** [comment]
Can you make a suggestion? Maybe something like `/certificates/program/` ? or `/certificates/dedp` ?

**Comment by gsidebo** [comment]
`/certificates/<program_stub>/<hash>` would be ideal. I'm trying to see if each program has a stub automatically generated (probably by wagtail) but I can't run the app locally right now. I'll comment again when I figure that out. If that doesn't work, `/certificates/program/<hash>` would be OK I think

**Comment by gsidebo** [comment]
NOTE: We could probably reuse the course certificate template to render these program certificates. There is some text and a few class names et. al. that refer specifically to courses, but it might be pretty simple to generalize them

**Comment by pdpinch** [comment]
I don't recall how they are created, but every program will have a stub/slug, I.e, DEDP, SCM. New one is POM I think. 

----------------
I am mobile.
