### ISSUE TITLE
Create program certificate when learner passes all courses in program

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3520]
When a learner passes all courses in a FA program, we should generate a program certificate for them. 

This is similar to the task in #3460, but should only be run when the leaner has passed each and every one of the courses in the program. 

Acceptance criteria:
- Model created to store program certificates (like `MicromastersCourseCertificate`)
- CMS contains a section where admins can edit relevant information for program certificates (signatories, etc.)
- Task created to create program certificates for any users that don't have one and should receive one

**Comment by gsidebo** [comment]
Celery task to generate course certificates: `grades.tasks.generate_course_certificates_for_fa_students`. The idea for generating the program certificates will be roughly the same: check for students that don't have a program certificate but should, then generate the record. My initial thought was to query for all `MicromastersCourseCertificate`s, join them to the related `Course`, and check whether the set of `Course`s for which a user has a certificate is equal to the set of courses in the program

**Comment by annagav** [comment]
@pdpinch @gsidebo Would the program certificate be related to an 'overall final grade' (that I think right now is only calculated in the front end). Or is the program certificate independent of overall grade and awarded only once for that program?

**Comment by gsidebo** [comment]
I think we can just associate it with a user and program. If we make sure that the user and program are unique together, we can be sure that a user only gets 1 per program.

**Comment by annagav** [comment]
@pdpinch @gsidebo, If user's ProgramEnrollment gets deleted, do we want to delete the certificate?

**Comment by pdpinch** [comment]
No. Not necessary

**Comment by pdpinch** [comment]
Let me be more clear. 

The program certificate is generated when the user has passed all courses in the program. "Passing" a course is defined in the front-end currently and relies on a weighted average of the best online course grade and the best exam grade. 

It is true that you can only get one program certificate per program. 

I don't think we want to bother deleting the certificate if the ProgramEnrollment is deleted. If you earned, you get it.

**Comment by annagav** [comment]
@pdpinch, Is this issue addressing certificates only for FA programs?

**Comment by pdpinch** [comment]
Yes, FA only.  (I actually remembered to put it in the description this time!)

**Comment by gsidebo** [comment]
@pdpinch Do non-FA students get some form of 'program certificate' from edX directly, or is it just coincidental that it's only FA courses that are asking for program certificates?

**Comment by pdpinch** [comment]
Yes. Non-FA students get a program certificate from edX. However, I don't know if there is an API that exposes the URL for downloading it. 

I guess we should open an issue for the future about addressing non-FA students linking to their certificate.

**Comment by pdpinch** [comment]
@annagav was this closed by PR #3524 ?

**Comment by annagav** [comment]
That's right
