### ISSUE TITLE
Recent posts page doesn't work if user is not currently logged in on open-discussions

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#3583]
I think we can fix this by having the fetch contact `/discussions/` first and then the open-discussions API

**Comment by noisecapella** [comment]
I tried this and it looks implemented already. @roberthouse54 can you try it again with the latest master?

**Comment by aliceriot** [comment]
yeah it should try to hit open-discussions, and if it gets a 401 back it should hit the `discussions_token` endpoint on MM to get a new token and then retry the request to open-discussions

**Comment by roberthouse54** [comment]
Not working for me. George is investigating

**Comment by noisecapella** [comment]
@roberthouse54 had a stale browser cache which was causing his problem. I've confirmed that the user can view the recent posts link even if they have never visited open-discussions before
