### ISSUE TITLE
Add a "Learner Stories" tab in DEDP Micromasters program page

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#3587]
This will be basically the same at the SCM "Learner Stories" tab. See: https://micromasters.mit.edu/scm/learner-stories/

This will consist of a tab called Learner Stories, with several images, and full testimonials beneath the images. 

NOTE: If DEDP wants to have these testimonials appear on the edx blog (like SCM does) then DEDP will have to coordinate this with edx.

**Comment by pdpinch** [comment]
This is done: https://micromasters.mit.edu/dedp/learner-stories/
