### ISSUE TITLE
ZenDesk Widget throwing 1000s of TypeErrors: Failed to execute 'getComputedStyle' on 'Window'

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3602]
I'm not sure if this is a bug in ZenDesk's JavaScript widget, or if it's an issue in how we're trying to use it. 

TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/361180415/

```
TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
  at callback (./static/js/entry/zendesk_widget.js:105:41)
  at apply (./static/js/entry/zendesk_widget.js:243:9)
```

**Comment by pdpinch** [comment]
If this is a ZenDesk error, then we should find a way to suppress the error so it doesn't go to Sentry. We're severely clogging the sentry logs with this error.

**Comment by noisecapella** [comment]
The stack trace is from our code. I think a CSS selector no longer matches because they adjusted something on their end, and this is causing a null error

**Comment by pdpinch** [comment]
@amir-qayyum-khan this is happening again. I'm hoping maybe it's just some cached javascript code, but I don't know. 

See, for example, https://sentry.io/mit-office-of-digital-learning/micromasters/issues/361180415/events/8370678176/
