### ISSUE TITLE
Dashboard request to open discussions frontpage API needs a trailing slash

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#3603]
https://github.com/mitodl/micromasters/blob/master/static/js/lib/discussions.js#L19 needs a trailing slash so a redirect doesn't occur and fail due to a CORS issue

**Comment by pdpinch** [comment]
Is there  a reason why this would affect one user and not others?

**Comment by rhysyngsun** [comment]
Is the request not happening for your other user?

**Comment by pdpinch** [comment]
Yeah. I'm running three different "people"  in chrome. This only happens to one. I think the CORS error is masking another error.
