### ISSUE TITLE
IntegrityError: null value in column "country_of_residence" violates not-null constraint

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3607]
I don't understand how this happens. I thought that if the user is missing required profile data, they are bounced to the profile form before they would load their dashboard. 

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/312366357/

```
IntegrityError: null value in column "country_of_residence" violates not-null constraint
DETAIL:  Failing row contains (9814, created, 0, 0, INR, null, 2017-10-05 10:17:36.695033+00, 24091, 1, 2017-10-05 10:17:36.706705+00, 2017-10-05 10:17:36.706774+00, null, null, null).

  File "django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "newrelic/hooks/database_dbapi2.py", line 25, in execute
    *args, **kwargs)

IntegrityError: null value in column "country_of_residence" violates not-null constraint
DETAIL:  Failing row contains (9814, created, 0, 0, INR, null, 2017-10-05 10:17:36.695033+00, 24091, 1, 2017-10-05 10:17:36.706705+00, 2017-10-05 10:17:36.706774+00, null, null, null).

(25 additional frame(s) were not displayed)
...
  File "rest_framework/generics.py", line 191, in post
    return self.create(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "rest_framework/mixins.py", line 26, in perform_create
    serializer.save()
  File "financialaid/serializers.py", line 86, in save
    country_of_residence=user.profile.country,
  File "financialaid/models.py", line 94, in save
    super().save(*args, **kwargs)

IntegrityError: null value in column "country_of_residence" violates not-null constraint
DETAIL:  Failing row contains (9814, created, 0, 0, INR, null, 2017-10-05 10:17:36.695033+00, 24091, 1, 2017-10-05 10:17:36.706705+00, 2017-10-05 10:17:36.706774+00, null, null, null).

```

**Comment by pdpinch** [comment]
This also caused issues when we tried to reindex after the elasticsearch 5 upgrade

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/460624900/

**Comment by pdpinch** [comment]
One way to address this might be to fix #2297

**Comment by amir-qayyum-khan** [comment]
- open admin pages, open profiles
- open dashboard in different browser
- if you remove country from profile
- do not refresh dashboard
- skip or apply for FA
- open http://192.168.99.100:8079/admin/financialaid/financialaid/ and you will see financialaid object with country. 

I am not able to produce IntegrityError it is allowing me financialaid object without country

**Comment by pdpinch** [comment]
Have you tried to make a change to the financial model and save it without the country? I think that's where the integrity error crops up.

**Comment by amir-qayyum-khan** [comment]
it wont allow me to save object, it will throw error before calling model, because of validation. Thats why no exception.

**Comment by pdpinch** [comment]
What kind of error is being thrown? Is it something the user can act on to correct?

**Comment by amir-qayyum-khan** [comment]
@pdpinch A validation error:
There is no exception because it is a validation error because it is not null field.

<img width="556" alt="screen shot 2018-03-14 at 5 54 42 pm" src="https://user-images.githubusercontent.com/10431250/37403492-d2e57ff6-27b0-11e8-9d0d-7844da16bde8.png">

**Comment by amir-qayyum-khan** [comment]
@pdpinch not able to produce it, and https://sentry.io/mit-office-of-digital-learning/micromasters/issues/312366357/ say `issue  you are looking for is not found`

**Comment by pdpinch** [comment]
Did you read all the comments on this issue? There's another link: https://sentry.io/mit-office-of-digital-learning/micromasters/issues/460624900/

**Comment by amir-qayyum-khan** [comment]
### To produce the issue
- docker-compose run web ./manage.py shell
```python
from django.contrib.auth.models import User
u = User.objects.get(id=122)
u.profile.country = None
u.profile.save()
u.profile.country == None
```

On dashboard do not refresh page, just skip FA. you will see exception on console.

```exception
|   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
web_1      |     return executor(sql, params, many, context)
web_1      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
web_1      |     return self.cursor.execute(sql, params)
web_1      |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
web_1      |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
web_1      |     return self.cursor.execute(sql, params)
web_1      | django.db.utils.IntegrityError: null value in column "country_of_residence" violates not-null constraint
web_1      | DETAIL:  Failing row contains (3, skipped, null, null, null, null, 2018-03-15 13:17:24.549258+00, 122, 4, 2018-03-15 13:17:24.696223+00, 2018-03-15 13:17:24.69629+00, null, null, null).
```

### To fix it:
- To fix issue i am going to check if profile is filled before api call

**Comment by aliceriot** [comment]
I think we'll need to find a way to address why the user is able to get a profile without a country in the first place at the same time. As Peter said above, they shouldn't be able to do that, so we must have a bug in some of our code to check whether the profile is complete. I think what you suggested generally makes sense though, we'll want to make sure that we provide the user with a way to fix the issue though (i.e. be redirecting them to the profile page so that they can fill out the required field).

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/495034986/
