### ISSUE TITLE
After initial channel creation, staff added to a program should be added as moderators

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#3613]
Not sure what kind of priority this is. We should also remove staff as moderators if they are removed from their staff role

**Comment by amir-qayyum-khan** [comment]
Should we create signal on role added or remove and add user to channel accordingly?

**Comment by pdpinch** [comment]
That's what I had in mind, but you should check with @noisecapella  -- he's actually thinking about a related issue right now.

**Comment by amir-qayyum-khan** [comment]
@rhysyngsun @noisecapella what are your thoughts on this?
