### ISSUE TITLE
DoesNotExist: UserSocialAuth matching query does not exist.

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3630]
We get multiple `DoesNotExist: UserSocialAuth matching query does not exist.` errors every six hours. Most of these errors are related to superusers on the CI and RC servers, but there is also at least one user in production. 

Since these users don't have an edX SocialAuth, we shouldn't even attempt to update their edX cache. Although I am curious about that one user in production, I don't see a lot of value is raising an exception every six hours for that user. Presumably, if they have a successful log in to micromasters.mit.edu the issue should clear. 

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/193071074/

```
DoesNotExist: UserSocialAuth matching query does not exist.
  File "dashboard/tasks.py", line 101, in batch_update_user_data_subtasks
    UserSocialAuth.objects.get(user=user)
  File "django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 385, in get
    self.model._meta.object_name

user "nawalyathccdd90e46a0f459a" does not have python social auth object
```

**Comment by pdpinch** [comment]
@noisecapella which PR addresses this?

**Comment by amir-qayyum-khan** [comment]
@pdpinch #3670

**Comment by amir-qayyum-khan** [comment]
https://github.com/mitodl/micromasters/pull/3670 merged
