### ISSUE TITLE
Remove HTTP basic auth from /_o/ endpoint on courses.stage.edx.org

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#366]
For a variety of reasons, we need to be able to test our releases with edX's staging environment. Unfortunately, stage.edx.org uses HTTP basic auth, which trips up the OAuth authentication flow. 

EdX devops says they will remove the basic auth from the `/_o` endpoint, which should make this a no-op for us. But I'm opening this issue to remind me to bug them about it. 

@bdero

**Comment by bdero** [comment]
Thanks for making an explicit issue for this, it's been our biggest blocker for #59 .

**Comment by pdpinch** [comment]
@bdero I open a ticket for this at https://openedx.atlassian.net/servicedesk/customer/portal/3/DEVOPS-4271 -- can you check to see if you can access it?

**Comment by bdero** [comment]
I don't have access to it. :o
