### ISSUE TITLE
Radio buttons on new user profile pages are misaligned

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#3665]
![selection_093](https://user-images.githubusercontent.com/28598/32008758-0a581c90-b97b-11e7-997e-c15d74ed7905.png)

**Comment by noisecapella** [comment]
I tried to find the commit introducing this via git bisect. It's at least a few months old and before that I run into migration issues I didn't want to deal with locally. I feel like it might be caused by the Chrome update rather than a library change, but I don't know for sure
