### ISSUE TITLE
Add course number to course model 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3667]
As a data consumer, I'd like to be able to see data correlated to course number which is easier to recognize in graphs and charts. 

As an admin doing customer support, I would be able to identify course enrollments and registrations more quickly if I could see the course number instead of reading the course name. 

Note that for SCM we added the course number to the course title, so that it displays on the dashboard. This could be refactored also to avoid putting course numbers into the titles.

**Comment by amir-qayyum-khan** [comment]
@pdpinch what will be format of course number, should it be auto generated?

**Comment by pdpinch** [comment]
Just a string — the course number is similar to the 2nd segment of the course key, e.g. 14.73x or SC0x.

I’ll be setting the values for these manually, at least for the foreseeable future.

**Comment by pdpinch** [comment]
@maxliu I just wanted to let you know that I've updated the course number data in production, so it should now be available to you in BI. Let me know if you have any questions.
