### ISSUE TITLE
Add header to profile pages 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#367]
I.e., make them look like this, including the user's avatar and the welcome message, on all profile forms, including the terms of service:

![step four - profile privacy](https://cloud.githubusercontent.com/assets/430126/15433249/874d39a8-1e7f-11e6-9b18-f5935fb5922a.png)

**Comment by aliceriot** [comment]
@pdpinch I'm wondering how this story relates to #346, it looks like Amir has the banner added to the ToS page there. Should I add it to the ToS page in the PR for this issue anyway, or just let Amir take care of that?

**Comment by pdpinch** [comment]
I'd like to be standardized on one approach. It seems like one of you will have a merge conflict though I suppose.

**Comment by aliceriot** [comment]
I think we're going to wait to merge #346 until after I've merged #398
