### ISSUE TITLE
Dashboard: Better UX when user has not calculated their price yet and wants to pay for a course

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3679]
Some learners don't notice the Personal Price card on their dashboard and become confused when they can't pay for a course (pay button is disabled).

For users who don't have a personal price, display the personal price modal when they click "Pay Now" instead of disabling the button.

**Comment by roberthouse54** [comment]
I think for this one, we can just open the price calculator modal if a user clicks the pay now button.

**Comment by pdpinch** [comment]
What if the learner has already submitted their income & are waiting to be approved?

**Comment by roberthouse54** [comment]
OK, so this design will address the following UX cases:
1. For users who are currently auditing a course and want to pay, but have not yet calculated their course price.
2. For users who are currently auditing a course and have submitted a financial aid application that is still pending approval.

A separate issue will make some small changes to the copy to clarify that users need to have calculated their course price before they can pay, and also add additional "Calculate your course price" links which will open the calculate course price modal.

**Comment by roberthouse54** [comment]
Here is the design for the following four statuses:

1. User is not enrolled (or auditing) and they have not calculated their price yet:
![image_1024](https://user-images.githubusercontent.com/20047260/33036327-08388d74-cdfc-11e7-8804-a898edceb3f0.png)

2. User is auditing a course but they have not calculated their price yet:
![image](https://user-images.githubusercontent.com/20047260/33036367-23f8954a-cdfc-11e7-815a-9b433a2fb5a9.png)
![image-1](https://user-images.githubusercontent.com/20047260/33036375-2856028a-cdfc-11e7-85f7-260ba2e92f3c.png)

3. User is not enrolled or auditing, and FA application is pending approval:
![image_1024-1](https://user-images.githubusercontent.com/20047260/33036388-32300a26-cdfc-11e7-976e-1f2fea4a7ff5.png)

4.  User is auditing a course, and their FA application is pending approval:
![image-2](https://user-images.githubusercontent.com/20047260/33036401-404b82b6-cdfc-11e7-8c54-e62cc6178571.png)
