### ISSUE TITLE
add footer to enrollment/profile pages

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#368]
- [x] use same footer as home page 
- [x] omit About page until we have one. 
- [x] Give button uses links to https://giving.mit.edu/explore/campus-student-life/digital-learning

![step four - profile privacy](https://cloud.githubusercontent.com/assets/430126/15433285/bbc9b6ca-1e7f-11e6-9a70-060f53c4f166.png)

**Comment by pdpinch** [comment]
According to the [MIT graphic identify site](http://web.mit.edu/graphicidentity/download-logos.html), it looks like this is the preferred logo for black backgrounds:

https://github.com/mitodl/micromasters/blob/fixup/pdpinch/add_footer/static/images/MIT-logo-ltgray-white-72x38.svg

**Comment by pdpinch** [comment]
@amir-qayyum-khan I should have mentioned this, but I thought you already knew. We have HTML templates from the designer at http://mitodl.github.io/micromasters-templates/ (repo at https://github.com/mitodl/micromasters-templates)

The footer should have been based on that template, except for the changes mentioned in the issue.

**Comment by amir-qayyum-khan** [comment]
resolved by #421
