### ISSUE TITLE
Dashboard: When learner misses payment deadline, tell them when they can pay next

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3680]
A learner who has passed an FA course, but missed the payment deadline, can pay for the course the next time an exam is offered. Instead of telling them to enroll again, we should let them know when they can next pay. 

This may require adding another field to the course or exam model to indicate when we will start taking payments again. 

See https://odl.zendesk.com/agent/tickets/10417 for an example.

**Comment by roberthouse54** [comment]
![image](https://user-images.githubusercontent.com/20047260/44116860-a8b31336-9fdf-11e8-9f8f-6ea8124ef5d4.png)

**Comment by annagav** [comment]
@roberthouse54 What should this say:
1. if there is no past exam run
2. if there is no future. 
Are these dates when an exam could be scheduled or taken?

**Comment by roberthouse54** [comment]
I think for #2 we can show this: "You passed the edX course but missed the payment deadline to take the proctored scheduled for Sep 27-30, 2018. There are no future exams scheduled at this time. Please check back later."

For question 1, I am a bit confused. Will this ever happen @pdpinch ?
