### ISSUE TITLE
Dashboard: don't show re-enroll button when course isn't open for enrollment

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3688]
For a learner who has failed a course, we show a "Re-Enroll" button. That button should be disabled (or hidden) if the course isn't open for enrollment, i.e. if `start_enrollment` is in the future or is null; or if the `edx_course_key` is null. 

<img width="1392" alt="screenshot 2017-11-01 08 26 48" src="https://user-images.githubusercontent.com/430126/32274788-ee930d94-bede-11e7-962c-417eb6204be4.png">

**Comment by roberthouse54** [comment]
![image](https://user-images.githubusercontent.com/20047260/32284397-7f0bcbf4-befd-11e7-91aa-7698b4b313f3.png)

OK, so we will show the disabled button, and also the copy "Enrollment starts [date]."
