### ISSUE TITLE
Mailing learners fails with 'Result window is too large'

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#3694]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/396645234/

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/396645234/

**Comment by amir-qayyum-khan** [comment]
there is a variable `max_result_window` which is set to 10000, we need to increase this limit.

- https://stackoverflow.com/questions/44050298/django-haystack-elasticsearch-result-window-too-large
- https://stackoverflow.com/questions/39888433/can-i-fix-large-window-error-without-index-max-result-window-in-es
- https://stackoverflow.com/questions/35206409/elasticsearch-2-1-result-window-is-too-large-index-max-result-window

**Comment by pdpinch** [comment]
@noisecapella what do you think?

**Comment by noisecapella** [comment]
I think we should switch to the scroll api and fetch results until completion. Ideally we would connect the scrolling generator to the bulk mail function so that we don't store all emails in memory at the same time, and do the emails asynchronously in a task so it doesn't depend on the HTTP connection being open

**Comment by amir-qayyum-khan** [comment]
@noisecapella i need to walk through code, can you help me?

**Comment by noisecapella** [comment]
This is the [scan](http://elasticsearch-py.readthedocs.io/en/master/helpers.html#elasticsearch.helpers.scan) function which uses the scroll API to fetch results. You will need to integrate it with the `search_for_field` function in `search/api.py`

**Comment by noisecapella** [comment]
@amir-qayyum-khan Any progress on this issue?

**Comment by amir-qayyum-khan** [comment]
I have a PR @noisecapella but do not know how to test it manually https://github.com/mitodl/micromasters/pull/3846
