### ISSUE TITLE
Exams: Display learner's exam eligibility for staff on profile page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3722]
As an course staff, I would like an easy way to view a learner's exam eligibility when I look at their learner profile. 

### acceptance critera

- [x] visible to staff only
- [x] uses same criteria for exam eligibility that is used on the learner dashboard, i.e. dashboard API returns `"can_schedule_exam" : true`

**Comment by pdpinch** [comment]
@roberthouse54 we'll need a simple design for this before Amir starts working on it (he's out until 1/15)

**Comment by roberthouse54** [comment]
![authorized_for_exam](https://user-images.githubusercontent.com/20047260/34791005-a42797c4-f611-11e7-89de-481328305ac8.png)
