### ISSUE TITLE
On Dashboard, gray-out "Apply for Masters" button

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#373]
The button isn't clickable, but it's still too subtle. We need to actually change the color of the button and the text. 

See, for example, https://getmdl.io/components/index.html#buttons-section

**Comment by amir-qayyum-khan** [comment]
@pdpinch what should be change in text?

**Comment by pdpinch** [comment]
The text should be:

```
Apply for Supply Chain Management Master’s Degree
```

I forgot that it was already white, so the color is fine. 

The button should be greyed out, as it is in the design. I.e. `#B2C9D2`
