### ISSUE TITLE
bug in uploading profile images: TypeError: Unable to get property 'contains' of undefined or null reference

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3730]
Based on timing and web browser, this issue appears to be related to https://odl.zendesk.com/agent/tickets/13261 and it's preventing the user from completing their profile. 

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/289053927/

```
TypeError: Unable to get property 'contains' of undefined or null reference
  at value (~/react-dropzone/dist/index.js:173:1)
  at wrapped (~/raven-js/src/raven.js:314:1)
```

**Comment by aliceriot** [comment]
It looks like this bug has been fixed in the react-dropzone package here: https://github.com/react-dropzone/react-dropzone/pull/517

So I think we should be good to just upgrade it, and hopefully we'll stop seeing it.
