### ISSUE TITLE
When freezing grades, we get AttributeError: 'NoneType' object has no attribute 'percent'

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3735]
This error appeared to be related to a few (one?) particular user. Because it raised an error during the freezing of grades, it prevented the task from being completed. 

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/416616973/

```
AttributeError: 'NoneType' object has no attribute 'percent'
  File "grades/api.py", line 177, in freeze_user_final_grade
    final_grade = get_final_grade(user, course_run)
  File "grades/api.py", line 116, in get_final_grade
    return final_grade_func(run_data)
  File "grades/api.py", line 76, in _compute_grade_for_non_fa
    grade = float(user_edx_run_data.current_grade.percent)

Impossible to get final grade for user "mitul4patel" in course course-v1:MITx+CTL.SC4x+3T2017
```

**Comment by annagav** [comment]
@pdpinch, The CourseRunGradingStatus for `course-v1:MITx+2.830.1x+1T2018` seems to be complete. Given that the task ran not at scheduled time, does that mean you ran it manually? If so, did it take you 3 runs of `freeze_final_grades` to complete it?

**Comment by pdpinch** [comment]
I don't think we've seen this issue in a while. I'm going to close it.
