### ISSUE TITLE
Dashboard: remind learners that they must pay for a course before they can schedule exam

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3738]
We had a user who was surprised to see the exam card when he had not yet paid for a course. 

We should modify the message "We will notify you when you become eligible" to something that mentions that the learner won't be eligible until they pay for a course. 

See https://odl.zendesk.com/agent/tickets/13407

![screenshot-p4 zdusercontent com-2018-01-04-09-24-05](https://user-images.githubusercontent.com/430126/34567785-a63267c2-f131-11e7-8eaa-52b74c6d3384.png)

**Comment by roberthouse54** [comment]
So just a clarifying question. Just above the gray box it says "Before you can take an exam, you have to pay for the course..." Is that not sufficient?

**Comment by pdpinch** [comment]
Yeah. I just read through the ticket again, and what I've described is not the issue.
