### ISSUE TITLE
add footer to home page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#376]
- [x] use same footer as profile / enrollment page (#368)
- [x] omit About page until we have one. 
- [x] Give button links to https://giving.mit.edu/explore/campus-student-life/digital-learning

![public home sign up](https://cloud.githubusercontent.com/assets/430126/15455820/7a20792a-202d-11e6-9716-28532c1e28ed.png)

**Comment by pdpinch** [comment]
@amir-qayyum-khan I should have mentioned this, but I thought you already knew. We have HTML templates from the designer at http://mitodl.github.io/micromasters-templates/ (repo at https://github.com/mitodl/micromasters-templates)

The footer should have been based on that template, except for the changes mentioned in the issue.

**Comment by amir-qayyum-khan** [comment]
sorry i was not aware, let me use this one.

**Comment by pdpinch** [comment]
@amir-qayyum-khan wasn't this closed by #421 ?

**Comment by amir-qayyum-khan** [comment]
yes it is closed.

On Fri, Jun 3, 2016 at 1:00 AM, Peter Pinch <notifications@github.com>
wrote:

> @amir-qayyum-khan <https://github.com/amir-qayyum-khan> wasn't this
> closed by #421 <https://github.com/mitodl/micromasters/pull/421> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mitodl/micromasters/issues/376#issuecomment-223404697>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJ8rEsLN9OCyaWXlfBJZ35wrWdqFAv0Lks5qHzZngaJpZM4IkCrx>
> .
>



-- 
Amir Qayyum Khan
*Skype:* l070020
*Ph:* (+92)3344200954
LinkedIn <http://pk.linkedin.com/pub/amir-qayyum-khan/17/102/207>, Facebook
<https://www.facebook.com/Amir.KingKhan.The.1>
