### ISSUE TITLE
edx.org rate limits on /oauth2/access_token/ end point

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3764]
Last week (1/11/18) edX added a 30 request per minute rate limit on the Oauth end point /oauth2/access_token/. When a client goes over the limit, it gets a 403 response. 

We blew through that limit dramatically on 1/12, getting tens of thousands of 403s. I'm not sure if this was due to grade freezing tests at that time, or our efforts to modify the membership of a channel. Maybe both?

On a regular basis, we're getting about 100 rate-limited 403 responses every six hours, when we try to do our bulk update. 

Sentry issue: HTTPError: 403 Client Error: FORBIDDEN for url: https://courses.edx.org/oauth2/access_token/

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/411527180/

```
HTTPError: 403 Client Error: FORBIDDEN for url: https://courses.edx.org/oauth2/access_token/
(3 additional frame(s) were not displayed)
...
  File "social_core/storage.py", line 55, in refresh_token
    response = backend.refresh_token(token, *args, **kwargs)
  File "backends/edxorg.py", line 106, in refresh_token
    response = super(EdxOrgOAuth2, self).refresh_token(token, *args, **kwargs)
  File "social_core/backends/oauth.py", line 431, in refresh_token
    request = self.request(url, **request_args)
  File "social_core/backends/base.py", line 229, in request
    response.raise_for_status()
  File "requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

Unable to refresh token for student PrSh
```

**Comment by pdpinch** [comment]
edX raised the rate limit. 

At some point they will add a bulk API so we don't need to make individually authenticated requests. Until that time, I am closing this issue.

**Comment by pdpinch** [comment]
I've been watching the 403 errors creep slowly up. Rather than asking edX's to increase the rate limit again, I wonder what would happen if we decreased our limit?

https://github.com/mitodl/micromasters/blob/1b83b5cb7e1c40f9e07b931536e732cec0bd3028/dashboard/tasks.py#L31

https://github.com/mitodl/micromasters/blob/1b83b5cb7e1c40f9e07b931536e732cec0bd3028/dashboard/tasks.py#L79-L92

If we just reduced that to just 4/m would we see fewer 403 errors with edX? I know it takes us some significant time to process all the dashboard updates. Can we afford to increase that time by roughly 20%?

@noisecapella I think you looked into this a bit already?

**Comment by pdpinch** [comment]
Maybe the rate limit should be an environment variable setting...

**Comment by noisecapella** [comment]
I think making it an environment variable makes sense. IIRC it takes about an hour to process them currently and there are 6 hours between batch updates, so there's a bit of room to spread this out

**Comment by pdpinch** [comment]
Ok. I opened a more specific issue for making the rate limit configurable.

**Comment by pdpinch** [comment]
We made the rate limit configurable, and tuned it down to `3/m` but we are still getting 403 errors. 

I'll try lowering it again, but I'm starting to wonder if I've been misinterpreting the 403 error (edX intended to change the quota error to a different error code, but as far as I know, they haven't done so yet)

**Comment by pdpinch** [comment]
After I lowered it to `2/m` the errors stopped.
