### ISSUE TITLE
Dashboard: 'Auditing' and 'Audited' are not the only options

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3767]
When a learner has paid for a course, but not yet passed or failed, we can't display `auditing` or `audited` in the grade pop-up 

Here's a case that shows the issue, from [ZenDesk #13770](https://odl.zendesk.com/agent/tickets/13770)

<img width="1363" alt="screenshot 2018-01-17 19 04 26" src="https://user-images.githubusercontent.com/430126/35074010-c8738af4-fbb9-11e7-81ce-ad67de88b09b.png">

Here's the code where the options are passed, failed, `auditing` or `audited` 
https://github.com/mitodl/micromasters/blob/aed8753e1dac52f9cd53d1186491bc73e6e5e000/static/js/components/dashboard/courses/GradeDetailPopup.js#L47-L58

If we can't think of a better option, I think `paid` would be acceptable.

**Comment by pdpinch** [comment]
@roberthouse54 can you comment on what should display in the grade pop-up in this case, instead of "audited" ?

**Comment by roberthouse54** [comment]
It seems that we should display either "In Progress" or "In Progress (paid)".

**Comment by pdpinch** [comment]
Perfect. I like "In Progress (paid)", to avoid ambiguity.

**Comment by roberthouse54** [comment]
OK, let's go with that.
