### ISSUE TITLE
Sorting posts/comments with an invalid sort method result in 500 error instead of 400

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#3769]
https://sentry.io/mit-office-of-digital-learning/discussions/issues/436529124/
https://sentry.io/mit-office-of-digital-learning/discussions/issues/436530265/

**Comment by pdpinch** [comment]
I'm going to move this to the open-discussions repo

**Comment by pdpinch** [comment]
Issue moved to [mitodl/open-discussions #438](https://github.com/mitodl/open-discussions/issues/438) via [**ZenHub**](https://www.zenhub.com/)
