### ISSUE TITLE
Dashboard: re-enroll button

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3780]
According to @annagav in https://github.com/mitodl/micromasters/issues/3233#issuecomment-342169648, we never implemented the re-enroll button in the dashboard redesign. I think it would still be useful. 

![paid](https://cloud.githubusercontent.com/assets/6207644/26414872/7d606eca-407e-11e7-80d2-a5cff9fea656.png)

**Comment by annagav** [comment]
@roberthouse54 Do you have a design for when we say "You passed this course." but the certificate has not been shown yet, and we want to show the 're-enroll' link?

**Comment by roberthouse54** [comment]
So, I think the question is whether we should add some copy here saying that the certificates will be issued soon. Something like "Certificates will be issued on Sep 10, 2018". We might also change this a bit so that the "Re-enroll" link is less prominent and looks more optional.

**Comment by roberthouse54** [comment]
OK, so let's just remove the View Certificate Link for now.

![image](https://user-images.githubusercontent.com/20047260/37537490-1f79ef72-2924-11e8-95b8-f0e8912dab6f.png)

**Comment by aliceriot** [comment]
So we don't want to show the 'view certificate' link at all?

**Comment by roberthouse54** [comment]
I was thinking no. What do you think? Show a disabled link?
