### ISSUE TITLE
When creating discussion user, pass email address to OD

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3783]
In order to allow the OD app to send via email, MicroMasters has to pass along the user's email address. 

- [x] Update `open-discussions-client` to the most recent version (note: there were function signature changes on `client.users.create()` and  `client.users.update()` required to support the new fields for this ticket. Need to adjust existing code in MM to account for that
- [x] Pass `email` on both `create` and `update`
- [x] Only pass `email_optin` on `create`

### questions
- [x] How should we handle users with `email_optin = false`? We could pass along that setting, or we could simply not pass an email address to the discussions app

### related issues
- Batch task to update existing user's email addresses
- Allow MicroMasters user to update email address

**Comment by pdpinch** [comment]
This is blocked by updates to Open Discussion API and the Open Discussions client.

**Comment by rhysyngsun** [comment]
I think it would be good to push the email plus an optin flag even if opting out of emails, it could help with reconciling multiple accounts down the road.
