### ISSUE TITLE
Synchronize email address with email address from edX 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3795]
As a learner, I would like my email address in MicroMasters to be in sync with my email address in edX.

**Comment by pdpinch** [comment]
I'm not sure when is the most convenient time to synchronized the email address. Perhaps on "login with edX." It's OK if there's some delay in updating the email address.

**Comment by amir-qayyum-khan** [comment]
@pdpinch i am changing `backends/pipeline_api.py` to update email even though user is not newly created

**Comment by pdpinch** [comment]
When does the pipeline get run? Is that on every authentication?

**Comment by amir-qayyum-khan** [comment]
@pdpinch it is social auth https://github.com/mitodl/micromasters/blob/master/micromasters/settings.py#L171

**Comment by amir-qayyum-khan** [comment]
@pdpinch here is PR https://github.com/mitodl/micromasters/pull/3801
