### ISSUE TITLE
"Skip and Pay Full Price" error

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3803]
### Steps to Reproduce (on CI and in production)

1. Delete or reset the learner's financial aid object. 
2. Click "Pay Full Price" on the dashboard, and again on the confirmation dialog

### Expected Behavior

- The learner's dashboard is updated with the full price: $1000

### Actual Behavior

- The learner gets a toast message "Failed to Skip Financial Aid"
- However, it appears that it actually succeeded"
  - the API returns a 200 (with no content)
  - the learner's financial aid object has a status of "skipped" 
  - reloading the browser restores the dashboard to the expected state

**Comment by aliceriot** [comment]
I'm able to reproduce this locally, so I think it's a programming error and not a configuration issue.

**Comment by pdpinch** [comment]
Can the fix for this include a fix for #3034?
