### ISSUE TITLE
Coupons: let user know that coupons will still work when paying full price

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3804]
As a learner who is part of a bulk purchase, I have a 100% off coupon (for a course or for the program) that I would like to use. I find it confusing that I have to fill out the personal pricing form and/or "skip and pay full price" to apply my 100% off coupon.

I think it would help if we had a brief message on the the personal price form and the "skip and pay full price" confirmation dialog that made it clear that coupons will still be applied. Maybe "(If you are using a coupon, it will be reflected when you checkout.)"

**Comment by roberthouse54** [comment]
I feel that there are a couple complications here. If we are telling people to just click "Skip and Pay Full Price" we may run into a problem if a user later decides to take OTHER courses. That user will now be locked into paying full price for courses. 

Basically, we are telling them to click "Pay Full Price" just so they can skip that requirement, and enroll for the course that they have a coupon for. The same is true for "Fixed Price" coupons. The user is being told that the course will only cost them $50, but they still have to determine their "program course price" before they can pay the $50.

I think we have to assume that a lot of the users in this particular use case will get the coupon from their employer, and will only ever want to take that one course for free (or for a limited price). For many of those users, "Skipping" the whole FA process to "Pay Full Price" will be fine. But we will run into a problem if any of those users later decide to take other courses in the program, and they have to pay full price, even if they would actually qualify for a discount.

**Comment by roberthouse54** [comment]
OK, well we may revisit this later, but for now let's just add some copy explaining what to do.

![image](https://user-images.githubusercontent.com/20047260/36918128-d3792348-1e26-11e8-99e6-f5e9d96e5cf0.png)

![image](https://user-images.githubusercontent.com/20047260/36918119-cab5430e-1e26-11e8-8754-53b6938ad3bb.png)
