### ISSUE TITLE
Misleading final grade search results

### ISSUE THREAD

**Issue by annagav** [mitodl/micromasters#3810]
The way enrollments are serialized [here](https://github.com/mitodl/micromasters/blob/master/dashboard/serializers.py#L17) only the first found paid course run enrollment is serialized and indexed, and that is the course run grade and semester that will show up in the search results.

It looks like for the final grade facet we should pick the best final grade the learner earned for the course.

**Comment by pdpinch** [comment]
Nice catch. I think this is the root cause of an issue that Lu showed me just a few days ago. 

I agree that we should choose the best grade, and I think it would be appropriate to do this work this sprint, while we're working on #3777.

**Comment by pdpinch** [comment]
I'm having second thoughts on picking just the best one, based on a conversation I'm having with Max. If anyone works on this, we should discuss.
