### ISSUE TITLE
Percolate error related to ES5 upgrade

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#3817]
#3789 

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/455485523/

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/455485465/

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/455374473/

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/455485525/

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/455485467/

**Comment by pdpinch** [comment]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/455485523/
