### ISSUE TITLE
'View more' link exists on learner search page but it's not functional

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#3820]
![screenshot from 2018-02-08 16-45-20](https://user-images.githubusercontent.com/863262/35999977-7e303194-0cef-11e8-99f4-d15fb82833d5.png)

**Comment by pdpinch** [comment]
This used to work...

**Comment by amir-qayyum-khan** [comment]
how to produce view more link, I dont see it at all.

<img width="494" alt="screen shot 2018-02-22 at 8 07 08 pm" src="https://user-images.githubusercontent.com/10431250/36545972-fcac391a-180b-11e8-9399-04ae2e9b9c1a.png">

**Comment by noisecapella** [comment]
I investigated this further, I think I misunderstood the expected behavior. The 'view more' link adds an extra 50 employers, but if that's not all employers the link will stay the same. If you open up the dropdown after you can see that the number of employers is increasing each time
