### ISSUE TITLE
Snapshot Dashboard Exam States: use FA program to test exam states

### ISSUE THREAD

**Issue by annagav** [mitodl/micromasters#3825]
The function that creates the dashboard state related to exams is using a non FA program [link](https://github.com/mitodl/micromasters/blob/632ca9071f61b1e8e76f567ea70d61e4fae4f488/selenium_tests/management/commands/snapshot_dashboard_states.py#L80).

**Comment by pdpinch** [comment]
Since that isn't going to happen in practice (for at least the next two years), can we just change it to use an FA course?
