### ISSUE TITLE
Update README on how to add enough memory for ES5 if using docker-machine on OSX

### ISSUE THREAD

**Issue by mbertrand** [mitodl/micromasters#3832]
ElasticSearch 5.x will not start properly on OSX when running under a docker-machine:
```
elastic_1  | ERROR: [1] bootstrap checks failed
elastic_1  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elastic_1  | [2018-02-12T17:01:08,229][INFO ][o.e.n.Node               ] [OjcDjUi] stopping ...
elastic_1  | [2018-02-12T17:01:08,297][INFO ][o.e.n.Node               ] [OjcDjUi] stopped
elastic_1  | [2018-02-12T17:01:08,308][INFO ][o.e.n.Node               ] [OjcDjUi] closing ...
elastic_1  | [2018-02-12T17:01:08,368][INFO ][o.e.n.Node               ] [OjcDjUi] closed
```

The solution is to run the following, this should probably be added to the README:
```
docker-machine ssh <machine_name>
sudo sysctl -w vm.max_map_count=262144
```

**Comment by noisecapella** [comment]
To do this permanently you need to update a different config file `/var/lib/boot2docker/profile` within docker-machine (see https://github.com/boot2docker/boot2docker/issues/1216). 

You should also increase the memory in your docker-machine VM to 4gb or so

**Comment by pdpinch** [comment]
@noisecapella should we solve this with documentation, or is there a way to add it to the docker dev config?

**Comment by noisecapella** [comment]
@pdpinch there may be some docker-machine hook we can use to update this file, it's worth investigating

**Comment by mbertrand** [comment]
No longer relevant, assuming that we stop using docker-machine on OSX going forward.

**Comment by pdpinch** [comment]
Ok. I can reopen if we ever need it again.
