### ISSUE TITLE
Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3850]
This problem seems to be exclusive to Chrome, possibly mobile only. 

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/441892967/

```
SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
  at None (/dedp/)
```

**Comment by amir-qayyum-khan** [comment]
unable to produce it on desktop, tested on changing view

**Comment by pdpinch** [comment]
This error appears to have stopped entirely.
