### ISSUE TITLE
Search: Current residence facet is limited to the first 20 countries 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3854]
See https://odl.zendesk.com/agent/tickets/15176

Maybe this was a side effect of the SearchKit upgrade?

**Comment by pdpinch** [comment]
@noisecapella do you happen to know if this is a regression, or due to a limitation in SearchKit?

**Comment by noisecapella** [comment]
It's probably a regression. There were some `size` aggregation parameters which were removed due to incompatibility with Elasticsearch 5, but there may be an alternative I didn't investigate. https://github.com/mitodl/micromasters/pull/3789/files#diff-19b75ce18fd1eaefee48fc255d15b45bL374

**Comment by noisecapella** [comment]
Some discussion on the removed support for `size={0}`: https://discuss.elastic.co/t/term-aggregation-size-0/64278/3

However we should be able to set a size large enough to hold all the countries

**Comment by pdpinch** [comment]
Do we set the size to the total number of countries? Or does it need to be countries + region combinations?

**Comment by noisecapella** [comment]
The size is set to 1000 but that just covers the number of countries. The size for states or territories is the default which is 20. Should I increase that too?

**Comment by pdpinch** [comment]
Would it be reasonable to set it to the maximum number of regions in our ISO-3166 dataset? 


> The size for states or territories is the default which is 20. Should I increase that too?

**Comment by noisecapella** [comment]
We can set it to 1000 if we want, the performance penalty is only for the number of territories that are available. That's higher than the maximum of 239 for Great Britian, with lots of room to handle updates

**Comment by noisecapella** [comment]
Actually I was wrong, that 1000 value is already applied for all facets so it would mean a max of 1000 countries and 1000 territories, which should be more than enough
