### ISSUE TITLE
Dashboard: display "View certificate" link even when user is auditing a course

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3862]
As a learner who has earned a course certificate, I would like to be able to audit the course again, and still be able to access my certificate. 

Currently, the dashboard message "You are auditing. You need to pay to get credit" is superseding the message "You passed this course. View Certificate" We need some way to display the "View certificate" link in this state. 

See [ZenDesk #15251](https://odl.zendesk.com/agent/tickets/15251) (FA course) and [ZenDesk #15260](https://odl.zendesk.com/agent/tickets/15260) (non-FA course).

**Comment by roberthouse54** [comment]
![image](https://user-images.githubusercontent.com/20047260/36865765-7a36cc40-1d5e-11e8-8dbc-6d044c8da91d.png)
