### ISSUE TITLE
Honor user privacy setting when viewing profile

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#387]
We have 3 types of user and 3 privacy settings, but only 7 use cases and 3 possible outcomes.

### Users  
1. The current user
2. A verified micromasters user (to be defined, but we will add a field to the user profile)
3. An anonymous use (not logged in). 

### Privacy Settings 
1. Private
2. Public to other verified micromasters users
3. Public to all

### Possible Outcomes
1. Access to the complete profile
2. Access to the public profile (all fields, except birthdate, `filled_out`, `agreed_to_terms_of_service`, `email_optin`, `pretty_printed_student_id`, `birth_city`, `birth_state_or_territory`
3. Access to a restricted profile (only the fields `username`, profile images, and `account_privacy`

### Use Cases
Case 1: User Foo looks at profile Foo (same user)
This is easy: the user should see everything: Outcome 1

Case 2: The user Foo (a MM student) looks at the profile Bar (with privacy set to "private")
Restricted Profile: Outcome 3

Case 3: the verified micromasters user Foo looks at the profile Bar (with privacy set to "private to MM students")
Public Profile: Outcome 2

Case 4: the verified micromasters user Foo looks at the profile Bar (with privacy set to "public")
Public Profile: Outcome 2 (same as case 3)

Case 5: The user Foo (not a verified micromasters user) looks at the profile Bar (with privacy set to "private")
Restricted Profile: Outcome 3

Case 6: The user Foo (not a verified micromasters user) looks at the profile Bar (with privacy set to "private to MM students")
Restricted Profile: Outcome 3 (same as case 5)

Case 7: The user Foo (not a verified micromasters user) looks at the profile Bar (with privacy set to "public")
Public Profile: Outcome 2

**Comment by noisecapella** [comment]
It looks like we already do this in the REST API, but we should at least double check that the proper tests are in place and that we're handling all three privacy settings

**Comment by giocalitri** [comment]
What the different users are supposed to see?

Case 1: User Foo looks at profile Foo (same user)
This is easy: the user should see everything.

Case 2: The user Foo looks at the profile Bar (with privacy set to "private")
?

Case 3: The user Foo (a MM student) looks at the profile Bar (with privacy set to "private to MM students")
?

Case 4: The user Foo (a MM student) looks at the profile Bar (with privacy set to "public")
Is this the same of case 3?

Case 5: The user Foo (NOT a MM student) looks at the profile Bar (with privacy set to "private")
?

Case 6: The user Foo (NOT a MM student) looks at the profile Bar (with privacy set to "private to MM students")
Is this the same of case 5?

Case 7: The user Foo (NOT a MM student) looks at the profile Bar (with privacy set to "public")
?

**Comment by pdpinch** [comment]
I'll update the description once we work through the details, but here's my first pass. 

Case 1: User Foo looks at profile Foo (same user)
This is easy: the user should see everything.

Case 2: The user Foo (a MM student) looks at the profile Bar (with privacy set to "private")
returns a 404

Case 3: The user Foo (a MM student) looks at the profile Bar (with privacy set to "private to MM students")
we display all profile information except birthdate (at least, in the current profile data we collect, I believe this is the only data that needs differential protection. If we collected mailing addresses, we might want to protect that as well)

Case 4: The user Foo (a MM student) looks at the profile Bar (with privacy set to "public")
same as Case 3

Case 5: The user Foo (NOT a MM student) looks at the profile Bar (with privacy set to "private")
same as Case 2, return a 404

Case 6: The user Foo (NOT a MM student) looks at the profile Bar (with privacy set to "private to MM students")
same as case 5 and case 2, return a 404

Case 7: The user Foo (NOT a MM student) looks at the profile Bar (with privacy set to "public")
same as case case 3, all the profile except birthdate 

@giocalitri @Ferdi if this makes sense I'll up date the description for this issue. (Let me know if there's any additional vetting we need?)

**Comment by giocalitri** [comment]
I have 2 doubts: 

1. the 404 looks a bit too eccessive to me: it means we are basically allowing the users to be invisible in the context of the application. I am not sure, but I think that LinkedIn does not allow this and probably only Facebook does.
2. should the cases 3, 4 and 7 exclude also 
    "filled_out", "agreed_to_terms_of_service", "account_privacy", "email_optin"?

**Comment by giocalitri** [comment]
Looking at edx, for private users, it returns a 200 with just username, profile_image and account_privacy.
```
HTTP 200 OK
Content-Type: application/json
Vary: Accept
Allow: GET, PATCH, HEAD, OPTIONS
{
    "username": "emmazp",
    "profile_image": {
        "image_url_full": "https://d37djvu3ytnwxt.cloudfront.net/static/themes/edx.org/images/profiles/default_500.d41d8cd98f00.png",
        "image_url_large": "https://d37djvu3ytnwxt.cloudfront.net/static/themes/edx.org/images/profiles/default_120.872c4f351224.png",
        "image_url_medium": "https://d37djvu3ytnwxt.cloudfront.net/static/themes/edx.org/images/profiles/default_50.76570a4d025e.png",
        "image_url_small": "https://d37djvu3ytnwxt.cloudfront.net/static/themes/edx.org/images/profiles/default_30.a82b312fc98a.png",
        "has_image": false
    },
    "account_privacy": "private"
}
```

**Comment by giocalitri** [comment]
Another note from a conversation with @pdpinch:

We should introduce a flag in the profile for `verified_micromaster_user` to be set to `True` when the student is `enrolled verified` in at leas one micromaster course.

**Comment by pdpinch** [comment]
@giocalitri @Ferdi I updated the description to combine Giovanni and my conversations. Let me know if I got everything right.

**Comment by giocalitri** [comment]
@pdpinch I think it is worth mentioning that we assume that unverified micromasters users will be considered as anonymous users for profile features

**Comment by pdpinch** [comment]
Thx. I updated the description.
