### ISSUE TITLE
Only create one course certificate per user per course

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3870]
With the release of the most recent proctored exam results, it's come to our attention that we are creating duplicate certificates for some learners. We create certificates when a learner passes an edX online course run and the corresponding proctored exam. 26 learners who have passed a proctored exam have taken passed multiple course runs and now have multiple course certificates. See https://bi.odl.mit.edu/queries/179 for a list

Although it hasn't happened yet, I expect additional certificates will be created if and when a learner passes a proctored exam multiple times. 

Instead, we should limit learners to one certificate per course

### acceptance criteria:
- [ ] Before creating a certificate, check the certificates table for existing course certificates for the user and the course in question
- [ ] if the user already has a course certificate, don't create a new one

### related issues
- For users with multiple certificates, link to the one with the best grade

**Comment by pdpinch** [comment]
You told me in #3872 that we have a reliable way to show only the "best" certificate. Given that, I don't think we need to do anything to clean up the existing duplicates -- at least for now. 

I'm a little nervous about just deleting the duplicates, because I don't know if users have linked to them.

**Comment by annagav** [comment]
Currently the MicromastersCourseCertificate is linked to a final grade. So if user passed a course he would have as many course certificates as passing final grades. Multiple exam runs do not lead to the creation of certificates, only multiple final grade do.
If I limit the creation of the certificates a user likely will have a certificate not for the best final grade. So the way we choose which certificate to show is not going to work anymore.

**Comment by pdpinch** [comment]
@annagav I think this is done now that you fixed the migration. I'm going to close this. 

@maxliu FYI, there shouldn't be duplicate course certificates any more.
