### ISSUE TITLE
Dashboard: certificate link should go to "best" certificate

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3872]
On the learner dashboard we only provide one link to the learner's certificate per course. This is ambiguous for learners (in both FA and non-FA courses) who have earned multiple certificates. 

When multiple certificates are available, we should link to the one from the course run with the best final grade. This is consistent with our practice of considering learners' best grades as the most significant.

**Comment by annagav** [comment]
As far as I know we are showing the certificate with the best grade, see here: https://github.com/mitodl/micromasters/blob/a623ed2a4234890f9bf7e8e97a1abeacdf79522e/dashboard/api.py#L500

Do we have cases where it shown the wrong certificate?

**Comment by pdpinch** [comment]
Nice job, planning ahead! 

I mistakenly assumed that we were just grabbing the first, or the most recent.
