### ISSUE TITLE
Profile viewer: add plus buttons to profile viewer

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#389]
... so the user can add additional degrees and jobs

clicking plus will open the form component to add a new item. 

the form is validated when the user saves it.

**Comment by aliceriot** [comment]
is this a different task than making the current education and employment components work on the profile view? they already include buttons for adding entries.

**Comment by pdpinch** [comment]
Sounds like it's already covered. If that's merged, you can close this.

**Comment by aliceriot** [comment]
not yet merged, but I'll close this when all the work I'm doing is done.

**Comment by pdpinch** [comment]
closed via #445 and #406
