### ISSUE TITLE
add contact us link to footer

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3891]
We recently heard from a user trying to find a contact us link on the home page. We should add a link to the footer. Any contact should go to ZenDesk.

**Comment by roberthouse54** [comment]
We are going to add a contact us link to the footer, and when it is clicked, it will open the zendesk contact form.

![image](https://user-images.githubusercontent.com/20047260/37678162-a9b0ece0-2c53-11e8-853b-8d6801bdd84b.png)

**Comment by amir-qayyum-khan** [comment]
the same form appear on clicking zendesk widget?

@pdpinch @roberthouse54

**Comment by pdpinch** [comment]
Yes. 

We want users who think "I want to contact the MicroMasters program" to use the same form and open a ZenDesk ticket.

**Comment by amir-qayyum-khan** [comment]
Only a logged in user can contact? Is this button will be show to login users only?

@pdpinch

**Comment by pdpinch** [comment]
No, any user should be able to use the form. 

I believe you can use the ZenDesk form on, for example, the program page without being logged in. You just need to type in your return e-mail.
