### ISSUE TITLE
invitation-only exam runs

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3914]
As a course team member, I would like to be able to set up an exam run for which learners must be authorized manually instead of automatically after having paid & passed a course. This would allow me to schedule "pop-up" proctored exams in regions where there is no Pearson exam center.

**Comment by pdpinch** [comment]
In discussing with @rhysyngsun most of this is already achievable by creating an exam run with a unique exam code and schedulable dates in the past. This will avoid automatic authorizations and also prevent the exam from being announced on learner dashboards. 

We could write a simple management command that takes the usernames to be authorized, creates the appropriate exam runs and authorizes the learners. 

The authorization process should follow the same requirements of having passed the course and paid. Manually authorized learners would have the same dashboard experience, with a schedule button. Even if there is only one schedulable exam, this is still preferred since it will integrate with Pearson systems in the same way.

**Comment by pdpinch** [comment]
This mostly works, but there is one issue: #4137

**Comment by pdpinch** [comment]
I did this manually for a late September exam run with 2 learners. After the fact, we learned that I had made an error in setting up the exam authorization. 

We should write a management command for this. Here is the code I ran manually. 

```
# authorize user `<userhname>` for examruns 28-32 (all five)
from django.contrib.auth.models import User
from courses.models import Course
from grades.models import FinalGrade
from exams.api import authorize_user_for_schedulable_exam_runs
from dashboard.utils import get_mmtrack
from dashboard.models import Program
from exams.models import ExamRun

dedp = Program.objects.get(title='Data, Economics, and Development Policy')
user = User.objects.get(email='<email>')
mmtrack = get_mmtrack(user,dedp)
for course in Course.objects.filter(program=dedp):
course_run = FinalGrade.objects.filter(user=user).filter(course_run__course=course).first().course_run
exam_run = ExamRun.objects.filter(course=course).filter(id__gte=28).filter(id__lte=32).first()
ExamAuthorization.objects.get_or_create(
    user=mmtrack.user,
    course=course_run.course,
    exam_run=exam_run,
)

```

**Comment by annagav** [comment]
@pdpinch so we want a management command that would generate authorizations for all courses in a program? The arguments to the command would be the program and a list of usernames?

**Comment by pdpinch** [comment]
Good question. 

We would only be authorizing one exam at a time, since a user may not have passed all the online courses. 

I think it would be best for the arguments to be a username/email and a course key. We might also need to specify an expiration date, but I’m not sure. 

I don’t mind running the command once per user. I don’t expect there to be more than 3-5 of these per term. 

One thing I’m not sure about is whether we can use the exam run (in the past) for all of these, instead of having to create new expired runs each term. 

We can talk more if any of this is confusing.  

- Peter
