### ISSUE TITLE
Upgrade to heroku-16 stack

### ISSUE THREAD

**Issue by shaidar** [mitodl/micromasters#3918]
App is currently running on Heroku `cedar-14` stack which is based on Ubuntu 14. We should look into upgrading to the `heroku-16` stack.

More info available [here](https://devcenter.heroku.com/articles/heroku-16-stack)

**Comment by pdpinch** [comment]
@amir-qayyum-khan since you have a PR for this, I'm assigning it to you and moving it to In Progress. 

@mitodl/devops we're going to need you to review Amir's PR in order to close this.
