### ISSUE TITLE
Set timeout for edX API calls

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#3928]
If the timeout was less than 30 seconds it would error to sentry before heroku terminates the connection so that we have a record of this

**Comment by pdpinch** [comment]
The timeout should be configurable, with a default of something less than 30 seconds: say 25 seconds. 

When the timeout happens, we can just raise an error to Sentry and log it?

**Comment by noisecapella** [comment]
I think it should by default. Looking at the edx-api-client source if we raise the exception in `requester` it should get handled like all of the other API exceptions
