### ISSUE TITLE
Wagtail can't handle missing file on S3

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3943]
I'm not sure how this happens, but twice now SCM documents in Wagtail get into a state where the file is missing. Instead of letting the CMS user upload another file, the edit form (and the view of the document) just fails. 

This Sentry error comes from the edit form. It's clearly not catching the exception properly when using S3 for storage: 

AttributeError: 'NoneType' object has no attribute 'size'

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/530801067/

```
AttributeError: 'NoneType' object has no attribute 'size'
(5 additional frame(s) were not displayed)
...
  File "wagtail/admin/urls/__init__.py", line 95, in wrapper
    return view_func(request, *args, **kwargs)
  File "wagtail/admin/decorators.py", line 28, in decorated_view
    return view_func(request, *args, **kwargs)
  File "wagtail/admin/utils.py", line 139, in wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "wagtail/documents/views/documents.py", line 154, in edit
    filesize = doc.file.size

AttributeError: 'NoneType' object has no attribute 'size'
```

**Comment by pdpinch** [comment]
This is the Sentry error that is raised when an end user tries to access the file. 

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/530800722/

**Comment by amir-qayyum-khan** [comment]
strange getting issue https://github.com/wagtail/wagtail/blob/master/wagtail/documents/views/documents.py#L154
but it should  fix issue https://github.com/wagtail/wagtail/blob/master/wagtail/documents/views/documents.py#L152

What version of wagtail we are using?

**Comment by pdpinch** [comment]
2.0

https://github.com/mitodl/micromasters/blob/a55af8037d7002579ff6375acfd3a981a149e35a/requirements.txt#L91

Do you think an upgrade will fix this issue?

**Comment by amir-qayyum-khan** [comment]
this file is exact same in next version. dont know why code is bypassing https://github.com/wagtail/wagtail/blob/v2.0/wagtail/documents/views/documents.py#L152
