### ISSUE TITLE
Move hardcoded 'I'm Interested' link into ProgramPage model

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#3952]
This link for #3949  was added as part of #3950 and is specific for one URL. We should move it into a model so that it varies depending on the program

**Comment by pdpinch** [comment]
@tasawernawaz this is rather urgent -- we need to get this URL changed before Monday morning. 

Do you think you could add this to the CMS on Thursday?

**Comment by tasawernawaz** [comment]
@pdpinch I am confident that this can be done by the end of today. Only question is that would we merge this before #4294 ?
