### ISSUE TITLE
Dashboard state 0014: passed course, another offered

### ISSUE THREAD

**Issue by annagav** [mitodl/micromasters#3972]
The user passed the course, another course run is offered:

![screen shot 2018-05-02 at 12 58 06 pm](https://user-images.githubusercontent.com/7574259/39537750-7e6bcd3a-4e08-11e8-8e8e-dbfb74aa71fb.png)

Should we show a message for current course run, and offer to enroll again?

How the message would change if the user paid for `Course`, not for `CourseRun`? (related to `gdm_course_payment`)

**Comment by pdpinch** [comment]
@roberthouse54 can I get a 2nd opinion on this?

**Comment by pdpinch** [comment]
@annagav @roberthouse54 is this still an issue?

**Comment by annagav** [comment]
Now this state looks like this:

<img width="703" alt="screen shot 2018-08-14 at 4 18 23 pm" src="https://user-images.githubusercontent.com/7574259/44116151-b8f685b8-9fdd-11e8-9f49-99ae1d555d71.png">

**Comment by pdpinch** [comment]
no longer relevant since the exam model has changed.
