### ISSUE TITLE
Stop updating OD user data when MicroMasters updates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3987]
Currently, when a user updates their profile (manually) or gets a email change from edX (automatically on login) we synchronize the change to open discussions. edX + MicroMasters is the source of truth. 

When open discussions allows users to modify their profiles and account settings, we want to let it be it's own source of truth. We need to stop updating user data from MicroMasters. 

This issue is blocked by https://github.com/mitodl/open-discussions/issues/681, https://github.com/mitodl/open-discussions/issues/682, https://github.com/mitodl/open-discussions/issues/683 and an issue that hasn't been written yet to allow users to change their e-mail in open discussions.

**Comment by pdpinch** [comment]
We added a flag to control this behavior in #4010.

When the blocking issues are addressed, we can change the flag to false and close this issue.

**Comment by pdpinch** [comment]
@rhysyngsun you said yesterday that this is still blocked, but I've forgotten what issue is blocking it. 

Also, at one point you said the feature flag in #4010 wasn't implemented correctly. Is that still an issue?

**Comment by rhysyngsun** [comment]
The feature flag was fixed in #4105, we just need to flip the switch on this and profile editing on discussions.

**Comment by rhysyngsun** [comment]
Done in CI, RC, and prod
