### ISSUE TITLE
Update discussions URL in settings to be auth end point

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3988]
related to https://github.com/mitodl/open-discussions/issues/670

**Comment by pdpinch** [comment]
@rhysyngsun is `OPEN_DISCUSSIONS_REDIRECT_URL` the setting that needs to be changed? 

When can we safely make this change? I presume it depends on https://github.com/mitodl/open-discussions/pull/699 being deployed to production. Does it also depend on `FEATURE_ANONYMOUS_ACCESS` being set to `TRUE` ?

**Comment by amir-qayyum-khan** [comment]
This is not clear enough. Does this issue about changing variable in code or its content ?
if content then that means that content is not set via .env?

**Comment by rhysyngsun** [comment]
@amir-qayyum-khan this requires coordination with auth work going on in discussions, I'm assigning to myself since I'm working on the epic over there.

**Comment by pdpinch** [comment]
@rhysyngsun what is blocking this? https://github.com/mitodl/open-discussions/pull/1093 ?

**Comment by rhysyngsun** [comment]
Done in prod
