### ISSUE TITLE
Exams: don't create authorizations for users who are not active

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3990]
As a user who has asked for my account to be deleted, I don't want to continue receiving exam authorizations. 

It seems like the simplest way to handle this is to filter out users who have `is_active=False` from the exam authorization function.

**Comment by amir-qayyum-khan** [comment]
@pdpinch Should we change tasks for this https://github.com/mitodl/micromasters/blob/master/exams/tasks.py

**Comment by pdpinch** [comment]
The second one, I would think. That's where the rest of the business logic is. 

https://github.com/mitodl/micromasters/blob/master/exams/api.py#L69
