### ISSUE TITLE
Fix layout and copy issue on mobile image uploader

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#3992]
The profile image uploader on mobile currently has a clunky layout with no left/right margins. Also the copy is wrong, as it says to "drag a photo" into the box, which is impossible on mobile.

![image](https://user-images.githubusercontent.com/20047260/40558369-1da58286-6021-11e8-871c-680419ea669e.png)

**Comment by pdpinch** [comment]
I think this can be closed?
