### ISSUE TITLE
How will we handle users under 13?

### ISSUE THREAD

**Issue by justinabrahms** [mitodl/micromasters#40]
How do we handle users who are under 13 years old? 

https://openedx.atlassian.net/browse/TNL-1606

That's the ticket from edX dealing with the same question. This is now exposed in their profile API, but what are we going to do about asking for their specific profile information on our side? Are there legal issues here?

**Comment by pwilkins** [comment]
And we expect a thirteen-year-old to seek a masters degree in supply chain management?

**Comment by noisecapella** [comment]
When you register at edx.org, the part where you list your age is an optional field, so it may be a common case that `requires_parental_consent` is true and we have to assume they are under 13.

**Comment by justinabrahms** [comment]
Especially as we add social features, this will become an issue. https://en.wikipedia.org/wiki/Children%27s_Online_Privacy_Protection_Act for back story.

**Comment by noisecapella** [comment]
We could just ignore edX's information (which is probably missing this field) and ask for their birthday ourselves. We could just forbid people under 13 years old from enrolling, not sure if that fits the overall goals of micromasters

**Comment by noisecapella** [comment]
I think the answer to this question is now, we'll just not allow these users. We'll ignore edX's information on this because we will ask them again when they fill out their profiles
