### ISSUE TITLE
Dashboard: Pending Payment message obscures re-enroll message

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4004]
As a learner who a) has not passed a course and b) is waiting for personal pricing approval, I would like to enroll in the next course run and try again. 

According to [ZenDesk #17524](https://odl.zendesk.com/agent/tickets/17524) it appears that the "Your personal course price is pending" message is preventing the  "You did not pass the edX course, but you can re-enroll" message from appearing.

**Comment by pdpinch** [comment]
@annagav thanks for pursuing this quick fix, but this issue is still in the backlog.

**Comment by annagav** [comment]
This is not the fix yet, this is just a dashboard state to see the message.

**Comment by annagav** [comment]
I think this was fix by #4011.

**Comment by pdpinch** [comment]
Ok, I'll take a look. 

> I think this was fix by #4011 <https://github.com/mitodl/micromasters/pull/4011>.

**Comment by pdpinch** [comment]
As far as I can tell, this is working now.
