### ISSUE TITLE
Error when viewing draft in wagtail

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#4007]
https://sentry.io/mit-office-of-digital-learning/micromasters/issues/571734480/?query=is:unresolved

**Comment by amir-qayyum-khan** [comment]
is there way to reproduce it?

**Comment by pdpinch** [comment]
I think this is happening when you preview a saved draft.

**Comment by amir-qayyum-khan** [comment]
@pdpinch not able to reproduce yet

**Comment by amir-qayyum-khan** [comment]
i think that link is showing preview error which is case by large amount of description text. We opened an issue on wagtail end. Should i ask progress on the issue?

**Comment by pdpinch** [comment]
The change in #4049 still needs to be load tested before we can turn it on
