### ISSUE TITLE
Exams: allow learner to pay for 3rd exam

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4025]
As a learner, I'd like to take the proctored exam a third time, beyond the two attempts that are offered with one payment. 

Currently, we restrict learners to two attempts per payment. IIRC, this is implemented at the exam authorization stage, so we don't authorize learners who have had two grades. However, we don't seem to allow learners to pay again via the dashboard. 

See ZenDesk https://odl.zendesk.com/agent/tickets/17987

**Comment by annagav** [comment]
I have looked through all the exam states and looks like this prblem happens in the state where the user had two exam attempts and there is new course run offering:

<img width="765" alt="screen shot 2018-06-19 at 2 52 32 pm" src="https://user-images.githubusercontent.com/7574259/41618188-74fd79ea-73d0-11e8-945a-c86d1e556e6d.png">

**Comment by annagav** [comment]
Do we want to be telling info about scheduling/paying for exams if the user has one failed one passed, or two passed exams?

**Comment by annagav** [comment]
@roberthouse54 said we don't want to show messages about scheduling exams if the user already has at least one passed exam.

**Comment by pdpinch** [comment]
As long as the user has the option to pay again

**Comment by pdpinch** [comment]
@annagav I just saw this PR your wrote last year: https://github.com/mitodl/micromasters/pull/3484 -- was there a regression?

**Comment by annagav** [comment]
@pdpinch, could you clarify. Right now the Pay Now button shows up in the message box where we tell the user about having to take exam. That message would show up only if the user has failed all the exam attempts. If the user passed at least one exam, there will be no message and no button to pay.

**Comment by annagav** [comment]
The reason the users did not see the pay button is that in StatusMessages there was a condition that gave priority to message about future enrollable run. I am fixing that in the PR by showing both messages.

**Comment by pdpinch** [comment]
@annagav I'm still having trouble in the specific case in [ZenDesk #17987](https://odl.zendesk.com/agent/tickets/17987). Here's a (redacted) screenshot:

![screenshot 2018-06-27 14 36 51](https://user-images.githubusercontent.com/430126/41993051-322881ca-7a18-11e8-90f1-13785b5af1cc.png)

1. Even though the learner has paid twice, the message says they can take the exam again. 
2. There's no way for the learner to pay again for a 3rd exam.

**Comment by annagav** [comment]
@pdpinch, the PR that fixes this issue is still in in review PR#4032. I think i linked the wrong issue.

**Comment by pdpinch** [comment]
@annagav this still isn't working for the user who originally requested it in [ZenDesk #17987](https://odl.zendesk.com/agent/tickets/17987). Here's a screenshot from [v0.106.0 in production](https://github.com/mitodl/micromasters/releases/tag/v0.106.0):

![screenshot 2018-07-05 09 03 37](https://user-images.githubusercontent.com/430126/42324921-a6fe96cc-8032-11e8-83d9-71c4ad9530a1.png)


It looks like the dashboard API returns the correct value for the Microeconomics course, `has_to_pay: true` but the front-end isn't offering a link to pay again.

**Comment by annagav** [comment]
It is not offering to take another exam because the user has a passing exam. I asked this question earlier in the comments, and it looked like it was confirmed. https://github.com/mitodl/micromasters/issues/4025#issuecomment-398834591

**Comment by pdpinch** [comment]
Sorry, I misunderstood your question. The whole point of this issue is to allow [this learner](https://odl.zendesk.com/agent/tickets/17987) to pay for a 3rd attempt. We don't need to say anything about _scheduling_ but we do need to say something about how they can _pay_ again. 

After they've paid, then we should tell them about scheduling again.

**Comment by annagav** [comment]
@pdpinch, that means that user cannot schedule to take the exam yet, the scheduling window is in the future.
