### ISSUE TITLE
Dashboard: don't tell learner they can sign up for an exam when they can't

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4026]
Related to #4025 

Learners are given two proctored exam attempts per payment. If the learner has already made two attempts, we shouldn't tell them they can sign up for a 3rd attempt -- at least not until they have paid. 

Here is the current dashboard for a learner who has made two attempts:

![screenshot-micromasters mit edu-2018-06-15-13-05-14](https://user-images.githubusercontent.com/430126/41480844-c59ac7da-709d-11e8-8d4a-7c654a691440.png)

**Comment by pdpinch** [comment]
@roberthouse54 can we talk about this before any gets started working on it?

**Comment by roberthouse54** [comment]
If the learner has already made two attempts, let's change the copy to say "If you want to re-take the exam, you need to <a>pay for the course again</a>"

**Comment by annagav** [comment]
This should be fixed now by PR#4028
