### ISSUE TITLE
Better error message when learner has paid but isn’t enrolled 

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#4034]
![image](https://user-images.githubusercontent.com/20047260/41857631-faf92bae-7865-11e8-84fa-ef765cb8db24.png)

New copy: You paid for this course but are not enrolled. You can Enroll Now, or if you think there is a problem, contact us for help.

**Comment by pdpinch** [comment]
This replaces an existing "something went wrong" error message

**Comment by annagav** [comment]
@pdpinch does this apply to non-FA courses?

**Comment by pdpinch** [comment]
nope. just FA

> @pdpinch <https://github.com/pdpinch> does this apply to non-FA courses?
