### ISSUE TITLE
Allow learner to unenroll from program

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4056]
As a a learner, I'd like to be able exit a program -- to stop getting email updates and to stop seeing it on my dashboard. 

Now that we're adding more programs, we're finding that some learners want to exit the program they are current enrolled in and register for another one. 

### questions
- is edX doing anything to track learner enrollment in programs now? 

### related issues
#2018 when manually deleting/retiring a user, we typically delete all their program enrollments

**Comment by roberthouse54** [comment]
1. Add a link to the settings bage to "Leave a MicroMasters Program"

![1](https://user-images.githubusercontent.com/20047260/43271041-83bbe212-90c4-11e8-9944-7f1c954e12e7.png)

2. Open a modal, that allows the user to select which program they want to leave. This would show all programs the user is enrolled in. We can also have a "All Programs" option. 
![2](https://user-images.githubusercontent.com/20047260/43271123-b6b9d26e-90c4-11e8-8cae-b3d669a66c48.png)

3. On submission, show a "success" toast message. 
![3](https://user-images.githubusercontent.com/20047260/43271153-c941e3c2-90c4-11e8-8f5c-62d3ca07c526.png)

4. If the user has unenrolled from all MicroMasters programs, then their dashboard will show an empty state, with a link allowing them to enroll in a program.
![4](https://user-images.githubusercontent.com/20047260/43271191-e7516252-90c4-11e8-9051-52fd8a7488fe.png)

**Comment by amir-qayyum-khan** [comment]
@pdpinch what i will Do

- remove user from model http://192.168.99.100:8079/admin/dashboard/programenrollment/
- Do i need to remove him from discussion as moderator if he is staff?
-  Show no program UI if he had single program. From there user can enroll.

**Comment by pdpinch** [comment]
Could you be more specific about what you mean by "remove user from model?"

I don't think it's necessary to remove the user's staff role, unless it's going to cause exceptions. They should be removed from any discussions channels automatically, because they will no longer have the necessary program enrollment. 

How will you populate the drop-down list of programs the user can leave?

**Comment by amir-qayyum-khan** [comment]
The model i was referring was program enrollment model.

i will load programs from dashboard api,
new api can also. be made.

**Comment by pdpinch** [comment]
Is the dashboard API already being loaded on this account settings page?

The dashboard API is quite slow. It's fine if we're already loading it, but we should avoid it if we can. I think there's a programs API that might be do what we need?

**Comment by amir-qayyum-khan** [comment]
i am going to use program api to load enrolled program. because that api is already call on settings page.
