### ISSUE TITLE
Freeze grades: RuntimeError: Never call result.get() within a task!

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4063]
I'm not sure how serious this is, but we're seeing a few errors like this per week. 

https://sentry.io/mit-office-of-digital-learning/micromasters/issues/592156147/

```
RuntimeError: Never call result.get() within a task!
See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks

(14 additional frame(s) were not displayed)
...
  File "celery/result.py", line 877, in _on_ready
    ResultSet._on_ready(self)
  File "celery/result.py", line 519, in _on_ready
    self._cache = [r.get() for r in self.results]
  File "celery/result.py", line 519, in <listcomp>
    self._cache = [r.get() for r in self.results]
  File "celery/result.py", line 203, in get
    assert_will_not_block()
  File "celery/result.py", line 41, in assert_will_not_block
    raise RuntimeError(E_WOULDBLOCK)

RuntimeError: Never call result.get() within a task!
See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks

```

**Comment by annagav** [comment]
It looks this issue has appeared with change that is causing now `ready()` to call AsyncResult `get()`, this might be a bug. Here is a similar issue: https://github.com/celery/celery/issues/4938. I was able to reproduce this locally, and played around to try to get the status of the tasks to decide whether there are any pending subtasks in result group, but it ends up going to call `get()` anyway.

**Comment by rhysyngsun** [comment]
Could we just send the revoke without checking `ready()`? It's just a celery signal to workers. Worst case wrap it in a `try` so it doesn't blow up this task.
