### ISSUE TITLE
Prevent edX users with is_active = False from creating accounts

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#4072]
At a minimum this is a call to `/api/users/v0/me` before `social_core.pipeline.user.create_user` is called to and checking `is_active` to abort the pipeline. We probably want to redirect them to a nice error page informing them what is required to proceed.

NOTE: We currently have an existing call [here](https://github.com/mitodl/micromasters/blob/328cce59ae5a9ff28850a9fff00f309bf187017d/backends/pipeline_api.py#L70-L75) to this API. We also have a call to the user_info API in the edx backend, when returns a subset of the users API. We should consolidate this to one upfront call.

  - [ ] Update MM to use new client library
  - [ ] Add `edx_is_active` field to `Profile` in MM to track if the email is verified on edX
  - [ ] Populate edx_is_active on login (checking with client library)

**Comment by annagav** [comment]
A call to `/api/users/v0/me` returns only `{'username': request.user.username}`. I think we have to use `/api/user/v1/accounts/{username}/` to get is_active
