### ISSUE TITLE
Limit creation/usage of discussion user accounts for edx inactive accounts

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#4073]
Limit discussion user account actions if edx email not confirmed

  - [ ] only create a discussion account when `edx_is_active is True`
  - [ ] only create a discussion jwt when `edx_is_active is True`

**Comment by pdpinch** [comment]
@rhysyngsun is this still necessary?

**Comment by rhysyngsun** [comment]
@pdpinch we're not storing these so I'll close it for now
