### ISSUE TITLE
Dashboard: add course dates to detail view

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4078]
As a user, when I look at the detailed list of grades on my dashboard, I can't tell which course is which. 

![screenshot 2018-07-27 08 28 17](https://user-images.githubusercontent.com/430126/43320695-55c464c0-9177-11e8-9982-200a07a2982e.png)

It seems like the simplest thing to do would be to add the course start and end dates to the end of the course title.

**Comment by roberthouse54** [comment]
This was the original design I had for this:
![image](https://user-images.githubusercontent.com/20047260/43413143-38339010-93fd-11e8-8c8a-f4072201c713.png)

**Comment by annagav** [comment]
This is what I was able to reproduce on master:
![screen shot 2018-08-06 at 3 50 42 pm](https://user-images.githubusercontent.com/7574259/43737821-9c7a3090-9990-11e8-8e28-aed3405047d0.png)

**Comment by pdpinch** [comment]
Can you use the same logic we use in the learner search for converting edx course keys to semesters?

See https://github.com/mitodl/micromasters/blob/12a0f36edd65ed0bcd6fb2b0e7fcd0028fc39df1/static/js/components/LearnerSearch.js#L70-L82

**Comment by annagav** [comment]
@pdpinch, the semesters seem to be already listed. What needs to change?
