### ISSUE TITLE
Use embedly display api for displaying image in detail page

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#4086]
Currently, in the detail page, we show the image directly from the source. Sometimes these images can be big and slow down the page. Consider using embedly display api to resize images.

**Comment by pdpinch** [comment]
Issue moved to [mitodl/open-discussions #1022](https://github.com/mitodl/open-discussions/issues/1022) via [**ZenHub**](https://www.zenhub.com/)
