### ISSUE TITLE
Search: no results for SDS learner search?

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4127]
I feel like I must be missing something, but when I do a search for SDS (program 4), I get no learner results. 

When I do a filter in the admin, I get 4000+ users.

**Comment by annagav** [comment]
@pdpinch, I think you just need to create a staff Role for that program in the django admin.

**Comment by pdpinch** [comment]
Ok, making myself staff took care of it. 

I thought we had "learner search for learners" turned on in production, but I guess not.
