### ISSUE TITLE
Exams: List schedulable exams based on authorizations

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4137]
We have an edge case where we would like to set up exam runs that can only be authorized manually. It works OK so far, but one issue is that when learners see the "schedule an exam" button on their dashboard when they have an active authorization, they don't see the list of courses. For example:

<img width="1004" alt="screen shot 2018-09-25 at 9 29 25 am" src="https://user-images.githubusercontent.com/430126/46017648-fb1e3d80-c0a5-11e8-80b3-8de7fc472a2a.png">

It appears the the "Schedule an Exam button" is controlled by the `pearson_exam_status` key in the dashboard API response, but the list of courses is built from other data (probably `course.can_schedule_exam`)

The first steps for this issue are to investigate the cause and then propose a solution, before implementation.

**Comment by amir-qayyum-khan** [comment]
i am not able to reproduce it, can you send me dashboard json. I can see the course name with minimal information attach in screenshot. My dashboard api has
```
"pearson_exam_status": "schedulable",
            "grade_average": 80,
            "certificate": "",
            "financial_aid_user_info": {
                "id": 1,
                "has_user_applied": true,
                "application_status": "skipped",
                "min_possible_cost": 403.0,
                "max_possible_cost": 1000.0,
                "date_documents_sent": null
            }
```
<img width="817" alt="screen shot 2018-10-02 at 6 46 28 pm" src="https://user-images.githubusercontent.com/10431250/46352567-92216180-c673-11e8-9254-0380f8c32fae.png">

**Comment by pdpinch** [comment]
I'll see if I can still reproduce it, but I think the issue is that `course.can_schedule_exam` is false

**Comment by amir-qayyum-khan** [comment]
the issue is he has 4 course and `"can_schedule_exam": false,`.
Then how pearson_exam_status": "schedulable",?

`pearson_exam_status": "schedulable",` should only appear when atleast one course has  `"can_schedule_exam": true,`

**Comment by amir-qayyum-khan** [comment]
```python
from exams.models import ExamProfile
from profiles.models import Profile
from exams.models import ExamAuthorization
from micromasters.utils import now_in_utc
from exams.models import ExamRun    

# create exam profile with status success
# create 4 courses
# create 4 past exam run
# authorize user for all past runs

profile = Profile.objects.get(user__username='aqkhan')
ex_profile = ExamProfile.objects.get(profile=profile)

# create new authorization for course 1 with `date_first_schedulable__lte` future
ExamAuthorization.objects.filter(id=4).update(status='success')
```
### Reproduce:

<img width="1155" alt="screen shot 2018-10-03 at 6 47 47 pm" src="https://user-images.githubusercontent.com/10431250/46414588-dd537700-c73c-11e8-9324-cbd580e9e356.png">

**Comment by pdpinch** [comment]
I agree, can_schedule_exam should be based on an exam authorization. Please proceed.
