### ISSUE TITLE
management command for retiring users

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4139]
we have been following a simple manual process for retiring users who want to have their account removed. For consistency and to avoid errors, we should commit it to a management command. 

### acceptance criteria
- [x] replicate the current, manual process:
  - [x] set `is_active=False` on the user
  - [x] set `email_optin=False` on the user's profile
  - [x] delete the user's program enrollment object(s)
    - deleting the program enrollments should signal an update to the elastic search index
- [x] delete any social auths (notably edX oauth tokens)
   - this will prevent any asynchronous data updates

**Comment by amir-qayyum-khan** [comment]
@pdpinch as you suggested i am putting this command in profile app
