### ISSUE TITLE
Dashboard: CSS issue

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4158]
inconsistent padding around the "passed" label

<img width="793" alt="screen shot 2018-10-11 at 9 40 58 am" src="https://user-images.githubusercontent.com/430126/46808300-04600900-cd3a-11e8-86e3-88941d1d59df.png">

**Comment by pdpinch** [comment]
@tasawernawaz here's a simple CSS issue to get started with

**Comment by tasawernawaz** [comment]
@pdpinch I am looking into this, however until now I can reproduce the scenario on my local machine. It would be much appreciated if you can guid my through steps to reproduce this.

**Comment by pdpinch** [comment]
@tasawernawaz to validate this issue on RC, you will need to:

1. Create a user on stage.edx.org (I will send you credentials)
2. Use that stage.edx user to create an account on micromasters-rc
3. Use the alter_data management command `set_course_run_to_paid` to give your user a passing grade in two runs of the same course (e.g. `course-v1:MITx+Digital+Learning+100+Aug_2015` and `course-v1:MITx+Digital+Learning+100+Jan_2016`)
4. View your learner's dashboard at /dashboard and click on the grade for "Digital Learning 100" which will open the pop-up where you can confirm the CSS change.

**Comment by tasawernawaz** [comment]
- I have an account for stage.edx.org. 
- What is the url for `micromasters-rc` ?
- I will go through the alter data management command and try to understand how it works.
