### ISSUE TITLE
Coupons: allow learner to skip payment step after applying a 100% off course coupon

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4160]
As a user it's confusing to apply a 100% course coupon and then still have to click the pay button to complete my purchase. We use 100% course coupons often to fulfill bulk sales and it's even more confusing when an organization purchases the coupon and then distributes them to their members. 

For 100% off program coupons, we already have a way to skip the payment step. We should try to do the same thing for 100% off course coupons. 

The current flow:

1. Apply coupon

![screen shot 2018-11-09 at 2 11 35 pm](https://user-images.githubusercontent.com/430126/48353570-c36f5300-e65d-11e8-89c3-3d51b00d8555.png)

2. Load dashboard with Enroll/Pay button

![untitled](https://user-images.githubusercontent.com/430126/48353726-25c85380-e65e-11e8-864b-43bb844f282d.png)

3. Click Pay button
4. Load order receipt

![screen shot 2018-11-09 at 2 26 13 pm](https://user-images.githubusercontent.com/430126/48353519-a0dd3a00-e65d-11e8-9d67-e816e1f4a36d.png)

5. Click Continue
6. reload dashboard reflecting payment. 

![untitled 2](https://user-images.githubusercontent.com/430126/48353818-53150180-e65e-11e8-8c46-a548bef2b848.png)

The desired flow (based on 100% off program flow):

1. Apply Coupon

![screen shot 2018-11-09 at 2 11 35 pm](https://user-images.githubusercontent.com/430126/48353570-c36f5300-e65d-11e8-89c3-3d51b00d8555.png)

2. Load dashboard with enroll button
3. Enroll and reload dashboard

![untitled 2](https://user-images.githubusercontent.com/430126/48353818-53150180-e65e-11e8-8c46-a548bef2b848.png)

No Pay button. No order receipt

**Comment by pdpinch** [comment]
I'm not sure if this might be blocked by the #3156 epic.

**Comment by pdpinch** [comment]
Not exactly. 

When the user applies the coupon, we should record a $0 order. No checkout necessary. 

Take a look at how we handle 100% program coupons. The UX and backend should be similar.

**Comment by pdpinch** [comment]
@amir-qayyum-khan I added screenshots to the description. Basically, we want to cut a step a step out of the flow when the user has a 100% off course coupon.

**Comment by amir-qayyum-khan** [comment]
@pdpinch screenshot is not available.

**Comment by pdpinch** [comment]
I think I found all the screenshots. Let me know if you have questions.

**Comment by amir-qayyum-khan** [comment]
so what is the process of apply coupon. Is that always `?coupon={code}` in url? if yes i can call checkout there. Because we need to call checkout to apply coupon.

**Comment by pdpinch** [comment]
Yes, that's it. 

Again, there should be some code that handles this for program coupons already.

**Comment by amir-qayyum-khan** [comment]
command or migration?

**Comment by pdpinch** [comment]
Sorry if I wasn't clear. If the learner applies a 100% off program coupon (as opposed to a course coupon), the learner doesn't get a "Pay" button and they don't have to go through the order page.

**Comment by amir-qayyum-khan** [comment]
what is process of applying a coupon. can you write steps here?

**Comment by pdpinch** [comment]
Amir confirmed with me that the course coupon behaves the same as the program coupon. The order receipt appears in both flows, and is necessary for associating the edx course key with the order. 

This isn't work trying to change.
