### ISSUE TITLE
alert when learners haven't been synced 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4166]
We discovered an issue where learners' memberships in discussion channels weren't being synced to the discussions app. As an admin I'd like to be alerted when this membership sync has been delayed for too long, so we can take action. 

I think an alert on any memberships that haven't been synced after 24 hours would be sufficient notice. The alert could be an exception raised to Sentry, or an email (or something else). 

The task that synchronizes memberships is:
https://github.com/mitodl/micromasters/blob/master/discussions/tasks.py#L90-L102

Most of the work is done here:
https://github.com/mitodl/micromasters/blob/master/discussions/api.py#L323

If the PercolateQueryMembership is stale -- i.e. `needs_update` is True and it was created/modified over 24 hours ago -- I want to get an alert to investigate. In most cases, I'll convince myself that the user is an edge case, and I'll (manually) reset `needs_update` to False.

**Comment by tasawernawaz** [comment]
@pdpinch Let me know when can we discuss this.

**Comment by pdpinch** [comment]
@tasawernawaz I'm going to remove this issue from the current sprint. We'll come back to it later.

**Comment by pdpinch** [comment]
I've decided to address this with a redash query and alert
