### ISSUE TITLE
delete a channel 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4168]
As an admin, I'd like to be able to delete a channel that I've created. 

In the past, we've done this ad hoc by deleting the `Channel` object associated with the channel. Unfortunately this has left thousands of "dangling" `PercolateQueryMemberships` that we attempt to synchronize with the discussions application every few minutes. 

- [ ] Add `is_deleted` columns to `Channel` and  `PercolateQuery` (`default=False`)
- [ ] Add a command that takes a channel name and sets the above fields to `True` and updates all the memberships to `is_member=False, need_update=True`
- [ ] Kicks off a task to remove moderators
- [ ] Update any areas where we query for `Channel` and `PercolateQuery` to filter out deleted ones

### Questions

- Should this remove memberships on the discussions side? (if yes, we may want to instead have a walk to mark the channel as deleted so the updates can still occur)
  - Yes, we need to clean this up too

**Comment by rhysyngsun** [comment]
@pdpinch updated the description to reflect that we usually delete the `Channel` record and added a question that might matter

**Comment by pdpinch** [comment]
I took a look at our [conversation about deleting channels in discussions](https://github.com/mitodl/open-discussions/issues/558) and it looks like we will indeed need to walk the users and remove their memberships. 

@rhysyngsun when you have a moment, can you update the description?

**Comment by rhysyngsun** [comment]
@pdpinch updated and I removed the piece about ES because I don't believe there's anything to do there. The proposed changes above will keep the records in place, but ensure that updates don't continue to happen.
