### ISSUE TITLE
Search: add facet for program certificate

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4175]
As a course team member, it need to be able to filter user profiles by those who have a program certificate. 

For some programs, we can approximate this now with the "# of courses passed" facet. However, for courses with proctored exams, or with electives, this is not reliable. 

At the moment, we only have program certificate data for financial aid programs. Unless and until we get program certificate data from edX, this facet will be limited to financial aid programs.

**Comment by annagav** [comment]
@pdpinch, the "number of courses passed" facet counts CombinedFinalGrades for financial aid courses. CombinedFinalGrade is only created for a passing final grade and a passing exam.

**Comment by pdpinch** [comment]
Oh, I didn't know that! That would be awesome and make this issue moot. 

Let me just double-check with @maxliu but it doesn't make sense to work on this for now.
