### ISSUE TITLE
Bug: Autocomplete + Enter key breaks tabbing behavior in profile form fields

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#419]
To reproduce:

- log in and navigate to the profile edit page
- highlight an autocompleted form field like "Preferred language"
- type a partial value, use the arrow keys to select an autocomplete option, and press Enter
- press Tab

Expected: the next input would be selected as if the Enter key was never pressed
Actual: the MIT Micromasters logo is highlighted and the page scrolls to the top

Looks like hitting Enter loses the active input, and Tab just selects the first tab-able element on the page

**Comment by noisecapella** [comment]
For what it's worth, this is a bug on the AutoComplete component, not necessarily our hacks to it: http://www.material-ui.com/#/components/auto-complete

There may be something we can do to say, when user selects an item, explicitly focus on the text field
