### ISSUE TITLE
How to get users enrolled into courses as verified?

### ISSUE THREAD

**Issue by justinabrahms** [mitodl/micromasters#42]
Based on discovery in #3, we can't support automatic enrollment with verified status.

Error is:

`curl -X POST -d '{"mode": "verified", "course_deta
ils": {"course_id": "course-v1:edX+DemoX+Demo_Course"}, "enrollment_attributes": {"namespace": "credit", "name": "provider_id", "value": "MIT"}}' -H
 "Authorization: Bearer 8ea70875b1449bdc9c0ded364d7173d8606fbe32" -H "Content-Type: application/json" -v http://localhost:8000/api/enrollment/v1/enrollment | python -m json.tool`

```js
{
    "message": "User does not have permission to create enrollment with mode [verified]."
}
```

This makes sense, b/c we'd want to get payment info first. Instead, we'll need to know how to craft that URL for getting verified status, then have some mechanism to re-check that the user has done it. Maybe a "re-check my verified status" button somewhere? Maybe a webhook every time the user updates which courses they're in?

**Comment by pdpinch** [comment]
Can we just update the verified status (and all enrollments, for that matter) when the user opens her dashboard?

**Comment by pdpinch** [comment]
Recommendation from edX is to ask Clinton how to approach this.

**Comment by pwilkins** [comment]
Clinton who?  Do you have an email?

**Comment by pwilkins** [comment]
@cblackburn We want to create a button like the green button in this screenshot:

![screenshot-courses edx org 2016-03-30 17-00-51](https://cloud.githubusercontent.com/assets/145821/14179075/96767a78-f72b-11e5-8752-00d8d01c5eda.png)

What is the API endpoint that returns whether a student is verified?

**Comment by justinabrahms** [comment]
Hey @cblackburn,

We know how to get the students verified status using the enrollments API. What we don't know is how to generate the link to upgrade a user to verified. How do we generate that link? Are the URLs stable and deterministic?

Thanks (cc @pwilkins)

**Comment by pwilkins** [comment]
Clinton's response on Slack edX #General channel:

> @peter-wilkins: Do you want to send users to an upgrade page, similar to https://courses.stage.edx.org/course_modes/choose/course-v1:ASUx+CreditDemo+Demo_Course/?

> If you're using Otto, the link you might see on the dashboard now takes the user straight to checkout: https://ecommerce.stage.edx.org/basket/single-item/?sku=0EF44D5

> You can go through the complete flow at https://stage.edx.org/course/dracula-stoker-berkeleyx-book-club-uc-berkeleyx-colwri3-6x.

**Comment by pwilkins** [comment]
@pdpinch says that the upgrade page is an acceptable solution.

**Comment by pdpinch** [comment]
So the constructed URL is something like EDX_SERVER_URL + `/course_modes/choose/` + course_key
