### ISSUE TITLE
Receiving 400 error when authorising with local instance of edx

### ISSUE THREAD

**Issue by nikhilrayaprolu** [mitodl/micromasters#4205]
![image](https://user-images.githubusercontent.com/15216503/50036620-1ad35b00-0030-11e9-81d8-251d3638d733.png)

It is great that the micromasters site is open-sourced by mitodl, I am receiving the above page with a 400 bad request error as shown below, after integrating micromasters with local instance of edx on docker devstack

![image](https://user-images.githubusercontent.com/15216503/50036673-9f25de00-0030-11e9-9134-95ea02b87f3b.png)

![image](https://user-images.githubusercontent.com/15216503/50036637-2e7ec180-0030-11e9-81db-60e228788bc0.png)

![image](https://user-images.githubusercontent.com/15216503/50036650-51a97100-0030-11e9-92c2-08ffcea45dc3.png)

What could be the reason for this error, Could you please help us in solving this issue.

**Comment by nikhilrayaprolu** [comment]
I had pasted the client secret and id as those are being used only for development purposes.

**Comment by nikhilrayaprolu** [comment]
I just realised that the error is because, there is a redirection to login page that's talking place but the query parameters are not being passed into the next_url

**Comment by nikhilrayaprolu** [comment]
How can this be solved? I couldn't find any location where an authentication check is happening in the stack trace.

**Comment by pdpinch** [comment]
Hi @nikhilrayaprolu. I don't quite understand the flow of what you are trying to do. Can you walk through it?

Are you trying to log in to your local instance of MicroMasters with a local instance of edX?

**Comment by pdpinch** [comment]
One small thing to check, did you check the "skip authorization" checkbox? It's cut off in your screenshot of /admin/oauth2_provider/application/3/

**Comment by pdpinch** [comment]
@nikhilrayaprolu I'm going to close this because I haven't heard any follow up from you. If you are still having trouble, feel free to add some more detail about what you've tried and re-open it.
