### ISSUE TITLE
Learner Record: Share

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4209]
As a learner, I want an explicit method for sharing my record with another university, employer etc. 

We can duplicate edX's method.

### acceptance criteria:
- [ ] add a Share button to the learner record in the top right corner (see [screenshot](https://images.zenhubusercontent.com/56c1e5a26caf56c9d38c8552/d2f4a07f-f7b7-4afd-90ac-283490a63382)
- [ ] When clicked, display a pop-up message with instructions (see [screenshot](https://images.zenhubusercontent.com/56c1e5a26caf56c9d38c8552/42cb8d6b-04ba-443a-a3b1-3cb7ca26c725) for text)
  - [ ] omit the text about "you can also directly send your program record... " 
- [ ] display the shareable URL in a field
- [ ] button for copying the link to a clipboard

**Comment by annagav** [comment]
@pdpinch Could you provide some more details for this?
