### ISSUE TITLE
Learner Record: Send to partner institutions

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4211]
As a learner, I would like to send my learner record to the MicroMasters Pathway partner school that I am applying to. 

As a Pathway partner school, I expect to receive a system-generated email that includes the learner record information. I would prefer to receive an email directly from MIT instead of information that the learner is passing along. 

#### Designs and Mock-ups

Web UI based on edX's current design. I sent screenshots to Anna. 
[Email template](https://goo.gl/maps/RxNQjAbLHCQ2) is below in comments

#### Requirements

- [ ] partner data based on info in [ZenDesk #26552](https://odl.zendesk.com/agent/tickets/26552)

**Comment by pdpinch** [comment]
Still trying to track down the email template. In the meantime, we have seed data for 8 pathway partners. The basic model is something like `partner.name` and `partner.email`. We can manage the partners through the django admin.

**Comment by pdpinch** [comment]
Here is edX's email template: https://github.com/edx/credentials/blob/master/credentials/templates/records/edx_ace/programcreditrequest/email/body.txt

In the interests of simplicity, the body can reduced to one case:

```
{{ user_full_name }} has sent their program record for {{ program_name }}

{{ user_full_name }} would like to apply for credit in the {{ pathway_name }}.

Please view {{ user_full_name }}’s public program record to determine their credit eligibility status.

{% trans "View Program Record" %}: {{ record_link }}

{% blocktrans %}The {{ platform_name }} Team{% endblocktrans %}
```

**Comment by annagav** [comment]
@pdpinch where can I find the partners data?

**Comment by pdpinch** [comment]
It's on this ticket: https://odl.zendesk.com/agent/tickets/26552

**Comment by annagav** [comment]
@pdpinch Do you have a link to how this feature looks in edx?
