### ISSUE TITLE
Learner Record: display "Verified attempts" 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4212]

**Comment by annagav** [comment]
@pdpinch should we ignore exam attempts and only show course runs attempts?

**Comment by pdpinch** [comment]
To the contrary, I think we should display exam attempts, counted by the number of proctored exam grades.

**Comment by pdpinch** [comment]
@annagav was this closed by #4204?

**Comment by annagav** [comment]
Yes, for verified attempts we are showing the number of exam attempts.
