### ISSUE TITLE
Learner Record: link from dashboard to learner record

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4213]

**Comment by annagav** [comment]
This is what it looks like now:
![screen shot 2019-01-16 at 11 52 49 am](https://user-images.githubusercontent.com/7574259/51264798-4a55ea00-1985-11e9-8d22-80a6ab069450.png)

**Comment by pdpinch** [comment]
Looks done to me (recognizing that it's behind a feature flag in production)
