### ISSUE TITLE
BI program dashboard

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4215]
As a member of the MicroMasters management team, I need a one-stop source of reliable, high-level data about each program. 

The numbers could be summarized in the following format:

| program | enrollment | unique learners | # of verified | # of course certificate | # of program credential | 
| -------- | -------- | -------- | -------- | -------- | -------- | 
| SCM |   |   |   |   |  
| DEDP |   |   |   |   |  
| PoM |   |   |   |   |  
| SDS |   |   |   |   |  
| Total |   |   |   |   |  

Much of this data is only available through the edX data in Google Big query. We will need to set up a data pipeline to extract and aggregate it. 

### related issues
- BI regional dashboard

**Comment by pdpinch** [comment]
@maxliu do you think we can close this now?

**Comment by maxliu** [comment]
we might need a test query for this one, it will be a different issue.
