### ISSUE TITLE
MicroMasters® trademark updates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4221]
edX is asking all their partners to update their electronic communication to better protect the MicroMasters trademark. The MITx MicroMasters team has asked us to make the following changes to the portal:

<img width="919" alt="mm site_homepage_screenshot 1" src="https://user-images.githubusercontent.com/430126/50924299-31958380-141d-11e9-8a99-ab56e2f396b0.png">
<img width="860" alt="mm site_homepage_screenshot 2" src="https://user-images.githubusercontent.com/430126/50924300-31958380-141d-11e9-9988-896f30272445.png">
<img width="368" alt="mm site_homepage_screenshot 3" src="https://user-images.githubusercontent.com/430126/50924301-31958380-141d-11e9-9499-20c11e9395ed.png">
<img width="924" alt="mm site_homepage_screenshot 4" src="https://user-images.githubusercontent.com/430126/50924302-31958380-141d-11e9-90ec-b9550e6893e7.png">
<img width="922" alt="mm site_homepage_screenshot 5" src="https://user-images.githubusercontent.com/430126/50924303-31958380-141d-11e9-81d7-f38852582a4b.png">

In general, the requirements is that the first mention of "MicroMasters" on the page is followed by a ® mark, and that MicroMasters never be used standalone, but only to modify a noun, like Program or Courses. 

We are getting in touch with the various course teams about the CMS content.

**Comment by pdpinch** [comment]
Most of these are on the home page, but I think one of them is in the database (on the program model?) and the last one is in a CMS template.

**Comment by pdpinch** [comment]
This is blocked until we get another round of reviews on the text changes.

**Comment by pdpinch** [comment]
@annagav this is unblocked now, please work on it as soon as possible

**Comment by annagav** [comment]
The program description should be changed in cms.

**Comment by pdpinch** [comment]
thanks for the reminder. It's actually in the database, but not the CMS. 

Done! 

<img width="40%" align="left" alt="mm site_homepage_screenshot 3" src="https://user-images.githubusercontent.com/430126/50924301-31958380-141d-11e9-9499-20c11e9395ed.png">

=> <img width="40%" align="right" alt="screen shot 2019-01-09 at 4 50 00 pm" src="https://user-images.githubusercontent.com/430126/50930695-a329fd80-142e-11e9-8a5c-9eefd5ec9d4c.png">
