### ISSUE TITLE
Fix flaky exam test

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#4233]
We have run into an intermittent test failure on Travis. I _think_ the test case is `dashboard.api.test_is_exam_schedulable` (Travis build have since been fixed and the failing job log was lost). If/when this happens again, this issue should be updated with the right test case and the error output

**Comment by pdpinch** [comment]
I'm not sure if this is still an issue.

**Comment by umarmughal824** [comment]
@pdpinch @gsidebo I have run it multiple times locally but it did not fail even once.

**Comment by umarmughal824** [comment]
@pdpinch I have tested it today as well so all the tests are passing so better to close it.
