### ISSUE TITLE
Allow links in CMS tables

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4235]
In #4227 we added support for tables on Program Tab pages in the CMS. However, we overlooked one requirement -- CMS users (course staff) need to be able to add links to the table. 

Our primary use case for the table is for providing learners with a list of universities that offer a masters program to micromasters credential holders. So we need to link learners to university web sites.

**Comment by pdpinch** [comment]
Looking at the Wagtail and handsontable docs, it looks like there are (at least) two options:

1. Allow HTML in the table: https://handsontable.com/docs/6.2.2/Options.html#allowHtml
2. Use a custom editor

Allowing HTML is probably easier to implement, but comes with some risk of breaking the page, or worse. 

handsontable has some examples of custom editors, but none do what we need: adding a link (or, even make the whole cell a link).

**Comment by pdpinch** [comment]
@tasawernawaz can you take a look at this on Monday? We overlooked a key feature of the CMS table.

**Comment by tasawernawaz** [comment]
@pdpinch Other then links user can simple add text.

**This is how you can edit/add link**

![screen shot 2019-01-22 at 2 39 42 pm](https://user-images.githubusercontent.com/4245618/51526165-93111580-1e53-11e9-886e-7135ce152cc8.png)

**This is how it render**

![screen shot 2019-01-22 at 2 36 35 pm](https://user-images.githubusercontent.com/4245618/51526173-97d5c980-1e53-11e9-8d3f-84bd9ff6d5e1.png)
