### ISSUE TITLE
Program Pages: make font size of table text same as default text size

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4266]
The font in tables is too large, in particular at mobile widths. 

Can we just remove this line from the CSS, and let it inherit the default font size?

https://github.com/mitodl/micromasters/blob/6b1ea17e1ddc7ae28fc8510c5da05e5af64918b9/static/scss/program-page.scss#L313

**Comment by pdpinch** [comment]
There may be some more style changes coming, but this one seems very simple. @tasawernawaz

**Comment by tasawernawaz** [comment]
@pdpinch I have removed the CSS. Let me know if there are any other changes required.
