### ISSUE TITLE
congratulations letter styling updates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4278]
- Instead of two logos ([MIT](https://d3o95baofem9lo.cloudfront.net/static/images/mitx_logo.png) and [program](https://d3o95baofem9lo.cloudfront.net/images/mit_center_for_trans_and_logistics_logo.max-200x100.png)) there should be one logo, controlled through the CMS. This allows the program to use a custom-colored version of the MIT logo
- tweak the print stylesheet so the letter fits on one page (one user is reporting the last line is on a second page)

**Comment by pdpinch** [comment]
@tasawernawaz can you fix at least the logo issue on Monday? When I sent you the two logos in one file, it was my intention that we'd leave them as one file, uploaded through the CMS.

**Comment by pdpinch** [comment]
![CTL logo blue-2 lines-v2](https://user-images.githubusercontent.com/430126/54073286-58243f00-4253-11e9-88fd-d292ebe44a95.png)

**Comment by tasawernawaz** [comment]
@tasawernawaz Into this.

**Comment by tasawernawaz** [comment]
@pdpinch Its my bad that I miss interpret this, I have fixed logo issue. Looking into print issue.

On side note, Do we really need a footer in program letter ?

**Comment by pdpinch** [comment]
Turns out the print issue was user error -- their printer was set to landscape. 

As for the footer, we can leave it as is for now. I don't think we need it, but I don't think it hurts either.
