### ISSUE TITLE
Add Kosovo as an independent country to profile

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4283]
ZenDesk ticket at  https://odl.zendesk.com/agent/tickets/26911

blog post on ISO use of `XK`: https://geonames.wordpress.com/2010/03/08/xk-country-code-for-kosovo/

We'll need to fork https://github.com/olahol/iso-3166-2.js (again), but they do seem to accept PRs.

**Comment by pdpinch** [comment]
We need to update micromasters to user our fork of iso-3166-2.js, https://github.com/mitodl/iso-3166-2.js/commit/36ef6437693efed2e5261a5fab5a9ceaf9650363

Also, @tasawernawaz you should open up a PR upstream to iso-3166-2.js

**Comment by pdpinch** [comment]
@tasawernawaz Can you add a link here to the upstream PR?

**Comment by tasawernawaz** [comment]
@pdpinch Link to upstream PR: https://github.com/olahol/iso-3166-2.js/pull/27
