### ISSUE TITLE
Error: Non-Error exception captured with keys: address, birth_country, city…

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#4304]
You can reproduce this error simply by trying to register as a new user, it errors on the /profile/personal page, although you appear to be able to still complete registration successfully.

https://sentry.io/organizations/mit-office-of-digital-learning/issues/994163942/?project=104497&referrer=github_plugin

```
Error: Non-Error exception captured with keys: address, birth_country, city…
  at _promiseRejectionHandler ([native code])

Non-Error exception captured with keys: address, birth_country, city…
```

**Comment by pdpinch** [comment]
Sentry issue: [MICROMASTERS-2RB](https://sentry.io/organizations/mit-office-of-digital-learning/issues/1034206520/?referrer=github_plugin)

**Comment by pdpinch** [comment]
Sentry issue: [MICROMASTERS-2RC](https://sentry.io/organizations/mit-office-of-digital-learning/issues/1034351142/?referrer=github_plugin)

**Comment by pdpinch** [comment]
Sentry issue: [MICROMASTERS-2RD](https://sentry.io/organizations/mit-office-of-digital-learning/issues/1034586228/?referrer=github_plugin)

**Comment by pdpinch** [comment]
Sentry issue: [MICROMASTERS-2RE](https://sentry.io/organizations/mit-office-of-digital-learning/issues/1034586375/?referrer=github_plugin)

**Comment by pdpinch** [comment]
Sentry issue: [MICROMASTERS-2RF](https://sentry.io/organizations/mit-office-of-digital-learning/issues/1034646385/?referrer=github_plugin)

**Comment by pdpinch** [comment]
Sentry issue: [MICROMASTERS-2RH](https://sentry.io/organizations/mit-office-of-digital-learning/issues/1035023220/?referrer=github_plugin)

**Comment by pdpinch** [comment]
Sentry issue: [MICROMASTERS-2RG](https://sentry.io/organizations/mit-office-of-digital-learning/issues/1035021444/?referrer=github_plugin)
