### ISSUE TITLE
Create endpoint to query for course run edx_course_key values

### ISSUE THREAD

**Issue by sesterki** [mitodl/micromasters#4311]
This endpoint will support our work on mitodl/open-discussions where we will be marking which courses are part of MicroMasters. We will need the list of course keys and the associated program title to store as metadata in the open-discussions course_catalog.

More information can be found here:
https://github.com/mitodl/open-discussions/issues/1981

**Comment by Ferdi** [comment]
@sesterki thanks, can you describe the context on how this is going to be used ?
