### ISSUE TITLE
add a search by email to the Cybersource report

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4338]
As a member of the customer service team, I'd like to be able to find a customer's order number, so I can give it to the finance team in order to execute a refund. 

#### Acceptance Criteria:

- [x] give appropriate access to the "MicroMasters monthly financial data" report to the customer support team
- [x] modify the report so the id column display the expected value in Cybersource, i.e. an id of "1234" becomes "MM-prod-1234" 
- [x] add a email search field to the report

**Comment by maxliu** [comment]
@pdpinch do you provide a user list of the customer support team who need access to this report ?

**Comment by maxliu** [comment]
related zendesk ticket  https://odl.zendesk.com/agent/tickets/30648

**Comment by maxliu** [comment]
the report with search box is available on https://bi.odl.mit.edu/dashboard/micromasters_1 and https://bi.odl.mit.edu/queries/8#1053

**Comment by maxliu** [comment]
@pdpinch for the "id" in the requirements, is it order id?

**Comment by pdpinch** [comment]
Yes. Same as MIT xPRO.
