### ISSUE TITLE
Progress shows wrong total number of courses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4365]
I'm testing the DEDP program on RC, and I think I've set up the elective properly. However, when I view my profile as an instructor, the total number of courses in the progress card shows "2/4" instead of the expected "3/5". (I passed the online parts of 2 core courses and 1 elective).

![image](https://user-images.githubusercontent.com/430126/62051747-feacb480-b1e1-11e9-98e5-bcf916cfcdad.png)

I haven't tested my dashboard view yet because I have a test program certificate obscuring it.

**Comment by annagav** [comment]
@pdpinch The number of required courses is set to 4 on the program: 
![Screen Shot 2019-07-29 at 9 29 01 AM](https://user-images.githubusercontent.com/7574259/62052418-69122480-b1e3-11e9-998a-2defa75b0439.png)

**Comment by annagav** [comment]
I am not sure about the passing of the courses because Microeconomics says in progress and doesn't have a final grade, and the elective course says that you missed deadline. I could check dashboard api response if I have your learner's username.

**Comment by pdpinch** [comment]
`pdpinch`

But based on what you said, I’m guessing it’s because one of the courses is “in progress”, presumably because grades haven’t been frozen.
