### ISSUE TITLE
Can't upgrade `axios` as a searchkit dependency

### ISSUE THREAD

**Issue by annagav** [mitodl/micromasters#4383]
Searchkit needs to update this [dependency](https://github.com/searchkit/searchkit/blob/staging/yarn.lock#L1084).  To get rid of the security alert need to `Upgrade axios to version 0.18.1 or later`.

**Comment by pdpinch** [comment]
It looks like searchkit has gotten a lot of attention in the past year, and axios may not longer be a dependency? In any case, we should look into updating it.
