### ISSUE TITLE
Populate Course.edx_key in all environments

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#4395]
The changes in #4380 introduced a `edx_key` field on `Course` in order to allow discussions to join course records from MM with course records from mitx. The primary purpose of this is to assign a course from mitx to a program in MM.

- [x] `edx_key` set in CI
- [x] `edx_key` set in RC
- [x] `edx_key` set in Prod

**Comment by pdpinch** [comment]
@rhysyngsun I think this is done now for MicroMasters RC. Is there a way we can sanity check it and see if discussions-rc can ingest it?

**Comment by rhysyngsun** [comment]
@pdpinch looks good on RC
