### ISSUE TITLE
Add program price and program dates to the catalog API

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4406]
As a catalog API consumer, like the MIT Open site, I'd like to know the MicroMasters program price, enrollment start date, start date and end date of each program.

### Acceptance Criteria:

- [ ] Add a price field to the API response, based on the product of `program.price` and `program.num_required_courses`
- [ ] Add an start_date field to the API response, using the next start date of the first course in the program
- [ ] Add an end_date field  to the API response, using the next end date of the last course in the program. 
- [ ] Add an enrollment_start date field to the API response, using the next enrollment_start date of the first course in in the program.

### Related issues 

- Similar to https://github.com/mitodl/mitxpro/issues/1129
- API response will be consumed by (issue to be created in open-discussions)

**Comment by noisecapella** [comment]
Is the "next end date" the end date for the latest run which is not expired for that course?
