### ISSUE TITLE
enable commendation letter for FA courses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4421]
The DEDP course team would like to offer commendation letters to learners, similar to what we have implemented for SCM.

**Comment by pdpinch** [comment]
@tasawernawaz I think you did the original implementation for this feature. At that time, we didn't apply it to FA programs, like DEDP. Are you aware of any blockers?

**Comment by tasawernawaz** [comment]
@pdpinch If I can remember correctly, I think FA programs get certificates thats why we decided that commendation letter would be only for non-FA programs.

**Comment by pdpinch** [comment]
@annagav I think you said you were going to take this, so I'm assigning it to you.

**Comment by annagav** [comment]
@pdpinch @abdul Do you have some preference for styling this?
![Screen Shot 2019-11-14 at 3 18 51 PM](https://user-images.githubusercontent.com/7574259/68893026-46ecd580-06f2-11ea-8aca-1a60a7e7ce7d.png)
