### ISSUE TITLE
Alumni benefits page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4429]
As a learner, I'd like to have a page that explains all the benefits from the MIT alumni association for people who earn a program certificate. 

As a marketing team member, I'd like to have a single URL that I can use in marketing to all potential users with a description of the benefit.

#### Designs and Mockups

- [x] Design is TBD

#### Acceptance Criteria:

- [x] New page in CMS, child of the home page and editable by marketing and the MicroMasters team
- [x] link to Alumni association

**Comment by pdpinch** [comment]
We currently have a tab on each program page with benefit information ([example](https://micromasters.mit.edu/scm/benefits/)), but it makes sense to have a single, generic page because the benefits apply to all programs. 

Copy is at https://docs.google.com/document/d/1xYmIWqdISNZ74DNfS8ndLelHnsFQeYmBOlxBLP4Swfs/edit?usp=sharing

**Comment by annagav** [comment]
Two questions:

1. Did we decide that we don't need three tabs? 

2. Where should we place the link to the benefits page?

**Comment by pdpinch** [comment]
1 That's correct. No tabs (because each one has the same content)

2. The link goes on the home page. It's spec'ed in the google doc in the section about the homage page: https://docs.google.com/document/d/1xYmIWqdISNZ74DNfS8ndLelHnsFQeYmBOlxBLP4Swfs/edit?disco=AAAADhxlL4I  

@abdulkdawson I can't remember -- did you say we should add benefits to the nav as well?

**Comment by annagav** [comment]
Oh, I see now, the link is in the new modified text. So I'll add the link together with the rest of home page changes.
