### ISSUE TITLE
Update Field of Study in education profile to use JSON data

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#443]
Currently this field is a free text field. We would like to convert it to a type-ahead field. As the user types, we will look up the field of study, and populate a dynamic drop-down menu with the results. 

For the future (not this story), we would like to allow the user to enter their own text (i.e. not matching anything returned from the API). 

We will store the CIP code in the profile, similar to what we do with country codes.

**Comment by gsidebo** [comment]
fields of study data source: https://nces.ed.gov/ipeds/cipcode/resources.aspx?y=55
