### ISSUE TITLE
Acknowledge admin and course team on program page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4430]
As a potential micromasters learner, I'd like to understand more about who teachers the courses and who oversees the program. 

As a member of the course team, I'd like to have my contribution to the courses acknowledged appropriately. 

As a member of the course team, I need to be able to update the names, titles, images and bios of all members at any time. 

#### Designs and Mockups

https://invis.io/Y8UKRZZSC6D#/391397475_MicroMasters_Team_Page_Copy (white background)

Sample copy at https://drive.google.com/file/d/1hYhbeNmzSVS-Hd3zBNzhcsRd2uefIlcJ/view

#### Acceptance Criteria:

- [x] Create a new tab specifically for the Course team, which probably requires a new wagtail page template
  - [x] The course team template should always be second
- [x] the course team page has four sections: Instructors, Administrative Team, Course Contributors and Current TAs. These section labels should have defaults but be able to be overridden. 
- [x] for each photo, there is a hover state that displays the person's bio
- [x] nice to have: ability to upload images from the page editor, instead of uploading them in the image section
- ~~add a link to this "course team" page below the existing faculty carousel (conditional on whether the page exists)~~

#### Questions

- **Q:** The current Instructor carousel is currently included in _every_ tab in the Program page. Should we reconsider this?
- **A:** I discussed with stakeholders, and we decided to keep it as is. 
- **Q:** What to do with bios?
- **A:** Bios will display on hover

**Comment by tasawernawaz** [comment]
@pdpinch Only this issue is not been picked from [MM enhancements](https://docs.google.com/document/d/1xQ6TvqDY7DSx4jvfzd6X_9MudYqAE3rkHbjSwGXNSwE/edit), do we expect this to be done in the current sprint.

**Comment by pdpinch** [comment]
I’d like it to be done this sprint, but we’re still working on the design.

**Comment by tasawernawaz** [comment]
@pdpinch Can I get answers to the questions in the description of the issue.

**Comment by pdpinch** [comment]
@tasawernawaz the design is still under review, but you can take a look at it now to get an idea of what the scope will be. It's a pretty significant change.

**Comment by tasawernawaz** [comment]
@pdpinch I had requested yesterday to inspect the design. That would help me to get the exact CSS styles.

Can I get an idea about what actual data/fields are required/optional in Instructors, Administrative Team, Course Contributors and Current TAs?

**Comment by tasawernawaz** [comment]
@pdpinch 
> Can I get an idea about what actual data/fields are required/optional in Instructors, Administrative Team, Course Contributors and Current TAs?

I am still waiting for your response on this, also could you confirm that the given design is approved ?

**Comment by pdpinch** [comment]
Each section should be optional. Ideally, the title of each section should be editable as well, with a default value as it appears in the design. 

Within each section, for each person, a name, an image and a "bio" are required. 

The approved design is at https://invis.io/Y8UKRZZSC6D#/391397475_MicroMasters_Team_Page_Copy -- it's the same as the other one, but with a white background.

**Comment by tasawernawaz** [comment]
@pdpinch this is how it will look like in CMS, I am moving to work on the CSS now. Let me know if you think there are any amendments needed.
![screencapture-localhost-8079-cms-pages-9-edit-2019-11-06-20_11_30](https://user-images.githubusercontent.com/4245618/68310402-c4e92500-00d1-11ea-9e05-d8ff7e9e105e.png)

**Comment by pdpinch** [comment]
@tasawernawaz I added another acceptance criteria to the description:

> add a link to this "course team" page below the existing faculty carousel (conditional on whether the page exists)

**Comment by tasawernawaz** [comment]
> @tasawernawaz I added another acceptance criteria to the description:
> 
> > add a link to this "course team" page below the existing faculty carousel (conditional on whether the page exists)

Thanks, I will update the code.

**Comment by pdpinch** [comment]
The CMS looks okay, but is there a way to change the order of images/bios?

**Comment by tasawernawaz** [comment]
> The CMS looks okay, but is there a way to change the order of images/bios?

yes they are.
