### ISSUE TITLE
Replace fax number with link to DocuSign

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4431]
As a learner, I would like to upload my financial documents, instead of faxing them. 

As a member of the course team, I would prefer that learner submit their documents online than any other method. 

#### Design

![Docusign on dashboard](https://user-images.githubusercontent.com/430126/67160545-08950e00-f320-11e9-89b9-040fe8d15726.png)

#### Acceptance Criteria

- [ ] Replace the text on the dashboard with 
> Before you can pay, you need to verify your income. Please visit the secure website [DocuSign](https://na2.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=4a74536d-1629-4709-b8e9-f173a51cf501&env=na2&v=2) to upload an English-translated and notarized income tax or income statement document. You can also send documents by mail. DO NOT SEND BY EMAIL.
- [ ] Remove the fax number section
- [ ] Move the mail section to the right 
- [ ] Add a "Upload to DocuSign" section with the full link to DocuSign

**Comment by tasawernawaz** [comment]
@pdpinch Could you please list down the steps to reproduce, I mean how I can test this change.

**Comment by pdpinch** [comment]
I think this will do it:

1. Enroll in a FA program
2. View the dashboard and click "Pay Now" 
3. Enter an income and country. The income has to be low enough for the country to require documentation. 

You should now have the message card on your dashboard with instructions about how to send in your documentation. 

@annagav can confirm. She may also know if there are selenium tests that verify this state.
