### ISSUE TITLE
Fix promise rejection with non-error exception

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#4435]
We're seeing an error `Non-Error exception captured with keys: detail, errorStatusCode`: https://sentry.io/organizations/mit-office-of-digital-learning/issues/991823545/?project=104497

It's probably being caused by this line rejecting a promise with a non-Error object:
https://github.com/mitodl/micromasters/blob/5d07dac5715ac11cc261727c75d2035709601307/static/js/actions/coupons.js#L32

The fix is to replace this with `Promise.reject(new Error("Unable to attach coupon"))` or something like that.

**Comment by HamzaIbnFarooq** [comment]
@rhysyngsun @pdpinch, the sentry issue link is giving a 404, can you please check if I have the appropriate access rights?

**Comment by HamzaIbnFarooq** [comment]
@pdpinch, Although I have created a PR (https://github.com/mitodl/micromasters/pull/4690) with the proposed fix, I am unable to produce this scenario locally. Is it possible that I get a proper use-case to test this issue?

**Comment by pdpinch** [comment]
Sorry, I don't know how to reproduce this myself. But we do have more sentry issues with similar patterns:

https://sentry.io/organizations/mit-office-of-digital-learning/issues/1607515510/

https://sentry.io/organizations/mit-office-of-digital-learning/issues/1604754837/

https://sentry.io/organizations/mit-office-of-digital-learning/issues/1633986782/
