### ISSUE TITLE
Update Program Letter template

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4479]
As a course team member, I'd like to have a more flexible template for program letters. 

#### Designs and Mockups

Exampe of the current letter (SCM): https://micromasters.mit.edu/letter/program/ab1a5c1d-4b23-4a94-9e04-dbbf0e5a3694

Desired letter (SDS): [SDS_letter_accomplishment_12.9.2019.pdf](https://github.com/mitodl/micromasters/files/3946022/SDS_letter_accomplishment_12.9.2019.pdf)

#### Acceptance Criteria:

- [ ] Allow for a wider logo graphic (but keep right alignment). This should accomodate the IDSS logo and address shown in the "desired letter" above
- [ ] Move the closing "Cordially Yours" out of the template and into the letter content. This will allow the SDS team to use a different closing than SCM. 
  - [ ] when this commit is deployed, we will plan to make any necessary updates to the SCM-specific data
- [ ] Review the spacing and image requirements for the signatures, so that three will fit in a vertical list, as displayed in the "desired letter" above. 
- [ ] would be nice: replace the current template footer (the name of the program) with another CMS image, similar to the header. 
- [ ] would be nice: the current CMS form has a required field for institution, which doesn't appear in the letter. Can it be removed, or at least made not required? 
- [ ] any changes need to avoid regressions in the SCM letter, since that is already in production.

**Comment by annagav** [comment]
@pdpinch, could you provide an example footer for the letter? Would you like this image to be optional in CMS?

**Comment by pdpinch** [comment]
Here are two examples with a footer. It should be optional so we don't have to make changes to the existing SCM letter. 

[SDS_letter_accomplishment_12.9.2019.pdf](https://github.com/mitodl/micromasters/files/3952292/SDS_letter_accomplishment_12.9.2019.pdf)

[DEDP Credential Letter_updated by LZ_9.20.2019.docx](https://github.com/mitodl/micromasters/files/3952300/DEDP.Credential.Letter_updated.by.LZ_9.20.2019.docx)
