### ISSUE TITLE
(Bug) IntegrationTestHelper/renderComponent swallows all errors

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#448]
To reproduce:

1. Open static/js/containers/ProfilePage_test.js
1. Immediately after any line that calls `renderComponent`, add the following line: `assert(false);`. Example:
    
        renderComponent("/profile/privacy").then(([, div]) => {
          assert(false);
          //...
1. Run the js tests for this file (`docker-compose run watch npm run-script singleTest static/js/containers/ProfilePage_test.js`)

**Expected)** The test indicates that your `assert(false);` failed with an AssertionError and a line number
**Actual)** An unhelpful error like the following is shown:

```javascript
1) ProfilePage marks email_optin and filled_out when saving this page:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
```

This may be a bug with static/js/util/integration_test_helper.js or the redux-asserts library. As things stand, it is very frustrating to debug the tests in this file and perhaps others.

**Comment by noisecapella** [comment]
I think this is what we want: https://nodejs.org/api/process.html#process_event_unhandledrejection
