### ISSUE TITLE
Add page titles

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#449]
All of the Profile pages have the title of "MIT Micromasters". As a result, a user's browser history (as revealed by right-clicking the back button) might look something like this:

![ss 2016-05-31 at 11 50 03 am](https://cloud.githubusercontent.com/assets/14932219/15726256/db55e494-281d-11e6-92d3-2b340f2894cb.png)

For this and other reasons, it would be wise to add some helpful titles to the Profile pages.

**Comment by pdpinch** [comment]
First draft of page titles

| Path                   | Title                                                                        |   |
|------------------------|------------------------------------------------------------------------------|---|
| /                      | MIT MicroMasters:  An online MIT credential available to anyone in the world |   |
| /:program_slug         | [Program Title] \| MIT MicroMasers                                            |   |
| /terms_of_service/     | Terms of Service \| MIT MicroMasters                                          |   |
| /profile/personal/     | Personal Profile \| MIT MicroMasters                                          |   |
| /profile/education/    | Education Profile \| MIT MicroMasters                                         |   |
| /profile/professional/ | Professional Profile \| MIT MicroMasters                                      |   |
| /profile/privacy/      | Privacy \| MIT MicroMasters                                                   |   |
| /dashboard/            | Learner Dashboard \| MIT MicroMasters                                         |   |
| /users/:username       | [Preferred Name] [Last Name] \| MIT MicroMasters                              |   |
|                        |                                                                              |   |

**Comment by gsidebo** [comment]
@pdpinch i imagine we want these with `'s` at the end?

**Comment by noisecapella** [comment]
We're now doing just `MicroMasters` without the apostrophe: #557

**Comment by roberthouse54** [comment]
First draft of page titles

| Path | Title |  |
| --- | --- | --- |
| / | MIT MicroMasters:  An online MIT credential available to anyone in the world |  |
| /:program_slug | [Program Title] | MIT MicroMasers |  |
| /terms_of_service/ | Terms of Service | MIT MicroMasters |  |
| /profile/personal/ | Personal Profile | MIT MicroMasters |  |
| /profile/education/ | Education Profile | MIT MicroMasters |  |
| /profile/professional/ | Professional Profile | MIT MicroMasters |  |
| /profile/privacy/ | Privacy | MIT MicroMasters |  |
| /dashboard/ | Dashboard | MIT MicroMasters |  |
| /users/:username | [First Name] [Last Name] | MIT MicroMasters |  |
|  |  |  |
