### ISSUE TITLE
Application error when viewing admin

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4493]
### Steps to Reproduce

Go to /finalgrade/136865/change/ in production

### Expected Behavior

admin form loads

### Actual Behavior

Heroku application error. I have not been able to find an error in Sentry. 

### Stacktrace

tbd

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/430126/71983661-47d34c80-31f5-11ea-920f-a038471b7e3b.png)

**Comment by annagav** [comment]
This is a request timeout error. This doesn't happen on RC.
```2020-01-21T18:32:26.760885+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/admin/grades/finalgrade/9274/change/" host=micromasters.mit.edu request_id=6c8abde1-61f8-4622-937e-d6fc04450ddb fwd="18.21.175.70" dyno=web.2 connect=0ms service=30001ms status=503 bytes=0 protocol=https```
