### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#45]
- [X] Create project in ODL GA account and -ci and -release profiles. 
        CI tag is UA-5145472-14
        Release tag (already in use) is UA-5145472-10
- [x] Invite all the necessary people to the GA account
- [x] add UA key to config
- [x] ? React coding?

**Comment by jamiefolsom** [comment]
@pdpinch I can take on the react coding. Separate issue? Same issue?

**Comment by pdpinch** [comment]
Same issue is fine, since getting the UA codes doesn't take much effort.

**Comment by jamiefolsom** [comment]
ok, thanks.
