### ISSUE TITLE
Switch SENTRY_DSN to the non-deprecated version

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#4526]
#### Summary

We're currently using the deprecated version of sentry DSN keys (looks like a url w/ `username:password` in it). The new version basically drops the password since this value isn't a secret.

- `SENTRY_DSN` - Switch this value to the regular DSN client key in sentry

#### Applicable Environments

- [x] Apply configuration to CI
- [x] Apply configuration to RC
- [x] Apply configuration to Production

┆Issue is synchronized with this [Trello card](https://trello.com/c/NK4vq6uK) by [Unito](https://www.unito.io/learn-more)

**Comment by shaidar** [comment]
The change has been made to all envs.

**Comment by rhysyngsun** [comment]
Verified this is looking good so closing it.
