### ISSUE TITLE
Fix selenium tests running locally

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#4536]
When working on #4533 I fixed the selenium tests so that they continue to run on travis, but I haven't fixed it running locally. We rarely run selenium tests locally so in the interest of getting that PR ready for review I'm putting the work of fixing selenium in the dev environment in this issue.

**Comment by umarmughal824** [comment]
@pdpinch the selenium test is not a part of Github CI actions, do we need to add it in the build?

**Comment by noisecapella** [comment]
@umarmughal824 yes, I will create an issue for that
