### ISSUE TITLE
Warnings related to Wagtail upgrade

### ISSUE THREAD

**Issue by annagav** [mitodl/micromasters#4563]
<img width="717" alt="Screen Shot 2020-03-20 at 10 48 06 AM" src="https://user-images.githubusercontent.com/7574259/77175849-9d4f9380-6a99-11ea-9160-e2bf2968ac3d.png">

┆Attachments: <a href="https://github.com/mitodl/micromasters/pull/4590">#4590 Warnings related to wagtail upgrade - #4563</a>

**Comment by pdpinch** [comment]
fixed by #4590
