### ISSUE TITLE
off-site links should open in a new window/tab

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#457]
As a user, I don't want to lose my place on the site. Off-site links should open in a new window. 

- [ ] footer: edX link
- [ ] footer: ODL link
- [ ] footer: Give to MIT button 
- [ ] home page: MITx link to https://www.edx.org/school/mitx

**Comment by aliceriot** [comment]
footer partial:
- [ ] footer: edX link
- [ ] footer: ODL link
- [ ] footer: Give to MIT button 
- [ ] home page: MITx link to https://www.edx.org/school/mitx

footer react component:
- [ ] footer: edX link
- [ ] footer: ODL link
- [ ] footer: Give to MIT button 
- [ ] home page: MITx link to https://www.edx.org/school/mitx
