### ISSUE TITLE
Fix environment variables so we can enable uWSGI strict mode

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#4597]
We have some environment variables starting with `UWSGI_` which are treated by uWSGI as settings. If there is no corresponding valid uWSGI setting, an error will occur on strict mode which causes uWSGI to exit.

I think we can solve this in a couple ways, for example with `UWSGI_THREAD_COUNT`:
 - Change `UWSGI_THREAD_COUNT` to `UWSGI_THREADS`, and only set the `if-not-env` case where the variable isn't already set.
 - Change `UWSGI_THREAD_COUNT` to `MICROMASTERS_THREAD_COUNT` or another non-conflicting environment variable, and set uWSGI similarly

**Comment by markbreedlove** [comment]
I recently made this change in `cookiecutter-djangoapp`: https://github.com/mitodl/cookiecutter-djangoapp/pull/167

My goal there was to preserve some kind of prefix, but not have uWSGI assign any configuration directives based on the variables.

**Comment by markbreedlove** [comment]
I do like the changes in the PRs referenced above. I would be happy to change my approach in `cookiecutter-djangoapp` to match that of the PRs.

**Comment by noisecapella** [comment]
@markbreedlove Ok, I'll merge these PRs and make a similar change for the cookiecutter
