### ISSUE TITLE
Use pdb++

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#460]
One of the pycon speakers mentioned this as being preferable to pdb, so we should try it out and update requirements if we like it

**Comment by gsidebo** [comment]
never used pdb, but i have used ipdb. have we ever looked at that? did the speakers compare pdb++ with ipdb at all?

**Comment by giocalitri** [comment]
I use pdn++ (pdbpp in pypi) a lot, but it does not work with python 3.4 (at least for me): another reason to  switch to 3.5
