### ISSUE TITLE
Use mypy for type checking

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#461]
Since we are using Python 3 we should try out mypy to enforce types in our project. 

Note: this is mypy-lang in pip, not just mypy which is a different package

**Comment by giocalitri** [comment]
Well, we should start to type the functions and then we can use mypy.

Anyway, I am still a bit skeptical about the syntax for type annotation.

**Comment by noisecapella** [comment]
There are some problems with this compared to our work with flow:
 - There's not the notion of typing dictionaries as different types, other than defining the type of the keys and values. 
 - Only functions with type annotations are typed. The flag `--check-untyped-defs` doesn't do a complete job: https://github.com/python/mypy/issues/1802
 - Empty dictionaries are not handled well: https://github.com/python/mypy/issues/1786
 - Django is also not part of the typeshed though this isn't a major issue if we just want to verify api functions for example. 

I think we should revisit this later but I'm not sure it's worth adding mypy support right now
