### ISSUE TITLE
sample .env file

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4616]
as a new developer, I'd like to have a sample .env file prepopulated with appropriate settings and information about to get the necessary secrets to run the app locally.

As with our other projects, the .env file should be stored in a secure, shared folder.

**Comment by HamzaIbnFarooq** [comment]
An env file has already been added to the shared folder, 2 months ago. Although it's not 100% accurate but that's the best version we currently have and new developers can use that for devstack without any compiling issue.

**Comment by HamzaIbnFarooq** [comment]
@annagav can you please have a look at the micromasters.env file uploaded to the shared folder to see if it can be updated or not?

**Comment by annagav** [comment]
@HamzaIbnFarooq could point me at the shared folder?

**Comment by HamzaIbnFarooq** [comment]
@annagav Shared in DM.

**Comment by annagav** [comment]
The file looks good to me.

**Comment by HamzaIbnFarooq** [comment]
Closing this issue as it has been resolved.
