### ISSUE TITLE
Another high school validation error

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#462]
cc @giocalitri 

When we sent `null` as the field of study to the backend it complains. We should update the backend with a database migration to allow nulls for all education and employment fields

**Comment by pdpinch** [comment]
It seems extreme to allow nulls on everything because of this one field. Are you anticipating some other changes?

**Comment by noisecapella** [comment]
It's not strictly necessary for the other fields, just for consistency. I can revert the changes to the other fields
