### ISSUE TITLE
Learner Record: Log sharing of learner records

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4628]
As a MM admin, I'd like to know how many learner records have been shared, and with which partners.

Learner records are a feature that allow learners to see all their grades in a program on one page, and to share a URL for that page with partner institution. You can read more in the [Learner Records Epic](https://github.com/mitodl/micromasters/issues/4097). The feature for sending learner records to partner institutions is described in https://github.com/mitodl/micromasters/issues/4211.

#### Acceptance Criteria:

- [ ] write a plan and share it for review, before writing code. 
- [ ] When a learner record is shared, log it someplace convenient, such as a database table. 

#### out of scope 

- [ ] create a summary report in BI

**Comment by umarmughal824** [comment]
@pdpinch could you please add a little more detail on it?

**Comment by pdpinch** [comment]
I updated the description. Let me know if you have more questions.

**Comment by pdpinch** [comment]
Here are some screenshots of the UX, to give you some context. 

Link on the Learner Dashboard (at /dashboard):

<img width="429" alt="image" src="https://user-images.githubusercontent.com/430126/100914724-70190900-34a1-11eb-8381-791ca14f1a79.png">

Learner Record page:

<img width="1744" alt="image" src="https://user-images.githubusercontent.com/430126/100914755-78714400-34a1-11eb-9202-fb9261036afd.png">

Pop-up box for sending the Learner Record to a partner institution:

<img width="626" alt="Screen Shot 2020-12-02 at 1 05 21 PM" src="https://user-images.githubusercontent.com/430126/100914810-8aeb7d80-34a1-11eb-9e76-02b6dd467a8d.png">

**Comment by umarmughal824** [comment]
@pdpinch here are my findings.

- [ ] Create a dedicated table which will take (user, partner school, and the program) fields
- [ ] On successful email sent, create a record for the email participants (associated user, program, and the partner school)

**Note**: There will be only one entry for a user against a partner school for a given program.

I don't have any idea about BI but would love to know about it. Do we have any helping material or documentation on it?

**Comment by pdpinch** [comment]
Sounds good, but I have a couple comments: 

- I want to make sure that the records include date created and date updated/modified 
- would it be helpful to to have a foreign key to the learner record (if such a thing exists)?
- given the use case, I think it's fine to have only one record, unique on user and partner

BI is an installation of ReDash, a python-based business intelligence platform. It's basically a way to create reports with SQL. I think the model you propose will work fine with it.

**Comment by umarmughal824** [comment]
> Sounds good, but I have a couple comments:
> 
> * I want to make sure that the records include date created and date updated/modified
> * would it be helpful to to have a foreign key to the learner record (if such a thing exists)?
> * given the use case, I think it's fine to have only one record, unique on user and partner
> 
> BI is an installation of ReDash, a python-based business intelligence platform. It's basically a way to create reports with SQL. I think the model you propose will work fine with it.

- Created and updated come by default to any model so will show them on the admin panel
- There is no learner record model so can't do much with it but we have the enrollment object if you want to add it That record is fetched from multiple places.
- For one user there can be only one record for a program in the partner school.

**Comment by pdpinch** [comment]
> Do we need to add any searching filters here either by users or school etc? 

There's very few of these, so I don't think it's necessary. But if its not too much trouble, you could add a filter by partner school.
