### ISSUE TITLE
Profile: don't hide Romanized name fields

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4637]
### Steps to Reproduce

1. Create a new account
2. Proceed to the first profile page, at /profile/personal
3. Enter non-Latin characters into the first name field. An emoji like 👍 will work. 
4. The form expands to display the romanized name fields so the user can enter alternate names
5. Enter non-Latin characters into the Romanized fields. 
6. Tab out of the romanized field. You should see a red underline indicating the validation didn't pass
6. Update the first name field to remove the emoji. 

### Expected Behavior

1. The romanized name should remain visible, so the error can be corrected. 
2. The form should not submit, because the romanized fields are not valid. 

### Actual Behavior

1. The form submits without issue

### Screenshot or Screencast

https://secure.vidyard.com/organizations/17949/players/C2AsxCMAirArVUpeDh4yem

**Comment by pdpinch** [comment]
Since #4654 merged, I'm not sure this is still necessary.

**Comment by pdpinch** [comment]
@HamzaIbnFarooq do you think we still need to do this, or did you take care of it already in #4654?

**Comment by HamzaIbnFarooq** [comment]
@pdpinch, yes it has been resolved. As you mentioned this ticket is a replica of https://github.com/mitodl/micromasters/issues/4638, you may close this.
