### ISSUE TITLE
Profile: replace Risal, Philippines with Rizal

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4653]
reported in https://odl.zendesk.com/agent/tickets/57751

### Steps to Reproduce

1. Log in and go to /profile/personal
2. Under "Where are you currently living" set the Country to "Philippines" 
3. Open the drop-down for "State or Territory"

### Expected Behavior

- you can choose the state "Rizal"

### Actual Behavior

- the state is spelled "Risal" 

### Notes

You can confirm this is the correct English spelling for the state in Wikipedia.

We should make this change in [our fork of the iso-3166-2.js library](https://github.com/mitodl/iso-3166-2.js) and then open a pull request upstream.

**Comment by HamzaIbnFarooq** [comment]
@pdpinch should we create a PR from the master of [mitodl fork](https://github.com/mitodl/iso-3166-2.js) to the [upstream ](https://github.com/olahol/iso-3166-2.js) or just a PR to fix the "Rizal" state-name issue?

**Comment by HamzaIbnFarooq** [comment]
Upstream PR: https://github.com/olahol/iso-3166-2.js/pull/32

**Comment by pdpinch** [comment]
Sorry I missed this question. 

Yes, please open a PR upstream as well. 

> @pdpinch <https://github.com/pdpinch> should we create a PR from the master of mitodl fork <https://github.com/mitodl/iso-3166-2.js> to the upstream  <https://github.com/olahol/iso-3166-2.js>or just a PR to fix the "Rizal" state-name issue?
