### ISSUE TITLE
Program Page: Label elective requirements

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4660]
As a potential MicroMasters learner, I'd like to know what the requirements are for electives in a program. 

For example, for the current DEDP electives at https://micromasters.mit.edu/dedp/ we should add  two headers to the courses card on the side of the page: one for the core courses with the text "Complete All:" and one for the electives, with the text "Complete 2 of 3:" 

#### Designs and Mockups

https://invis.io/USUG2T5R7H9

#### Acceptance Criteria:

- [ ] Group the courses in the course card by elective set
- [ ] Add an appropriate header for each elective set 

#### Out of Scope

- we won't make any changes to the learner dashboard at this time.

**Comment by arslanashraf7** [comment]
@pdpinch can you please invite me and @HamzaIbnFarooq to the InvasionApp as currently, we don't have access to it. Our emails are `arslan.ashraf@edly.io` and `hamza.farooq@edly.io`.

**Comment by pdpinch** [comment]
I updated the InVision link in the description.

**Comment by arslanashraf7** [comment]
There is an addition to this functionality about how we are going to show the electives.

Previously, the program page used to show all the elective courses from all the elective sets that are part of a program. This used to work without categorization except for Label test `ELECTIVE` on the left side of the rendered course row.

The new implementation of this will categorize the elective courses with a specific header labeled as `<ELECTIVE_SET_TITLE> (Complete <REQUIRED_NUMBER> of <TOTAL_ELECTIVE_COURSES_IN_SET>)`.

**Scenario:**
1. Let's assume we have 7 courses associated with a program, namely `Course 1, Course 2 ... Course 7`
2. Assuming `Course 1` and `Course 2` are not part of any elective set. (We'll treat them as CORE courses)
3. Assuming `Course 3`, `Course 4`, and `Course 5` are part of an Electives set titled `Elective set 1` with `Required_number` as 2.
4. Assuming `Course 6` and `Course 7` are part of another Elective set titled `Elective set 2` with `Required_number` as 1.
In the above scenario, we assume that the mentioned elective sets are associated with the program.

Below is what would be the categorization(mentioned above) on the program page:
**`CORE (Complete all)`**
`Course 1`
    `Course 2`

**`Elective set 2 (Complete 2 of 3)`**
    `Course 3`
    `Course 4`
    `Course 5`

**`Elective set 3 (Complete 1 of 2)`**
    `Course 6`
    `Course 7`
