### ISSUE TITLE
Process exam grades csv from edx 

### ISSUE THREAD

**Issue by annagav** [mitodl/micromasters#4668]
Add a management command for reading and creating (already adjusted) exam grades from a csv file provided by the course team.

**Comment by annagav** [comment]
@pdpinch do you already have a sample csv file for the grade report?

**Comment by annagav** [comment]
Looking at the documentation here https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/proctored_exams/rpnow_results.html#download-the-proctored-exam-results-report for status fields in the exam grade report.

**Comment by annagav** [comment]
@pdpinch do you think when the grades are adjusted the course team would add columns to the spreadsheet with some information on `passing score`?

**Comment by annagav** [comment]
@pdpinch I think we used to get the passing score for an exam from Pearson, and the adjusted grades csv doesn't seem to contain that column. Would it make sense to add a field `passing_score`  to ExamRun model, so you could set the value when setting up the Exam run? I don't know if this value changes ever with any grade readjustments.

**Comment by annagav** [comment]
@pdpinch Is is a correct assumption that there will be on one exam_run per course per term, or do we sometimes have exceptions?

**Comment by pdpinch** [comment]
With Pearson we would sometimes have multiple exam_runs per course per term, to accommodate people with scheduling issues. 

With edX.org exams, I don’t expect that any more. The course team will be able to reset learners if needed, and they can retake the exam without a special exam_run.
