### ISSUE TITLE
Performance monitoring

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#469]
As a devops, I'd like to be able to monitor the response time of the server so I can detect any issues in response time and, ideally, identify their cause. 

Loading micromasters-ci is often very slow, which we attribute to the time spent waking the Heroku dyno. We need some monitoring in place so that we know that this isn't an issue in production.

**Comment by Ferdi** [comment]
@blarghmatey Can you update the description/status pls ?

**Comment by blarghmatey** [comment]
We have the MicroMasters app configured to use NewRelic which will alert based on their Apdex score which is a proxy for user experience. If it falls below a configurable threshold (currently 0.7) it will fire an alert which gets routed to the on-call operations engineer via OpsGenie. NewRelic also provides request rates and response times. We can also get that information from Heroku.

NewRelic will additionally provide the list of the slowest transactions with traces into what is causing them.

I also configured Heroku to send an alert email to OpsGenie if it consistently sees 95th percentile response times in excess of 1 second or >5% of requests get an error response.

**Comment by pdpinch** [comment]
What are the first-response remedies for a low appdex score or high response time?

**Comment by blarghmatey** [comment]
The first-response solutions are somewhat dependent on the specific cause but they are likely either add more dynos if the per-dyno load is too high, scale the dynos to a larger size if they are maxing out on RAM, or bounce the processes if there is an intermittent bug resulting in a higher than normal error rate.

**Comment by pdpinch** [comment]
How do we test the New Relic and OpsGenie configurations? Do you expect we'll see some notifications when we do load testing?

**Comment by blarghmatey** [comment]
I imagine that we should see some alerts come through once we start load testing until we get the scaling factors tuned properly.
