### ISSUE TITLE
Upgrade heroku stack

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#4695]
Micromasters is running on `heroku-16`, which in EOL in April 2021. We should upgrade this well ahead of time.

For each environment, there is an "Upgrade Stack" button on the Heroku website. Once run, we should verify the application still works, so we should treat this upgrade as a release of its own.

- [x] Upgrade stack for CI
- [x] Upgrade stack for RC
- [x] Upgrade stack for Prod

**Comment by asadiqbal08** [comment]
Can we add the details a bit more, I mean what actions are required for that upgrade etc etc ?

**Comment by rhysyngsun** [comment]
@asadiqbal08 I updated the description

**Comment by pdpinch** [comment]
My mistake. Someone from @mitodl/devops should take care of this.

**Comment by pdpinch** [comment]
@rhysyngsun can this be closed now?

**Comment by rhysyngsun** [comment]
Completed 1/14/21
