### ISSUE TITLE
Bug: micromasters-ci still requires authorization on login with edX 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#470]
Presumably, this is a configuration issue -- we're either using the wrong OAuth library on the CI server, or we haven't configured OAuth to skip authorizations.

**Comment by pdpinch** [comment]
just fix the django configuration

**Comment by giocalitri** [comment]
I just configured all the apps in 
https://micromasters.d.mitx.mit.edu/admin/oauth2_provider/application/

to skip the authorization and in particular
![screen shot 2016-06-06 at 2 36 57 pm](https://cloud.githubusercontent.com/assets/1005204/15833400/b1706f8e-2bf4-11e6-8d59-01cd5108cd84.png)

**Comment by giocalitri** [comment]
@Ferdi can you please test it tomorrow morning to check if it asks again for the authorization?

**Comment by giocalitri** [comment]
@Ferdi just tested it and the problem is fixed
