### ISSUE TITLE
Remove eligibility dates from ExamRun

### ISSUE THREAD

**Issue by annagav** [mitodl/micromasters#4703]
Remove `date_first_eligible` and `date_last_eligible` from the model `ExamRun`. Remove all usages of those values in the exam card, and replace it with schedulable dates.

**Comment by pdpinch** [comment]
Is there some way to preserve the historical data, but remove it going forward?

I'm just a little concerned about needing to review this old data to resolve user tickets about past course runs. 

Another option is just to wait longer before removing this data.

**Comment by annagav** [comment]
It looks like we are still going to need eligibility dates, as dates for when the learner can actually take the exam.
