### ISSUE TITLE
Test student dashboard with a real certificate

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#471]
Up until now, we've only test the student dashboard with a fake certificate, which leads to the odd situation of a pass with 0%. We need to test with a more plausible certificate. 

We can do this by:

- [ ] create a dummy course with at least one problem
- [ ] create a verified track for the course
- [ ] add the course to a micromasters program
- [ ] register a user as verified
- [ ] have the verified user answer the problem
- [ ] run the certificate generation command

**Comment by noisecapella** [comment]
@pdpinch Is this something I can work on or is it more of a devops task?

**Comment by pdpinch** [comment]
With Brandon out, I'd appreciate your attention. 

Giovanni may know some of the prerequisites: the course must have a verified track, and the user must be enrolled as verified. You may have to be creative about the course content & grading policy. Then I think there's a management command for generating certificates. 

----------------
I am mobile.

**Comment by noisecapella** [comment]
Ok, I can verify that the dashboard shows the correct grade with a passed certificate. Is that it for this issue?

**Comment by pdpinch** [comment]
Screenshot? 

@giocalitri anything else?

**Comment by giocalitri** [comment]
I think this is it.
