### ISSUE TITLE
populate_edx_exam_coupons error for course 14.310x

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4719]
The regex we're using to assign coupons to courses is having trouble distinguishing between 14.310x and 14.310Fx. 

### Steps to Reproduce

1. Run the `populate_edx_exam_coupons` with coupons for 14.310x

```
~ $ python manage.py populate_edx_exam_coupons 14.310x.csv
CommandError: There are multiple courses with given number "14.310"
```

### Expected Behavior

- Coupons should be added to ExamAuthorizations for 14.310x

### Actual Behavior

`CommandError: There are multiple courses with given number "14.310"`

**Comment by pdpinch** [comment]
I worked around this by temporarily changing the course number of 14.310Fx, running the command, and then changing it back.

**Comment by annagav** [comment]
This issue is no longer relevant since the command now reads the course number from the file itself.
