### ISSUE TITLE
Fix flaky financial aid calculator tests

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#4721]
### Steps to Reproduce

```

  1) FinancialAidCalculator
       should let you enter your preferred currency:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/micromasters/micromasters/static/js/containers/FinancialAidCalculator_test.js)
  
```

### Expected Behavior

Tests pass consistently

**Comment by HamzaIbnFarooq** [comment]
Seems like it has already been solved in https://github.com/mitodl/micromasters/pull/4720 by increasing the amount of [timeout](https://github.com/mitodl/micromasters/blob/master/static/js/containers/FinancialAidCalculator_test.js#L325).

**Comment by rhysyngsun** [comment]
I think ideally we don't need the timeout, so maybe we should redefine this issue to be to refactor the tests, which i guess raises another question of how valuable that is, given this product sees smaller quantities of development.

It looks like the tests here haven't had a functional change since Jul 18, 2017, so we can maybe backlog this issue.

**Comment by HamzaIbnFarooq** [comment]
Thanks @rhysyngsun, that makes sense to me. Now it seems like the ball is in @pdpinch 's court.

**Comment by pdpinch** [comment]
Ok. I'm going to close this unless/until we see the test failures crop up again.
