### ISSUE TITLE
Admin for ExamAuthorization

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4723]
As an admin, I'd like to be able to add an `exam_coupon_url` to an ExamAuthorization through the django admin. 

#### Acceptance Criteria:

- [ ] display the exam_coupon_url in list view so it's easy to see which ExamAuthorizions don't have them
- [ ] display user email, exam_run_id and course number in list view
- [ ] in detail view, use raw id for the user foreign key, to avoid timeouts in production

**Comment by HamzaIbnFarooq** [comment]
@pdpinch Kindly have a look at the attached Screenshots [here](https://github.com/mitodl/micromasters/pull/4724) to see if it fulfills the requirements.
