### ISSUE TITLE
Upgrade to Python 3.9

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#4729]
As a developer, I'd like to use the latest stable version of python so that we can upgrade our build environment  

#### Acceptance criteria
 - [ ] Update `runtime.txt` to update the heroku stack
 - [ ] Update the github actions configuration to use this version of python
 - [ ] Update docker containers to use this version of python

**Comment by arslanashraf7** [comment]
Initial attempts to upgrade python to 3.9 show that we might be facing some package issues e.g `psycopg2, astroid, pylint`. Though `psycopg2`'s pip wheel breaks with python 3.9 and it looks like we don't still have a python3.9 supported version of it. Some references are available for `psycopg2` support but the latest version of it (https://pypi.org/project/psycopg2/) still breaks for me with `python3.9`.

I'm trying to at least upgrade python to 3.8 which currently seems feasible with few requirement tweaks and available supported versions.

**Comment by arslanashraf7** [comment]
An additional detail to my last comment, I tried again and i was able to upgrade it to 3.9. My best guess is that previously i had some bad environment issues that broke the `psycopg` wheel.

The 3.9 upgrade changes are done in https://github.com/mitodl/micromasters/pull/4769/.

**Comment by arslanashraf7** [comment]
Closing this since the associated PR is deployed on production now. https://github.com/mitodl/micromasters/pull/4769
