### ISSUE TITLE
make "enroll" and "upgrade to verified" buttons more accessible

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#473]
As a screen reader user who navigates the dashboard by links, there's no way to distinguish multiple "enroll" buttons or multiple "upgrade to verified" buttons. 

We can follow the approach in https://github.com/edx/edx-platform/pull/12269 (which includes a custom `sr` CSS class

**Comment by noisecapella** [comment]
It looks like bootstrap includes a class `sr-only` already
