### ISSUE TITLE
ZenDesk Theme

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4734]
As a customer support person, I'd like users to read the FAQs in the ZenDesk Help Center before they open a ticket. 

The help center needs some theming

#### Designs and Mockups

https://invis.io/HQZS3LCBPAD#/440821532_MM_Zendesk_Page

#### Acceptance Criteria:

- [ ] Create a repo similar to https://github.com/mitodl/mitxpro-zendesk-theme

**Comment by HamzaIbnFarooq** [comment]
[mitxpro-zendesk-theme](https://github.com/mitodl/mitxpro-zendesk-theme) is forked from [zendesk's copenhagen_theme](https://github.com/zendesk/copenhagen_theme).

From the description, it seems like we have to get our new repo from our own fork (mitxpro-zendesk-theme), is this correct?

FYI: the new repo will be a direct upload, as we can't fork the same repo multiple times.

**Comment by HamzaIbnFarooq** [comment]
@pdpinch do we have any zendesk support app configured for micromasters? and can I get its access?

**Comment by pdpinch** [comment]
We haven’t done a custom theme for Micromasters, so I don’t think we have a support app configured. 

If I recall correctly, giving you access requires a ZenDesk license. I’ll ask if we have any spare ones, but they are very expensive.

**Comment by HamzaIbnFarooq** [comment]
I might not need the full access, I just want a support app created just like you did with mitxpro and an API-Token to connect my local repo to zendesk app, to do further processes.

**Comment by HamzaIbnFarooq** [comment]
@pdpinch 
Following tasks are blocking me rn:
1) Define a base for micromasters zendesk repo, it any would be any of ([mitxpro-zendesk-theme](https://github.com/mitodl/mitxpro-zendesk-theme) or [zendesk's copenhagen_theme](https://github.com/zendesk/copenhagen_theme))
2) Need to get a Zendesk support app created for micromasters (just like https://xpro.zendesk.com/)
3) Access to zendesk app (if can't add a new user, we can simply create an `API token` from `Zendesk Support Admin panel` and use any user's email who have access to the app)

**Comment by HamzaIbnFarooq** [comment]
@pdpinch can I get the background-image shown in https://invis.io/HQZS3LCBPAD#/440821532_MM_Zendesk_Page, I got one from google but the resolution quality is not as better as required.

**Comment by abdulkdawson** [comment]
@HamzaIbnFarooq here is the image you requested. 
![Mit_Zendesk_Hero](https://user-images.githubusercontent.com/49685474/104602224-2c412400-5649-11eb-9e08-b245546e78f1.png)

**Comment by pdpinch** [comment]
I'm going to reopen this and assign it to Brian so he can finish the last part of deploying it to ZenDesk.

**Comment by pdpinch** [comment]
This should be deployed to https://mitx-micromasters.zendesk.com/hc/
