### ISSUE TITLE
MM Homepage Redesign

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4736]
The current home page doesn't present the MicroMasters program as it exists now. In particular, we want a better presentation of five programs, webinars and FAQ.

The home page should continue to be a static HTML page. 

#### Designs and Mockups

https://invis.io/YFZ4N7KMWT3#/435513872_Homepage_V2

#### Acceptance Criteria:

- [x] New (shorter) hero image
- [x] new tag line
- [x] move video from an embedded player to a pop-up (similar to xPRO)
- [x] change program tiles to a two column layout
- [x] on hover over the tiles, display program description and link to program page
- [x] OMIT B2B section in design (content is not ready)
- [x] be sure to include mobile screenshots on PR
- [x] Events button links to /events/ page which will use same template as ... 
- [x] FAQ section links to ... 

#### Out of Scope

- B2B section
- Update edX logos to new edX branding

**Comment by umarmughal824** [comment]
@pdpinch I am confused about the last two points (Events & FAQ) ending with `...`, could you please elaborate on that.

**Comment by abdulkdawson** [comment]
@umarmughal824 here are the MM images I think you are requesting. 

![FAQ_Icon](https://user-images.githubusercontent.com/49685474/104194185-f6086800-53ee-11eb-98a7-d693e675d0ca.png)

![New_MIT_MM_hero_Image](https://user-images.githubusercontent.com/49685474/104194213-fe60a300-53ee-11eb-92af-78001e55e024.png)

![MIt event image](https://user-images.githubusercontent.com/49685474/104194259-0b7d9200-53ef-11eb-9039-1ccc243f18fd.png)

![B2B logo](https://user-images.githubusercontent.com/49685474/104194275-10424600-53ef-11eb-92f7-90913b6c65e1.png)

**Comment by abdulkdawson** [comment]
@HamzaIbnFarooq here are the new icons for the home page. 

This should replace the dollar sign.
![dome_icon](https://user-images.githubusercontent.com/49685474/105393167-063bf680-5bea-11eb-9e05-9eb43df7b082.png)

This should replace the old B2B logo.
![B2B_Icon_2](https://user-images.githubusercontent.com/49685474/105393141-ff14e880-5be9-11eb-88d0-8c56fe0f10ca.png)

**Comment by umarmughal824** [comment]
@abdulkdawson I need that mit-dome transparent image in that dimension. `123*91` like its siblings icons.

**Comment by abdulkdawson** [comment]
@umarmughal824 here is the updated icon at 123 x 91. 
![dome_icon](https://user-images.githubusercontent.com/49685474/105502224-38edf980-5c93-11eb-861a-c23253a4d3c6.png)

**Comment by abdulkdawson** [comment]
@umarmughal824 I've made some size adjustments to the icon. Let me know how this works.

![dome_icon](https://user-images.githubusercontent.com/49685474/105515541-cedd5080-5ca2-11eb-96ad-1cb55e73ec6e.png)

**Comment by umarmughal824** [comment]
@abdulkdawson anyhow, I have updated it in the build. You can view it here.
https://micromasters-ci-pr-4749.herokuapp.com/

<img width="1440" alt="Screenshot 2021-01-22 at 21 47 35" src="https://user-images.githubusercontent.com/4043989/105519642-78503080-5cfb-11eb-93b4-7a0c76858d1a.png">

**Comment by abdulkdawson** [comment]
@umarmughal824 here are new image files in a webp format. You have to unzip the folder. 

[MM_Icons.zip](https://github.com/mitodl/micromasters/files/5857620/MM_Icons.zip)

**Comment by umarmughal824** [comment]
@abdulkdawson could you please share the B2B icon with white lines and its background image as given in the Invision?

**Comment by abdulkdawson** [comment]
@umarmughal824 here are the icons you requested. 

![B2B_BIG_BG](https://user-images.githubusercontent.com/49685474/106006133-e477bf00-6082-11eb-9e59-8e3861702d3c.png)

![B2B_logo_White](https://user-images.githubusercontent.com/49685474/106006162-e9d50980-6082-11eb-84ba-3af1286fe029.png)

**Comment by umarmughal824** [comment]
@abdulkdawson I need background image with the black background, otherwise, it looks like
<img width="1440" alt="Screenshot 2021-01-28 at 12 23 47" src="https://user-images.githubusercontent.com/4043989/106106446-5b868380-6167-11eb-9fc8-065508f6ab03.png">


@pdpinch So for now, I have applied the black color as the background. If you think that is fine

<img width="1440" alt="Screenshot 2021-01-28 at 12 50 56" src="https://user-images.githubusercontent.com/4043989/106106519-7c4ed900-6167-11eb-86c6-c53f6bc832fb.png">

**Comment by abdulkdawson** [comment]
@umarmughal824 here's the proper background 

![B2B_Background](https://user-images.githubusercontent.com/49685474/106149722-95945d00-6148-11eb-86ad-4d1aae6d1e51.png)

**Comment by umarmughal824** [comment]
thanks @abdulkdawson
