### ISSUE TITLE
Use chai eventually assert to assert promise results

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#475]
This wouldn't change functionality, it would just make our tests cleaner and more explicit

http://chaijs.com/plugins/chai-as-promised/

cc @gsidebo

**Comment by aliceriot** [comment]
can we use chai side-by-side with mocha, or will we have to refactor our current test setup?

**Comment by noisecapella** [comment]
I believe we would just replace our `assert` library with the chai one. It looks like chai provides an assert module which is a drop in replacement for the one we currently use

**Comment by aliceriot** [comment]
Awesome, that sounds pretty painless.

**Comment by gsidebo** [comment]
@aliceriot what he said. fyi: https://mochajs.org/#assertions

our current assertion library is 'assert' (confused yet?). chai would just replace it and allow for some more elegant and (most importantly) accurate assertions

**Comment by noisecapella** [comment]
It looks like it's not quite drop-in, we would need to rename `assert.ok` to `assert.isOk` or just `assert()`.

**Comment by noisecapella** [comment]
It looks like if we return the promise from the test we don't need chai-as-promised at all: http://tobyho.com/2015/12/16/mocha-with-promises/

**Comment by noisecapella** [comment]
Actually now that I think about it we can use the chai assertions inside our util methods like `listenForActions` and `renderComponent` to provide better error messages, and return the promise in our tests also
