### ISSUE TITLE
Upgrade boto to boto3

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#4753]
`boto` is unmaintained and hasn't been updated in over 2 years. It's also now caused the warning
```
/usr/local/lib/python3.7/site-packages/boto/plugin.py:40
  /usr/local/lib/python3.7/site-packages/boto/plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
```

The `imp` module has been deprecated since python 3.4 and is scheduled for remove in python 3.10 ([see PEP 594](https://www.python.org/dev/peps/pep-0594/#imp)).

There is some usages in pearson code which we _probably_ don't need anymore. Please verify this w/ Peter and if so we can probably also remove the pearson code as a pre-req.

**Comment by pdpinch** [comment]
Which Pearson code in particular uses boto?

**Comment by arslanashraf7** [comment]
@pdpinch I was able to take an initial look at this and it seems that we are using `boto` in our `ExamDataAuditor` class of Pearson. e.g.

- `exam/pearson/audit` https://github.com/mitodl/micromasters/blob/master/exams/pearson/audit.py

Other indirect usages are associated with either tests of audit class or the usages of `ExamDataAuditor`.

**Comment by arslanashraf7** [comment]
Looks like the code containing boto usage might be removed in another legacy code removal PR https://github.com/mitodl/micromasters/pull/4765/files#diff-050dcae6dde23195d90b4f02491429cf2cd2a8d13c4406bddc867906b29660acL5. Putting this on hold till that PR is finalized after which we can decide if we will need to proceed with this or not.

**Comment by annagav** [comment]
@arslanashraf7 The PR with the removal of the  legacy Pearson code was merged.

**Comment by arslanashraf7** [comment]
Deployed on production now.
