### ISSUE TITLE
Profile: Tighten up the Education and Professional forms

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#476]
When there is no education or employment listed, we don't need so much space for each card.

**Comment by aliceriot** [comment]
@pdpinch is there a mockup which shows what the optimal end state is for this, or should I just give it a go?

**Comment by pdpinch** [comment]
Please "give it a go" and post a screenshot to the issue for Ferdi to review.

**Comment by aliceriot** [comment]
will do!

**Comment by aliceriot** [comment]
here's what I have so far!

![standard](https://cloud.githubusercontent.com/assets/6207644/15868894/be4bc2ee-2cb7-11e6-8bba-d5f200c5e767.png)

![partially](https://cloud.githubusercontent.com/assets/6207644/15868897/c159c01c-2cb7-11e6-8d11-3342d32c4d14.png)

![fully](https://cloud.githubusercontent.com/assets/6207644/15868898/c3ab1690-2cb7-11e6-94a1-5968b3746ccb.png)

basically this is just setting the `min-height` to be a little bit smaller, setting `padding-bottom: 0` and decreasing `margin-bottom` a little bit. I also deleted the placeholder text we had previously when the work history for was switched off.

**Comment by pdpinch** [comment]
Actually, this issue was about the profile -- /profile/education -- not /users (I wish I had better names for these views). 

That said, this is a relevant test for #498

**Comment by aliceriot** [comment]
Ah, so the changes I made above I just showed on the `/users` page for convenience, the changes above are made in such a way that they show up the same way on `/profile/education` and `/profile/professional`.

**Comment by pdpinch** [comment]
Ah, cool. I didn't realize. 

These seems like good improvements, but can we can remove some of the whitespace in the card in the case where the switch is on, but there are now rows yet (i.e. when there's just the FAB)?

**Comment by aliceriot** [comment]
I can try! that's a little bit trickier but it might be doable.

**Comment by aliceriot** [comment]
another go! here I removed some `padding-bottom` on the card and also removed `min-height`:

![smaller](https://cloud.githubusercontent.com/assets/6207644/15870904/0ef901ea-2cc0-11e6-97e1-9aa1f1a07f7b.png)

it's more condensed, but I think still not too busy.

**Comment by aliceriot** [comment]
@pdpinch if this looks good I can go ahead and open a pr with these changes, let me know what you think!

**Comment by aliceriot** [comment]
@pdpinch do you have any feedback on this? I have a pr I can open if the above screen looks good to you.

**Comment by pdpinch** [comment]
Sorry I was slow to get back to you. This look good. 🚢
