### ISSUE TITLE
Profile Privacy: move each hint to its own line, below the radio button.

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#477]
- [x] move each hint to its own line
- [ ] make hint text accessible, using #555555 for the text color
- [x] change the text as follows:

`Your MicroMaster’s profile will be visible to all website visitors.`

`Your profile will be visible to other MicroMaster’s learners, and to MIT faculty and staff`

`Your MicroMaster’s profile will only be visible to MIT faculty and staff`

**Comment by amir-qayyum-khan** [comment]
@pdpinch So, do you want me to change color of hint as well. Of this light gray color is ok?

**Comment by amir-qayyum-khan** [comment]
@pdpinch is this UI ok.

![screen shot 2016-06-07 at 5 12 48 pm](https://cloud.githubusercontent.com/assets/10431250/15857140/2a706b44-2cd3-11e6-84eb-5630f6385f0f.png)

**Comment by pdpinch** [comment]
Using the color contrast check at http://webaim.org/resources/contrastchecker/ you are correct -- there isn't enough contrast between that gray and the white background. 

Let's change the hint text to #555555 -- it's pretty dark but it passes the WCAG AAA requirement.

**Comment by pdpinch** [comment]
Please change the text as follows (I also updated the description):

`Your MicroMaster’s profile will be visible to all website visitors.`

`Your profile will be visible to other MicroMaster’s learners, and to MIT faculty and staff`

`Your MicroMaster’s profile will only be visible to MIT faculty and staff`

**Comment by pdpinch** [comment]
UI looks good.

**Comment by amir-qayyum-khan** [comment]
Done.
![screen shot 2016-06-07 at 5 37 59 pm](https://cloud.githubusercontent.com/assets/10431250/15857793/9bb9920a-2cd6-11e6-900b-2f834c335f3b.png)

**Comment by pdpinch** [comment]
While we're working on this, can you change the header text `Who can see your profile` to an h4? I think it should be styled the same as similar questions in the other profile forms.

**Comment by amir-qayyum-khan** [comment]
ok let me.

**Comment by amir-qayyum-khan** [comment]
Done @pdpinch 

![screen shot 2016-06-07 at 5 55 49 pm](https://cloud.githubusercontent.com/assets/10431250/15858276/213abdf8-2cd9-11e6-8393-bc5619559c33.png)
