### ISSUE TITLE
Exams: use edX coupons more efficiently

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4770]
In our current implementation of edX proctored exams, we require one coupon per ExamAuthorization. Since there are many, many users with historical authorizations, and because users don't always take their proctored exam in the same term as the course, we end up requiring far more coupons than are actually used. This is problematic because edX requires several weeks notice to create coupons, and it is difficult to accurately predict how many we will need before the course concludes. 

A more efficient system would be to have a pool of coupons which we assign to ExamAuthorizations when they are needed. There are multiple ways to determine "when the coupon is needed" but the simplest seems to do it at the time a user loads their dashboard and gets the exam/coupon link. Typically, users who aren't taking the exam won't be loading their dashboard. 

#### Acceptance Criteria:

- [ ] create a model for edX coupons. It should carry enough metadata to manage the coupons, i.e.
       - course the exam is associated with (foreign key to course?)
       - expiration date
       - coupon code
       - URL for using coupon code
       - edX course key for the exam course 
       - type of coupon ("exam")
       - status? 
       - other foreign keys?
- [ ] management command for ingesting coupons from a csv
- [ ] update the dashboard API to assign a coupon to the ExamAuthorization if necessary (hopefully this won't make the dashboard API much slower than it already is) 
- [ ] confirm that the front-end doesn't require any additional changes

#### Related Issues

- Update dashboard message to include link to instructions on how user can get to exam course
- Improve error handling when the front-end logic expects an exam coupon link and there is none

**Comment by pdpinch** [comment]
@annagav should this be a mini-epic? I can see there being 3 or 4 different PRs.

**Comment by annagav** [comment]
@pdpinch is there an automatic expiration date that we would want to set on coupons? maybe 3 months from creation...

**Comment by pdpinch** [comment]
When we get the coupons from edX they will have an expiration date on them. Do you want to ingest that, or just set a default? 

I presume we ask for a specific date when we request them.
