### ISSUE TITLE
Programs that are not live should not display on the home page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4777]
### Steps to Reproduce

1. Create a Program
2. Set `live=False` on the program

### Expected Behavior

The program should not display on the home page

### Actual Behavior

There is an empty space on the home page for the program. 

### Screenshot or Screencast

from RC, where there are only 5 live programs: 

![image](https://user-images.githubusercontent.com/430126/107410448-51f00a80-6adb-11eb-9976-e06968f1ff20.png)

**Comment by arslanashraf7** [comment]
@pdpinch I was unable to reproduce this issue locally as well as on RC. What i tried to reproduce is basically:
1. Add a program through `/admin`
2. Set `Live Checkbox` Unchecked
3. Tried with both (With & without creating associated CMS Page)

Please let me know if, maybe i'm missing something or could it have been related to something else.

**Comment by pdpinch** [comment]
Thanks for looking into it. I see now that RC is behaving properly.
