### ISSUE TITLE
Use MicroMaster's in logo image

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#478]
New logos were added in the micromasters-templates repository by https://github.com/mitodl/micromasters-templates/commit/a76837efae0521e77827b0c188febea2266e24a3

https://github.com/mitodl/micromasters-templates/blob/gh-pages/assets/images/logo-micromasters.png
https://github.com/mitodl/micromasters-templates/blob/gh-pages/assets/images/logo-micromasters%402x.png
https://github.com/mitodl/micromasters-templates/blob/gh-pages/assets/images/logo-mit-micromasters-whitered.png
https://github.com/mitodl/micromasters-templates/blob/gh-pages/assets/images/logo-mit-micromasters-whitered%402x.png

**Comment by pdpinch** [comment]
Nevermind. The apostrophe has been nixed.

**Comment by noisecapella** [comment]
We still need to change the image from `Micromasters` to `MicroMasters`
