### ISSUE TITLE
heroku-16 heroku build stack is deprecated

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#4787]
![Screenshot from 2021-02-19 09-59-28](https://user-images.githubusercontent.com/863262/108520902-2ae2c700-7299-11eb-9a87-d57769e48f41.png)

We should upgrade to heroku-20 or some other modern build stack by June to avoid build failures

**Comment by pdpinch** [comment]
It looks to me like there's only [one PR review build](https://github.com/mitodl/micromasters/pull/4786) still running on heroku-16. I think Nathan had already upgraded the others to heroku-18.

**Comment by pdpinch** [comment]
For some reason, new PR builds are getting the Heroku-16 stack. I guess I don't understand how this works. @mitodl/devops can you advise how we can/should go about updating all these, to heroku-20 as George suggests?

**Comment by shaidar** [comment]
The PR apps have the CI app as its parent and that's still using heroku-16. I can upgrade that to heroku-20 and then go from there as far as RC and production.

**Comment by shaidar** [comment]
Yeah it can be handled through `app.json` file but think once u change in the console, it won't downgrade based on what's specified in that file. For now, I updated the CI app and started a manual deploy.

**Comment by pdpinch** [comment]
I believe this was fixed by #4816
