### ISSUE TITLE
Certificates: update styling to match current edX certificates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4788]
As a user, I'd like certificates from my FA courses and programs to look the same as edX certificates. 

#### Designs and Mockups

Current [course certificates look like this](https://micromasters-rc.odl.mit.edu/certificate/course/74fa750f2d30c4cfa8bfc21052d88056) and [program certificates look like this](https://micromasters-rc.odl.mit.edu/certificate/program/0d54d09954752e507775550841644584).

They both need to be updated to match the [current edx.org certificates](https://courses.edx.org/certificates/dd6838d94f4b41038c03be77aed91172)

#### Acceptance Criteria:

- [ ] Remove the background logo
- [ ] Replace the MicroMasters logo with "Verified Certificate"
- [ ] Make sure that when the page is printed it look similar to the on-screen certificate

#### Related Issue

- #4784 certificates share and print bar

**Comment by HamzaIbnFarooq** [comment]
@pdpinch, when we try to print the edX certificate the background image doesn't get included. Are we going to replicate that as well?
![image](https://user-images.githubusercontent.com/42243411/108716934-82ee2780-753e-11eb-916b-a95bf74928dc.png)

**Comment by HamzaIbnFarooq** [comment]
Oh, sorry, that seems to be a browser-specific thing, background images need to be allowed by browsers, doesn't have anything to do with development.

**Comment by pdpinch** [comment]
The goal is to make this certificate behave the same as the edX one. 

Maybe take a look at the edX help page for printing certificates and see what they recommend as far as printing backgrounds. 

https://support.edx.org/hc/en-us/articles/207206647-How-are-edX-certificates-delivered-

https://support.edx.org/hc/en-us/articles/206504068-Can-I-get-a-paper-copy-of-my-certificate-

**Comment by HamzaIbnFarooq** [comment]
@pdpinch 
Sorry I didn't consider this scenario earlier, so mentioning it now, when there are more than 3 signatories the printer can't print that onto a single page (e.g: https://micromasters-rc.odl.mit.edu/certificate/program/0d54d09954752e507775550841644584) should we do something about it before the design release (https://github.com/mitodl/micromasters/pull/4813)?

**Comment by pdpinch** [comment]
In production, the max number of signatures we have is 4. 

What can we do?

- Peter

**Comment by HamzaIbnFarooq** [comment]
@ Pdpinch, the latest certificate design has been deployed to prod, kindly have a look into it so we can close this issue.

**Comment by pdpinch** [comment]
Thanks, this is looking good to me now.
