### ISSUE TITLE
Clarify behavior when turning switches to 'off' on education and work history forms

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#482]
Currently turning off the switch doesn't remove any previously entered jobs or degrees, so a user could enter two jobs, flip the switch to 'off', and then click 'save and continue', and currently the entered jobs would be saved.

We should clarify what we intend for the switches to do. Here's an idea:

- If a user has already entered some input, a confirmation is shown ('really delete all jobs?')
- If a user has not entered any input, the switch goes to 'off' and they are allowed past the validation
- If the switch is 'on' we validate for the presence of at least one entry (one job, one degree, etc)

**Comment by pdpinch** [comment]
Thanks Alice. This is exactly what I was expecting from the switch.
