### ISSUE TITLE
User can't checkout with old financial aid

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4823]
### Steps to Reproduce

1. Create a user
2. View the dashboard for a program with finacial aid
3. Click "skip and pay for price" which will create a full price financial aid object for the user
4. The "pay now" button should be active for your user, click it.
5. You should navigate to the checkout page, click the checkout button
6. There should be no API error and you should advance to the Cybersource site. Don't pay for the course. 
7. Now, in the django admin for financial aid program tiers, uncheck the "current" box for the corresponding tier. This prevents new users from accessing this tier 
5. As the user, return to the dashboard 
2. The "pay now" button should still be active for your user, click it. 
3. You should navigate to the checkout page, click the checkout button

### Expected Behavior

- Similar to the first time through, there should be no API error and you should advance to the Cybersource site

### Actual Behavior

- the checkout API returns a 400 error

### Stacktrace

See https://sentry.io/organizations/mit-office-of-digital-learning/issues/2270428820/?environment=production&project=104497&query=is%3Aunresolved

appears to be coming from this line of code: https://github.com/mitodl/micromasters/blob/0f4caa22263468959415a9ec3e161f7bbb710730/ecommerce/api.py#L84

**Comment by pdpinch** [comment]
I'm checking with the course team how they want to handle this. Possible solutions. 

1. Reset all the financial aid requests and ask users to apply again. 
2. Migrate all the approved financial aid requests to the new program tiers (how will we handle ambiguous cases?) 
3. Remove the check core `tier_program__current=True`

**Comment by pdpinch** [comment]
I think they're going to go for option 2, but there are some follow-up questions that would need to be answered before we can go that route. 

In the meantime, I'd like to have a PR ready to merge for option 3, since it's a straightforward change that we could possibly release on Monday -- if they decide to go that way.

**Comment by pdpinch** [comment]
I heard back from the DEDP team, and it seems like we need to go with option 2 here, migrate the existing financial aid objects. I don't think this requires a code change, but I'm going to look into it further.

**Comment by arslanashraf7** [comment]
Sure let me know if things need to be changed on the code side, Although, If it matters, I was pursuing option 2 and the branch for those changes is [here](https://github.com/mitodl/micromasters/tree/arslan/4823-financial-aid-checkout). Didn't convert it into a PR yet.

**Comment by pdpinch** [comment]
I spoke with @annagav today and we decided that we should go with a management command that migrates the prorgramtier on existing financialaid objects to use the corresponding new programtier. The mapping should be straightforward since the old and new tiers only differ in price. 

It could be something like this:
```new_programtier = ProgramTier.objects.get(threshold=old_programtier.threshhold)```
