### ISSUE TITLE
Dashboard: Confusing exam dates after payment deadline passed

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4824]
### Steps to Reproduce

1. Create a user and enroll them in a course run that has a final exam (I believe their is a seed data command to do this)
2. Create two exams for the course, one that ended in the past and one that is coming up in the future.
3. Set the upgrade deadline for the course run to the paste

### Expected Behavior

- The dashboard should tell the user that they missed the payment deadline for the upcoming exam, but that they can pay now for a future exam. 

### Actual Behavior

- The dashboard message suggests that they missed a payment deadline for the last exam, but they can still pay for the next one, which makes it seem like there isn't a deadline at all. 

### Screenshot or Screencast

I saw a user with this state on March 13. The payment deadline was March 12:

<img width="776" alt="wrong dashboard message for March 13" src="https://user-images.githubusercontent.com/430126/111032825-27e07f80-83dc-11eb-9f4c-d001bfb9d7ca.png">

Instead, this should just say that the learner missed the deadline to take the exam April 28th.

**Comment by pdpinch** [comment]
I'm no sure, but I don't think we have the right data model to support this properly, since _exams_ don't have payment deadline, only course runs do.

**Comment by annagav** [comment]
@pdpinch this message was implemented as a way for the user to pay for course even after the payment deadline has passed, with the ability of taking the exam. Do we still want to allow the user to pay if they missed the deadline?

**Comment by annagav** [comment]
Here is the original issue: https://github.com/mitodl/micromasters/issues/3680 for this course message.

**Comment by pdpinch** [comment]
Thanks for the context. 

Ideally, we’d like to let people pay, but not let them take the exam until the next exam offering. 

I know that’s a lot more complicated. Is there a way to do that? This week?

**Comment by annagav** [comment]
Do  they have an opportunity to take the exam without the exam authorization and coupon?

**Comment by pdpinch** [comment]
No. They can’t take the exam without authorization and the exam course coupon. 

Are you suggesting that we could control this at the authorization step?

**Comment by annagav** [comment]
The message to enroll for exam appears only if the use paid, got exam authorization and got an exam coupon. So paying for a course does not enable them the take an exam until the exam period is there.

**Comment by annagav** [comment]
@pdpinch so do we want to keep the behavior the same, and just change the message? 
Does it make sense to show the message about missed deadline if they can still pay? Or is there something that qualifies them to take the exam even though the deadline for payment passed? We could just display a message saying that next exam is coming up and they can pay to take it.
