### ISSUE TITLE
Checkout: display error for user when API returns a 400

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4825]
Related to #4823 

When the checkout API returns a 400 error, we should display an error for the user "Something went wrong. Please contact customer support" 

I looked around briefly for other models of how we handle API errors. I found an example of a [Toast message](https://github.com/mitodl/micromasters/blob/6360a9026098d0aca1b7d90dc2778d554ec227cc/static/js/containers/DashboardPage.js#L204), but if that seems too complicated I'm okay going with something simpler. 

#### Acceptance Criteria:

- [ ] Display error message when API returns a 400 error
- [ ] include a link to the customer support form (https://mitx-micromasters.zendesk.com/hc/en-us/requests/new) in the error message

**Comment by arslanashraf7** [comment]
Closing, Associated PR is merged & Deployed on production.
