### ISSUE TITLE
Users API should return 404 for users with privacy setting set to "private"

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#483]

**Comment by amir-qayyum-khan** [comment]
@pdpinch sorry i forget abt Users API. Can you give me api url?

**Comment by pdpinch** [comment]
The web page view is at /users/ but the API is /api/v0/profiles/<username>

**Comment by amir-qayyum-khan** [comment]
thanks

**Comment by amir-qayyum-khan** [comment]
@pdpinch raises PermissionDenied. Are you ok with it?

<img width="975" alt="screen shot 2016-06-08 at 3 20 38 pm" src="https://cloud.githubusercontent.com/assets/10431250/15891171/d5de0766-2d8c-11e6-844a-02ef636585da.png">

**Comment by pdpinch** [comment]
No, if we throw a 500 due to the exception, or return a 403, it leaks information that the account exists. 

We need to return a 404.

**Comment by pdpinch** [comment]
@amir-qayyum-khan what's the status of this issue?

**Comment by amir-qayyum-khan** [comment]
@pdpinch made this PR https://github.com/mitodl/micromasters/pull/546

**Comment by amir-qayyum-khan** [comment]
fixed via https://github.com/mitodl/micromasters/pull/546
