### ISSUE TITLE
"MicroMasters Certificate" missing from program certificates 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4842]
### Steps to Reproduce

1. Create a Program certificate for a fa program

### Expected Behavior

The Program credential certificate should include the text "Micromasters® Certificate" in the top left corner. 

### Actual Behavior

There is no MicroMasters label on the certificate. 

### Screenshot or Screencast

it should look something like this (signatures have been removed): 
[sample MicroMasters program credenential certificate.pdf](https://github.com/mitodl/micromasters/files/6183126/sample.MicroMasters.program.credenential.certificate.pdf)

**Comment by HamzaIbnFarooq** [comment]
@pdpinch 
when we say `fa` does it mean that we have to add this to some specific program certificates only? or it has to applied to all certificates?

**Comment by pdpinch** [comment]
Sorry for being unclear. It applies to all certs we provide. 

“Fa” is short for “financial aid.” We only provide certificates for fa courses and fa programs in the MicroMasters app. Non-fa course certificates are served from EdX.org

**Comment by HamzaIbnFarooq** [comment]
@pdpinch can close this?

**Comment by pdpinch** [comment]
I thought it was deployed to production on Friday, but I don’t see the change… 

Let me look into it some more.

**Comment by pdpinch** [comment]
Oh, there it is!
