### ISSUE TITLE
user settings

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#485]
Users should be able to change their settings from the user drop-down.

The settings page will currently just have the privacy setting.

**Comment by amir-qayyum-khan** [comment]
@pdpinch  is their UI mocks for this task. Should we reuse profile/privacy tab here?

**Comment by pdpinch** [comment]
There's no mock-up for this task. We should use the same UI as /profile/privacy

**Comment by pdpinch** [comment]
@amir-qayyum-khan thanks for the PR. You should have copied the screenshots here for discussion:

#### Screenshots 

<img width="364" alt="screen shot 2016-06-10 at 6 39 08 pm" src="https://cloud.githubusercontent.com/assets/10431250/15966097/015fccb2-2f3b-11e6-9c38-63f77cd17413.png">
<img width="785" alt="screen shot 2016-06-10 at 6 41 30 pm" src="https://cloud.githubusercontent.com/assets/10431250/15966096/015eb872-2f3b-11e6-9529-17d7dcef7984.png">

**Comment by pdpinch** [comment]
repeating my https://github.com/mitodl/micromasters/pull/519#issuecomment-225273413 on the PR:

- [ ] remove text "We care about your privacy"
- [ ] remove dotted line and move the form up 
- [ ] The button label should be "Save" instead of "I'm Done!"

**Comment by amir-qayyum-khan** [comment]
fixed via https://github.com/mitodl/micromasters/pull/519

**Comment by pdpinch** [comment]
You can open another issue to fix it
