### ISSUE TITLE
Make separate celery queue for index_users tasks

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4880]
In #4702 we created a separate celery queue for the dashboard tasks. Today we discovered a backlog of tasks due to `index_user` tasks. 

To make tasks queues more manageable, we should create a separate queue for `index_users` as well.

**Comment by pdpinch** [comment]
according to @rhysyngsun "it's fine for that queue to be added to the same worker that's running the dashboard queue"

**Comment by rhysyngsun** [comment]
I think we run all the workers on all queues, that's fine to continue with this new queue.

**Comment by rhysyngsun** [comment]
Fixed by #4883
