### ISSUE TITLE
Add link to ZenDesk Help Center (FAQ) to page footer

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4887]
As a user, I'd like quick and easy access to the FAQs that are hosted in the ZenDesk help center. 

In https://github.com/mitodl/micromasters/pull/4749 we added a FAQ icon and link to the bottom of the home page. We will add that section to all the page templates. 

#### Acceptance Criteria:

- [x] Program page(s) template(s)
- [x] "Benefits" page template
- [x] Learner Dashboard

I don't think other templates need the FAQ link necessarily, since they're rarely used. But if it's easier to add it everywhere, let's do that.

**Comment by arslanashraf7** [comment]
@pdpinch Can you suggest the order in which it should appear on the aforementioned pages in the ticket? e.g. if we visit https://micromasters.mit.edu/scm/ program we can see `Instructors` right above the footer, should it be above the instructors or below them in this case?

On the benefits page, I assume it will be just above the footer.

For reference, this is the current behaviour on `HomePage` where it shows above the quotes section:
<img width="1440" alt="Screenshot 2021-05-18 at 5 05 15 PM" src="https://user-images.githubusercontent.com/34372316/118647938-5410e600-b7fb-11eb-8e0b-7f915efe6087.png">

**Comment by pdpinch** [comment]
On all pages except the home page, the FAQ link should appear directly above the footer. 

So, on the program page, it should appear below the Instructors carousel. 

> @pdpinch <https://github.com/pdpinch> Can you suggest the order in which it should appear on the aforementioned pages in the ticket? e.g. if we visit https://micromasters.mit.edu/scm/ <https://micromasters.mit.edu/scm/> program we can see Instructors right above the footer, should it be above the instructors or below them in this case?

**Comment by arslanashraf7** [comment]
> On all pages except the home page, the FAQ link should appear directly above the footer. So, on the program page, it should appear below the Instructors carousel.
> […](#)
> @pdpinch <https://github.com/pdpinch> Can you suggest the order in which it should appear on the aforementioned pages in the ticket? e.g. if we visit https://micromasters.mit.edu/scm/ <https://micromasters.mit.edu/scm/> program we can see Instructors right above the footer, should it be above the instructors or below them in this case?

Thanks for clarifying that, Now while we are at it I just saw another case where I thought it would be a good idea to discuss.
We currently have an inner FAQ tab/page inside the program page, and with this ticket, I intend to add a common FAQ section that will show under all the tabs inside a program. What do you think of this FAQ section being shown under the inner FAQ tab as well?

Ref: https://micromasters.mit.edu/scm/frequently-asked-questions/

**Comment by pdpinch** [comment]
I think it's fine to include a link the ZenDesk FAQ on the program-specific FAQ pages. We plan to shorten or remove those pages, now that we have the ZenDesk FAQ up and running. 

If you could give me a screenshot when it’s ready, then I could confirm.

**Comment by arslanashraf7** [comment]
Sure thing, I'll add the screenshots in the PR where you would be able to take a look.

**Comment by arslanashraf7** [comment]
For any additional details of the pages where we added FAQ section can be seen in the [PR Description](https://github.com/mitodl/micromasters/pull/4895#issue-646724762).

**Comment by arslanashraf7** [comment]
Closing, Since the associated PR has been merged and deployed on Prod.
