### ISSUE TITLE
Link to Learner Dashboard for staff

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4888]
As a staff member, I'd like a link to see my learner dashboard, so I can review the course list and link to MIT Open. 

Currently, we replace the learner dashboard for staff users with the learner search page. Staff can view their learner dashboard by entering the URL directly, but there is no link. 

#### Acceptance Criteria:

- [ ] In the user menu, display a link to "Dashboard" above the link to "Learners"

**Comment by pdpinch** [comment]
@umarmughal824 I realize that I was vague when I said "staff"

To be more specific, I mean any user who has a "staff" or "instructor" role in the roles app: https://github.com/mitodl/micromasters/blob/master/roles/roles.py

These are the users who need to find a link to the learner dashboard, in addition to their access to leaner search.

**Comment by umarmughal824** [comment]
I had figured it out already.
