### ISSUE TITLE
Update redux hammock and update its version in micromasters

### ISSUE THREAD

**Issue by arslanashraf7** [mitodl/micromasters#4899]
- [x] Bump hosted-git-info in [redux-hammock](https://github.com/mitodl/redux-hammock)
- [x] Bump `lodash` in [redux-hammock](https://github.com/mitodl/redux-hammock)
- [x] update redux-hammock version in MicroMasters

https://github.com/mitodl/redux-hammock/security/dependabot

**Comment by arslanashraf7** [comment]
Adding the blocked label because before continuing, we'll need to push a new release of https://github.com/mitodl/redux-hammock now that the related bumps `hosted-git-info, lodash` are merged.

After the new release of `redux-hammock` we'll update the version in MicroMasters.

**Comment by pdpinch** [comment]
redux-hammock 0.3.3. is released to npm.

**Comment by arslanashraf7** [comment]
Closing, This PR has been merged and deployed on Prod.
