### ISSUE TITLE
Update trim-newlines

### ISSUE THREAD

**Issue by HamzaIbnFarooq** [mitodl/micromasters#4952]
off-topic question: why do we need an npm package to trim newlines? Is that really not a standard JS function?

See https://github.com/mitodl/micromasters/security/dependabot/yarn.lock/trim-newlines/open

**Comment by HamzaIbnFarooq** [comment]
> off-topic question: why do we need an npm package to trim newlines? Is that really not a standard JS function?

Apparently, JS doesn't have such a feature and even if there is one, micromasters is not directly using it rather it's a child dependency of `node-sass`.

**Comment by arslanashraf7** [comment]
@HamzaIbnFarooq, Just FYI, There is are similar alerts in [Bootcamp](https://github.com/mitodl/bootcamp-ecommerce/security/dependabot/yarn.lock/trim-newlines/open) & [xPRO](https://github.com/mitodl/mitxpro/security/dependabot/yarn.lock/trim-newlines/open) as well.

It might be a good idea to create similar PRs for there too.

**Comment by HamzaIbnFarooq** [comment]
closed by https://github.com/mitodl/micromasters/pull/4953
