### ISSUE TITLE
Use UUID based certificate urls

### ISSUE THREAD

**Issue by HamzaIbnFarooq** [mitodl/micromasters#4964]
Use UUID based certificate URLs in both course-certificates and program-certificates

### out of scope

At this time, we don't have any plans to change existing URLs

**Comment by pdpinch** [comment]
@HamzaIbnFarooq I added some details to the description. Let me know if this is correct.

**Comment by HamzaIbnFarooq** [comment]
Closed by: https://github.com/mitodl/micromasters/pull/4963
