### ISSUE TITLE
User's can't enroll in a course with an upgrade deadline in the past

### ISSUE THREAD

**Issue by briangrossman** [mitodl/micromasters#4975]
### Steps to Reproduce

- On RC, update the fields for a course run as follows:
   - `Enrollment start` - some date in the past
   - `Start date` - some date in the future
   - `Enrollment end` - some date in the future
   - `End date` - some date in the future
   - `Upgrade deadline` - some date in the future
   - `Freeze grade date` - some date in the future
- On the program page, this course should have a link to edX on the popup (image), provide the start date of the upcoming run, and show the start date on the dashboard (image)
![image](https://user-images.githubusercontent.com/21342568/124668495-f2760b00-de7e-11eb-867e-b1cfa310d153.png)
![image](https://user-images.githubusercontent.com/21342568/124669630-b5127d00-de80-11eb-9a20-25d11ab26800.png)
- Update the `Upgrade deadline` to some date in the past
- On the program page, this course will no longer have a link to edX on the popup (image) and the dashboard shows `There are no future runs scheduled` (image)
![image](https://user-images.githubusercontent.com/21342568/124668614-1fc2b900-de7f-11eb-86d2-58c728e4c2ef.png)
![image](https://user-images.githubusercontent.com/21342568/124669530-898f9280-de80-11eb-91cc-ce5e81f752d0.png)

### Expected Behavior

Enrollment in the course (i.e. the link to edX) and displaying the course dates should not be affected by `Upgrade deadline`, just `Enrollment end` As long as `Enrollment end` is in the future, even if `Upgrade deadline` is in the past: 
- users should be able to link through to edX on the course popup
- the upcoming / current course date should be displayed on the program page
- the upcoming / current course date should be displayed on the dashboard

### Actual Behavior

- If `Upgrade deadline` is in the past, the link to edX is removed and the upcoming / current course dates are hidden from the program pages and dashboard

**Comment by briangrossman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Brian Grossman](https://trello.com/c/p79YK9T8/6225-brian-grossman)

**Comment by annagav** [comment]
@briangrossman In the section "Steps to Reproduce" you write: `Update the Upgrade deadline to some date in the past`, and in the "Expected Behavior" you refer to "freeze grade date" as being in the past being the problem. Are you using the terms "upgrade deadline" and "freeze grade date" interchangeably?

**Comment by annagav** [comment]
I was able to reproduce this. Looking back at the [PR](https://github.com/mitodl/micromasters/pull/1389/files) it looks like it was a conscious  decision not to show the current runs with upgrade deadline in the past.

@arslanashraf7 yes, I think you can just remove that check for upgrade_deadline in `is_unexpired`. Afters that we should check all the status messages by running the selenium tests and make sure no other messages got effected.

**Comment by briangrossman** [comment]
> @briangrossman In the section "Steps to Reproduce" you write: `Update the Upgrade deadline to some date in the past`, and in the "Expected Behavior" you refer to "freeze grade date" as being in the past being the problem. Are you using the terms "upgrade deadline" and "freeze grade date" interchangeably?

@annagav 
Whoops! It was all supposed to be `Upgrade deadline`. I updated the description. 

That being said... and looking into the past issues... I just want to make sure this change is the right thing to do. The question is whether we'd ever want to show upcoming runs that are no available for upgrade.

**Comment by pdpinch** [comment]
I can confirm that what you wrote in expected behavior is what I expect: 

> Enrollment in the course (i.e. the link to edX) and displaying the course dates should not be affected by Upgrade deadline, just Enrollment end 

The is an edge case that shouldn't have happened but nonetheless, an upgrade deadline shouldn't not affect whether the course is open for enrollment.

**Comment by briangrossman** [comment]
Thanks @pdpinch! 

@arslanashraf7: You can work on this when you have time.
