### ISSUE TITLE
Collapse multiple education cards on User page into one card

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#498]
Instead of:

![screenshot-micromasters-ci herokuapp com 2016-06-07 13-43-15](https://cloud.githubusercontent.com/assets/430126/15868472/f9c9d2c2-2cb5-11e6-844a-dd85bd53aa90.png)

we'd like something more like:

<img width="293" alt="screen shot 2016-06-07 at 1 45 57 pm" src="https://cloud.githubusercontent.com/assets/430126/15868517/33b12058-2cb6-11e6-9b26-f9b0d3371e89.png">

I'm not sure if this means that we can't reuse the components from the education profile form. Also, if we collapse all the education into one form, we'll need a way for users to identify the level of a particular degree.

**Comment by pdpinch** [comment]
@Ferdi what's your opinion on this?

**Comment by Ferdi** [comment]
@pdpinch I agree actually.  I understand we might lose component re usability,   it looks like we need a new component here, very similar to Employment.

**Comment by aliceriot** [comment]
If we did this we wouldn't be able to re-use the component we currently have for education.

I think it would be a substantial amount of work to make this happen, we'd need to pull the pop-up form portion out of the current education form into a separate component, build a new display component for the `/users` page, etc. There's a lot of specialized logic built into the education form which would probably be tricky to take apart (to deal with the different degree types and so on).

**Comment by Ferdi** [comment]
Wow, this was fast, thanks @aliceriot . 

I have a comment on functionality.  The green plus button breaks the pattern - User expects a popup no a menu.  I think the education level should be one of the fields in the popup. 

We can talk more and open a new issue for this    /cc @pdpinch

**Comment by aliceriot** [comment]
Yeah, I agree that it's a little inconsistent. I went with this approach because it required the fewest changes to the existing forms (the popup we show on `/users` is the same as on `/profile/education` currently).
