### ISSUE TITLE
Program letter prints in landscape mode in Chrome on a Mac

### ISSUE THREAD

**Issue by briangrossman** [mitodl/micromasters#5008]
### Steps to Reproduce

- View a program letter on Chrome on a Mac. 
   - E.g. https://micromasters-rc.odl.mit.edu/letter/program/64b3a67f-954b-40f4-9592-937d495e5e60
- Select print to open the print dialog. Note that it tries to print in landscape mode.

Here's how it prints on different Mac browsers. (It has not been tested on Windows.)
- Mac Chrome: landscape
- Mac Safari: portrait
- Mac Firefox: portrait

Ideally, we'd be able to figure out why Chrome is trying to print in landscape mode and adjust the page to ensure it defaults to portrait mode. Additionally, we can look into this CSS: 
- [size attribute](https://developer.mozilla.org/en-US/docs/Web/CSS/@page/size) - `@media print{@page {size: portrait}}`

### Expected Behavior

This page should print in portrait mode.

### Actual Behavior

It prints in landscape mode on Chrome on a Mac.

### Related Issues

#4988

### Screenshot or Screencast

Print dialog
![image](https://user-images.githubusercontent.com/21342568/128564014-941d1124-f577-4b82-ace5-edc1282f7b65.png)

**Comment by umarmughal824** [comment]
@briangrossman I have downloaded the print from chrome and it's in portrait. Could you please elaborate further if it's not the desired behavior? that how it looks like
[MITx MicroMasters.pdf](https://github.com/mitodl/micromasters/files/7934315/MITx.MicroMasters.pdf)

**Comment by briangrossman** [comment]
@umarmughal824 Thanks for looking into this. Based on the margins in the document you attached, it actually looks like it's in landscape mode still. Attached is a PDF generated by Safari on a Mac. You can see the different when you look at the margins. 

[Portrait_MacSafari.pdf](https://github.com/mitodl/micromasters/files/7935681/Portrait_MacSafari.pdf)
 
Here's a video showing the differences on my computer:
https://www.dropbox.com/s/ljzotkl58yofvty/PortraitLandscapePrinting.mov?dl=0
