### ISSUE TITLE
Layout of /learner pages: move program titles to above the program courses

### ISSUE THREAD

**Issue by briangrossman** [mitodl/micromasters#5020]
### Steps to Reproduce

- View the learner page /learner/[username] for a learner enrolled in more than one program
- Note that the program title, course completion graph, and average grade are below the list of courses for that program. They should ideally be above (see image below)

### Expected Behavior

- Program titles would appear above the course list

### Actual Behavior

- Program titles appear below the course list

### Screenshot or Screencast

![Screen Shot 2021-08-24 at 11 20 18 AM](https://user-images.githubusercontent.com/21342568/130646493-b2b1ea55-b286-4ca2-afa3-e535c0c21aeb.png)

**Comment by pdpinch** [comment]
moot
