### ISSUE TITLE
SDS learners can be awarded a completion letter without completing all the requirements

### ISSUE THREAD

**Issue by briangrossman** [mitodl/micromasters#5021]
### Steps to Reproduce

**SDS**
- Learner passes all three core courses:
   - Fundamentals of Statistics (course_id: 28)
   - Machine Learning with Python: from Linear Models to Deep Learning (course_id: 29)
   - Probability - The Science of Uncertainty and Data (course_id: 26)
- Learner passes both elective courses:
   - Data Analysis in Social Science—Assessing Your Knowledge (course_id: 27)
   - Data Analysis: Statistical Modeling and Computation in Applications (course_id: 37)
- Learner does not complete or pass the capstone course:
   - Capstone Exam in Statistics and Data Science (course_id: 30)

### Expected Behavior

**SDS**
Given that the requirements for receiving a completion letter in SDS are:
```
To complete the SDS MicroMasters program, learners will need to take the three core courses and 
one out of two electives. Once learners have passed their four courses, they will then take the 
virtually-proctored Capstone exam to earn the MicroMasters program credential in SDS.
```
the learner should not get a completion letter until they complete the capstone exam. 

### Actual Behavior

The learner receives a completion letter on their dashboard. 

### Additional Information

- There is a problem with the logic to determine if a learner receives the completion letter ([link to code](https://github.com/mitodl/micromasters/blob/83beab9ffba6be34d28f74f1231e94b667a795e9/grades/api.py#L263))
- One option to consider is changing the logic to check if the learner has:
   - completed and passed the `num_required_courses`
   - completed and passed all the core (non-elective) courses
- Here is a BI report to find all false positive SDS program completion letter award recipients ([link](https://bi.odl.mit.edu/queries/1071/source))

**Comment by annagav** [comment]
@briangrossman this bug does not effect DEDP learners since there is different algorithm for them.
