### ISSUE TITLE
MITx Online: Failed to add course enrollment error when creating MITx Online account before Micromasters

### ISSUE THREAD

**Issue by briangrossman** [mitodl/micromasters#5046]
### Steps to Reproduce

- Video here: https://www.dropbox.com/s/drag8a5xxtf7dlk/MITxOnlineFirst.mov?dl=0
- Create MITx Online account at https://rc.mitxonline.mit.edu/
- Create Micromasters account at https://micromasters-rc.odl.mit.edu/
   - Register for edX account
- Register for course that lives on MITx Online
   - Get error: `Failed to add course enrollment` (approximately 4:30 in the video)

### Expected Behavior

- Micromasters would need to recognize I have an MITx Online account and/or give me the opportunity to log in before giving the error

### Actual Behavior

- User receives an error that they failed to enroll in the course

### Related Issues

Possibly related to: #5044

### Screenshot or Screencast

https://www.dropbox.com/s/drag8a5xxtf7dlk/MITxOnlineFirst.mov?dl=0

**Comment by rhysyngsun** [comment]
I think #5047 will fix this

**Comment by rhysyngsun** [comment]
@briangrossman I'm pretty sure this is fixed on RC now, can you verify?

**Comment by briangrossman** [comment]
@rhysyngsun 

I just tested again... now when I registered for DEDP, I was prompted to create an MITx Online account. 

![image](https://user-images.githubusercontent.com/21342568/134244136-6027c39c-1a0a-433b-be56-0e17fdae6560.png)

When I clicked the link, it connected my MITx Online account. 

So... if this is what is expected to happen, then, yup, it's fixed.

**Comment by rhysyngsun** [comment]
Great, closing then.
