### ISSUE TITLE
Financial aid submissions: loses search_query when paging through results

### ISSUE THREAD

**Issue by briangrossman** [mitodl/micromasters#5048]
### Steps to Reproduce

- Access financial aid review page, e.g. /financial_aid/review/2/ 
- Type a search term (e.g. `an`) and click the magnifying glass
- Note how many pages of results are returned
- Click `>` to advance to the next page of results

### Expected Behavior

- User would be taken to the 2nd page of returned results filtered by the search term

### Actual Behavior

- User is taken to the 2nd page of all results. It is no longer filtered by `search_query`. You can confirm by noting that the number of pages is larger than after the search filter was applied (the `y` in  `Page [x] of [y]`)
- Note that the `search_query` querystring parameter is removed from the URL when you click `>` or `<`
- I believe the code is here:

https://github.com/mitodl/micromasters/blob/88db6b61fb2335aaef2dd5c43041923a197e3fa9/financialaid/templates/review_financial_aid.html#L80-L95)

### Screenshot or Screencast

https://www.screencast.com/t/bUBXzapSseaa - Provided by customer support

**Comment by pdpinch** [comment]
I agree this is a bug, but what is the user trying to do in this case? I wonder if we would help the user more if they can quickly filter the results down to one page instead of paging through multiple results.
