### ISSUE TITLE
user has an account and profile, but does not appear in learner search

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#5114]
We have had multiple reports from customer support of users that have accounts, but cannot be found in the learner search. 

When they have alerted us to the issue, we have been able to locate the accounts via the django admin. Running the following code in the django shell will then add the user to the learner search without issue:

```
from search.tasks import index_users 
index_users([user.id],check_if_changed=True)
```

As far as I know, these users should be added to the index as soon as they complete their profile. Why is this failing, especially when running it in the shell corrects the issue immediately? I can't find any relevant errors in sentry.

**Comment by pdpinch** [comment]
I'll share some specific examples in Slack

**Comment by umarmughal824** [comment]
@pdpinch could you please share the examples that you have mentioned here?

**Comment by umarmughal824** [comment]
@pdpinch after exploring the codebase that's what I feel like those users don't have complete profiles. Because this code run only on creating/updating profiles, education, employment, and role. So that seems like those users don't have anything filled out yet that's why they are facing such behavior.

**Comment by umarmughal824** [comment]
@pdpinch I could locally produce it by getting error share below. It says the API allows read-only or delete methods. That normally happens when you hit the elastic search space limit, it converts all indexes mode to read-only or delete. So @blarghmatey could you please confirm that did we ever encountered that space limit?
```
[2021-11-12 13:35:53,062: ERROR/ForkPoolWorker-2] Task search.tasks.index_users[dc73c65a-2202-4fd5-8d63-e32a72590e76] raised unexpected: BulkIndexError('1 document(s) failed to index.', [{'index': {'_index': 'micromasters_b365fa2e86a243339e019f9ec6160159', '_type': '_doc', '_id': '143', 'status': 403, 'error': {'type': 'cluster_block_exception', 'reason': 'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];'}, 'data': {'id': 143, 'user_id': 126, 'profile': {'first_name': 'Umar', 'last_name': 'Asghar', 'preferred_name': 'Umar', 'full_name': 'Umar Asghar', 'romanized_first_name': None, 'romanized_last_name': None, 'image': None, 'image_small': None, 'image_medium': None, 'username': 'umaryope', 'filled_out': False, 'account_privacy': 'public_to_mm', 'country': 'PK', 'state_or_territory': 'PK-PB', 'city': 'Lahore', 'birth_country': 'PK', 'work_history': []}, 'program': {'id': 2, 'enrollments': [], 'courses': [], 'is_learner': True, 'total_courses': 3, 'course_runs': []}}}}])

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 385, in trace_task

    R = retval = fun(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 648, in __protected_call__

    return self.run(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner

    reraise(*exc_info)

  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 54, in reraise

    raise value

  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner

    return f(*args, **kwargs)

  File "/src/search/tasks.py", line 109, in index_users

    _index_program_enrolled_users(enrollments)

  File "/src/search/indexing_api.py", line 426, in index_program_enrolled_users

    _index_chunks(

  File "/src/search/indexing_api.py", line 280, in _index_chunks

    count += _index_chunk(chunk, index=index)

  File "/src/search/indexing_api.py", line 247, in _index_chunk

    insert_count, errors = bulk(

  File "/usr/local/lib/python3.9/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk

    for ok, item in streaming_bulk(client, actions, *args, **kwargs):

  File "/usr/local/lib/python3.9/site-packages/elasticsearch/helpers/__init__.py", line 188, in streaming_bulk

    for data, (ok, info) in zip(

  File "/usr/local/lib/python3.9/site-packages/elasticsearch/helpers/__init__.py", line 137, in _process_bulk_chunk

    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)

elasticsearch.helpers.BulkIndexError: ('1 document(s) failed to index.', [{'index': {'_index': 'micromasters_b365fa2e86a243339e019f9ec6160159', '_type': '_doc', '_id': '143', 'status': 403, 'error': {'type': 'cluster_block_exception', 'reason': 'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];'}, 'data': {'id': 143, 'user_id': 126, 'profile': {'first_name': 'Umar', 'last_name': 'Asghar', 'preferred_name': 'Umar', 'full_name': 'Umar Asghar', 'romanized_first_name': None, 'romanized_last_name': None, 'image': None, 'image_small': None, 'image_medium': None, 'username': 'umaryope', 'filled_out': False, 'account_privacy': 'public_to_mm', 'country': 'PK', 'state_or_territory': 'PK-PB', 'city': 'Lahore', 'birth_country': 'PK', 'work_history': []}, 'program': {'id': 2, 'enrollments': [], 'courses': [], 'is_learner': True, 'total_courses': 3, 'course_runs': []}}}}])
```

**Comment by pdpinch** [comment]
As far as I know, we haven't seen that particular exception, `BulkIndexError`

But we have seen this error, on Prod and RC: https://sentry.io/organizations/mit-office-of-digital-learning/issues/2474373743/?project=104497&query=is%3Aunresolved+ForkPoolWorker&statsPeriod=14d 

Could it be related?

**Comment by umarmughal824** [comment]
@pdpinch I have tried to created about 8 - 10 users both on rc and local. But I am unable to produce the error after fixing the spacing issue locally. I didn't find any sentry error either.

On completeing profile, I could see that everything is working fine both on rc and local. Here is what it returns everytime.

Thanks @pdpinch Now it seems like the etastic search process exited as you have pointed out in the last comment. @blarghmatey could answer it better that [it's](https://sentry.io/organizations/mit-office-of-digital-learning/issues/2474373743/?project=104497&query=is%3Aunresolved+ForkPoolWorker&statsPeriod=14d) happening. I don't see any other issue but only that one.

```
[2021-11-15 11:28:12,289: INFO/ForkPoolWorker-2] Task search.tasks.index_users[72e4f13d-7557-4968-9bff-afcd2e74e8e5] succeeded in 0.5592306999988068s: None
```

**Comment by umarmughal824** [comment]
@blarghmatey do you know why the celery process gets exited. I am talking about it

https://sentry.io/organizations/mit-office-of-digital-learning/issues/2474373743/?project=104497&query=is%3Aunresolved+ForkPoolWorker&statsPeriod=14d

**Comment by blarghmatey** [comment]
That's probably because of Heroku restarting the process which it will do on at least a daily basis.

**Comment by umarmughal824** [comment]
> That's probably because of Heroku restarting the process which it will do on at least a daily basis.

@pdpinch that's why we are getting that issue as long as it could not see any other error after testing it multiple times both on local and rc.

**Comment by umarmughal824** [comment]
I have found another error in sentry that could be the cause of it too. I will take a look at it tomorrow

**Comment by umarmughal824** [comment]
These two sentry errors are not showing on production and even on RC was produced weeks ago so I could produce it only while running script manually through the shell, we are passing the wrong type of data that triggers such issues. There is no way it could produce in the codebase.

And I also search about process exiting that's what they says the tasks will be lost 
https://docs.celeryproject.org/en/stable/userguide/workers.html#stopping-the-worker
```When shutdown is initiated the worker will finish all currently executing tasks before it actually terminates. If these tasks are important, you should wait for it to finish before doing anything drastic, like sending the KILL signal.
```

**Comment by umarmughal824** [comment]
@blarghmatey are we using heroku for production or we are using AWS for that? If we are using AWS, could we expect such process exits as heroku?

**Comment by pdpinch** [comment]
We use Heroku in production for this site.

**Comment by pdpinch** [comment]
Do we need to set something up so unfinished jobs are started again when the worker restarts?

> That's probably because of Heroku restarting the process which it will do on at least a daily basis.

**Comment by pdpinch** [comment]
We have MicroMasters exams coming up right after the holiday break. I don't want to make these changes until after the exams get started. 

I'd also like to get a second opinion from @rhysyngsun or @annagav but that can wait until January.

**Comment by rhysyngsun** [comment]
It's probably best to apply `@app.task(asks_late=True)` to the relevant task instead of setting it globally for now, unless we have the bandwidth to verify there's no undesired side effects in other areas.

**Comment by umarmughal824** [comment]
@rhysyngsun Sure, I am gonna apply it to that specific task for now but as per @blarghmatey saying, Heroku restarts the process at least once a day so there is a chance of losing other tasks too.
