### ISSUE TITLE
Environment Configuration for Sentry webpack Plugin 

### ISSUE THREAD

**Issue by Wassaf-Shahzad** [mitodl/micromasters#5123]
#### Summary

- `SENTRY_AUTH_TOKEN` - Sentry Auth Token at organisation level
- `SENTRY_ORG_NAME` - Organisation Name as described in sentry 
- `SENTRY_PROJECT_NAME` - Project Name as described in sentry ( micromasters )  
- `SENTRY_RELEASE` - Release Number should match the release number passed in sentry init call 

These values need to be set in heroku during build.

#### Applicable Environments

- [ ] Apply configuration to CI
- [x] Apply configuration to RC
- [x] Apply configuration to Production

**Comment by mbertrand** [comment]
@Wassaf-Shahzad it looks like `SENTRY_RELEASE` [is assigned automatically from the code](https://github.com/mitodl/micromasters/pull/5118/files#diff-42d5e2ccb416109ce0d9871c69f34e5fd46ee67de5d07a6e9b512cdc37cac976R18-R67), is that right?  

Does `SENTRY_AUTH_TOKEN` have to be generated/obtained by devops (@shaidar)?  Ditto `SENTRY_ORG_NAME` and `SENTRY_ORG_NAME` ?

**Comment by Wassaf-Shahzad** [comment]
> @Wassaf-Shahzad it looks like `SENTRY_RELEASE` [is assigned automatically from the code](https://github.com/mitodl/micromasters/pull/5118/files#diff-42d5e2ccb416109ce0d9871c69f34e5fd46ee67de5d07a6e9b512cdc37cac976R18-R67), is that right?
> 
> Does `SENTRY_AUTH_TOKEN` have to be generated/obtained by devops (@shaidar)? Ditto `SENTRY_ORG_NAME` and `SENTRY_PROJECT_NAME` ?

Yes the release is automatically read.The auth pro can be generated from sentry but it would be best to get  @shaidar input on this.
Also the ORG and PROJECT name need to be the same as given in sentry.
