### ISSUE TITLE
Temporarily put automated dashboard updates on hold

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#5133]
On a regular basis, multiple times a day, we update the cached edX data for all users. These tasks can interfere with other scheduled tasks, like finalizing grades and created exam authorizations. 

We should put the dashboard update tasks on hold during the week of 12/20 to focus our resources on final grade updates and exam authorizations.

### acceptance criteria

- [ ] Two PRs: one to remove the task(s) and one to add them back. The 2nd PR should include notes about the timing and criteria for merging it.

**Comment by annagav** [comment]
I don't think we need to remove it, I think it easier to set it to a different schedule, and then just revert that PR later.
