### ISSUE TITLE
broken link to MITx Online Dashboard

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#5134]
### Steps to Reproduce

1. Log in to RC
2. Authorize yourself for the 14.750x exam:
   1. link your account to rc.mitxonline.mit.edu
   2. enroll in 14.750x
   3. pay for 14.750x (if you have trouble with the test Visa account on CyberSource, I found success by using the admin to change the status of my order to `fulfilled`)
   3. using the admin, create a passing grade for yourself
   4. you should be authorized for the exam now
3. Load the dashboard
4. You should see the message "you can access your exam through your MITx Online Dashboad"
5. click the link

### Expected Behavior

- Browser navigates to the mixonline dashboard. For RC this would be at rc.mitxonline.mit.edu/dashboard/
 
### Actual Behavior

- browser navigates to /courses on open edX, a page this is blank (by design) 

If it requires a lot of effort (like, adding yet another setting) to make this link work, I suggest keeping things simple. Just remove the anchor tag and leave the text. This message was originally added to compensate for the fact that the prior link, to register for the course, was single use only. Since that's no longer the case, we don't really need this link any more.

**Comment by pdpinch** [comment]
Here is the relevant code: https://github.com/mitodl/micromasters/blob/c2965d691a91616a6d2a0af7ae19ab0a08e1f169/static/js/components/dashboard/courses/StatusMessages.js#L318

Configuring the dev environment to duplicate these conditions is will take much longer than the code modification. In the interests of time, I think it's OK to merge this change and we will test it on RC.

**Comment by umarmughal824** [comment]
@pdpinch After performing all the steps mentioned in the PR description, I found out that we have set up the environment variable `MITXONLINE_BASE_URL` to `https://courses-qa.mitxonline.mit.edu/`. But that should be set to `https://rc.mitxonline.mit.edu/` and for the dashboard link, I have created the PR.
