### ISSUE TITLE
edx related functions, having common use case, can be moved to openedx app in ol-django.

### ISSUE THREAD

**Issue by MAbdurrehman12** [mitodl/micromasters#5139]
It was observed that there are some edx related functions implemented and used in mitxonline, micromasters etc. Since some of these functions seems to have a common use case and it is possible that a function defined in one app can be required in some other app. So in order to avoid code duplication, an app named "openedx" is being created in ol-django in this PR: https://github.com/mitodl/ol-django/pull/48. The purpose of this app is to have edx related functions with common use case, hence those functions can be reused in several apps, wherever required. 

Micromasters also seems to have some functions here: https://github.com/mitodl/micromasters/blob/master/courses/utils.py which can be moved to ol-django. So the purpose of this ticket is to identify and decide which functions in micromasters are common and can be moved to ol-django.

**Comment by MAbdurrehman12** [comment]
@pdpinch Is this something we need to do and prioritise or we can do it later on?

**Comment by pdpinch** [comment]
I consider this tech debt, which should be taken up when there's down-time, or when someone is working on relevant code.

**Comment by MAbdurrehman12** [comment]
Not sure if this is something we need to do or not. So I'm closing this issue for now, and if we need to work on it, we can reopen it later on.
