### ISSUE TITLE
Investigate react-virtualized to fix AutoComplete performance issues

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#515]
https://github.com/bvaughn/react-virtualized

This is used in https://github.com/bvaughn/react-virtualized-select to render only a portion of the option list for react-select. I'm wondering if we can do the same thing for AutoComplete

**Comment by Ferdi** [comment]
Looks good. Can we reuse it easily ?

**Comment by noisecapella** [comment]
I'm not sure. I feel like it would be reasonably quick to try it out and see if it works, but if there are problems we might not easily work around them given the complexity of the material-ui components
