### ISSUE TITLE
Discovery: replace Elasticsearch with OpenSearch

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#5155]
Elasticsearch 6.7 has passed it's end of life. Instead of upgrading elasticsearch, we would like to switch to a hosted opensearch service.

AWS OpenSearch is broadly compatible with elasticsearch 7.10

#### Acceptance Criteria:

- [ ] investigate what changes are necessary to switch from elasticesearch to OpenSearch
- [ ] create a branch for OpenSearch testing 
- [ ] add an OpenSearch image to the local dev env
- [ ] test indexing
- [ ] test the learner search feature / searchkit integration 
- [ ] test the percolate feature that controls email campaigns and subscriptions in open-discussions

**Comment by asadiqbal08** [comment]
Referring to this [ReadMe guide](https://github.com/mitodl/micromasters#elasticsearch), Anyone can point me out the possible values for local setup ?

**Comment by asadiqbal08** [comment]
As a prototype, I created a [WIP PR](https://github.com/mitodl/micromasters/pull/5166) for getting feedback or any input. 

While working on the PR, I figured out that [mitodl/django-server-status](https://github.com/mitodl/django-server-status/blob/v0.5.0/requirements.txt) is pinned to 0.5.0 in `micromaster` and utilizing the `elasticsearch` in it but the latest version of [mitodl/django-server-status](https://github.com/mitodl/django-server-status/blob/v0.7.3/requirements.txt) has an empty `requirements.txt` but the view is using a third party [OpenSSL.crypto](https://github.com/mitodl/django-server-status/blob/v0.7.3/server_status/views.py#L14) library that is missing while installation. 

Is that [repo](https://github.com/mitodl/django-server-status) required any changes related to openssl library ?


Secondly, the [test_requirements.txt](https://github.com/mitodl/django-server-status/blob/v0.7.3/test_requirements.txt) has references of elasticsearch. Did this repo also need some updation ?

**Comment by pdpinch** [comment]
Not sure I understand all the issues here, but I recommend opening a separate issue just to update mitodl/django-server-status. If that means you need to leave the elasticsearch testing endpoint for now, I'm fine with that.

**Comment by pdpinch** [comment]
When we replace ElasticSearch with OpenSearch we can also just remove ELASTIC_SEARCH from https://github.com/mitodl/micromasters/blob/1821465874a741699e7025ae5d078f624fbac0dc/micromasters/settings.py#L430
