### ISSUE TITLE
"View on MITx Online" links on dashboard are broken

### ISSUE THREAD

**Issue by briangrossman** [mitodl/micromasters#5164]
### Steps to Reproduce

- Log in to MM as a user who is enrolled in (or has been enrolled in a MM course that is hosted on MITx Online
- View your MM dashboard: https://micromasters.mit.edu/dashboard/
- Click on the link for a course that says `View on MITx Online` (see image below)

### Expected Behavior

- It will take you directly to the course on edX on MITx Online 
   - e.g. `https://courses.mitxonline.mit.edu/learn/course/course-v1:MITxT+14.310x+1T2022`

### Actual Behavior

- It takes you to this link: `https://mitxonline.mit.edu/dashboard/course-v1:MITxT+14.310x+1T2022`

### Related Issues

- https://github.com/mitodl/micromasters/issues/4993
- https://github.com/mitodl/micromasters/issues/5134 - pay careful attention to this one as it looks like this is what may have broken this link. Ensure that your fix doesn't recreated this issue.

### Screenshot or Screencast

![Screen Shot 2022-02-03 at 2 07 23 PM](https://user-images.githubusercontent.com/21342568/152416201-2dd4bf68-7590-45e3-9409-38603d6efb16.png)

**Comment by pdpinch** [comment]
When we open a PR for this, can we add some tests to avoid another regression?

**Comment by briangrossman** [comment]
@umarmughal824 I don't know of any specific documentation on the integration, but my hope is that by reviewing the past issues / PR's, you'll be able to get the information you need:

- https://github.com/mitodl/micromasters/issues/4993
- https://github.com/mitodl/micromasters/issues/5134
- https://github.com/mitodl/micromasters/pull/5016

Something to note is that this used to be working, but was broken at some point, possibly with this: https://github.com/mitodl/micromasters/pull/5136. You'll need to make sure that any change you make doesn't end up reverting anything fixed by: https://github.com/mitodl/micromasters/pull/5136.

At a high level, these links should point to the correct location for MITx Online courses:
- `https://courses.mitxonline.mit.edu/learn/course/[course id]`

**Comment by umarmughal824** [comment]
> @umarmughal824 I don't know of any specific documentation on the integration, but my hope is that by reviewing the past issues / PR's, you'll be able to get the information you need:
> 
> * [MITx Online Integration: Update frontend links to courseware backends #4993](https://github.com/mitodl/micromasters/issues/4993)
> * [broken link to MITx Online Dashboard #5134](https://github.com/mitodl/micromasters/issues/5134)
> * [Update dashboard links #5016](https://github.com/mitodl/micromasters/pull/5016)
> 
> Something to note is that this used to be working, but was broken at some point, possibly with this: #5136. You'll need to make sure that any change you make doesn't end up reverting anything fixed by: #5136.
> 
> At a high level, these links should point to the correct location for MITx Online courses:
> 
> * `https://courses.mitxonline.mit.edu/learn/course/[course id]`

@briangrossman this was the requirement that it should point to mix online rather the open edx. See that 
```
Expected Behavior
Browser navigates to the mixonline dashboard. For RC this would be at rc.mitxonline.mit.edu/dashboard/
Actual Behavior
browser navigates to /courses on open edX, a page this is blank (by design)
```

So I am confused about what it should point to? I mean don't we need that specific ticket requirement anymore? Please let me know

**Comment by briangrossman** [comment]
@umarmughal824 

I just looked at https://github.com/mitodl/micromasters/issues/5134. I see how this is confusing. 

Here's an image that should clarify things (I hope):
![Screen Shot 2022-02-11 at 10 42 20 AM](https://user-images.githubusercontent.com/21342568/153622711-43b6b5ef-a9c9-4e64-889b-07ed4b0e96b5.png)

**Link 1**

This is the link that is currently broken and described above in this issue description. When a course is in progress on MITx Online, learners can link directly to the course from the Micromasters dashboard using this link. 

- It currently points to `https://mitxonline.mit.edu/dashboard/[course_id]` (e.g. `https://mitxonline.mit.edu/dashboard/course-v1:MITxT+14.310x+1T2022`)
- ... but should point to `https://courses.mitxonline.mit.edu/learn/course/[course_id]` (e.g. `https://courses.mitxonline.mit.edu/learn/course/course-v1:MITxT+14.310x+1T2022`)

**Link 2**

This is the link that was fixed on: https://github.com/mitodl/micromasters/issues/5134 


It appears as though the work done to fix https://github.com/mitodl/micromasters/issues/5134 is what broke this functionality. This may require the two links using two different values to form the URLs. 

Let me know if you have additional questions.

**Comment by annagav** [comment]
@umarmughal824 does the PR you opened correct link 2 as well? Am I understanding correctly?
