### ISSUE TITLE
/learner pages: show authorizations for exams on /learner pages

### ISSUE THREAD

**Issue by briangrossman** [mitodl/micromasters#5173]
As a member of the customer support or course teams, it would be helpful to know whether or not a learner is authorized to take an exam. This information is not currently available on the /learner pages. Learners are frequently asking customer support for this information. Customer support, in turn, requests the information from engineering. 

#### Related Issues

According to these related issues, it looks like this functionality was actually implemented at some point:
- https://github.com/mitodl/micromasters/issues/3722
- https://github.com/mitodl/micromasters/pull/3792

#### Acceptance Criteria:

- [ ] Update the /learner pages to indicate if the learner is authorized to take the exam
- [ ] Ensure that this works for learners who have already taken the exam (passed or failed), as well as learners currently enrolled in the course, and still have an authorization(s) remaining

#### Designs and Mockups

The learner's dashboard shows that they are authorized to take the Microeconomics exam (note that is no Pay Now button)
![image](https://user-images.githubusercontent.com/21342568/154770345-5711278c-4a7f-4a89-a56a-522aa3a6f5be.png)

... but their /learner page doesn't indicate that they are authorized to take the exam
![image](https://user-images.githubusercontent.com/21342568/154770442-a020913c-a4f7-4e12-a8d8-66c09af68361.png)

---

The learner's dashboard shows that they are authorized to take the Data Analysis for Social Scientists exam (note that is no Pay Now button and it says 'You can register to take the exam...'). They failed the exam, but purchased another authorization.
![image](https://user-images.githubusercontent.com/21342568/154769523-04b2f478-1edf-4800-a866-14c33f4ed32b.png)

... but the /learner page for this learner shows no indication of whether the learner is authorized to take the exam. 
![image](https://user-images.githubusercontent.com/21342568/154769482-ecbe8934-3086-4691-9fda-a1af39670104.png)

**Comment by umarmughal824** [comment]
@briangrossman As per my understanding, it does not load any course for learner profile but only for staff users who load a learner profile that shows all the details of courses, grades, etc. So as per my understanding, it was never added for the staff learners profile view.

**Comment by briangrossman** [comment]
@umarmughal824 

Your assumptions are mostly correct. This is, indeed, a feature specifically for staff users. We want staff, particularly customer support, to be able to determine how many authorizations a learner has left for a given course. 

The use case is something like this:
- a learner believes they should have an authorization to take an exam, but their dashboard is asking them to pay
- the learner contacts customer support to confirm if they have  authorizations
- the customer support team wants to be able to confirm if the learner has authorizations using their /learner page

The customer support team is currently able to determine if the learner has paid, but they are not able to accurately determine if the learner has an authorization remaining. There is also some complexity as earlier purchases allowed for two authorizations, but they are now for one authorization only. 

I will connect with you offline about this issue.

**Comment by pdpinch** [comment]
This will be moot after we migrate ecommerce to mitxonline
