### ISSUE TITLE
Allow CMS user to change program thumbnail on homepage

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#518]
As a course staff, I want to use an image or video to promote my program on the MicroMaster's home page. 

Since this is a promotional video, we can use YouTube and the YouTube player, provided we can make it fit the layout and captions work properly. 

If YouTube doesn't work, we can use the same player we used on the mitili site.

**Comment by pdpinch** [comment]
We'll also need an option for the CMS user to choose whether the video or the image will be used. 

If no image is chosen, we can default to a scaled version of the hero image from the program page.

**Comment by noisecapella** [comment]
What's the expected size of the thumbnail? Should I just make a guess based on the width/height of the box? There's nothing which enforces specific pixel dimensions

**Comment by pdpinch** [comment]
Adding @roberthouse54 to this conversation, in case he has a contrary view. 

I'd like these thumbnails to be similar to the edX course thumbnail, so minimum of 378x225. Anything larger should be at the same aspect ratio. Does that work with the current layout?

ref: https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/named-release-cypress/building_course/setting_up_student_view.html#add-a-course-image

**Comment by roberthouse54** [comment]
Yes, let's stay consistent with the size of the EDx course thumbnail, so the image should be 378 x 225.

**Comment by roberthouse54** [comment]
Actually... thinking more about this. I feel we should maybe break this into separate issues. 1. Allow users to change the thumbnail image for a program. 2. Allow users to post Videos to the Program page.

I do not really think that we should be agnostic about whether the program can be represented either by a thumbnail OR a video. I think that what the CMS user really wants is more control. They probably want to be able to add a video to the program page. Biut it should not be the thumnail. So I'd rather break out the "Add a Video to the Program page" as a separate issue.

**Comment by noisecapella** [comment]
Should we shrink the boxes on the homepage to this size as well? Currently the boxes just take up approx half of the width so that there are two boxes per row

**Comment by pdpinch** [comment]
I update the title to remove the mention of homepage video

**Comment by roberthouse54** [comment]
I think maybe the best solution for the time being is just to do nothing. We should make sure that the image maintains the aspect ratio, but it can scale to fill whatever width the box has, and it should look ok. We will have to fix this in a more real way pretty soon, but we are probably going to want to redo the whole layout framework eventually.
