### ISSUE TITLE
Exams: Don't use any of `Honor` or `Audit` enrollment modes for enrollments

### ISSUE THREAD

**Issue by arslanashraf7** [mitodl/micromasters#5193]
### Steps to Reproduce
- Setup the latest edx Devstack or visit https://courses-qa.mitxonline.mit.edu/
- Enroll in [this test course](https://courses-qa.mitxonline.mit.edu/learn/course/course-v1:Arbisoft+ATC__ARB_0001+1/home)
- Start the course and visit any of the units in this course
- You will see `You do not have access to proctored exams with your current enrollment.` error message (Ref Screenshot below)

### Expected Behavior
- The user is able to visit protored exams without any issues or permission error messages

### Actual Behavior
- Upon visiting a proctored exam the user sees `You do not have access to proctored exams with your current enrollment.` error message

### Related Issues
There have been some updates in the proctoring access with respect to the enrollment mode of the user in the course. With those updates a user enrolled with `Audit/Honor` mode is now unable to access the proctored exam.

For more details take a look at below:
- [Jira ticket that discusses why this change was needed](https://openedx.atlassian.net/browse/MST-1273)
- [PR that updates the proctoring access in edx-platform](https://github.com/openedx/edx-platform/pull/29929)
- [PR that updates the Learning MFE to handle proctored access based on enrollment track](https://github.com/openedx/frontend-app-learning/pull/831)

### Possible Resolution:
- We might need to update our enrollment API client to enroll with course modes other than `Honor` and `Audit`
- We need to choose which mode to use moving onwards, [This available list of modes](https://github.com/openedx/edx-platform/blob/master/common/djangoapps/course_modes/models.py#L131-L142)
- I believe the relevant code in [MicroMasters is here](https://github.com/mitodl/micromasters/blob/master/ecommerce/api.py#L324)
- I believe, The relevant code in the [edx-api-client is here](https://github.com/mitodl/edx-api-client/blob/master/edx_api/enrollments/__init__.py#L163-L178)

### Screenshot or Screencast
<img width="1680" alt="Screenshot 2022-04-11 at 8 30 02 PM" src="https://user-images.githubusercontent.com/34372316/162776401-253bf4fa-7106-4397-a5c5-a3a2218b1e9c.png">

**Comment by pdpinch** [comment]
To be clear, this is only an issue for enrollments in exam courses, which only applies to FA / DEDP courses.

**Comment by annagav** [comment]
@arslanashraf7 here is where we enroll the user in an exam run : https://github.com/mitodl/micromasters/blob/master/dashboard/views.py#L200

What happens here is we create an exam enrollment for the user in a given exam run, when the user gets that option on the dashboard to enroll in the exam run(that means they were eligible, paid, have passing grade for the course, and scheduling perion is present). [Here ](https://github.com/mitodl/micromasters/blob/master/dashboard/views.py#L194) we use staff credentials to create the user enrollment in the course and not the users credentials.

But this function is used in a variety of places: in the course enrollment view, ecommerce api( the place you pointed out), and exam enrollment view. 

Let me know if there is anything I can clarify.

**Comment by arslanashraf7** [comment]
@annagav Thanks for adding these details.

@pdpinch In addition to the above, we also need to decide which enrollment track we are going to use instead of `Audit`. [These modes](https://github.com/openedx/edx-platform/blob/master/common/djangoapps/course_modes/models.py#L131-L142) are currently available in edX.

Also just to note, In my opinion changing the enrollment track might have a significant impact on the user experience within the edX. The impact would mostly be related to the courseware access, certificate, and probably payment. So, we need to consider these before selecting an enrollment track to enroll the users.

**Comment by arslanashraf7** [comment]
@annagav 
>[Here ](https://github.com/mitodl/micromasters/blob/master/dashboard/views.py#L194)we use staff credentials to create the user enrollment in the course and not the users credentials.

Can you confirm why we use we are using staff credentials at some points and the user's own credentials on other?

As you mentioned, [Here we use Staff credentials](https://github.com/mitodl/micromasters/blob/master/dashboard/views.py#L194)
[Here in the dashboard we are using self credentials](https://github.com/mitodl/micromasters/blob/master/dashboard/views.py#L112)
[Here in eCommerce we are using self credentials](https://github.com/mitodl/micromasters/blob/master/ecommerce/api.py#L324)

In addition, I'm asking this because creating enrollment with a mode such as `Verified` will require a staff API key/Access Token, unlike `Audit` enrollments.

@pdpinch FYI.

**Comment by annagav** [comment]
@arslanashraf7 We were using staff credentials because the exam course was going to be by invitation only, but I am not entirely sure on all the reasons, all we had some trouble with getting it to work. Maybe @rhysyngsun would have more insight into the reasons, and whether it is still important to enroll using staff credentials.
