### ISSUE TITLE
Student dashboard: UI for View courses and course enrollments

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#52]
As a student, I need to be able to see which courses are included in my micromasters programs, and understand whether I'm enrolled. 

The list of courses in a particular MM program are available from the MM API. Student enrollments are available from the edX enrollment API. The enrollment API returns a list of the courses the student is enrolled in and whether she is ID verified. 

This story covers display the list of courses, links to the course home page (aka tab) and an indicator as to whether the student is enrolled, enrolled & verified or not enrolled.

**Comment by jamiefolsom** [comment]
Note: there should be a row below the listing of all courses for the "final exam"; this is some kind of proctored, rigorous capstone that users need to pass.

The specifics haven't been determined yet, but we need to signal to users that it exists and make sure we account for it in our program model.

**Comment by jamiefolsom** [comment]
Also, to accommodate a growing list of programs, each with a list of courses, we should consider an interface like the bootstrap collapsible accordion:

![accordion](https://cloud.githubusercontent.com/assets/882377/13750845/a3aba2e6-e9dd-11e5-9cdb-70945178b15d.gif)

**Comment by pdpinch** [comment]
@annagav @noisecapella did #90 address this, or is there more work to be done on the enrollments part?

If so, I'm inclined to close this and create a new issue just for the enrollments work.

**Comment by noisecapella** [comment]
Yes, more work to be done for enrollments.
