### ISSUE TITLE
restore the link to the program record for DEDP

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#5227]
### acceptance criteria

- [ ] only for DEDP
- [ ]  The program record link can be conditional on the existence of combined final grades.

**Comment by pdpinch** [comment]
@annagav I'm seeing this for some users, but not all. What is the condition(s) for when the link gets displayed?

**Comment by annagav** [comment]
Could you provide an example user foe whom this doesn't work?

**Comment by pdpinch** [comment]
See https://odl.zendesk.com/agent/tickets/135560

**Comment by pdpinch** [comment]
Oh wait. That's different. Sorry.

**Comment by pdpinch** [comment]
There's no link for my user.

**Comment by pdpinch** [comment]
And there's no link for the user in https://odl.zendesk.com/agent/tickets/135615
