### ISSUE TITLE
code review for anything conditional on the financial aid setting

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#5229]
We are planning to turn off the financial aid setting for the DEDP program on 10/8 and direct users to request financial assistance on mitxonline.mit.edu 

There is a lot of code that is conditional on the "Financial aid availability" setting. We should inventory it in this epic, and then we can decide what needs to be changed, and in what order.

**Comment by annagav** [comment]
I looked through the code one more time to check for the proper usages of the financial aid flag on the program, and I think this issue could be closed.
