### ISSUE TITLE
List of users who have paid, but have not yet passed a course

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#5235]
As a user who has paid for DEDP course, I need a discount/enrollment code for mitxonline, so I can enroll as verified and take a proctored exam. 

This is similar to https://github.com/mitodl/mitxonline/issues/961 but on that issue we limited the list to users who were authorized. This omitted anyone who had not yet passed the course. 

#### Acceptance Criteria:

- [ ] csv of username, email, course key

#### related issues

- use this list as an input for creating discount codes in mitxonline

**Comment by arslanashraf7** [comment]
I was looking around and it looks like @annagav might already have created a command that pretty much does the same and doesn't take exam authorizations into account for identifying upgradable users. That command is [list_currently_enrolled_paid](https://github.com/mitodl/micromasters/blob/master/exams/management/commands/list_currently_enrolled_paid.py). Is this exactly what we need? @annagav what's your opinion on this?

**Comment by annagav** [comment]
@pdpinch as I am understanding, the previous command where we were picking authorized users, is a subset of all users that paid and haven't used their attempt. So it will be one list of all users paid, and need a coupon.

**Comment by annagav** [comment]
This is not completed yet.
