### ISSUE TITLE
MM legacy: validate program letters, disable incorrect ones

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#5248]
A user alerted us that they were seeing a program letter for a program that they had not completed. Normally, these letters are only offered on program completion. See https://odl.zendesk.com/agent/tickets/140048

After investigating, I confirmed a large number of such letters had been generated, almost all of them on the same day (on a date before the program had even started)

We need a clean, safe and reliable way to validate existing program letters (`MicromastersProgramCommendation`) and disable (or delete) any that were mistakenly created. 

#### Acceptance Criteria:

- [x] Take a look a the state of the code and the production data, and propose a way to clean this up

**Comment by arslanashraf7** [comment]
I did some initial analysis on this and here are the details:

**_MicromastersProgramCommendation creation attempt paths:_** 
1. Create through a command [generate_program_letter.py](https://github.com/mitodl/micromasters/blob/master/grades/management/commands/generate_program_letter.py). I believe we didn't run this.
2. In signals, when a [MM Program certificate is created](https://github.com/mitodl/micromasters/blob/master/grades/signals.py#L30). Whenever a program certificate is created for a user we would attempt to create a Program Letter.
3. In signals, When a [FinalGrade entry is created](https://github.com/mitodl/micromasters/blob/master/grades/signals.py#L43-L44) and the program associated with that course doesn't have financial Aid enabled.


**_Preconditions when a Program Letter creation is attempted:_** 

1. If the program has [FinancialAid enabled and also the user has a MMProgramCertificate](https://github.com/mitodl/micromasters/blob/53e17fd5e7857924817eeeed7e74d98a2ce9ede6/grades/api.py#L286-L287) it would create the ProgramLetter.
2. If condition in point#1 doesn't meet we just check if the[ user has completed the program](https://github.com/mitodl/micromasters/blob/53e17fd5e7857924817eeeed7e74d98a2ce9ede6/grades/api.py#L290-L291) and we generate the letter.

I suspect this might have started happening when we switched off the FinancialAid for DEDP.

**Comment by pdpinch** [comment]
In my review, I found ~1000 program letters created for program id=5 on 12/19/2019, even though there were no certificates granted in any of that program's courses until 2020. 

> 2. If condition in point#1 doesn't meet we just check if the[ user has completed the program](https://github.com/mitodl/micromasters/blob/53e17fd5e7857924817eeeed7e74d98a2ce9ede6/grades/api.py#L290-L291) and we generate the letter.

If we test these program letters to see if the user has completed the program, what do we get?

**Comment by arslanashraf7** [comment]
>If we test these program letters to see if the user has completed the program, what do we get?

You are correct, Testing these letters against the program completion shows many that don't have the program completed.

I was able to get the stats that might help us conclude the analysis. I've shared those with you in Slack.

**Comment by pdpinch** [comment]
Ok. I think we need to split this into a few separate issues: 

- [ ] Revoke erroneous program letters
- [ ] Audit views of erroneous program letters
- [ ] RCA erroneous program letters created on 12/19/2019
- [ ] RCA erroneous program letters created after 12/19/2019

**Comment by pdpinch** [comment]
I neglected to mention that the FIN team (program id=5) has removed their program letter from the CMS for now, which blocks all access to letters while we resolve this. 

There are still 3 letters that are not program id=5 that need to be reviewed and revoked.
