### ISSUE TITLE
Legacy MM: Audit views of erroneous program letters

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#5251]
The course team would like to know a few things about the erroneous program letters:

1. When were they available for viewing? It seems like the records were created well before the letter was added to the CMS.
2. Were they viewed? We capture pages views in Google Analytics

part of #5248 

#### Acceptance Criteria:

- [x] Confirm that letters cannot be viewed when the letter template does not exist in the CMS
- [x] Identify when the letter template for program id=5 was created. 
- [ ] Compare GA page view data to the list of erroneous program letters 

#### Relates issues

- RCA erroneous program letters created on 12/19/2019
- RCA erroneous program letters created after 12/19/2019

**Comment by pdpinch** [comment]
Looking at the wagtail history UI, I believe the program letter template for program 5 was created sometime in February 2022. Can we confirm that by looking through the wagtail version history?

**Comment by pdpinch** [comment]
You can contact me for a dump of the GA page view data. @arslanashraf7 and I have a list of the erroneous program letters.

**Comment by arslanashraf7** [comment]
>When were they available for viewing? It seems like the records were created well before the letter was added to the CMS.

They should have been available for viewing when the template was added for the program which is Feb 16, 2022.

>Were they viewed? We capture pages views in Google Analytics

Can I get the Analytics data to check how many were viewed?

**Comment by pdpinch** [comment]
> Can I get the Analytics data to check how many were viewed?

I [dumped this from Google Analytics](https://drive.google.com/file/d/1f7hv3SOLinZfb8_Np_Trfv3HwML5u7Nr/view?usp=share_link). I can give you access to the analytics account if you think that would be more helpful.
