### ISSUE TITLE
Update 3T2022 DEDP certificates and grades in MicroMasters

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#5275]
Legacy DEDP courses have separate grades for the online course, exam, and combined final grade. As of 3T2022, the online course and exam are combined into one grade, which is the same as the combined final grade. 

However, in 3T2022, the combined final grade and its passing status does not reflect the requirement that the learner pass the final exam. Some one-off adjustments will be necessary. 

#### Acceptance Criteria:

- [ ] Come up with a plan to import and migrate the necessary data to provide passing status, certificates, and a correct learner record for learners who took the 3T2022 exams. 
- [ ] Update this PR description with the plan.

#### related issues:

-  https://github.com/mitodl/mitxonline/issues/1315

**Comment by pdpinch** [comment]
I believe if we freeze the grades as is, we will have a correct course grade and combined final grade. However, the passing status will not be correct due to the issue outlined in https://github.com/mitodl/mitxonline/issues/1315

**Comment by pdpinch** [comment]
We can write a management command to import the combined final grades and passing status.

**Comment by annagav** [comment]
There are two different issues here:
1. Disabling the CombinedFinalGrade functionality for DEDP courses
2. Be able to show the correct grade and the passing status. As far as I understand, the grade on edx is correct, and the passing status is incorrect. So in this case what we could do is after we freeze the final grades we can update the passing status of the grades.

> Can we import final exam grades using the existing script?
@pdpinch  I think we should just show the edx grade and completely remove the "exam grade" and "combined grade" from the dashboard.

Let me know if that makes sense.

**Comment by pdpinch** [comment]
> @pdpinch I think we should just show the edx grade and completely remove the "exam grade" and "combined grade" from the dashboard.

> Let me know if that makes sense.

I think this is the right direction going forward, which I guess means that we don't need to import the final grades for 3T2022 (and beyond) at all. 

But I'm not sure what the plan is for the legacy grades (before 3T2022). We can discuss on #5276.

**Comment by pdpinch** [comment]
> 2. Be able to show the correct grade and the passing status. As far as I understand, the grade on edx is correct, and the passing status is incorrect. So in this case what we could do is after we freeze the final grades we can update the passing status of the grades.

Does the final grade model already include a Boolean for passing status?

**Comment by annagav** [comment]
Yes it does

**Comment by annagav** [comment]
@pdpinch 

> Instead of combined final grades which are a combination of the course grade and exam grade, can we copy the course grade into the combined final grade? It will be the correct score, but not the correct passing status

We cannot populate edx grade into the combined final grade, because the combined final grade represents the best grade for course over all course runs and exams, and not a grade for a single course run. 
Options I am considering:
1) Make combined final grade optional, if it exists display it if not then also okay. Decide whether the user passed the course on not based on the existence of a certificate.
2) use the new grades to compare to existing combined final grade, if the score is higher than before, then create/update combined final grade.

**Comment by annagav** [comment]
@pdpinch do we want to keep MicromastersCourseCertificates generation? Based on what do we decide to generate it? Or do we get certificates from edx now for DEDP, the same as we do for non-fa programs?

**Comment by pdpinch** [comment]
> do we want to keep MicromastersCourseCertificates generation?

No, I don’t want to keep it. I would prefer to direct users to MITx Online to get their certificates (same as we do with edX).

However, I don’t know if we have a reliable API in MITx Online’s open edX that we can use for this purpose.

**Comment by annagav** [comment]
So the dashboard should display something like this now:
<img width="807" alt="Screen Shot 2023-01-20 at 8 49 38 AM" src="https://user-images.githubusercontent.com/7574259/213712870-ebf1cd6e-1791-425e-8a10-71d651fc2f07.png">

**Comment by pdpinch** [comment]
I think the dashboard display is OK, given the constraints. 

We do need to freeze the grades. We should test a couple of users to see if it works as expected.

**Comment by pdpinch** [comment]
@annagav I put off freezing the grades until you were back from vacation. Can we freeze the grades now?

**Comment by pdpinch** [comment]
@annagav can this be closed now?
