### ISSUE TITLE
Remove CombinedFinalGrade feature for DEDP

### ISSUE THREAD

**Issue by annagav** [mitodl/micromasters#5276]
Starting Fall 2022 the course grade on edx is a grade for course and the exam combined together. 

- [ ] Remove the following:

<img width="796" alt="Screen Shot 2023-01-03 at 11 22 23 AM" src="https://user-images.githubusercontent.com/7574259/210398186-4affc832-4b27-4b86-8516-3d90d6af84aa.png">

- [ ] Disable the creation of Combined final grade

- [ ] make sure course certificates are pulled from edx

**Comment by pdpinch** [comment]
We can remove exam grade and final grade for DEDP courses starting with 3T2022, but what do we do with the older grades?

**Comment by annagav** [comment]
For now we decided to treat frozen final grades with a passing status, with a start date later than Sep 1st, 2022, as being equivalent to having a MicromastersCourseCertificate.

On the dashboard, the exam grade and overall grade remain blank.
