### ISSUE TITLE
Use preferred name and last name on dashboard header

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#529]
The MicroMaster's site needs to feel official, not casual. We should use full names, not just first (given) names or preferred name. 

Requested by Erdin.

**Comment by aliceriot** [comment]
I think we should maybe reconsider this - lots of people use preferred names which are not just nicknames. My legal name, for instance, is not Alice. It's a bad user experience to force users to identify themselves with a legal first name which may not be the name they actually use everyday.

**Comment by pdpinch** [comment]
Okay, I'm convinced. I'm changing the title and description to be preferred name.

**Comment by noisecapella** [comment]
Does preferred name replace the first + last or is it just replacing the first name? I'm not sure this is obvious to the user in the profile page currently

**Comment by aliceriot** [comment]
@pdpinch can you clarify where we need to make this change? we show something involving the preferred name in the `Jumbotron` component in a couple different different places:

- on the profile flow we show something like `Welcome ${preferred_name}, let's complete your enrollment to MIT MicroMasters`
- on the dashboard page we just show `${preferred_name}`
- on `/settings` we just show `${preferred_name}`
- on the terms of service page we show  `Welcome ${preferred_name}, let's complete your enrollment to MIT MicroMasters`

**Comment by pdpinch** [comment]
Hmm, that's more variability that I expected.

I think we want to use  ${preferred_name} {last_name} everywhere

Biut I don't think we have those fields on the terms of service page, or on the 1st page of the profile flow. Can we use edX's full name there? Or drop the name altogether?

**Comment by aliceriot** [comment]
we have a little utility function called `getPreferredName` which falls back to the name set by edX and then to the username, so I think we should be able to just use that on the ToS page (as we currently do).
