### ISSUE TITLE
Fix validation copy

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#532]
Forgot to fix this before #504 was merged. From https://github.com/mitodl/micromasters/pull/504#discussion_r66634253

> For the first one, I think it would be good to give the user some guidance on what to do, e.g.

> "A Master's Degree is required if the Master's Degree switch is on. Click the + button to add a degree or switch it off"

> ... that's probably too long though.

> What's the user supposed to do in the 2nd case, on L103?

**Comment by noisecapella** [comment]
Here's what I have so far. It needs some work, any comments so far?

![screenshot from 2016-06-23 11-50-52](https://cloud.githubusercontent.com/assets/863262/16310034/ea51f6c8-3938-11e6-8ab2-b07d5c728642.png)

**Comment by roberthouse54** [comment]
To be honest, I wonder if we can hold off on this. I feel that I want to probably redesign this sign up flow in a way to get rid of the switches completely. The switches UI paradigm makes no sense to me.

**Comment by Ferdi** [comment]
OK to redesign but can we put some text there until that happens?

**Comment by roberthouse54** [comment]
OK, go with this then:

eg.

"Master's Degree is required if the switch is on. Please add a degree or switch it off."

Also, please make sure the text is aligned with the header above it. It is a bit too far left.
