### ISSUE TITLE
remove edX logo from all micromasters.mit.edu certificates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#5324]
edX doesn't have a role in the MicroMasters certificates on this site. 

#### Acceptance Criteria:

- [ ] remove from program certificates
- [ ] remove from course certificates

**Comment by annagav** [comment]
@pdpinch There is also explanation of edx under the certificate. Should this be removed? 
<img width="1499" alt="Screen Shot 2023-04-07 at 10 34 24 AM" src="https://user-images.githubusercontent.com/7574259/230626760-0e87a79d-5348-496f-aa25-baa599dee8aa.png">

**Comment by pdpinch** [comment]
remove it
