### ISSUE TITLE
Select field - odd filtering behavior after options have been selected

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#551]
This involves a few different behaviors. We should center around one of these for consistency.
### To reproduce scenarios 1-3, start with these steps:
1. Focus on any select field (eg: the Country field under 'Currently Living' in the Personal profile tab)
2. Choose any autocompleted option (doesn't matter if you type anything, or if you hit enter/click to choose)

**Scenario 1**
1. Click the text input area again

Result: All options are presented as suggestions, not just the option you've already chosen

**Scenario 2**
1. Immediately after choosing, hit the down arrow to bring up suggestions

Result: Only the option you've already chosen is presented as a suggestion

**Scenario 3**
1. Click the text input area again
2. Hit the left arrow to move the text cursor back to the penultimate letter
3. Hit the right arrow to move the text cursor to the end of the text again

Result: Initially, all options are presented as suggestions. After moving the cursor, only the option you've already chosen is presented as a suggestion (even when it is moved back to the end of the text)
### Now here's the weird one...

**Scenario 4 (refresh the page before trying this)**
1. Focus on any select field
2. Click on one of the autocomplete options without typing anything 
3. Hit the down arrow to bring up autocomplete suggestions
4. Clear the field
5. Type in a couple letters to filter the autocomplete suggestions
6. Select one of those suggestions via enter key or mouse click
7. Hit the down arrow again to bring up autocomplete suggestions

Result: After hitting the down arrow the first time, all suggestions are presented. After the second time, only the option you've already chosen is presented as a suggestion
### Suggested fix

I'm inclined to say we should only present the already-chosen option as a suggestion under all circumstances, but we can certainly discuss this

**Comment by pdpinch** [comment]
may be addressed by #547

**Comment by pdpinch** [comment]
Now that #547 has been fixed, has this issue been addressed? If it's partially addressed, I'd like to open a new issue for the remaining work and close this one (it's a bit overloaded).

**Comment by aliceriot** [comment]
closing because we switched to react-select
