### ISSUE TITLE
Select field - poor performance on country select field

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#553]
Easiest way to observe:

1. Click on a country select (eg: the one under 'Currently Living' in the Personal tab)
1. Hold the down arrow to rapidly navigate through the options

**Result:** The suggestions menu effectively freezes for several seconds. During this time, the escape key has no effect, and the menu stays in the same position within the browser window as you scroll up/down on the page

Another way to observe:

1. Type a single letter that many countries share as their first letter (C, F, S, etc.)
1. Hit backspace after typing the letter and immediately type a different letter that many countries share 
1. Repeat a few times in quick succession (eg: 'C', backspace, 'F', backspace, 'S', backspace, 'C')

**Result:** The suggestions menu and the input field are very slow to update

This is almost definitely due to the relatively large number of options and the burden of DOM updates. For the fields of study select, we mitigated this by preventing the suggestions menu on blank input and limiting the number of suggestion matches. We might consider doing something similar here. We might also want to consider some kind of load-ahead solution (ie: only load N suggestions to start out, and load the next N as the user navigates down through the list)

**Comment by pdpinch** [comment]
Wait to see if react-virtualize address this (PR is open now)

**Comment by noisecapella** [comment]
Can you comment on the performance now @gsidebo?

**Comment by gsidebo** [comment]
💯 💯  💯  🔥 🔥 🔥💯 💯  🔥 🔥🔥 🔥💯 💯 💯 🔥 🔥 🔥 

(looks really good now)
