### ISSUE TITLE
Remove the Apostrophe from MicroMaster's 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#557]
The News Office has reconsidered and MicroMaster's does not need to have an apostrophe everywhere. 

Presumably, all that's required is a revert of #478 and #236, but there may be a few instances in the text beyond those two PRs. Also, if an apostrphe make sense in the context, we can leave it in.

**Comment by noisecapella** [comment]
MicroMaster's degree makes sense but what about MicroMasters programs? Should that be MicroMasters' programs?

**Comment by noisecapella** [comment]
Also wondering about this:
> Also, don't hesitate to let us know about what MicroMasters you’d like to see
What does that word mean in the plural? Is a MicroMaster a credential for a single MicroMasters program?
