### ISSUE TITLE
Dialog forms - when window is too small, some fields are invisible w/ no indication that they exist

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#561]
![ss 2016-06-16 at 12 10 07 pm](https://cloud.githubusercontent.com/assets/14932219/16124074/7a0f9ad2-33bb-11e6-9007-94e651746340.png)

If a dialog window is too small vertically, required fields can be obscured with no visual indication that they exist. The scrollbar to access these fields in invisible by default. As a result, a user might be informed about form errors on fields they cannot see. Clicking 'Save' produces no apparent visual change whatsoever in these cases

Opinion: This one should be considered very high priority

**Comment by pdpinch** [comment]
I thought @noisecapella had already fixed this...

**Comment by aliceriot** [comment]
clarification: we previously fixed a separate issue, which is that in this same case the dialog used to extend off the page. imo the problem now is that when the screen height is too small the scrollbar doesn't show up, so it's not obvious that the user can scroll down to see the rest of the popup.

**Comment by aliceriot** [comment]
this may be specific to OSX, here's what happens on my (linux) box when I do the same thing:

![scrollbar](https://cloud.githubusercontent.com/assets/6207644/16125733/f9976a4e-33c2-11e6-8251-1fe598451d33.png)

**Comment by aliceriot** [comment]
or, rather, it may be specific to any setup that does floating scrollbars (which chrome recently added cross-platform).

**Comment by aliceriot** [comment]
here's what happens in chrome on linux with the experimental 'overlay scrollbars' feature flag enabled (in `chrome://flags`):

![visible_scrollbars](https://cloud.githubusercontent.com/assets/6207644/16125842/654b40f8-33c3-11e6-85c5-bfdbf8062925.png)

**Comment by pdpinch** [comment]
Is there a way to force the scroll bar to appear?

**Comment by noisecapella** [comment]
It looks like there's a CSS workaround: http://stackoverflow.com/questions/7492062/css-overflow-scroll-always-show-vertical-scroll-bar

**Comment by aliceriot** [comment]
it seems like that may not work in firefox on os x: https://stackoverflow.com/questions/18317634/force-visible-scrollbar-in-firefox-on-mac-os-x

**Comment by pdpinch** [comment]
@roberthouse54 could we instead fix the height of the dialog box, so the user scrolls the whole page instead of just the dialog box.

**Comment by aliceriot** [comment]
What about if we scroll the offending input into view? so that if the user leaves off e.g. `Country` from the personal dialog when they click 'save' it will be scrolled into view, so it's obvious what they need to do to move on from there.

**Comment by aliceriot** [comment]
@roberthouse54 I was just playing around and I implemented the behavior described above, lmk if you want to see how it feels

**Comment by aliceriot** [comment]
gonna implement that!
