### ISSUE TITLE
Add users page link in user dropdown in header in navbar

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#571]
This will need to be done on the 404 page as well. (base_error.html)

**Comment by gsidebo** [comment]
@pdpinch can we clarify this a bit? does this mean if i'm logged in as the user 'staff', we want a link for '/users/staff'?

**Comment by pdpinch** [comment]
That's correct, an item in the drop-down menu labelled "profile" that links to `/users/:username`

**Comment by gsidebo** [comment]
![ss 2016-06-28 at 12 36 41](https://cloud.githubusercontent.com/assets/14932219/16424725/5bfdd856-3d2f-11e6-8445-6f4962e90f8a.png)

@pdpinch wondering about the functionality of this top-right menu in general. clicking on the username here takes you to 'dashboard/'. clicking on the new 'Profile' link takes you to '/users/(username)'. i guess i'm a bit confused as to why these links are different. @roberthouse54 maybe you have some thoughts on this

**Comment by pdpinch** [comment]
dashboard is for viewing your current status in MicroMasters program that you are enrolled in. 

profile is for editing your profile.  

We can talk about a way to merge those, but right now I think they're different UIs. 

Eventually we will also add a settings item to this menu, for changing account settings like privacy.
