### ISSUE TITLE
Home: Popup when 'Learn More' is clicked on home page needs better look and feel

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#572]

**Comment by pdpinch** [comment]
Is this a design task, or is it obvious what's needed?

**Comment by noisecapella** [comment]
Yes, I think it needs some design

**Comment by pdpinch** [comment]
@roberthouse54 can you take a look at this pop as well, when you're looking at the home page?

**Comment by pdpinch** [comment]
This will be removed in the MM2 design
