### ISSUE TITLE
profile: If user refreshes page while editing profile, education switch state is lost

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#576]
This is causing confusing validation errors the user can't see. To reproduce:
 - fill out education profile, click Save and continue
 - on employment page refresh the browser
 - fill out employment profile, click Save and continue
 - fill out Privacy, click "I'm Done"

Since the UI state is lost and the validation when "I'm Done" is clicked includes UI state validation, the user will be prevented from moving on. Ideas:
 - validate only the UI of the page the user is currently on
 - persist education switch state in database
 - direct user back to the profile page where they had the error

**Comment by aliceriot** [comment]
@noisecapella what's your idea of the best of those ideas? I think validating only the UI of the current page sounds the easiest and most straightforward. I have other silly ideas involving local storage too.

**Comment by noisecapella** [comment]
I agree with you, and also want to avoid localStorage unless we absolutely need it

**Comment by aliceriot** [comment]
agreed :)
