### ISSUE TITLE
Fix '1 or more courses' text on '/dashboard/' to be singular

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#582]

**Comment by pdpinch** [comment]
Is this related to https://github.com/mitodl/micromasters/blob/e20edfc2255a87c54acf60bfd8e1682a9ad56f16/static/js/components/CourseList.js#L123 and the fact that when there is only one more course to pass, it still uses the plural "courses" ?

I'm realizing that we need to say something completely different when the user has completed all the courses in the program.

**Comment by pdpinch** [comment]
I believe the UI where this was an issue has been removed.
