### ISSUE TITLE
Graduation date field should be formatted consistently

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#586]
Since we pad the month with a 0 in the graduation date text, the field should show the same padding

Graduation date text:
![screenshot from 2016-06-23 17-48-52](https://cloud.githubusercontent.com/assets/863262/16321433/cf3e0dd6-396a-11e6-90d5-1cb907656bc3.png)

Field:
![screenshot from 2016-06-23 17-49-40](https://cloud.githubusercontent.com/assets/863262/16321446/e02902a4-396a-11e6-9b89-2f1733e61243.png)

**Comment by noisecapella** [comment]
@roberthouse54 should we add a 0 to the graduation date month in the text field, or remove it from the other places where we pad the 0?

**Comment by roberthouse54** [comment]
Add a zero to make it consistent. But a question... if the user just enters "8" with no zero, does the zero get added automatically?

**Comment by noisecapella** [comment]
No, should we?

**Comment by aliceriot** [comment]
@noisecapella would it make sense to roll this change into https://github.com/mitodl/micromasters/pull/641 ?

**Comment by noisecapella** [comment]
@aliceriot Yeah, that makes sense

**Comment by aliceriot** [comment]
kk I'll fix the bug you just found and then add this

**Comment by aliceriot** [comment]
should be just some `_.padStart` business I think
