### ISSUE TITLE
Dashboard is missing a spinner

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#587]

**Comment by pdpinch** [comment]
@roberthouse54 can you comment on the spinner design?

![screenshot from 2016-06-27 15-23-09](https://cloud.githubusercontent.com/assets/863262/16392668/12ea69a4-3c7b-11e6-9786-748cb6d87b98.png)

**Comment by pdpinch** [comment]
@noisecapella is this a size of 2 do you think?

**Comment by noisecapella** [comment]
A 1 or a 2. This is just copying work already done on the users page

**Comment by roberthouse54** [comment]
I think the spinner looks fine for now. There are other spinners that visually look better, and I think in the future we can add some text below the spinner (such as "Loading...", or something a bit more fun. But this is good for mow.
