### ISSUE TITLE
/dashboard/ does not show error if certificates API returns a 500

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#589]
@giocalitri put a `1/0` in the certificates API code. The devstack reported the zero division error but his micromasters instance's `/dashboard/` showed a list of courses as if there was no error

**Comment by giocalitri** [comment]
this should be closed when we update the `requirements.txt` with the updated library

**Comment by noisecapella** [comment]
Ah, I used the word 'fix' and github was being smart about it
