### ISSUE TITLE
Put error message on users page like on dashboard

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#591]

**Comment by pdpinch** [comment]
I don't understand this. I may need a screenshot.

**Comment by noisecapella** [comment]
The dashboard shows an error message like this, added in #517:

![screenshot from 2016-06-20 10-56-02](https://cloud.githubusercontent.com/assets/863262/16198913/99688700-36d5-11e6-845e-d6b5a0db1c65.png)

We don't do anything for the users page when the rest API GET fails there, or if a PATCH fails
