### ISSUE TITLE
Field of study should be sorted alphabetically

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#593]

**Comment by gsidebo** [comment]
@pdpinch and I discussed this. This is something that could go either way. The non-alphabetized version comes straight from NCES (https://nces.ed.gov/ipeds/cipcode/browse.aspx?y=55). It's ordered by code, and effectively it groups similar fields together. Click 'expand all' on that page and you'll see how the choices are grouped. The choices we've made available to users as fields of study are the 'leaves' in this document. It might be helpful to keep similar fields grouped together, but it's worthwhile to discuss what advantages that has vs. pure alphabetical ordering

**Comment by pdpinch** [comment]
I'm going to close this, unless we have a strong example of where alphabetizing would improve user experience.
