### ISSUE TITLE
Program Pages: redesign program FAQ page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#595]
Questions and answers aren't styled enough to be able to tell the difference.

**Comment by pdpinch** [comment]
You can see this with real data at https://micromasters-demo2.herokuapp.com/supply-chain-management/ (click on the FAQ tab). 

Here's is a screenshot (sorry it's so long. I'm being a bit lazy)

![screenshot-micromasters-demo2 herokuapp com 2016-06-22 14-59-52](https://cloud.githubusercontent.com/assets/430126/16279670/11db8812-388a-11e6-8c45-8047f7ac5da4.png)

**Comment by roberthouse54** [comment]
This design depends on the Program page design. The basic idea is to make the question bold, and the answer in a regular font. I do have a design for this, but it is in the context of the Program Page, which is still not signed off on.
