### ISSUE TITLE
Test real DEDP and SCM text in CMS

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#596]
Scrape SCM text from http://scm.mit.edu/micromasters/

DEDP text is still in progress, but we can put in some FPO text based on the proposal.

**Comment by pdpinch** [comment]
I've add the real SCM text into wagtail on micromasters-ci.mitx.mit.edu

**Comment by pdpinch** [comment]
I don't have admin access to micromasters.herokuapp.com.

@mitodl/devops can I get an admin account on micromasters.herokuapp.com ?

**Comment by bdero** [comment]
I just made your existing account (pdpinch) a superuser. Let me know if
that works.

**Comment by pdpinch** [comment]
Thanks. I am proceeding.

**Comment by pdpinch** [comment]
I added real-ish SCM content to the production app at https://micromaster.herokuapp.com

However, it is likely that we'll change the design before we go live.
