### ISSUE TITLE
Allow CMS user to direct program page to their own web site

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#598]
Some programs (like SCM) may already have their own micromasters site. We should allow CMS users to specify a URL for their program pages instead of using our program pages.

**Comment by giocalitri** [comment]
I think there are two flows to consider:

1. the staff flow
2. the student flow

### Staff flow:
The staff will still create a program page in the CMS and he will specify an URL for the external page and the program. He can ignore the other fields.

### User flow:
The user will click on the program on the homepage and he will automatically go to the external page.

**Comment by pdpinch** [comment]
Yes, this is what I had in mind.

**Comment by giocalitri** [comment]
additional question: should the link open in a new tab?

**Comment by roberthouse54** [comment]
I'd say no... just a regular link for now.
