### ISSUE TITLE
Add babel-polyfill to support IE11

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#609]
This will also help support other browsers which may have missing ES6 features here and there which the transpiler doesn't automatically take care of.

**Comment by gsidebo** [comment]
example: 

![ss 2016-06-21 at 12 14 49 pm](https://cloud.githubusercontent.com/assets/14932219/16238094/2d793e80-37ad-11e6-86c4-d3bbeca70302.png)

tested in a Win7/IE11 VM
