### ISSUE TITLE
Use docker-unison instead of docker-osx-dev

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#61]
The main thing it provides is a two way sync instead of a sync from host to dev.

**Comment by jamiefolsom** [comment]
@noisecapella is this decided, or up for discussion? Sounded over lunch like it was an idea.

**Comment by noisecapella** [comment]
I felt strongly about it when I filed the issue but now I'm not so sure, so up for discussion

**Comment by jamiefolsom** [comment]
OK, totally open to it, just curious.
