### ISSUE TITLE
Bug: program page styling regression

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#620]
As of 6/22 the program page is looking like this:

https://drive.google.com/file/d/0B9nbgzSIkR7mUHJZcWxid3VYNEE/view?usp=drivesdk

Yesterday it looked like this (the way it should):

https://drive.google.com/file/d/0B9nbgzSIkR7mUHdUNGVQS1Rzanc/view?usp=drivesdk

**Comment by noisecapella** [comment]
It looks like the regression was introduced in #567
