### ISSUE TITLE
Prevent user from skipping ahead in user profile form sequence

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#627]
Related to #576 

If the user skips a form by entering the URL for a later one in the sequence, the user can get stuck with a validation error she can't perceive or correct, because it's on a prior form. 

When the user skips ahead, she should be directed back to the earlier form that failed validation.

**Comment by pdpinch** [comment]
@gsidebo @aliceriot does this capture the issue mentioned in #618 ?

**Comment by aliceriot** [comment]
Yes, I think so. I'm not sure exactly what the way we want to solve this issue is though, we had talked about not having separate URLs for different steps, redirecting to the unfilled step, etc.

**Comment by gsidebo** [comment]
sounds like we would benefit from @roberthouse54 's input

**Comment by noisecapella** [comment]
My vote would be to remove the different links like `/profile/professional/`. This would require moving that logic from react-router into `ProfilePage` but I think that would also clean up some workarounds we do like cloning child components
