### ISSUE TITLE
Profile validation errors sometimes have no visual indicator

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#635]
To reproduce:

1. Open up the /profile/personal tab
1. Fill out the entire form, and enter something invalid for DOB (eg: "00/00/0000")
1. Scroll down to the bottom of the page and, if necessary, shrink the window so you can't see the DOB field
1. Click "Save and Continue"

Expected: some visual indication that the form validation failed
Actual: visually, nothing happens

A couple options to consider:

- when validation fails, change the form focus to the first field that needs to be fixed
- when validation fails, put some generic error message above/aside/below the "Save and Continue" button, eg: "Please fix the errors above"

**Comment by aliceriot** [comment]
@gsidebo @roberthouse54 what if in this situation we greyed out 'save and continue' and displayed a message saying 'please fix the errors on the page' (or something to that effect) next to the button?

**Comment by roberthouse54** [comment]
![error_validation](https://cloud.githubusercontent.com/assets/20047260/17114902/f4e29034-527e-11e6-8ad5-87533ca1993d.jpg)

**Comment by aliceriot** [comment]
cool, will do
