### ISSUE TITLE
Add JS tests that test full React component tree structure

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#636]
So far, I've only seen 'shallow' React component testing in our JS tests. This means that our tests 'render' certain components, but cannot assert anything about any child components that it renders. 

One case where this approach falls short: I added the ability to define a MenuItem renderer for use by AutoComplete and its child components. One of those renderers 'highlights' the text of a MenuItem that matches the user's input. I would love to test the SelectField or AutoComplete components in such a way that I can confirm that, given some search text, the options match and the search text is bold. This can't be done with shallow rendering since it involves child components.

Here's a reference doc that discusses some React component testing approaches: http://reactkungfu.com/2015/07/approaches-to-testing-react-components-an-overview/

@noisecapella @aliceriot Maybe this is something we don't need. Discussion is quite welcome.

**Comment by noisecapella** [comment]
There are tests which test the full component tree structure, look for the files ending in `_test.js` in the `static/js/containers` directory. We could use more, though. Can you make a list of specific cases to test?

**Comment by gsidebo** [comment]
ok cool, i'll take a look at those and see where i get

**Comment by gsidebo** [comment]
@noisecapella are you talking about the use of `renderComponent`? seems like that's only used to render an entire page. i'm looking to render a single component and all of its children. do we do that anywhere? is it not generally advisable/possible?

**Comment by aliceriot** [comment]
We installed [enzyme](http://airbnb.io/enzyme/) recently, which I think should take care of this.

All in favor of closing?
