### ISSUE TITLE
Home: What to do with very long program descriptions

### ISSUE THREAD

**Issue by giocalitri** [mitodl/micromasters#653]
[This comment](https://github.com/mitodl/micromasters/pull/625#issuecomment-228863117) demonstrates that there might be an odd behavior in case of a very long description.
In [the following one](https://github.com/mitodl/micromasters/pull/625#issuecomment-228874532) @roberthouse54 suggests to truncate it to a reasonable limit, but the problem is that this content is not available in the program page so if we truncate it, there is no way to show the full content.

So we need either to 

- move it to the CMS to have it available in the program page
- keep it in the django ADMIN, but then find a way to show the full length in the home page in case we need to truncate it (well this can be an option even if we move the content to the CMS in case this description need to be specific to the home page)
- drop this description

CC @Ferdi @pdpinch

**Comment by pdpinch** [comment]
In the long run, I think we should be pulling these course descriptions from an edX API -- unless we have a reason for supporting different descriptions. 

I think the drives us towards your second option Giovanni.

**Comment by giocalitri** [comment]
I understand, but we have already moved the thumbnail to the CMS...

**Comment by pdpinch** [comment]
Scratch that. I was confusing courses and programs. 

We have to write the program descriptions, and manage the program thumbnails -- at least for any foreseeable future.

**Comment by giocalitri** [comment]
Ok, but given that the thumbnail is in the CMS, I think it makes sense to have the description there as well (or am I missing something?)

**Comment by pdpinch** [comment]
Sorry I wasn't clear. I am agreeing with you, now that I understand why the thumbnail is in the CMS.

**Comment by pdpinch** [comment]
We've decided that we'll manage the text for these descriptions, and we won't let them get too long.
