### ISSUE TITLE
Home: add character limit to program.description in django admin

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#658]
On the home page there is no limit to how much text a CMS user can put in a program description. It would be convenient to automatically truncate the text with a (View More) link. This would require a minimal amount of JS (maybe there's a CSS solution?)

**Comment by roberthouse54** [comment]
I am not sure if we are still planning on doing this, but I think the better solution is the one where we put a character limit on the text entry field in the Django admin, or wherever we are editing this copy.

**Comment by pdpinch** [comment]
We manage this copy, so it hasn't been an issue.
