### ISSUE TITLE
cursor jumps to end of string when editing a `<TextField>` for the first time

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#665]
When editing a text field rendered using a material-ui `<TextField>` for the first time (e.g. after opening the new work history or education menu) the cursor will jump to the end of the line, away from where the user had the cursor.

We noticed this when reviewing https://github.com/mitodl/micromasters/pull/641

here's a possibly-related issue in the material-ui repo: https://github.com/callemall/material-ui/issues/4502

**Comment by gsidebo** [comment]
I created a duplicate issue for this bug (which I've now closed). Here are the reproduce steps in case they help...

- Open the personal tab of the profile edit form with a non-blank last name (users page or profile, doesn't matter)
- Click on the first name field to focus on it
- Hit tab to navigate to the last name field and highlight the text
- Hit the left arrow key to deselect the text and move the cursor to the beginning of the input
- Type two letters

**Expected:** The two letters would be inserted at the position of the text cursor (ie: the beginning of the input
**Actual:** The first letter is inserted at the beginning of the input, and the second letter is inserted at the end

**Comment by aliceriot** [comment]
So this seems to be only happening for `<TextField>` components which are located inside of `<Dialog>` components, the text fields on the personal info section of `/profile` seem to be working fine.

here are a couple of more related issues (no fix yet that I see):

https://github.com/callemall/material-ui/issues/4430
https://github.com/facebook/react/issues/955

**Comment by ethan-deng** [comment]
This repros only for TextField in Dialog.

Two ways to hack it (not sure it is a fix).
1. Use "defaultValue" instead of "value" with TextField.
2. Comment out this line https://github.com/callemall/material-ui/blob/master/src/TextField/TextField.js#L356

this.setState({hasValue: isValid(event.target.value), isClean: false});

**Comment by gilesbradshaw** [comment]
"are located inside of <Dialog> components,"  and Popovers..

**Comment by pdpinch** [comment]
@aliceriot @gsidebo is this still an issue for us?

**Comment by gsidebo** [comment]
@pdpinch looks like this is solved! i'll close

**Comment by aliceriot** [comment]
cool!
