### ISSUE TITLE
Discovery: SearchKit UI for Elastic Search

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#668]
http://www.searchkit.co/

**Comment by aliceriot** [comment]
@pdpinch where can I find the mockup for what the search UI should look like?

**Comment by pdpinch** [comment]
There's a screenshot on the epic, #669 

And here it is again:

![learner_search](https://cloud.githubusercontent.com/assets/430126/16533340/02558e2e-3fa6-11e6-8846-90fd677b9f52.png)

Any comments or questions, ask @roberthouse54 -- he's made it clear that it's not final.

**Comment by pdpinch** [comment]
Oy, I replied to this, but I think I forgot to save. 

The screenshot is on the epic #669. I'll paste it in here as well:

![learner_search](https://cloud.githubusercontent.com/assets/430126/16533340/02558e2e-3fa6-11e6-8846-90fd677b9f52.png)

**Comment by aliceriot** [comment]
haha, same comment twice!

**Comment by aliceriot** [comment]
going to close this, implementing the basic ui in #714

**Comment by noisecapella** [comment]
:+1:
