### ISSUE TITLE
Learner Profile Search

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#669]
As a member of a MM team, I want a faceted search interface that I can use to find learners and then do something with the results. 

Use cases:
- I want to find all the learners in my MM who completed two courses with a grade better than 90%. I want to e-mail them a message about signing up for the next course.
- I want to find all the learners in my MM who are citizens of an Arabic country and let them know about a scholarship opportunity. 
- I want to find all the learners in my MM who have worked in the construction industry and invite them to post to a forum with AMA questions for an MIT faculty member
- I want to find all the learners in my MM in Seoul, South Korea and create a chat room for them, so they can meet each other before a bootcamp opens

Fields for search
   user name
   all the text (?)

Fields for faceting
  completed courses 
  completed course grade
  currently enrolled
  current grade
  country of residence
  country of birth
  education degrees
  education schools
  education fields of study (values are hierarchical) 
  employment companies
  employment positions
  employment industries

Fields in search results
  link to user profile page
  enrollments
  grades (?)

Mock-up (in progress; details will change):

![learner_search](https://cloud.githubusercontent.com/assets/430126/16533340/02558e2e-3fa6-11e6-8846-90fd677b9f52.png)

**Comment by aliceriot** [comment]
@pdpinch is there a story for building the initial UI? #668 seems to just encompass discovery, but I've been working on actually starting to build the UI as well.

**Comment by Ferdi** [comment]
Feel free to create a new issue

- Sent from my phone

**Comment by aliceriot** [comment]
cool, will do!

**Comment by Ferdi** [comment]
@pdpinch time to close this ?

**Comment by pdpinch** [comment]
This is so big and so old, I think we should close it just because it's not very useful. 

But what would you like to do with the remaining facets?

- #857 Facet by Nationality
- #858 Facet by Field of Study
- #859 Facet by Degree
- #860 Facet by School
- #862 Facet by Employment Position
- #863 Facet by Company

**Comment by pdpinch** [comment]
I'm going to close this. We'll keep the individual facet stories open, but since no one's asked for them they'll remain low priority.
