### ISSUE TITLE
Student dashboard: Display student avatar and student name

### ISSUE THREAD

**Issue by jamiefolsom** [mitodl/micromasters#67]
As a student, I want my avatar to appear on my dashboard page, and throughout the private (and in community areas, as appropriate based on my privacy preferences).

This requires: offering a way for students to authenticate with another service and select a hosted avatar (eg gravatar, twitter, facebook), or to upload one, size, center and crop.

MVP: display edX avatar

**Comment by pdpinch** [comment]
When we create the profile from the edX profile, we will get a link to the edX avatars. We should allow the user to change these, or add a new one. 

It would be nice to support Gravatar as an option. as well.

**Comment by pdpinch** [comment]
If there is no value for the avatar we will use edX's default (need URL)
