### ISSUE TITLE
batch update user data without the user logging in

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#671]
As a MM team member, I'd like to be able to search learner profiles with fresh data, even for users who might not have visited the MM site recently. 

Normally we rely on users visiting their dashboard to initiate an update of learner data from edX (enrollments, certificates and grades).

For less active users, we can set up a periodic batch process to update any learner data that's older than a configurable number of hours. 

We will need to coordinate with edX about frequency of these updates, so we don't overwhelm them. 

- [ ] add celerybeat to handle scheduling of this task
- [ ] start with starting batch every 6 hours
- [ ] only refresh user data that is stale
- [ ] if the user's access token has expired, we can refresh it (dashboard already does this)
- [ ] if the refresh fails, raise an exception, log it and move on -- the user will need to log into edX again 
- [ ] can we limit the pace of outgoing requests to edX?

**Comment by pdpinch** [comment]
Giovanni reminded me that we have the access token stored, so we can fetch the users' data (read only!) without them currently logged in to the web site. Is this covered by the terms of service?

If we go this route we will need an asynchronous task to periodically update users' data.

**Comment by gsidebo** [comment]
i'm guessing it's possible for a user's access token to be expired when we attempt to fetch edX data. what happens then? are we able to refresh it? if so, does that have any affect on the user the next time s/he logs in?

**Comment by amir-qayyum-khan** [comment]
@pdpinch,

@giocalitri will work on this or I?

**Comment by giocalitri** [comment]
@amir-qayyum-khan I think the plan is that you will.
Before starting to code, can you please write here a summary of what you plan to do so we can discuss and agree about what to do before writing actual code?

**Comment by amir-qayyum-khan** [comment]
@giocalitri i will discuss this  tomorrow, today I need to do some research, as soon i finish i will write summary here and discuss with you tomorrow after or before standup.

**Comment by amir-qayyum-khan** [comment]
@giocalitri 
- Create produce tasks, set time every 6 hour and run it via celerybeat. There are some links that will help:
  - http://stackoverflow.com/questions/20116573/in-celery-3-1-making-django-periodic-task
  - http://stackoverflow.com/questions/11792101/how-to-configure-and-run-celerybeat
- To refresh user token code is here https://github.com/mitodl/micromasters/blob/master/dashboard/views.py#L46-L52
Do we need to fetch all users in our task and in loop should we update their information like enrollments, certificates and grades ? This [code can be reuse](https://github.com/mitodl/micromasters/blob/master/dashboard/views.py#L55-L59) to fetch and update user information but i do not see any code for grades can you point me out?

- > if the refresh fails, raise an exception, log it and move on -- the user will need to log into edX again 

So in this case can we log information and somehow inform user that he needs to login. For example we can send him email which state that his session is expire he needs to visit MM to update his information. Any suggestion?
- > can we limit the pace of outgoing requests to edX?

Do you have any idea abt this? Is their any limit on edX site for users requesting in specific interval of time?

**Comment by pdpinch** [comment]
> Do we need to fetch all users in our task and in loop should we update their information like enrollments, certificates and grades ?
> 
Yes
> This code can be reuse <https://github.com/mitodl/micromasters/blob/master/dashboard/views.py#L55-L59> to fetch and update user information but i do not see any code for grades can you point me out?
> 
The certificates data should include (final) grades. 

> if the refresh fails, raise an exception, log it and move on -- the user will need to log into edX again
> 
> So in this case can we log information and somehow inform user that he needs to login. For example we can send him email which state that his session is expire he needs to visit MM to update his information. Any suggestion?
> 
For now, we just want to log it. 

I'm not sure e-mailing the user is a good idea, since they'll update the token the next time they visit the site. 

> > can we limit the pace of outgoing requests to edX?
> Do you have any idea abt this? Is their any limit on edX site for users requesting in specific interval of time?
> 
AFAIK, edX doesn't do any rate limiting at this time. That's why we'd like to consider making it configurable on our end.

**Comment by giocalitri** [comment]
> AFAIK, edX doesn't do any rate limiting at this time. That's why we'd like to consider making it configurable on our end. 

I actually do not know how do do this given that we will use celery, but it seems possible:
http://stackoverflow.com/questions/4857464/celery-django-rate-limiting
