### ISSUE TITLE
Add roles to user model

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#674]
3 roles currently:

admin
MM team (can have this role on multiple programs) 
learner (can have this role on multiple programs)

Do we need an instructor role, distinct from MM team?

MM team permissions includes things like:
- editing their pages in the CMS
- search private learner profiles in their MicroMasters
- possible future features like creating new forums and messaging learners in their MicroMasters

**Comment by pdpinch** [comment]
Does edX have an API that exposes user role on edX?

**Comment by blarghmatey** [comment]
Of possible interest for implementing RBAC: http://django-prbac.readthedocs.io/en/latest/

**Comment by giocalitri** [comment]
The basic idea around the implementation of Roles and Permissions for Micromasters is based on the assumption that the kind of roles will be pretty stable: at the moment they are `mm-staff`, `instructor` and `learner`.

By default a MM user will be a `learner`: this means that if a user just logs in the app, she will see the `learner` dashboard and anything is designed for the students and nothing else.
Other roles need to be specified explicitly. 
Also there will be no direct inheritance or dependency among roles: this means that (with the current requirements) a `instructor` user is not necessarily a `staff` user and vice versa. If different roles have the same permissions assigned, then they might be considered equivalent.

The roles will be defined per `MM program` with a specific model. Something like:
```
class MMRoles:
    type -> foreign key to "RoleType"
    user -> foreign key to "Users"
    program -> foreign key to "Programs"

class RoleType:
   description -> any of [staff, instructor]
```

With this in place we should be able to implement logical Roles (i.e. what the role means in terms of permissions) using [django-role-permissions](http://django-role-permissions.readthedocs.io/en/latest) and specific [object permission checks](http://django-role-permissions.readthedocs.io/en/latest/object_permissions.html) to check, for instance, if the user is staff or a course.

I still need to make a first attempt of implementation using this approach, so there might be some issues yet to be discovered.

**Comment by pdpinch** [comment]
Does this allow a user to have different roles on different programs? (I'm not sure this is requirement, but it would be good to know)

How do we handle things like privacy settings, where the result of a permission check depends on both the role and an attribute on the object? Is that just another parameter for the permission check?

**Comment by giocalitri** [comment]
> Does this allow a user to have different roles on different programs? (I'm not sure this is requirement, but it would be good to know)

This is a good question: from the design point of view this is already achieved, but from the UI point of view this is going to be a nightmare IF we are assuming that an user can be `learner` on one program and `staff`/`instructor` on another.

> How do we handle things like privacy settings, where the result of a permission check depends on both the role and an attribute on the object? Is that just another parameter for the permission check?

Not sure I understood the question: example?

**Comment by Ferdi** [comment]
@giocalitri , looks good to me.

> to check, for instance, if the user is staff or a course.
It would probably be better to check "if user_has_permission(permission, user)" instead of checking the user role.

**Comment by Ferdi** [comment]
How do you assign a permission to a role ? what the code looks like ?

**Comment by giocalitri** [comment]
@Ferdi the documentation seems to suggest that it is pretty streight forward:
http://django-role-permissions.readthedocs.io/en/latest/roles.html

**Comment by giocalitri** [comment]
@Ferdi 

>It would probably be better to check "if user_has_permission(permission, user)" instead of checking the user role.

You need to check also the scope of the permission, meaning if the user has permission for a specific program. this should be covered as well by the library.

**Comment by Ferdi** [comment]
@giocalitri thanks for the docs  and good point on the scope !

**Comment by pdpinch** [comment]
We met to discuss this and agreed on this plan. 

In the course of discussion, we identified a few more _potential_ use cases:

- The MM team members will need permission to edit their pages in the CMS. Since the CMS is a separate app with it's own ACLs, we will implement a signal to update the CMS when a users role is changed (#687 is a related issue)
- We expect we'll need a similar approach for external services, like chat or forums
- The front-end will not be responsible for enforcing permissions, but will need to know them so it can present the appropriate interface. We will include the user's permissions in the profile API (needs issue)
