### ISSUE TITLE
add model(s) for users' enrollments, grades, certificates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#677]
To start with, we will update this data (synchronously) whenever the user looks at his dashboard, if it's older than a configured amount of time. 

When the user makes an API request, we check the date of last update. If it's been longer than a set amount (say 6 hours), we make an upstream request to edX's API and store the result in our database. 

We may need another story for doing batch updates.

**Comment by noisecapella** [comment]
It looks like we don't retrieve the current grade, and the final grade is part of the certificate data, so there will only be two models

**Comment by noisecapella** [comment]
It looks like the certificates request depends on the course keys from the enrollments data. Should the `Certificates` model have a foreign key to the `Enrollments` model or should the two models be treated as if retrieved separately? cc @giocalitri

**Comment by giocalitri** [comment]
the reason the Certificate API is dependent on the Enrollments one is because we do not have a way to look for ALL the certificates.
In theory the certificates are a subset of the enrollments and they must have a correspondent enrollment, but I think that we do not need a foreign key, given that a course run, for a specific user, can have only one enrollment and one certificate at most.

**Comment by noisecapella** [comment]
Ok, I'll make the models `Enrollment` and `Certificate` and not have the foreign key relationship

**Comment by giocalitri** [comment]
you still might want to put a foreign key to the runs

**Comment by noisecapella** [comment]
I'm not sure about that, there's no guarantee that for every course run in edX there is a `CourseRun` object in our database

**Comment by giocalitri** [comment]
You are right, but we want to store locally ONLY informations about `CourseRun`s we know about

**Comment by noisecapella** [comment]
What do you think of this?

    class Enrollments(Model):
        """
        Model for user enrollments data from edX
        """
        user = OneToOneField(User)
        last_request = DateTimeField()
    
    
    class Enrollment(Model):
        """
        Model for user enrollment data from edX
        """
        enrollments = ForeignKey(Enrollments)
        course_run = ForeignKey(CourseRun)
        data = JSONField()
    
        class Meta:
            unique_together = (('enrollments', 'course_run'), )
    
    
    class Certificates(Model):
        """
        Model for certificates data from edX
        """
        user = OneToOneField(User)
        last_request = DateTimeField()
    
    
    class Certificate(Model):
        """
        Model for certificate data from edX
        """
        certificates = ForeignKey(Certificates)
        course_run = ForeignKey(CourseRun)
        data = JSONField()
    
        class Meta:
            unique_together = (('certificates', 'course_run'), )

**Comment by noisecapella** [comment]
I'm not sure we're all on the same page regarding the cache. I talked with @giocalitri and I'm going to do a solution where it always fetches from edX and updates our local copy, then we can talk about modifying it when @pdpinch gets back

**Comment by noisecapella** [comment]
I talked with @giocalitri again and we will do what the issue describes, except there will be a 5 minute timeout for enrollments instead of 6 hour for certificates
