### ISSUE TITLE
Integration tests for creating student accounts

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#68]
As a devops, I'd like a test that I can run to confirm that student accounts can be created successfully on a deployment. 

For some time in production, account creation was failing with a 500 error. We're still not entirely sure what the cause was, but we'd like to have better tooling to detect it in the future. 

To create a student account, we will need a course code.

**Comment by pdpinch** [comment]
FYI @justinabrahms

**Comment by justinabrahms** [comment]
Assuming SCB as well?

**Comment by pdpinch** [comment]
Yeah. Sorry, wrong repo. ZenDesk usability fail.
