### ISSUE TITLE
filter by average grade (back end)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#682]
As a MicroMaster team member, I need to filter learner profile search results by grade range. 

The proposed UI includes both summary data from the search results and a control for specifying the grade:

![image](https://cloud.githubusercontent.com/assets/430126/16533477/edf0bcd2-3fa6-11e6-896a-e1586a65930d.png)

- [ ] When certificates & final grades are updated, update the index with an average of all the learner's final grades
- [ ] add the average final grade as a facet in the search results (API)
- [ ] How will we deal with learners with an average of Zero? Add another facet for number of courses completed.

**Comment by gsidebo** [comment]
we can definitely look into front-end components for this, and we can always mock out data as needed, but i spoke with @noisecapella last week, and it seemed like there was some uncertainty about how we're going to fetch or store grade data

**Comment by pdpinch** [comment]
The only data that we have at this time is the final grade for each certificate. It's stored in the certificate model (data field).

**Comment by pdpinch** [comment]
Can Elasticsearch calculate the average on the search results, to find an "overall grade" or will we need to add that to the index explicitly? 

A quick read of the docs suggests yes.

**Comment by gsidebo** [comment]
@pdpinch 

> The only data that we have at this time is the final grade for each certificate. It's stored in the certificate model (data field).

do we? isn't this model being added as part of #677, which is still in progress? i don't think this issue can be started until that's done. i'm more than happy to do some ES study in the meantime

**Comment by pdpinch** [comment]
#677/#678 are closed/merged, so we have the necessary component data. 

Further discussion and evaluation of elastic search has lead us to conclude, however, that we need to calculate and add the average grade (per program) to the elastic search document, instead of relying on elasticsearch to aggregate the grades at query-time.

**Comment by pdpinch** [comment]
Blocked by #774

**Comment by gsidebo** [comment]
### Requirements update

- We will be calculating a user's overall grade on a *per program basis* in our app before sending it to be indexed in ES. Filtering by grade will act on these per-program values. Adding this calculation and serializing it should be done as part of 
- As a result, the filter-by-grade widget *should only be available when a single Program is selected as a filter/facet*. Grade-filtering paramaters should not be added to the ES query unless a single program is selected
