### ISSUE TITLE
Student Dashboard: Create and display Student ID

### ISSUE THREAD

**Issue by jamiefolsom** [mitodl/micromasters#69]
As a student, I want my "student identification number" stored in my profile, for use in verifying my identity, retrieving my enrollments, grades, etc.

The ID should look like : 

MMM ### ####
For example 

MMM 000 0001
MMM 000 0002
etc.

Numbers will be serial. We will use a separate field, to avoid confusing the user primary key with this "student id"

- [x] add to model
- [x] update REST API
- [x] add to dashboard react component

**Comment by pdpinch** [comment]
MIT student IDs are 9 digit numbers. For now, let's plan to do the same thing. 

Perhaps at some point we will engage the bureaucracy to see if we can get bona fide student ids for micromasters candidates. I'm not sure where to start that conversation though.

**Comment by pdpinch** [comment]
I updated the description to capture the discussion in planning.

**Comment by aliceriot** [comment]
just opened #173 which addresses some of this (adds the attribute, adds it to the model serializer), but I think we're waiting on some more React work to include this somewhere in the frontend (unless I'm misunderstanding how it's to be included in the UI).

**Comment by noisecapella** [comment]
I think you should be able to start now, the dashboard has the user profile image and name already. There are some mockups here: https://projects.invisionapp.com/share/KR6FYCZTX#/screens/142338434

**Comment by aliceriot** [comment]
ah cool, not seeing that I thought the id was only supposed to appear at `/dashboard/profile`
