### ISSUE TITLE
Is Heroku/Bonsai FERPA compliant?

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#698]
If we use Bonsai and Heroku for storing student data, is the service FERPA compliant?

If it isn't, we'll need to set up an EL cluster in AWS. This would be 3-point devops story.

**Comment by pdpinch** [comment]
It is, according to Bonsai's feature page at https://bonsai.io/pricing

**Comment by Ferdi** [comment]
that's only on the "enterprise" option right ?

**Comment by pdpinch** [comment]
You're right. I misread that. I assumed that anything in the box was good. 

Okay then, we'll set up a cluster -- maybe next sprint though. Let me talk to @mitodl/devops
