### ISSUE TITLE
Implement ElasticSearch index

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#699]
we'll use ElasticSearch DSL

Configure the index schema to match the user profile, user education, user employment

We will be adding new fields to the models in other issues. #677 #672

**Comment by aliceriot** [comment]
http://docs.searchkit.co/stable/docs/server/indexing.html

**Comment by noisecapella** [comment]
I'm planning on indexing only the fields which appear in the REST API. I don't think we need anything else but let me know if there's something that would be missing.

**Comment by Ferdi** [comment]
@noisecapella , can you list the fields here ?

**Comment by noisecapella** [comment]
@Ferdi:

    {
        "account_privacy": "public",
        "agreed_to_terms_of_service": true,
        "birth_city": "XXX",
        "birth_country": "AF",
        "birth_state_or_territory": "AF-NIM",
        "city": "Alger",
        "country": "LR",
        "date_of_birth": "1991-11-11",
        "education": [
            {
                "degree_name": "b",
                "field_of_study": "31.0505",
                "graduation_date": "2034-08-01",
                "id": 21,
                "online_degree": false,
                "school_city": "Cocos Islands",
                "school_country": "BO",
                "school_name": "School",
                "school_state_or_territory": "BO-L"
            }
        ],
        "edx_level_of_education": null,
        "email_optin": true,
        "filled_out": true,
        "first_name": "staff",
        "gender": "o",
        "has_profile_image": false,
        "last_name": "Staff",
        "preferred_language": "en",
        "preferred_name": "Staff",
        "pretty_printed_student_id": "MMM000007",
        "profile_url_full": "https://www.gravatar.com/avatar/c20b63b48c471b990cbd21f8f572e17c?r=PG&s=800&d=https%3A%2F%2Fs3.amazonaws.com%2Fodl-micromasters-production%2Favatar_default.png",
        "profile_url_large": "https://www.gravatar.com/avatar/c20b63b48c471b990cbd21f8f572e17c?r=PG&s=500&d=https%3A%2F%2Fs3.amazonaws.com%2Fodl-micromasters-production%2Favatar_default.png",
        "profile_url_medium": "https://www.gravatar.com/avatar/c20b63b48c471b990cbd21f8f572e17c?r=PG&s=250&d=https%3A%2F%2Fs3.amazonaws.com%2Fodl-micromasters-production%2Favatar_default.png",
        "profile_url_small": "https://www.gravatar.com/avatar/c20b63b48c471b990cbd21f8f572e17c?r=PG&s=100&d=https%3A%2F%2Fs3.amazonaws.com%2Fodl-micromasters-production%2Favatar_default.png",
        "state_or_territory": "LR-BG",
        "username": "staff",
        "work_history": [
            {
                "city": "City",
                "company_name": "Workplace",
                "country": "DZ",
                "end_date": "2016-08-01",
                "id": 23,
                "industry": "Leisure, Travel & Tourism",
                "position": "Tourist",
                "start_date": "2016-05-01",
                "state_or_territory": "DZ-46"
            }
        ]
    }
