### ISSUE TITLE
Student Dashboard: enrollment status

### ISSUE THREAD

**Issue by jamiefolsom** [mitodl/micromasters#70]
As a student, I want to enroll in a course within a MM program. This requires a button next to any course in which I am not currently enrolled, which initiates a course enrollment.

See: https://projects.invisionapp.com/share/KR6FYCZTX#/screens/142338434

Per #42, enrollments can't currently be completed in a single step, so once clicked, the button should be disabled, and should be labelled "verification pending" or similar. When enrollment is confirmed, it can be removed, and (per #53) the course status column should have a column indicating the appropriate date.

This includes enrolling the user (an edX API call) and presenting the user with a link to upgrade to ID Verified.

**Comment by pdpinch** [comment]
Students must be ID Verified in a course in order for it to count towards the micromasters program. We need to flag this status for users who haven't yet verified.

**Comment by Ferdi** [comment]
Closing, duplicate of #125 and #123
