### ISSUE TITLE
Search: facet UI for choosing geographies

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#700]
How to choose country, region and city

**Comment by Ferdi** [comment]
This doesn't look bad : http://demo.searchkit.co/taxonomy

**Comment by pdpinch** [comment]
Confirmed with @roberthouse54 that the design presented in http://demo.searchkit.co/taxonomy should work. We'll do 3 levels: country, region (state) and city

**Comment by roberthouse54** [comment]
![current_residence_facet](https://cloud.githubusercontent.com/assets/20047260/17307199/d87c2850-5801-11e6-89e8-445d11ca9e0c.png)

**Comment by pdpinch** [comment]
Thanks Rob. Is this in Invision now?

I'll open an issue to implement it.

**Comment by roberthouse54** [comment]
I just added it. https://invis.io/SU85FP84K#/178365359_Current_Residence_Facet
