### ISSUE TITLE
Search API for staff users

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#701]
wrap the standard elastic search API with access controls, including privacy restrictions

only signed in users can use the API.

Admin can search all users and all user data. 

Staff can search users in their program, and all user data (including grades)

(Learners can only search users who share their profile, and they can never see grades. We'll implement learner-to-learner search as another API) 

requires roles issues to be completed. Blocked by #709

**Comment by pdpinch** [comment]
How to protect elastic search with searchkit: https://news.ycombinator.com/item?id=11323912

**Comment by giocalitri** [comment]
which kind of sorting will we have?
cc @pdpinch @aliceriot @roberthouse54

**Comment by roberthouse54** [comment]
For a start, I'd say:
Name A-Z, Name Z-A Grade High-to-low, Grade Low-to-High. Maybe also Country?

**Comment by giocalitri** [comment]
where "Name" is "last name" or what?

**Comment by roberthouse54** [comment]
yeah, last name

**Comment by pdpinch** [comment]
Blocked by #774

**Comment by pdpinch** [comment]
@giocalitri now that #811 is merged can you start working on this again?

**Comment by giocalitri** [comment]
I actually started yesterday

Sent by my iDevice. May be rife with typos or poor judgment.

On Aug 9, 2016, at 8:44 AM, Peter Pinch <notifications@github.com<mailto:notifications@github.com>> wrote:


@giocalitri<https://github.com/giocalitri> now that #811<https://github.com/mitodl/micromasters/pull/811> is merged can you start working on this again?
