### ISSUE TITLE
Build elasticsearch cluster

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#707]
We will be storing private student data in elasticsearch, including grades, so we need a FERPA compliant solution.  The elasticsearch services offered by Heroku aren't FERPA compliant, so we need to build our own cluster.

**Comment by noisecapella** [comment]
FYI @blarghmatey is setting up Bonsai instances for now, we'll want to replace them with our own cluster before we close this issue though

**Comment by pdpinch** [comment]
@blarghmatey how is this going?

**Comment by blarghmatey** [comment]
This has been deployed in its own VPC as a 3 node cluster of Elasticsearch servers. They are using the elasticsearch-readonlyrest-plugin to segregate access to the indices for pre-prod and production environments. The traffic is being proxied by Nginx to allow for TLS encrypted communications from the Micromasters app running in Heroku.
