### ISSUE TITLE
Run flow as part of tests

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#715]
This would mean requiring flow to pass in order to submit code. I think it's worth it IMO but we should wait for @pdpinch to get back to get his opinion

**Comment by aliceriot** [comment]
I also think it's worth it, there is extra time that goes into annotating types for things but the extra readability and correctness assurance it gives us is :100:

**Comment by aliceriot** [comment]
@noisecapella what do you think about tackling this soon? I think it would be good to enforce that flow should be passing on any JS changes.

**Comment by noisecapella** [comment]
It has a :+1: from me

**Comment by pdpinch** [comment]
Can one of you make the case to me? What's the end-user impact?

**Comment by noisecapella** [comment]
Less likelihood of JS bugs. It's a dev tool so there's no immediate end-user impact. We already have flow annotations in most places, this issue is just adding it to the list of things Travis checks for.
