### ISSUE TITLE
Allow instructors to compose an email to learners in search results

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#719]
_This issue depends on #669 (Learner Search) being done and is part of the actual implementation of #694. The issue to implement the actual sending of the email is #718_ 

After an instructor performs a learner search, they need a way to select any number of learners from the search results and compose a message to them. The following should be done for this issue:

- Add the "Email Selected" button (can be seen in the mockup in #669) to the search results page
- Keep in mind that these messages will be text-only for the time being
- When the message is submitted, post the message body and recipient list to the endpoint created is #718

@roberthouse54: Your input would be appreciated for the message composition part of this. The composition interface probably doesn't need much more than a simple text box, a submit button, and some simple display of the recipients. We could present this interface in a completely separate view, in a lightbox, or in some other manner that someone with actual design talent might think of 😄

**Comment by pdpinch** [comment]
Rob has a (simple) design for this.

**Comment by pdpinch** [comment]
When the user has selected a query through the search interface, we'll need to fetch *all* the users that match the query. We can do this by capturing the query search parameters and passing it to the API for the API to resolve ( #718 )

**Comment by pdpinch** [comment]
@roberthouse54 you showed me a preliminary design for this. Can you post it here?

**Comment by roberthouse54** [comment]
![send_email_dialog 2x](https://cloud.githubusercontent.com/assets/20047260/17027463/f639362c-4f31-11e6-8a00-4c337615d34d.jpg)

**Comment by aliceriot** [comment]
For this issue I'm going to implement just the basic email composition.

Addition tasks: 
https://github.com/mitodl/micromasters/issues/888
https://github.com/mitodl/micromasters/issues/889
