### ISSUE TITLE
Student Dashboard: Add a date column

### ISSUE THREAD

**Issue by jamiefolsom** [mitodl/micromasters#72]
As a student, I want to see both the relevant start or enrollment date, per #53, and my current grade if any.

This is currently handled in a single column ("status"), but needs to be in two.

<img width="414" alt="screenshot 2016-03-14 12 34 29" src="https://cloud.githubusercontent.com/assets/882377/13751575/2e8aa152-e9e1-11e5-997a-07e3a326bb52.png">

**Comment by pdpinch** [comment]
We're reconsidering this as we get some new designs from Nicholae

**Comment by pdpinch** [comment]
No longer part of the dashboard design
