### ISSUE TITLE
implement new page header / navigation design

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#723]
screenshot of the mockup:

![nav_header](https://cloud.githubusercontent.com/assets/6207644/16879304/0550cd04-4a7e-11e6-9900-84b1f8f4a2e3.png)

**Comment by Ferdi** [comment]
Not sure this is the final design, @roberthouse54 ?

**Comment by aliceriot** [comment]
we just spoke and this is final (just the navbar design)

**Comment by aliceriot** [comment]
@roberthouse54 I forget already, do we have an asset for the logo that will work?

**Comment by aliceriot** [comment]
if not I could throw the current asset in, which looks like this:

![current_logo](https://cloud.githubusercontent.com/assets/6207644/16887018/9f652184-4aa5-11e6-9829-4cb24de353e2.png)

and then file an issue to add the correct one later

**Comment by roberthouse54** [comment]
I will make the asset for you
