### ISSUE TITLE
implement new user menu design

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#724]
![nav_header](https://cloud.githubusercontent.com/assets/6207644/16879325/1aa98498-4a7e-11e6-81e2-a936e78c5c11.png)

**Comment by aliceriot** [comment]
@roberthouse54 have you come up with a design for the user menu dropdown? I can also just make something up! hahaha

**Comment by roberthouse54** [comment]
![user_dropdown](https://cloud.githubusercontent.com/assets/20047260/17105664/260bb8ee-5256-11e6-8877-392eb0618844.jpg)
