### ISSUE TITLE
UX: Facet on number of courses completed, number of courses enrolled

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#732]

**Comment by roberthouse54** [comment]
![image](https://cloud.githubusercontent.com/assets/20047260/17306268/1f0c2612-57fd-11e6-92e5-8f297779f553.png)

**Comment by roberthouse54** [comment]
I think here, we really only need the filter by "Number of Courses Completed". 

![courses_complete](https://cloud.githubusercontent.com/assets/20047260/17306333/932cba5c-57fd-11e6-9fe9-aa40098230fa.png)

**Comment by pdpinch** [comment]
If the histograms are as easy to implement as Alice thinks, I'd like to keep them. They reveal information about that the result set that's otherwise hard to see, e.g. whether most learners have completed the series (histogram skews right), or if most of them are just getting started (histogram skews left). 


Probably even more valuable for the average grade than the number of courses completed.

**Comment by roberthouse54** [comment]
Sounds good. I don't think we need them for # of courses completed.

**Comment by pdpinch** [comment]
Ok. We can close this once invasion is updated. 

I'll open a new issue for implementation.

**Comment by roberthouse54** [comment]
![courses_complete 2x](https://cloud.githubusercontent.com/assets/20047260/17334190/5350380e-58a3-11e6-88bb-807c3c68c118.png)

**Comment by roberthouse54** [comment]
I added the mock to Invision
