### ISSUE TITLE
Add e-mail opt-in to user settings 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#733]
There is already a field for opt-in in the user profile. We want to expose this to users via the user settings page. 

See https://github.com/mitodl/micromasters/blob/master/profiles/models.py#L93

For form text we can use something like:

```
<h4 class="privacy-form-heading">Who can see your profile?</h4>

<input type="radio">
<label>Yes, opt-in to e-mail</label>
<p>Send me occasional e-mails from MIT and MIT MicroMasters faculty and staff.</p>
<input type="radio">
<label>No, don't send me any e-mail<label>
<p>Don't send me any e-mail.</p>
``` 

We need to look into how to synchronize this setting with mailgun (in a separate issue)

**Comment by pdpinch** [comment]
Updated the description to include some pseudo-code including the form text. Make it look like the rest of the form. Once we have a screenshot, we can run it by Rob.

**Comment by amir-qayyum-khan** [comment]
<img width="1177" alt="screen shot 2016-07-20 at 6 41 10 pm" src="https://cloud.githubusercontent.com/assets/10431250/16988342/959f69fe-4ea9-11e6-8e01-cbefb21a1ef2.png">

**Comment by roberthouse54** [comment]
I am not sure that the copy is right for this. Basically, what we are doing (for V1) is to allow faculty and staff to send emails to users. In V2 we are probably going to allow students to send email to other students (maybe). I think even for V1 we should change the copy slightly. The way it is worded sounds linke you are opting in to spam/marketing emails. I am not sure what the right solution is here, but I think this needs a bit of discussion/clarification.

**Comment by Ferdi** [comment]
@roberthouse54 , I agree we can work with the wording a bit. Any ideas ?

> Basically, what we are doing (for V1) is to allow faculty and staff to send emails to users

And this is a setting for them to opt-out of these e-mails.  OK ?

**Comment by amir-qayyum-khan** [comment]
So you want to add checklist here
- list of email opt-in categories for example
 - Staff to students
 - Student to students

@pdpinch

**Comment by pdpinch** [comment]
Our [model for opt-in right now is a boolean](https://github.com/mitodl/micromasters/blob/master/profiles/models.py#L93) -- you're either in or out. In my draft of the copy, I was trying to make it work for just the V1 use case (faculty to students).

I'd prefer to not update the model at this time (as Amir proposed above) if we don't have to. Is there a way to finesse the copy to make that work?

**Comment by roberthouse54** [comment]
I mainly just think we should make it not sound like opting in to sort of marketing spam email.

Maybe:

"Email Preferences"
- "Faculty and staff can send me emails about the program"
- "I don't want to receive any emails"

In the future we will want to update this because:

1. We may build an in-app messaging feature
2. Even if we do not do so, we may want to allow students to email other students.
3. We should consider if we will publicly display user email addresses in the app.

**Comment by gsidebo** [comment]
100% agree with Rob, and those copy changes are a step in the right
direction. Are we sure we know exactly how instructors are going to use
this email? Is it possible that they will send out important course
announcements via email? If so, I don't think students should be given the
option to opt out at all. I'm quite sure that MIT students on campus don't
have a website/form where they can opt out of emails from instructors in
courses that they're enrolled in.

**Comment by pdpinch** [comment]
@amir-qayyum-khan please change the copy as [Rob suggests](https://github.com/mitodl/micromasters/issues/733#issuecomment-234261844) so we can move ahead. 

@gsidebo we can't predict how faculty will use e-mail, but they are encouraged to put important course announcements in the course itself. In addition, they can send e-mail from edx.org (which also has an opt out). 

We will have to decide how to apply this rule. I would suggest that it be used for any "campaign" e-mail, but not for any transactional e-mail. The former is our current use case.

**Comment by amir-qayyum-khan** [comment]
Done @pdpinch in PR https://github.com/mitodl/micromasters/pull/740

![screen shot 2016-07-22 at 4 06 41 pm](https://cloud.githubusercontent.com/assets/10431250/17055468/654e4814-5026-11e6-9d11-7fbacafa3465.png)

**Comment by roberthouse54** [comment]
Hey Amir... I don't know if it is too late to make a tiny tweak on this...

1. Can you remove the colon after Email Preferences
2. Can you change the first option to say "Faculty and staff can send me emails" --- (i.e. remove "about the program").

Thanks!

**Comment by amir-qayyum-khan** [comment]
let me do it

**Comment by amir-qayyum-khan** [comment]
fixed @roberthouse54 

<img width="1206" alt="screen shot 2016-07-22 at 10 04 00 pm" src="https://cloud.githubusercontent.com/assets/10431250/17064883/42f8a4b2-5058-11e6-8aa7-1e015d262993.png">
