### ISSUE TITLE
Student enrollments from edX 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#74]
As a student, I need to be able to get my enrollments from edX. 

There is an API we can use for this, which returns a list of courses the student is enrolled in. This list needs to be compared with the courses model. 

There is a curl command in the other story about this that covers the UI.

**Comment by justinabrahms** [comment]
I had some issues with mocking & stubbing w/r/t some teachersportal stuff. We were doing tons of mocking because we didn't have a good testing seam.

Let's take that lesson forward. If we had a class called EdXAPI (or similar) which housed these methods and the oauth dance.. that would make our lives much, much easier w/r/t testing.

Happy to answer any questions you might have about that or my experience there.

**Comment by giocalitri** [comment]
What's the actual scope for this PR?
with the enrollments retrieved via [edx-api-client](https://github.com/mitodl/edx-api-client/pull/5) in theory this story is limited to only retrieve the access token for the current user. 
Do I need to create only an interface for this?

**Comment by pdpinch** [comment]
This story is for the backend. There's a separate story for the react front-end. 

I presume the front-end will iterate through the list of courses in the micromasters and request the current user's enrollment status for each course. Does edx-api-client have an api  that fits that case?

**Comment by giocalitri** [comment]
So this story needs to provide a REST API for the enrollments?
This is fine. 
Just a couple questions: 
- should we return the list of enrollments intersected with the list of courses for micromasters? If so, do we have a list of Courses for the first micromaster?
- do you know how to identify a course where the user is enrolled with paid certificate?

**Comment by pdpinch** [comment]
I think we need to provide a REST API for the react front-end, unless it can communicate with edX directly. 

Courses are outlined on the SCM web site, http://scm.mit.edu/micromasters. I'll update this comment with course keys. 

The course enrollments API returns a field `mode` for each enrollment. I believe when the user pays the mode is set to `verified` (and not `honor` or `audit`).

**Comment by pdpinch** [comment]
| course number | example course key               | enrollment start | enrollment end | start date | end date |
|---------------|----------------------------------|------------------|----------------|------------|----------|
| CTL.SC0x      | course-v1:MITx+CTL.SC0x+3T2016   |                  |                |            |          |
| CTL.SC1x      | course-v1:MITx+CTL.SC1x_1+2T2015 |                  |                |            |          |
| CTL.SC2x      | course-v1:MITx+CTL.SC2x_2+2T2016 |                  |                |            |          |
| CTL.SC3x      | course-v1:MITx+CTL.SC3x+2T2016   |                  |                |            |          |
| CTL.SC4x      | course-v1:MITx+CTL.SC4x+1T2017   |                  |                |            |          |
| (final exam)  | ???                              |                  |                |            |          |

**Comment by justinabrahms** [comment]
@noisecapella and I talked a bit about this w/r/t TP. If you have two endpoints (one for all courses available, one for the user's specific enrollments) it allows for nicer caching strategies, at the expense of two RPCs. I think 2 RPCs will be fine, and think that would be the method that I'd personally pursue.

**Comment by pdpinch** [comment]
This was superseded by #125
