### ISSUE TITLE
add bpython to test_requirements.txt

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#751]
Can we? We have ipython in there already, and I prefer bpython to ipython and I'd like to use it for my django shell.

@giocalitri @blarghmatey

**Comment by blarghmatey** [comment]
👍

**Comment by aliceriot** [comment]
I have to admit I don't remember how to set django to use a different shell, I think giovanni did it for me when I was first getting set-up?

**Comment by blarghmatey** [comment]
I'm not sure off-hand. I can investigate if you need me to.

**Comment by aliceriot** [comment]
Nah it's cool, I forgot you can do it from the command line (`python
manage.py -i bpython`)

Alice
