### ISSUE TITLE
Update navbar to work well on mobile

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#753]
mobile!

**Comment by aliceriot** [comment]
@roberthouse54 do you have any ideas about what this should look like? if not no rush 😄

**Comment by roberthouse54** [comment]
![navbar_mobile 2x](https://cloud.githubusercontent.com/assets/20047260/17258804/a1aa58be-5596-11e6-82c0-05910dcd33fb.jpg)

**Comment by aliceriot** [comment]
awesome, thanks

**Comment by aliceriot** [comment]
@roberthouse54 is there anything else to do for this? I think maybe it should have been closed in #1460

**Comment by roberthouse54** [comment]
Yeah I think we should close this.
