### ISSUE TITLE
Implement user chip in search results

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#757]
When the user hovers over a search result, the "user chip" appears to reveal more information about the learner found in the result, and to present links to the learner's profile. 

For now, we will only implement the "View Profile" button on the user chip. Omit the user's e-mail address and the "Send Email" button that are in the design. 

From https://invis.io/9B804AMXA#/172058723_Instructor_User_Search : 

![instructor_user_search 2x](https://cloud.githubusercontent.com/assets/430126/17279018/06f81d7a-5739-11e6-86e6-ca8de762f2ee.png)

- [x] @roberthouse54 please confirm this description

**Comment by roberthouse54** [comment]
https://invis.io/3D84YKICW#/178075727_User_Chip

![user_chip 2x](https://cloud.githubusercontent.com/assets/20047260/17299596/fd6015ac-57dc-11e6-8b74-760e86a5c14e.png)

**Comment by pdpinch** [comment]
Clicking the profile button opens the learner's full profile page.

**Comment by pdpinch** [comment]
Will require a new component, although it's not very complex.
