### ISSUE TITLE
Course run facet

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#758]
As faculty or staff member, I need to be able to facet learner on particular runs, so I can target my messaging more closely. 

Proposal: add a facet that allows the user to select particular runs. Runs will need to be identified by their date(s) (start and/or end), since most course runs have the same title. 

This issue is for the UX design. There will be separate issue for implementation.

**Comment by roberthouse54** [comment]
This design is for selecting "Completed Courses" ... each course can be expanded to show runs, which are displayed by date. (Where can we get this data?)  --- note, the Current Courses is a separate section in the search filters, and it does not have runs. It is assumed that Current means the current run only.

![completed_courses_facet](https://cloud.githubusercontent.com/assets/20047260/17307681/5f493c5e-5804-11e6-8fce-c575f6775576.png)

**Comment by pdpinch** [comment]
Doing this as a hierarchical menu increase the coding complexity. Can we just load all the runs in a simple facet?

Something like:

[ ] Supply Chain Logistics and Fundamentals (started 9/24/14)
[ ] Supply Chain Logistics (started 5/20/15)
[ ] Supply Chain Logistics (started 5/6/16)

There are a couple of places where we can get this data. I believe we're currently picking it up from user enrollments, or from our own database.

**Comment by roberthouse54** [comment]
These strings are very long an will likely truncate the only part that is a unique identifier (the start date). I would rather do this as a hierarchical menu if possible. We could use start date as the Run identifier in the UI. Also... aren't we planning on using a hierarchical menu in the "Current Residence" facet? Is it more complex to do it here?
