### ISSUE TITLE
Fetch the user's current grade when viewing the dashboard

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#762]
As a learner, I want to see my current grade on the learner dashboard whenever I open it.

Since fetching grades can be slow, but they update relatively infrequently, we'll need to a simple caching mechanism. If you work on this issue, please explain the caching strategy on this issue. 

Depends on mitocw/edx-platform#259

**Comment by noisecapella** [comment]
When doing this issue we should make sure to handle failed courses too since they make use of the same current grade data

**Comment by pdpinch** [comment]
@giocalitri was this issue covered already by #1094?

**Comment by giocalitri** [comment]
Yes, it was.

**Comment by pdpinch** [comment]
I'll close it then.
