### ISSUE TITLE
Update current grades when batch updating learner data from edx.org

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#763]
When we batch update learner data from edx.org we need to also update current grades. 

Related to #671 and #762.

Depends on mitocw/edx-platform#259

**Comment by pdpinch** [comment]
@giocalitri was this issue covered already by #1094?

**Comment by giocalitri** [comment]
No, I actually forgot to implement the batch update part in that PR.
Please assign this issue to me: I will work on it asap.
