### ISSUE TITLE
Search: grade facet

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#765]
## Acceptance Criteria

- [ ] This facet is only active when a course has been chosen in the course facet. Otherwise it is not populated.
- [ ] Histogram is populated with the grades of the user in the current result set.

**Comment by pdpinch** [comment]
@roberthouse54 do you think we could facet on all current grades instead of trying to come up with an average grade for each learner?

Most learners will have only one current grade, because they will only be taking one course at a time.

For learners that have more than one current grade, they could get double-counted in the facet UI, but I don't think that's necessarily a problem?

I don't know yet which is easier to implement.

**Comment by roberthouse54** [comment]
I think that sounds like it should work. It will be the same UI as Average Grade, but with a different label (presumably, "Current Course Grade".)

**Comment by roberthouse54** [comment]
I updated the design for the User Search on Invision to show this new facet. I have also reordered the facets somewhat, to make a clearer grouping.

https://invis.io/6G85GNOH8

**Comment by pdpinch** [comment]
Added screenshot from https://invis.io/6G85GNOH8 to description.

**Comment by pdpinch** [comment]
Closed in favor of #1711
