### ISSUE TITLE
Dashboard: New UI/UX to match current designs

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#766]
As seen in [MM2 on Indesign](https://invis.io/9B804AMXA#/172619323_Dashboard)

![dashboard 2x](https://cloud.githubusercontent.com/assets/430126/17280439/1232a8ac-575e-11e6-93dd-8e4a36fe4d2d.png)

- [x] update to current header
- [ ] only implement "dashboard" in the top nav for now
- [x] Update the user widget
- [ ] Update the courses widget (except for current grade, and pricing)
- [ ] Add tool tip widget, to explain "verified" See https://projects.invisionapp.com/share/H486ZHFJ3#/screens
- [ ] Fix #780 Dashboard looks different in FireFox

This issue does not include:

- Grading curve widget
- Learners near you widget
- Progress widget
- My Groups widget
- Current grades in t

**Comment by aliceriot** [comment]
@pdpinch the new navbar and user menu designs have already been completed (I did them last week).

**Comment by pdpinch** [comment]
I ticked off the first item in the description. Does that match what's done?

**Comment by aliceriot** [comment]
2nd one too

**Comment by aliceriot** [comment]
this is what the navbar currently looks like:
![mm](https://cloud.githubusercontent.com/assets/6207644/17299203/58375a3c-57db-11e6-965e-f42e95951c47.png)

**Comment by pdpinch** [comment]
This is no longer blocked. @roberthouse54 updated the i[nvision design](https://invis.io/TJ85H2WK2#/172619323_Dashboard) to omit pricing information, until we get that resolved.

**Comment by pdpinch** [comment]
I added a checkbox for adding a tooltip for "verified" per https://projects.invisionapp.com/share/H486ZHFJ3#/screens

**Comment by noisecapella** [comment]
We don't currently have a way to tell if the user failed, right? cc @giocalitri

**Comment by giocalitri** [comment]
@noisecapella yes, the rest API is able to say if the user failed
