### ISSUE TITLE
Dashboard: Progress widget

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#767]
As a learner I would like to see at glance how much of the MIcroMasters program I have completed. 

For MVP, this widget should just reflect how many courses in the MIcroMasters program the user has completed. So if the user has completed 3 courses and has started the 4th, the widget should display 60% (i.e. 3/5). 

The button "apply for micromasters" should be greyed out and inactive until the user has reached 100%. 

From [MM2 on invision](https://invis.io/9B804AMXA#/172619323_Dashboard):

![image](https://cloud.githubusercontent.com/assets/20047260/17335868/9d50a334-58a9-11e6-91bc-3076eebac236.png)

Questions for @roberthouse54 :

- [x] What do we do for a user with 0% complete? **display "0/x Course complete"**
- [x] Are fractions or percentages clearer for learners? **we chose fractions (see below)**

**Comment by pdpinch** [comment]
The circle will require some SVG work.

**Comment by roberthouse54** [comment]
OK, I have updated this to show "2/5" courses complete, instead of a % complete. In the case of 0 complete, just show "0/5 complete", etc.

![progress_ 2x](https://cloud.githubusercontent.com/assets/20047260/17335868/9d50a334-58a9-11e6-91bc-3076eebac236.png)

**Comment by pdpinch** [comment]
@roberthouse54 for users who are 0% complete, do we hide the widget altogether, or do we display with "0 / 5" and a completely green circle?

**Comment by roberthouse54** [comment]
In the case of 0 complete, show "0/5 complete", and green circle

**Comment by amir-qayyum-khan** [comment]
@here there is example of circular progress bar

https://github.com/wmartins/react-circular-progress
Demo
http://wmartins.github.io/react-circular-progress/


Svg file used in above sample is [code](https://github.com/wmartins/react-circular-progress/blob/gh-pages/src/js/components/CircularProgress.react.js#L20). 
**Can i get our own design svg file**

@pdpinch

**Comment by roberthouse54** [comment]
Is there any reason we cannot just do this with code, like in the example above?

**Comment by noisecapella** [comment]
The SVG required to do this shouldn't be that complicated. It should be similar to how they do it in their render function.

**Comment by pdpinch** [comment]
@roberthouse54 besides the color difference (which I assume is trivial to change), the only difference is the tick marks. Can we omit those for now?

**Comment by roberthouse54** [comment]
Yes, that is fine.
