### ISSUE TITLE
Dashboard: People near me widget

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#768]
As a learner, I'd like to be able to connect to learners who are near me. 

This widget will also be a way to make learners aware for the learner profile search and the group features, when those are ready. 

For MVP, the search results will be based on learners in the same city. The search results will be capped at 12 learners. We will omit a link to learner profile search or "create a group" until those features are ready.

**Comment by pdpinch** [comment]
@roberthouse54 will hovering off the user's avatar display a [user chip](https://github.com/mitodl/micromasters/issues/757)?

**Comment by roberthouse54** [comment]
Yeah, we should show the same user chip here. Giovanni suggested that we match on Region/state instead of City, which I think is a good idea. If we are limiting to only show 12 results (max.), we could in theory sort by City matches first, if there are any, then show Region/State matches.

**Comment by pdpinch** [comment]
This is a duplicate of #600
