### ISSUE TITLE
Update profile forms design

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#769]
Update the styling of the profile forms and the TOS page to match the current designs in [MM2 on invision](https://invis.io/9B804AMXA#/172057957_Signup1).

![singup1 2x](https://cloud.githubusercontent.com/assets/430126/17280783/03200792-5763-11e6-989c-43e7f66f8be2.png)
![signup2 2x](https://cloud.githubusercontent.com/assets/430126/17280784/05a5ba5c-5763-11e6-99a3-46152e09f5ee.png)
![signup2c 2x](https://cloud.githubusercontent.com/assets/430126/17280785/08647b5c-5763-11e6-81b4-28079b5c375d.png)
![signup2b 2x](https://cloud.githubusercontent.com/assets/430126/17280786/0a9d5b00-5763-11e6-9bcc-c68b299bbe1c.png)

**Comment by gsidebo** [comment]
UI & updates to the model for Nationality will be done in a separate story

**Comment by aliceriot** [comment]
@roberthouse54 I have a question about the ToS, it looks we're just adding a checkbox for it on the first profile screen. How should we display the ToS itself (the actual copy)? accordion-ey thing that opens up? link that opens in another tab?

**Comment by roberthouse54** [comment]
Can we do it as a dialog like this? Also, make the "Terms of Service" a link with default link style.

![tos](https://cloud.githubusercontent.com/assets/20047260/17409935/6324c55e-5a3f-11e6-88a6-33f53f68365c.png)

**Comment by aliceriot** [comment]
Sure, do we want the popup to appear when the user clicks 'next'?

**Comment by roberthouse54** [comment]
I was thinking it would only appear if they click on the Terms of Service link.

**Comment by aliceriot** [comment]
ok, so there's two separate places they can agree? the checkbox and the 'I agree' button?

**Comment by roberthouse54** [comment]
Yes, so if they open the dialog, and click "I agree", it would close the dialog and check that box.

**Comment by aliceriot** [comment]
cool, that sounds good to me

**Comment by pdpinch** [comment]
Shouldn't make a difference, but I'll mention it just in case: we'll probably be adding another paragraph to the TOS, to cover FERPA issues (if they're not already covered).

**Comment by aliceriot** [comment]
@roberthouse54 I just wanted to clarify the behavior of the yes / no switches on the education form.

Currently, we have the little switch in the corner. If you turn it on, you can add entries to that degree level. If you switch it off, it prevents the display of the whole form component (the add button and so on), and if you currently have entries added it asks you to confirm if you want to delete them.

How should the switch behave in the new design? Currently it looks like you have the switch only appearing when the user hasn't yet entered any entries.

**Comment by roberthouse54** [comment]
Hi Alice. Sorry this was not clear in the design. I think I didn't think it through fully. 

So in the initial state, if the user checks "No", this basically doesn't do anything. If the user clicks Yes, it opens the dialog. If they enter something, then we display the entry with edit/delete links, and a link to "Add Another". If they later delete all the entries and hit save, then the card goes back to the default state, with "No" selected. (I think that makes sense, but if not, or if this is unclear, please ping me.)

**Comment by roberthouse54** [comment]
Also, I never mocked up the employment page, but it is the same UI. The text will be "Do you want to enter an employer?"

**Comment by aliceriot** [comment]
Yes that makes sense to me. I can implement the same thing on the employer page too.

**Comment by aliceriot** [comment]
@pdpinch code so far is up here: https://github.com/mitodl/micromasters/compare/ap/new-profile-forms

**Comment by pdpinch** [comment]
Yikes, 41 files? If there's a way to break it down, please do so -- if only for the sake of your reviewers.

**Comment by aliceriot** [comment]
pulling out the ToS dialog component: https://github.com/mitodl/micromasters/issues/814
