### ISSUE TITLE
Clean instructions in README for docker-osx-dev

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#77]
Also update cookiecutter

**Comment by pwilkins** [comment]
"Clean instructions..." means what?  Do you mean add instructions for ``docker-osx-dev`` using the Teacher's Portal ``README.md`` as an example and convert that from RST format to Markdown?  (I've got an open PR #119 for that.  :-) )

**Comment by pwilkins** [comment]
I spoke with George out-of-band.  He wants the ``docker-osx-dev`` instructions cleaned-up.  For example, the ``Makefile`` re-installs ``docker`` each time it's run.  Granted, it doesn't do anything if ``docker`` is already installed, but it is still an extra step.
