### ISSUE TITLE
UX: Revise designs for User Profile view

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#770]
We need updated designs for the user profile, including a staff version that includes grades and a learner/not logged in version that does not.

**Comment by pdpinch** [comment]
I'll close this once invision has been updated and there's an issue for implementing.

**Comment by roberthouse54** [comment]
![user_profile 2x](https://cloud.githubusercontent.com/assets/20047260/17299343/fd1e1b6c-57db-11e6-87e9-c60d619f3179.jpg)

**Comment by pdpinch** [comment]
@roberthouse54 [this screenshot](https://github.com/mitodl/micromasters/issues/770#issuecomment-236616886) is for learners or users who haven't logged in. 

Do we have a version for staff, i.e. with grades?

**Comment by pdpinch** [comment]
Opened an issue for the learner/not-logged-in view: #795

**Comment by roberthouse54** [comment]
I don't have a design for staff with grades.
