### ISSUE TITLE
Change index to store users based on Program enrollments

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#778]
_This is replacing #774. For more details on why this indexing change is needed, read the description of that issue_

To get around some Elasticsearch limitations, we will be changing the structure of our index. We will be creating one indexed document per Program enrollment rather than per User. This means that a User enrolled in 2 Programs would have 2 documents in the index. In terms of Program-related data (enrollments, grades, etc), only the information that is directly linked to the given Program would be a part of the document.

**Comment by pdpinch** [comment]
Can this be closed?

(I was reminded recently that we if we write "fixes" before the issue number in the PR description, the issue will close automatically.)
