### ISSUE TITLE
Add configuration to authenticate against Elasticsearch

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/micromasters#782]
In order to provide some measure of access control to our Elasticsearch cluster we will be using the elasticsearch-readonly-reset plugin (https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/wiki/Supported-Rules). This will require handling authentication in the proxy API based on environment variables.

/cc @giocalitri @noisecapella

**Comment by pdpinch** [comment]
This is blocked by #707 but otherwise ready

**Comment by blarghmatey** [comment]
The elasticsearch cluster will be configured to require an API key passed in an `X-Api-Key` header in order to access the indices. This header will only need to be set in pre-prod and production environments. Per @giocalitri there should be a constructor method for retrieving the client instance for any code that is interfacing with Elasticsearch.

As specified [here](https://elasticsearch-dsl.readthedocs.io/en/latest/configuration.html#default-connection) the header can be passed as a kwarg which will ultimately be passed to the [connection class](http://elasticsearch-py.readthedocs.io/en/master/connection.html#urllib3httpconnection-default-connection-class).
