### ISSUE TITLE
Upgrade flow

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#784]
When I upgrade flow locally there are many extra warnings which need fixing

**Comment by aliceriot** [comment]
oh noes  :(

**Comment by aliceriot** [comment]
I started fiddling with this a bit, it looks like the lib definition we've been using for redux and moment aren't being updated to work with flow v 0.30, what do you think about using https://github.com/flowtype/flow-typed instead?

**Comment by aliceriot** [comment]
it's a bit weird, there's a CLI that we use to 'install' definition files that we check in.

**Comment by aliceriot** [comment]
(there doesn't seem to be a way to just include them as dependencies)

**Comment by aliceriot** [comment]
I'm working on it!
