### ISSUE TITLE
Update styling for user profile view

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#795]
For example, the URL at /users/pdpinch should look like

![user_profile 2x](https://cloud.githubusercontent.com/assets/20047260/17299343/fd1e1b6c-57db-11e6-87e9-c60d619f3179.jpg)

instead of 

![/users/pdpinch](https://box.everhelper.me/attachment/540634/5b9e34bf-3230-4d23-90b2-5cf4f94c3cb7/623857-1KnJn2tsWZStP14w/screen.png)

**Comment by pdpinch** [comment]
@amir-qayyum-khan if you get a chance, let us know if there's a branch for this.

**Comment by amir-qayyum-khan** [comment]
I did some work into it but not  complete https://github.com/mitodl/micromasters/pull/864

**Comment by amir-qayyum-khan** [comment]
@roberthouse54 @pdpinch 

- I need an email icon just like in screen shot with email.
- I need a Camera Icon, just like in screenshot above user image.
- What about the ``About section``. Do i need to add it or take it from some where?

<img width="652" alt="screen shot 2016-08-23 at 6 37 31 pm" src="https://cloud.githubusercontent.com/assets/10431250/17894026/4ab0675e-6961-11e6-9f5e-84470fa0e68b.png">

**Comment by pdpinch** [comment]
Skip the about for now. That will be another issue (probably after our 10/15 release)

**Comment by amir-qayyum-khan** [comment]
OK,

change in design, removed border line for last row.

<img width="652" alt="screen shot 2016-08-23 at 6 37 31 pm" src="https://cloud.githubusercontent.com/assets/10431250/17894772/02f548d2-6964-11e6-9195-29d0aacb79c5.png">

**Comment by Ferdi** [comment]
What does "Edit" do ?

**Comment by amir-qayyum-khan** [comment]
@Ferdi I asked the same question from @roberthouse54  https://github.com/mitodl/micromasters/issues/795#issuecomment-241734593, From mockups it seems they disable row wise editing and enabled editing for whole section i.e education or work history.

**Comment by roberthouse54** [comment]
Here is a revised design with inline editing.
![profile 2x](https://cloud.githubusercontent.com/assets/20047260/17941451/5ec0bf78-6a01-11e6-9f15-28328beb3bb0.png)

**Comment by roberthouse54** [comment]
![profile_v2 2x](https://cloud.githubusercontent.com/assets/20047260/17941505/a257eefa-6a01-11e6-9cc2-b18d68e154b4.png)

**Comment by amir-qayyum-khan** [comment]
@roberthouse54 made changes, also sent you email regarding icons

<img width="1276" alt="screen shot 2016-08-25 at 7 12 09 pm" src="https://cloud.githubusercontent.com/assets/10431250/17972365/f1e90048-6af7-11e6-9b84-0fadb0e5b5af.png">

**Comment by pdpinch** [comment]
Rob, is there any chance we can use fontawesome (or another font) for these icons?

It just makes it easier to keep track of assets.

**Comment by roberthouse54** [comment]
We are using standard material design image assets. If there is a font awesome set for material design icons I am fine with that. In short, I don't really care how it is done, but I want them to look like the standard material design icons.

**Comment by amir-qayyum-khan** [comment]
Fixed via https://github.com/mitodl/micromasters/issues/864
