### ISSUE TITLE
Learner Dashboard: allow learner to switch between MM programs (program context)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#796]
As a learner, I need to be able to see my progress in all micromasters that I'm a member of. 

We will add a component to the top nav of learner dashboard with a drop-down list of all the MM programs the current user is registered for. 

![contexts 2x](https://cloud.githubusercontent.com/assets/430126/18054853/98db074c-6dd3-11e6-8a86-dbb188966614.jpg)

# Acceptance Criteria / Tasks

- [x] 1. Update the dashboard API to return data only for the current program. 
- [x] 2. API for updating the user's programs (#953)
- [x] 3. All live programs appear in the drop-down list
- [ ] 4. modal to allow user to enroll in additional programs
- [x] 5. Remove the signals handlers that update the program enrollment based on the CachedEnrollment model: the Program Enrollment will be updated only via REST API.

# Related issues

- #917 Sign Up / Get Started Modal 
- #833 Refactor dashboard API

**Comment by pdpinch** [comment]
@giocalitri Does this cover the dashboard context, or is there more?

**Comment by giocalitri** [comment]
We need to update the dashboard rest API to take in input the id of the program and return data about only that one.

This means that we need to somehow pass the list of the programs to the UI. This is important also to build the dropdown menu itself. Probably it makes sense to build a new REST API specific to this purpose.

If there are other parts that need to be modified, I will add another comment

**Comment by pdpinch** [comment]
Ok. I updated the description.

**Comment by pdpinch** [comment]
Updated screenshots

**Comment by giocalitri** [comment]
If this story includes also the enrollment in the program (it seems so from the latest screenshots), then, in addition to what I wrote before, we need also to:

1. create a rest API to enroll the user in a program (the program enrollment model already exists).
2. create something (a view?) where we can send via parameter and preselect the program where to enroll and just enroll the user (use case is a user that clicks "enroll in this program" from the program marketing page: we do not want to ask her again).
3. Remove the signals handlers that update the program enrollment based on the `CachedEnrollment` model: the Program Enrollment will be updated only via REST API.

**Comment by giocalitri** [comment]
I think I need clarification about 

>  If the learner is in only one MicroMasters, we will omit the component:

from the description

**Comment by pdpinch** [comment]
@roberthouse54 that was an older UX that we've scrapped. The drop-down will always be present.

**Comment by pdpinch** [comment]
I updated the description to include Giovanni's items from https://github.com/mitodl/micromasters/issues/796#issuecomment-243155135 except his no. 2 is part of issue, #917

**Comment by noisecapella** [comment]
Per conversation with @roberthouse54 the snackbar will show up for 3 seconds and then go away. There won't be an `x` to click

**Comment by Ferdi** [comment]
@pdpinch is 4) in your "acceptance criteria" list tracked anywhere ?

**Comment by Ferdi** [comment]
@pdpinch never mind. It looks like it's #1000
