### ISSUE TITLE
Create models for mail

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#804]
In our first messaging feature #694, we need to keep track of sent mail, so we can build a view for staff that allows them to resend mail to students who entered the group since the last mailing. We also want to be able to report on delivery and open rates. 

 In the future, we will want to support things like two-way mail, a web-based inbox and research on messaging. 

a quick list of fields:

- subject
- body
- to list
- query/group used to create the to list (a separate object?)
- external message id (i.e. mailgun)
- delivery count
- open rate

**Comment by gsidebo** [comment]
Closing in favor of #830
