### ISSUE TITLE
create models for groups (for mail and other features)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#806]
We plan to use search queries ("learners near me" or "people who passed sc1x with at least 90%") to create groups. These groups can be used to send mail, or create chat rooms, or message in other ways. 

We need a way to store a reference to a group, including the query and (perhaps) a manifestation of the group. In some cases, we'll want the group to be dynamic (adding and removing users from a chat room) but other uses may be fixed (the list of users who were sent an e-mail).

**Comment by gsidebo** [comment]
Closing in favor of #830
