### ISSUE TITLE
Change birth country for fake users to not match current country

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#813]
The birth location seems to match the current location exactly for all fake users, but these should deviate at least some of the time

**Comment by gsidebo** [comment]
good idea. should be an easy change. that reminds me that i should put the generation scripts into a gist at some point

**Comment by pdpinch** [comment]
I think it would be easier to find them if they were part of the docs.

>  that reminds me that i should put the generation scripts into a gist at some point
