### ISSUE TITLE
Add ToS agreement to the profile signup flow

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#814]
need to:

- [x] add a checkbox to the personal form that sets `profile.agreed_to_terms_of_service`
- [x] add a dialog component that shows the actual ToS text
- [x] tests n stuff

pulled from #769

**Comment by pdpinch** [comment]
Do you think we can finish this during [this sprint](https://github.com/mitodl/micromasters/milestone/12)?

**Comment by aliceriot** [comment]
yes, this work is already done, I'm just separating it out so that the PR for updating the form style isn't too big

**Comment by aliceriot** [comment]
@pdpinch do you have the updated ToS copy handy?

**Comment by pdpinch** [comment]
Sorry for the delay. I added two comments to the PR: https://github.com/mitodl/micromasters/pull/822/files#r74312469 and https://github.com/mitodl/micromasters/pull/822/files#r74312607

**Comment by aliceriot** [comment]
no worries :)
