### ISSUE TITLE
Update profile progress widget to latest design

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#820]
as seen here: https://projects.invisionapp.com/share/9B804AMXA#/screens/178066345

pulled out of #769

**Comment by pdpinch** [comment]
I think the invision link is wrong -- the ui is better demonstrated at https://invis.io/NB7VM1GSG#/172058003_Signup2b right?

Or this:

<img width="550" alt="screen shot 2016-08-19 at 8 31 37 am" src="https://cloud.githubusercontent.com/assets/430126/17809876/86ce0f8e-65e7-11e6-96f9-43e2463043da.png">
