### ISSUE TITLE
Create a Mailgun account for MIT ODL

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#831]
https://www.mailgun.com/signup

Pretty obvious: To use Mailgun, we need an account. Price is based on usage, so I don't believe we need to worry about payment (yet)

**NOTE TO WHOMEVER DOES THIS:** I experienced an issue with activation emails from Mailgun (which still hasn't been resolved). Mailgun activation emails will most likely be sent to spam quarantine when you sign up. I say 'most likely' because I'm not able to log into spam quarantine to check. Activation emails to me and invitation emails to Peter never reached our MIT inboxes

**Comment by blarghmatey** [comment]
This has been set up to use the mitx-devops@mit.edu email address. Credentials are in the keepass database located in mitx-sysdocs. The subdomain that is configured for use is micromasters.mit.edu.
