### ISSUE TITLE
Key prop error when running tests

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#835]
CourseList
        ✓ renders apply for master button and text (380ms)
        ✓ renders courses using util functions (285ms)
    
      ErrorInfo
        unit tests
          ✓ should render an error and message on the error_code and user_message attributes
          ✓ should render an error and message on the error_code and detail attributes
          ✓ should render an error and message on the errorStatusCode and user_message attributes
          ✓ should render an error and message on the errorStatusCode and detail attributes
        showing errors on pages
          dashboard page
            ✓ error from the backend triggers error message in dashboard (119ms)
            ✓ the error from the backend does not need to be complete (93ms)
            ✓ the error from the backend does not need to exist at all as long as there is an http error (90ms)
            ✓ a regular response does not show the error (205ms)
          profile page
            ✓ renders errors when there is an error receiving the profile (70ms)
          user page
            ✓ should show an error for profile GET (62ms)
    Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `EmploymentForm`. See https://fb.me/react-warning-keys for more information.
            ✓ should show an error for profile PATCH (537ms)

**Comment by aliceriot** [comment]
I think this was my doing...

**Comment by aliceriot** [comment]
yup
