### ISSUE TITLE
Remove "New Group from Selected" button in search results

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#852]
We don't have a feature that uses this yet. 

![image](https://cloud.githubusercontent.com/assets/430126/17684730/b09c096a-632b-11e6-9265-1aa8f926e508.png)

**Comment by pdpinch** [comment]
Hey @aliceriot did you just pick this up in passing while you were working on the e-mail form?

**Comment by aliceriot** [comment]
No, I was looking through the issues and this looked really small so I grabbed it. Opening the pr took about 2 minutes.
