### ISSUE TITLE
Facet by Company

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#863]
Company is currently a free text field, where the user can enter multiple values. We can make this a simple flat text facet, although the list may be very long.

**Comment by roberthouse54** [comment]
I think for this, we should use a react select search field.

**Comment by roberthouse54** [comment]
The "Company" facet will use the react-select typeahead field. 
![image](https://cloud.githubusercontent.com/assets/20047260/21404984/e93bcb5a-c791-11e6-8c6e-a1249c1359d2.png)
