### ISSUE TITLE
username is not indexed in elasticsearch

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#870]
Looks like all the results coming back have `null` in the username field. I don't understand what's going on in the elasticsearch python code too much, but it looks like we're not accounting for the fact that `username` is a property on `User` and not on `Profile`.

**Comment by aliceriot** [comment]
@noisecapella and I determined it probably has to do with the fake users not having social auth information.

**Comment by noisecapella** [comment]
It looks like this happens because the fake users don't have social auth information, and we access the edX social auth information whenever we want to get the username. We could create fake social auth accounts too, not sure if this is important to fix though

**Comment by aliceriot** [comment]
It does mean that we cannot test out features that rely on the username with these fake users

**Comment by gsidebo** [comment]
this should be solved by #883. ill close this when that gets merged

**Comment by pdpinch** [comment]
@gsidebo can we close this now?

**Comment by noisecapella** [comment]
Yes, this should be fixed
