### ISSUE TITLE
Dashboard error when no programs are live

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#872]
This is an edge case for sure, but if there are no Programs with live=True in data, the dashboard page fails and the loading spinner spins forever

The line of code that effectively causes this is in static/js/containers/DashboardPage.js:

`if (dashboard.errorInfo === undefined && dashboard.programs.length > 0){`

**Comment by pdpinch** [comment]
This should raise the ImproperlyConfigured error used elsewhere.

**Comment by pdpinch** [comment]
this may be fixed already
