### ISSUE TITLE
Search page error and poor visual state when user lacks staff/instructor role 

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#876]
![ss 2016-08-17 at 12 08 27](https://cloud.githubusercontent.com/assets/14932219/17743929/a3542c6c-6473-11e6-81d0-5d41f96dfaf0.png)

When the logged-in user does not have staff/instructor permissions for any programs, the Learners tab is still visible/clickable and this is what it shows. We should either hide the Learners tab or show some descriptive error on this screen

**Comment by pdpinch** [comment]
Learners won't have a way to access this view. Eventually this will be replaced by the learners search for learners ui, #935
