### ISSUE TITLE
Update realistic user generation command for programs & social username

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#879]
Two updates are needed in the gen_realistic_search_data command:

1. Fake programs should be set to live=True
1. A social username should be created for each fake user (ie: we need to make sure that profiles.api.get_social_username returns a value for these users)

**Comment by pdpinch** [comment]
What happens when programs.live is false?

**Comment by pdpinch** [comment]
Can you put an estimate on this?

**Comment by gsidebo** [comment]
@pdpinch 

1. certain parts of our code depend on 'live' being true for programs (see: [this bug](https://github.com/mitodl/micromasters/issues/872))
1. estimate is a 1, since thats about how long it took me 😄
