### ISSUE TITLE
Add new fields to user profile model

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#88]
includes designing the data model and updating the profile API

See list referenced here: https://github.com/mitodl/micromasters/issues/18#issuecomment-198034861

**Comment by pdpinch** [comment]
This should wait until we've done some discovery around integrating with other services, particularly LinkedIn.

**Comment by pdpinch** [comment]
LinkedIn didn't pan out, so we'll do this all by hand, based on the fields described in https://docs.google.com/spreadsheets/d/1ehN3FNymCOhpJT7h9XZDOITP_lOFDnEcStRa0le4MX8/edit?pref=2&pli=1#gid=0

users will have a profile card for personal, employment and education. 

personal info can be added directly to the profile model, but employment and education will be one-to-many

**Comment by pdpinch** [comment]
We'll start by focusing on the personal data, so as not to block the work on the front-end.

**Comment by noisecapella** [comment]
I will be getting rid of these fields collected from edX:

 - bio
 - requires_parental_consent (we will add validation that birthdate is at least 13 years)
 - goals
 - language_proficiencies
 - mailing_address
 - linkedin

There are other fields related to education or employer that will be migrated to our new model in some future issue

**Comment by pdpinch** [comment]
@Ferdi should we keep language_proficiencies ?

I agree that the rest of these can go.

**Comment by Ferdi** [comment]
Can we keep them all there ? And for the moment dont expose them in the UI ?

**Comment by noisecapella** [comment]
Closed by #180 
@Ferdi the fields have been renamed but not deleted except for year_of_birth which we can't really use and will be replaced by date_of_birth which we ask for
