### ISSUE TITLE
Search facet expand carets are spilling out of their container (Chrome, Safari)

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#881]
![ss 2016-08-17 at 17 33 20](https://cloud.githubusercontent.com/assets/14932219/17754079/dcdd8d34-64a0-11e6-8d2a-bd26db82cbde.png)

The search facet expand carets jut out to the left of the containing element

**Comment by pdpinch** [comment]
Is this still an issue?

**Comment by pdpinch** [comment]
I don't think this is an issue any more.
