### ISSUE TITLE
implement frontend interface for email API

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#889]
depends on #719

**Comment by pdpinch** [comment]
Is this closed by #900 ?

**Comment by aliceriot** [comment]
No, this is for writing the actual code to make the API requests.

**Comment by pdpinch** [comment]
So it's blocked by #718 -- is that far enough along yet that this can be started?

@gsidebo

**Comment by gsidebo** [comment]
not yet. PR will be up today
