### ISSUE TITLE
Fix home and program page styling on dev instance

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#892]
This was caused by the fix I made in #886. If you go to the home page in your local instance you see this:
![screenshot from 2016-08-19 16-02-14](https://cloud.githubusercontent.com/assets/863262/17822696/715760ee-6626-11e6-8470-d9f802a5ec17.png)

https://micromasters-ci.herokuapp.com is fine, not sure why there's a difference

**Comment by pdpinch** [comment]
This was fixed incidentally by other styling changes.
