### ISSUE TITLE
The circle in the progress widget should be filled starting at 12 noon, filling counter clockwise. 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#896]
As a learner, I want to know how I'm progressing towards completion of my program. 

Like this
<img width="241" alt="screen shot 2016-08-22 at 3 28 27 pm" src="https://cloud.githubusercontent.com/assets/430126/17868570/57cc9046-687d-11e6-9cd6-87d2874649ff.png">

Not this (it looks like this starts at 3 o'clock and fills clockwise)
<img width="241" alt="screen shot 2016-08-22 at 3 28 27 pm" src="https://s3.amazonaws.com/uploads.hipchat.com/151776/2201274/uWN6V8HBPNGIbnP/Screen%20Shot%202016-08-22%20at%203.20.33%20PM.png">

**Comment by pdpinch** [comment]
@amir-qayyum-khan what's the status of this?

**Comment by amir-qayyum-khan** [comment]
i have done anything on it, let me start
