### ISSUE TITLE
Create an order receipt page

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#904]
This is the page which the user will be redirected to after a successful payment on cybersource

**Comment by pdpinch** [comment]
@roberthouse54 has a design for this, but it's just the dashboard with a banner. Is that OK?

https://invis.io/9B804AMXA#/182566039_Mm_Dashboard_After_Ecommerce

**Comment by noisecapella** [comment]
This is fine. We can send the receipt url '.../dashboard/?order=MM-xx' and use the order number to show the receipt
