### ISSUE TITLE
Home: Sign Up / Get started modal

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#917]
Implement Sign Up workflow:

![popup](https://cloud.githubusercontent.com/assets/125561/18008479/468186ce-6b76-11e6-97f3-850730501ac0.png)

Acceptance criteria:

- [x] Add pop-up modal form to home page, including drop-down for user to choose
Program. On home page, user chooses program. 
- [x] Add pop-up modal to program page; determine learner's program from the page. On Program page, we can set program to the current page's program. 
- [x] Open TOS in a new window
- [x] Associate user with the chosen program.
- [x] Set "agreed to TOS" field to true when the user returns from logging in to edX
- [x] Clicking outside the modal dismisses it

TOS Design:

![tos 2x](https://cloud.githubusercontent.com/assets/430126/18009731/911f8b7c-6b7b-11e6-8ab9-187ffb9326ab.png)

**Comment by pdpinch** [comment]
use material-design-lite or react, whichever is faster

**Comment by aliceriot** [comment]
@pdpinch I'm going to break the ToS page into a separate story and do that first.

**Comment by aliceriot** [comment]
@pdpinch should the new terms of service page be done in React or just using a django template? what url should it live at? I think before we used `/terms_of_service` or something.

**Comment by pdpinch** [comment]
The user isn't logged in at this point, so my assumption was that it would just be a django template, but whatever is fastest is OK. 

I agree, I think it was at /terms_of service

**Comment by aliceriot** [comment]
yep, just looked here: f1f4922d5e18fbfec894fd17477d38c40c1c5601 and that's correct.

**Comment by aliceriot** [comment]
@pdpinch do we have an asset for the edx logo?

**Comment by aliceriot** [comment]
also for the MIT logo

**Comment by aliceriot** [comment]
another question: in the dropdown on the homepage, what programs should I provide options for right now? Just SCM and Economics?

**Comment by pdpinch** [comment]
Re: https://github.com/mitodl/micromasters/issues/917#issuecomment-243857442 -- the current live programs should be available from the CMS in the template. Can you use those instead of hard-coding? 

Re: https://github.com/mitodl/micromasters/issues/917#issuecomment-243848679 -- MIT Logos are available from http://mit.edu/graphicidentity/download-logos.html ([zip file](https://web.mit.edu/graphicidentity/download/logo-sets/MIT-logos-web.zip)) but @roberthouse54 may have one already. 

Re: https://github.com/mitodl/micromasters/issues/917#issuecomment-243847475 -- edX logos are available from https://www.edx.org/media-kit ([zip file](https://www.edx.org/sites/default/files/mediakit/image/thumb/edx20logo20and20style20guidelines.zip)), but again it may be easier to ask @roberthouse54

**Comment by aliceriot** [comment]
are you able to download that zip file from MIT? I get an 'insecure connection' error in chrome :(

**Comment by roberthouse54** [comment]
Here are the images
![edx_logo](https://cloud.githubusercontent.com/assets/20047260/18142344/1f521ff0-6f8b-11e6-8b4d-8ae8b97c5f39.png)
![mit_logo](https://cloud.githubusercontent.com/assets/20047260/18142343/1f51396e-6f8b-11e6-972e-fab41a645fe7.png)

**Comment by aliceriot** [comment]
:100:

**Comment by aliceriot** [comment]
ok, so this is a technical question, and I think I'm just having trouble figuring out what's going on in the django / edX end of things.

How should I preserve the user's selection from the home page? If they pick e.g. SCM that value should be set, I think, automatically as soon as we get the redirect from edX, once they've signed in.

Is there a way I can get arbitrary url parameters that edX will pass through? I tried to read through our code to see if we're doing anything like this, but couldn't really find anything.

**Comment by aliceriot** [comment]
this is what the dialog looks like rn:

![signup](https://cloud.githubusercontent.com/assets/6207644/18179491/9b20bb80-7050-11e6-8b5c-7d00daf04c9f.png)

**Comment by noisecapella** [comment]
I feel like there's some way to tell django-social-auth to include extra args at runtime, and then have edX send it back to us in the query argument when they redirect back to us. If that doesn't work, we should just store the information in localStorage IMO

**Comment by noisecapella** [comment]
Maybe it would be easiest just to do localStorage right now, then we can investigate using query arguments at some point later if we have time

**Comment by aliceriot** [comment]
Ok, I'm more asking how to accomplish that with django-social-auth, haha.

for `localStorage`, do you mean just stick the program into `localStorage`, and then check in there when we `PATCH` the profile later?

**Comment by pdpinch** [comment]
I suspect localStorage will be simpler, since we don't have to muck with OAuth configuration. Are there any downsides to localStorage?

**Comment by aliceriot** [comment]
well strictly speaking it doesn't accomplish this: "Set "agreed to TOS" field to true when the user returns from logging in to edX"

**Comment by aliceriot** [comment]
or wait nvm not that one :p

**Comment by aliceriot** [comment]
I meant that we wouldn't set the program until the user updates their profile, unless we wanted to check for the value in `localStorage` when the JS app boots and, if it's there, `PATCH` the profile right away.

**Comment by noisecapella** [comment]
Basically what @aliceriot said. Also we need to be careful about the state of data in localStorage, since the user can't just fix problems by refreshing their browser. And they would need to do the checkout flow in a single browser, which doesn't seem too much to ask

**Comment by pdpinch** [comment]
Looking around a bit, it appears that there is a parameter in OAuth called state that is (sort of) designed for this purpose. You pass it and the OAuth identity provider returns it unmodified. I'm trying to find some authoritative docs.

**Comment by noisecapella** [comment]
Yeah, I looked at `EdxOrgOAuth2` and there's a `REDIRECT_STATE = False`. It looks like there's a method we can override `auth_extra_arguments` to send the data

**Comment by noisecapella** [comment]
Actually if we turn on `REDIRECT_STATE` and set the relevant `..._AUTH_EXTRA_ARGUMENTS` setting I think we can pass the arguments to the login URL as GET params: http://django-social-auth.readthedocs.io/en/latest/configuration.html#extra-arguments-on-auth-processes

**Comment by aliceriot** [comment]
ok i'll give that a go then

**Comment by pdpinch** [comment]
I'm not sure how that can work, but it seems worth trying...

**Comment by aliceriot** [comment]
I have the `localStorage` approach mostly working, fwiw
