### ISSUE TITLE
Program Pages: Faculty profile widget

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#923]
Update the program page template to include a carousel of faculty profiles

![image](https://cloud.githubusercontent.com/assets/430126/18010516/d8c128fc-6b7e-11e6-8cad-6dc3adf60e69.png)
[InVisionapp mockup](https://projects.invisionapp.com/share/NB7VM1GSG#/screens/182565886)
# Depends on:

- #924 : Allow program owners to add/update faculty profiles

# Acceptance criteria 

- [ ] Display faculty name/title, bio and image
- [ ] no autoplay
- [ ] test and plan for at least 2 faculty members

**Comment by pdpinch** [comment]
I updated the description with the current design. FYI @roberthouse54

**Comment by Ferdi** [comment]
Why are we limiting to 3 ?

**Comment by pdpinch** [comment]
We're not limited to 3. It's just 3 per row. I updated the description yesterday, but if it's not clear feel free to change it.

**Comment by Ferdi** [comment]
How it will look like if you have 4 ?   - I liked the carusel better.

**Comment by pdpinch** [comment]
@roberthouse54

**Comment by roberthouse54** [comment]
OK, we can switch it back to the carousel, but I think it is going to be tricky to get it right.
