### ISSUE TITLE
Dashboard: update to match design

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#925]
Should look like this:

![mm_dashboard 2x](https://cloud.githubusercontent.com/assets/430126/18012133/2d7d4694-6b86-11e6-93d2-c4add1304746.jpg)

Not like this:

![image](https://box.everhelper.me/attachment/559111/eb68aeb9-7366-4cd9-9ed9-edae1a1b5a5a/623857-O2nYtnYzIAku0OV3/screen.png)

Here is a complete set of course states:

![course_statuses 2x](https://cloud.githubusercontent.com/assets/430126/18178388/1caecd22-704c-11e6-9328-1c7fab19b421.png)

# Acceptance Criteria:

- [x] Match design
- [x] Remove histogram widget
- [x] Remove tab navigation
- [x] Fix Firefox CSS issue (#780) 
- [ ] each course state implemented

# Related Issues:

- Learners near me widget (#600)
- Context Switch (#796)
- Financial Aid links, if program has financial aid option #937
- Display course prices (requires API update) #938
- Dashboard: Display multiple runs of the same course #939
- Dashboard: Update progress widget to work with program context #941

**Comment by pdpinch** [comment]
I updated the description with a screenshot of all course states. It seems likely this is more than 2 points now.

**Comment by pdpinch** [comment]
Amir is going to start to work on the following issues:

- [ ] Remove histogram widget
- [ ] Remove tab navigation
- [ ] Fix Firefox CSS issue (#780)

**Comment by amir-qayyum-khan** [comment]
sure

**Comment by noisecapella** [comment]
I made issues for the remaining work to be done and assigned the stories to myself. See #1015 for the issues
