### ISSUE TITLE
Sign-up: Update UX and styling for screen 3  - Professional

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#930]
# Acceptance Criteria:

- [ ] defaults cards to nothing selected
- [ ] clicking yes will show the pop-up 
- [ ] hide yes/no option when an entry is added; 
- [ ] when all entries are deleted, the yes/no option should return
- [ ] styling fixes

Should look like this:

![sign_up_3 2x](https://cloud.githubusercontent.com/assets/430126/18037976/df0adf6a-6d5d-11e6-9d44-3cb8f83c695c.png)

**Comment by gsidebo** [comment]
@roberthouse54 @pdpinch: the education tab changes ( #929 ) specify this: "defaults cards to nothing selected". this one says the default should be "No". are we OK with that difference?

**Comment by pdpinch** [comment]
@gsidebo sorry for the late reply. Professional should be the same as Education. We changed our minds on Education, but I didn't update this issue. It's updated now.

**Comment by pdpinch** [comment]
@gsidebo have you started this?
