### ISSUE TITLE
Search: Courses facet 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#933]
![image](https://cloud.githubusercontent.com/assets/20047260/20535693/dfc1c45c-b0b3-11e6-864d-decd45cfe97e.png)

Clicking on a course filters by that course, and shows all users who are currently taking the course, or who have taken the course in the past.

## Acceptance Criteria:

- [ ] Add courses to elastic search index
- [ ] The courses facet is the first facet
- [ ] This will be an "and" facet, so users can only choose one of the items from the list. 
- [ ] It will include all the courses (not course runs) in the current program. 
- [ ] If possible, sort by course order

In later issues we want to expand an area under the course name, with 2 additional facets: the "Grade" facet (#1711), which filters by the grade in that course, and the status facet (#1730), which allows users to filter by whether the student has paid for the course or is auditing.

## See Also

#1710 semester facet
#1711 grade facet
#1730 status facet

**Comment by roberthouse54** [comment]
<img width="700" alt="upload" src="https://cloud.githubusercontent.com/assets/20047260/20190174/5e2c9444-a74e-11e6-8b74-3c947a89cbef.png">

Clicking on a course filters by that course, and also expands an area under the course name, with 2 additional facets: the "Grade" facet (#1711), which filters by the grade in that course, and the status facet (#1730), which allows users to filter by whether the student has paid for the course or is auditing.

**Comment by pdpinch** [comment]
Integrated Rob's comment into the description. 

I'll delete these comments next.

**Comment by pdpinch** [comment]
Add a course to the index for each learner. Include the most recent grade (current or final) the learner earned.

**Comment by gsidebo** [comment]
@pdpinch @roberthouse54 are there any invision links for this?

**Comment by roberthouse54** [comment]
There is this: https://invis.io/E49IZSEWM#/202316455_Learner_Search

**Comment by gsidebo** [comment]
@roberthouse54 @pdpinch a couple questions: 

1. Do we only want to show *currently* enrolled students? Do we want to count students who were enrolled in the course previously and passed?
1. Is it a requirement to show 'empty' courses (ie: courses that have no students enrolled)? It may reduce complexity if we don't have that requirement

**Comment by roberthouse54** [comment]
1. No, we want to show both currently enrolled students, and students who were enrolled in previous runs of the course... including students who enrolled and failed or passed.
2. I am a bit unclear on this one. I feel that we should show all the courses in the program, whether or not there are any enrolled students. But I think it should be rare that there are no enrolled students in a course.

**Comment by pdpinch** [comment]
1. I agree with Rob. 
2. Keep it simple. If it's easier to not display "empty" courses, let's leave them out. If users wants that, they'll let us know & we can decide at that time.
