### ISSUE TITLE
Learners search for learners

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#935]
As a learner, I would like to find out more about other learners in my program and contact them individually. 

The learner will discover this feature via the "learners near me" widget in the learner dashboard. The learner can explore further via the learner search for learners features -- which is similar to the instructor search except that it doesn't include grades or grade facets, nor the ability to send bulk e-mail. 

Learners search for learners:

![learner_search_for_learners 2x](https://cloud.githubusercontent.com/assets/430126/18038718/8136822a-6d69-11e6-80eb-e89a94e71fbe.png)
# Acceptance Criteria:
- [ ] /learners route should return a 403
- [ ] separate learner view of search results: similar to instructor search but without grades
- [ ] breadcrumb navigation so learner can return to dashboard

Related Issues:
-  #943 : Learners should be able to e-mail other learners
- “Learners near me” widget on dashboard (US #600)

**Comment by roberthouse54** [comment]
An open question is what search facets we want to show to learners. I think we should show the following:

Course
Semester
Residence

We might also want to show:

Country of Birth
Field of Study
School
Industry
Company

Others?

**Comment by pdpinch** [comment]
I think those first 3 make a good MVP. 

I think Industry and Company would be useful, when they're implemented.

**Comment by roberthouse54** [comment]
This feature allows regular users to search for other learners, and send them messages. For V1 we will display a subset of the filters available to Admins, specifically:

Course
Semester
Current Residence

From this page, we will allow users to send individual messages to other learners. TBD -  We may also allow users to send group messages to a filtered list of users.

![image](https://cloud.githubusercontent.com/assets/20047260/21397747/eea26bcc-c772-11e6-8073-5ebf98bd7b42.png)

**Comment by pdpinch** [comment]
The repeated "Send Message" button is kind of chunky and repetitive. Can we put a mail icon on the user chip?

**Comment by roberthouse54** [comment]
![image](https://cloud.githubusercontent.com/assets/20047260/21431627/f6192fb2-c835-11e6-9ce4-1e4af6d991f1.png)

**Comment by gsidebo** [comment]
Stray thought: one-way emailing has made sense thus far because it has only been available for instructors emailing learners. That is much more likely to be a one-way messaging scenario. If learners are emailing each other, it's much more likely that they want to have a two-way conversation. If a learner receives a message from another learner with the current setup, they will have to go into the dashboard, search for that user, and send a one-way message back to them. That will, of course, ignore any message history. We should seriously consider bumping up the priority of two-way messaging/message threading if we want to have learners emailing each other

**Comment by gsidebo** [comment]
How do users access this search page? Is there a link from the dashboard or something? The issue description says this:

> The learner will discover this feature via the "learners near me" widget in the learner dashboard.

...but I feel like that can't be right. This feature does not implement "learners near me" as I understood it. The Course and Semester facets, for example, have nothing to do with a learner being near you.

**Comment by roberthouse54** [comment]
In my opinion, we should add navigation at the point we implement this feature. So basically, a tab or something similar.

**Comment by Ferdi** [comment]
@gsidebo @roberthouse54  OK, but this issue is about having a page where learners search for learners.  Messaging and how to get the the page are only related issues.

P.S @gsidebo 
>  If a learner receives a message from another learner with the current setup, they will have to go into 
>  the dashboard
Or they hit reply on their email client :-)

**Comment by roberthouse54** [comment]
The simplest thing is to just have navigation to the page, because users may want to get to this feature without going through the dashboard to do so.

**Comment by gsidebo** [comment]
@roberthouse54 I'm going to start looking at this, but I still don't know how learners are going to get to this search page. I've seen some mocks with a search tab, but I don't see any issues for implementing that tab for learners. I'm happy to move ahead with this and just create a new URL route (let's say `/dashboard/search`), but if there is no green-lit issue for implementing the actual navigation to this page, we should probably get on it

**Comment by roberthouse54** [comment]
Yes, agreed. There is a new design for navigation here: https://projects.invisionapp.com/d/#/console/8032462/212190604/preview

We could probably add tabs, which would be quicker way of getting a basic nav setup. So the tabs would be Dashboard, and Learners.

**Comment by pdpinch** [comment]
This will need to respect the learner's setting for whether their profile is shared with other learners.

**Comment by roberthouse54** [comment]
I rewrote this ticket as #2512 . Closing this issue.
