### ISSUE TITLE
Settings: Update styling

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#936]
Update setting styling to match current design:

Should be like:

![settings 2x](https://cloud.githubusercontent.com/assets/430126/18038838/9f579252-6d6a-11e6-9a86-88eb4376e369.png)

Not like:

![image](https://box.everhelper.me/attachment/560189/eb68aeb9-7366-4cd9-9ed9-edae1a1b5a5a/623857-xfgS7W1qDcLXnOpd/screen.png)

# Acceptance criteria:

- [x] remove tab navigation
- [x] remove avatar header
- [x] separate content into two distinct cards

**Comment by amir-qayyum-khan** [comment]
Fixed via https://github.com/mitodl/micromasters/pull/1014
