### ISSUE TITLE
Personalized Pricing: add section to dashboard, when required by programs

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#937]
Not all programs offer personalized pricing. This text box should only be displayed for those that do. 

![image](https://cloud.githubusercontent.com/assets/430126/18365843/450e71dc-75e2-11e6-8b6d-00a8ccc4363a.png)

# Acceptance Criteria:

- [x] Display the cost calculator box when the program offers personalized pricing

# Related Issues:

- #998 Course price calculator

**Comment by pdpinch** [comment]
Need to add boolean to program indicating whether the program offers personalized pricing. 

Since this is the only program, we can hard code the minimum price.

**Comment by pdpinch** [comment]
@aliceriot can you move this to "in progress" since you're working on it (and have a PR open)?
