### ISSUE TITLE
Dashboard: Display multiple runs of the same course

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#939]
This is a lower priority issue because it may be some time before we have multiple runs of courses available in the MicroMasters programs. 

The relevant cases are (see [Google Doc](https://docs.google.com/document/d/1C8JwVxLW0YZBAFwUR06754uz-uyCCEbnvt2TIMJtKk0/) for screenshots): 

### Missed Deadline to Pay

![image](https://cloud.githubusercontent.com/assets/430126/18767163/9d737458-80eb-11e6-9f10-24e298e9a422.png)

If the user has missed the payment deadline, they will not be able to get MicroMasters credit for the course. We show them the “re-enroll” UI, the same as if they have failed.

### Failed Course

![image](https://cloud.githubusercontent.com/assets/430126/18856931/6c045dfc-842d-11e6-9e35-010487009df2.png)

If the user has failed, the course status in the right column changes to “Failed”. We then display the “Re-enroll” UI, same as if the user was auditing a course but missed the Payment Due date.

### Failed Course - Enrollment Not Open

![image](https://cloud.githubusercontent.com/assets/430126/18856938/783918a6-842d-11e6-96cb-74f606362884.png)

If the user has failed, but the enrollment is not open, we display this status.

### Failed Course - No Future Course Runs are defined

![image](https://cloud.githubusercontent.com/assets/430126/18856940/82c70a6c-842d-11e6-87e4-33f4db7b1563.png)

This course status is a combination of “Failed” and “No Future Runs defined”

### Multiple Past Course runs

![image](https://cloud.githubusercontent.com/assets/430126/18857006/42ad4b8e-842e-11e6-9979-2e0f1ebc69ca.png)

This mock shows the UI when a user has multiple completed past course runs.

### Re-Enrolled

![image](https://cloud.githubusercontent.com/assets/430126/18856994/192a5888-842e-11e6-8143-77d1b855c100.png)

After the student has re-enrolled, either after failing a course, or for any other reason, the current run is displayed at the top, like normal, and any “Completed Runs” are displayed below, in gray boxes.

**Comment by roberthouse54** [comment]
See: https://invis.io/6N8H0EBFG
