### ISSUE TITLE
Configure google analytics

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#94]
This can be configured using the GA_TRACKING_ID environment variable

**Comment by pdpinch** [comment]
The tracking ids are in https://github.com/mitodl/micromasters/issues/45

**Comment by bdero** [comment]
It looks like there are two IDs listed: One for CI and one for Release. Should I use the micromasters-ci tracking ID for RC as well? @pdpinch

**Comment by pdpinch** [comment]
Sorry for the delayed reply. Yes, please use the UA code for CI on both CI and RC.

**Comment by pdpinch** [comment]
I'm seeing pageviews on GA for /dashboard/
