### ISSUE TITLE
Dashboard: Add tooltip with personal pricing info 

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#940]
Depends on #937 

<img width="485" alt="screen shot 2016-09-09 at 9 42 43 am" src="https://cloud.githubusercontent.com/assets/430126/18389011/d6ad5146-7671-11e6-96d2-2161d85dbe63.png">

# Acceptance Criteria

- [ ] tool tip icon is only displayed for courses that offer personalized pricing
- [ ] Need to get text from DEDP program

**Comment by pdpinch** [comment]
@roberthouse54 do we still have a need for this tooltip?
