### ISSUE TITLE
Dashboard: Update progress widget to work with program context

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#941]
The number of completed courses and the total number of courses in the progress widget should update when the user switches program contexts. 

Depends on #796 

<img width="241" alt="screen shot 2016-08-22 at 3 28 27 pm" src="https://cloud.githubusercontent.com/assets/430126/17868570/57cc9046-687d-11e6-9cd6-87d2874649ff.png">

# related issue

- Update circle

**Comment by pdpinch** [comment]
@noisecapella is the program context in the dashboard done enough for this issue to be started?

**Comment by noisecapella** [comment]
Yes, the only part left for the program context is unrelated to this work
