### ISSUE TITLE
Learners should be able to e-mail other learners

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#943]
Send single e-mail, to one user, from the current user. 

![image](https://cloud.githubusercontent.com/assets/430126/18056404/b7c814be-6dd9-11e6-8545-eb94e963ac5e.png)

![image](https://cloud.githubusercontent.com/assets/430126/18038756/f4d49898-6d69-11e6-8635-3ced0e9b4301.png)
# Acceptance Criteria:
- [ ] Button on user chip to send message
- [ ] modal for composing e-mail
- [ ] connect to mail API to send mail

**Comment by pdpinch** [comment]
replaced by #2196
