### ISSUE TITLE
CMS: update program thumbnails, description and link

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#944]
Program teams need to be able to update the program thumbnail (within design guidelines), program description, and the program page link on the MicroMasters home page.  

![image](https://cloud.githubusercontent.com/assets/430126/18387240/7c51f7a4-7669-11e6-89cd-66129a412141.png)

# Acceptance criteria

- [ ] CMS editors can change this data via the CMS, although it's [stored in the courses model currently](https://github.com/mitodl/micromasters/blob/master/courses/models.py#L10-L19). 
- [ ] CMS editors are given some guidelines on thumbnails so they aren't too large and fit the design

# Related issues

- [ ] #919 update home page template

**Comment by pdpinch** [comment]
We will drop the blurb for now and stick to using the total of courses.

**Comment by Ferdi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xDyB1JyO&#x2F;1-test"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> test</a>

**Comment by Ferdi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xDyB1JyO&#x2F;1-test"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> test</a>

**Comment by Ferdi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xDyB1JyO&#x2F;1-test"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> test</a>

**Comment by pdpinch** [comment]
Update the screenshot and the description to remove references to the blurb, which is no longer CMS-modifiable.

**Comment by noisecapella** [comment]
@roberthouse54 What dimensions should we require for the program thumbnail?

**Comment by noisecapella** [comment]
I'm going to avoid any template changes since they'll be handled in #919, other than the resolution change
