### ISSUE TITLE
MIT Micromasters graphics

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#95]
We should create graphics for the MIT Micromasters logo, see:
https://projects.invisionapp.com/share/KR6FYCZTX#/screens/142338434

**Comment by pdpinch** [comment]
![logo-micromasters](https://cloud.githubusercontent.com/assets/430126/14188673/d11a4d0e-f757-11e5-96bf-c4c1456a4e56.png)
![logo-micromasters 2x](https://cloud.githubusercontent.com/assets/430126/14188672/d11906c4-f757-11e5-8640-c3fa2df8395a.png)
