### ISSUE TITLE
add link to home page to terms of service page

### ISSUE THREAD

**Issue by aliceriot** [mitodl/micromasters#954]
should have been done for #951

**Comment by Ferdi** [comment]
Thanks @aliceriot .  And what's the reason we are not showing the user dropdown menu, if the user is logged in ?

**Comment by aliceriot** [comment]
The user dropdown menu is written in React, we could show it as well but I think it would be a separate story.

**Comment by aliceriot** [comment]
(we'd need to do a little hacking basically)

**Comment by pdpinch** [comment]
This new TOS work is part of the Sign Up story (#917) so in the most common case, users won't be logged in when they view this.

**Comment by Ferdi** [comment]
@pdpinch we will probably have a link to tos somewhere in the front page too.
