### ISSUE TITLE
Remove CyberSource

### ISSUE THREAD

**Issue by noisecapella** [mitodl/micromasters#963]
We should remove the CyberSource-related code, leaving the ecommerce parts which we still need for ecommerce

**Comment by Ferdi** [comment]
@noisecapella we definitely want to get back to accepting payment , when edx enrollment API allows us to enroll users as verified-id.  Knowing that , does it make sense to remove the code or somehow disable this feature.

**Comment by noisecapella** [comment]
I think we should remove it. We still have it in git, we can add it back later when we have an immediate use of it.

**Comment by Ferdi** [comment]
sounds good.

**Comment by pdpinch** [comment]
Looks like we'll be keeping Cybersource
