### ISSUE TITLE
Home: mailchimp signup needs to use https

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#965]
It works on the current marketing site, because that's only on http

```
jquery-2.2.0.min.js:4 Mixed Content: The page at 'https://micromasters-ci.herokuapp.com/' was loaded over HTTPS, but requested an insecure script 'http://facebook.us6.list-manage.com/subscribe/post-json?u=ad81d725159c1f322…ersity+or+educational+institution&MMERGE4=&MMERGE3=MIT+ODL&_=1472821806637'. This request has been blocked; the content must be served over HTTPS.send @ jquery-2.2.0.min.js:4ajax @ jquery-2.2.0.min.js:4(anonymous function) @ jquery.ajaxchimp.js:120dispatch @ jquery-2.2.0.min.js:3r.handle @ jquery-2.2.0.min.js:3
jquery.ajaxchimp.js:126 mailchimp ajax submit error: error
```

The code in question is here: https://github.com/mitodl/micromasters/blob/536a36729e633979bccc1f3d30c23298213de4c4/static/js/public.js#L71

**Comment by pdpinch** [comment]
I was also thrown off by the `facebook` in the URL. I'll have to check with marketing (@mariaODL) to see if we're hitting the right endpoint at mailchimp.

**Comment by pdpinch** [comment]
@annagav can you fix this too. If you want to do it as part of #1035 that's fine. Or it can be separate.

**Comment by annagav** [comment]
@pdpinch, where can I reproduce the bug?
