### ISSUE TITLE
Update realistic user generation to create program enrollments

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#967]
Realistic user generation no longer creates program enrollments now that we're creating program enrollments directly instead of via signals (PR #964)

**Comment by pdpinch** [comment]
@amir-qayyum-khan can you work on this?

**Comment by amir-qayyum-khan** [comment]
@gsidebo what do you mean by that?
you are saying after you run command, you use enroll created student manually and you want to put this feature in command, so that program create user as well as enroll.

**Comment by gsidebo** [comment]
this is done, actually. i must have forgotten to link to this issue in the PR. sorry for the confusion!
