### ISSUE TITLE
Production error monitoring

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#980]
Given the complexity of the sign-on flow, we should have some monitoring in production to detect and log repeated API errors -- whether they come from one of the MIcroMasters APIs or edX.

**Comment by Ferdi** [comment]
@blarghmatey can you update description/stuatus / what needs to be done ?

**Comment by blarghmatey** [comment]
I am setting up Sentry to aggregate and monitor exceptions from the app. I will also add calls at integration points to alert on failed requests to edX API endpoints so that we can trigger threshold alerts on multiple failures.

**Comment by pdpinch** [comment]
I'm also concerned about failures on internal API requests (i.e. between the front-end and the backend), like the one we saw today. Can we track those as well?

**Comment by blarghmatey** [comment]
Issues with internal API requests will be tracked by Sentry.
