### ISSUE TITLE
(Bug) Graduation date year field in education form is slow

### ISSUE THREAD

**Issue by gsidebo** [mitodl/micromasters#985]
On the Education page of the signup flow, editing the "Graduation Date" year field is very slow. The response to input is significantly slower than other text inputs. Possibly significant: each character entered appears to trigger an UPDATE_PROFILE action

![year_field_slowness](https://cloud.githubusercontent.com/assets/14932219/18286313/27eda9f4-7440-11e6-9828-c54d73a259e3.gif)

**Comment by noisecapella** [comment]
`UPDATE_PROFILE` is triggered every time a textfield is edited, it shouldn't be that slow though. Does the School Name field have the same behavior?

**Comment by gsidebo** [comment]
nope. the year field is the only one in the modal that seems to have this problem. it may also exist in the Employment form (i just haven't tested it) and the month field (but it wouldn't be so noticeable since it's just 1 or 2 characters)

**Comment by aliceriot** [comment]
I wonder if this is because of the validation code? That's definitely pretty different between the date and non-date fields.

**Comment by aliceriot** [comment]
It is the validation code!
