### ISSUE TITLE
Personalized Pricing: Course price calculator

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#988]
Learners submit minimal information to find out their personal course price. Low income learners in developing countries and high income learners in developed countries will get an immediate answer and can pay for courses right away. Learners who don't get an immediate response will be asked to upload documentation that will be reviewed by MIT. 

When the review process is complete (either automated or manual), the learner's price on the dashboard will be updated to reflect the personal pricing. 

Form:

![image](https://cloud.githubusercontent.com/assets/430126/18394151/7d748b2a-7686-11e6-8095-592c72d12b62.png)

If an immediate response is possible & no further documentation required:

![image](https://cloud.githubusercontent.com/assets/430126/18394174/98882264-7686-11e6-8112-d6f71e440d87.png)

If further documentation is required:

![image](https://cloud.githubusercontent.com/assets/430126/18394191/ae6db9fe-7686-11e6-8e0c-7378aac47b11.png)

# Acceptance Criteria

## build form
- [ ] form appears in modal.
- [ ]  User cannot change country of residence. 
- [ ] Currency is pre-selected to match country of residence but can be changed. 
- [ ] Validate User enters annual income as a number (not a range). 

## calculate price
- [ ] convert currency to dollars
- [ ] look-up discount based on income; use country to determine whether more documentation required

## API (now part of #1041)
- On clicking calculate, the app determines if an immediate response is possible, or if further documentation is required.
- All user submissions and system decisions are logged for later audit

## Update dashboard after calculation
- [ ] Immediate response: new price is stored and displayed.
- [ ] More documentation required: user is given form for uploading docs, see story #989 
- [ ] In all future sessions, the user is given their personalized price

# Related Issues:

- ~~Personalized Pricing: add section to dashboard, when required by programs #937~~ 
- Personalized Pricing: Learner uploads supporting documents #989

**Comment by pdpinch** [comment]
We can store the income thresholds in a look up table so it's possible to update them if/when necessary.

**Comment by pdpinch** [comment]
fixer.io REST API for currency conversions

**Comment by aliceriot** [comment]
https://openexchangerates.github.io/money.js/

**Comment by aliceriot** [comment]
this too: https://openexchangerates.github.io/accounting.js/

**Comment by pdpinch** [comment]
This issue is being replaced by a few smaller issues:

#1076 Allow learners to bypass financial aid & pay full price
#1097 Financial Aid: Cost Calculator
#1044 Approved requests
#1098 Documents required for verification
#1100 Docs reviewed and approved / rejected

**Comment by pdpinch** [comment]
Removed related issue from description about uploading documents.

**Comment by patcon** [comment]
Did this ever get implemented?
