### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#99]
Add a logout link to the user menu that links to the logout endpoint.

**Comment by noisecapella** [comment]
While you're working with the logout React element, can you also fix this warning:

Failed propType: The prop 'id' is required to make 'Dropdown' accessible for users using assistive technologies such as screen readers
Check the render method of `Uncontrolled(Dropdown)`.

**Comment by pdpinch** [comment]
That's interesting -- what generates that warning?

**Comment by aliceriot** [comment]
@noisecapella cool, I can take care of that.

@pdpinch looks like the component requires a particular prop (`id`) for accessibility and we're not passing it. do you mean where does the warning show up?

**Comment by noisecapella** [comment]
@pdpinch propTypes are a React feature to verify that certain props are present and of the correct types (ie, asserts). I guess `Dropdown` makes use of the id attribute to let screen readers know what to call it
