### ISSUE TITLE
Personalized Pricing: staff interface for reviewing learners submitted docs

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#990]
![financial_aid_8 2x](https://cloud.githubusercontent.com/assets/430126/18360874/cb3814da-75cd-11e6-8684-05e1a9af2d47.jpg)

# Acceptance Criteria

- [ ] limit access to staff in the appropriate program
  - [ ] User authenticated via OAuth with edX, same as learners
  - [ ] authorization managed through roles, same as for learner search
- [ ] display row per user 
- [ ] filter based on submission status: pending, approved, rejected, auto-approved
- [ ] Clicking "View Documents" downloads a zip file of all documents that have been submitted
  - [ ] logs the download of documents and which user initiated it
- [ ] Clicking the checkmark updates the student's state to approved and: 
  - [ ] updates student's course price for this program
  - [ ] notifies the student via e-mail & logs the e-mail
  - [ ] logs the decision and which user made it
- [ ] Clicking the X button updates the student's state to rejected and:
  - [ ] updates student's course price for this program (to the max for their country)
  - [ ] notifies the student via e-mail & logs the e-mail
  - [ ] logs the decision and which user made it
- [ ] Clicking the e-mail button opens an e-mail modal (similar to ...) 
  - [ ] from address on e-mail is a ZenDesk account
  - [ ] logs the sending of e-mail
- [ ] Clicking name sorts by learner's last name, then first name
- [ ] Clicking location sorts by country, region, city 
- [ ] pagination works
- [ ] Users aren't added to the pending list until they've uploaded documents & clicked submit

# Related Issues

- #937 
- #940 
- #988 
- #989

**Comment by pdpinch** [comment]
Replaced by #1045
