### ISSUE TITLE
Personalized Pricing: Payment / Coupons management

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#991]
After a learner has received his financial aid results (either an immediate, automatic reply, or an approval for a reduced price), they need to be directed to a coupon link they can use to complete the purchase at edx.org. 

We will get coupons in advance from edX for the courses in question, for a fixed set of discounts. 

# Acceptance criteria

- [ ] A way to upload coupon codes (could be API POST, or management command, or...)
- [ ] A way to set SKUs for courses (SKUs come from edx)
- [ ] Learner is linked to appropriate coupon URL when clicking enroll or upgrade, using a combination of coupon code and SKU
- [ ] Log which coupon the user is given 
- [ ] When a coupon is given to a user, don't give it to another user

# Out of scope

- Update the database when a coupon is used

**Comment by pdpinch** [comment]
Updated the description with acceptance criteria. Still needs screenshots?

**Comment by pdpinch** [comment]
We will need to plan ahead for provisioning coupons to make sure we don't run out when users enroll.

**Comment by pdpinch** [comment]
The edX coupons are all discount coupons. They can be a percentage off, or a fixed dollar discount. We need to decide which we prefer. The test coupons that I have generated on 9/11 are percent off.

**Comment by pdpinch** [comment]
Sample coupon csv export from edX's ecommerce system. (Contact @pdpinch if you need something that works)

| Code                             | Coupon Name               | Maximum Coupon Usage | Redemption Count | Coupon Type | URL                                                    | Catalog Query  | Course Seat Types | Client | Category             | Note | Price | Invoiced Amount | Discount Percentage | Discount Amount | Status | Order Number | Redeemed By Username | Redeemed For Course ID | Created By  | Create Date | Coupon Start Date | Coupon Expiry Date | Email Domains |
|----------------------------------|---------------------------|----------------------|------------------|-------------|--------------------------------------------------------|----------------|-------------------|--------|----------------------|------|-------|-----------------|---------------------|-----------------|--------|--------------|----------------------|------------------------|-------------|-------------|-------------------|--------------------|---------------|
| This row applies to all vouchers | DEDP MicroMasters 80% off |                      |                  |             |                                                        | number:14.73x* | verified          | mitx   | Financial Assistance |      |       |                 |                     |                 |        |              |                      |                        | Peter Pinch | 12-Sep-16   | 1-Sep-16          | 31-Dec-16          |               |
| 3xxxxxxxxxxxxxxV                 |                           | 1                    | 0                |             | https://ecommerce/coupons/offer/?code=3xxxxxxxxxxxxxxV |                |                   |        |                      |      |       |                 |                     |                 | Active |              |                      |                        |             |             |                   |                    |               |
| 3xxxxxxxxxxxxxxV                 |                           | 1                    | 0                |             | https://ecommerce/coupons/offer/?code=3xxxxxxxxxxxxxxV |                |                   |        |                      |      |       |                 |                     |                 | Active |              |                      |                        |             |             |                   |                    |               |

**Comment by pdpinch** [comment]
Executive decision from today: we won't be using coupons.

Instead we'll handle transactions in the MM portal. Fulfillment will be an automatic enrollment into an audit track at edx.org plus a registering for a MM certificate to be granted when all courses and exams are passed.
